### ISSUE TITLE
<atomic>: Remove workarounds for LLVM-46595

### ISSUE THREAD

**Issue by CaseyCarter** [microsoft/STL#1018]
LLVM-46595 requests support in Clang to mirror MSVC's addition of `_InterlockedMeow64` intrinsics in x86 mode. The bug has been fixed on trunk, so we can remove our workarounds in `<atomic>` when we update our required Clang version (presumably) to LLVM 11.

**Comment by StephanTLavavej** [comment]
Wow, https://github.com/llvm/llvm-project/commit/82206e7fb49d9593d946599b107e8a8ad29a7d22 was implemented incredibly quickly - thank you @topperc! :smile_cat:

**Comment by StephanTLavavej** [comment]
The MSVC compiler had to revert its addition of the intrinsics due to compatibility with the Win8.1 SDK, so we're simply going to avoid them for all compilers. :crying_cat_face:
