### ISSUE TITLE
Status Chart: Track the combined age of the PR backlog

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#1043]
Suggested by @AlexGuteniev: https://github.com/microsoft/STL/issues/921#issuecomment-658064093

Tracking the size of the PR backlog is useful, but its age is another important dimension. (If we had 200 PRs open at any given time, but PRs spent no more than 1 month being reviewed, that would be amazing.) Among the possible options:

* **Max age** seems minimally informative and useful; it would ignore everything that's happening except for the oldest PR. Working on the oldest PR is important, but not necessarily all-important.
* **Average age** (whether mean or median) seems like a misleading metric. An influx of new PRs would lower the average age, but would be "more work", so that's the wrong direction.
* **Total age** seems to capture the essence of how the PR backlog weighs on my mind. It increases N days per day, and newly opened PRs don't immediately improve or harm the metric, they just cause it to increase faster. Merging an old PR is then "rewarded" in proportion to its age, which feels right. Merging a bunch of new PRs at least limits the growth rate.

This information is within my newfound power as a JavaScript programmer to gather. :smiley_cat:

I think it will need to be a separate chart (on the same page), though - the units are completely different from the existing lines, and the line will behave differently too.

**Comment by cbezault** [comment]
This might be beyond your JS abilities right now but I think the salient metric is total number of days since a maintainer posted a review with changes requested (or if it's a new PR days since creation).

This is just a variant of your "total age" option which I agree seems the most useful of the above metrics.

**Comment by StephanTLavavej** [comment]
That appears to be doable (with significantly more logic). I see how to list PR reviews, and I believe I see how to query whether a user is a member of the vclibs team. I'll probably explore that after getting the chart initially working. Thanks!
