### ISSUE TITLE
<atomic>: Improvements to atomic::wait

### ISSUE THREAD

**Issue by BillyONeal** [microsoft/STL#1047]
This item tracks pending design change requests against https://github.com/microsoft/STL/pull/593, which was landed before these were fixed to unblock other PRs' progress

- [ ] Delete spinning from headers and only do that in the separately compiled bits where necessary
- [ ] Use the `SRWLOCK` and `CONDITION_VARIABLE` implementation for the "indirect" case instead of trying to build a bespoke thing, which gets us out of the business of most tunable parameters.
- [ ] Change timeouts in the DLL interface to speak `FILETIME` (because that is what `QueryUnbiasedInterruptTime` and the rest of the platform native scheduler timers speak)

**Comment by BillyONeal** [comment]
@AlexGuteniev How do you feel about passing `DWORD milliseconds` instead of `FILETIME` and then `__std_atomic_wait_direct` can use a weak symbol alias to real WaitOnAddress?

**Comment by AlexGuteniev** [comment]
I'm fine if you want this way. But I don't see it as extremely useful thing to alias real `WaitOnAddress`. For `WakeByAddress*` notifies make more sense.

Do you mean alias can be done not only on ARM?

**Comment by BillyONeal** [comment]
>But I don't see it as extremely useful thing to alias real WaitOnAddress. For WakeByAddress* notifies make more sense.

Hmmm that's a good point. Although if I can't alias both of them I don't want to do either to leave our options open vis a vis ABI.

>Do you mean alias can be done not only on ARM?

It can also be done for `_ONECORE` / `_CRT_APP`. Kernel32 of course can not.

**Comment by AlexGuteniev** [comment]
Initially my concern was that with locked ABI you cannot take advantage of better instructions/APIs. Say, if vNext is for next 10 years, I would want precision increase possibility.

The decision to break exactly the way I did was for efficient use of current milli precision, along with access to nano. I don't mind `FILETIME` too.

If you want to break ABI more often, say in 2-3 years, then maybe `DWORD` is the best way to go, even if not using `aliasobj`

**Comment by AlexGuteniev** [comment]
> unblock other PRs' progress

Anyone works on semaphores or barriers?

**Comment by AlexGuteniev** [comment]
> * Use the `SRWLOCK` and `CONDITION_VARIABLE` implementation for the "indirect" case

I would then prefer having another export that exposes this pair for contention table. And to make it the same for `atomic_ref`. 
This helps using the same lock for atomicity of non-lock-free `atomic_ref` and its notifying `CONDITION_VARIABLE`, which I think would be more optimal (less locks to acquire) and more safe (less locks - less troubles with deadlocks)

**Comment by AlexGuteniev** [comment]
Did
 - Delete spinning from headers and only do that in the separately compiled bits where necessary
 - Use the `SRWLOCK` and `CONDITION_VARIABLE` implementation for the "indirect" case instead of trying to build a bespoke thing, which gets us out of the business of most tunable parameters.

in the main PR

Did not do this
 -  Change timeouts in the DLL interface to speak `FILETIME` (because that is what `QueryUnbiasedInterruptTime` and the rest of the platform native scheduler timers speak)

Not sure now if it was a good idea at all. probably just passing milliseconds and aliasing would be better.
I recalled that 100ns APIs have varying precision, depending on other function calls, so they would violate least surprise principle.

**Comment by BillyONeal** [comment]
>Not sure now if it was a good idea at all. probably just passing milliseconds and aliasing would be better.

The idea here was to allow passing this value as a plain `long long` rather than passing pointers to structs, particularly with unused fields, around.

I am completely OK with only offering ms precision; after all the scheduler usually operates with 16ms granularity anyway.
