### ISSUE TITLE
<iomanip>: std::get_time doesn't work as intended

### ISSUE THREAD

**Issue by fsb4000** [microsoft/STL#1054]
**Command-line test case**
```
#include <cassert> 
#include <iomanip> 
#include <sstream>

void readTime(
    char const* str,
    char const* format,
    std::tm* time)
{
    std::istringstream is{ str };
    is >> std::get_time(time, format);
}

int main()
{
    {
        std::tm time{};
        readTime("2016-12-31", "%Y-%m-%d", &time);
        // All pass. 
        assert(time.tm_year == 2016 - 1900);
        assert(time.tm_mon == 12 - 1);
        assert(time.tm_mday == 31);
    }

    {
        std::tm time{};
        readTime("20161231", "%Y%m%d", &time);
        // All fail. 
        assert(time.tm_year == 2016 - 1900);
        assert(time.tm_mon == 12 - 1);
        assert(time.tm_mday == 31);
    }
}
```

**Expected behavior**
Asserts should not fail.

**STL version**
    Microsoft Visual Studio Community 2019 
    Version 16.6.4

**Additional context**
See also: [VSO-257790](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/257790) | [DevCom-140618](https://developercommunity.visualstudio.com/content/problem/140618/meow.html) [DevCom-9505](https://developercommunity.visualstudio.com/content/problem/9505/meow.html)

From https://github.com/microsoft/STL/issues/939

And actually it seems like duplicate of the bug: https://github.com/microsoft/STL/issues/944

**Comment by StephanTLavavej** [comment]
Aha, thanks for finding the duplicate! I agree that the repro is exactly the same for the failing case, so I'll close this and link up the other one.
