### ISSUE TITLE
<filesystem>: Use of std::filesystem::path causes link error on UWP(already fixed)

### ISSUE THREAD

**Issue by fsb4000** [microsoft/STL#1069]
**Describe the bug**
Use of std::filesystem::path causes link error on UWP

**Command-line test case**
```
1. Create default UWP C++ Project.
2. Add /std:c++17  flag
3. Add
#include <filesystem>
static auto myPath = std::filesystem::path("anyDir") / std::filesystem::path("anyFile.txt");
```

**Expected behavior**
Should work.  
Actually it works.
![test](https://i.imgur.com/3Du6rHE.png)
The bug is already fixed: https://github.com/microsoft/STL/issues/322

**STL version**
 Microsoft Visual Studio Community 2019
 Version 16.6.4

**Additional context**
See more: [VSO-718901](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/718901) / [AB#718901](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/718901) |  [DevCom-369081](https://developercommunity.visualstudio.com/content/problem/369081/meow.html)

**Comment by StephanTLavavej** [comment]
Thanks for verifying that this was indeed fixed. (Apparently there was a second error that vanished, probably due to WinSDK updates; I've never known how to build UWP projects so I *really* appreciate your work here!) I've resolved the DevCom and VSO bugs accordingly.
