### ISSUE TITLE
<deque>: deque should support incomplete value types

### ISSUE THREAD

**Issue by tuccio** [microsoft/STL#108]
**Describe the bug**
Due to these two lines, deque cannot be used without the definition of the element type:
https://github.com/microsoft/STL/blob/ee1ede2c6207fb2be2c870bcddf67c48d9d32a24/stl/inc/deque#L250
https://github.com/microsoft/STL/blob/ee1ede2c6207fb2be2c870bcddf67c48d9d32a24/stl/inc/deque#L593

Seems unnecessary, since the enumerator doesn't seem to be referenced anywhere in the codebase.

**Command-line test case**
STL version (git commit or Visual Studio version):
ee1ede2c6207fb2be2c870bcddf67c48d9d32a24

```
#include <deque>

class foo
{
    foo();
    foo(const foo&) = delete;
    foo(foo&&) = delete;
    foo& operator=(const foo&) = delete;
    foo& operator=(foo&&) = delete;

    ~foo();

    struct impl;
    std::deque<impl> m_impl;
};

```

```
c:\Users\Davide\Desktop>cl repro.cpp
Microsoft (R) C/C++ Optimizing Compiler Version 19.21.27702.2 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

repro.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.21.27702\include\deque(606): error C2027: use of undefined type 'foo::impl'
repro.cpp(13): note: see declaration of 'foo::impl'
repro.cpp(14): note: see reference to class template instantiation 'std::deque<foo::impl,std::allocator<_Ty>>' being compiled
        with
        [
            _Ty=foo::impl
        ]
```

**Expected behavior**
I would expect it to be pimpl-friendly just like other stl implementations: https://godbolt.org/z/JNqc_R

**Comment by BillyONeal** [comment]
This is moving away from the direction we need for Concepts. :(

**Comment by StephanTLavavej** [comment]
The Standard does not require deque to support incomplete value types. I believe we should resolve this as an out-of-scope extension request.

**Comment by frederick-vs-ja** [comment]
@tuccio `_EEN_DS` is not used in the code base, but used in STL.natvis.

@StephanTLavavej I guess the one reason why the Standard doesn't required `deque` to support incomplete element types is that "MSVC STL perfers to perserve some compile-time constants for debugger visualization on `std::deque`" (as said in WG21-N3890). The other reason is that libc++ can't do this without breaking ABI.

However, I found that `sizeof(value_type) <= 1 ? 16 : ...` can be evaluated already in the debugger visualizer in VS2019 (at least 16.11, perhaps 16.0 is also OK). If we move the whole expression into STL.natvis and remove the `_EEN_DS` mechanism (alongwith related `constexpr` variables, but turn some into `constexpr` functions), then MSVC STL's `deque` can also support incomplete element types.
