### ISSUE TITLE
Encouraging Contributors to Code Review

### ISSUE THREAD

**Issue by mnatsuhara** [microsoft/STL#1097]
It can sometimes take time for maintainers to review a PR, and if a PR goes through several iterations of maintainer review, the lifetime of the PR is extended even further.  If contributors are willing to review PRs, it can oftentimes accelerate the review process as it allows the PR to be in a more finished state before maintainers review, and fewer maintainer review iterations are needed.  It has always been appreciated when contributors are willing to review each others' PRs, but this has not been explicitly said anywhere.  

We should make this clear on the wiki or in the README so contributors may be more comfortable reviewing open PRs.

**Comment by KishkinJ10** [comment]
sir can I work on this?? I am a beginner.

**Comment by KishkinJ10** [comment]
Sir I have made a PR on this . I am a beginner sir Please check it.
