### ISSUE TITLE
P0340R3 SFINAE-Friendly underlying_type

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#11]
[P0340R3](https://wg21.link/P0340R3) SFINAE-Friendly `underlying_type`

**Comment by SuperWig** [comment]
Is this something that can be applied to all modes or does it need `_HAS_CXX20`?

**Comment by CaseyCarter** [comment]
Unconditional implementation seems fine: this defines behavior that was previously undefined, so an implementation of C++20 `underlying_type` is also a conforming implementation of C++17 `underlying_type`.

> e.g. quoting the standard "Mandates: T is not an incomplete enumeration type."

There's not much to do; we dispatch directly to a compiler intrinsic, and the compiler generally issues the diagnostic for an incomplete type. (Although to my understanding C1XX currently treats all enumeration types as complete: https://godbolt.org/z/VkcENq.)

**Comment by StephanTLavavej** [comment]
I agree that this one should be unconditional.

**Comment by SuperWig** [comment]
> There's not much to do; we dispatch directly to a compiler intrinsic, and the compiler generally issues the diagnostic for an incomplete type. (Although to my understanding C1XX currently treats all enumeration types as complete: https://godbolt.org/z/VkcENq.)

The reason I ask is because there's comments for `common_reference` of a similar manner
```
// N4810 [meta.trans.other]/5.3.5: "Otherwise, there shall be no member type."
```
