### ISSUE TITLE
Itanium support?

### ISSUE THREAD

**Issue by AlexGuteniev** [microsoft/STL#1106]
As old .cpp files should support Windows XP, and Windows XP and its immediate successor Winows 2003 had Itanium version, I'm asking, if some parts should also support Itanium

**Comment by CaseyCarter** [comment]
https://docs.microsoft.com/en-us/cpp/overview/supported-platforms-visual-cpp?view=vs-2019 doesn't even have a column to indicate our lack of support, so no: I don't think any parts of this library should support Itanium.

**Comment by StephanTLavavej** [comment]
Yep, the toolset dropped IA-64 support many years ago.
