### ISSUE TITLE
implement usleep shim and sys/time.h header

### ISSUE THREAD

**Issue by KOLANICH** [microsoft/STL#111]
**Describe the bug**
Some apps use this API call. Unfortunately it is not available in MSVC standard lib. When making one app buildable with msvc I had to implement it myself.

```c++
void usleep(DWORD waitTimeMicroseconds) {
	LARGE_INTEGER pliTimeout;
	pliTimeout.QuadPart = waitTimeMicroseconds / 100;
	NtDelayExecution(FALSE, &pliTimeout);
}
```

1. Is it a correct impl? If it isn't, is it a suitable shim?
2. Would you add it into this stdlib?

**Comment by MikeGitb** [comment]
So,  you want the msvc standard library to implement all the various posix APIs. Wouldn't that be a task more suited for the windows team?

**Comment by StephanTLavavej** [comment]
Like #112, this is out-of-scope. We are implementing the C++ Standard Library here, not a POSIX layer.

**Comment by KOLANICH** [comment]
IDK. Are Windows SDKs produced by Windows team? Will they be published under a free license too?

**Comment by StephanTLavavej** [comment]
Yes, the Windows division maintains the Windows SDK. You’ll have to ask them about any plans for open sourcing. (The Windows Feedback Hub is probably the correct way to do so.)
