### ISSUE TITLE
Issues needed for skipped libcxx tests 

### ISSUE THREAD

**Issue by MahmoudGSaleh** [microsoft/STL#1114]
The set of skipped libcxx tests in [`tests/libcxx/skipped_tests.txt`](https://github.com/microsoft/STL/blob/master/tests/libcxx/skipped_tests.txt) contain a number of tests skipped due to STL bugs that have no corresponding GitHub issues. The set of such bugs is included under `# *** STL BUGS ***`.

We need to open a new GitHub issue for each of the ones below (or link to one if already exists). In addition to clear title, description, test case and expected behavior, we need to add skipped test information in the additional context, so it can be enabled once the bug is fixed. The first two, GH-1112 and GH-1113, can be used as examples. 

:heavy_check_mark: Issue Filed
===
* [x] GH-1112 
https://github.com/microsoft/STL/blob/06827feb4cdc4d2328dfbfab9fd5302de6058dd9/tests/libcxx/expected_results.txt#L550-L551

* [x] GH-1113
https://github.com/microsoft/STL/blob/06827feb4cdc4d2328dfbfab9fd5302de6058dd9/tests/libcxx/expected_results.txt#L553-L555

* [x] GH-1256
https://github.com/microsoft/STL/blob/06827feb4cdc4d2328dfbfab9fd5302de6058dd9/tests/libcxx/expected_results.txt#L557-L560

* [x] GH-1004
https://github.com/microsoft/STL/blob/06827feb4cdc4d2328dfbfab9fd5302de6058dd9/tests/libcxx/expected_results.txt#L562-L563

* [x] GH-942
https://github.com/microsoft/STL/blob/06827feb4cdc4d2328dfbfab9fd5302de6058dd9/tests/libcxx/expected_results.txt#L572-L574

* [x] GH-942 
https://github.com/microsoft/STL/blob/06827feb4cdc4d2328dfbfab9fd5302de6058dd9/tests/libcxx/expected_results.txt#L576-L581

* [x] GH-1006
https://github.com/microsoft/STL/blob/06827feb4cdc4d2328dfbfab9fd5302de6058dd9/tests/libcxx/expected_results.txt#L586-L589

* [x] GH-1259
https://github.com/microsoft/STL/blob/06827feb4cdc4d2328dfbfab9fd5302de6058dd9/tests/libcxx/expected_results.txt#L591-L594

* [x] GH-1116
https://github.com/microsoft/STL/blob/06827feb4cdc4d2328dfbfab9fd5302de6058dd9/tests/libcxx/expected_results.txt#L634-L635

* [x] GH-1190
https://github.com/microsoft/STL/blob/06827feb4cdc4d2328dfbfab9fd5302de6058dd9/tests/libcxx/expected_results.txt#L637-L638

* [x] GH-757
https://github.com/microsoft/STL/blob/06827feb4cdc4d2328dfbfab9fd5302de6058dd9/tests/libcxx/expected_results.txt#L640-L642

* [x] GH-784 
https://github.com/microsoft/STL/blob/06827feb4cdc4d2328dfbfab9fd5302de6058dd9/tests/libcxx/expected_results.txt#L644-L645

* [x] GH-1260
https://github.com/microsoft/STL/blob/06827feb4cdc4d2328dfbfab9fd5302de6058dd9/tests/libcxx/expected_results.txt#L565-L566

* [x] GH-1261
https://github.com/microsoft/STL/blob/06827feb4cdc4d2328dfbfab9fd5302de6058dd9/tests/libcxx/expected_results.txt#L583-L584

* [x] GH-1264
https://github.com/microsoft/STL/blob/06827feb4cdc4d2328dfbfab9fd5302de6058dd9/tests/libcxx/expected_results.txt#L631-L632

* [x] GH-1275
https://github.com/microsoft/STL/blob/06827feb4cdc4d2328dfbfab9fd5302de6058dd9/tests/libcxx/expected_results.txt#L599-L629

:smile_cat: Fixed
===
* [x] GH-940
https://github.com/microsoft/STL/blob/06827feb4cdc4d2328dfbfab9fd5302de6058dd9/tests/libcxx/expected_results.txt#L568-L570

**Comment by AlexGuteniev** [comment]
* [x] GH-940
```
 # STL bug: Missing <valarray> assignment operators.
 
 std/numerics/numarray/template.mask.array/mask.array.assign/mask_array.pass.cpp FAIL
 
 std/numerics/numarray/template.slice.array/slice.arr.assign/slice_array.pass.cpp FAIL
 ```

 * [x] GH-942
```
# STL bug: VSO-207715 We reject array<NoDefault, 0>.
 
 std/containers/sequences/array/array.cons/implicit_copy.pass.cpp FAIL
 
 std/containers/sequences/array/array.cons/initialization.pass.cpp FAIL
 
 std/containers/sequences/array/array.data/data_const.pass.cpp FAIL
 
 std/containers/sequences/array/array.data/data.pass.cpp FAIL
 
 std/containers/sequences/array/iterators.pass.cpp FAIL
 ```

**Comment by AlexGuteniev** [comment]
Also GH-442, I've added to additional context
```
 # STL bug: We allow fill() and swap() for array<const T, 0>.
 
 std/containers/sequences/array/array.fill/fill.fail.cpp FAIL
 
 std/containers/sequences/array/array.swap/swap.fail.cpp FAIL
```

**Comment by AlexGuteniev** [comment]
* [x] GH-1004
```
 # STL bug: regex_traits::transform() isn't following the Standard.
 
 std/re/re.traits/transform.pass.cpp FAIL
 ```

**Comment by AlexGuteniev** [comment]
* [x] GH-1006
https://github.com/microsoft/STL/blob/06827feb4cdc4d2328dfbfab9fd5302de6058dd9/tests/libcxx/expected_results.txt#L586-L589

**Comment by MahmoudGSaleh** [comment]
Thanks @AlexGuteniev. I've added your issues numbers.

**Comment by AlexGuteniev** [comment]
Does it make sense to label as libcxx_skip GH-940?
The bug is fixed, and the skip lines are removed already

**Comment by MahmoudGSaleh** [comment]
> Does it make sense to label as libcxx_skip [GH-940](https://github.com/microsoft/STL/issues/940)?
> The bug is fixed, and the skip lines are removed already

The issue is closed as well. It did affect it at some point in time, so this is only for historical record. I've marked it fixed in the comment

**Comment by fsb4000** [comment]
* [x]  [GH-1116](https://github.com/microsoft/STL/issues/1116)
 https://github.com/microsoft/STL/blob/06827feb4cdc4d2328dfbfab9fd5302de6058dd9/tests/libcxx/expected_results.txt#L634-L635

**Comment by AlexGuteniev** [comment]
-  [x] GH-1190 
https://github.com/microsoft/STL/blob/06827feb4cdc4d2328dfbfab9fd5302de6058dd9/tests/libcxx/expected_results.txt#L637-L638

**Comment by fsb4000** [comment]
* [x]  [GH-1256](https://github.com/microsoft/STL/issues/1256)
https://github.com/microsoft/STL/blob/06827feb4cdc4d2328dfbfab9fd5302de6058dd9/tests/libcxx/expected_results.txt#L557-L560

**Comment by StephanTLavavej** [comment]
Thanks @fsb4000 - updated above!

**Comment by fsb4000** [comment]
* [x]  [GH-1259](https://github.com/microsoft/STL/issues/1259)
https://github.com/microsoft/STL/blob/06827feb4cdc4d2328dfbfab9fd5302de6058dd9/tests/libcxx/expected_results.txt#L591-L594

**Comment by fsb4000** [comment]
* [x]  [GH-1260](https://github.com/microsoft/STL/issues/1260)
https://github.com/microsoft/STL/blob/06827feb4cdc4d2328dfbfab9fd5302de6058dd9/tests/libcxx/expected_results.txt#L565-L566

**Comment by fsb4000** [comment]
* [x]  [GH-1261](https://github.com/microsoft/STL/issues/1261)
https://github.com/microsoft/STL/blob/06827feb4cdc4d2328dfbfab9fd5302de6058dd9/tests/libcxx/expected_results.txt#L583-L584

**Comment by StephanTLavavej** [comment]
Updated, thanks yet again @fsb4000 :rocket:

**Comment by fsb4000** [comment]
* [x]  [GH-1264](https://github.com/microsoft/STL/issues/1264)
https://github.com/microsoft/STL/blob/06827feb4cdc4d2328dfbfab9fd5302de6058dd9/tests/libcxx/expected_results.txt#L631-L632

**Comment by StephanTLavavej** [comment]
`while (true) { thanks(@fsb4000); }`

**Comment by fsb4000** [comment]
* [x]  [GH-1275](https://github.com/microsoft/STL/issues/1275)
https://github.com/microsoft/STL/blob/06827feb4cdc4d2328dfbfab9fd5302de6058dd9/tests/libcxx/expected_results.txt#L599-L629

**Comment by StephanTLavavej** [comment]
All done! Thanks @fsb4000 and @AlexGuteniev!
