### ISSUE TITLE
<system_error>: error_category's default ctor isn't constexpr. 

### ISSUE THREAD

**Issue by fsb4000** [microsoft/STL#1116]
**Describe the bug**
error_category's default ctor isn't constexpr. 

**Command-line test case**
```
C:\Temp>type test.cpp
#include <system_error>
#include <type_traits>
#include <string>
#include <cassert>


class test1
    : public std::error_category
{
public:
    constexpr test1() = default;  // won't compile if error_category() is not constexpr
    virtual const char* name() const noexcept {return nullptr;}
    virtual std::string message(int) const {return std::string();}
};

int main(int, char**)
{
    static_assert(std::is_nothrow_default_constructible<test1>::value,
                                 "error_category() must exist and be noexcept");

  return 0;
}
C:\Temp>cl /EHsc /W4 /WX  /std:c++latest test.cpp
Оптимизирующий компилятор Microsoft (R) C/C++ версии 19.27.29109 для x64
(C) Корпорация Майкрософт (Microsoft Corporation).  Все права защищены.

/std:c++latest предоставляется как предварительная версия языковых функций из последнего
рабочего черновика C++. Мы приветствуем сообщения об ошибках и предложения к улучшению.
Однако обратите внимание, что эти функции предоставляются как есть, без поддержки и могут
измениться или быть удалены по мере развития рабочего черновика. Дополнительные сведения:
https://go.microsoft.com/fwlink/?linkid=2045807.

test.cpp
Microsoft (R) Incremental Linker Version 14.27.29109.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:test.exe
test.obj
C:\Temp>.\test.exe
```

**Expected behavior**
Should not compile now and should compile when error_category constructor will be constexpr

**STL version**
    ```
    Microsoft Visual Studio Community 2019 Preview
    Version 16.7.0 Preview 6.0
    ```
**Additional context**
https://github.com/microsoft/STL/blob/06827feb4cdc4d2328dfbfab9fd5302de6058dd9/tests/libcxx/expected_results.txt#L634-L635

https://github.com/llvm/llvm-project/blob/master/libcxx/test/std/diagnostics/syserr/syserr.errcat/syserr.errcat.nonvirtuals/default_ctor.pass.cpp

https://github.com/microsoft/STL/blob/e000d3feaf6acaf6214aedcfa21de483931ccbb7/stl/inc/system_error#L70

**Comment by StephanTLavavej** [comment]
@frederick-vs-ja's #3139 has fixed this except for `/clr:pure`, so we can go ahead and close this. :tada: (Everything mentioning `/clr:pure` will be eradicated during vNext, and as long as we don't break code that currently works with it, nobody cares about this mode.)
