### ISSUE TITLE
<deque>: erase with two iterators invokes move / move_backward when the range is empty

### ISSUE THREAD

**Issue by Bekenn** [microsoft/STL#1118]
https://github.com/microsoft/STL/blob/4e97255b3595a01f5268b98fad397e8579d14ed2/stl/inc/deque#L1295

This runs counter to the preconditions on `std::move`, which requires that the destination iterator is outside the source range.

**Comment by CaseyCarter** [comment]
Ugh. We self-move-assign every element in the shorter of `[begin(), x)` or `[x, end())` when someone calls `erase(x, x)`.

**Comment by Bekenn** [comment]
Yup.  Looks like vector used to have the same issue, but was fixed some time back.
