### ISSUE TITLE
Implement unistd.h

### ISSUE THREAD

**Issue by KOLANICH** [microsoft/STL#112]
Some apps rely on it. Lack of this header makes some apps unbuildable with MSVC without using third-party shims.

**Comment by sylveon** [comment]
This header is used to provide access to a POSIX API but Windows is not a POSIX operating system.

**Comment by KOLANICH** [comment]
It is not, hutnit would be good to have this header since lot of open-source software depends on it.

**Comment by StephanTLavavej** [comment]
This is out-of-scope. Please see README.md; we are focused on implementing the C++ Standard, not POSIX.
