### ISSUE TITLE
<bit>: Test _Countl_zero_bsr() internal helper

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#1120]
Recommended by @barcharcraz in https://github.com/microsoft/STL/pull/1108#discussion_r463279067 .

After merging #1108, `<bit>` is going to have an internal helper `_Countl_zero_bsr()` for x86/x64 that's active only for very old processors; therefore it will receive no regular testing, although it is necessary for correctness. While we've manually tested it for this PR, we should investigate adding automated testing by directly calling the helper (which we generally avoid doing, but this merits a special exception).

**Comment by AlexGuteniev** [comment]
I think a better alternative would be to have a fixture  via force include, similar to this one:
https://github.com/microsoft/STL/blob/4e97255b3595a01f5268b98fad397e8579d14ed2/tests/std/include/force_include.hpp

It would add `__isa_available = 0` (and `__isa_enabled=0` on x86) in constructor of  a static variable.

It would participate in test matrix.

A way to build such matrix for `<bit>` tests should be found, it will also be useful in the context of #954 resolution
