### ISSUE TITLE
<iostream> : When a double-width characters in cout, blank output without permission.

### ISSUE THREAD

**Issue by fsb4000** [microsoft/STL#1122]
**Describe the bug**
When the full-width character is output in cout, blank is output without permission

**Command-line test case**
```
C:\Temp>type main.cpp
//  file encoding: utf-8 or Shift JIS
#include <iostream> 
#include <cstdlib>
using namespace std;

int main()
{ 
	system("chcp 932 > NUL"); // system("chcp 65001 > NUL");
	cout << "あいうえお" << endl;
}

C:\Temp>cl /EHsc /W4 /WX /utf-8 main.cpp
or
C:\Temp>cl /EHsc /W4 /WX main.cpp
Оптимизирующий компилятор Microsoft (R) C/C++ версии 19.27.29109 для x64
(C) Корпорация Майкрософт (Microsoft Corporation).  Все права защищены.

main.cpp
Microsoft (R) Incremental Linker Version 14.27.29109.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:main.exe
main.obj

C:\Temp>main.exe
あいうえお
```

**Expected behavior**
Should print without additional spaces. 
Actually it works. I can't reproduce the bug. 
Works for both utf-8 and Shift JIS.

![test](https://i.imgur.com/gqmdzAo.png)

**STL version**
    ```
    Microsoft Visual Studio Community 2019 Preview
    Version 16.7.0 Preview 6.0
    ```

**Additional context**
[VSO-441122](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/441122) / [AB#441122](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/441122) | [DevCom-59694](https://developercommunity.visualstudio.com/content/problem/59694/meow.html)

**Comment by fsb4000** [comment]
wcout and L"str" also works fine:
![utf8](https://i.imgur.com/Spkn6jE.png)

**Comment by fsb4000** [comment]
If you will test too, check that your cmd font is NSimSun or MSGothic.
The examples don't work with Lucida Console or Consolas fonts.

![font](https://i.imgur.com/jLZQ3S8.png)

**Comment by fsb4000** [comment]
I see. Unicode symbols fits '2 spaces' in console. and ansi symbols fits 1 space.
The issue is better shown even for Cyrylic symbols :)

```
#include <iostream> 
#include <cstdlib>
using namespace std;

int main()
{ 
	system("chcp 65001 > NUL");
	cout << "ABABABABAB\n"; // English
	cout << "あいうえお\n";
	cout << "АВАВАВАВАВ\n"; // Russian
}
```
![test](https://i.imgur.com/C0caTJp.png)

**Comment by StephanTLavavej** [comment]
Thanks @cpplearner and @fsb4000! I've resolved the DevCom bug with links to your analysis and screenshots.
