### ISSUE TITLE
Intermittent failures due to build agent starvation probably caused by multithreaded tests

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#1149]
The test infrastructure relies on an Azure DevOps "build agent" that needs CPU cycles, otherwise the test run will fail. The test infrastructure tries to be polite by running only N - 2 tests simultaneously:

https://github.com/microsoft/STL/blob/b74b6188b233cce0647950d7fd6bbbb3bd3744f0/azure-devops/run-build.yml#L57

However, we have tests that are themselves multithreaded, and it appears that this can stress the machine enough to starve the build agent and cause a failure.

Possible solutions:
* Mark multithreaded tests with magic comments, and teach the test infrastructure to run them sequentially. (May not help if the test in isolation is sufficiently stressful.)
* Set the tests to run at low priority, so that the build agent at normal priority gets the cycles it needs.
  + `std`'s force-include mechanism is tempting, but we need to be careful about dragging in Windows.h
  + It appears that Python can manipulate process priority
  + Is the priority of compilation also a problem?

**Comment by AlexGuteniev** [comment]
I guess tests run in their own job, including compilation. 
If they aren't they should.
`SetInformationJobObject` + `JOBOBJECT_BASIC_LIMIT_INFORMATION::Affinity` - set it the way to exclude 1st core

**Comment by StephanTLavavej** [comment]
Happily, we haven't seen sporadic failures of this nature in a very long time. Sometimes VMs get taken away from us (as we use spot VMs), but we've stopped seeing VMs running with unresponsive build agents. (It's possible that the build agent code was updated to be more robust, e.g. running at higher priority.)
