### ISSUE TITLE
CMakeLists.txt: VCLIBS_SUFFIX should be a cache variable

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/STL#115]
Simply:

https://github.com/microsoft/STL/blob/7f65140761947af4ed7f9dfc11adee8c86c9e4c2/CMakeLists.txt#L15

should be a cache variable so that users might be able to change it via the cmake command line. 

e.g. something like:
`set(VCLIBS_SUFFIX "_oss" CACHE STRING "Additional suffix appended to build dlls to not conflict with the one the OS or other applications uses.")`

**Comment by BillyONeal** [comment]
I'm assigning this to me but if someone wants to make a PR for it before I get there feel free.

**Comment by bhardwajs** [comment]
I can work on this one as well. Unless someone beats me to it :)

**Comment by StephanTLavavej** [comment]
Sounds good to me!
