### ISSUE TITLE
MSVC can't detect three way operator of int and double

### ISSUE THREAD

**Issue by hewillk** [microsoft/STL#1154]
https://godbolt.org/z/9qWhGd

```
template <typename T, typename U, typename = void>
struct is_three_way_comparable : std::false_type {};
template <typename T, typename U>
struct is_three_way_comparable<T, U, std::void_t<decltype(std::declval<T>() <=> std::declval<U>())>> : std::true_type {};

static_assert(is_three_way_comparable<double, int>());
```

Could not pass the static_assert, this seems weird.

**Comment by CaseyCarter** [comment]
This isn't an appropriate place to report compiler bugs - we only take blame for STL bugs here ;) A compiler bug like this should be reported at https://developercommunity.visualstudio.com/, and indeed [this one has already been reported](https://developercommunity.visualstudio.com/content/problem/1044530/long-double-works-but-not-in-a-concept.html). Feel free to upvote that report to help the compiler devs prioritize bugfixing.
