### ISSUE TITLE
<yvals_core.h>: _HAS_CONDITIONAL_EXPLICIT breaks clang/pyside in C++ 17 mode

### ISSUE THREAD

**Issue by ArcEarth** [microsoft/STL#1155]
**Describe the bug**
Clang-8 (Pyside) failed to parse STL headers like `<utility>` or `<tuple>` because `_HAS_CONDITIONAL_EXPLICIT` was incorrectly reported for Clang in C++ 17 mode.

**Command-line test case**
```
C:\Temp>type repro.cpp
#include <yvals_core.h>

#if _HAS_CONDITIONAL_EXPLICIT
namespace foo{
    template <typename... Args>
    class tuple {
        explicit(sizeof...(Args) == 1)
        tuple(Args&&...) {}
    };
}
#endif

C:\Temp>clang -std=c++14 .\repro.cpp
```

**Expected behavior**
Macro `_HAS_CONDITIONAL_EXPLICIT` should be defined to `0` on Clang unless `__cpp_conditional_explicit` is defined.

**STL version**
    ```
    Microsoft Visual Studio Professional 2019
    Version 16.7.0
    ```

    ```
    https://github.com/microsoft/STL/commit/e000d3feaf6acaf6214aedcfa21de483931ccbb7
    ```

**Comment by miscco** [comment]
The STL is quite aggressive in setting the minimum requirements for supported compilers.

So currently clang 10 is required as far as I know.

**Comment by miscco** [comment]
See 

https://github.com/microsoft/STL/blob/master/stl/inc/yvals_core.h#L495-L509

**Comment by ArcEarth** [comment]
Hmm, that is quite aggressive... Update clang-tools like PySide(Qt) can have quite different schedule than updating visual studio in my organization...
Anyway, this can be solved by adding defines on our side.

**Comment by StephanTLavavej** [comment]
It is indeed quite aggressive, as C++ is adding features at a rapid pace, and supporting older compilers is enormously time-consuming. For that reason, we support only the latest production release of Clang, increasing our required version as soon as the next one is available in the VS Installer.
