### ISSUE TITLE
<valarray>: magic static

### ISSUE THREAD

**Issue by AlexGuteniev** [microsoft/STL#1169]
**Describe the bug**
valarray potentially uses magic static

**Command-line test case**
```
#include <string>
#include <iostream>
#include <valarray>

int main()
{
	std::valarray<std::string> a{"strings", "are", "numeric", "types"};
	std::valarray<std::string> b = a.shift(2);
	for (std::string s : b) {
		std::cout << s << " ";
	}
}
```

**Expected behavior**
It works as expected. 
But in C++17 where `std::string` constructor is not `constexpr` it should rely on magic static in debug mode:
https://github.com/microsoft/STL/blob/e000d3feaf6acaf6214aedcfa21de483931ccbb7/stl/inc/valarray#L353

**STL version**
https://github.com/microsoft/STL/commit/e000d3feaf6acaf6214aedcfa21de483931ccbb7

**Additional context**
Probably not a real problem, only from lawyering point of view.

**Comment by StephanTLavavej** [comment]
`_Ty{}` might or might not be ideal here (because it would theoretically construct, move-assign, and destroy), but I would expect to see an ordinary local variable otherwise.

**Comment by AlexGuteniev** [comment]
I'd expect `_Construct_in_place(_Myptr[_Idx]);`

**Comment by AlexGuteniev** [comment]
Actually figured it out. Yes, `_Construct_in_place`, but no, don't need to call it.
It was already called, since a new `valarray` for destination is created.

**Comment by AlexGuteniev** [comment]
Yeah,
```C++
    _NODISCARD valarray shift(int _Count) const {
        const size_t _Size = size();
        valarray<_Ty> _Ans(_Size);
        const size_t _Min = (_Count < 0) ? static_cast<size_t>(-_Count) : 0;
        const size_t _Max = (_Count > 0) ? _Size - static_cast<size_t>(_Count) : _Size;
        for (size_t _Idx = _Min; _Idx < _Max; ++_Idx) {
            _Ans[_Idx] = _Myptr[_Idx + _Count];
        }
        return _Ans;
    }
```
Was it ever worth to encapsulate a cryptic ternary into a mighty macro?
