### ISSUE TITLE
CMakeLists.txt: Activate FrameHandler4

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#118]
https://github.com/microsoft/STL/blob/7f65140761947af4ed7f9dfc11adee8c86c9e4c2/CMakeLists.txt#L66-L67

We should be able to remove this escape hatch, which should slightly reduce the size of our binaries on x64.

**Comment by BillyONeal** [comment]
I asked Modi and Kirsten if we still need the escape hatch.

**Comment by BillyONeal** [comment]
Modi says:

>How does the STL pick up vcruntime? As long as the satellite DLL is available you can build with FH4 enabled.

**Comment by StephanTLavavej** [comment]
AFAIK we're an ordinary consumer of VCRuntime, so `vcruntime140_1.dll` should be available normally.

**Comment by BillyONeal** [comment]
That's my understanding as well. I'd be willing to bet the situation in our old build system was because that was shut off for the whole "crt" directory.
