### ISSUE TITLE
Update OS minimum version and remove XP runtime detection

### ISSUE THREAD

**Issue by AlexGuteniev** [microsoft/STL#1192]
Currently STL has to target Vista as minimum OS version for x86 and x64

Update `filesystem.cpp`
https://github.com/microsoft/STL/blob/87dc1d3383a052216822fab1a37c8fe2794b0cdb/stl/src/filesystem.cpp#L56-L99

Update awint.hpp / winapisupp.cpp

*Note*: the ABI compatibility for XP toolset should stay. The XP toolset should build; it just doesn't need to support Windows XP anymore.

**Comment by StephanTLavavej** [comment]
We definitely have to be extra-careful about preserving ABI compatibility here. Our object files, static libraries, import libraries, and DLLs don't have to worry about running on XP anymore, but we can't change any data structure representations that would be visible across boundaries, can't remove DLL exports, and can't alter DLL export behavior. Changing the version defined in `CMakeLists.txt` is the scariest in this sense - we would need to verify every possible effect it has. Altering individual functions (e.g. in `winapisupp.cpp`) is much easier to reason about.

There is also an argument that this isn't worth the effort and risk for the remaining life of v19.

**Comment by AlexGuteniev** [comment]
Removed `CMakeFile.txt` reference.
On the contrary, it is little performance thing: call by stored pointer invokes control flow guard overhead, whereas call by import address table does not.

**Comment by StephanTLavavej** [comment]
That's a good point - both perf and code size (customers *love* code size improvements and that is worth some level of effort / risk).

**Comment by MikeGitb** [comment]
Any chance Vista support will be dropped for VNEXT considering that market share for vista seems to be even lower than XP (not sure how reliable those online market share statistics at statcounter of netmarketshare are)?

**Comment by AlexGuteniev** [comment]
Dropping Vista enables only one static import, though an important one: `TryAcquireSRWLockExclusive`

**Comment by sylveon** [comment]
Might as well go for supported operating systems only and target 8+ as minimum ;)

**Comment by MikeGitb** [comment]
> In more serious talk, I don't think the STL team can make that decision - it's the VS team which will decide the minimum supported OS.

This wasn't meant as a request from my side but asking for a prediction of what the upper echolons may decide.
