### ISSUE TITLE
CMakeLists.txt: semi-documented switch /d2Zi+ used for apparently no reason

### ISSUE THREAD

**Issue by AlexGuteniev** [microsoft/STL#1198]
According to [the documentation](https://docs.microsoft.com/en-us/cpp/build/reference/zo-enhance-optimized-debugging) `/d2Zi+` has documented `/Zo` equivalent and is also implied with `/Z7`

**Comment by BillyONeal** [comment]
It is used because when I wrote the CMake build system I made sure it used the same flags as the internal system, which hails from before there was a more public version of `/d2Zi+`.

**Comment by BillyONeal** [comment]
(That is to say, there was no consideration between `/d2Zi+` and anything else, just a blind copy)

**Comment by AlexGuteniev** [comment]
This probably means that you still can fix it as long as you change the internal system as well.

Possibly in the past when `/Zo` did not exist, `/d2Zi+` was not implied, so it did make sense, and now it does not.

**Comment by StephanTLavavej** [comment]
I looked at our internal, legacy, MSBuild build system - this option is ultra-global (used for all of the "vctools" toolset, not just the STL or the libraries), so I see no reason to attempt to change it there.

Therefore, this should be a very simple change - all we need to do is remove `/d2Zi+` here:

https://github.com/microsoft/STL/blob/3cca47387bc286e94f6bce18f3adcd7d737f5a3c/CMakeLists.txt#L71

**Comment by BillyONeal** [comment]
I recommend against introducing divergence between the internal and the external system wherever possible until the internal system is decomissioned, or it will be difficult to verify that the new system produces identical results as the old system.
