### ISSUE TITLE
Does the STL implemention depend on some code from compiler ?

### ISSUE THREAD

**Issue by Jamlee** [microsoft/STL#120]
C++ can not implement stl by only c++ lang , Does it depend on some compiler `black magic` ?

**Comment by sylveon** [comment]
yes, it depends on various compiler intrinsics

**Comment by StephanTLavavej** [comment]
And here are three examples:

https://github.com/microsoft/STL/blob/7f65140761947af4ed7f9dfc11adee8c86c9e4c2/stl/inc/type_traits#L34-L35

https://github.com/microsoft/STL/blob/92508bed6387cbdae433fc86279bc446af6f1b1a/stl/inc/new#L24-L29

https://github.com/microsoft/STL/blob/7f65140761947af4ed7f9dfc11adee8c86c9e4c2/stl/inc/xstring#L309-L327
