### ISSUE TITLE
README.md: Consider explaining how to build ARM and ARM64

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#1211]
We merged #873, removing an incomplete explanation of how to build the STL for ARM and ARM64. We should consider adding a complete explanation, which would involve selecting ARM and ARM64 support in the VS installer. #3730 added CMake Presets, centralizing everything else.

**Comment by AlexGuteniev** [comment]
Mentioning `-DTESTS_BUILD_ONLY=ON` that can be used for limited testing in absence of ARM or ARM64
