### ISSUE TITLE
Clang and EDG support for <coroutine>

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#1223]
We've arranged for the `<coroutine>` header and its test coverage to activate when a compiler defines `__cpp_impl_coroutine` to `201902L` (the C++20 value). This is expected for MSVC in VS 2019 16.8 Preview 4 and we've verified that the test will pass at that time.

Currently, this is inactive for Clang and EDG. In theory, we should be able to take no action whatsoever, and this will automatically work in the future - but we should probably coordinate with their compiler devs to verify that everything will work with no library changes needed.

https://github.com/microsoft/STL/blob/484fbc9742f895030047977efc55dc8950a37086/stl/inc/yvals_core.h#L1171-L1177
https://github.com/microsoft/STL/blob/484fbc9742f895030047977efc55dc8950a37086/stl/inc/coroutine#L16-L18
https://github.com/microsoft/STL/blob/484fbc9742f895030047977efc55dc8950a37086/tests/std/tests/P0912R5_coroutine/test.cpp#L4-L5

**Comment by CaseyCarter** [comment]
My investigation with LLVM trunk suggests that `<coroutine>` will "light up" in Clang when LLVM 14 releases with no changes required.
