### ISSUE TITLE
What about <format> ?

### ISSUE THREAD

**Issue by NUU-Solutions** [microsoft/STL#1237]
Sorry if this is the wrong place to ask.
My understanding was that a <format> library implementation is coming soon. 
Can't find it, however, nor any information.

Is there a time-frame? 
Is it still recommended to use {fmt} for quite a while?

**Comment by miscco** [comment]
You might want to have a look at #1232

**Comment by sylveon** [comment]
> Is it still recommended to use {fmt} for quite a while?

Note that `std::format` is not a fully drop in replacement. It doesn't have literals, a `fmt::memory_buffer` equivalent, or compile-time checking of the format string (although that will probably be something compilers implement in the future) so you should review or correct your usage to make sure that `std::format` fits it. `fmt::memory_buffer`, for example, will have to be replaced by your own memory buffer implementation, if you use it.

**Comment by NUU-Solutions** [comment]
Thanks for the warning.
I was trying to avoid those (future) problems by using a current STL implementation which I believed to be open source.
I'm just unable to find the code.

**Comment by StephanTLavavej** [comment]
As @miscco noted, @barcharcraz is working on `<format>`; #1232 is the first of what should be several PRs (we're using a feature branch `feature/format` to collect this work). #30 is the tracking issue for the feature (one of 24 remaining C++20 features). It's a big feature, so we can't promise when it'll be done, but we're working on it :smile_cat:

**Comment by NUU-Solutions** [comment]
Got it, thx.
