### ISSUE TITLE
cgmanifest.json: Move to a subdirectory

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#125]
This is a machine-readable file for Microsoft-internal purposes. It must remain in our tree, but there's no reason for it to be at the top level, where it pushes the readme down. Moving it to the `stl` subdirectory would be an improvement (as it covers the code within). The tools that read this don't care about its location at all.

**Comment by BillyONeal** [comment]
Can it go into docs instead?

I didn't want to put it in the `stl` directory in case we add other parts like vcruntime to this repo in the future.

**Comment by StephanTLavavej** [comment]
That seems like a good place, yes.
