### ISSUE TITLE
<yvals_core.h>: Update _MSVC_STL_UPDATE to September 2020

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#1257]
Explanation on our wiki: [Macro `_MSVC_STL_UPDATE`](https://github.com/microsoft/STL/wiki/Macro-_MSVC_STL_UPDATE)

Code:
https://github.com/microsoft/STL/blob/d19446293a1d3afb7e4482e1c7d3ea5f4b6b910c/stl/inc/yvals_core.h#L498

Previous issue: #1128

This issue is intended for a new contributor (especially one new to GitHub) to get started with the simplest possible change.

**Comment by Madhvan28** [comment]
Hi !
I am New to Open-Source .
Can I solve this issue?

**Comment by CaseyCarter** [comment]
> Hi !
> I am New to Open-Source .
> Can I solve this issue?

Yes, absolutely!
