### ISSUE TITLE
Does stl::filesystem::copy use FILE_SHARE_READ file opening attribute?

### ISSUE THREAD

**Issue by ohhmm** [microsoft/STL#1267]
Thanks,
Serg

**Comment by sylveon** [comment]
It uses [CopyFile](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-copyfile)

https://github.com/microsoft/STL/blob/154f9a8a978a865bac23516d97f0824e73c25f17/stl/src/filesystem.cpp#L449

**Comment by ohhmm** [comment]
Thanks @sylveon,

Looks like https://github.com/microsoft/STL/blob/154f9a8a978a865bac23516d97f0824e73c25f17/stl/src/filesystem.cpp#L463 states an issue for update_existing?

Thanks,
Serg
