### ISSUE TITLE
<ranges>: Questionable conditional noexcept

### ISSUE THREAD

**Issue by CaseyCarter** [microsoft/STL#1269]
The range adaptors defined in `<ranges>` strengthen `noexcept` more aggressively than much of the STL. Upon noticing that a couple of conditional `noexcept`s in `transform_view` were incorrect for non-zero IDL modes, I threw together some preprocessor stuffs to "turn off" a conditional `noexcept` in non-zero IDL:

https://github.com/microsoft/STL/blob/be0441cda16c2cb49d0bc3710d77912b866992a4/stl/inc/ranges#L1016-L1020

So that precondition-checking machinery that calls user-provided functions:

https://github.com/microsoft/STL/blob/be0441cda16c2cb49d0bc3710d77912b866992a4/stl/inc/ranges#L1064-L1067

is usable from functions that want to provide conditional `noexcept`:

https://github.com/microsoft/STL/blob/be0441cda16c2cb49d0bc3710d77912b866992a4/stl/inc/ranges#L1112-L1120

This is a bit of a hack, and [it was received as such](https://github.com/microsoft/STL/pull/1258#discussion_r483751596). I've since observed that other range adaptors have the same problem and simply slam into `noexcept`:

https://github.com/microsoft/STL/blob/be0441cda16c2cb49d0bc3710d77912b866992a4/stl/inc/ranges#L876-L882

(Note that conditional `noexcept` on `iter_move` and `iter_swap` overloads is not strengthened, but Standard-mandated.)

We need to devise policy for how we want to handle conditional `noexcept` on functions that call user-provided in "debug" modes only, including both strengthened and non-strengthened cases.

**Comment by AlexGuteniev** [comment]
I don't think that there's much point in this conditional `noexcept`.

I mean simple inline functions that call `noexcept` functions.

Compiler can propagate the observation of non-throwing into inlined code. So that even if it would not be `noexcept` from the type system point of view, it would be `noexcept` for optimization.

Mostly I see the point for `noexcept` in exports, where compiler does not see the implementation. But those `noexcept` are never conditional.

**Comment by AdamBucior** [comment]
Another solution would be to silently catch the exceptions that go out of debug machinery. I still think that terminating is the best option but silent catching is not a bad idea.

@AlexGuteniev `noexcept` is not only a hint to the compiler, it's also a hint to the user. Conditional `noexcept` tells the user, under what conditions the function does not throw exceptions, so he does not have to check definitions of all functions the function calls and see if they throw any exceptions.

**Comment by CaseyCarter** [comment]
I've come to the conclusion over the last couple of years that debug checks should affect neither `noexcept` nor ABI for ranges.

We discussed at the weekly maintainer meeting, and have consensus for that principle. Casey will submit a PR to remove the conditional noexcept that current exists in `<ranges>`.
