### ISSUE TITLE
P0356R5 bind_front()

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#13]
[P0356R5](https://wg21.link/P0356R5) `bind_front()`
[P1651R0](https://wg21.link/P1651R0) `bind_front()` Should Not Unwrap `reference_wrapper`

[LWG 3184](https://wg21.link/lwg3184) Inconsistencies in `bind_front` wording

**Comment by NathanSWard** [comment]
Would this issue be another one I could possibly attend to?
I have an initial implementation [here](https://github.com/NathanSWard/bind_front/blob/master/bind_front.hpp) for reference.

**Comment by StephanTLavavej** [comment]
Yes! There are no special compiler interactions here, and `bind_front()` is simpler than the full complexity of `bind()`.

While our test infrastructure is not yet available, the basic idea is simple - just have a command-line program that exits with `EXIT_SUCCESS` or `EXIT_FAILURE` and verifies things with `assert()`.
