### ISSUE TITLE
Use explicit(bool) unconditionally

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#1301]
At our request, C1XX, Clang, and EDG support C++20 `explicit(bool)` unconditionally - i.e. in C++14/17 modes. (Like `if constexpr`, C1XX and Clang emit Future Technology warnings that can be suppressed.) This allows us to _dramatically_ simplify `pair`, `tuple`, and `optional`.

We've requested similar support from NVIDIA's CUDA compiler. When this is available, and when MSVC can begin requiring that version of CUDA at a minimum, we should update the STL to remove our fallback codepaths.

Product code examples:

https://github.com/microsoft/STL/blob/5f3e91211ab25a2f493edf5f7d28520ac6b81d28/stl/inc/yvals_core.h#L371-L380
https://github.com/microsoft/STL/blob/5f3e91211ab25a2f493edf5f7d28520ac6b81d28/stl/inc/utility#L184-L207

Self-contained test case demonstrating C1XX, Clang, and EDG behavior:

```
C:\Temp>type explicit.cpp
```
```cpp
#include <type_traits>
using namespace std;

#ifdef __clang__
#pragma clang diagnostic ignored "-Wc++20-extensions" // warning: explicit(bool) is a C++20 extension
#else
#pragma warning(disable: 5053) // support for 'explicit(<expr>)' in C++17 and earlier is a vendor extension
#endif

struct No {};
struct Im {};
struct Ex {};

struct A {
    A(Im) {}
    explicit A(Ex) {}
};

template <typename T, typename Arg>
constexpr bool NotConstructible = !is_constructible_v<T, Arg> && !is_convertible_v<Arg, T>;

template <typename T, typename Arg>
constexpr bool ImplicitlyConstructible = is_constructible_v<T, Arg> && is_convertible_v<Arg, T>;

template <typename T, typename Arg>
constexpr bool ExplicitlyConstructible = is_constructible_v<T, Arg> && !is_convertible_v<Arg, T>;

static_assert(NotConstructible<A, No>, "BOOM NotConstructible");
static_assert(ImplicitlyConstructible<A, Im>, "BOOM ImplicitlyConstructible");
static_assert(ExplicitlyConstructible<A, Ex>, "BOOM ExplicitlyConstructible");


template <typename T1, typename T2> struct OldPair {
    template <typename U1, typename U2,
        enable_if_t<conjunction_v<is_constructible<T1, const U1&>, is_constructible<T2, const U2&>,
            is_convertible<const U1&, T1>, is_convertible<const U2&, T2>>, int> = 0>
        OldPair(const OldPair<U1, U2>&) {}

    template <typename U1, typename U2,
        enable_if_t<conjunction_v<is_constructible<T1, const U1&>, is_constructible<T2, const U2&>,
            negation<conjunction<is_convertible<const U1&, T1>, is_convertible<const U2&, T2>>>>, int> = 0>
        explicit OldPair(const OldPair<U1, U2>&) {}
};

static_assert(NotConstructible<OldPair<A, A>, const OldPair<No, No>&>, "OldPair BOOM 1");
static_assert(NotConstructible<OldPair<A, A>, const OldPair<No, Im>&>, "OldPair BOOM 2");
static_assert(NotConstructible<OldPair<A, A>, const OldPair<Im, No>&>, "OldPair BOOM 3");
static_assert(ImplicitlyConstructible<OldPair<A, A>, const OldPair<Im, Im>&>, "OldPair BOOM 4");
static_assert(ExplicitlyConstructible<OldPair<A, A>, const OldPair<Im, Ex>&>, "OldPair BOOM 5");
static_assert(ExplicitlyConstructible<OldPair<A, A>, const OldPair<Ex, Im>&>, "OldPair BOOM 6");
static_assert(ExplicitlyConstructible<OldPair<A, A>, const OldPair<Ex, Ex>&>, "OldPair BOOM 7");


template <typename T1, typename T2> struct NewPair {
    template <typename U1, typename U2,
        enable_if_t<conjunction_v<is_constructible<T1, const U1&>, is_constructible<T2, const U2&>>, int> = 0>
        explicit(!is_convertible_v<const U1&, T1> || !is_convertible_v<const U2&, T2>)
        NewPair(const NewPair<U1, U2>&) {}
};

static_assert(NotConstructible<NewPair<A, A>, const NewPair<No, No>&>, "NewPair BOOM 1");
static_assert(NotConstructible<NewPair<A, A>, const NewPair<No, Im>&>, "NewPair BOOM 2");
static_assert(NotConstructible<NewPair<A, A>, const NewPair<Im, No>&>, "NewPair BOOM 3");
static_assert(ImplicitlyConstructible<NewPair<A, A>, const NewPair<Im, Im>&>, "NewPair BOOM 4");
static_assert(ExplicitlyConstructible<NewPair<A, A>, const NewPair<Im, Ex>&>, "NewPair BOOM 5");
static_assert(ExplicitlyConstructible<NewPair<A, A>, const NewPair<Ex, Im>&>, "NewPair BOOM 6");
static_assert(ExplicitlyConstructible<NewPair<A, A>, const NewPair<Ex, Ex>&>, "NewPair BOOM 7");

int main() { }
```
```
C:\Temp>cl /EHsc /nologo /W4 /std:c++14 explicit.cpp
explicit.cpp

C:\Temp>cl /EHsc /nologo /W4 /std:c++14 /c /BE explicit.cpp
explicit.cpp

C:\Temp>clang-cl /EHsc /nologo /W4 /std:c++14 explicit.cpp

C:\Temp>
```

**Comment by AlexGuteniev** [comment]
Hello from 2022. Is this still blocked?

**Comment by StephanTLavavej** [comment]
Yes, unfortunately. I never received a response from NVIDIA (and I got busy so I never followed up, I imagine it was the same for them), so I'm unsure if the latest CUDA version supports `explicit(bool)` unconditionally. (Perhaps it does due to EDG upstream changes, but I think this is unlikely.)

Someone would need to contact NVIDIA and see if they can make this happen.

**Comment by AlexGuteniev** [comment]
We can just try without asking. Which NVIDIA's CUDA compiler version needs to support it? The latest one or the currently used?

**Comment by StephanTLavavej** [comment]
I'm virtually certain that the one we use (10.1 Update 2, the minimum we require) doesn't support this. If the latest version does, then we could talk to our bosses and boss-like entities about when we could increase the minimum (which we did for `if constexpr`). We're also not quite sure how eager CUDA users are about upgrading, although it seems to be fairly common to get support for new GPUs, which makes increasing the minimum version more palatable.

**Comment by AlexGuteniev** [comment]
It fails with 10.1 Update 2, but works with 11.7.  Maybe need to contact to determine the exact fix version, as binary search appears to be time consuming.

**Comment by StephanTLavavej** [comment]
Thanks! Would it be possible to check one more version? The [11.6.0 release notes](https://docs.nvidia.com/cuda/archive/11.6.0/cuda-toolkit-release-notes/index.html#cuda-compiler-new-features) from January 2022 say:

> **VS2022 Support**: CUDA 11.6 officially supports the latest VS2022 as host compiler. A separate Nsight Visual Studio installer 2022.1.1 must be downloaded from [here](https://developer.nvidia.com/nsight-visual-studio-edition). A future CUDA release will have the Nsight Visual Studio installer with VS2022 support integrated into it.

If CUDA 11.6 supports `explicit(bool)`, and if it was the first release to support VS 2022 without needing the compiler version escape hatch, I think we would have a fairly strong argument for increasing our minimum required version.

(Now I wonder if the Intel compiler supports this :scream_cat:)

**Comment by AlexGuteniev** [comment]
> (Now I wonder if the Intel compiler supports this 🙀)

Looks like yes:
https://godbolt.org/z/5xee7MWWE

**Comment by StephanTLavavej** [comment]
Removing the `blocked` label, as I can increase our requirement to CUDA 11.6.

Regarding the Intel compiler - what we specifically need is support for `explicit(bool)` as Future Technology, i.e. in C++14/17 mode (suppressible warnings OK). It looks like classic ICC doesn't support this, but modern ICX does.

**Comment by cpplearner** [comment]
I see that classic Intel compiler does enable `explicit(bool)` in C++14 mode on Windows.

```
D:\test>type test.cpp
#ifndef __cpp_conditional_explicit
#error __cpp_conditional_explicit is not defined
#endif

struct A { explicit(false) A(); };

D:\test>icl /c /FoNUL /std:c++14 test.cpp
Intel(R) C++ Intel(R) 64 Compiler Classic for applications running on Intel(R) 64, Version 2021.6.0 Build 20220226_000000
Copyright (C) 1985-2022 Intel Corporation.  All rights reserved.

test.cpp
```

**Comment by StephanTLavavej** [comment]
I will create a PR soon.
