### ISSUE TITLE
<xnode_handle.h>: values should be destroyed with value_type allocator

### ISSUE THREAD

**Issue by Kami-chanw** [microsoft/STL#1309]
for example, in the function `_Clear`

https://github.com/microsoft/STL/blob/5f3e91211ab25a2f493edf5f7d28520ac6b81d28/stl/inc/xnode_handle.h#L82-L91

why uses node allocator traits(_Alnode_traits) to destroy _Ptr->_Myval? I think it should be made by value allocator traits(_Alty_traits). All of value destructions have this problem. 

Also tracked by DevCom-1190997 and Microsoft-internal VSO-1217757 / [AB#1217757](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1217757) .

**Comment by CaseyCarter** [comment]
The Standard is pretty clear that `ator_traits` (an alias for `allocator_traits<allocator_type>`, where `allocator_type` comes from the container) is used to destroy the value stored in the node in both places where that occurs ([[container.node.cons]/3.1](http://eel.is/c++draft/container.node.cons#3.1) and [[container.node.dtor]/1](http://eel.is/c++draft/container.node.dtor#1)).

**Comment by BillyONeal** [comment]
I think the standard is wrong here: the allocator requirements don't require that the T* passed to construct or destroy match allocator::value_type.

If we want to ensure that it matches allocator::value_type, then we and the standard should consistently do that everywhere (and the allocator requirements should contain that restriction). But given that nothing has cared in the last 30 years I think the performance cost of the extra rebinds, small as it may be, is not worthwhile and the standard should resolve this by not mentioning the allocator_traits type used.

**Comment by CaseyCarter** [comment]
I agree, but I don't care enough to invest my time in an LWG issue for this. We're already paying the rebind cost since the Standard requires node-handles to store a value_type allocator, so the change to conform here is trivial.

If you feel strongly, feel free to file an LWG issue.

**Comment by BillyONeal** [comment]
Casey points out that other parts of the standard have been updated to be consistent about this in his PR, so I don't think an LWG issue is needed.

**Comment by Kami-chanw** [comment]
> The Standard is pretty clear that `ator_traits` (an alias for `allocator_traits<allocator_type>`, where `allocator_type` comes from the container) is used to destroy the value stored in the node in both places where that occurs ([[container.node.cons]/3.1](http://eel.is/c++draft/container.node.cons#3.1) and [[container.node.dtor]/1](http://eel.is/c++draft/container.node.dtor#1)).

Yes, but in the <xnode_handle.h>, _Alnode_traits is traits of node allocator (`using _Alnode = _Rebind_alloc_t<_Alloc, _Node>`), which isn't conform with standard.

**Comment by BillyONeal** [comment]
> Yes, but in the <xnode_handle.h>, _Alnode_traits is traits of node allocator (`using _Alnode = _Rebind_alloc_t<_Alloc, _Node>`), which isn't conform with standard.

I'm arguing that the implementation is correct and the standard is wrong, because the containers don't do that rebind.

**Comment by CaseyCarter** [comment]
> > The Standard is pretty clear that `ator_traits` (an alias for `allocator_traits<allocator_type>`, where `allocator_type` comes from the container) is used to destroy the value stored in the node in both places where that occurs ([[container.node.cons]/3.1](http://eel.is/c++draft/container.node.cons#3.1) and [[container.node.dtor]/1](http://eel.is/c++draft/container.node.dtor#1)).
> 
> Yes, but in the <xnode_handle.h>, _Alnode_traits is traits of node allocator (`using _Alnode = _Rebind_alloc_t<_Alloc, _Node>`), which isn't conform with standard.

Sorry for the lack of clarity: I was pointing out the justification in the Standard for your "I think this is a bug" statement. Billy is bothered by the fact that the Standard is telling us to do something that's semantically inconsistent with how nodes are handled by containers - it's weird that we have to handle nodes in a container differently from nodes outside a container held in a _`node-handle`_.

It's almost a tradition of WG21 that every time the Standard Library uses allocators it uses them a bit differently than in the other places. I don't think this indicates disagreement so much as a lack of clarity about the allocator design.

**Comment by BillyONeal** [comment]
>I don't think this indicates disagreement so much as a lack of clarity about the allocator design.

Or lack thereof 😅
