### ISSUE TITLE
<vector>: vector's move ctor initializes members twice

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#1324]
@xiangfan-ms discovered that `vector`'s move constructor zero-initializes its pointers before taking the other `vector`'s pointers, and that this isn't optimized away in release mode. (Which results in larger, slower codegen, and probably inhibits further optimizations like `memcpy` coalescing.)

1. `vector`'s move constructor constructs its base before allocating the proxy and taking the other's pointers:
https://github.com/microsoft/STL/blob/530bdc5aaa8a21277e1281ad3df8b8d8433b5caa/stl/inc/vector#L581-L584
2. The base construction sets the pointers to null:
https://github.com/microsoft/STL/blob/530bdc5aaa8a21277e1281ad3df8b8d8433b5caa/stl/inc/vector#L375
3. Then `_Move_construct` calls `_Take_contents` which re-assigns the pointers:
https://github.com/microsoft/STL/blob/530bdc5aaa8a21277e1281ad3df8b8d8433b5caa/stl/inc/vector#L556-L558
https://github.com/microsoft/STL/blob/530bdc5aaa8a21277e1281ad3df8b8d8433b5caa/stl/inc/vector#L384-L393

I believe it's possible to change this behavior. We'd need to make `_Vector_val` constructible from three pointers, so we can directly initialize them. (This will work with `_Compressed_pair`'s one-then-variadic-args - the one arg is for the allocator, the variadic args are sent to `_Vector_val`.) Then we'd need to allocate/swap proxies (which vanishes for release mode), and null out the other pointers. (This is `noexcept` so allocation failure is termination - no EH concerns. vNext will remove the allocation.)

**Comment by BillyONeal** [comment]
`string` has similar cases we didn't touch we because we were being paranoid about ABI compat at the time.

**Comment by StephanTLavavej** [comment]
I think we've gotten more comfortable about the ABI implications of changing the behavior of single member functions in a way that continues to uphold their Standard-mandated behavior. I see no potential for mix-and-match problems here.

**Comment by CaseyCarter** [comment]
I read Billy's comment less as a warning and more as a suggestion that we might want to make similar changes to `basic_string`.

**Comment by BillyONeal** [comment]
Correct

**Comment by BillyONeal** [comment]
> I read Billy's comment less as a warning and more as a suggestion that we might want to make similar changes to `basic_string`.

Yes, that's right. I meant in general that this problem where we have bases that initialize things happens in string too.

(Of course in basic_string we might have to add a no-op ctor that takes a tag to give it a different name or something to `_String_val` if there is ABI paranoia but still...)
