### ISSUE TITLE
<yvals_core.h>: Update _MSVC_STL_UPDATE to October 2020

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#1338]
Explanation on our wiki: [Macro `_MSVC_STL_UPDATE`](https://github.com/microsoft/STL/wiki/Macro-_MSVC_STL_UPDATE)

Code:
https://github.com/microsoft/STL/blob/530bdc5aaa8a21277e1281ad3df8b8d8433b5caa/stl/inc/yvals_core.h#L504

Previous issue: #1257

This issue is intended for a new contributor (especially one new to GitHub) to get started with the simplest possible change.

:jack_o_lantern: :ghost: :vampire: :spider: :bat: :candy: :chocolate_bar:

**Comment by praveenojha33** [comment]
Hello @StephanTLavavej , I have made a PR for this please review 😄 .
