### ISSUE TITLE
what is the status of <format> header for C++ 20

### ISSUE THREAD

**Issue by vickoza** [microsoft/STL#1349]
Instructions
============
Here, you can ask a question about this STL implementation, and a maintainer
will answer. Please read the examples below, then delete all of this text and
replace it with your question. If you aren't sure whether a question is
on-topic, just go ahead and ask it! :-)

On-Topic Examples
-----------------
* What is this code in the STL doing? You can link to the relevant code:
https://help.github.com/en/github/managing-your-work-on-github/creating-a-permanent-link-to-a-code-snippet
* What are the preferred conventions for writing something?
* What are the maintainers planning to do in the future?
* Would the maintainers be interested in specific enhancements?

Off-Topic Examples
------------------
* Questions about non-STL components, such as the compiler, the CRT,
the Windows API, the Visual Studio IDE, etc.
* Questions about how to use the STL or C++ in general. For such questions,
consider https://stackoverflow.com or https://www.reddit.com/r/cpp_questions/ .
* Questions about whether you've encountered a bug in the STL. Instead of this
Question template, please use the Bug Report template, because we'll need
a command-line test case and the other information requested there.

**Comment by sylveon** [comment]
See #30

**Comment by fsb4000** [comment]
and https://github.com/microsoft/STL/issues/1237

**Comment by StephanTLavavej** [comment]
Yep, @barcharcraz is working on `<format>`.
