### ISSUE TITLE
Sporadic failure of P0660R10_jthread_and_cv_any

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#1365]
After updating to Python 3.9, I'm seeing sporadic failures in `P0660R10_jthread_and_cv_any`. I can repro them with x64 (haven't tried x86 yet) and they don't seem to be specific to any particular configuration. They're pretty common and both `cl` and `clang-cl` can fail. They're always asserting on this line:

https://github.com/microsoft/STL/blob/e7d5113376763268075d87dbad662a7cf4763a10/tests/std/tests/P0660R10_jthread_and_cv_any/test.cpp#L219

**Comment by CaseyCarter** [comment]
Passing `move(token)` to `cv.wait_for` twice:

https://github.com/microsoft/STL/blob/e7d5113376763268075d87dbad662a7cf4763a10/tests/std/tests/P0660R10_jthread_and_cv_any/test.cpp#L182-L183

https://github.com/microsoft/STL/blob/e7d5113376763268075d87dbad662a7cf4763a10/tests/std/tests/P0660R10_jthread_and_cv_any/test.cpp#L200-L201

https://github.com/microsoft/STL/blob/e7d5113376763268075d87dbad662a7cf4763a10/tests/std/tests/P0660R10_jthread_and_cv_any/test.cpp#L218-L219

is smelly enough that it deserves a comment if it isn't wrong.

**Comment by StephanTLavavej** [comment]
@CaseyCarter Yes! I ran x86 and x64 10 times each, and they all passed.

(My machine seems to be *exceptionally good* at finding sporadic multithreading bugs.)
