### ISSUE TITLE
<memory> should use concepts instead of return-type SFINAE

### ISSUE THREAD

**Issue by mnatsuhara** [microsoft/STL#1367]
The `friend` functions for `shared_ptr` and `unique_ptr` are the only places where we still use return-type SFINAE.  We should update those functions to be concept-constrained and remove this return-type SFINAE once concepts are fully supported by EDG.  

https://github.com/microsoft/STL/blob/e7d5113376763268075d87dbad662a7cf4763a10/stl/inc/memory#L1904-L1937

**Comment by AdamBucior** [comment]
Isn't it a duplicate of #602?
