### ISSUE TITLE
README.md: Minor capitalization issues

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#137]
* GitHub URLs accept any casing for `microsoft/STL`, but the repo always depicts itself with that casing. The README mentions `Microsoft/STL` twice, which seems inconsistent.

* Some section headers capitalize everything, like "What This Repo Is Useful For". (I am notoriously responsible for doing this.) Other headers don't, like "How to Build with a Native Tools Command Prompt". This is inconsistent.

(reported to me via email)

**Comment by BillyONeal** [comment]
I think this changed literally during our preparation of the readme.

**Comment by contre** [comment]
For the second point, which way is the correct way: capitalize everything or standard title capitalization rules?

**Comment by StephanTLavavej** [comment]
The normal rules are best (instead of my weird style) - there are websites that will apply them to given text. (Only code identifiers, which are case-sensitive, should be allowed to override them.)

**Comment by bhumijgupta** [comment]
@StephanTLavavej  Can I work on this?

**Comment by StephanTLavavej** [comment]
Yes, definitely! 😸
