### ISSUE TITLE
Interest in supporting STL with generated Windows SDK headers

### ISSUE THREAD

**Issue by mjsabby** [microsoft/STL#1376]
I'm building a distributable cross platform build toolchain using Clang that can be acquired through Nuget. Its main use case will be invoking the toolchain from a .NET project/build system. For the purposes of this discussion, it means the toolchain is a simple set of zip files with all things needed to compile a native C++ application for all platforms and operating systems of interest (arm64, x64 windows and linux), and of course STL being relevant only for the windows arm64/x64 portion.

I would like to use STL on Windows, since it is the best C++ standard library on Windows.

I can already achieve part of my goal of a distributable toolchain by having a private CI server where I install the Windows SDK that builds the STL with options I care about (LLVM BC, LLVM BC with PGO collection instrumentation, Static Library, and PE file with import library) and distribute the built object code in the various forms I listed.

Windows SDK object files and import libraries are already available through Nuget, for example https://www.nuget.org/packages/Microsoft.Windows.SDK.CPP.x64/10.0.18362.3-preview

However, the Windows SDK headers are not available in Nuget and the Windows SDK is not redistributable. However, we could package the headers found on https://github.com/ntdiff/headers instead which are synthesized from PDBs.

And so coming back to STL, my question is would there be interest in supporting STL for headers that are synthesized from a source other than the Windows SDK (like the ntdiff headers mentioned above).

Without this support, the STL object files may be redistributable but it will not be a seamless experience because the user will have to edit their copy of STL pinned at the particular version to use the ntdiff headers, instead of the Windows SDK headers.

**Comment by StephanTLavavej** [comment]
My initial reaction is that supporting a "mutant build" doesn't align with our [Goals](https://github.com/microsoft/STL#goals) and would be a maintenance burden. We wouldn't want to add additional test coverage or significant amounts of infrastructure for such scenarios. (We already have a lot of obscure builds and this complexity tends to be multiplicative.)

However, I am confused as to exactly what's being asked here. STL headers completely avoid dragging in WinSDK headers (because they are large and enormously polluting) - only our separately compiled files include WinSDK headers. So what doesn't work, and what would you want to change?

**Comment by mjsabby** [comment]
Thank you for your response. If that is indeed a goal, that the STL will never refer to the Windows SDK then perhaps it is only a mild annoyance that building the STL would require Windows SDK headers, and my tool chain will have binary blobs for the compiler, linker and the STL. This means the user experience will not be what I described above, users will not need to be hand-edit the STL headers.

To your question of what would I like to change in the STL, it would be that the separately compiled files include an indirection, say "WindowsSDK.h" and this file in-tree would be per usual i.e. Windows SDK, but out-of-tree or through some mechanism could be supplied by the user of the repository in cases where they don't have access to Windows SDK but can supply the similar information through other mechanisms (one of which I described above).

In the end, this is to avoid getting into the mess of redistributing the Windows SDK, but perhaps that is what one should address. The import libraries are available from Nuget (I pasted the link above), but the headers are not.

**Comment by StephanTLavavej** [comment]
> If that is indeed a goal, that the STL will never refer to the Windows SDK

Yep - that's been the case for at least the last 13 years, and I expect it to be true indefinitely (until the world becomes fully modularized).

> my tool chain will have binary blobs for the compiler, linker and the STL.

You'll need to distribute compiled binaries for the STL in any event, if you want them to have the official names (`msvcp140.dll`) and be signed by Microsoft. This repo generates binaries with a different name (`msvcp140_oss.dll`) which are unsigned.

> To your question of what would I like to change in the STL, it would be that the separately compiled files
> include an indirection, say "WindowsSDK.h" and this file in-tree would be per usual i.e. Windows SDK,
> but out-of-tree or through some mechanism could be supplied by the user of the repository in cases
> where they don't have access to Windows SDK but can supply the similar information through other
> mechanisms (one of which I described above).

That probably wouldn't be too disruptive. We already have a mostly-centralized header for wrapping `Windows.h` already.

> In the end, this is to avoid getting into the mess of redistributing the Windows SDK, but perhaps
> that is what one should address. The import libraries are available from Nuget (I pasted the link above),
> but the headers are not.

Yes, I agree. If you haven't already, you should talk to the VCAIR team - @BillyONeal just moved there and can redirect you further if necessary.
