### ISSUE TITLE
Many warnings

### ISSUE THREAD

**Issue by Haceau-Zoac** [microsoft/STL#1381]
I enabled the /Wall, /std:c++latest and /experimental:module parameters, but there are many warnings when compiling the following program

code:

    import std.core;

    int main(void)
    {
        std::cout << "Hello C++20" << std::endl;
        return 0;
    }

warnings:

    警告	C4820	“std::basic_ostream<char,std::char_traits<char>>::sentry”:“3”字节填充添加在 数据成    员“std::basic_ostream<char,std::char_traits<char>>::sentry::_Ok”后
    警告	C4820	“std::basic_ios<char,std::char_traits<char>>”:“7”字节填充添加在 数据成员“std::basic_ios<char,std::char_traits<char>>::_Fillch”后
    警告	C4820	“__std_exception_data”:“3”字节填充添加在 数据成员“__std_exception_data::_DoFree”后
    警告	C4820	“std::ios_base”:“4”字节填充添加在 数据成员“std::ios_base::_Ploc”后
    警告	C5050	导入模块“std.core”时可能不兼容的环境: _M_FP_PRECISE is defined in current command line and not in module command line
    警告	C5050	导入模块“std.core”时可能不兼容的环境: _DEBUG is defined in current command line and not in module command line	Project1
    警告	C5050	导入模块“std.core”时可能不兼容的环境: _GUARDOVERFLOW_CRT_ALLOCATORS=1 is defined in current command line and not in module command line

And the following code:

    #include <iostream>

    int main(void)
    {
        std::cout << "Hello, world!" << std::endl;
        return 0;
    }

warnings:

    警告	C4365	“参数”: 从“long”转换到“unsigned int”，有符号/无符号不匹配
    警告	C4365	“参数”: 从“long”转换到“unsigned int”，有符号/无符号不匹配
    警告	C4365	“参数”: 从“long”转换到“unsigned int”，有符号/无符号不匹配
    警告	C4365	“参数”: 从“long”转换到“unsigned int”，有符号/无符号不匹配
    警告	C4365	“参数”: 从“long”转换到“unsigned int”，有符号/无符号不匹配
    警告	C4365	“参数”: 从“long”转换到“unsigned int”，有符号/无符号不匹配
    警告	C4514	“signbit”: 未引用的内联函数已移除	
    警告	C4514	“signbit”: 未引用的内联函数已移除
    警告	C4514	“signbit”: 未引用的内联函数已移除
    警告	C4514	“_fpcomp”: 未引用的内联函数已移除
    警告	C4514	“_fpcomp”: 未引用的内联函数已移除
    警告	C4514	“_fpcomp”: 未引用的内联函数已移除
    警告	C4514	“_chgsignl”: 未引用的内联函数已移除
    警告	C4514	“_copysignl”: 未引用的内联函数已移除
    警告	C4514	“abs”: 未引用的内联函数已移除
    警告	C4514	“_hypotl”: 未引用的内联函数已移除
    ...(208 in total)

I also enabled the /WX parameter, these warnings make me very distressed

**Comment by sylveon** [comment]
The STL doesn't support /Wall

**Comment by Haceau-Zoac** [comment]
> The STL doesn't support /Wall

Can i just block the warning?

**Comment by Haceau-Zoac** [comment]
> The STL doesn't support /Wall

In addition, some warnings also exist when /W3

**Comment by CaseyCarter** [comment]
To be precise, we keep the STL clean with `/W4` and a smattering of off-by-default warnings for which we've received specific requests. `/Wall` turns on literally every diagnostic in the compiler, including quite a few that are for investigating particular problems but not really meant to be enabled on "normal" compiles like C4820, C4514, and C4365.

> In addition, some warnings also exist when /W3

C5050 is a `/W1` warning: it's trying to warn you that you are using different command-line switches than were used to compile the module `std.core`.

**Comment by fsb4000** [comment]
> 
> 
> > The STL doesn't support /Wall
> 
> Can i just block the warning?

You can add:

```
 /experimental:external /external:anglebrackets  /external:W0 
```
It blocks most of the warnings.

For the rest you could use similar to this:

```
#pragma warning(push)
#pragma warning( disable : 4355 )
#pragma warning( disable : 5204 )
import std.core;
#pragma warning(pop)
```

**Comment by Haceau-Zoac** [comment]
Thank you very much

**Comment by Haceau-Zoac** [comment]
> To be precise, we keep the STL clean with `/W4` and a smattering of off-by-default warnings for which we've received specific requests. `/Wall` turns on literally every diagnostic in the compiler, including quite a few that are for investigating particular problems but not really meant to be enabled on "normal" compiles like C4820, C4514, and C4365.
> 
> > In addition, some warnings also exist when /W3
> 
> C5050 is a `/W1` warning: it's trying to warn you that you are using different command-line switches than were used to compile the module `std.core`.

How can I solve the c5050 warning?

**Comment by StephanTLavavej** [comment]
As [the documentation](https://docs.microsoft.com/en-us/cpp/cpp/modules-cpp?view=vs-2019) instructs, "compile your program with `/EHsc` and `/MD` options" and avoid adding any options that trigger warning C5050. (In my experimentation, some options that *should* trigger C5050 don't, so the absence of the warning doesn't prove that an option is okay. I'm not sure exactly which options are safe to add, although I would expect that the warning options are fine.)

This compiles cleanly:

```
C:\Temp>type meow.cpp
import std.core;

int main(void)
{
    std::cout << "Hello C++20" << std::endl;
    return 0;
}

C:\Temp>cl /std:c++latest /experimental:module /EHsc /MD /nologo /W4 meow.cpp
meow.cpp

C:\Temp>cl /std:c++latest /experimental:module /EHsc /MD /nologo /W4 /WX meow.cpp
meow.cpp

C:\Temp>
```

**Comment by Haceau-Zoac** [comment]
> As [the documentation](https://docs.microsoft.com/en-us/cpp/cpp/modules-cpp?view=vs-2019) instructs, "compile your program with `/EHsc` and `/MD` options" and avoid adding any options that trigger warning C5050. (In my experimentation, some options that _should_ trigger C5050 don't, so the absence of the warning doesn't prove that an option is okay. I'm not sure exactly which options are safe to add, although I would expect that the warning options are fine.)
> 
> This compiles cleanly:
> 
> ```
> C:\Temp>type meow.cpp
> import std.core;
> 
> int main(void)
> {
>     std::cout << "Hello C++20" << std::endl;
>     return 0;
> }
> 
> C:\Temp>cl /std:c++latest /experimental:module /EHsc /MD /nologo /W4 meow.cpp
> meow.cpp
> 
> C:\Temp>cl /std:c++latest /experimental:module /EHsc /MD /nologo /W4 /WX meow.cpp
> meow.cpp
> 
> C:\Temp>
> ```

This didn't solve my problem
But I solved it with compilation parameter /Wv:18
Thank you very much

**Comment by UMU618** [comment]
> But I solved it with compilation parameter /Wv:18

Just as #pragma warning( disable : xxx )
