### ISSUE TITLE
tests: Consistently use unsigned int

### ISSUE THREAD

**Issue by SuperWig** [microsoft/STL#1389]
Conventionally `unsigned int` is used instead of just `unsigned` (details: https://github.com/microsoft/STL/pull/1159#discussion_r498709286). There seems to be 3 files where that convention isn't used.

* [P0088R3_variant/test.cpp](https://github.com/microsoft/STL/blob/master/tests/std/tests/P0088R3_variant/test.cpp)
* [P0220R1_optional/test.cpp](https://github.com/microsoft/STL/blob/master/tests/std/tests/P0220R1_optional/test.cpp)
* [P0898R3_concepts/test.cpp](https://github.com/microsoft/STL/blob/master/tests/std/tests/P0898R3_concepts/test.cpp)

(thought this would be a good first issue)

**Comment by CaseyCarter** [comment]
The majority of the `variant` and `optional` tests are mechanically extracted from libc++'s tests with namespaces hand-edited in. The extracted portions should agree as much as is possible with upstream to ease updating regardless of our local conventions. It's perfectly fine to tweak the non-extracted portions of those two tests, though.
