### ISSUE TITLE
How to detect the microsoft standard library?

### ISSUE THREAD

**Issue by MikeGitb** [microsoft/STL#1401]
Is there a supported way to reliably detect the microsoft standard library at preprocessor stage (as oppesed to e.g. libstdc++ or libc++)? I.E. a macro similar to `_MSC_VER` but defined by the library? If not, I'd like to request such a feature.

Sorry, if this is already answered somewhere. I googled a bit and looked in the issues, but maybe I just didn't know what terms to search for. The only information I found is from 2016, when the microsoft standard library would only be used by msvc (IIRC)

**Comment by ZaldronGG** [comment]
Would `MSVC_STL_UPDATE` work for you?
https://github.com/microsoft/STL/wiki/Macro-_MSVC_STL_UPDATE

**Comment by MikeGitb** [comment]
Perfect thanks. 
Stupid me: I actually was aware of the regular PRs to update this macro, but completely forgot about it.
