### ISSUE TITLE
Can non-throwing operations on optional have some form of debug check?

### ISSUE THREAD

**Issue by Predelnik** [microsoft/STL#1402]
I understand that it probably doesn't fit very well to current debug switches (e.g. `_ITERATOR_DEBUG_LEVEL`) but asserting on wrong access to optional seems to be even more important than bounds checking containers in some cases, because
1. In many cases it will not lead to crash but to some random value based behavior (e.g. for `optional<int>`)
2. It will not be found via runtime sanitizers.

It's a bit of question/suggestion mix, so sorry about that in advance 😄

**Comment by sylveon** [comment]
https://github.com/microsoft/STL/pull/1362 ?

**Comment by Predelnik** [comment]
Sorry, it was 14 days ago, I couldn't know (searched only issues)
Thanks for implementing!
