### ISSUE TITLE
<chrono>: [time.duration.io] output should handle types beyond char and wchar_t

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#1430]
When #1341 implemented `operator<<(basic_ostream&, const duration&)`, its unit suffix logic handled only `char` and `wchar_t`:

https://github.com/microsoft/STL/blob/6458199849fb3c66e810b7f77d733d9899dce36f/stl/inc/chrono#L625-L662

However, WG21-N4868 27.5.11 [[time.duration.io]/1](http://eel.is/c++draft/time.duration.io#1) doesn't limit `charT` to being only `char` and `wchar_t`. Instead, it depicts narrow string literals being directly streamed into the `basic_ostream` regardless of its `charT` (which works because `const char *` is always streamable, albeit with reduced performance if the types differ).

Retaining the `wchar_t` logic is permitted and improves performance, so we just need to fix this for other character types (like `char8_t`, `char16_t`, and `char32_t`). 

@MattStephanson's first suggested strategy in https://github.com/microsoft/STL/pull/1341#issuecomment-723202382 sounds good:

> I think I can just switch the order of the `if/else` to make `char` the fallback, then use a `conditional` to get the correct return type.

We should also add test coverage for this - it doesn't have to be exhaustive, just testing a literal and a general suffix for another character type would be sufficient.

**Comment by MattStephanson** [comment]
Are they any tricks for using iostreams classes with `char??_t`? I tried to test this with a `basic_stringstream<char16_t>`, and got an error from
https://github.com/microsoft/STL/blob/19c683d70647f9d89d47f5a0ad25165fc8becbf3/tests/std/tests/prefix.lst#L6
https://github.com/microsoft/STL/blob/19c683d70647f9d89d47f5a0ad25165fc8becbf3/stl/inc/xlocale#L2397

`_FACET_SPECIALIZATION_MESSAGE` refers to [[locale.category]](https://eel.is/c++draft/locale.category), though perhaps [[iostreams.limits.pos]/2](https://eel.is/c++draft/iostreams.limits.pos#2) is relevant too. The only instantiations for `num_put` are for `char`, `wchar_t`, and `unsigned short` (fallback for `/Zc:wchar_t-`?), so it doesn't look like the library supports anything else, which would make this issue moot.

https://github.com/microsoft/STL/blob/19c683d70647f9d89d47f5a0ad25165fc8becbf3/stl/inc/xlocnum#L1619-L1635

**Comment by CaseyCarter** [comment]
> Are they any tricks for using iostreams classes with `char??_t`?

The iostreams class templates only support characters of type `char` and `wchar_t` (and `unsigned char` when `/Zc:wchar_t-`, but don't do that). The fact that many of the templates can be instantiated with other types is an unfortunate historical artifact of our implementation.

**Comment by MattStephanson** [comment]
@StephanTLavavej, what do you think of this, in light of @CaseyCarter's comments? It looks like the library is not required, and does not attempt, to support iostream classes using other than `char` and `wchar_t`.

**Comment by StephanTLavavej** [comment]
Yep, I agree that this is a non-bug. Thanks for looking into it (and apologies for the delayed response).
