### ISSUE TITLE
<xmemory> Debug iterators have undefined behavior

### ISSUE THREAD

**Issue by miscco** [microsoft/STL#1437]
As  @zygoloid found during the analysis of #1407, we mutate members of potentially constant variables through the current proxy interface. We should fix this by marking the respective member variables as mutable

From the comment:

I think the problem is that inside `rbegin` we create a new iterator, and then return a copy of it. That means we:

1) Create an iterator X of type `reverse_iterator`. The container's next pointer points to X.
2) Create a copy of that iterator, initializing the variable `rb` of type `const reverse_iterator`. Now the container's next pointer points to `rb`, and `rb`'s next pointer points to X.
3) The construction of `rb` completes, and it becomes const.
4) Destroy X.

In step (4), we attempt to modify `rb`'s next pointer to remove X from the linked list. But `rb` is a const object.

I think this is arguably a Clang bug (plus a standard bug): `rb` should probably not "become" a const object until the call to `rbegin` returns. But fixing that in the standard and in Clang won't actually solve the problem. Imagine if immediately after the above line of code you have:

`range_constructed.rbegin();`

Now you'll hit the same problem: creation of the new iterator will attempt to modify the member of the const object `rb`. And there's no way to handwave past that: this line of code modifies a non-mutable member of a const object, at a time in the object's lifetime when it is unquestionably const.

So ultimately, I think this is a bug in the implementation of your intrusive linked list: the next pointers need to be `mutable`, because you have no control over whether the objects of which they are subobjects are const objects and you could mutate the list at any time.

_Originally posted by @zygoloid in https://github.com/microsoft/STL/pull/1407#issuecomment-723347115_

**Comment by CaseyCarter** [comment]
We've been ignoring this particular bit of UB because it hasn't caused problems in practice; apparently the technical debt is about to come due.

**Comment by miscco** [comment]
Looks like we forgot to close this after we have added `mutable` to the respective members
