### ISSUE TITLE
<yvals_core.h>: Update _MSVC_STL_UPDATE to November 2020

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#1438]
Explanation on our wiki: [Macro `_MSVC_STL_UPDATE`](https://github.com/microsoft/STL/wiki/Macro-_MSVC_STL_UPDATE)

Code:
https://github.com/microsoft/STL/blob/9959929c77b18e25b6dfbc8886e311b913321925/stl/inc/yvals_core.h#L505

Previous issue: #1338

This issue is intended for a new contributor (especially one new to GitHub) to get started with the simplest possible change.

Please feel free to submit a pull request if there isn't one already linked here - no need to ask for permission! :smile_cat:

You can (and should) link your pull request to this issue using [GitHub's close/fix/resolve syntax](https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

**Comment by avinal** [comment]
Hello, I would like to work on this issue.

**Comment by mnatsuhara** [comment]
Please do!

**Comment by avinal** [comment]
I have added a pull request please review.😅

**Comment by SuperWig** [comment]
Perhaps future issues should add something to the effect of

"If there's currently no pull request/this issue isn't labelled "work in progress" please feel free to submit a pull request"

**Comment by StephanTLavavej** [comment]
Thanks @SuperWig - I have edited this issue's text so it'll be copy-pasted for the next issue. Hopefully this will make it even easier for contributors to get started - asking for permission to begin work is very polite :heart_eyes_cat: and common among new contributors (thank you @avinal!) but introduces additional delay until a maintainer can respond. In the unlikely event that we receive two near-simultaneous PRs, it would be quite simple to credit both contributors in the history, and both contributors would have the experience of preparing and submitting the PR, so no work would be wasted.
