### ISSUE TITLE
Second STL Contributors Meetup

### ISSUE THREAD

**Issue by MahmoudGSaleh** [microsoft/STL#1443]
A few months ago, Microsoft's Visual C++ Libraries Team hosted the first STL Contributors meetup. Thanks to everyone who attended! Several important changes and proposals were initiated during the meetup, including a new [Discord channel](https://discord.gg/XWanNww) and various other items tracked by GH-1096 , GH-1097 and GH-1098. You can find more details at the previous meetup announcement, GH-921.

Now, as we're getting closer to completing the implementation of C++20 STL features, we'd like to invite you to another meetup that will take place on `Wednesday, December 9th, 2020 from 9am to 10am Pacific Time (PT)`.

Similar to the previous one, the meeting will be conducted using Microsoft Teams. To participate, we ask that you register for the event using this link: https://aka.ms/stl-meetup. The focus of this meetup will be our plan to get to C++20 feature complete as well as the high-level workflow of the repo. Due to time constraints, we won't be discussing technical issues such as bugs, specific C++20 features or PRs unless their main purpose is to improve or change the STL repo workflow. Both Discord and GitHub Discussions page are better places for such technical discussions.
 
Please feel free to comment on this issue to ask any questions and to propose agenda items you’d like to bring up during the meetup.

**Comment by MahmoudGSaleh** [comment]
Invites have been sent out. Please let me know if you have registered, but haven't received an invite yet.

**Comment by mnatsuhara** [comment]
The Meeting Notes page of the wiki has been updated with notes from this most recent Contributors Meetup: https://github.com/microsoft/STL/wiki/MSVC-STL-Contributors-Meeting-Notes
