### ISSUE TITLE
P0881R7 `<stacktrace>`

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#1447]
[P0881R7](https://wg21.link/P0881R7) `<stacktrace>`
[P2301R1](https://wg21.link/P2301R1) Add A `pmr` Alias For `std::stacktrace`

Feature-test macro:
```cpp
#define __cpp_lib_stacktrace 202011L
```

@CaseyCarter's internal VS-PR-339694 has taught the IDE to recognize this as a C++ header.

**Comment by miscco** [comment]
Does this require compiler support and should it be marked as blocked until compiler support is ready?

**Comment by AlexGuteniev** [comment]
There's an alternative -- `CaptureStackBackTrace`. It is faster than `StackWalk`, but it is not a part of complete API family.

There's also `IDiaStackWalker::getEnumFrames2`, but it is the same as `StackWalk`  (apparently one is a wrapper on another).

**Comment by AlexGuteniev** [comment]
There's a caveat. Documentation of `StackWalk64` and friends contains the following:

> All DbgHelp functions, such as this one, are single threaded. Therefore, calls from more than one thread to this function will likely result in unexpected behavior or memory corruption. To avoid this, you must synchronize all concurrent calls from more than one thread to this function.

I'm not sure how to address this properly in `<stacktrace>`

**Comment by AlexGuteniev** [comment]
@leha-bot , are you planning to submit a PR ? 
I'm interested in this feature.

**Comment by AlexGuteniev** [comment]
Wow)

**Comment by SuperWig** [comment]
Would it make sense to mark this issue be marked work in progress in that case?

**Comment by StephanTLavavej** [comment]
Sure, I've labeled this as "work in progress" and moved it to the Investigating column.

(Guess who's catching up on half-month-old notifications?)

**Comment by StephanTLavavej** [comment]
I've updated this issue to mention the patch paper [P2301R1](https://wg21.link/P2301R1) "Add A `pmr` Alias For `std::stacktrace`" which was just accepted, with no changes to the feature-test macro.

**Comment by AlexGuteniev** [comment]
@leha-bot I went ahead and made PR with my vision of how to implement it. Please take a look if you are interested.

**Comment by AlexGuteniev** [comment]
I'm wondering why doesn't ёstacktraceё use ёsource_locationё, and why doesn't it provide column

**Comment by AdamBucior** [comment]
> I'm wondering why doesn't `stacktrace` use `source_location`

I think it's because `source_location` uses `const char*`s and not `string`s

**Comment by AlexGuteniev** [comment]
`stacktrace` would also benefit from using `const char*`. And from adding `column`

**Comment by KindDragon** [comment]
> I'm wondering why doesn't stacktrace use source_location, and why doesn't it provide column
Hi, @apolukhin. Do you know why?

**Comment by apolukhin** [comment]
> I'm wondering why doesn't `stacktrace` use `source_location`, and why doesn't it provide column

This is due to platform divergence. As it is stated in [P0881R7](https://wg21.link/P0881R7): "Unfortunately this is a necessarity on some platforms, where getting source line requires allocating or where source file name [returned into](https://github.com/boostorg/stacktrace/blob/a0f948e9f505cb53baf582fccbcb3024fd255ee1/include/boost/stacktrace/detail/frame_msvc.ipp#L213-L219) a storage [provided by user](http://www.qnx.com/developers/docs/6.5.0/index.jsp?topic=%2Fcom.qnx.doc.neutrino_lib_ref%2Fb%2Fbt_get_backtrace.html)."

**Comment by AlexGuteniev** [comment]
> "Unfortunately this is a necessarity on some platforms, where getting source line requires allocating or where source file name [returned into](https://github.com/boostorg/stacktrace/blob/a0f948e9f505cb53baf582fccbcb3024fd255ee1/include/boost/stacktrace/detail/frame_msvc.ipp#L213-L219) a storage [provided by user](http://www.qnx.com/developers/docs/6.5.0/index.jsp?topic=%2Fcom.qnx.doc.neutrino_lib_ref%2Fb%2Fbt_get_backtrace.html)."

I see. Although this could have been addressed by making the `std::string` internal to `stacktrace_entry`, it would have required extra member to hold the buffer.

Why no `source_column` anyway? At least in Windows it is available for free.

**Comment by apolukhin** [comment]
> Why no `source_column` anyway? At least in Windows it is available for free.

Most popular solutions for non-Windows platforms do not provide a `source_column()`. At the moment `std::stacktrace` is a minimal subset of abilities of all platforms, so the column is missing. This could be changed later, the addition seems quite simple for C++ standardization.

**Comment by apolukhin** [comment]
> @apolukhin , should `std::stacktrace` load symbols from the Internet?

It may. It is a question of "quality of implementation" and user needs. Some of the users would love such a feature. For others opening a socket in their application may be a showstopper.

IMO the feature is a very good one if there is a switch to disable it.

**Comment by AlexGuteniev** [comment]
I see, I also think so, the question is the default then. I was thinking a good default would be to use module names, export names, names from .pdbs, but don't go to http/https symbols servers for them.

Also I would like the configuration to be runtime, using a global or static function member setter for a thread-local variable (I wouldn't like passing extra parameters to getters, or, especially, to `<<` operators)

**Comment by AlexGuteniev** [comment]
> How would std::stacktrace retrieve symbols from PDB files?

An open question I guess.
My PR currently uses DbgEng, but lists main alternatives and their drawback as the first question to decide upon.

**Comment by AlexGuteniev** [comment]
> How would std::stacktrace retrieve symbols from PDB files? And if the symbols it retrieves are C++ mangled names, how would it demangle those names? Would this functionality rely on the msdia library for PDB reading?

See #2779
