### ISSUE TITLE
P0943R6 Supporting C Atomics In C++

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#1448]
[P0943R6](https://wg21.link/P0943R6) Supporting C Atomics In C++

Feature-test macro:
`#define __cpp_lib_stdatomic_h 202011L`

**Comment by XeonKHJ** [comment]
I'm still getting this error when compiling Electron 15.3.3 using MSVC 14.3.
`C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.31.31103\include\stdatomic.h(15,2): error: <stdatomic.h> is not yet supported when compiling as C, but this is planned for a future release.`
Same issue here https://issueantenna.com/repo/gnustep/libobjc2/issues/225

**Comment by CaseyCarter** [comment]
This proposal defines a `<stdatomic.h>` header that actually uses `std::atomic` so C11 code compiled as C++ works. We don't yet support atomics when actually compiling C, so such failures are expected.
