### ISSUE TITLE
P1048R1 `is_scoped_enum`

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#1449]
[P1048R1](https://wg21.link/P1048R1) `is_scoped_enum`

Feature-test macro:
`#define __cpp_lib_is_scoped_enum 202011L`

**Comment by SuperWig** [comment]
> This probably needs compiler support.

Surely it's just `is_enum_v<_Ty> && !is_convertible_v<_Ty, int>` ?

**Comment by StephanTLavavej** [comment]
You're absolutely right, this is WG21-N4885 [conv.integral]/1 "A prvalue of an unscoped enumeration type can be converted to a prvalue of an integer type."

However, I think that a library-only implementation will need to be careful to perform short-circuiting here. A user might have a class type where attempting to ask `is_convertible_v<_Ty, int>` would result in an unrecoverable hard error. `conjunction` should be sufficient.
