### ISSUE TITLE
LWG-3211 std::tuple<> should be trivially constructible

### ISSUE THREAD

**Issue by futuarmo** [microsoft/STL#1459]
[LWG-3211](https://cplusplus.github.io/LWG/issue3211) std::tuple<> should be trivially constructible

**Comment by miscco** [comment]
Has this ABI implications? Otherwise the fix is rather trivial (I blame @CaseyCarter for that one)

https://github.com/microsoft/STL/blob/9959929c77b18e25b6dfbc8886e311b913321925/stl/inc/tuple#L207-L209

**Comment by StephanTLavavej** [comment]
As the previous ABI-breaker here, I believe that the default ctor should be OK to change, but we'll double-check of course.
