### ISSUE TITLE
A long term issue. std::deque in Visual C++ is TOOOOOOOOOOOOOOOOOOO Slow

### ISSUE THREAD

**Issue by euloanty** [microsoft/STL#146]
**Describe the bug**
It uses subscriptors to implement iterator deferences which violates zero overhead principle. std::deque is by default running faster than std::vector for push_back because of less allocation.

GCC's implementation is not optimal as well. However, it is at least 10 times faster than VC's implementation.

I can guarantee not the issue of deque buffer size. Even I set the buffer size of deque to 4096, it is still SLOW because this implementation is bad and cannot correctly use cache which leads to cache miss.

Please reimplement std::deque so it could be actually useful. I know writing std::deque is hard but this container is objectively the best container for most cases than std::vector.

**Command-line test case**
STL version (git commit or Visual Studio version):
ANY version. THEY ARE ALL BAD!! IT IS JUST A HORRIBLE IMPLEMENTATION WHICH VIOLATES standard requirements.
I am using Visual Studio 2019 Developer Command Prompt v16.3.0-pre.4.0
```
C:\Users\billy\Desktop>type repro.cpp
#include<deque>
#include<chrono>
#include<vector>
#include<cstdio>
#include<string>

class timer
{
	std::string s;
	std::chrono::high_resolution_clock::time_point t0;
public:
	template<typename ...Args>
	timer(Args&& ...args):s(std::forward<Args>(args)...),t0(std::chrono::high_resolution_clock::now()){}
	timer(const timer&) = delete;
	timer& operator=(const timer&) = delete;
	~timer()
	{
		std::fprintf(stderr,"%s:\t%.8fs\n",s.c_str(),std::chrono::duration_cast<std::chrono::duration<double>>(std::chrono::high_resolution_clock::now()-t0).count());
	}
};

template<typename Cont,std::size_t N=100000000>
inline auto test(std::string const & tag)
{
		timer t1(tag+"\ttotal");
		Cont dq;
		{
		timer t1(tag+"\templace_back");
		for(std::size_t i(0);i!=N;++i)
			dq.emplace_back(i);
		}
		{
		timer t1(tag+"\tsum");
		std::size_t sum(0);
		for(auto const & e : dq)		//need tricks here since ++ it can't be optimized for deque
			sum+=e;
		return sum;
		}
}

int main()
{
	return test<std::vector<std::size_t>>("vector")==test<std::deque<std::size_t>>("deque");
}

```
**Command-line test case**
D:\hg\gcc>g++ --version
g++ (gcc-9-branch HEAD with MCF thread model, built by LH_Mouse.) 9.2.1 20190813
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

D:\hg\gcc>g++ -o deque deque.cc -O2

D:\hg\gcc>deque
vector  emplace_back:   0.66418800s
vector  sum:    0.05000800s
vector  total:  0.77719900s
deque   emplace_back:   0.34505500s
deque   sum:    0.11422500s
deque   total:  0.67933700s

D:\hg\gcc>cl -EHsc -Ox deque.cc -Ox
Microsoft (R) C/C++ Optimizing Compiler Version 19.23.28105.4 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

deque.cc
Microsoft (R) Incremental Linker Version 14.23.28105.4
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:deque.exe
deque.obj

D:\hg\gcc>deque
deque   emplace_back:   2.28296610s
deque   sum:    0.23614530s
deque   total:  4.28485920s
vector  emplace_back:   0.91508030s
vector  sum:    0.03928030s
vector  total:  1.01778770s

**Expected behavior**
THEY SHOULDN'T BE IMPLEMENTED AS SUBSCRIPTORS. PLEASE USE STANDARD IMPLEMENTATION.

std::deque is my favorite container but you screw it.

    _NODISCARD reference operator*() const {
        const auto _Mycont = static_cast<const _Mydeque*>(this->_Getcont());
#if _ITERATOR_DEBUG_LEVEL != 0
        _STL_VERIFY(_Mycont, "cannot dereference value-initialized deque iterator");
        _STL_VERIFY(_Mycont->_Myoff <= this->_Myoff && this->_Myoff < _Mycont->_Myoff + _Mycont->_Mysize,
            "cannot deference out of range deque iterator");
#endif // _ITERATOR_DEBUG_LEVEL != 0

        _Size_type _Block = _Mycont->_Getblock(_Myoff);
        _Size_type _Off   = _Myoff % _DEQUESIZ;
        return _Mycont->_Map[_Block][_Off];
    }

FUCK YOU. Why you cannot just dereference a pointer for * operator? it makes no sense for me.

Don't fool me. I even have my own implementation of std::deque because you screw it.

https://bitbucket.org/ejsvifq_mabmip/cqwrteur-std-deque/src/default/ejsvifq_mabmip-cqwrteur-std-deque-5aacb718a2fa[3475]/ejsvifq_mabmip-cqwrteur-std-deque-5aacb718a2fa/

**Comment by StephanTLavavej** [comment]
Please read the [Microsoft Open Source Code of Conduct](https://opensource.microsoft.com/codeofconduct/). Disrespectful behavior is not acceptable here.

I'm going to close and lock this issue, and file a separate one regarding `deque` performance (which was already one of the items on our todo list that will be migrated to GitHub issues).
