### ISSUE TITLE
LWG-3170 is_always_equal added to std::allocator makes the standard library treat derived types as always equal

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#1466]
LWG-3170 `is_always_equal` added to `std::allocator` makes the standard library treat derived types as always equal

**Comment by futuarmo** [comment]
`using is_always_equal = true_type;` now presents in `_Default_allocator_traits`, so according to this part of LWG:

> Add a new subclause in Annex D after D.13 [depr.str.strstreams]:

    D.? The default allocator [depr.default.allocator]

    -?- The following member is defined in addition to those specified in 20.10.10 [default.allocator]:

    namespace std {
      template <class T> class allocator {
      public:
        using is_always_equal = true_type;
      };
    }

we should just mark `is_always_equal` member of `std::allocator` as deprecated, am I right?
