### ISSUE TITLE
provision-image.ps1: Fix Windows Driver Kit installation

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#1471]
In the toolset update #1451, I attempted to install the Windows Driver Kit when preparing the Virtual Machine Scale Set, needed for #1289. I wrote:

https://github.com/microsoft/STL/blob/ea156e730cf3370d0551a0532669b7de90c78915/azure-devops/provision-image.ps1#L251-L252

I didn't actually test this manually, I just verified the successful return code. On Discord, @ben-craig reports that running `wdksetup.exe` isn't blocking, so we should run:

`cmd /c start /wait wdksetup.exe /quiet /features +`

**Comment by Arzaghi** [comment]
I've investigated this issue. I downloaded[ WDK installer](https://docs.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk#wdk-for-windows-10-version-2004) and tried to run this command locally. It perfectly blocks the operation until the installation finished. `-wait` cause the command to block until the job is completed.
I hope I understand the reported issue correctly.

**Comment by StephanTLavavej** [comment]
Thanks for verifying, @Arzaghi! Yep, we just need this to block until it's done (otherwise we might shut down and snapshot the VM before the installation finishes). I should be able to update this command in the next toolset update then.

**Comment by cbezault** [comment]
@Arzaghi, did you mean that the existing command works or the updated `cmd /c start /wait wdksetup.exe /quiet /features +` works?

**Comment by Arzaghi** [comment]
> @Arzaghi, did you mean that the existing command works or the updated `cmd /c start /wait wdksetup.exe /quiet /features +` works?

I mean the existing command works as expected.
