### ISSUE TITLE
VSO_0226079_mutex is sporadically failing

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#1472]
We encountered a sporadic test failure:

```
Assertion failed: time_execution([this] { unique_lock<Mutex> ul(mtx, 50ms); assert(!ul.owns_lock()); }) >= 50ms,
file C:\a\1\s\tests\std\tests\VSO_0226079_mutex\test.cpp, line 327
```

https://github.com/microsoft/STL/blob/ea156e730cf3370d0551a0532669b7de90c78915/tests/std/tests/VSO_0226079_mutex/test.cpp#L324-L327

It appears that `system_clock` behavior may be making this test unreliable.

**Comment by CaseyCarter** [comment]
Any idea why `time_execution` doesn't measure with `steady_clock`?
