### ISSUE TITLE
Is std::basic_string_view and std::span in MSVC STL binary compatible with POSIX iovec?

### ISSUE THREAD

**Issue by expnkx** [microsoft/STL#1477]
libstdc++ ensures this. Does msvc stl ensure this too?

**Comment by miscco** [comment]
Please have a look at #874 

tl;dr It *should* be compatible but we would not care if it is not

**Comment by expnkx** [comment]
> Please have a look at #874
> 
> tl;dr It _should_ be compatible but we would not care if it is not

POSIX is the operating system standard. That is why it is important.

**Comment by MikeGitb** [comment]
STL doesn't run on posix systems as far as I am aware, so why would it matter?

**Comment by expnkx** [comment]
> STL doesn't run on posix systems as far as I am aware, so why would it matter?

That is false. CRT is following the POSIX standard, for example, CRT does provide file descriptors.

Here what I want is to make std::span, std::string_view being binary compatible with libstdc++ and libc++ to implement locale system.

**Comment by MikeGitb** [comment]
It may be the case that the crt provides some of the functionality specified in posix, but things like `readv` or `iovec` are (to the best of my knowledge) not part of it.

**Comment by expnkx** [comment]
> It may be the case that the crt provides some of the functionality specified in posix, but things like `readv` or `iovec` are (to the best of my knowledge) not part of it.

Sure. But struct iovec is still very useful to maintain many other binary compatibilities. Think the struct iovec interface can be used as std::span directly. That is amazing.

**Comment by MikeGitb** [comment]
Sure, if I ever had iovec and mscv's stl std::span in the same process that would be cool but as that is not going to be the case, I don't see the point. And I also don't see why binary compatibility between different standard libraries is relevant either.

But apparently you have a usecase for it. Maybe you could elaborate, what exactly would be the benefit for my code?

Just to be clear: Its not me you have to convince of course - I'm not connected to this repository. I was just curious.

**Comment by expnkx** [comment]
> Sure, if I ever had iovec and mscv's stl std::span in the same process that would be cool but as that is not going to be the case, I don't see the point. And I also don't see why binary compatibility between different standard libraries is relevant either.
> 
> But apparently you have a usecase for it. Maybe you could elaborate, what exactly would be the benefit for my code?
> 
> Just to be clear: Its not me you have to convince of course - I'm not connected to this repository. I was just curious.

I am implementing a new locale system based so it can be cross-platform available on all platforms

Here I want them to be binary compatible.
https://bitbucket.org/ejsvifq_mabmip/fast_io_i18n/src/master/localedef.h
https://bitbucket.org/ejsvifq_mabmip/fast_io_i18n/src/master/localedef_fast_io.h

It looks like they are compatible. So I will close the comment.

**Comment by miscco** [comment]
I believe these were the exact same questions that were raised in #874 by @StephanTLavavej
