### ISSUE TITLE
<complex>: arm64_neon.h declares many non-_Ugly identifiers/macros

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#1489]
While performing surgery on #935 to make it header-only for `/clr:pure` compatibility, I made `<complex>` drag in `arm64_neon.h`:

https://github.com/microsoft/STL/blob/19c683d70647f9d89d47f5a0ad25165fc8becbf3/stl/inc/complex#L23-L32

@statementreply observed that `arm64_neon.h` declares a zillion non-`_Ugly` identifiers and macros.

We should consider doing something about this. Possibilities:

* @CaseyCarter suggested extracting a small subheader (possibly into `intrin0.h` itself) with just what the STL needs. This would also be good for x86/x64 `emmintrin.h`.
* Wait for vNext and after `/clr:pure` is erased from human memory, go back to @statementreply's original separately compiled design, which avoids this identifier pollution.
* Hybrid approach: Continue to use the header-only, non-intrinsic code for `/clr:pure`, but separately compile the intrinsics for use by native and `/clr` code. (The only reason I didn't try this was time pressure.)

**Comment by frederick-vs-ja** [comment]
This seems fixed by #4695.

**Comment by CaseyCarter** [comment]
> This seems fixed by #4695.

Confirmed, we have no remaining inclusion of `arm64_neon` in the codebase. Let's call this resolved.
