### ISSUE TITLE
<atomic>:  clang-cl reports undeclared identifier '_InterlockedCompareExchange128_nf' for ARM64

### ISSUE THREAD

**Issue by zufuliu** [microsoft/STL#1491]
**Describe the bug**
clang-cl (`LLVM-11.0.0-win64.exe` from https://github.com/llvm/llvm-project/releases/tag/llvmorg-11.0.0) reports undeclared identifier `_InterlockedCompareExchange128_nf` at atomic(484,12) for ARM64 with `-std:c++latest`, no errors with `-std:c++17` or `-std:c++14` or without C++ language standard option.

https://github.com/microsoft/STL/blob/19c683d70647f9d89d47f5a0ad25165fc8becbf3/stl/inc/atomic#L483-L485

**Command-line test case**
```
C:\Temp>type repro.cpp
#include <atomic>

C:\Temp>clang-cl -c --target=aarch64-pc-windows-msvc .\repro.cpp

C:\Temp>clang-cl -c --target=aarch64-pc-windows-msvc -std:c++14 .\repro.cpp

C:\Temp>clang-cl -c --target=aarch64-pc-windows-msvc -std:c++17 .\repro.cpp

C:\Temp>clang-cl -c --target=aarch64-pc-windows-msvc -std:c++latest .\repro.cpp
In file included from .\repro.cpp:1:
D:\Program Files\Microsoft Visual Studio\2019\VC\Tools\MSVC\14.28.29333\include\atomic(484,12): error: use of undeclared identifier '_InterlockedCompareExchange128_nf'
    return _InterlockedCompareExchange128_nf(_Dest, _Tmp[1], _Tmp[0], _Tmp) != 0;
           ^
1 error generated.
```

**Expected behavior**
No errors like other architectures.

**STL version**
Visual Studio 2019 14.28.29333

**Additional context**
My failed GitHub Actions job `Build with LLVM (Visual C++)` for `LLVMRelease` configuration at
https://github.com/zufuliu/notepad2/runs/1424448830?check_suite_focus=true#step:7:7
It use `LLVM_v142` toolchain from https://github.com/zufuliu/llvm-utils, also reproducible with `LLVM (clang-cl)` toolchain.

```
   In file included from ..\..\scintilla\src\AutoComplete.cxx:19:
  In file included from C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29333\include\memory:18:
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29333\include\atomic(484,12): error : use of undeclared identifier '_InterlockedCompareExchange128_nf' [D:\a\notepad2\notepad2\build\VS2017\Notepad2.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29333\include\atomic(484,12): error :     return _InterlockedCompareExchange128_nf(_Dest, _Tmp[1], _Tmp[0], _Tmp) != 0; [D:\a\notepad2\notepad2\build\VS2017\Notepad2.vcxproj]
```

**Comment by StephanTLavavej** [comment]
Thanks for reporting this. I see (at least) 3 issues here:

* Clang should implement the same intrinsics that the MSVC compiler implements; this should be reported as an LLVM bug
* The STL should work around this, temporarily, by using the sequentially consistent intrinsic (assuming it works)
* The STL should have coverage for Clang targeting ARM64 (tracked by #820)

**Comment by zufuliu** [comment]
`_InterlockedCompareExchange128_nf` is declared at line 171 of `VC\Tools\MSVC\14.28.29333\include\intrin0.h`, but for some reason not visible to Clang.

```cpp
#ifdef __clang__
// This looks like a circular include but it is not because clang overrides <intrin.h> with their specific version.
// See further discussion in LLVM-47099.
#include <intrin.h>
#else /* ^^^ __clang__ // !__clang__ vvv */

// other definitions and declarations
// line 171 for _InterlockedCompareExchange128_nf
#endif /* ^^^ !__clang__ */
```

https://bugs.llvm.org/show_bug.cgi?id=47099
```

**Comment by cbezault** [comment]
We could start building all the tests for `ARM64` even if we don't run them. That would have caught this problem.

**Comment by AlexGuteniev** [comment]
Is there non- _nf function available? If so, could use it

**Comment by zufuliu** [comment]
None are available in Clang 11 or bellow for ARM64, see https://reviews.llvm.org/D92062, but Clang has some atomic builtins http://clang.llvm.org/docs/LanguageExtensions.html#c11-atomic-builtins

**Comment by AlexGuteniev** [comment]
Probably can also use inline assembly for Clang.
Unlike MSVC in Clang it works in x64 and it allows specifying clobbering, so it is not expected to be problematic.
