### ISSUE TITLE
<atomic>: atomic_ref<const T> fails to compile

### ISSUE THREAD

**Issue by mocabe** [microsoft/STL#1497]
**Description**
`n4868`/`[atomic.ref.generic]` says template parameter `T` of `atomic_ref<T>` should satisfy `is_trivially_copyable_v`.  
Current `atomic_ref<T>` has `static_assert` for `is_trivially_copyable_v<_Ty> && is_copy_constructible_v<_Ty> && is_move_constructible_v<_Ty> && is_copy_assignable_v<_Ty> && is_move_assignable_v<_Ty>`, which is probably copy-pasted from `atomic<T>`.

This makes `atomic_ref<const T>` fail to compile since `const T` is not assignable, but I believe this is valid use case.

**Test code**
```cpp
#include <atomic>

auto load_as_atomic(const std::atomic<int>& i) 
{
    return i.load();
}

auto load_as_atomic(const int& i) 
{
    // should compile
    return std::atomic_ref(i).load();
}

int main() {}
```
This compiles with libstdc++ ([Godbolt](https://godbolt.org/z/sr7Mff)), but not with STL.

**Possible Solution**

Change `static_assert` to match standard wording.

**Comment by StephanTLavavej** [comment]
Yep, this is a bug, thanks for reporting it. We missed the copy-pasting during code review.

WG21-N4868 [31.8.1 [atomics.types.generic.general]/1](https://eel.is/c++draft/atomics.types.generic.general#1): "The program is ill-formed if any of `is_­trivially_­copyable_­v<T>`, `is_­copy_­constructible_­v<T>`, `is_­move_­constructible_­v<T>`, `is_­copy_­assignable_­v<T>`, or `is_­move_­assignable_­v<T>` is `false`."
https://github.com/microsoft/STL/blob/19c683d70647f9d89d47f5a0ad25165fc8becbf3/stl/inc/atomic#L2165-L2168

WG21-N4868 [31.7.1 [atomics.ref.generic.general]/2](https://eel.is/c++draft/atomics.ref.generic.general#2): "The program is ill-formed if `is_­trivially_­copyable_­v<T>` is false."
https://github.com/microsoft/STL/blob/19c683d70647f9d89d47f5a0ad25165fc8becbf3/stl/inc/atomic#L2350-L2353

This is *trivial* to fix in the product code :joy_cat: but we should also add test coverage for a non-(copy/move)-(constructible/assignable) type. (`const int` is copy constructible, but not copy assignable.)
