### ISSUE TITLE
<optional>: vc140: c++17: header not found

### ISSUE THREAD

**Issue by ohhmm** [microsoft/STL#1542]
Header: optional 
Toolchain: vc140
STD: c++17
Expected: <optional> is
Actual: no <optional> header
Additional info: https://en.cppreference.com/w/cpp/utility/optional

**Comment by StephanTLavavej** [comment]
This is expected. `<optional>` was originally implemented in VS 2017 15.0, also known as the vc141 toolset. vc140 was VS 2015, which forever lacks `<optional>`. (vc142 is VS 2019.) This is documented [here](https://docs.microsoft.com/en-us/cpp/overview/visual-cpp-language-conformance?view=msvc-160) on Microsoft Docs. This is also listed in https://en.cppreference.com/w/cpp/compiler_support/17 - while this is an unofficial source, cppreference is great and they put a lot of effort into maintaining their extremely detailed tables.

Because VS 2015/2017/2019 are binary-compatible, we strongly recommend upgrading to the latest version of VS 2019 for its features, bugfixes, and performance/throughput improvements.

**Comment by ohhmm** [comment]
Hi @StephanTLavavej,

Am I understanding you correctly, that vc140 is not supported anymore?

I guess it is.

It's still part of VS2019 distribution.

I bet it includes bugfixing.

Please, double check and reopen.

Thanks,
Serg

**Comment by MikeGitb** [comment]
If I'm mistaken,  you are not asking for a bugfix, but for the backport of a feature.

**Comment by ohhmm** [comment]
Hi @MikeGitb,

It is totally bug of C++17 support in VC 14.0 toolset. 

This should be fixed in order to make sure Visual Studio 2015 Professional/Ultimate users could us C++17 compliant compiler. 

Otherwise the VC140 C++17 is buggy because its C++17 compliance is not complete by standard.

Thanks,
Serg

**Comment by MikeGitb** [comment]
VS2015 never had complete c++17 support, nor did they claim to be c++1€ compliant (as far as I remember). All toolchains start with partial support for a new standard for a couple of version before they are finished with implementing it and none is back porting later features to earlier versions (again, as far as I'm aware).

**Comment by ohhmm** [comment]
@MikeGitb,

There is no much point in supporting standard partially. 
It makes each code that trying to use your compiler to face compilation difficulties.
Compiler either some std compliant or not.
Because ifdefs make it compiled perfectly with both C++14 and C++17 (boost is an example).
If a developer could expect that C++17 has only partial implementation then he just would use C++14 to build.

Thanks,
Serg

**Comment by MikeGitb** [comment]
Well,  if that is your view, then you should consider VS2015 as not supporting c++17. Plain and simple. Considering that it was released 2 years before the release of c++17 that isn't suprising. Does VS2015 even have a /std:c++17 flag or just /std:c++latest

**Comment by ohhmm** [comment]
Ok, Thanks @MikeGitb

**Comment by StephanTLavavej** [comment]
We're fixing severe silent bad codegen bugs in VS 2017 15.9.x (whose patch version is up to a high number now). The bar for fixing bugs in VS 2015, which had older installer technology (Update 3 was the last major update), is even higher - I am not sure what it officially is, but it's basically "security bugs only".

We don't backport features to older releases, as that's a ton of effort for possibly negative value, as such changes will destabilize releases that are in maintenance mode. (Even new headers often involve changes to shared machinery.) If you want new features, you need to upgrade to new versions, so you can react to any source-breaking changes and report any regressions that need to be fixed quickly. We provide Standard mode options so you can separately upgrade the toolchain and move to a new set of features.
