### ISSUE TITLE
<streambuf>: basic_streambuf<char8_t>, basic_streambuf<char16_t>, basic_streambuf<char32_t> warnings for codecvt

### ISSUE THREAD

**Issue by expnkx** [microsoft/STL#1549]
**Describe the bug**
D:\hg\fast_io\.tmp\getline_tests>cl -EHsc -Ox line_get.cc /std:c++latest /experimental:concepts /MD
Microsoft (R) C/C++ Optimizing Compiler Version 19.28.29617 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

/std:c++latest is provided as a preview of language features from the latest C++
working draft, and we're eager to hear about bugs and suggestions for improvements.
However, note that these features are provided as-is without support, and subject
to changes or removal as the working draft evolves. See
https://go.microsoft.com/fwlink/?linkid=2045807 for details.

Experimental features are provided as a preview of proposed language features,
and we're eager to hear about bugs and suggestions for improvements. However,
note that these experimental features are non-standard, provided as-is without
support, and subject to breaking changes or removal without notice. See
http://go.microsoft.com/fwlink/?LinkID=691081 for details.

line_get.cc
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29617\include\fstream(160): warning C4996: 'std::codecvt<char16_t,char,mbstate_t>': warning STL4020: std::codecvt<char16_t, char, mbstate_t>, std::codecvt<char32_t, char, mbstate_t>, std::codecvt_byname<char16_t, char, mbstate_t>, and std::codecvt_byname<char32_t, char, mbstate_t> are deprecated in C++20 and replaced by specializations with a second argument of type char8_t. You can define _SILENCE_CXX20_CODECVT_FACETS_DEPRECATION_WARNING or _SILENCE_ALL_CXX20_DEPRECATION_WARNINGS to acknowledge that you have received this warning.
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29617\include\xlocale(664): note: see declaration of 'std::codecvt'
D:\hg\fast_io\include\fast_io_legacy_impl/cpp/streambuf_io_observer.h(15): note: see reference to class template instantiation 'std::basic_filebuf<char16_t,std::char_traits<char16_t>>' being compiled
D:\hg\fast_io\include\fast_io_legacy_impl/cpp/streambuf_io_observer.h(158): note: see reference to alias template instantiation 'fast_io::basic_filebuf_io_observer<char16_t,std::char_traits<char16_t>>' being compiled
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29617\include\fstream(160): warning C4996: 'std::codecvt<char32_t,char,mbstate_t>': warning STL4020: std::codecvt<char16_t, char, mbstate_t>, std::codecvt<char32_t, char, mbstate_t>, std::codecvt_byname<char16_t, char, mbstate_t>, and std::codecvt_byname<char32_t, char, mbstate_t> are deprecated in C++20 and replaced by specializations with a second argument of type char8_t. You can define _SILENCE_CXX20_CODECVT_FACETS_DEPRECATION_WARNING or _SILENCE_ALL_CXX20_DEPRECATION_WARNINGS to acknowledge that you have received this warning.
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29617\include\xlocale(664): note: see declaration of 'std::codecvt'
D:\hg\fast_io\include\fast_io_legacy_impl/cpp/streambuf_io_observer.h(15): note: see reference to class template instantiation 'std::basic_filebuf<char32_t,std::char_traits<char32_t>>' being compiled
D:\hg\fast_io\include\fast_io_legacy_impl/cpp/streambuf_io_observer.h(162): note: see reference to alias template instantiation 'fast_io::basic_filebuf_io_observer<char32_t,std::char_traits<char32_t>>' being compiled
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29617\include\fstream(520): warning C4996: 'std::codecvt<char32_t,char,mbstate_t>::in': warning STL4020: std::codecvt<char16_t, char, mbstate_t>, std::codecvt<char32_t, char, mbstate_t>, std::codecvt_byname<char16_t, char, mbstate_t>, and std::codecvt_byname<char32_t, char, mbstate_t> are deprecated in C++20 and replaced by specializations with a second argument of type char8_t. You can define _SILENCE_CXX20_CODECVT_FACETS_DEPRECATION_WARNING or _SILENCE_ALL_CXX20_DEPRECATION_WARNINGS to acknowledge that you have received this warning.
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29617\include\fstream(490): note: while compiling class template member function 'unsigned int std::basic_filebuf<char32_t,std::char_traits<char32_t>>::uflow(void)'
D:\hg\fast_io\include\fast_io_legacy_impl/cpp/streambuf_io_observer.h(15): note: see reference to class template instantiation 'std::basic_filebuf<char32_t,std::char_traits<char32_t>>' being compiled
D:\hg\fast_io\include\fast_io_legacy_impl/cpp/streambuf_io_observer.h(162): note: see reference to alias template instantiation 'fast_io::basic_filebuf_io_observer<char32_t,std::char_traits<char32_t>>' being compiled
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29617\include\fstream(431): warning C4996: 'std::codecvt<char32_t,char,mbstate_t>::out': warning STL4020: std::codecvt<char16_t, char, mbstate_t>, std::codecvt<char32_t, char, mbstate_t>, std::codecvt_byname<char16_t, char, mbstate_t>, and std::codecvt_byname<char32_t, char, mbstate_t> are deprecated in C++20 and replaced by specializations with a second argument of type char8_t. You can define _SILENCE_CXX20_CODECVT_FACETS_DEPRECATION_WARNING or _SILENCE_ALL_CXX20_DEPRECATION_WARNINGS to acknowledge that you have received this warning.
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29617\include\fstream(406): note: while compiling class template member function 'unsigned int std::basic_filebuf<char32_t,std::char_traits<char32_t>>::overflow(unsigned int)'
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29617\include\fstream(681): note: see reference to function template instantiation 'unsigned int std::basic_filebuf<char32_t,std::char_traits<char32_t>>::overflow(unsigned int)' being compiled
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29617\include\fstream(520): warning C4996: 'std::codecvt<char16_t,char,mbstate_t>::in': warning STL4020: std::codecvt<char16_t, char, mbstate_t>, std::codecvt<char32_t, char, mbstate_t>, std::codecvt_byname<char16_t, char, mbstate_t>, and std::codecvt_byname<char32_t, char, mbstate_t> are deprecated in C++20 and replaced by specializations with a second argument of type char8_t. You can define _SILENCE_CXX20_CODECVT_FACETS_DEPRECATION_WARNING or _SILENCE_ALL_CXX20_DEPRECATION_WARNINGS to acknowledge that you have received this warning.
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29617\include\fstream(490): note: while compiling class template member function 'unsigned short std::basic_filebuf<char16_t,std::char_traits<char16_t>>::uflow(void)'
D:\hg\fast_io\include\fast_io_legacy_impl/cpp/streambuf_io_observer.h(15): note: see reference to class template instantiation 'std::basic_filebuf<char16_t,std::char_traits<char16_t>>' being compiled
D:\hg\fast_io\include\fast_io_legacy_impl/cpp/streambuf_io_observer.h(158): note: see reference to alias template instantiation 'fast_io::basic_filebuf_io_observer<char16_t,std::char_traits<char16_t>>' being compiled
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29617\include\fstream(431): warning C4996: 'std::codecvt<char16_t,char,mbstate_t>::out': warning STL4020: std::codecvt<char16_t, char, mbstate_t>, std::codecvt<char32_t, char, mbstate_t>, std::codecvt_byname<char16_t, char, mbstate_t>, and std::codecvt_byname<char32_t, char, mbstate_t> are deprecated in C++20 and replaced by specializations with a second argument of type char8_t. You can define _SILENCE_CXX20_CODECVT_FACETS_DEPRECATION_WARNING or _SILENCE_ALL_CXX20_DEPRECATION_WARNINGS to acknowledge that you have received this warning.
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29617\include\fstream(406): note: while compiling class template member function 'unsigned short std::basic_filebuf<char16_t,std::char_traits<char16_t>>::overflow(unsigned short)'
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29617\include\fstream(681): note: see reference to function template instantiation 'unsigned short std::basic_filebuf<char16_t,std::char_traits<char16_t>>::overflow(unsigned short)' being compiled
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29617\include\fstream(733): warning C4996: 'std::codecvt<char32_t,char,mbstate_t>::unshift': warning STL4020: std::codecvt<char16_t, char, mbstate_t>, std::codecvt<char32_t, char, mbstate_t>, std::codecvt_byname<char16_t, char, mbstate_t>, and std::codecvt_byname<char32_t, char, mbstate_t> are deprecated in C++20 and replaced by specializations with a second argument of type char8_t. You can define _SILENCE_CXX20_CODECVT_FACETS_DEPRECATION_WARNING or _SILENCE_ALL_CXX20_DEPRECATION_WARNINGS to acknowledge that you have received this warning.
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29617\include\fstream(720): note: while compiling class template member function 'bool std::basic_filebuf<char32_t,std::char_traits<char32_t>>::_Endwrite(void)'
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29617\include\fstream(652): note: see reference to function template instantiation 'bool std::basic_filebuf<char32_t,std::char_traits<char32_t>>::_Endwrite(void)' being compiled
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29617\include\xlocale(430): warning C4996: 'std::codecvt<char32_t,char,mbstate_t>': warning STL4020: std::codecvt<char16_t, char, mbstate_t>, std::codecvt<char32_t, char, mbstate_t>, std::codecvt_byname<char16_t, char, mbstate_t>, and std::codecvt_byname<char32_t, char, mbstate_t> are deprecated in C++20 and replaced by specializations with a second argument of type char8_t. You can define _SILENCE_CXX20_CODECVT_FACETS_DEPRECATION_WARNING or _SILENCE_ALL_CXX20_DEPRECATION_WARNINGS to acknowledge that you have received this warning.
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29617\include\xlocale(664): note: see declaration of 'std::codecvt'
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29617\include\fstream(690): note: see reference to function template instantiation 'const _Facet &std::use_facet<std::codecvt<char32_t,char,mbstate_t>>(const std::locale &)' being compiled
        with
        [
            _Facet=std::codecvt<char32_t,char,mbstate_t>
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29617\include\fstream(688): note: while compiling class template member function 'void std::basic_filebuf<char32_t,std::char_traits<char32_t>>::imbue(const std::locale &)'
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29617\include\xlocale(436): warning C4996: 'std::codecvt<char32_t,char,mbstate_t>': warning STL4020: std::codecvt<char16_t, char, mbstate_t>, std::codecvt<char32_t, char, mbstate_t>, std::codecvt_byname<char16_t, char, mbstate_t>, and std::codecvt_byname<char32_t, char, mbstate_t> are deprecated in C++20 and replaced by specializations with a second argument of type char8_t. You can define _SILENCE_CXX20_CODECVT_FACETS_DEPRECATION_WARNING or _SILENCE_ALL_CXX20_DEPRECATION_WARNINGS to acknowledge that you have received this warning.
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29617\include\xlocale(664): note: see declaration of 'std::codecvt'
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29617\include\xlocale(430): warning C4996: 'std::codecvt<char32_t,char,mbstate_t>::id': warning STL4020: std::codecvt<char16_t, char, mbstate_t>, std::codecvt<char32_t, char, mbstate_t>, std::codecvt_byname<char16_t, char, mbstate_t>, and std::codecvt_byname<char32_t, char, mbstate_t> are deprecated in C++20 and replaced by specializations with a second argument of type char8_t. You can define _SILENCE_CXX20_CODECVT_FACETS_DEPRECATION_WARNING or _SILENCE_ALL_CXX20_DEPRECATION_WARNINGS to acknowledge that you have received this warning.
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29617\include\xlocale(436): warning C4996: 'std::codecvt<char32_t,char,mbstate_t>::_Getcat': warning STL4020: std::codecvt<char16_t, char, mbstate_t>, std::codecvt<char32_t, char, mbstate_t>, std::codecvt_byname<char16_t, char, mbstate_t>, and std::codecvt_byname<char32_t, char, mbstate_t> are deprecated in C++20 and replaced by specializations with a second argument of type char8_t. You can define _SILENCE_CXX20_CODECVT_FACETS_DEPRECATION_WARNING or _SILENCE_ALL_CXX20_DEPRECATION_WARNINGS to acknowledge that you have received this warning.
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29617\include\xlocale(430): warning C4996: 'std::codecvt<char16_t,char,mbstate_t>': warning STL4020: std::codecvt<char16_t, char, mbstate_t>, std::codecvt<char32_t, char, mbstate_t>, std::codecvt_byname<char16_t, char, mbstate_t>, and std::codecvt_byname<char32_t, char, mbstate_t> are deprecated in C++20 and replaced by specializations with a second argument of type char8_t. You can define _SILENCE_CXX20_CODECVT_FACETS_DEPRECATION_WARNING or _SILENCE_ALL_CXX20_DEPRECATION_WARNINGS to acknowledge that you have received this warning.
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29617\include\xlocale(664): note: see declaration of 'std::codecvt'
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29617\include\fstream(690): note: see reference to function template instantiation 'const _Facet &std::use_facet<std::codecvt<char16_t,char,mbstate_t>>(const std::locale &)' being compiled
        with
        [
            _Facet=std::codecvt<char16_t,char,mbstate_t>
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29617\include\fstream(688): note: while compiling class template member function 'void std::basic_filebuf<char16_t,std::char_traits<char16_t>>::imbue(const std::locale &)'
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29617\include\xlocale(436): warning C4996: 'std::codecvt<char16_t,char,mbstate_t>': warning STL4020: std::codecvt<char16_t, char, mbstate_t>, std::codecvt<char32_t, char, mbstate_t>, std::codecvt_byname<char16_t, char, mbstate_t>, and std::codecvt_byname<char32_t, char, mbstate_t> are deprecated in C++20 and replaced by specializations with a second argument of type char8_t. You can define _SILENCE_CXX20_CODECVT_FACETS_DEPRECATION_WARNING or _SILENCE_ALL_CXX20_DEPRECATION_WARNINGS to acknowledge that you have received this warning.
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29617\include\xlocale(664): note: see declaration of 'std::codecvt'
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29617\include\xlocale(430): warning C4996: 'std::codecvt<char16_t,char,mbstate_t>::id': warning STL4020: std::codecvt<char16_t, char, mbstate_t>, std::codecvt<char32_t, char, mbstate_t>, std::codecvt_byname<char16_t, char, mbstate_t>, and std::codecvt_byname<char32_t, char, mbstate_t> are deprecated in C++20 and replaced by specializations with a second argument of type char8_t. You can define _SILENCE_CXX20_CODECVT_FACETS_DEPRECATION_WARNING or _SILENCE_ALL_CXX20_DEPRECATION_WARNINGS to acknowledge that you have received this warning.
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29617\include\xlocale(436): warning C4996: 'std::codecvt<char16_t,char,mbstate_t>::_Getcat': warning STL4020: std::codecvt<char16_t, char, mbstate_t>, std::codecvt<char32_t, char, mbstate_t>, std::codecvt_byname<char16_t, char, mbstate_t>, and std::codecvt_byname<char32_t, char, mbstate_t> are deprecated in C++20 and replaced by specializations with a second argument of type char8_t. You can define _SILENCE_CXX20_CODECVT_FACETS_DEPRECATION_WARNING or _SILENCE_ALL_CXX20_DEPRECATION_WARNINGS to acknowledge that you have received this warning.
Microsoft (R) Incremental Linker Version 14.28.29617.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:line_get.exe
line_get.obj

**Command-line test case**

D:\hg\fast_io\.tmp\getline_tests>cl -EHsc -Ox line_get.cc /std:c++latest /experimental:concepts /MD
```cpp
#include"../../include/fast_io.h"
#include"../../include/fast_io_device.h"
#include"../../include/fast_io_legacy.h"

int main()
#ifdef __cpp_exceptions
try
#endif
{
	using namespace fast_io::manipulators;
	fast_io::filebuf_file fbf("line.txt",fast_io::open_mode::in);
	std::string str;
	scan(fbf,line_get(str));
	fast_io::filebuf_file obf("en.txt",fast_io::open_mode::out);
	for(auto e : str)
		println(obf,e," ",fast_io::chvw(e));
	print(obf,"END\n");
	scan(fbf,line_get(str));
	for(auto e : str)
		println(obf,e," ",fast_io::chvw(e));
	print(obf,"END\n");
	scan(fbf,line_get(str));
	for(auto e : str)
		println(obf,e," ",fast_io::chvw(e));
	print(obf,"END\n");
}
#ifdef __cpp_exceptions
catch(std::exception const& e)
{
	perrln(e);
	return 1;
}
#endif

```

**Expected behavior**
They should not report warnings

**Additional context**
https://github.com/expnkx/fast_io/blob/f24f44ef78acb697ed29ed81310c2c858f5d9f1f/include/fast_io_legacy_impl/cpp/filebuf_file.h#L171
I would like to create generic abstractions for all file (nt_file, zw_file, win32_file, posix_file, c_file, c_file_unlocked, bio_file) types. However, msvcstl reports warnings for u8filebuf, u16filebuf u32filebuf. I know this stuff does not exist in the standard, which means they should not report errors either.

https://github.com/expnkx/fast_io/blob/f24f44ef78acb697ed29ed81310c2c858f5d9f1f/include/fast_io_legacy_impl/cpp/streambuf_io_observer.h#L153

Here are u8c_file, u16c_file, u32c_file, u8c_file_unlocked, u16c_file_unlocked, u32c_file_unlocked
https://github.com/expnkx/fast_io/blob/f24f44ef78acb697ed29ed81310c2c858f5d9f1f/include/fast_io_legacy_impl/c/impl.h#L955

u8posix_file, u16posix_file, u32posix_file
https://github.com/expnkx/fast_io/blob/f24f44ef78acb697ed29ed81310c2c858f5d9f1f/include/fast_io_hosted/platforms/posix.h#L1081

u8win32_file, u16win32_file, u32win32_file
https://github.com/expnkx/fast_io/blob/f24f44ef78acb697ed29ed81310c2c858f5d9f1f/include/fast_io_hosted/platforms/win32.h#L875

u8nt_file, u16nt_file, u32nt_file
https://github.com/expnkx/fast_io/blob/f24f44ef78acb697ed29ed81310c2c858f5d9f1f/include/fast_io_hosted/platforms/nt.h#L714

u8zw_file, u16zw_file, u32zw_file
https://github.com/expnkx/fast_io/blob/f24f44ef78acb697ed29ed81310c2c858f5d9f1f/include/fast_io_hosted/platforms/nt.h#L758

openssl u8bio_file, u16bio_file, u32bio_file https://github.com/expnkx/fast_io/blob/f24f44ef78acb697ed29ed81310c2c858f5d9f1f/include/fast_io_driver/openssl_driver/bio.h#L309

**Comment by miscco** [comment]
Maybe stupid question, but why are you not defining `_SILENCE_CXX20_CODECVT_FACETS_DEPRECATION_WARNING` as suggested in that warning?

 Note that deprecated facilities are almost never really removed.

**Comment by expnkx** [comment]
> Maybe stupid question, but why are you not defining `_SILENCE_CXX20_CODECVT_FACETS_DEPRECATION_WARNING` as suggested in that warning?
> 
> Note that deprecated facilities are almost never really removed.

Well, that is not something I can control as a library. If user defines streambuf before fast_io_legacy.h, it will still warn.

Why not make it a noop? just call fwrite instead of doing codecvt stuffs for char8_t, char16_t, char32_t? Or you can codecvt to utf-8 always tbh.

**Comment by miscco** [comment]
Yes but this is not something the standard library can do. 

We cannot "simply" do something. The standard clearly states what it expects when some facility is used. In this case `https://eel.is/c++draft/depr.locale.stdcvt` clearly marks these as deprecated and we will warn you about it.

There is nothing to do here. If the user wants to use that he needs to silence the warning (Which IMHO is bad)

**Comment by expnkx** [comment]
> Yes but this is not something the standard library can do.
> 
> We cannot "simply" do something. The standard clearly states what it expects when some facility is used. In this case https://eel.is/c++draft/depr.locale.stdcvt clearly marks these as deprecated and we will warn you about it.
> 
> There is nothing to do here. If the user wants to use that he needs to silence the warning (Which IMHO is bad)

but why u8filebuf has to deal with locale? I do not understand why standard loves to put everything with locale. locale is not thread-safe either.

**Comment by MattStephanson** [comment]
I think the issue here is that `std::basic_filebuf` still uses the `char`-based `codecvt`, so the call's coming from inside the house:
https://github.com/microsoft/STL/blob/2914b4301c59dc7ffc09d16ac6f7979fde2b7f2c/stl/inc/fstream#L160
https://github.com/microsoft/STL/blob/2914b4301c59dc7ffc09d16ac6f7979fde2b7f2c/stl/inc/fstream#L767

It's holding a pointer to the `codecvt` internally, though, so I'd be concerned that changing the type might break ABI. But maybe `_STL_DISABLE_DEPRECATED_WARNING` can be used to silence it internally until vNext?

**Comment by expnkx** [comment]
> I think the issue here is that `std::basic_filebuf` still uses the `char`-based `codecvt`, so the call's coming from inside the house:
> https://github.com/microsoft/STL/blob/2914b4301c59dc7ffc09d16ac6f7979fde2b7f2c/stl/inc/fstream#L160
> 
> 
> https://github.com/microsoft/STL/blob/2914b4301c59dc7ffc09d16ac6f7979fde2b7f2c/stl/inc/fstream#L767
> 
> It's holding a pointer to the `codecvt` internally, though, so I'd be concerned that changing the type might break ABI. But maybe `_STL_DISABLE_DEPRECATED_WARNING` can be used to silence it internally until vNext?

i have a solution. 
Change
```cpp
using _Cvt  = codecvt<_Elem, char, typename _Traits::state_type>; 
```

to
using _Cvt  = codecvt<_Elem, std::conditional_t<std::is_same_v<_Elem,char>||std::is_same_v<_Elem,wchar_t>,char,char8_t>, typename _Traits::state_type>;

**Comment by MattStephanson** [comment]
But that kind of change risks breaking binary compatibility. Any already-compiled function, for example, that takes a `basic_fstream<char_16t>&` parameter is currently expecting that object to point to a `codecvt<char16_t,char>` and is going to call that class's member functions. There's no guarantee that those functions will work with a `codecvt<char16_t,char8_t>` instead. They might, since they're both supposed to convert to UTF-8 after all, but it seems like a pretty risky move just to silence a deprecation warning.

**Comment by expnkx** [comment]
> But that kind of change risks breaking binary compatibility. Any already-compiled function, for example, that takes a `basic_fstream<char_16t>&` parameter is currently expecting that object to point to a `codecvt<char16_t,char>` and is going to call that class's member functions. There's no guarantee that those functions will work with a `codecvt<char16_t,char8_t>` instead. They might, since they're both supposed to convert to UTF-8 after all, but it seems like a pretty risky move just to silence a deprecation warning.

there are no basic_fstream<char16_t> tbh. Since C++ standard library fstream only supports char and wchar_t. They are internally implemented by C's stdio facilities with C locale. Locale only supports char and wchar_t io. No formatted io at all for char8_t, char16_t, and char32_t. The only solution is to use fast_io since fast_io supports all character types.

**Comment by MattStephanson** [comment]
> There are no basic_fstream<char16_t> tbh

Okay, so `std::basic_fstream` is a bad example, replace it with `std::basic_filebuf` if you prefer. But my point is about ABI compatibility in general. If you're using a class, then someone else could be, and MSVC has a policy of (for now) not breaking already-compiled code. I tried it out, and you can silence the warnings by adding `_STL_DISABLE_DEPRECATED_WARNING` to about 5 places in `<fstream>`. Unless I'm mistaken about this issue or ABI, that seems like the best resolution until vNext.

**Comment by StephanTLavavej** [comment]
Our deprecation warnings are designed to be suppressed project-wide by the end programmer-user (by defining either the fine-grained or coarse-grained suppression macros). If a third-party library needs to suppress deprecation warnings, it is typically possible to push/disable/pop warning 4996 before using the deprecated machinery; the STL itself does this in many places where it has to use its own deprecated machinery.
