### ISSUE TITLE
<optional> <variant> etc. #pragma message for old standard mode should have STL#### prefix

### ISSUE THREAD

**Issue by BillyONeal** [microsoft/STL#155]
The Visual Studio IDE team would like to better surface cases when users try to use new language features in older language modes, as the IDE currently can't display the pragma messages we use, like:

https://github.com/microsoft/STL/blob/b72c0a609f00b92aedbb18d09faf72d48ceb9b4f/stl/inc/optional#L641

They requested that we change that message to be of the form STLNNNN (where N are digits) just like the rest of the library-generated diagnostics.

**Comment by StephanTLavavej** [comment]
Related: #209 "STL: Consider cleaning up and numbering static_assert messages".
