### ISSUE TITLE
c2864 compile error

### ISSUE THREAD

**Issue by yunhenk** [microsoft/STL#1553]
I caught a compile error [c2864](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-2/compiler-error-c2864?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(C2864)%26rd%3Dtrue&view=msvc-160)

Its description is :

```
C2864	'std::_Tree<_Traits>::_Multi': a static data member with an in-class initializer must have non-volatile const integral type or be specified as 'inline	
```

 which points to xtree line 874 and map line 43, the code is like:
```
static constexpr bool _Multi = _Traits::_Multi;
```
```
static constexpr bool _Multi = _Mfl;
```
I wonder why this happed. I am using visual studio 2019 and cpp14. Thanks for checking this question.

**Comment by yunhenk** [comment]
sorry, seem like somewhere defined a "constexpr "

**Comment by wangxihao** [comment]
@yunhenk  hello ,I met the same problem , could you share the solution to this ? thank you~

**Comment by yunhenk** [comment]
> @yunhenk hello ,I met the same problem , could you share the solution to this ? thank you~

em... seems like my own code also defined "constexpr ", like:
```
define constexpr xxx
```
comment it will do ok
