### ISSUE TITLE
<algorithm>: input_iterators break ranges algorithm

### ISSUE THREAD

**Issue by miscco** [microsoft/STL#1555]
**Describe the bug**
The current specification of the ranges algorithms as implemented is broken with respect to `input_iterators`, which makes them non-composable.

Consider the following simple test function:
```cpp
    template< input_iterator it,  sentinel_for<it> sen>
    find_and_do_something(it first, sen last, const std::iter_value_t<it>& target ) {
         auto result = std::ranges::find(first, last, target);
         if (result != last) {
             // Do something fancy
         }
    }
```

Now this would be totally fine previously, but `input_iterators` are not required to be copyable, so we must instead move them:
```cpp
    template< input_iterator it,  sentinel_for<it> sen>
    find_and_do_something(it first, sen last, const std::iter_value_t<it>& target ) {
         auto result = std::ranges::find(std::move(first), std::move(last), target);
         if (result != last) { // <-- URGH, last is in moved from state
             // Do something fancy
         }
    }
```

As you can see, we cannot ever use the result from the call to `std::ranges::find` because the algorithm eats an iterator/sentinel pair, but only gives back an iterator. 

If we are indeed passing true `input_iterators`, then we cannot even dereference the result, because it could be the end of the range, but we will never find out. This is true for all ranges algorithms that take input iterators.

The solution here would be *simple*TM. Instead of returning a single iterator we *should* return a `subrange`. This would enable us to actually do something with the return value and compose the algorithms as usual.

**Expected behavior**
Unfortunately this is exactly what the standard requires. It is just broken as it is. 

Someone with access to LWG should file an issue. I am happy to help with writing a paper for it, but not if the answer is that we cannot write a DR against C++20.

**Comment by cpplearner** [comment]
`sentinel_for` implies `semiregular` which implies `copyable`, so there's no need to use `std::move(last)`.

**Comment by miscco** [comment]
Does that mean that input iterators cannot be common_ranges?

**Comment by timsong-cpp** [comment]
If your input iterator isn't copyable, then no.

**Comment by miscco** [comment]
Thanks a lot for the clarification
