### ISSUE TITLE
Q1 2021 priority: C++20

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#1558]
In the first quarter of 2021, **our top priority is finishing C++20** for VS 2019 16.10. (See our [C++20 Features project](https://github.com/microsoft/STL/projects/3?fullscreen=true) and [Conformance milestone](https://github.com/microsoft/STL/milestone/1).) We continue to welcome PRs that fix bugs, improve performance/throughput, and so forth, but code reviews may be significantly delayed as we focus on C++20.

If you have questions about our plans for this quarter, feel free to ask them here.

**Comment by Hamondorf** [comment]
For this quarter are there any plans to allow class non-type template parameters for user-defined string literals? As well as any plans to add Intellisense for 'using enum' declarations?

**Comment by miscco** [comment]
This is the repo of the standard library. I feel your questions are more geared toward the compiler and should be asked at the developer community

**Comment by AdamBucior** [comment]
> For this quarter are there any plans to allow class non-type template parameters for user-defined string literals? As well as any plans to add Intellisense for 'using enum' declarations?

According to [C++ reference](https://en.cppreference.com/w/cpp/compiler_support) class NTTP for UDLs will be available in VS 2019 16.9.

**Comment by StephanTLavavej** [comment]
Thanks @miscco and @AdamBucior. @Hamondorf, here's the link: [Developer Community](https://developercommunity.visualstudio.com/spaces/62/index.html). You can report IntelliSense issues there.

While this repo is indeed for the C++ Standard Library only (and we try to stay on-topic, otherwise we won't get our library work done), I took a moment to do some compiler archaeology - for [P0732R2](https://wg21.link/P0732R2), it appears that this was implemented by internal MSVC-PR-279799 on Oct 7, before the Preview 2 cutoff on Nov 6, so cppreference is accurate and it should be available right now (Preview 2 is the latest publicly available build).

**Comment by jovibor** [comment]
Good Day.
I have one question.
Why in the world the MS STL's progress depends on Clang? It can be clearly seen from the issues like #1364 and many more.
Is it also true for gcc? Is Clang's libc++ also depends on MS compiler?

Could you please shed some light on this subject? 
May be even some blog post, explaining all these cross dependencies, could be very helpful.

**Comment by cbezault** [comment]
@jovibor We treat Clang as a first class citizen alongside the MSVC compiler. To that end we extensively test the version of clang shipped with VS with our implementation of the C++ standard library and sometimes need to consider the differing behaviors of the two compilers as well as the difference in available language features.

**Comment by fsb4000** [comment]
```As well as any plans to add Intellisense for 'using enum' declarations?```
@Hamondorf,  EDG implemented "Using Enum" (P1099R5) recently in version 6.3. When the Visual Studio receives that version, then Intellesence support will appear...

**Comment by Hamondorf** [comment]
@fsb4000 sounds good, thanks for the update
