### ISSUE TITLE
P0595R2 is_constant_evaluated()

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#156]
[P0595R2](https://wg21.link/P0595R2) `is_constant_evaluated()`

This is a compiler feature in a library wrapper. [Clang 9 supports](https://clang.llvm.org/cxx_status.html) the compiler builtin; MSVC's compiler front-end C1XX has implemented it for VS 2019 16.5 Preview 2.

Thanks to @NathanSWard for bringing this paper to my attention (we had Microsoft-internal spreadsheets for the compiler and library, and I converted the library spreadsheet to GitHub issues, but I forgot that I had put this one in the compiler spreadsheet).

Feature-test macro as of WG21-N4842:
`#define __cpp_lib_is_constant_evaluated 201811L`

**Comment by jonwil** [comment]
Do you mean VS 2019 16.4 Preview 2? (Given that 16.4 isn't even available yet, let alone a 16.5 Preview 1, I can't see how a 16.5 Preview 2 can exist)

**Comment by StephanTLavavej** [comment]
I really do mean 16.5 Preview 2 - VS releases are deeply pipelined, with a number of merges and “toolset insertions” required before bits end up shipping publicly.

**Comment by SuperWig** [comment]
>Do you mean VS 2019 16.4 Preview 2?

16.4 is already on Preview 4. 
If I'm not mistaken Preview 1 comes out at the same time as a final version,
