### ISSUE TITLE
<xlocnum>: "multiply by power of 10" logic is imprecise

### ISSUE THREAD

**Issue by statementreply** [microsoft/STL#1582]
**Describe the bug**

`_Stodx_v2` and `_Stofx_v2` contains:
https://github.com/microsoft/STL/blob/b1fbbdc4c31f0b810226e6eef782129e9e9c853c/stl/inc/xlocnum#L58-L60

> Like almost all of our pre-charconv floating-point formatting, I believe that this is incorrect - dividing by a power of 10 isn't an exact operation.

I believe that this code path is only activated when the integral part of the significand is longer than 768 digits (which overflows without a negative exponent).

**Command-line test case**

```
D:\Temp>type long_num_get.cpp
```
```cpp
#include <cassert>
#include <sstream>
#include <string>

using namespace std;

int main() {
    istringstream iss{"1" + string(2000, '0') + "e-2000"};
    double x;
    assert(iss >> x);
    assert(x == 1.0);
    return 0;
}
```

```
D:\Temp>cl /EHsc /W4 /WX long_num_get.cpp
Microsoft (R) C/C++ Optimizing Compiler Version 19.28.29812 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

long_num_get.cpp
Microsoft (R) Incremental Linker Version 14.28.29812.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:long_num_get.exe
long_num_get.obj

D:\Temp>.\long_num_get.exe
Assertion failed: iss >> x, file long_num_get.cpp, line 10
```

**STL version**

```
Microsoft Visual Studio Community 2019 Preview
版本 16.9.0 Preview 3.0
```

**Comment by CaseyCarter** [comment]
I suspect we could grep the sources for occurrences of `\b10\b` and every one would be a floating-point bug.

**Comment by StephanTLavavej** [comment]
Thanks for the example - I had noted this line in #264 but thought it was dead.

**Comment by frederick-vs-ja** [comment]
Perhaps #1792 is quite similar to this.
