### ISSUE TITLE
[span.sub] para 5 condition is insufficient

### ISSUE THREAD

**Issue by CaseyCarter** [microsoft/STL#159]
Per the discussion in https://github.com/microsoft/STL/pull/142#discussion_r331345592.

`Offset + Count <= size()` is insufficient to guarantee that the `span` returned from `span::subspan` is valid since `Offset + Count` can wrap. It should instead be `Count <= size() - Offset`.

**Comment by CaseyCarter** [comment]
I've submitted the issue to LWGChair, and will followup here once a number is assigned.

**Comment by miscco** [comment]
Hm I wasnt sure what happens when `_Count > size()` (aka wrap around via underflow) but that case is covered in conjunction with the other assert that `_Offset <= size()`

**Comment by CaseyCarter** [comment]
This problem is resolved by the P/R of LWG-3103.
