### ISSUE TITLE
<xtree>: Why _Tree_temp_node uses allocator for node to construct/destroy value? 

### ISSUE THREAD

**Issue by Kami-chanw** [microsoft/STL#1607]
Here is a constructor of _Tree_temp_node:
```
template <class... _Valtys>
    explicit _Tree_temp_node(_Alnode& _Al_, _Nodeptr _Myhead, _Valtys&&... _Vals)
        : _Tree_temp_node_alloc<_Alnode>(_Al_) {
        _Alnode_traits::construct(this->_Al, _STD addressof(this->_Ptr->_Myval), _STD forward<_Valtys>(_Vals)...);
        _Construct_in_place(this->_Ptr->_Left, _Myhead);
        _Construct_in_place(this->_Ptr->_Parent, _Myhead);
        _Construct_in_place(this->_Ptr->_Right, _Myhead);
        this->_Ptr->_Color = _Red;
        this->_Ptr->_Isnil = false;
    }
```
Besides, `this->_Ptr->_Left`/`this->_Ptr->_Parent`/`this->_Ptr->_Right` are raw pointers, why initialize them by `operator=` directly?

**Comment by StephanTLavavej** [comment]
> Why `_Tree_temp_node` uses allocator for node to construct/destroy value?

The Standard requires us to. WG21-N4878 22.2.1 [container.requirements.general]/3: "For the components affected by this subclause that declare an `allocator_type`, objects stored in these components shall be constructed using the function `allocator_traits<allocator_type>::rebind_traits<U>::construct` and destroyed using the function `allocator_traits<allocator_type>::rebind_traits<U>::destroy` (20.10.9.3), where `U` is either `allocator_type::value_type` or an internal type used by the container. These functions are called only for the container’s element type, not for internal types used by the container."

> Besides, `this->_Ptr->_Left`/`this->_Ptr->_Parent`/`this->_Ptr->_Right` are raw pointers, why initialize them by `operator=` directly?

They're raw pointers for `std::allocator` and 99% of user-defined allocators, but in general they can be "fancy pointers" (i.e. pointer-like class types). See 16.4.4.6.1 [allocator.requirements.general] and related Standardese.
