### ISSUE TITLE
parallelize tool may hang or crash

### ISSUE THREAD

**Issue by gix** [microsoft/STL#1619]
**Describe the bug**
Adding batching of input files to the parallelize tool for my own needs (cuts the runtime for clang-format in half for me), I believe I encountered two issues:

1. Quite often it would crash upon returning from `p.wait_all()` since a kernel mode operation corrupted the stack. This goes away when using an explicit manual-reset event for `OVERLAPPED` in `output_collecting_pipe`.
2. It can hang on exit because the `output_collecting_pipe` destructor does not clear the `running` flag. The threadpool callback then starts another IO operation which never completes.

If useful, I can prepare a patch to fix these.

**Comment by StephanTLavavej** [comment]
A patch would be great - please submit a pull request when you're ready!

**Comment by StephanTLavavej** [comment]
I suspect this was the root cause of #257.

**Comment by BillyONeal** [comment]
> I suspect this was the root cause of #257.

It might contribute but I seem to recall getting hangs even when we ran it serially?
