### ISSUE TITLE
<atomic>: leads to compilation error C2437 ('_Base' already initialized)

### ISSUE THREAD

**Issue by Cygon** [microsoft/STL#1673]
**Describe the bug**
I am creating a array of atomic chars like this: `new std::atomic<std::uint8_t>[capacity];`

This compiles cleanly on clang 11.0.0, gcc 9.3.0, gcc 10.2.0 and the Visual C++ compiler Visual Studio 2017 Community in its currently latest update.

Using "Visual Studio Build Tools 2019", Version 16.8.5 with cl.exe 19.28.29337, the aforementioned code snippet results in the error:
```
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\include\atomic(2163,1): error C2437: '_Base': has already been initialized
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\include\atomic(2163): note: while compiling class template member function 'std::atomic<unsigned char>::atomic(void) noexcept'
```

The error happens here: https://github.com/microsoft/STL/blob/834baa6acacb8325367e255b0728c582c7e443ff/stl/inc/atomic#L1415-L1421
The changes discussed in issue #336 may be related

**Command-line test case**
See attached `.zip` file (_sorry, I tried hard but was not able to create a single-file reproduction case_)
[Microsoft-STL-Atomic-Header-C2437-Repro.zip](https://github.com/microsoft/STL/files/6022466/Microsoft-STL-Atomic-Header-C2437-Repro.zip).
The included `build.cmd` contains the full `cl.exe` parameter list, though the parameters shown below suffice.

```
C:\Temp>type ConcurrentRingBuffer.MPMC.inl
...
      std::uint8_t *buffer = new std::uint8_t[sizeof(TElement[2]) * capacity / 2U];
      {
        auto itemMemoryDeleter = ON_SCOPE_EXIT_TRANSACTION {
          delete[] buffer;
        };
        this->itemStatus = new std::atomic<std::uint8_t>[capacity]; // <-- C2437 in <atomic> header here
        itemMemoryDeleter.Commit(); // disarm the item memory deleter
      }
      this->itemMemory = reinterpret_cast<TElement *>(buffer);
...

C:\Temp>cl /EHsc /W4 /WX /std:c++17 /utf-8 .\main.cpp
Microsoft (R) C/C++ Optimizing Compiler Version 19.28.29337 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

main.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\include\atomic(2163,1): error C2437: '_Base': has already been initialized
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\include\atomic(2163): note: while compiling class template member function 'std::atomic<unsigned char>::atomic(void) noexcept'
...
```

**Expected behavior**
I expect the reproduction code to compile without any errors, like it does on older versions of the Visual C++ compiler and other compilers tested.

**STL version**
Visual Studio Build Tools 2019
16.8.5
(latest one available via Visual Studio Installer Version 2.8.3077.1211 as of 2021-02-21)

**Additional context**
Since the error location already mentions workarounds for a compiler issue, this may well turn out to be an interaction between very specific STL code and a compiler issue.

**Comment by statementreply** [comment]
Reproduced without `<atomic>`. Looks like a complier bug.

https://godbolt.org/z/9c1r4j
```cpp
struct A {};

template <bool>
using Select = A;

#ifdef WORKAROUND
template <typename>
using Base = Select<true>;
#else
template <typename>
using Base = Select<!false>;
#endif

template <typename T>
struct B : public Base<T> {
    B() : Base<T>() {}
};

void test(A* a) {
    (void) [&] {
        a->~A();
        B<int> b;
    };
}
```
```
C:\Users\He\source\test\GH-1673>cl /W4 /std:c++17 /c test.cpp
用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.28.29828 版
版权所有(C) Microsoft Corporation。保留所有权利。

test.cpp
test.cpp(16): error C2614: “B<int>”: 非法的成员初始化:“Base<int>”不是基或成员
test.cpp(16): note: 在编译 类 模板 成员函数“B<int>::B(void)”时
test.cpp(22): note: 查看对正在编译的函数 模板 实例化“B<int>::B(void)”的引用
test.cpp(22): note: 查看对正在编译的 类 模板 实例化“B<int>”的引用

C:\Users\He\source\test\GH-1673>cl /W4 /std:c++17 /DWORKAROUND /c test.cpp
用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.28.29828 版
版权所有(C) Microsoft Corporation。保留所有权利。

test.cpp
```

**Comment by StephanTLavavej** [comment]
Thanks! This compiler bug should be reported to [Developer Community](https://developercommunity2.visualstudio.com/report?space=62&entry=problem).

**Comment by Cygon** [comment]
I've reported the issue on Visual Studio Feedback borrowing @statementreply 's much simpler reproduction case (thanks!):

https://developercommunity2.visualstudio.com/t/compiler-confuses-base-class-causing-error-c2437-i/1346618
