### ISSUE TITLE
<optional>: Potential constraint recursion for operator<=>(const optional<T>&, const U&)

### ISSUE THREAD

**Issue by CaseyCarter** [microsoft/STL#1674]
While implementing `<=>` support for `std::optional` we stumbled across what appears to be constraint recursion for the `operator<=>` signature specified in [[optional.comp.with.t]/25](http://eel.is/c++draft/optional.comp.with.t#25) when the second argument is a specialization of `optional`. Specifically, checking `three_way_comparable_with` seems to recurse via checking the constraint that e.g. `<` is viable for `operator<(const optional<T>&, const optional<U>&)`, which it certainly is if `<=>` is provided by the first signature. We avoided the recursion by adding an additional constraint to the first signature requiring that `U` is not a specialization of `optional`, which is checked before the `three_way_comparable_with` constraint.

https://github.com/microsoft/STL/blob/4c862ee11ce956556b810a813e77b0f8f97fb642/stl/inc/optional#L646-L650

Looking at it now (with the workaround disabled) the recursion only manifests when compiling with Clang. Given how differently Clang and MSVC handle C++20 relational operator rewrites it's not clear to me if the constraint recursion is real or an artifact of said rewrites in Clang. We need to reduce this to something library-free and then determine whether the bug is in Clang or the C++ Standard and deal with it appropriately. (I will nonetheless tag this "LWG issue needed" for the time being.)

**Comment by jwakely** [comment]
I think this is a defect in the standard library. Libstdc++ is [missing](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=98842) the `three_way_comparable_with<U,T>` constraint on `operator<=>(const optional<T>&, const U&)` but once I add it, GCC also hits this constraint recursion (and an ICE).

**Comment by CaseyCarter** [comment]
I've submitted an LWG issue for this defect - with our workaround as proposed resolution - and will report back here when LWGChair assigns an issue number.

**Comment by CaseyCarter** [comment]
This is LWG-3566; #2011 updates the comment in `<optional>` to refer to the LWG issue and closes this issue.
