### ISSUE TITLE
P2162R2 Inheriting From `variant`

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#1683]
[P2162R2](https://wg21.link/P2162R2) Inheriting From `variant`

Feature-test macro:
`#define __cpp_lib_variant 202102L`

**Comment by CaseyCarter** [comment]
This proposal almost exactly says "do what Microsoft's `std::visit` does" so this should be an easy "audit to be sure everything is kosher and update the feature-test macro" job.
