### ISSUE TITLE
P2259R1 Repairing Input Range Adaptors And counted_iterator

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#1684]
[P2259R1](https://wg21.link/P2259R1) Repairing Input Range Adaptors And `counted_iterator`

**Comment by cpplearner** [comment]
This paper resolves LWG-3283, LWG-3289, and LWG-3408. It should probably be treated as a DR and applied to C++20.

**Comment by StephanTLavavej** [comment]
@CaseyCarter confirmed on Discord:

> Oh, there's no question: we should treat it as a DR since the adaptors don't work otherwise. We've already implemented something to get them working (lots of `// TRANSITION, LWG-3289` stuff), which IIRC is quite close to the "things that aren't C++17 iterators have no `iterator_category`" design in the proposal.
