### ISSUE TITLE
<string>: constexpr basic_string is unimplementable as specified

### ISSUE THREAD

**Issue by CaseyCarter** [microsoft/STL#1699]
Per the ongoing work in #1502, `basic_string` cannot be made to work in constant expressions without additional changes to the character traits class. Specifically, we've had to modify `char_traits::assign(s,n,c)` (for all library-defined specializations of `char_traits`) to create new objects with value `c` rather than assigning that value to existing objects. (This may not be the only necessary change, we need to audit #1502 for any other fallout.)

**Comment by frederick-vs-ja** [comment]
This is probably resolved by #3334, and probably no there is need to change all `traits_type::assign`.
