### ISSUE TITLE
_NODISCARD should appear before __declspec

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#1702]
@JonCavesMSFT reported:

> My recent PR to add a warning for uses of `[[nodiscard]]` that are ignored, C5240, has shown up an issue with the self-build:
>
> The header file `<memory_resource>` contains the following line:
>
> https://github.com/microsoft/STL/blob/52b7b3205fb8542b664bdeca3e90bbee5677ba2c/stl/inc/memory_resource#L47
>
> Which causes the compiler to emit the new warning: and if you currently call the function as follows:
>
> ```cpp
> void f()
> {
>     null_memory_resource();
> }
> ```
>
> Then no warning about discarding the return value is emitted.
>
> If I change the declaration of `null_memory_resource` to:
>
> ```cpp
> extern "C" _NODISCARD _CRT_SATELLITE_1 memory_resource* __cdecl null_memory_resource_2() noexcept;
> ```
>
> Then the new warning is not emitted and the call to the function does emit, "C4834: discarding return value of function with 'nodiscard' attribute".
>
> To unblock the self-build I will, for now, make this warning off-by-default.

`_CRT_SATELLITE_1` is defined to be `__declspec(dllexport)` or nothing in `crtdefs.h`; the issue is with an attribute like `[[nodiscard]]` occuring after a `__declspec`.

I observe that this also affects a lot of Special Math machinery.

**Comment by StephanTLavavej** [comment]
Note that this isn't an issue for users, because `_CRT_SATELLITE_1` is defined to be nothing (after our overhaul to avoid `__declspec(dllimport)` for functions - it remains only for classes and data).

I found 2 occurrences of `__declspec` before `[[deprecated]]` on classes:
https://github.com/microsoft/STL/blob/52b7b3205fb8542b664bdeca3e90bbee5677ba2c/stl/inc/xlocale#L847-L849
It appears that the attribute takes effect either way here, but I think we should make this consistent.

**Comment by JonCavesMSFT** [comment]
Classes are different: there is no _decl-specifier-seq_ for the attribute to appertain to (the problem with functions is that the greedy _decl-specifier-seq_ grabs the attribute instead of leaving it for the complete declaration). So for a class the order doesn't matter but I agree being consistent is good.

**Comment by StephanTLavavej** [comment]
Ah, thanks for the explanation. I had to revert that change because of Clang; we'll need to report a bug if we want to clean that up.
