### ISSUE TITLE
<memory>: ranges::uninitialized_copy and ranges::uninitialized_move fail to compile with trivial types

### ISSUE THREAD

**Issue by AdamBucior** [microsoft/STL#1712]
**Describe the bug**
`ranges::uninitialized_copy` and `ranges::uninitialized_move` fail to compile with trivial types, common first range and non-common second range.

**Code**
```
#include <memory>
#include <ranges>

using namespace std;

int main() {
    int arr[3]{0, 1, 2};
    int arr2[3];

    ranges::uninitialized_copy(begin(arr), end(arr), begin(arr2), unreachable_sentinel);
}
```

**Expected behavior**
Should compile fine.

**STL version**
Microsoft Visual Studio Community 2019 Preview
Version 16.10 Preview 1

**Comment by miscco** [comment]
What is not tested is broken. 

We are currently checking for the memory optimization with this:
```cpp
if constexpr (is_same_v<_Se, _It> && _Ptr_move_cat<_It, _Out>::_Really_trivial) {
```

This obviously does not account for whether the output range is common. The easy solution is to add `is_same_v<_Out, _Se2>`

That said, I wonder whether we should expand the optimization up to `sized_sentinel_for`

**Comment by CaseyCarter** [comment]
> That said, I wonder whether we should expand the optimization up to `sized_sentinel_for` @CaseyCarter

That seems correct given that these algorithms always traverse the ranges from beginning to end so they don't care if the sentinel is or is not an iterator. Commonality is being used here only because it implies (together with the `contiguous_iterator` requirement) `sized_sentinel_for`.
