### ISSUE TITLE
std::string_view visualizer is incomplete and inconsistent with std::string

### ISSUE THREAD

**Issue by AnjuDel** [microsoft/STL#1715]
Visual Studio supports debug visualizers of many C++ library types, including std::string and std::string_view.
Unfortunately the visualizer of std::string_view is incomplete and inconsistent with the std::sting one: it does not allow to open the data in the “Text Visualizer” window.

Steps to reproduce:

Compile the following code in C++17 or Preview mode (project properties - C/C++ - Language - C++ Language Standard):

```cpp
#include <string>
#include <string_view>

int main()
{
	std::string a = "12345";
	std::string_view b = a;

	return 0;
}
```

Put a breakpoint on the last line
Start debugging
Go to the “Autos” window
Pay attention to “a” and “b” variables there, in particular:
– “a” does have a magnifier icon on the right that allows to view its value in the Text Visualizer window
– the physical address of “a” is hidden (because it’s useless in this context)
– “b”, on the contrary, does not have the magnifier icon on the right and therefore does not allow to view its value in the Text Visualizer window. This makes inspecting long strings incredibly painful, because they simply do not fit into that tiny single line.
– the physical address of “b” is visible, which is useless in this context and inconsistent with “a”.

**Comment by StephanTLavavej** [comment]
@AnjuDel fixed this with VS-internal https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/308324 which will ship in VS 2019 16.10 Preview 2 (I am 99% sure).
