### ISSUE TITLE
We should build the STL with /ZH:SHA_256

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#1734]
@sylveon observed that Microsoft's [BinSkim](https://github.com/microsoft/binskim) tool emits "warning BA2004" for the STL's import library (specifically `filesystem.obj`, `nothrow.obj`, and `syserror_import_lib.obj` in `msvcprt.lib`). [This says:](https://github.com/microsoft/binskim/blob/main/src/BinSkim.Rules/RuleResources.resx#L473-L483)

> Compilers can generate and store checksums of source files in order to provide linkage between binaries, their PDBs, and associated source code. This information is typically used to resolve source file when debugging but it can also be used to verify that a specific body of source code is, in fact, the code that was used to produce a specific set of binaries and PDBs. This validation is helpful in verifying supply chain integrity. Due to this security focus, it is important that the hashing algorithm used to produce checksums is secure. Legacy hashing algorithms, such as MD5 and SHA-1, have been demonstrated to be broken by modern hardware (that is, it is computationally feasible to force hash collisions, in which a common hash is generated from distinct files). Using a secure hashing algorithm, such as SHA-256, prevents the possibility of collision attacks, in which the checksum of a malicious file is used to produce a hash that satisfies the system that it is, in fact, the original file processed by the compiler. [...] For native binaries, pass '/ZH:SHA_256' on the cl.exe command-line to enable secure source code hashing.

[MSVC's `/ZH` documentation](https://docs.microsoft.com/en-us/cpp/build/reference/zh?view=msvc-160) explains that `/ZH:MD5` is the default, and:

> Because of a risk of collision problems in MD5 and SHA-1, Microsoft recommends you use the **/ZH:SHA_256** option. The SHA-256 hash may result in a small increase in compile times. [...] The **/ZH** option is available starting in Visual Studio 2019 version 16.4.

We should build everything in the STL with this compiler option. Note that we'll need to modify both the modern CMake build system and the legacy MSBuild build system.

**Comment by sylveon** [comment]
I filled DevCom-1369173 for the equivalent issue with the CRT
