### ISSUE TITLE
invoke_result_t has no type define.

### ISSUE THREAD

**Issue by clover-storm** [microsoft/STL#1741]
using invoke_result_t, there is a compile error.

```
template <class _Callable, class... _Args>
using invoke_result_t = typename _Select_invoke_traits<_Callable, _Args...>::type;
```

in case, **_Invoke_traits_zero**

```
template <class _Callable, class... _Args>
using _Select_invoke_traits = conditional_t<sizeof...(_Args) == 0, _Invoke_traits_zero<void, _Callable>,
    _Invoke_traits_nonzero<void, _Callable, _Args...>>;
```

there is no "type" type define.

```
template <class _Callable>
struct _Invoke_traits_zero<void_t<_Decltype_invoke_zero<_Callable>>, _Callable>
    : _Invoke_traits_common<_Decltype_invoke_zero<_Callable>, noexcept(_STD declval<_Callable>()())> {};

```

any idea?

**Comment by StephanTLavavej** [comment]
`type` is provided by the `_Invoke_traits_common` base class: https://github.com/microsoft/STL/blob/c5ee3b32bd3ee219b6d93d72f24429ae6e240ced/stl/inc/type_traits#L1669-L1671

Can you provide a self-contained example where `invoke_result_t` doesn't seem to be providing a `type`? Then we can inspect your callable object and argument types, and determine what's happening. This machinery has been extensively tested.

**Comment by clover-storm** [comment]
Oh my mistake, yes you're right. it was

```
template <class _Void, class _Callable>
struct _Invoke_traits_zero {
    // selected when _Callable isn't callable with zero _Args
    using _Is_invocable         = false_type;
    using _Is_nothrow_invocable = false_type;
    template <class _Rx>
    using _Is_invocable_r = false_type;
    template <class _Rx>
    using _Is_nothrow_invocable_r = false_type;
};
```

I tried to write some example codes but I'm not good at using traits :(

**Comment by StephanTLavavej** [comment]
No problem, this stuff can be confusing! Unfortunately, the STL is only able to detect whether something is callable with given args - if it's not, we can't report why. (The reason might be that there is no function call operator, that there aren't enough or too many args, that the args aren't convertible, that the function call operator is inaccessible, etc.)
