### ISSUE TITLE
<algorithm>: Use ranges::partition_point's probing technique in the binary-search algorithm family

### ISSUE THREAD

**Issue by CaseyCarter** [microsoft/STL#1755]
The implementation of `ranges::partition_point` for unsized ranges:

https://github.com/microsoft/STL/blob/2d890fdadde44bdb8eced76f29803ce2ecbe0378/stl/inc/algorithm#L2084-L2114

uses a technique in which it probes elements at the end of intervals that increase exponentially in size looking for an element that is demonstrably past the target element in the input sequence, after which it performs binary subdivision of the (now smaller) subrange to locate the target. This can improve performance relative to an implementation that traverses the entire sequence to calculate its length before performing binary subdivision over the entire sequence to locate the target element, when the input sequence is not a `sized_range`.

We should implement a similar initial exponential probing phase for `std::partition_point` and all `std` / `ranges` algorithms in the "binary search" family (`lower_bound`, `upper_bound`, `equal_range`, `binary_search`) when they operate on ranges that are not sized / iterators that cannot be differenced.

**Comment by BillyONeal** [comment]
Does that comply with http://eel.is/c++draft/lower.bound#4 ? (Note that it's an exact count, not big-O or big-Theta)

**Comment by CaseyCarter** [comment]
> Does that comply with http://eel.is/c++draft/lower.bound#4 ? (Note that it's an exact count, not big-O or big-Theta)

Off the cuff, no. I think the worst case (searching for the last element) needs `log(N)` probes, then `log(N/2) + O(1)` compares to subdivide, which is `2 * log(N) + O(1)` comparisons in total. The average case (assuming uniform distribution of the target value in the range) I believe is the same, the performance benefit is primarily from reducing iterator and sentinel operations. All of which suggests that there's more here than a simple change, or even a simple LWG issue. This needs a short paper with some complexity analysis for LEWG, which makes it interesting but out-of-scope for the STL repo.
