### ISSUE TITLE
<vector>: _ITERATOR_DEBUG_LEVEL could detect forbidden aliasing

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#177]
WG21-N4830 [tab:container.seq.req]: "`a.assign(n,t)` *Expects:* [...] `t` is not a reference into
`a`."

This means that `v.assign(5, v[0])` is undefined behavior. We can't detect every possible occurrence of this (I can easily devise unusual ownership scenarios), but because `vector` is contiguous, we could easily add an address range check that would detect common forms of aliasing. For other sequence containers, checking would be more costly, so it may be counterproductive.

We should consider investigating all member functions where aliasing is forbidden, and seeing how much validation we can perform.

**Comment by miscco** [comment]
I would guess that this also applies for all derivations of `std::copy`?

**Comment by StephanTLavavej** [comment]
That's a good suggestion. Yes, the algorithms that forbid overlapping ranges (either completely, or in certain directions as is the case for `copy()`) could be enhanced to detect this for contiguous iterators including pointers, and it would be reasonable to do so as part of addressing this issue.

**Comment by StephanTLavavej** [comment]
Another example that should detect overlapping ranges:
https://github.com/microsoft/STL/blob/d0d724fb916c59f1c4f2830330ed967a72d2d2b8/stl/inc/algorithm#L1264-L1273
