### ISSUE TITLE
<chrono>: Perform cleanups identified during code review

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#1805]
While reviewing #1789, @CaseyCarter noticed several things in `<chrono>` that could be cleaned up. None of them are correctness issues or have ABI impact, so we're filing a followup issue.

Also while reviewing #1870, @mnatsuhara identified several good cleanups. @CaseyCarter also found some things to clean up with comments in https://github.com/microsoft/STL/pull/1870#pullrequestreview-642642435.

One more issue (noticed while explaining a `decltype`) - the occurrences of `decltype(tzdb::zones)` and `decltype(tzdb::links)` are relics of an earlier attempt to use special allocators (which was foiled by the Standard's insistence on `std::allocator` here). It would probably be simpler to replace these with their actual types. Example occurrences:

https://github.com/microsoft/STL/blob/dde4623b98d3af3aeeff0371c130d028d4cb5d33/stl/inc/chrono#L2607
https://github.com/microsoft/STL/blob/dde4623b98d3af3aeeff0371c130d028d4cb5d33/stl/inc/chrono#L2618-L2619

**Comment by CaseyCarter** [comment]
I made some nitpicky comments reviewing #1870, none of which are significant enough to delay merging. Nevertheless, at some point we should followup on the comments in https://github.com/microsoft/STL/pull/1870#pullrequestreview-642642435.

**Comment by StephanTLavavej** [comment]
I finally have changes for this.
