### ISSUE TITLE
Implementing a proposal.

### ISSUE THREAD

**Issue by hatcat** [microsoft/STL#1813]
I am interested in implementing P1385D7 in this library due to my total lack of experience with libc++ or libstdc++. Beyond forking and tinkering away, can you offer any advice?

http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/p1385r6.pdf for reference (things have come on quite a bit since this)

**Comment by miscco** [comment]
Hi Guy,

as far as I can tell, @StephanTLavavej mentioned that we would welcome, if there were reference implementations for proposals for the MSVC STL. However, the current suggestion was to create a branch in the private for of the repo and gather feedback there.

As an example I have written a reference implementation for P2283R1 [here](https://github.com/miscco/STL/pull/2)

**Comment by hatcat** [comment]
Many thanks. I will proceed thus.

**Comment by hatcat** [comment]
(Leaving open in case other commentary is offered: feel free to close on April 19th.)
