### ISSUE TITLE
src: Change C casts to C++ casts

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#184]
We've cleaned up the `inc` headers to always use C++ casts. We need to do the same for the `src` source files.

**Comment by ranolfi** [comment]
I would like to take on this. I don't see in the repo history a commit or series of commits for this refactoring you mentioned - can you point me to it?

**Comment by StephanTLavavej** [comment]
Thank you! Unfortunately, we aren’t able to make our pre-GitHub commit history public, but the header changes were simply performed by grepping for C cast syntax, and replacing each occurrence with `static_cast`, `const_cast`, and/or `reinterpret_cast` as described by https://eel.is/c++draft/expr.cast#4 . (Careful attention is occasionally required, e.g. to avoid using `reinterpret_cast` when `static_cast` suffices.) In some cases, we changed the code to avoid the need for any casting.

**Comment by ranolfi** [comment]
Oh, I  figured. Thanks for clarifying.

> the header changes were simply performed by grepping for C cast syntax

Pretty much what I've been doing. If only we could run g++ `-Wold-style-cast` on it. :)

Ok, will report later. For this issue, a single commit with all of the changes should be alright, correct?

**Comment by StephanTLavavej** [comment]
Clang is supported for `inc`, but not for `src`. (It can't be in general due to the `/clr` support machinery, which is not yet built by our CMake build system.) However, attempting to build `src` with Clang `-Wold-style-cast` is a good idea.

**Comment by StephanTLavavej** [comment]
There are at least 2 remaining C casts:
https://github.com/microsoft/STL/blob/c12089e489c7b6a3896f5043ed545ac8d1870590/stl/src/filesys.cpp#L37
https://github.com/microsoft/STL/blob/c12089e489c7b6a3896f5043ed545ac8d1870590/stl/src/filesys.cpp#L65

**Comment by StephanTLavavej** [comment]
I believe that all C casts have been changed or removed now.
