### ISSUE TITLE
STL: Finish supporting /Wall

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#186]
For aeons, the STL has supported `/W4` but not `/Wall`, because `/Wall` contains many noisy warnings, some of which aren't meant to be used regularly. Nevertheless, some customers prefer to use `/Wall`, leading to persistent requests for support.

After we overhauled the STL's warning suppression machinery, supporting `/Wall` became much more thinkable, and we committed a number of improvements short of full support. More recently, the UCRT and VCRuntime are being cleaned up for `/Wall`, so we should investigate completing this work for the STL. This will also involve adding `/Wall` test coverage, which may be a significant amount of work.

Also tracked by DevCom-1080802 (see below) and Microsoft-internal VSO-1151642 / [AB#1151642](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1151642).

**Comment by fsb4000** [comment]
From DevCom-1080802 :

```
#include <locale> 
#include <string> 
#include <sstream> 
int main() { 
    std::string de_double = "1.234.567,89"; 
    // parse using streams 
    std::istringstream de_in(de_double); 
    de_in.imbue(std::locale("de_DE")); 
    double f1; 
    de_in >> f1; 
}
```
Customer's example doesn't warn with
`/W4 /O2`
but warn with 
`/W4 /w14165 /w24826 /w34738 /w44062 /w45038 /O2`
(without /O2 or /O1 it also doesn't warn)

**Comment by StephanTLavavej** [comment]
I think we need to decide whether to spend any time here.

**Comment by StephanTLavavej** [comment]
We talked about this at the weekly maintainer meeting and have decided not to spend any time here. We're keeping the status quo, where the STL does *not* attempt to be `/Wall` clean. We'll continue to consider adding silencing and test coverage for individual off-by-default warnings on a case-by-case basis, if there's a compelling case that they are high value and low noise.

**Comment by frederick-vs-ja** [comment]
I think it's MSVC's bug to raise C4738 for the example in DevCom-1080802, as the warning is only raised for x86 `/O1` or x86 `/O2`.
