### ISSUE TITLE
winapinls.cpp: Fuse nlsdownlevel.h and remove C idioms

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#188]
[winapinls.cpp](https://github.com/microsoft/STL/blob/957fe99f41748b80c3108447e5dd5ce2be962f4e/stl/src/winapinls.cpp) is the only file that includes [nlsdownlevel.h](https://github.com/microsoft/STL/blob/957fe99f41748b80c3108447e5dd5ce2be962f4e/stl/src/nlsdownlevel.h). We should fuse them together and remove the C idioms.

**Comment by chris0x44** [comment]
Hi there! Is this issue still available? If so, I'd like to take it.
