### ISSUE TITLE
Is there any way to get the CreatedAt timestamp exposed via std::filesystem's directory iterators?

### ISSUE THREAD

**Issue by jeremyong** [microsoft/STL#1880]
I noticed that `std::filesystem::directory_entry` doesn't have any mechanism to retrieve the timestamp when a file was created. Furthermore, this feature seems to be entirely absent from the entire filesystem module. However, the windows implementation at least seems to have this information which is simply discarded.

Ideally, this would be added to the standard, but barring that, would the maintainers be open to exposing that data as a non-standard extension?

**Comment by StephanTLavavej** [comment]
Thanks for asking - there's no "native handle" functionality, so this isn't possible in the current implementation.

> would the maintainers be open to exposing that data as a non-standard extension?

We generally avoid adding non-Standard extensions - they encourage non-portable code and they're a headache to maintain as the Standard evolves. This is listed in our [Non-Goals](https://github.com/microsoft/STL#non-goals).
