### ISSUE TITLE
<bit>: endian

### ISSUE THREAD

**Issue by dgengin** [microsoft/STL#1881]
The endian enum class is being included with the most common headers (string, vector) when using /std:c++latest
I'm using this which has a namespace with a conflicting name:
https://github.com/steinwurf/endian

```c++
#include <stack>

int main()
{
	// should this code compile?
	auto e = std::endian::little;
}
```

Visual Studio 16.9.4

Is this the expected behavior in C++20 or is it just being included when it shouldn't? It was working fine with some previous versions using the same settings.

**Comment by MikeGitb** [comment]
Any standard library header may include any other header, so yes, there is nothing in the standard saying that example must not work. 
But conversely there is nothing promising that it will work either.

**Comment by sylveon** [comment]
Also, I'm not sure how this is conflicting, unless you're doing `using namespace std`.

**Comment by dgengin** [comment]
I'm not using `using namespace std`. the conflict comes from the enum `endian` that is defined by `<stack>` and the namespace `endian` that's defined in that library. to use any function in it, you have to do: `endian::func_name`.

**Comment by MikeGitb** [comment]
But why does your function `endian::little` conflict with `std::endian::little` without a using namespace std;?5

**Comment by dgengin** [comment]
You're right. I was also including another header that's doing `using namespace std`: https://github.com/justinhj/astar-algorithm-cpp/

I removed that using from that file and there's no conflict now. Thanks.

**Comment by sylveon** [comment]
`times_someone_was_burned_by_header_using_namespace_std++;`

**Comment by sylveon** [comment]
I created an issue in that repo

**Comment by MikeGitb** [comment]
> This software has been used in AAA video games and is well tested in the wild.

Hard to believe that no one else ran into this problem. I think this is the first time I've seen this problem in production code

**Comment by CaseyCarter** [comment]
Looks like this is external and was reported as https://github.com/justinhj/astar-algorithm-cpp/issues/27. Feel free to follow-up there.

**Comment by justinhj** [comment]
> > This software has been used in AAA video games and is well tested in the wild.
> 
> Hard to believe that no one else ran into this problem. I think this is the first time I've seen this problem in production code (counting my luck)

I guess if it was ever an issue the user simply deleted the using statement from the header. Nobody reported it to me so I never noticed. Thanks for pointing it out!
