### ISSUE TITLE
`<cmath>`: New intrinsics broke CUDA

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#1885]
When #1336 added usage of new intrinsics to `<cmath>`, we forgot about CUDA. :scream_cat: (Long ago, we broke CUDA by adding new type traits intrinsics in C++14 mode, but these math functions were just different enough that I didn't remember the interaction. Oops!)

I'm not exactly sure why our CUDA unit test didn't catch this, given that the affected overloads aren't templates:

https://github.com/microsoft/STL/blob/f675d68f03cfb7a303cd5408502f2642947d32b7/stl/inc/cmath#L62-L70

We are including `<cmath>`, so there's probably some detail of the CUDA compilation process that I don't understand:

https://github.com/microsoft/STL/blob/f675d68f03cfb7a303cd5408502f2642947d32b7/stl/inc/__msvc_all_public_headers.hpp#L156
https://github.com/microsoft/STL/blob/f675d68f03cfb7a303cd5408502f2642947d32b7/tests/std/tests/GH_000639_nvcc_include_all/test.compile.pass.cpp#L4-L6

In any event, fixing this should be easy, we just need to backport it to VS 2019 16.9.

Originally encountered in https://github.com/pytorch/pytorch/issues/54382 and tracked by Microsoft-internal VSO-1314894 / AB#1314894 .

**Comment by sylveon** [comment]
I believe the CI did not catch this because it only seems to happen when building device code, not host code (not familiar with CUDA but the error message seems to imply this)

**Comment by EricAtORS** [comment]
Is this related as well?
https://devtalk.blender.org/t/cuda-compile-error-windows-10/17886

I experienced that issue with other cuda as well, but the suggestion to switch from floor to floorf made it compile.

**Comment by sylveon** [comment]
Yes, `floorf` is unaffected because it comes from the UCRT, which the PR couldn't update since it isn't open source.

**Comment by IngmarVoigt2** [comment]
Hi @StephanTLavavej,

is this already on the latest Visual Studio releases? You mentioned this should be backported to v16.9, no? If not do you know when we could expect this to be released? I neither saw this on the release notes for [v16.9](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-v16.9) nor for [v16.10](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes).

Thx a lot!

**Comment by IngmarVoigt2** [comment]
Nevermind, I realized it's already in 16.10.2 at least

**Comment by StephanTLavavej** [comment]
@IngmarVoigt2 Yep, this shipped in 16.10.0 and was backported to 16.9.7. The VS and MSVC release notes don't contain this level of detail, but the STL's Changelog does - see https://github.com/microsoft/STL/wiki/Changelog#vs-2019-1610 and search for the PR number #1886.
