### ISSUE TITLE
P0475R1 Guaranteed Copy Elision For Piecewise Construction

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#19]
[P0475R1](https://wg21.link/P0475R1) Guaranteed Copy Elision For Piecewise Construction

This should be implemented together with #20, [P0591R4](https://wg21.link/P0591R4) Utility Functions For Uses-Allocator Construction.

**Comment by ArtemSarmini** [comment]
I tested last example from this paper with 16.4.3, it compiles well. Does it mean this issue is noop?
