### ISSUE TITLE
`<chrono>`: formatting a duration fails to compile

### ISSUE THREAD

**Issue by mnatsuhara** [microsoft/STL#1903]
Observed by @statementreply.

`format("{}", duration<long long, femto>{})` fails to compile, though it should be valid. 

Discovered while implementing #12.

**Comment by StephanTLavavej** [comment]
This was fixed by @barcharcraz's #2814. Thanks @JMazurkiewicz for finding this! :heart_eyes_cat: :hammer_and_wrench: :tada:
