### ISSUE TITLE
Fix chronat tests to deal with locale-dependent time zones abbreviations

### ISSUE THREAD

**Issue by mnatsuhara** [microsoft/STL#1904]
chronat tests are failing on @statementreply's machine because time zone abbreviations are locale dependent; e.g. `"EST"` is instead `"GMT-5"` and `"EDT"` is instead `"GMT-4"`.  

We need to fix the tests to use a specific locale when testing the time zone format specifiers.

**Comment by statementreply** [comment]
I guess this depends on the language and region setting of Windows rather than C++ locale.

**Comment by fsb4000** [comment]
@statementreply is correct. The tests are failing for me too.

`python tests\utils\stl-lit\stl-lit.py ..\..\..\tests\std\tests\P0355R7_calendars_and_time_zones_formatting -v`

But if I change region to USA than tests pass.

1. Settings.
2. Time and Language.
3. Region
4. Set USA.

https://imgur.com/a/59BD6pi

**Comment by mnatsuhara** [comment]
Ah, thank you for the correction here!  I wasn't sure of the specific cause for the failures when I saw the card in the Chrono project, so I made my best guess.
