### ISSUE TITLE
Constexpr std::error_category constructor?

### ISSUE THREAD

**Issue by joelfrederico** [microsoft/STL#1922]
Any chance we’ll get a standard-compliant constexpr std::error_category constructor?

§19.5.1.1 [syserr.errcat.overview]
(C++17 standard, but apparently standard since C++11)

https://github.com/microsoft/STL/blob/18c12ab01896e73e95a69ceba9fbd7250304f895/stl/inc/system_error#L74

**Comment by StephanTLavavej** [comment]
Duplicate of #1116. Unfortunately, fixing this will break binary compatibility, so we need to wait for the "vNext" ABI-breaking release, which is not yet scheduled.

**Comment by joelfrederico** [comment]
Ah I’m sorry for the duplicate, my mistake.

**Comment by StephanTLavavej** [comment]
No worries! :smile_cat:
