### ISSUE TITLE
<type_traits>: std::as_const is improperly defined in C++14 and below

### ISSUE THREAD

**Issue by amyspark** [microsoft/STL#1925]
**Describe the bug**

`std::as_const`, [defined in the C++17 standard according to cppreference](https://en.cppreference.com/w/cpp/utility/as_const), is improperly available when using `/std:c++14` and below.

**Command-line test case**
```
C:\Temp>type repro.cpp

#include <type_traits>

namespace std {

// from C++17

#if (__cplusplus < 201703L)

template <typename...> using void_t = void;

template <class T> constexpr std::add_const_t<T> &as_const(T &t) noexcept {
  return t;
}

template <class T> void as_const(const T &&) = delete;

#endif

template <bool is_const, class T> struct add_const_if {
  using type = std::conditional_t<is_const, std::add_const_t<T>, T>;
};

template <bool is_const, class T>
using add_const_if_t = typename add_const_if<is_const, T>::type;

} // namespace std

#include <cassert>
#include <string>
#include <type_traits>
#include <utility>

int main() {
  std::string mutableString = "Hello World!";
  auto &&constRef = std::as_const(mutableString);

  //  mutableString.clear(); // OK
  //  constRef.clear(); // error: 'constRef' is 'const' qualified,
  //        but 'clear' is not marked const

  assert(&constRef == &mutableString);
  assert(&std::as_const(mutableString) == &mutableString);

  using ExprType =
      std::remove_reference_t<decltype(std::as_const(mutableString))>;

  static_assert(std::is_same<std::remove_const_t<ExprType>, std::string>::value,
                "ExprType should be some kind of string.");
  static_assert(!std::is_same<ExprType, std::string>::value,
                "ExprType shouldn't be a mutable string.");
}

C:\Temp>cl /EHsc /W4 /WX /std:c++14 /Zc:__cplusplus .\repro.cpp
Compilador de optimización de C/C++ de Microsoft (R) versión 19.28.29915 para x64
(C) Microsoft Corporation. Todos los derechos reservados.

main2.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\utility(610): error C2995: 'add_const<_Ty>::type &std::as_const(T &) noexcept': ya se ha definido la plantilla de función
.\main2.cpp(42): note: vea la declaración de 'std::as_const'
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\utility(615): error C2995: 'void std::as_const(const T &&)': ya se ha definido la plantilla de función
.\main2.cpp(46): note: vea la declaración de 'std::as_const'
```

**Expected behavior**

If the C++ standard isn't C++17, the monkey patch should be successfully applied. If not, it should be skipped, as per the guard clause.

**STL version**
    ```
    Microsoft Visual Studio Community 2019
    Versión 16.9.5
    ```

**Additional context**

This bug still appears in:
```
Microsoft Visual Studio Community 2019 Preview
Versión 16.10.0 Preview 3.0
```

**Comment by fsb4000** [comment]
Perhaps on purpose.
Some traits also available in c++14 mode.

For example: is_lvalue_reference_v is c++17 feature but it is also available for c++14

https://en.cppreference.com/w/cpp/types/is_lvalue_reference

See example: https://gcc.godbolt.org/z/xa9bz3oxY

But I'm not an MSVC employee, maybe I'm wrong...

And https://github.com/microsoft/STL/blob/main/stl/inc/type_traits has some 
```
#if _HAS_CXX17
```

**Comment by MikeGitb** [comment]
That's not an explanation for the error you are experiencing, but FYI:

- msvc doesn't define __cplusplus correctly unless you specify `/Zc:__cplusplus`
- Adding anything to the std namespace is UB, so - as far as the standard is concerned (the Microsoft team might provide additional guarantees) - you have no guarantee whatsoever that this is going to work.

**Comment by CaseyCarter** [comment]
This is by-design: our "C++14" mode is actually "C++14 and the parts of C++17 that were implemented before we added language version modes." This ensures that all programs that compiled successfully before adding language modes continue to compile successfully after.

The correct way to "polyfill" newer feature support is to use a namespace other than `std` - I often suggest `notstd` - and conditionally either define names or pull them in from `std` via `using` declarations or alias templates.
