### ISSUE TITLE
<chrono>: Missing parse overloads

### ISSUE THREAD

**Issue by HowardHinnant** [microsoft/STL#1928]
**Describe the bug**

A new LWG issue was just filed because of a defect in the C++20 chrono `parse` overloads.

https://cplusplus.github.io/LWG/issue3554

As I write this, the issue hasn't been looked at by the LWG.  I am hopeful for a quick P0 resolution.  The recommended wording in the issue has been implemented at https://github.com/HowardHinnant.

**Command-line test case**

This should work:

```
in >> parse("%F %T", tp);
```

where `tp` is `system_clock::time_point` and `in` is any `istream`.  Right now it doesn't work because `parse` is lacking an overload to take the format string literal.

**Comment by StephanTLavavej** [comment]
I think that there may be an issue in your Proposed Resolution:

```cpp
template<class charT, class traits, class Alloc, class Parsable>
  unspecified
    parse(const charT* fmt, Parsable& tp,
          basic_string<charT, traits, Alloc>& abbrev);
```

> Effects: Equivalent to `return parse(basic_string<charT, traits, Alloc>{fmt}, tp, abbrev);`

This depicts using the `abbrev`'s `Alloc` type for the temporary `basic_string`, but there's no guarantee that the user's `Alloc` is default-constructible. I believe that `Alloc` should not be used here. Possibly the `traits` from `abbrev` shouldn't be used either. (However, when the argument is `basic_string_view<charT, traits> fmt`, then using that `traits` is desirable.)

**Comment by HowardHinnant** [comment]
I agree that's an issue.  LWG3554 will likely be given P2 priority and the LWG (or LEWG) can sort it out.  Fwiw, no one has complained about my example implementation which has this characteristic:  https://github.com/HowardHinnant/date/blob/master/include/date/date.h#L8163-L8172

I think the main thing clients will care about is that they can use string literals for the `fmt` argument.
