### ISSUE TITLE
<vector>, <array>: Exception: 'read access violation' in _Orphan_range_unlocked() in Debug-mode

### ISSUE THREAD

**Issue by Spammed** [microsoft/STL#1934]
For DEBUG builds in MS Visual Studio 2019, Ver. 16.10.0, Toolset v142, I got with the code below an exception: 'read access violation' in _Orphan_range_unlocked() (possibly very similar to what is discussed here [https://stackoverflow.com/a/62605686/15157143)])

The problem does not occur if `arrvec` is not `static`. 
It does not fail with a `std::vector<int>` directly (not in an `array`). 
It does not fail with clang toolset nor in release nor in C++17 or in older VS versions
Because the exception only occurs in these very specific circumstances, I suspect there may be a bug in Visual Studio. 
Or is it a programming error after all? I would like to understand this.

```
#include <vector>
#include <array>

int main()
{
    // Exception: 'read access violation' in _Orphan_range_unlocked()
    // (in C++20 MSVC Debug builds but not in C++17 nor Release)

    static std::array<std::vector<int>, 4> arrvec;
    arrvec[0].reserve(3);
    arrvec[0].emplace_back(1);  // <- Exception occurs here
}
```

**Comment by CaseyCarter** [comment]
I wouldn't expect it to manifest in Release builds, `_Orphan_range_unlocked` is part of our iterator debugging machinery that's conditional compiled away in Release builds. This is almost certainly an MSVC compiler bug triggered by the changes we made in 16.10 to support `constexpr` `vector` and `string`. 

@miscco or @mnatsuhara, do you want to take a look at this regression?

**Comment by miscco** [comment]
I will look at it soon^TM

**Comment by Spammed** [comment]
With a large portion of hubris and hoping that this is 'only' a problem with _HAS_ITERATOR_DEBUGGING, I changed line 105 of file yvals.h to '#define HAS_ITERATOR_DEBUGGING 0'.
With this I can debug for the moment again.
(Otherwise I would have to get the VS previous VS version somewhere and install it, I think).

**Comment by miscco** [comment]
Is the `reserve` call necessary?

**Comment by miscco** [comment]
Note that this is nearly exactly the use case why we had to bring back the iterator debugging for vector at all. It seems that again the constructor is skipped and the proxy is not properly allocated

**Comment by CaseyCarter** [comment]
> With a large portion of hubris and hoping that this is 'only' a problem with _HAS_ITERATOR_DEBUGGING, I changed line 105 of file yvals.h to '#define _HAS_ITERATOR_DEBUGGING 0'.
> With this I can debug for the moment again.
> (Otherwise I would have to get the previous VS version somewhere and install it, I think).

The recommended/supported method for disabling iterator debugging is to define `_ITERATOR_DEBUG_LEVEL` to `0`. This can cause some weirdness interacting with `locale`s when linking against the DLL (`/MDd`) if you use non-default `locale`s you may need to switch to linking statically (`/MTd`) for your debug builds.

**Comment by Spammed** [comment]
@Casey: Thank you. I'm already build statically. (But, were exactly is to define _ITERATOR_DEBUG_LEVEL to 0? in yvals.h?)
@misco: Yes the call to reserve is necessary to provoke the exception.

**Comment by miscco** [comment]
@Casey I just tried it and indeed the constructor of the vector is not run properly.

Without a proxy allocated we end up crashing in `_Orphan_range` 

I believe this is similar to a bug we had when implementing constexpr vector, where the constructor would be skipped. I thought it fixed but I think we need to get some compiler support

**Comment by miscco** [comment]
@Spammed could I get you to file a developer community ticket as this is definitly a comiler bug

**Comment by miscco** [comment]
@Spammed I do not know if you controll the code, but a simple workaround would be to explicitly value initialize the array
```cpp
#include <array>
#include <vector>
using namespace std;

static array<vector<int>, 4> arrvec{}; all is fine on my side
int main() {
    arrvec[0].reserve(3);
    arrvec[0].emplace_back(1);
}
```

**Comment by CaseyCarter** [comment]
> @casey: Thank you. I'm already build statically. (But, were exactly is to define _ITERATOR_DEBUG_LEVEL to 0? in yvals.h?)

In your build / on the command line. 

> @Spammed could I get you to file a developer community ticket as this is definitely a compiler bug

I'll file it.

**Comment by CaseyCarter** [comment]
Filed DevCom-1433426.

**Comment by Spammed** [comment]
@miscco: The situation is (of course) a bit more complex than in the example code, but your solution seems easy to apply. Thank you very much, I will try it.
@CaseyCarter: OK, thanks to you too, the command line is a much more appropriate place for intervention.
I will be happy to follow up on this on Devcom.

**Comment by Spammed** [comment]
@miscco: Intializing the array solves my problem (it can be that simple).

One last question here for clarification: 

Should I consider not intializing the array as a **programming error** on my part or just my **bad style**?

**Comment by miscco** [comment]
@Spammed You can consider this a compiler bug. There should be no need for the explicit value-initialization

**Comment by davlovsky** [comment]
I'm still getting this Orphan error after five iterations, using push_back, into a private member vector variable. I've tried reinitializing it in the constructor, but it's still not working.

**Comment by StephanTLavavej** [comment]
@davlovsky Please provide your toolset version as displayed by `cl.exe`, a self-contained test case, and the command line.

**Comment by davlovsky** [comment]
@StephanTLavavej 
Toolset: Microsoft (R) C/C++ Optimizing Compiler Version 19.42.34435 for x64
I'm running this from inside of VS2022. 
I found a workaround by just making the member variable `static inline`.
