### ISSUE TITLE
<format>: does not accept enums as an argument

### ISSUE THREAD

**Issue by DmitryKo76** [microsoft/STL#1936]
Passing an enum to std::format results in compiler error C2664 in 16.11.0 Preview 1.0

```
#include <iostream>
#include <format>

int main()
{
enum CPP {CPP20 = 20};
std::cout << std::format("STL is now C++{} feature-complete!\n", CPP20);
}
```

> error C2664: ‘const char *std::_Get_format_arg_storage_type<_Context>(const char *)’: cannot convert argument 1 from ‘const _Ty’ to ‘const char *’
> Conversion from integral type to pointer type requires reinterpret_cast, C-style cast or function-style cast
> see declaration of ‘std::_Get_format_arg_storage_type’
> see reference to variable template ‘const size_t _Get_format_arg_storage_size<std::basic_format_context<std::back_insert_iterator<std::_Fmt_buffer<char> >,char>,enum main'::2’::CPP>’ being compiled
> see reference to class template instantiation ‘std::_Format_arg_store<_Context,main::CPP>’ being compiled
> see reference to function template instantiation ‘auto std::make_format_argsstd::format_context,main::CPP(const main::CPP &)’ being compiled
>  see reference to function template instantiation 'std::string std::format<main::CPP>(const std::string_view,const main::CPP &)' being compiled

It is expected that __Get_format_arg_storage_type_ etc. should  treat enum as an integer constant.

**Comment by CaseyCarter** [comment]
> It is expected that `_Get_format_arg_storage_type` etc. should treat enum as an integer constant.

I can't find any justification for this in the C++20 Standard. Notably, there's no specialization of `std::formatter` listed in [[format.formatter.spec]](http://eel.is/c++draft/format.formatter.spec) that knows how to format arbitrary enumeration types, and therefore no constructor of `basic_format_arg` ([[format.arg]](http://eel.is/c++draft/format.arg)) that would accept such a type.

Does {fmt} behave this way for enumerations? I can imagine WG21 removing such a behavior during standardization and requiring folks to explicitly specify how to format their enumeration types.

**Comment by miscco** [comment]
There is an example for formatter that takes an enumeration: https://eel.is/c++draft/format#formatter.spec-6

So I am quite sure that enumerations are actually not handled

**Comment by DmitryKo76** [comment]
That's just an example of a custom formatter. I cannot find any duscussion to deliberately omit enum values in [P0645R10](https://github.com/microsoft/STL/projects/5)  - I'd rather think enums were supposed to output as integers by default, as implemented by fmtlib. 

Unscoped enums are treated as integers by the _switch()_ statement and _printf_() /_wprintf_() functions (which <format> library is supposed to replace),  and they are almost exclusively used to define integer constants in C header fles; therefore an explicit cast to an integer would be unnecessarily verbose.  

If I neeeded to print a human-readable constant name instead of its numeric value, I'd use  _switch()_ with a temporary string rather than implement a custom formatter, due to internalization and localization issues. Type reflection similar to [_GetEnumNames_() in C#](https://docs.microsoft.com/en-us/dotnet/api/system.type.getenumnames) would be even better  though.

**Comment by CaseyCarter** [comment]
I can't find any mention of enumerations in any of the WG21 design discussion for P0645. @Vitaut, was it an oversight that `std::format` doesn't treat enumerations - even unscoped enumerations - as their underlying types, or an intentional design decision?

**Comment by vitaut** [comment]
P0645 focused on types where it doesn't make sense for users to override the default behavior. Enums are different so should be explored in a separate paper.

**Comment by barcharcraz** [comment]
This is by design, until reflection there isn't a good standard way to format enums.
