### ISSUE TITLE
<chrono>: Allow the parsing of year + day-of-the-year to a time_point using from_stream

### ISSUE THREAD

**Issue by amasciotta** [microsoft/STL#1938]
I'm not able to parse a string representing a date in the format `<year>.<day-of-the-year>.<hours>.<minutes>.<seconds>` using `std::from_stream` to a `std::chrono::time_point`. The following code fails for me on Visual Studio 2019 v16.10.

```
auto toTimePoint(const std::string& val)
{
    std::istringstream ss(val);
    std::chrono::system_clock::time_point tp;
    std::chrono::from_stream(ss, "%Y.%j.%H.%M.%S", tp)
    return tp;
}
```

Digging into the implementation, I've found that the code fails on [this line](https://github.com/microsoft/STL/blob/3cafa97eecdbfde41ea5c09126f877a7eb97f9e9/stl/inc/chrono#L4083) of the `chrono` header, because the `_Used` bit mask misses both the `_F_day` and `_F_month` flags: in this case this requirement should be fulfilled by the presence of the `_F_doy` flag, shouldn't it?

Also check this [question](https://stackoverflow.com/questions/67726168/how-to-parse-2021-147-17-33-45-using-howard-hinnants-date-library-or-the-equ?noredirect=1#comment119717978_67726168) on SO.

**Comment by TheSombreroKid** [comment]
The above fix fixes std::chrono::from_stream but std::chrono::parse is still broken - 
`    auto toTimePoint(const std::string& val)
    {
        std::chrono::system_clock::time_point tp = std::chrono::parse<std::string::value_type, std::string::traits_type, std::string::allocator_type, std::string>("%Y.%j.%H.%M.%S", val);
        return tp;
    }`

fails to deduce the fifth unnamed template argument, which i think is using sfinae to select the correct from_stream to use?
`
error C2672: 'std::chrono::parse': no matching overloaded function found
error C2783: 'auto std::chrono::parse(const std::basic_string<_Elem,_Traits,_Alloc> &,_Parsable &)': could not deduce template argument for '<unnamed-symbol>'
`

**Comment by cpplearner** [comment]
> 
> 
> The above fix fixes std::chrono::from_stream but std::chrono::parse is still broken -
> 
> ```
>     auto toTimePoint(const std::string& val)
>     {
>         std::chrono::system_clock::time_point tp = std::chrono::parse<std::string::value_type, std::string::traits_type, std::string::allocator_type, std::string>("%Y.%j.%H.%M.%S", val);
>         return tp;
>     }
> ```
> 
> fails to deduce the fifth unnamed template argument, which i think is using sfinae to select the correct from_stream to use?
> 
> ```
> error C2672: 'std::chrono::parse': no matching overloaded function found
> error C2783: 'auto std::chrono::parse(const std::basic_string<_Elem,_Traits,_Alloc> &,_Parsable &)': could not deduce template argument for '<unnamed-symbol>'
> ```

IIUC This is not the correct way to use `parse`. The intended usage is `std::istringstream(val) >> std::chrono::parse("%Y.%j.%H.%M.%S"s, tp)`
