### ISSUE TITLE
<format>: parameter name consistency: _First/_Last vs _Begin/_End

### ISSUE THREAD

**Issue by barcharcraz** [microsoft/STL#1947]
Format uses _Begin and _End as parameters sometimes and _First and _Last other times. It might be good to standardize on _First and _Last, as that's what we use elsewhere in the STL.

This goes for the names of parameters in the concepts in format as well.

**Comment by RhnSharma** [comment]
I would like to take this one.

**Comment by mghalayini** [comment]
I'm going to take a swing at this. Basically, all I have to do is change the `_Begin` and `_End` parameters to `_First` and `_Last` in the functions that use them, as well as change the bodies of those functions (changing every reference to `_Begin`/`_End` to `_First`/`_Last`). Is that all?

**Comment by StephanTLavavej** [comment]
That should be all! I quickly checked `<format>` and didn't find any occurrences of things like `_Begin1` that would need to be changed similarly.

Note that there are functions named plain `begin`/`end` and also `_Unchecked_begin`/`_Unchecked_end` - those should remain unchanged.
