### ISSUE TITLE
<format>: consider moving throws into a separate [[noreturn]] inline function

### ISSUE THREAD

**Issue by barcharcraz** [microsoft/STL#1948]
In other parts of the STL, like [`<optional>`](https://github.com/microsoft/STL/blob/a31bd6ed6b4f1c18045bc329b38c08845ec0fc3d/stl/inc/optional#L52-L54) we `_THROW` from a separate `[[noreturn]]`-marked inline function, to keep exception code out of the hot path. This may or may not be a good idea in `<format>`, we'll have to actually look at codegen and decide it it's worth it.

**Comment by AlexGuteniev** [comment]
> marked inline function

I do the same in critical production code, except that I also mark these functions as `__declspec(noinline)`, to make sure it is `jmp` out of critical function, not `jmp` around some code in critical function; this helps making hot functions smaller and inlining them.

**Comment by StephanTLavavej** [comment]
Fixed by #2674.
