### ISSUE TITLE
`<yvals.h>`: `_STL_VERIFY` emits long strings for function names, apparently unused

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#1956]
Noticed by @xiangfan-ms.

`_STL_VERIFY` expands to `_STL_REPORT_ERROR` which expands to `_CRT_SECURE_INVALID_PARAMETER`:

https://github.com/microsoft/STL/blob/aa5145c8bea8bfe268761253ecc40ae5ac581f51/stl/inc/yvals.h#L186-L194

https://github.com/microsoft/STL/blob/aa5145c8bea8bfe268761253ecc40ae5ac581f51/stl/inc/yvals.h#L167-L171

For `_DEBUG` mode, `C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\corecrt.h` defines:

```cpp
        #define _CRT_SECURE_INVALID_PARAMETER(expr) \
            ::_invalid_parameter(_CRT_WIDE(#expr), __FUNCTIONW__, __FILEW__, __LINE__, 0)
```

`__FUNCTIONW__` can be a very long string. Interestingly, it doesn't appear to be used by the assertion dialog:

```
---------------------------
Microsoft Visual C++ Runtime Library
---------------------------
Debug Assertion Failed!

Program: C:\Temp\meow.exe
File: C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.29.30129\include\array
Line: 171

Expression: cannot increment value-initialized array iterator

For information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts.

(Press Retry to debug the application)

---------------------------
Abort   Retry   Ignore   
---------------------------
```

I wonder whether we could change `_STL_REPORT_ERROR` to behave like `_CRT_SECURE_INVALID_PARAMETER` except passing an empty string for the function name; this might reduce the size of debug-mode binaries by a noticeable amount.

**Comment by fsb4000** [comment]
@StephanTLavavej related bug: https://developercommunity.visualstudio.com/t/Error-C1091-when-working-with-nested-std/1437715
`error C1091: compiler limit: string exceeds 65535 bytes in length` in Debug config, not in Release

marked as fixed, so probably in VS 2022 we will have string literal with more than 65535 bytes in length.
