### ISSUE TITLE
<ranges>: views::take and views::drop constrain the type of count to be integer-like

### ISSUE THREAD

**Issue by hewillk** [microsoft/STL#1957]
For the constraint of the second parameter of `take_view`, the standard only specifies in [[range.take#overview-2]](http://eel.is/c++draft/range.take#overview-2): "If `decltype((F))` does not model `convertible_to<D>`, `views​::​take(E, F)` is ill-formed.", it seems that the following case should be well-formed:

```
#include <ranges>

int x[] = {42, 42, 42};
auto r1 = x | std::views::take(std::integral_constant<int, 5>{});
auto r2 = x | std::views::drop(std::integral_constant<int, 5>{});
```
https://godbolt.org/z/M576MjWKv
Please correct me if I am missing something.

**Comment by miscco** [comment]
I believe the error is that we are currently constraining both range-adaptors with `_Integer_like`

I *think* it would be simple to drop `_Integer_like` and let the `requires convertible_to<_Ty&, range_difference_t<_Rng>>` handle any fallout.

The obvious fallout would be that it is possible to create stupid range adaptors, as the range adaptor itself has no connection to a range and therewith cannot check whether the range would take what we give it.

```cpp
auto meow = std::views::take(std::vector<bool>{true});
```

@CaseyCarter anything wrong with that?

**Comment by hewillk** [comment]
> The obvious fallout would be that it is possible to create stupid range adaptors, as the range adaptor itself has no connection to a range and therewith cannot check whether the range would take what we give it (https://godbolt.org/z/ne8Mj1nrq).
> 
> ```c++
> #include <ranges>
> 
> struct hiss{};
> 
> auto meow = std::views::take(hiss{});
> ```

The problem of stupid range adaptors also exists in other adaptors such as` views::filter` and `views::transform`. I don’t know if it is worth submitting an LWG for it.

**Comment by timsong-cpp** [comment]
> The problem of stupid range adaptors also exists in other adaptors such as` views::filter` and `views::transform`. I don’t know if it is worth submitting an LWG for it.

What do you expect LWG to do? Mandate some sort of check that argument is invocable with *something*? How is that even supposed to work?
