### ISSUE TITLE
<cassert><cstdlib>: An ABI-breaking version of UCRT might be needed

### ISSUE THREAD

**Issue by frederick-vs-ja** [microsoft/STL#196]
As `assert` and `aligned_alloc` are included in the C++ standard library, I think it's OK to reporting the issues here, though they're mainly about UCRT.
- MSVC's implementation of `assert` can't satisfy the requirement of C99/C++11 and later versions of standard, because its underlying function `_wassert` can't correctly handle the predefined variable `__func__`.
- `aligned_alloc` can't be implemented currently because of the existing implementation of `malloc`, `free`, etc.

It seems that these issues can't be fixed without ABI-breakage. Will there be a ABI-breaking version of UCRT fixing them?

**Comment by jonwil** [comment]
I am not 100% sure but I suspect the ABI stuff is why they created dlls like api-ms-win-crt-conio-l1-1-0.dll and others and that new dlls that bump up the numbers may be made in the future to handle ABI changes.

**Comment by StephanTLavavej** [comment]
Although the C++ Standard incorporates the C Standard Library by reference, this project (the STL) and the UCRT are physically separate, maintained by different developers, and shipped through different mechanisms. As https://github.com/microsoft/STL#reporting-issues explains:

> If it's a bug in the compiler, CRT, or IDE, please report it through Developer Community or Report A Problem.

Apologies for the inconvenience, but this will allow your request to be properly tracked.

(Bugs that are entirely within the wrapper headers `<cmeow>` can and should be reported here on GitHub.)
