### ISSUE TITLE
`<format>`: Can't call `format_to` in a `formatter` specialization

### ISSUE THREAD

**Issue by glebov-andrey** [microsoft/STL#1961]
When specializing `std::formatter` is can be useful to call `std::format_to(format_context.out(), ...)` to actually do the formatting.
In fact the Working Draft includes [an example that does just that](https://eel.is/c++draft/format#context-example-1).
But when attempting to do so I get the following error: `format(1816,15): error: no member named 'resize' in 'std::_Fmt_buffer<char>'`.

**Test case**
```c++
#include <format>

struct wrapper {
    int value;
};

template<typename CharT>
struct std::formatter<wrapper, CharT> {
    auto parse(auto &context) const {
        auto it = context.begin();
        if (it != context.end() && *it != CharT{'}'}) {
            throw format_error{"invalid format specification"};
        }
        return it;
    }

    auto format(const wrapper wrap, auto &context) const {
        return format_to(context.out(), "{}", wrap.value);
    }
};

auto main() -> int {
    std::format("{}", wrapper{123});
}
```

**The full error message from Clang (MSVC fails the in exact same way)**

```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037\include\format(1816,15): error: no member named 'resize' in 'std::_Fmt_buffer<char>'
        _Cont.resize(_Capacity);
        ~~~~~ ^
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037\include\format(1824,14): note: in instantiation of member function 'std::_Fmt_iterator_buffer<std::back_insert_iterator<std::_Fmt_buffer<char>>, char>::_Grow' requested here
    explicit _Fmt_iterator_buffer(back_insert_iterator<_Container> _Out, ptrdiff_t = 0)
             ^
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037\include\format(2897,43): note: in instantiation of member function 'std::_Fmt_iterator_buffer<std::back_insert_iterator<std::_Fmt_buffer<char>>, char>::_Fmt_iterator_buffer' requested here
    _Fmt_iterator_buffer<_OutputIt, char> _Buf(_STD move(_Out));
                                          ^
main.cpp(87,16): note: in instantiation of function template specialization 'std::format_to<std::back_insert_iterator<std::_Fmt_buffer<char>>, int>' requested here
        return format_to(context.out(), "{}", wrap.value);
               ^
main.cpp(92,10): note: in instantiation of function template specialization 'std::format<wrapper>' requested here
    std::format("{}", wrapper{123});
         ^
```

I'm pretty sure the problem is that the `_Fmt_iterator_buffer<back_insert_iterator<_Container>, ...>` specialization is not sufficiently constrained.
`_Fmt_iterator_buffer::_Grow` calls `_Cont::resize` here: https://github.com/microsoft/STL/blob/4c862ee11ce956556b810a813e77b0f8f97fb642/stl/inc/format#L1816-L1818
But the constraint on the specialization does not check for `resize` being available: https://github.com/microsoft/STL/blob/4c862ee11ce956556b810a813e77b0f8f97fb642/stl/inc/format#L1800-L1803

Considering that the specialization in question is meant to optimize for contiguous output buffers and `_Fmt_buffer` is contiguous, it would seem reasonable to add a `resize` member function to `_Fmt_buffer` (or maybe there should even be a separate specialization for `_Fmt_buffer`).

**Comment by sylveon** [comment]
Fixed by #1894

**Comment by SuperWig** [comment]
This was actually fixed in https://github.com/microsoft/STL/commit/02ae70ae52bc39f6c17ad939b5738164e2fe0561 which is going into 17.0 Preview 2 according to the changelog.

Might be a good idea to update the changelog to include this information?

**Comment by StephanTLavavej** [comment]
Fix verified and recorded in the Changelog - thanks everyone!

**Comment by The-MR777** [comment]
Will this FIX be released for **VS 2019** as well?

**Comment by StephanTLavavej** [comment]
@The-MR777 Yes, but this will be combined with many other `<format>` changes and backported in a single commit, after the Committee has stopped making changes and we've finished implementing them, as described in our GH-1814 plan. We don't have an official ETA for that yet, although we expect it should be early in calendar year 2022 (when C++20 is finished :joy_cat:).
