### ISSUE TITLE
`<thread>`: `jthread` should provide `native_handle()`

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#1963]
`jthread` defines `native_handle_type` but not a `native_handle()` member function:

https://github.com/microsoft/STL/blob/4c862ee11ce956556b810a813e77b0f8f97fb642/stl/inc/thread#L291-L377

While it's implementation-defined as to whether `native_handle()` is provided, we should do so - `jthread` wraps `thread` so we can just return its `native_handle()`.

Reported as DevCom-1389817 and Microsoft-internal VSO-1306513 / AB#1306513 .

**Comment by bhardwajs** [comment]
Do you already have a taker? If not, I can send a PR.

**Comment by StephanTLavavej** [comment]
No takers yet - go ahead! :smile_cat:
