### ISSUE TITLE
`<random>`: `generate_canonical()` could avoid calling `log2()` at runtime

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#1964]
Gautham Beeraka reported a performance issue in `generate_canonical()`, where it calls `log2()`:

https://github.com/microsoft/STL/blob/4c862ee11ce956556b810a813e77b0f8f97fb642/stl/inc/random#L248-L259

For engines like `mt19937` and `mt19937_64`, this is a really expensive way of computing `32.0` and `64.0`.

Solving this in a completely general manner might be somewhat difficult, but perhaps we could simply special-case the Standard engines that are known to have a power-of-2 range.

**Comment by pjessesco** [comment]
Hi, if I understand this issue correctly, is the suggested solution comparing `_Gen` with standard engines and specifing the denominator manually?

For example,

    if(_Gen == mt19937) 
        denominator = 32
    else if(_Gen == other pre-defined engines)
        denominator = something
	....
    else
        denominator = _STD log2(_Rx)
