### ISSUE TITLE
P1328R1 `constexpr` `type_info::operator==()`

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#1972]
[P1328R1](https://wg21.link/P1328R1) `constexpr` `type_info::operator==()`

Feature-test macro:
```cpp
#define __cpp_lib_constexpr_typeinfo 202106L
```

**Comment by cpplearner** [comment]
`type_info` is defined in `<vcruntime_typeinfo.h>`, which is not part of this repo.

**Comment by StephanTLavavej** [comment]
Not yet, but it will be soon! :smile_cat:

We've gotten the necessary blessings to open-source vcruntime/vcstartup, now we just need to update the file banners, move stuff around, add them to the new CMake build system, etc. This is not yet concretely scheduled but should start in a month, hopefully.

**Comment by SuperWig** [comment]
> but should start in a month, hopefully.

Meteor strikes withstanding?

**Comment by miscco** [comment]
> > but should start in a month, hopefully.
> 
> Meteor strikes withstanding?

He said "a month". which one in which year remains undetermined

**Comment by StephanTLavavej** [comment]
Merged MSVC-PR-392482 for 17.3 Preview 1.

**Comment by jonwil** [comment]
Is the vcruntime open source delay because of the previously mentioned performance stuff? (i.e. the lack of a way to make sure 3rd party submissions aren't hurting perf)

**Comment by CaseyCarter** [comment]
> Is the vcruntime open source delay because of the previously mentioned performance stuff? (i.e. the lack of a way to make sure 3rd party submissions aren't hurting perf)

Yes, that is the case. Until we have some kind of benchmarking in place to defend against critical perf regression, we're not comfortable open-sourcing VCRuntime. (Despite that the vast majority of VCRuntime changes that come from the STL don't touch perf-critical code.)

**Comment by jonwil** [comment]
Obvious question is why it can't be opened up but (as with patches that break ABI) patches to perf critical code not accepted for merge until the infrastructure is in place to detect regressions.

**Comment by CaseyCarter** [comment]
> Obvious question is why it can't be opened up but (as with patches that break ABI) patches to perf critical code not accepted for merge until the infrastructure is in place to detect regressions.

That's a good question which I wasn't motivated enough to get an answer to. @MahmoudGSaleh and @mnatsuhara were involved more directly in the cross-team opensourcing discussions, maybe Mahmoud could comment?

**Comment by StephanTLavavej** [comment]
17.3 Preview 1 didn't contain an MSVC toolset update (due to factors outside of our control) - we are actually waiting for 17.3 Preview 2 here.
