### ISSUE TITLE
P2216R3 `std::format` Improvements

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#1981]
[P2216R3](https://wg21.link/P2216R3) `std::format` Improvements

Feature-test macro:
`#define __cpp_lib_format INCREASED_VALUE_TO_BE_DETERMINED`

At the June 2021 virtual plenary meeting, this was accepted as a defect report for C++20, which means that this paper applies retroactively to the C++20 Standard.

**Comment by fsb4000** [comment]
I saw @miscco wrote about marking as `blocked` https://github.com/microsoft/STL/issues/1447
I think we should also mark as `blocked` this issue because: https://github.com/microsoft/STL/pull/1882
