### ISSUE TITLE
P2281R1 Clarifying Range Adaptor Objects

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#1983]
[P2281R1](https://wg21.link/P2281R1) Clarifying Range Adaptor Objects

No feature-test macro is mentioned.

At the June 2021 virtual plenary meeting, this was accepted as a defect report for C++20, which means that this paper applies retroactively to the C++20 Standard.

**Comment by frederick-vs-ja** [comment]
Is this already implemented (via the report in [LWG-3509](https://cplusplus.github.io/LWG/issue3509))?

**Comment by CaseyCarter** [comment]
There's nothing to implement here; this proposal simply clarifies the requirements of the existing implementations and codifies them in the Standard. I'm calling this complete.

**Comment by CaseyCarter** [comment]
I'm mistaken, I wasn't looking closely enough. Our range adaptor closure objects for `split_view` (and soon `lazy_split_view`) capture the pattern argument like a `viewable_range` via `views:all`, whereas P2281 says we should capture by copy. This will need another small followup in or after merging #2042.
