### ISSUE TITLE
P2328R1 `join_view` Should Join All Views Of Ranges

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#1985]
[P2328R1](https://wg21.link/P2328R1) `join_view` Should Join All Views Of Ranges

No feature-test macro is mentioned.

At the June 2021 virtual plenary meeting, this was accepted as a defect report for C++20, which means that this paper applies retroactively to the C++20 Standard.

**Comment by CaseyCarter** [comment]
This effectively depends on #1984.

**Comment by CaseyCarter** [comment]
When implementing this, consider using the non-propagating cache for `split_view::_Current` which #2012 puts in a `_Defaultabox`.
