### ISSUE TITLE
P2367R0 Remove Misuses Of List-Initialization From Clause 24 Ranges

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#1986]
[P2367R0](https://wg21.link/P2367R0) Remove Misuses Of List-Initialization From Clause 24 Ranges

No feature-test macro is mentioned.

At the June 2021 virtual plenary meeting, this was accepted as a defect report for C++20, which means that this paper applies retroactively to the C++20 Standard.

**Comment by CaseyCarter** [comment]
While I believe the changes to be largely orthogonal, I think this is likely to have merge conflicts with #1984 since that change touches so much (moreso in test code than product code). I think we should wait for #1984 to land before implementing this.
