### ISSUE TITLE
P2186R2 Removing Garbage Collection Support

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#1988]
[P2186R2](https://wg21.link/P2186R2) Removing Garbage Collection Support

There's no feature-test macro as this is a removal.

(This was a Core motion, but it primarily has Library impact.)

**Comment by jovibor** [comment]
Damn... we're back again to manual memory management in C++.

**Comment by AdamBucior** [comment]
Should we remove it unconditionally? I'm sure no one would even notice. (By no one I mean literally zero people)

**Comment by CaseyCarter** [comment]
I also find it incredibly unlikely that anyone but test suites would notice, but I'd prefer that we keep these stub functions around in earlier language modes.

**Comment by StephanTLavavej** [comment]
I'd also prefer for the removal to be conditional on C++23 with the usual escape hatch system - I totally agree that no actual users will notice, but this may make things simpler for various compiler/library test suites (the compiler has some third-party conformance tests that may be looking for this no-op machinery).
