### ISSUE TITLE
STL: Avoid TODO in comments

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#200]
MSVC's IDE has a Task List that displays TODO comments, even in system headers. We're almost perfect at avoiding interfering with this, as we use TRANSITION comments for temporary things (usually compiler bug workarounds). However, we've accumulated three TODO comments:

https://github.com/microsoft/STL/blob/1e4f423120b1b3de409655bdbcc0492121940afb/stl/inc/compare#L12

https://github.com/microsoft/STL/blob/1e4f423120b1b3de409655bdbcc0492121940afb/stl/inc/xcharconv_ryu.h#L1117

https://github.com/microsoft/STL/blob/1e4f423120b1b3de409655bdbcc0492121940afb/stl/inc/xcharconv_ryu.h#L1799

**Comment by jpjjulie** [comment]
Hi,
Can I please work on this? Just for clarification, I should be removing the entire TODO comments above right?

**Comment by StephanTLavavej** [comment]
Sure, thank you! We actually want to keep the comments, but change TODO to TRANSITION. That will make the IDE not display them, and will make them show up on our usual searches for TRANSITION.

**Comment by jpjjulie** [comment]
Okay! Thanks for the clarification.
