### ISSUE TITLE
`tests.py` should map `/std:c++latest` to `'c++2b'`

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#2001]
`tests.py` maps compiler options to "features", used by the libcxx test suite:

https://github.com/microsoft/STL/blob/4c862ee11ce956556b810a813e77b0f8f97fb642/tests/utils/stl/test/tests.py#L234-L241

The toolset update #1953 is mapping `/std:c++20` to `'c++2a'`. However, it's still mapping `/std:c++latest` to `'c++2a'`. This prevents libcxx's C++23 tests from running.

For example, #1950 is implementing `is_scoped_enum`, but attempting to unskip its test
https://github.com/microsoft/STL/blob/4c862ee11ce956556b810a813e77b0f8f97fb642/tests/libcxx/skipped_tests.txt#L278-L279
leads to it being detected as unsupported. (The test marks itself as unsupported in C++03 through C++2a inclusive, meaning it expects C++2b.)

As I recall, I initially attempted to map `/std:c++latest` to `'c++2b'` in toolset update #1953, but encountered a couple of libcxx tests that weren't expecting this. This might be resolved if we update to libcxx's latest commit.

**Comment by SuperWig** [comment]
> This might be resolved if we update to libcxx's latest commit.

I can confirm that works. I updated the commit and got

> Unexpectedly Passed Tests (2):
  libc++ :: std/utilities/meta/meta.unary/meta.unary.prop/is_scoped_enum.pass.cpp:0
  libc++ :: std/utilities/meta/meta.unary/meta.unary.prop/is_scoped_enum.pass.cpp:1
