### ISSUE TITLE
<regex>: utf8 type match are not supported

### ISSUE THREAD

**Issue by GC-Toph** [microsoft/STL#2022]
**Describe the bug**
initialize a regex object with string R"(\u1234)" is not valid
core code: std::regex pa(R"(\u1234)");
regex parser will throw an error

**Command-line test case**
```
C:\Temp>type repro.cpp
#include <iostream>
#include <regex>

int main()
{
    std::regex pa(R"(\u1234)");
    std::cout << "test failure\n";
}
 
Windows SDK 10.0(latest)
default compile configurations

**Expected behavior**
The program exits normally as I tried with compiler g++

**STL version**

* Option 1: Visual Studio version
  * Displayed in Help > About Microsoft Visual Studio
    Microsoft Visual Studio Community 2019
    Version 16.10.2
**Additional context**
nothing

**Comment by StephanTLavavej** [comment]
Ideas for investigation (I haven't tried these yet):
* What bytes does the narrow string literal contain?
* What happens if you compile with [`/utf-8`](https://docs.microsoft.com/en-us/cpp/build/reference/utf-8-set-source-and-executable-character-sets-to-utf-8?view=msvc-160)?

**Comment by GC-Toph** [comment]
> Ideas for investigation (I haven't tried these yet):
> 
> * What bytes does the narrow string literal contain?
> * What happens if you compile with [`/utf-8`](https://docs.microsoft.com/en-us/cpp/build/reference/utf-8-set-source-and-executable-character-sets-to-utf-8?view=msvc-160)?

1.Any bytes will occur such a problem, in fact, this problem occurs when the regex object initializes
2.Nothing new will happen when i tried to compile with /utf-8

**Comment by MattStephanson** [comment]
[re.grammer/12](http://eel.is/c++draft/re#grammar-12):
If the _CV_ of a _UnicodeEscapeSequence_ is greater than the largest value that can be held in an object of type `charT` the translator shall throw an exception object of type `regex_­error`.

Instead of using an ECMAScript Unicode escape sequence, however, you could use a universal character name `"\u1234"`. As @StephanTLavavej mentioned, you'd have to compile with `/utf-8` also.

**Comment by GC-Toph** [comment]
> [[re.grammer]/12](http://eel.is/c++draft/re#grammar-12):
> If the _CV_ of a _UnicodeEscapeSequence_ is greater than the largest value that can be held in an object of type `charT` the translator shall throw an exception object of type `regex_­error`.
> 
> Instead of using an ECMAScript Unicode escape sequence, however, you could use a universal character name `"\u1234"`. As @StephanTLavavej mentioned, you'd have to compile with `/utf-8` also.

Thanks your advice, but how can i use a universal character name "\u1234" in regex, i am still puzzled so can you show me some code examples?

**Comment by fsb4000** [comment]
```
#include <iostream>
#include <regex>

int main()
{
  std::regex pa("(\u1234)");
  std::string s = "text have \u1234 character";
  if (std::regex_search(s, pa)) {
    std::cout << "Found\n";
  }
  else {
    std::cout << "Not Found\n";
  }
}
```
it prints "Found"...

**Comment by StephanTLavavej** [comment]
Thanks @MattStephanson and @fsb4000 - I agree that `<regex>` is working correctly here and throwing a `regex_error` for the original code as specified by the Standard.

@GC-Toph To clarify, the (subtle!) difference between your code and the alternate approach that @MattStephanson and @fsb4000 are suggesting, is that your code used a raw string literal for `R"(\u1234)"`, which passes a backslash, a lowercase u, and the digits 1234 to `regex`, which interprets it as a UnicodeEscapeSequence (according to the modified ECMAScript grammar). Their suggested alternative is to use `"(\u1234)"` which is **not** a raw string literal - here, the backslash-escape is parsed by the C++ compiler, so the resulting narrow string directly contains an encoding of this character.
