### ISSUE TITLE
`<format>`: Can we avoid including `<array>`?

### ISSUE THREAD

**Issue by jovibor** [microsoft/STL#2027]
I don't know your general conventions about using `<array>` internally in the STL, but in the `<format>` it's used only in four places and seems can easily be replaced by raw arrays. So, is it really worth to keep that additional header here?

Generally it's a good idea to keep as little dependencies as possible, especially for something as widespread  as text formatting.

**Comment by StephanTLavavej** [comment]
I agree that the compiler throughput benefit likely outweighs the convenience of using `array` internally.
