### ISSUE TITLE
<xstring> : The behavior of stream.widen(0) is not consistent.

### ISSUE THREAD

**Issue by Kami-chanw** [microsoft/STL#2028]
In the `_Insert_string`, which is invoked in operator<<, `_Ostr.width(0)` will be called after inserting a string in stream correctly:
```
if (!_Ok) {
        _State |= _Ostr_t::badbit;
    } else { // state okay, insert characters
        _TRY_IO_BEGIN
        //some code
        _Ostr.width(0);
        _CATCH_IO_(_Ostr_t, _Ostr)
    } 
```
But in the `operator>>`,  `_Istr.width(0)` always will be called no matter whether characters can be extracted:
```
if (_Ok) { // state okay, extract characters
        const _Ctype& _Ctype_fac = _STD use_facet<_Ctype>(_Istr.getloc());
        _Str.erase();

        _TRY_IO_BEGIN
        //some code
        _CATCH_IO_(_Myis, _Istr)
    }

    _Istr.width(0);
```
It seems that the behavior of them is not consistent. I wonder if there is relevant regular in standard

**Comment by StephanTLavavej** [comment]
This behavior appears to match the Standardese (although I'm not an iostreams expert).

For `operator<<`, WG21-N4892 21.4.6 [string.view.io]/1 says:

> *Effects:* Behaves as a formatted output function (29.7.5.3.1) of `os`. Forms a character sequence `seq`, initially consisting of the elements defined by the range `[str.begin(), str.end())`. Determines padding for `seq` as described in 29.7.5.3.1. Then inserts `seq` as if by calling `os.rdbuf()->sputn(seq, n)`, where `n` is the larger of `os.width()` and `str.size()`; then calls `os.width(0)`.

If inserting `seq` fails, this doesn't say that `os.width(0)` should be called. Nothing in the "formatted output function" wording says that either (it says "If the generation fails, then the formatted output function does `setstate(ios_base::failbit)`, which can throw an exception." etc.).

For `operator>>`, 21.3.4.4 [string.io]/2-3 says:

> After the last character (if any) is extracted, `is.width(0)` is called and the `sentry` object is destroyed.
> If the function extracts no characters, it calls `is.setstate(ios_base::failbit)`, which may throw `ios_base::failure` (29.5.5.4).

I believe this clearly requires the implementation's unconditional `_Istr.width(0);` call.

Hope this helps - thanks for bringing this up!
