### ISSUE TITLE
`<vector>`: Annotate `vector` for use with ASan

### ISSUE THREAD

**Issue by cbezault** [microsoft/STL#2030]
ASan can be taught to understand the concept of an access to a contiguous container that is in a valid region of memory but not in a valid region of the container.

e.g.
```
std::vector<int> v;
v.push_back(1);
v.pop_back();
*v.data() = 1;
```

would not result in an ASan exception as things stand. However, we can add annotations to the ASan shadow memory using ` __sanitizer_annotate_contiguous_container` which will allow ASan to detect the invalid access.

**Comment by AlexGuteniev** [comment]
+ `<string>` ?

**Comment by StephanTLavavej** [comment]
Linking https://github.com/microsoft/STL/pull/2071#issuecomment-888460301 here for the record - `<string>` changes are indeed planned.
