### ISSUE TITLE
`<type_traits>`: `std::byte` is not `_Is_trivially_swappable`

### ISSUE THREAD

**Issue by fsb4000** [microsoft/STL#2039]
**Describe the bug**
`std::byte` is not `_Is_trivially_swappable`, so code generation is worse than for `unsigned char`

This problem is best seen at godbolt: https://godbolt.org/z/qxP8fYd3v

**Expected behavior**
`std::byte` should have same speed as `unsigned char`

**STL version**
    ```
    Microsoft Visual Studio Community 2022 Preview 1.1
    Version 17.0.0
    ```

**Additional context**
 DevCom-1467265 and Microsoft-internal VSO-1352013 / AB#1352013

**Comment by fsb4000** [comment]
Can we do:
```cpp
template<>
_INLINE_VAR constexpr bool _Is_trivially_swappable_v<std::byte> = true;
```
?

And will this affect the ABI?

**Comment by AdamBucior** [comment]
Interesting, nothing that's in `std` namespace can be trivially swappable: https://godbolt.org/z/vTYYejKqY. Presumably because ADL chooses `std::swap`.

**Comment by frederick-vs-ja** [comment]
Perhaps we should reuse the mechanism for `std::ranges::swap` to get rid of the primary `std::swap` overload.
By the way, IMO the related header is `<type_traits>`, in which `_Is_trivially_swappable` is problematically defined.

**Comment by CaseyCarter** [comment]
> Can we do:
> 
> ```c++
> template<>
> _INLINE_VAR constexpr bool _Is_trivially_swappable_v<std::byte> = true;
> ```
> 
> ?
> And will this affect the ABI?

This seems perfectly cromulent. Note that (1) `std::byte` doesn't need to be qualified in namespace `std`, and (2) `byte` is only available in `_HAS_CXX17` or later modes where we can say `inline` instead of `_INLINE_VAR`. ABI isn't a problem: linking new and old TUs together may pick the old/slow version but the resulting program will be correct in any case.

**Comment by fsb4000** [comment]
Cool. I will add a PR. Thank you @CaseyCarter
