### ISSUE TITLE
<iterator>: The issue of std::common_iterator::iterator_­category

### ISSUE THREAD

**Issue by hewillk** [microsoft/STL#2067]
The standard explains the definition of `iterator_category` of `common_iterator` in [[iterators.common#common.iter.types-1.2]](http://eel.is/c++draft/iterators.common#common.iter.types-1.2): "`iterator_­category` denotes `forward_­iterator_­tag` if the _qualified-id_ `iterator_­traits<I>​::​iterator_­category` is valid and denotes a type that models `derived_­from<forward_­iterator_­tag>`; otherwise it denotes `input_­iterator_­tag`."
However, the MSVC's implementation is as follows:
https://github.com/microsoft/STL/blob/bd7adb4a932725f60ba096580c415616486ab64c/stl/inc/iterator#L1034-L1035

This does not check the validity of `iterator_traits<I>​::​iterator_category`.

**Comment by cpplearner** [comment]
IIUC this will be fixed by #2059

**Comment by hewillk** [comment]
> IIUC this will be fixed by #2059

Thank you for pointing it out for me. I just found out that CaseyCarter has [already implemented](https://github.com/microsoft/STL/pull/2059/commits/f7e1671964592dc0514ecdb0a6cfc4bed274a46d) it.
