### ISSUE TITLE
STL: Finish marking virtual functions as override

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#207]
We've marked most `virtual` functions as `override` when possible. We should do a final pass to find any that were missed.

Our non-Standard `_Doraise()` was one example, fixed by #302. I am unsure if there are any remaining examples.

**Comment by jpjjulie** [comment]
Hi,
Can I contribute to this project by changing _Doraise() into an override function?

**Comment by StephanTLavavej** [comment]
Sure! If you have time to check every `virtual` function not already marked `override` and figure out whether it’s a base declaration or is missing `override`, that would be awesome and we can resolve this bug. If you just want to mark `_Doraise`, that would be a strict improvement that we could merge, and we’d keep this issue open for further investigation.

Currently, we use both the `virtual` and `override` keywords on overriders. I suppose changing our style to say `override` only would make searching for `virtual` easier, but that should be a separate issue and I’d want to see what @BillyONeal, @CaseyCarter, and @barcharcraz think.

**Comment by jpjjulie** [comment]
Sure! I'll figure out. Thanks.
