### ISSUE TITLE
<type_traits>: declval<T>() does not reject use in an evaluated context

### ISSUE THREAD

**Issue by AlexGuteniev** [microsoft/STL#2087]
**Describe the bug**
`std::declval<T>()` does not reject use in an evaluated context

**Command-line test case**
```
D:\Temp>type test.cpp
#include <type_traits>

template<class T>
auto type() { return std::declval<T>(); }

using T = decltype(type<int>());

int main()
{
}


D:\Temp>cl test.cpp
Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30132 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

test.cpp
Microsoft (R) Incremental Linker Version 14.29.30132.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:test.exe
test.obj
```

**Expected behavior**
Don't compile, as gcc: https://godbolt.org/z/xenzr79q4

**STL version**
Microsoft Visual Studio Professional 2019 Preview
Version 16.11.0 Preview 3.0

**Additional context**
This SO question https://stackoverflow.com/q/68590453/2945027

**Comment by StephanTLavavej** [comment]
Surprising, but I agree that this is a bug and that we need to add enforcement here.

**Comment by StephanTLavavej** [comment]
This should be a (nearly) one-line fix. We'll need to add a function body to `declval` (which is currently declared-but-not-defined):

https://github.com/microsoft/STL/blob/cc515bbb42dbbfba184527ad2e7c093a78c10442/stl/inc/type_traits#L147-L148

This will need to `static_assert`, with `_Always_false<_Ty>` (to delay emitting the compiler error until the function body is actually instantiated; compare other uses of `_Always_false` in the codebase), and the `static_assert` message should say `"Calling declval is ill-formed, see N4892 [declval]/2."`
