### ISSUE TITLE
`<yvals_core.h>`: Update `_MSVC_STL_VERSION` and `_MSVC_STL_UPDATE`

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#2090]
Explanation on our wiki: [Macro `_MSVC_STL_UPDATE`](https://github.com/microsoft/STL/wiki/Macro-_MSVC_STL_UPDATE)

Code:
https://github.com/microsoft/STL/blob/6a53cf2b809cbd3c10d5f35226e996ad5486ac06/stl/inc/yvals_core.h#L561-L562

:star: Special for this month only! :star: In addition to the monthly increase of `_MSVC_STL_UPDATE`, we **also** need to increase `_MSVC_STL_VERSION` to `143` for VS 2022's release.

Previous issue: #2034

This issue is intended for a new contributor (especially one new to GitHub) to get started with the simplest possible change.

Please feel free to submit a pull request if there isn't one already linked here - no need to ask for permission! :smile_cat:

You can (and should) link your pull request to this issue using [GitHub's close/fix/resolve syntax](https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

**Comment by joseherrera7** [comment]
I can help with this task
