### ISSUE TITLE
Isn't _mm256_zeroupper needed after __m256i version of STL algorithms?

### ISSUE THREAD

**Issue by AlexGuteniev** [microsoft/STL#2105]
One of occurrences:
https://github.com/microsoft/STL/blob/bfa2cb2a6dc168653a2752cb91521e8d0b4a4e69/stl/src/vector_algorithms.cpp#L59-L70

From Agner Fog's "Optimizing software in C++":

> 
> There is a problem when mixing code compiled with and without AVX support on some Intel
> processors. There is a performance penalty when going from AVX code to non-AVX code
> because of a change in the YMM register state. This penalty should be avoided by calling
> the intrinsic function _mm256_zeroupper() before any transition from AVX code to nonAVX code. This can be necessary in the following cases:
> • If part of a program is compiled with AVX support and another part of the program is
> compiled without AVX support then call _mm256_zeroupper() before leaving the
> AVX part.
> 
> • If a function is compiled in multiple versions with and without AVX using CPU
> dispatching then call _mm256_zeroupper() before leaving the AVX part.
> 
> • If a piece of code compiled with AVX support calls a function in a library other than
> the library that comes with the compiler, and the library has no AVX support, then
> call _mm256_zeroupper() before calling the library function

**Comment by StephanTLavavej** [comment]
Sounds like a real issue. I wonder what "some Intel processors" are - is this restricted to something like Sandy Bridge and Ivy Bridge (2011/2012), or are more recent processors affected? If the affected set of processors is sufficiently ancient, perhaps there's nothing to do here.

**Comment by BillyONeal** [comment]
This perf hazard exists at least as recently as Ice Lake (Sunny Cove cores). See around figure 15-1 in the Optimization Manual https://software.intel.com/content/dam/develop/external/us/en/documents-tps/64-ia-32-architectures-optimization-manual.pdf

When I added this stuff, if I recall correctly, the compiler inserted zeroing to avoid these perf hazards for us (one of the benefits of using intrinsics instead of inline assembly). Please double check that the compiler actually emits code that has one of the harmful transitions.

**Comment by BillyONeal** [comment]
I observe the compiler doing the correct zeroing:

![795D6B33-14C0-4D21-9EAE-A5D74AB42DC5](https://user-images.githubusercontent.com/1544943/128977746-513164d6-b0f8-4df5-8244-932dfd5d86c0.jpeg)

**Comment by AlexGuteniev** [comment]
I confirm I don't see any harmful transitions in assembly. 
I wasn't aware that compilers inserts `vzeroupper` for intrinsics, not only for auto-vectorizing.

**Comment by AlexGuteniev** [comment]
Related: recently I've learned that:
 * There is `/d2vezroupper` /  `/d2vezroupper-`  option to enable/disable automatic `vzeroupper`
 * By default `veroupper` is generated, but with `/favor:AMD64` it is not, but can be enabled with `/d2vezroupper`
