### ISSUE TITLE
Support `char8_t` in C++17 mode

### ISSUE THREAD

**Issue by MahmoudGSaleh** [microsoft/STL#2106]
The STL currently understands and handles `char8_t` in C++17 and lower language modes when compiling with `/Zc:char8_t`.
To complete the support for [p0482r6 - char8_t: A type for UTF-8 characters and strings)](https://wg21.link/p0482r6), the following is still needed:
* Add test coverage for P0482 under `/std:c++17 /Zc:char8_t`
* Support `u8string` and `u8string_view` when `__cpp_char8_t` is defined (not only in C++20 mode)
* Determine which (if any) of the changes from WG21-P1423 we should down-port as well.

Related to DevCom-1030065.

**Comment by StephanTLavavej** [comment]
We plan to work on this after completing the C++20 Defect Reports.

**Comment by ingo-loehken** [comment]
I'd just like to ask if your plans to bring in something like `/Zc:lib_char8_t` as feature toggle compiler vendor supported equivalent to hacking `/D__cpp_lib_char8_t`  into `/std:c++17` Standard Compiler Options is in schedule after [C++ 20 DRs](https://devblogs.microsoft.com/cppblog/msvcs-stl-completes-stdc20/) have been finished ?

If so, do you plan to target vs2022 and backport to vs2019 ?

Another question off-topic: I did not find any proposals for `std::u8stringstream` or similar in the C++ Standard. This hinders Interoperability and with `char8_t` and signedness of `char` in common differs. Are there any plans from Microsoft STL Team to fill that gap ?

**Comment by fsb4000** [comment]
@ingo-loehken `u8string`, `u8string_view` and `std::filesystem` additions are available with `/Zc:char8_t`
I don't know if it will be backported to vs2019.
About `std::u8stringstream`, as far as I know there is no such proposal from Microsoft employees and they usually implement what C++ standard says. 
https://github.com/microsoft/STL#non-goals
