### ISSUE TITLE
<fstream>: Performance issue when reading a binary file using std::basic_ifstream<unsigned char>

### ISSUE THREAD

**Issue by jamesmagnus** [microsoft/STL#2109]
**Describe the bug**
Performance issue.
When reading a **binary** file using unsigned data type (ie `std::basic_ifstream<unsigned char>`) is order of magnitude slower than reading it using signed data type (ie `std::basic_ifstream<char>`).
It seems you are doing character by character locale conversion, altough the file is open as binary and not text.

**Command-line test case**
```
Z:\beaus\Desktop\MSVC>type Source.cpp
#include <vector>
#include <iostream>
#include <fstream>
#include <chrono>
#include <filesystem>

int main()
{
        const std::filesystem::path filePath{ "test.data" }; // 128 MB binary file
        const size_t fileSize{ std::filesystem::file_size(filePath) };

        // Read the whole file using char data type
        {
                // Open file in binary mode
                std::basic_ifstream<char> fileStream{ filePath, std::fstream::binary };
                std::vector<char> data;
                data.resize(fileSize);

                const auto start{ std::chrono::system_clock::now() };
                fileStream.read(data.data(), fileSize);
                const auto end{ std::chrono::system_clock::now() };

                std::cout << "Duration read signed: " << std::chrono::duration_cast<std::chrono::milliseconds>(end - start).count() << " ms" << std::endl;
        }

        // Read the whole file using unsigned char data type
        {
                // Open file in binary mode
                std::basic_ifstream<unsigned char> fileStream{ filePath, std::fstream::binary };
                std::vector<unsigned char> data;
                data.resize(fileSize);

                const auto start{ std::chrono::system_clock::now() };
                fileStream.read(data.data(), fileSize);
                const auto end{ std::chrono::system_clock::now() };

                std::cout << "Duration read unsigned: " << std::chrono::duration_cast<std::chrono::milliseconds>(end - start).count() << " ms" << std::endl;
        }

        return 0;
}
Z:\beaus\Desktop\MSVC>cl /EHsc /W4 /WX /std:c++17 .\Source.cpp
Compilateur d'optimisation Microsoft (R) C/C++ version 19.29.30040 pour x64
Copyright (C) Microsoft Corporation. Tous droits réservés.

Source.cpp
Microsoft (R) Incremental Linker Version 14.29.30040.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:Source.exe
Source.obj

Z:\beaus\Desktop\MSVC>Source.exe
Duration read signed: 79 ms
Duration read unsigned: 12838 ms
```

**Expected behavior**
Read a **binary** file using `char` or `unsigned char` should take the same time. (no character conversion for binary data)

**STL version**
* Option 1: Visual Studio version
  * Displayed in Help > About Microsoft Visual Studio
    ```
    Microsoft Visual Studio Community 2019
    Version 16.10.4
    ```

**Additional context**
Use a randomly generated `test.data` binary file to reproduce the issue with my code. Mine is 128MB.

**Comment by fsb4000** [comment]
Duplicate: https://github.com/microsoft/STL/issues/817

use `.rdbuf()->pubsetbuf()`

**Comment by fsb4000** [comment]
```
#include <vector>
#include <iostream>
#include <fstream>
#include <chrono>
#include <filesystem>

int main()
{
        const std::filesystem::path filePath{ "test.data" }; // 128 MB binary file
        const size_t fileSize{ std::filesystem::file_size(filePath) };

        // Read the whole file using char data type
        {
                // Open file in binary mode
                std::basic_ifstream<char> fileStream{ filePath, std::fstream::binary };
                std::vector<char> data;
                data.resize(fileSize);

                const auto start{ std::chrono::system_clock::now() };
                fileStream.read(data.data(), fileSize);
                const auto end{ std::chrono::system_clock::now() };

                std::cout << "Duration read signed: " << std::chrono::duration_cast<std::chrono::milliseconds>(end - start).count() << " ms" << std::endl;
        }

        // Read the whole file using unsigned char data type
        {
                // Open file in binary mode
                std::basic_ifstream<unsigned char> fileStream{ filePath, std::fstream::binary };
                std::vector<unsigned char> data;
                data.resize(fileSize);

                const auto start{ std::chrono::system_clock::now() };
                fileStream.read(data.data(), fileSize);
                const auto end{ std::chrono::system_clock::now() };

                std::cout << "Duration read unsigned: " << std::chrono::duration_cast<std::chrono::milliseconds>(end - start).count() << " ms" << std::endl;
        }

        // Read the whole file using unsigned char data type
        {
                // Open file in binary mode
                std::basic_ifstream<unsigned char> fileStream{ filePath, std::fstream::binary };
                unsigned char buf[1024*10 + 1];
                fileStream.rdbuf()->pubsetbuf(buf, sizeof buf);
                std::vector<unsigned char> data;
                data.resize(fileSize);

                const auto start{ std::chrono::system_clock::now() };
                fileStream.read(data.data(), fileSize);
                const auto end{ std::chrono::system_clock::now() };

                std::cout << "Duration read unsigned with buffering: " << std::chrono::duration_cast<std::chrono::milliseconds>(end - start).count() << " ms" << std::endl;
        }

        return 0;
}
```
```
Duration read signed: 135 ms
Duration read unsigned: 7279 ms
Duration read unsigned with buffering: 92 ms
```
![изображение](https://user-images.githubusercontent.com/4289847/128869503-c0305d00-2766-4095-9bd5-87d09e8efa07.png)
![изображение](https://user-images.githubusercontent.com/4289847/128869575-5edccf84-2256-41fd-ad78-d9812ddbad3c.png)

**Comment by jamesmagnus** [comment]
Mmmh Ok I see. But why there is no internal buffer for all 1 byte data types ?

**Comment by fsb4000** [comment]
@jamesmagnus As far as I understand we don't use buffering for `cout`/`cin` and `ofstream`/`ifstream`.
So `pubsetbuf` with user provided buffer will be the fastest method.
But we use some optimization for `char` only because `codecvt` will be always `noconv`:
https://github.com/microsoft/STL/blob/bfa2cb2a6dc168653a2752cb91521e8d0b4a4e69/stl/inc/xlocale#L717-L720
https://github.com/microsoft/STL/blob/280347a4309eaaf5f1bba3b1ad98a27687b9d9c3/stl/inc/fstream#L609-L636
https://github.com/microsoft/STL/blob/280347a4309eaaf5f1bba3b1ad98a27687b9d9c3/stl/inc/fstream#L561-L607
If @StephanTLavavej  has time, he can answer in a more detailed way...

**Comment by fsb4000** [comment]
By the way LLVM libc++ do buffering in the basic_filebuf constructor: https://github.com/llvm/llvm-project/blob/main/libcxx/include/fstream#L314

Maybe we could do similar...

**Comment by AdamBucior** [comment]
Couldn't we make `codecvt::do_always_noconv` return `true` when `_Byte` and `_Elem` are same size integral types (the same criteria `copy` uses to decide whether to use `memmove`)? It seems that `do_in` and `do_out` just `static_cast` everything so no real conversion happens in that case.

**Comment by fsb4000** [comment]
Probably, I offered return `true` for `codecvt<unsigned char, char>::do_always_noconv` , `codecvt<char8_t, char>::do_always_noconv` and `codecvt<std::byte, char>::do_always_noconv`  but your idea is just better because more general.

**Comment by StephanTLavavej** [comment]
@CaseyCarter notes that `basic_ifstream<unsigned char>` is a quasi-non-Standard specialization, and is unsure what the motivation is for using this type.

**Comment by jessey-git** [comment]
> @CaseyCarter notes that `basic_ifstream<unsigned char>` is a quasi-non-Standard specialization, and is unsure what the motivation is for using this type.

As somewhat alluded to in #817, it's kind of about trying to have sane concepts in your api's and types.  Surely, if you open a stream in binary mode you'd really like to do so while using the std::byte type right? Right?! Or similar with uint8_t's or whatever might fit within your given domain while still conveying the concept of "this is an opaque blob of data" not a character string.

And right now you can't do it without resorting to extra, ugly, API calls to set the internal buffers. Maybe at least fix it for std::byte?

In my case, had I not realized that my unit tests were taking 30 to 50x longer to complete (a few seconds longer than previous) I would have subjected dozens (dozens!) of people who use my lib to very bad performance on Windows.  And Windows still needs all the help it can get due to slight performance losses everywhere else (ABI nonsense).
