### ISSUE TITLE
<xstring>: basic_string assumes trivial destructor for fancy pointers

### ISSUE THREAD

**Issue by AlexGuteniev** [microsoft/STL#2123]
https://github.com/microsoft/STL/blob/a9321cfe53ea31a7e197d5d8336167d6ca3de8b6/stl/inc/xstring#L2357-L2365

Should there be `_Ptr.~pointer()` ?

**Comment by cpplearner** [comment]
IIUC the `_Ptr` is destroyed by `basic_string` where needed:
https://github.com/microsoft/STL/blob/a9321cfe53ea31a7e197d5d8336167d6ca3de8b6/stl/inc/xstring#L4051-L4056
https://github.com/microsoft/STL/blob/a9321cfe53ea31a7e197d5d8336167d6ca3de8b6/stl/inc/xstring#L4590-L4599
https://github.com/microsoft/STL/blob/a9321cfe53ea31a7e197d5d8336167d6ca3de8b6/stl/inc/xstring#L4631-L4636

**Comment by AlexGuteniev** [comment]
Agree, didn't expect it to be constructed and destroyed in different places
