### ISSUE TITLE
<intrin0.h>: needs some stuff for `_M_ARM64`

### ISSUE THREAD

**Issue by fsb4000** [microsoft/STL#2129]
For https://github.com/microsoft/STL/pull/2127 I need

1) `__uint64ToN64_v`
2) `neon_cnt`
3) `neon_addv8`
4) `__n64`

from `<arm64_neon.h>`

https://godbolt.org/z/MbEqfshGG

**Comment by fsb4000** [comment]
clang generates only 2 errors.

```
#include <intrin0.h>

_NODISCARD int _Arm64_popcount(const unsigned long long _Val) noexcept {
    const __n64 _Result = neon_cnt(__uint64ToN64_v(_Val));
    return neon_addv8(_Result).n8_u8[0];
}

int main() {
    return _Arm64_popcount(0xFFFF);
}

```

```
$ clang++ --target=aarch64-windows-msvc -O3 -S test.cpp
test.cpp:4:11: error: unknown type name '__n64'
    const __n64 _Result = neon_cnt(__uint64ToN64_v(_Val));
          ^
test.cpp:4:36: error: use of undeclared identifier '__uint64ToN64_v'
    const __n64 _Result = neon_cnt(__uint64ToN64_v(_Val));
                                   ^
2 errors generated.
```

So does clang use different `<intrin0.h>`?
If so should I create a bug report at LLVM bugzilla?

**Comment by AlexGuteniev** [comment]
Want also `neon_cntq`, `neon_addvq8`, `__n128` to optimize `bitset::count` further than with 64-bit versions

**Comment by StephanTLavavej** [comment]
@fsb4000 Yes, according to my understanding, Clang has their own `<intrin0.h>` that they use instead of ours.
