### ISSUE TITLE
<locale> is killing server performance because of the global lock in glibc

### ISSUE THREAD

**Issue by MaruHyl** [microsoft/STL#2134]

**Comment by sylveon** [comment]
I don't think the Microsoft STL can do anything about glibc.

**Comment by StephanTLavavej** [comment]
This is a duplicate of #1652. Unfortunately, we can't fix this while preserving binary compatibility, so that issue is labeled as `vNext` and will need to wait for an upcoming binary-breaking overhaul (there is no ETA for vNext at this time).
