### ISSUE TITLE
`<variant>`: `std::invoke` cannot be applied to  `variant`'s `valueless_by_exception()` and `index()`

### ISSUE THREAD

**Issue by hewillk** [microsoft/STL#2154]
MSVC STL defines `valueless_by_exception()` and `index()` inside `_Variant_base`:

https://github.com/microsoft/STL/blob/472161105d596192194d4715ccad307c6c163b4a/stl/inc/variant#L843-L849

And the `variant` privately inherits `Variant_base `to obtain the corresponding special member functions:

https://github.com/microsoft/STL/blob/472161105d596192194d4715ccad307c6c163b4a/stl/inc/variant#L930-L932

https://github.com/microsoft/STL/blob/472161105d596192194d4715ccad307c6c163b4a/stl/inc/variant#L1006

In order to access the private `valueless_by_exception()` and `index()` functions, MSVC-STL uses the using-declaration inside the `variant`:

https://github.com/microsoft/STL/blob/472161105d596192194d4715ccad307c6c163b4a/stl/inc/variant#L1124-L1125

But we still cannot convert `variant<_Types...>` to `_Variant_base<_Types...>`, which means that the following code will be rejected:

```
#include <functional>
#include <variant>

int main() {
  std::variant<int> v;
  std::invoke(&std::variant<int>::index, v);
}
```

https://godbolt.org/z/fhT4Md853

**I don't know if this is a bug or just implementation-defined since a similar issue exists in [libc++'s `optional`](https://godbolt.org/z/dhzjfx59r).**

**Comment by timsong-cpp** [comment]
You are not allowed to take the address of standard library member functions.

**Comment by hewillk** [comment]
> You are not allowed to take the address of standard library member functions.

Do you mean that the following codes are not allowed?

```
  std::vector<std::string> v;
  std::ranges::sort(v, {}, &std::string::size);
```
