### ISSUE TITLE
`<variant>`: `variant::operator=(T&&)` accept wrong case

### ISSUE THREAD

**Issue by hewillk** [microsoft/STL#2171]
From [[variant#assign-13]](http://eel.is/c++draft/variant#assign-13) (emphasis mine):

> _Effects_:
> If `*this` holds a `Tj`, assigns` std​::​forward<T>(t)` to the value contained in `*this`.
> Otherwise, if `is_­nothrow_­constructible_­v<Tj, T> || !is_­nothrow_­move_­constructible_­v<Tj>` is `true`, equivalent to `emplace<j>(std​::​forward<T>(t))`.
> **Otherwise, equivalent to `operator=(variant(std​::​forward<T>(t)))`.**

For the last case, MSVC STL did not call `operator=(variant(std​::​forward<T>(t)))` but called `_Emplace_valueless<_TargetIdx>(_STD move(_Temp))`:
https://github.com/microsoft/STL/blob/78ff4618d4fa43eeb4bb714d76f27d88cf11a1b6/stl/inc/variant#L1068-L1093

Consider ([godbolt](https://godbolt.org/z/19d34eenE)):

```cpp
#include <variant>

struct A { 
  A() = default;
  A(A&&) = delete;
};

struct B { 
  B(A&&) {};
};

int main() {
  std::variant<A, B> v{};
  v = A{};
}
```
In this case, `_Variant_should_directly_construct_v` (that is, `is_nothrow_constructible_v<B, A> || !is_nothrow_move_constructible_v<B>`) is false, so we call `operator=(variant&&)`, but since `A`'s move constructor is deleted, we should fail.

Please note that MSVC v19.28 and v19.29 under `/std:c++17` correctly rejected it, so I don't know where the problem is (it seems to be in 87152f4).

**Comment by hewillk** [comment]
This seems more like a language issue and has nothing to do with the library, so I closed this issue, sorry for the noise.

**Comment by hewillk** [comment]
I need to know the answer.

**Comment by CaseyCarter** [comment]
This is not the result of a bug, this is an intentional behavior change from C++20 that we do not implement in earlier language modes due to the potential for breakage. In C++20, [[variant.assign]/11](https://eel.is/c++draft/variant.assign#11) determines the alternative type <code>T<sub>j</sub></code> that should be either assigned to or made active for a given argument type `T`:

> Let <code>T<sub>j</sub></code> be a type that is determined as follows: build an imaginary function <code>FUN(T<sub>i</sub>)</code> for each alternative type <code>T<sub>i</sub></code> for which <code>T<sub>i</sub> x[] = {std::forward<T>(t)};</code> is well-formed for some invented variable <code>x</code>. The overload <code>FUN(T<sub>j</sub>)</code> selected by overload resolution for the expression <code>FUN(std::forward<T>(t))</code> defines the alternative <code>T<sub>j</sub></code> which is the type of the contained value after assignment.

When `T` is `A` and `t` is an lvalue of type `A`, as in the sample program,
```c++
A x[] = { std::forward<A>(t) };
```
is ill-formed since `A` has a deleted move constructor, but
```c++
B x[] = { std::forward<A>(t) };
```
is well-formed. Consequently, the imaginary overload set only contains `FUN(B)`, which is selected by overload resolution, and the sample program correctly changes the active alternative of `v` to a `B` initialized from `A{}`.

(I suspect libstdc++ hasn't implemented this C++20 change yet, but on the off chance it's a bug let's tag @jwakely.)

**Comment by jwakely** [comment]
P0608 was implemented for GCC 10.1, but is enabled unconditionally for C++17 and C++20.

**Comment by CaseyCarter** [comment]
> P0608 was implemented for GCC 10.1, but is enabled unconditionally for C++17 and C++20.

I think you have a bug in your assignment operator, then. Interestingly, the converting constructor seems to do the right thing : https://godbolt.org/z/rxTGPzcx9.

**Comment by hewillk** [comment]
> Consequently, the imaginary overload set only contains FUN(B), which is selected by overload resolution, and the sample program correctly changes the active alternative of v to a B initialized from A{}.

I can't understand. Under your description, `Tj` is `B` and `T` is `A`, so we will initialize `B` with `A{}`, but isn't this behavior defined in [[variant#assign-13]](http://eel.is/c++draft/variant#assign-13) as using **deleted** `variant::operator=(variant&&)` for `B`'s initialization?

**Comment by jwakely** [comment]
https://cplusplus.github.io/LWG/issue3585

**Comment by CaseyCarter** [comment]
Thank you @hewilk for pointing out that the wording doesn't say what I want it to say despite my determined efforts to be unteachable, and thank you @jwakely for filing this LWG issue to keep `variant`'s assignment operators consistent with its constructors.

**Comment by hewillk** [comment]
I think this issue was submitted by @BRevzin, thank you.

**Comment by frederick-vs-ja** [comment]
This seems fixed since LWG-3585 has been voted into the Working Paper...

**Comment by CaseyCarter** [comment]
> This seems fixed since [LWG-3585](https://cplusplus.github.io/LWG/issue3585) has been voted into the Working Paper...

Yes it is - this issue fell through the cracks. LWG-3585 standardized our implementation.
