### ISSUE TITLE
<cstdlib>: missing std::aligned_alloc function.

### ISSUE THREAD

**Issue by B1aNB1aN** [microsoft/STL#2176]
**Describe the bug**
std::aligned_alloc is added to c++ standard at c++17 standard. Is there any plan to implement this function?

**Comment by fsb4000** [comment]
No, as far as I know.

Use `_aligned_malloc` and `_aligned_free`

https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/aligned-malloc?view=msvc-160

**Comment by CaseyCarter** [comment]
@fsb4000 has it right. Windows supports aligned allocation, but those allocations can't be deallocated by `free`, so there's no way to support `aligned_alloc` without major destabilizing changes. Windows folk have expressed to us a distinct lack of interest in making such changes.
