### ISSUE TITLE
LWG-3530 `BUILTIN-PTR-MEOW` should not opt the type out of syntactic checks

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#2182]
LWG-3530 *`BUILTIN-PTR-MEOW`* should not opt the type out of syntactic checks

**Background:**

The C++ Standardization Committee's Library Working Group recently resolved the linked issue, which changed a bunch of complicated wording in the C++ Standard. The good news is that our implementation already conforms to the updated Standard, so all we have to do is remove a bunch of comments from the code. (These comments cited our also-complicated issue GH-489 - no need to read that issue, just citing it for completeness.)

Specifically, there are 11 comments saying `// TRANSITION, GH-489` across 4 files (`<compare>`, `<functional>`, `<system_error>`, and `<xutility>`), for example:

https://github.com/microsoft/STL/blob/6fe2eae6b5163c6fd97cec5ce8a7bd6392757145/stl/inc/compare#L324-L326

**Necessary changes:**

* Find and remove all 11 occurrences of `// TRANSITION, GH-489`.
* Avoid leaving any trailing whitespace (if you do, our automated checks will detect that).
  + Many editors (including VSCode) have commands to Trim Trailing Whitespace. For convenience, if you use VSCode's Open Folder on our repo, it will automatically trim trailing whitespace when you save files. (This is controlled by [this line](https://github.com/microsoft/STL/blob/6fe2eae6b5163c6fd97cec5ce8a7bd6392757145/.vscode/settings.json#L19) in our `.vscode/settings.json`, if you're curious.)

---

This issue is intended for a new contributor (especially one new to GitHub) to get started with the simplest possible change.

Please feel free to submit a pull request if there isn't one already linked here - no need to ask for permission! :smile_cat:

You can (and should) link your pull request to this issue using [GitHub's close/fix/resolve syntax](https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

**Comment by AnudeepGunukula** [comment]
Hi @StephanTLavavej . i had made a pr that will close this issue.
