### ISSUE TITLE
LWG-3543 Definition of when `counted_iterator`s refer to the same sequence isn't quite right

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#2184]
LWG-3543 Definition of when `counted_iterator`s refer to the same sequence isn't quite right

In #1965, @frederick-vs-ja categorized this as:

> Implemented at first, only comments should be updated.
> `_Same_sequence` performs as least increments as possible, which is still OK for current wording

The comment is:

https://github.com/microsoft/STL/blob/6fe2eae6b5163c6fd97cec5ce8a7bd6392757145/stl/inc/iterator#L1278-L1284

I agree that the comment should be updated to cite WG21-N4892's new wording. (It appears that this isn't a case where the comment should be removed entirely.)

**Comment by AlexGuteniev** [comment]
I don't like the new wording, as according to it, the current `_Same_sequence` may be claimed wrong, as it does not try each possible `n` that might exist, instead assuming a specific `n`.

Otherwise, looks good-first-issuish.
