### ISSUE TITLE
spaceship: std::map does not use specialised operator< for value

### ISSUE THREAD

**Issue by gjasny** [microsoft/STL#2234]
Hello,

I stumbled over this issue when porting a code base from C++17 to C++20. Both: GNU libstdc++ as well as MSVC STL show the unexpected behaviour. Libc++ seems to do the right thing.

**Describe the bug**
Compiling the test case with C++17 works as expected whereas compiling it with C++20 makes the test assumption fail.
The reason is that for C++ 20 builds the specialised `operator<(const FooPtr& left, const FooPtr& right)` is not picked up. Instead the default `operator<=>` for `std::shared_ptr` is used which only compares the raw pointers and not the content they point to.

**Command-line test case**
```c++
#include <algorithm>
#include <iostream>
#include <map>
#include <memory>
#include <stdexcept>

struct Foo {
    int i;
};

using FooPtr = std::shared_ptr<Foo>;
using Map = std::map<int, FooPtr>;

#if 0

#include <compare>

std::strong_ordering operator<=>(const Foo& left, const Foo& right)
{
    return left.i <=> right.i;
}

std::strong_ordering operator<=>(const FooPtr& left, const FooPtr& right)
{
    return *left <=> *right;
}

#else

bool operator<(const Foo& left, const Foo& right)
{
    return left.i < right.i;
}

bool operator<(const FooPtr& left, const FooPtr& right)
{
    return *left < *right;
}

#endif

int main(int argc, const char * argv[]) {

    // Create two shared pointers to Foo whose pointer addresses
    // compare inverse to their content
    
    auto p1 = std::make_shared<FooPtr::element_type>();
    auto p2 = std::make_shared<FooPtr::element_type>();
    
    auto& smallerAddress = (p1.get() < p2.get()) ? p1 : p2;
    auto& largerAddress = (p1.get() > p2.get()) ? p1 : p2;
    
    *smallerAddress = {2}; // assign larger value
    *largerAddress = {1}; // assign smaller value

    auto& smallerValue = largerAddress;
    auto& largerValue = smallerAddress;
    
    const auto smallerMap = Map{{ 0, smallerValue }};
    const auto largerMap = Map{{ 0, largerValue }};
    
    if (largerMap < smallerMap) {
        std::cerr << "WRONG result: smaller\n";
        //throw new std::runtime_error("Unexpected Comparison Result");
    } else {
        std::cerr << "CORRECT result: larger\n";
    }
    
    return 0;
}
```

**Expected behavior**
I'd expect that with C++17 and C++20 the STL would prefer the specialized `operator<(const FooPtr& left, const FooPtr& right)` over the synthesised `<=>` one. The would also align with the strong backwards compatibilities C++ strives for.

**STL version**
```
Microsoft Visual Studio Professional 2022 Preview (64-bit)
Version 17.0.0 Preview 4.1
```

**Additional context**
Testcase is also here: https://github.com/gjasny/map-spaceship-testcase

Thanks,
Gregor

**Comment by gjasny** [comment]
GNU libstdc++ issue: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=102589

**Comment by hewillk** [comment]
This is the expected result. The reason why libc++ behaves differently is that [p1614r2](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p1614r2.html#clause-22-containers-library) has not yet been fully implemented.

**Comment by miscco** [comment]
It is at least a bit unfortunate that we silently changed the place where one could overwrite the default implementation

**Comment by jwakely** [comment]
Redefining what comparisons mean for `shared_ptr<X>` is a bit questionable anyway, even if `X` is a program-defined type.

**Comment by CaseyCarter** [comment]
This is the intended behavior, which jwakely explains well at https://gcc.gnu.org/bugzilla/show_bug.cgi?id=102589.
