### ISSUE TITLE
P2415R2 What Is A `view`?

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#2238]
[P2415R2](https://wg21.link/P2415R2) What Is A `view`?

Note: If this link appears to be broken, don't worry! Papers are often revised during a WG21 meeting before the final vote. When that happens, there's a delay of a few weeks between the end of the meeting and the publication of the papers. When the papers are available, the https://wg21.link redirector will start working.

This increases the value of `__cpp_lib_ranges`.

**Comment by CaseyCarter** [comment]
> This increases the value of `__cpp_lib_ranges`.

Fun fact: this means that `__cpp_lib_ranges` will be _twenty_ months after `__cplusplus` when compiling in C++20 mode.

**Comment by timsong-cpp** [comment]
> > This increases the value of `__cpp_lib_ranges`.
> 
> Fun fact: this means that `__cpp_lib_ranges` will be _twenty_ _months_ _after_ `__cplusplus` when compiling in C++20 mode.

*frantically tries to find something to write a paper on so that we can make it a nice round 24*

**Comment by BRevzin** [comment]
> > > This increases the value of `__cpp_lib_ranges`.
> > 
> > 
> > Fun fact: this means that `__cpp_lib_ranges` will be _twenty_ _months_ _after_ `__cplusplus` when compiling in C++20 mode.
> 
> _frantically tries to find something to write a paper on so that we can make it a nice round 24_

You rang?
