### ISSUE TITLE
winapinls.cpp: static_assert is_sorted() for the lookup tables

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#224]
After #6 is implemented, we should use `constexpr is_sorted()` in `winapinls.cpp`.

**Comment by BillyONeal** [comment]
Note that we compile that thing with MSVC, so even though we can implement #6 now because Clang has support for `is_constant_evaluated`, we need MSVC to support that before attempting to resolve this item.

**Comment by StephanTLavavej** [comment]
Also applies to the `validate.cpp` tool:

https://github.com/microsoft/STL/blob/f9b1dccd121b5f8bb76d06adb0c85aac3f766326/tools/validate/validate.cpp#L173-L176
