### ISSUE TITLE
P0288R9 `move_only_function`

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#2241]
[P0288R9](https://wg21.link/P0288R9) `move_only_function`

Feature-test macro:
`__cpp_lib_move_only_function`

**Comment by AlexGuteniev** [comment]
I think while it could be possible to tune the existing `function` to handle move-only implementation, it is better to have a new better implementation. Better means it should at least address #969, also I have some additional thoughts on a better function.

**Comment by AlexGuteniev** [comment]
@MikeGitb, after giving this more thoughts, I think probably it could be a good option to use bits, as you suggested. Specifically:
 * Bit for trivial destructor
 * Bit for trivial move

With trivial move bit set, will `memcpy` exactly two pointers. This will cover:
 * Large functions
 * Small functions with size of a pointer or less (this includes plain pointers and trivial lambdas)
 * Empty functions (will unnecessarily copy one pointer, but given `alignas(8)` and SSE2 as baseline, this will cause no performance difference whether copy one pointers or two)
    *  Need to make sure for empty function second pointer is initialized to zero: to avoid reading initializing memory that may be flagged by address sanitizing tools, and to make store of empty function double-pointer store, and enable load-to-store forwarding

**Comment by AlexGuteniev** [comment]
@MikeGitb, I've experimented with optimizations:
1. always call by pointer
2. check pointer bits (before reaching fake vtable)
3. check vtable entries for null

2 and 3 are somewhat better than 1. Still there's not enough evidence to tell if 2 or 3 is better.

So I'll keep option 3 as it is simpler. You can try a PR after my PR is hopefully submitted if you think 2 is better, or can suggest other improvements (I think it is free to change, as no ABI stability is promised for C++23).
