### ISSUE TITLE
P1675R2 `rethrow_exception` Must Be Allowed To Copy

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#2248]
[P1675R2](https://wg21.link/P1675R2) `rethrow_exception` Must Be Allowed To Copy

No feature-test macro is mentioned.

From a quick glance at the paper, I believe that it is N/A - nothing for implementers to do, it simply permits MSVC's current implementation. After confirming that, we should resolve this issue and remove the **cxx23** label, as it was never a feature to begin with.

**Comment by fsb4000** [comment]
it looks like N/A for me too.

**Comment by CaseyCarter** [comment]
Thirded, the intent of this change is to allow our EH runtime's behavior to conform.
