### ISSUE TITLE
P2321R2 `zip`

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#2252]
[P2321R2](https://wg21.link/P2321R2) `zip`

Feature-test macro:
```cpp
#define __cpp_lib_ranges_zip 202110L
```

Be sure to implement the resolutions of these LWG issues which patch this feature:

* LWG-3692 `zip_view::`_`iterator`_'s `operator<=>` is overconstrained
* LWG-3702 Should `zip_transform_view::`_`iterator`_ remove `operator<`?
* LWG-3773 `views::zip_transform` still requires `F` to be `copy_constructible` when empty pack
* LWG-3798 Rvalue reference and `iterator_category`
  + Affects `views::adjacent_transform`, see [\[range.adjacent.transform.iterator\]/1.1](https://eel.is/c++draft/range.adjacent.transform.iterator#1.1).
* LWG-3848 `adjacent_view`, `adjacent_transform_view`, and `slide_view` missing `base` accessor

and the pertinent changes from [P2165R4](https://wg21.link/P2165R4) and [P2494R2](https://wg21.link/P2494R2).

**Comment by Ukilele** [comment]
Not that I would want to make promises, that I will create a MR any time soon. But I at least implemented some of the minor changes as well as zip_view in https://github.com/Ukilele/STL/tree/ranges_zip.
I could use some help with:
- [5.1](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2021/p2321r2.html#tuple) & [5.2](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2021/p2321r2.html#pair): Constructors and assignment operators for `std::tuple` and `std::pair`
- [5.4](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2021/p2321r2.html#conversion-and-common-type-for-integer-class-types): Not sure which changes this requires
- [5.6](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2021/p2321r2.html#zip): Is implemented as described in the paper. But are there functions whose noexceptness should be strengthened?

**Comment by miscco** [comment]
Hey do you need any help with this?

**Comment by Ukilele** [comment]
Hey @miscco , I assume this question is addressed to me? If so, thanks for asking! Unfortunately, currently I wont find the time to work on this. The missing parts in my branch are noexcept-strengthening, unit tests as well as `adjacent` and `adjacent_transform`.

**Comment by miscco** [comment]
Note that you do not need to implement everything in a go.

Could you do a squash and rebase on main? I would be happy to give it another round of review and Tam implemented most prerequisites

**Comment by Ukilele** [comment]
Squashed and rebased on main 🙂

**Comment by frederick-vs-ja** [comment]
[P2165R4](https://wg21.link/P2165R4) also changes `zip_view` etc. (making them no longer use `pair`) and `basic_common_reference` and `common_type` partial specializations.

**Comment by CaseyCarter** [comment]
> [P2165R4](https://wg21.link/P2165R4) also changes `zip_view` etc. (making them no longer use `pair`) and `basic_common_reference` and `common_type` partial specializations.

I will add a note to the OP to make sure that `zip` implementation doesn't miss the changes from P2165R4. There's enough to P2165R4 that I think of it as more a standalone feature than simply a patch on `zip`, so I'll leave the separate feature issue.
