### ISSUE TITLE
P2393R1 Cleaning Up Integer-Class Types

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#2254]
[P2393R1](https://wg21.link/P2393R1) Cleaning Up Integer-Class Types

No feature-test macro is mentioned.

**Comment by timsong-cpp** [comment]
This paper is really a mega-LWG issue resolution.

**Comment by frederick-vs-ja** [comment]
MSVC STL doesn't provide integer-class types. So it seems that we can only add comments.

**Comment by frederick-vs-ja** [comment]
Oh, I'm sorry for rechecking this so late...
The wording changes are made to ensure the well-formedness when a integer-class type is involved. Unlike integer types, implicit conversion between one integer-class type and one integer type or two integer-class types is not always allowed (although the implementation may always allow it). So explicit cast is needed in some places.
IIUC nothing needs to be changed if the implementation doesn't provide integer-class types.

I guess we shoule say the status is N/A at this moment. However, if integer-class types come into MSVC STL in future (probably an API- and ABI-breakage), then this DR needs to be considered.

**Comment by StephanTLavavej** [comment]
@CaseyCarter Now that you've implemented 128-bit integers, are implementation changes required here?

**Comment by CaseyCarter** [comment]
I was working to the updated [iterator.requirements.winc] when implementing `_Signed128` / `_Unsigned128` - so they are fine - but I had forgotten the little tweaks this proposal makes to wording elsewhere. So yes, there are changes required.
