### ISSUE TITLE
 LWG-2762 unique_ptr operator*() should be noexcept

### ISSUE THREAD

**Issue by AlexGuteniev** [microsoft/STL#2257]
LWG-2762 asks for `unique_ptr` and `optional` indirection operators to be `noexcept`

`unique_ptr` is already `noexcept`. It is marked as `/* strengthened */` as this `noexcept` was not previously require by the Standard.

Note that LWG requires conditional `noexcept(noexcept(*declval<pointer>()))`

According to [[unique.ptr.single.general]/3](http://eel.is/c++draft/unique.ptr.single.general#3), `unique_ptr<T, D>` may obtain fancy pointer as underlying pointer type via `remove_­reference_­t<D>​::​pointer`. 

https://github.com/microsoft/STL/blob/dc888f7d9fb7a4db8d3441f9e9bac2e0c6ecc4db/stl/inc/memory#L3210

So the fix is to change `noexcept` to conditional, and remove  `/* strengthened */` comment.

`optional` misses `noexcept`, it should be added:
https://github.com/microsoft/STL/blob/dc888f7d9fb7a4db8d3441f9e9bac2e0c6ecc4db/stl/inc/optional#L345-L381
These are unconditional.

**Comment by frederick-vs-ja** [comment]
Is the unconditional `noexcept` for `unique_ptr::operator*` too strong to be conforming? It seems that `unique_ptr::operator*` is allowed to throw an exception (from the throwing underlying `operator*`).

**Comment by AlexGuteniev** [comment]
> Is the unconditional `noexcept` for `unique_ptr::operator*` too strong to be conforming?

Yes, already edited. Hopefully it does not require `vNext`
