### ISSUE TITLE
<functional>: Avoid pessimization in `std::move_only_function` assignment operators

### ISSUE THREAD

**Issue by AlexGuteniev** [microsoft/STL#2278]
Does the below look like a valid LWG issue?

----

In `std::move_only_function` wg21-p0288, some assignments are defined in terms of `swap` (in [func.wrap.mov.con])

> `move_only_function& operator=(move_only_function&& f);`
> _Effects:_ Equivalent to: `move_only_function(std::move(f)).swap(*this);`

> `template<class F> move_only_function& operator=(F&& f);`
>  _Effects:_ Equivalent to: `move_only_function(std::forward<F>(f)).swap(*this);`

The implementation of assignment via swap is normally useful for exception safety.

However, this is superfluous here, as `move_only_function` is moved with `noexcept`.

At the same time, this approach causes extra moving of function. This may be expensive due to large small-functor-optimization buffer, and due to calling user-provided move constructor for small factor.

Looks like the optimizations made by implementation to avoid extra moving cannot always be made, as calling user-provided move constructor is observable.

I propose:
~add `nocexcept` to move assingment `move_only_function& operator=(move_only_function&& f) noexcept;`~
change the mentioned methods to say:

> `move_only_function& operator=(move_only_function&& f);`
> _Effects:_ the target object of `this` is set to the target object of `f` before the assignment and leaves f in a valid state with an unspecified value.

> `template<class F> move_only_function& operator=(F&& f);`
>  _Effects:_ Equivalent to: `*this = move_only_function(std::forward<F>(f));`

**Comment by AlexGuteniev** [comment]
> adding allocator support in the future.

Allocator support was already removed from `std::function`, will it get a second chance?

> I'm also not seeing how this is observable. Nothing in the specification of swap requires it to call the move constructor of the targets.

So can I just implement these operations as I proposed, without changed wording?

**Comment by MikeGitb** [comment]
Re allocator: Please DON'T.

What would be much more useful is a guaranted minimal size for the small buffer. If I know that objecst smaller than e.g. two pointers doesn't get allocated on the heap, I can create my own wrapper for the callable that takes care of allocation. std::function/move_only_function doesn't have to know about that.

Speaking of which (sorry for the slight off topic): Could you please talk to the libc++ and libstdc++ guys and see if you can agree on a common size for SBO?

Re observability: Maybe I'm missunderstanding your concern, but if the standard guarantees that after
   
    std::move_only_function f1 = callable1;
    {
        std::move_only_function f2 = callable2.;
        f1=std::move(f2);
    }
   
f1 contains callable2., then that's of course an observable property.  Most obviously, I'm allowed to do `f1()`  and get callable2() and of course the order in which the destructors of `callable1` and `callable2` run might also be observable, if they have sideeffects.

**Comment by AlexGuteniev** [comment]
@MikeGitb ,

> What would be much more useful is a guaranted minimal size for the small buffer

You have this. 

[func.wrap.func.con]/14:
> Throws: Nothing if FD is a specialization of reference_­wrapper or a function pointer type. Otherwise, may throw bad_­alloc or any exception thrown by the initialization of the target object.

 [func.wrap.mov.con]/22
> Throws: Any exception thrown by the initialization of the target object. May throw bad_alloc unless VT is a function pointer or a specialization of reference_wrapper.

I think no-bad_alloc is unimplementable if SBO cannot fit a pointer

**Comment by AlexGuteniev** [comment]
Since the optimizations to special case to destroy small-trivially-destructible and move small-trivially-moveable or large functors are there, I'm taking advantages of this information to optimize swap:
1. If the new target is empty or large or small-trivially-moveable-fitting-one-pointer, then move is not observable, destroy old target if needed, and move the new one in.
2. Otherwise, if the current target is empty or small-trivially-destructible, just move the new target in
3. Finally do the whole thing of moving out old target to temporary, moving the new target to the instance, and destroying old target

See here
https://github.com/AlexGuteniev/STL/blob/ec120ed618e2404fe83030ebbbefbd8b3c014b9c/stl/inc/functional#L1405-L1430

This avoids any potentially observable difference against the standard, whereas still optimizing many cases, and the checks are fused with the optimization checks that would otherwise have been there anyway.

I'm satisfied with this enough to avoid raising this issue.

**Comment by MikeGitb** [comment]
That makes sense. Thanks for explaining

**Comment by StephanTLavavej** [comment]
Thanks for looking into this. After thinking about this issue and your implementation, I think it would be reasonable to file an LWG issue, but I believe there's a moderate chance of it being resolved as Not A Defect. I also think that your current implementation in #2267 is an efficient way to handle the current wording.

**Comment by AlexGuteniev** [comment]
This is LWG-3642 now

**Comment by AlexGuteniev** [comment]
Should we close this?
-  Mitigation is implemented
-  LWG-3642 is there
-  Clearly no justification to implement LWG speculatively

**Comment by CaseyCarter** [comment]
Yes, I'm happy to close this and wait for LWG-3642 to tell us what (if anything) to change.
