### ISSUE TITLE
`<memory>`, `<optional>`, `<any>`: Implicit SFINAE constraints

### ISSUE THREAD

**Issue by frederick-vs-ja** [microsoft/STL#2299]
**Describe the bug**
According to [[structure.specifications]/4](https://eel.is/c++draft/structure.specifications#4), some uses of "_Effects:_ Equivalent to" specifies "_Constraints:_" of the underlying function calls. I suppose that it only propagates "_Constraints:_" specified for standard library functions, not literal `requires` or other substitution failures, and the implied "_Constraints:_" were specified by "_Remarks:_" in C++11~17 (in other words, essentially unchanged in C++20).

From a quick glance at WG21-N4901, I think the following functions have additional SFINAE constraints (and currently there're some defects in N4901):
- template overloads of `std::shared_ptr::operator=`
- template overloads of `std::shared_ptr::reset`
- template overloads of `std::weak_ptr::operator=`
- `std::make_optional`
- `std::make_any`
- the template overload of `std::move_only_function::operator=`
(Anything missing?)

Currently none of these functions is constrained in MSVC STL (except for `std::move_only_function::operator=`, which is being implemented).

As all of these functions have the same "_Constraints:_" as the selected constructors, perhaps we can simply add `enable_if_t<is_constructible_v<...>, int> = 0` to them.

I have submitted 2 related LWG issues:
- LWG-3627: `std::make_optional` overloads are inconsitently specified. IMO they should all be constrained.
- LWG-3628: `uninitialized` algorithms and some `std::reduce` overloads are also specified by "_Effects:_ Equivalent to", but I feel that they are misspecified and should not have additional SFINAE constraints.

**Comment by StephanTLavavej** [comment]
I originally filed this as #214 but didn't have the list of specific occurrences that you've found here - thanks! :smile_cat:
