### ISSUE TITLE
<filesystem>: std::filesystem::file_status missing the no throw constructor

### ISSUE THREAD

**Issue by niclar** [microsoft/STL#2332]
The filesystem implementation seems to be missing the no throw constructor, i.e;
std::filesystem::file_status status( const std::filesystem::path& p, std::error_code& ec ) noexcept

( C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.31.30818\include\filesystem )

**Comment by fsb4000** [comment]
I don't see such constructor there: https://en.cppreference.com/w/cpp/filesystem/file_status/file_status

**Comment by fsb4000** [comment]
Do you mean this?
https://github.com/microsoft/STL/blob/178b8406a5647507e759442960f17cd33045cdf5/stl/inc/filesystem#L3673-L3677

**Comment by StephanTLavavej** [comment]
Yep, this appears to be correctly implemented; thanks @fsb4000 for finding the definition. I'll go ahead and close this issue - if we've misunderstood something, please let us know.
