### ISSUE TITLE
<algorithm>: clamp produces unoptimal assembly with branches

### ISSUE THREAD

**Issue by lhecker** [microsoft/STL#2334]
The implementation of `std::clamp` is implemented in terms of using `std::less` here: https://github.com/microsoft/STL/blob/178b8406a5647507e759442960f17cd33045cdf5/stl/inc/algorithm#L10178-L10182

Unfortunately this has the side-effect of being harder to optimize for MSVC.

For `T = int`, `std::clamp` produces:
```asm
int std_clamp(int,int,int) PROC
        cmp     r8d, ecx
        jge     SHORT $LN6@std_clamp
        mov     eax, r8d
        ret     0
$LN6@std_clamp:
        cmp     ecx, edx
        cmovl   ecx, edx
        mov     eax, ecx
        ret     0
int std_clamp(int,int,int) ENDP
```

As MSVC appears to have specific optimizations to compile ternaries into conditional assignments (`cmov`), an implementation based on `std::min/max` produces a version without branching:
```cpp
template<class T>
constexpr const T& my_clamp(const T& v, const T& lo, const T& hi) {
    return std::max(lo, std::min(hi, v));
}
```

```asm
int min_max_clamp(int,int,int) PROC
        cmp     edx, r8d
        cmovl   r8d, edx
        cmp     ecx, r8d
        cmovl   ecx, r8d
        mov     eax, ecx
        ret     0
int min_max_clamp(int,int,int) ENDP
```

This advantage holds up even if the comparator for `T` is more complex, like the one for `std::string`.
`clang` doesn't need such special treatment, which is why this could be considered a compiler optimization issue.

**Comment by AlexGuteniev** [comment]
I don't know why, but when I tried ternaries, it did not emit `cmov`, but when used `min`/`max` it did.

Btw, don't use exactly this `my_clamp` elsewhere, `v` and `lo` should be swapped there.

**Comment by AlexGuteniev** [comment]
Figured it out.
The current version as it is written is better for types where skipping one comparison is of advantage.
As it does early return.

I.e. this is helpful if the second condition may be not evaluated:
https://github.com/microsoft/STL/blob/178b8406a5647507e759442960f17cd33045cdf5/stl/inc/algorithm#L10167-L10173

To make the best of two worlds, let's specialize `clamp` for integers and pointers!

**Comment by AlexGuteniev** [comment]
Discovered that the branchless version is worse when all values are in range.

**Comment by AlexGuteniev** [comment]
Need maintainers decision if we should optimize worst case (random out of range and in range inputs) by making best case (all values are in range) worse.

**Comment by StephanTLavavej** [comment]
We talked about this at the weekly maintainer meeting, and we believe that such an optimization (improving the worst case but degrading the best case) **wouldn't** be desirable, both due to our preference for pure optimizations, and our belief that for `clamp` specifically, values should generally be expected to be in-range.

Should we go ahead and close this issue then?

**Comment by AlexGuteniev** [comment]
@StephanTLavavej , apparently we need to investigate this issue more, and possibly even try the reverse: preventing cmov generation. (Currently branchy is half-branchy, it has one jcc, and one cmov)

**Comment by AlexGuteniev** [comment]
@StephanTLavavej , currently it looks like that 
 * Branchy version is better on Intel, branchless version is better on AMD
 * Without LTCG, branchy version is pessimized by not using registers, and becomes only slightly better than branchless on Intel and more worse than branchless on AMD

Regarding the reverse, that is making branchy version more branchy: apparently it is not possible to persuade the compiler to do this, although older compiler versions did this by themselves.

**Comment by AlexGuteniev** [comment]
Another variable here is `/QIntel-jcc-erratum`. It makes branchy version better on Intel. 
I've created DevCom-1603517 to make this implied by default, unless targeting for AMD.

With values in range+LTCG+/QIntel-jcc-erratum the current branchy one is a certain win: 
```
Type: ints branchy: 0.569531 branchless: 0.702434
```

**Comment by AlexGuteniev** [comment]
> possibly even try the reverse: preventing cmov generation. (Currently branchy is half-branchy, it has one jcc, and one cmov)

This is currently not possible, we don't have this level of control. I've created DevCom-1603545 for that.

So the current options are either accept the current PR (optimizing worst case everywhere and best case for AMD, but pessimizing best case for Intel) or do nothing.
