### ISSUE TITLE
`<xlocale>` `locale0.cpp`: `_Facet_Register`: should not `(_Fac_node*)_Fac_head` be deleted？

### ISSUE THREAD

**Issue by ScuptFang** [microsoft/STL#2354]
**Describe the bug**
(_Fac_node*)_Fac_head is consRT but doesnot be deleted, using mimalloc for printing info.

**Command-line test case**

#include <mimalloc-override>
#include <iostream>
#include <fstream>
using namespace std;
int main() {
    ifstream ifn;
    ifn.open("xxx.xxx", std::ios::in); //when file exists, ifstream::open call _Facet_Register : _Fac_head = new _Fac_node(_Fac_head, _This);
    ifn.close();
    mi_collect(true);
    mi_stats_print(nullptr);
    return 0;
}

**Expected behavior**
In debug mode, _Fac_node will call malloc_dbg. BP in the free code never hits at all:
    //relate to local0.cpp
    void operator delete(void* _Ptr) noexcept { // replace operator delete
        _free_dbg(_Ptr, _CRT_BLOCK); // <- set a bp for test.
    }

In release mode, mimalloc could tell the block which doesnot be freed and the address of that page is the same with _Fac_head's.

**STL version**
Microsoft Visual Studio Community 2019
Version 16.11.3

**Additional context**
![image](https://user-images.githubusercontent.com/40800491/142964362-d9c3129d-53ed-4370-bcdd-c32c45ae25fc.png)

**Comment by ScuptFang** [comment]
Additional: 
If this block will be freed after the 'main' function, are there any available ways to control it earlier? thanks STL.

**Comment by StephanTLavavej** [comment]
Thanks for reporting this. We'll need to look into this - from a glance at the source code, we're overloading `operator new` and `operator delete` to mark the allocation as a `_CRT_BLOCK` (so it won't be reported as a leak by the CRT's leak tracking machinery), and then using `new` and `delete` to invoke these overloaded operators. I believe it's deleted here:

https://github.com/microsoft/STL/blob/3c2fd04d441d46ec9d914d9cbb621a3bac96c3a5/stl/src/locale0.cpp#L52-L62

**Comment by ScuptFang** [comment]
> Thanks for reporting this. We'll need to look into this - from a glance at the source code, we're overloading `operator new` and `operator delete` to mark the allocation as a `_CRT_BLOCK` (so it won't be reported as a leak by the CRT's leak tracking machinery), and then using `new` and `delete` to invoke these overloaded operators. I believe it's deleted here:
> 
> https://github.com/microsoft/STL/blob/3c2fd04d441d46ec9d914d9cbb621a3bac96c3a5/stl/src/locale0.cpp#L52-L62
> 
> We don't support attempting to delete this earlier.

Thank your reply. I had noticed this snippet, and it's deleted in the deconstruction of '_Fac_tide_reg' after the 'main', thanks again. closing it.
