### ISSUE TITLE
Tests should support AddressSanitizer

### ISSUE THREAD

**Issue by wmyyy** [microsoft/STL#2355]
Hi All,

I have follow [How To Build With A Native Tools Command Prompt](https://github.com/microsoft/STL#how-to-build-with-a-native-tools-command-prompt) to build STL project with visual studio. When I try to use AddressSanitizer by set compiler option: set _ CL _=/fsanitize=address /GS- /wd5072 /wd4100 /fno-sanitize-address-vcasan-lib and link option: set _ LINK _="clang_rt.asan_dynamic-x86_64.lib" "clang_rt.asan_dynamic_runtime_thunk-x86_64.lib" to build the project. Then run the tests follow [How To Run The Tests With A Native Tools Command Prompt](https://github.com/microsoft/STL#how-to-run-the-tests-with-a-native-tools-command-prompt), there are some tests failed. If not use AddressSanitizer, there is no failed tests, so I wonder if the tests for STL support AddressSanitizer, could you please help comfirm?

Thanks a lot

**Comment by fsb4000** [comment]
No, the tests didn't support AddressSanitizer.
Probably there are some bugged tests...

![изображение](https://user-images.githubusercontent.com/4289847/143015570-43560199-13a0-42d5-88b1-b16f35c12ab0.png)

**Comment by AlexGuteniev** [comment]
Which tests fail and for what reasons?

**Comment by CaseyCarter** [comment]
Changing this from a question to an actual issue. Ideally the tests would support ASAN - we need to analyze the failures and file some issues to get things cleaned up.

**Comment by wmyyy** [comment]
Hi @CaseyCarter @AlexGuteniev ,

Thanks a lot for your reply!
For AddressSanitizer, while running the tests, pop out below error window many times. 
![image](https://user-images.githubusercontent.com/17844901/143202622-fd29025f-f17e-4bbd-9993-9e3d75eff1c5.png)
You can reproduce the error by running any one failed subset of a test suite (step6) . And I have attached test log
[testlog.txt](https://github.com/microsoft/STL/files/7594075/testlog.txt)
 for one failed subset of a test suite. You can also reproduce the error by below steps:

1. Open an "x64 Native Tools Command Prompt for VS 2022 Preview".
2. Change directories to the previously cloned STL directory.
3. set _ CL _=/fsanitize=address /GS- /wd5072 /wd4100 /fno-sanitize-address-vcasan-lib
4. set _ LINK _="clang_rt.asan_dynamic-x86_64.lib" "clang_rt.asan_dynamic_runtime_thunk-x86_64.lib"
3. cmake -G Ninja -S . -B out\build\x64
4. ninja -C out\build\x64
5. cd STL\out\build\x64
6. python tests\utils\stl-lit\stl-lit.py -v ..\..\..\tests\std\tests\Dev08_496675_iostream_int_reading

**Comment by AlexGuteniev** [comment]
@wmyyy , hm, I don't think this is right to build the STL itself with ASan, and you should only build tests with it.
So move your steps 3 and 4 after step 6.

**Comment by AlexGuteniev** [comment]
Hm, I cannot recreate the issue with your steps

**Comment by cbezault** [comment]
@wmyyy can you confirm what VS version you're using?

**Comment by cbezault** [comment]
There's also the problem that the steps you have posted will link the release asan runtimes into the debug c++ runtime.

**Comment by cbezault** [comment]
After hacking the `CMakeLists.txt` to link in the appropriate libs the only failures I'm seeing is about `_ITERATOR_DEBUG_LEVEL` mismatching which is a known bug with the currently shipped ASan libs.

**Comment by wmyyy** [comment]
Hi @cbezault,

Thanks a lot for your reply! I use vs 2022 preview 17.1.0 Preview 1.1. According your reply, I have tried to link debug asan runtime libraries, and as you said the only failures is _ITERATOR_DEBUG_LEVEL mismatching. Since it is a known bug I will close this issue. Thanks again!

**Comment by wmyyy** [comment]
> Hm, I cannot recreate the issue with your steps

Hi @AlexGuteniev , cannot reproduce maybe due to the space between  _ CL _ and _ LINK _, I have add space here to avoid the styling with markdown, _ _ will style text Italic.
