### ISSUE TITLE
<filesystem>: `path`'s comparison operators are IF-NDR

### ISSUE THREAD

**Issue by statementreply** [microsoft/STL#2358]
**Describe the bug**

After #2000, `path`'s comparison operators are IF-NDR (ill-formed, no diagnostic required). See @Quuxplusone's [blogpost](https://quuxplusone.github.io/blog/2021/11/21/concepts-what-are-you-doing/) and @jwakely's [comment](https://www.reddit.com/r/cpp/comments/qz699h/is_path_convertible_to_string_view_a_war_story/hlmhzxr/) for a detailed analysis of similar issues in libc++ and libstdc++.

**Command-line test case**

Copied from Arthur O’Dwyer's blogpost.

```
D:\Temp>type repro.cpp
```
```cpp
#include <filesystem>
#include <ranges>

static_assert(std::ranges::range<std::filesystem::path>);
static_assert(std::ranges::range<const std::filesystem::path>);
```
```
D:\Temp>clang-cl /c /EHsc /W4 /std:c++latest /D_HAS_CXX23=1 repro.cpp
repro.cpp(5,1): error: static_assert failed
static_assert(std::ranges::range<const std::filesystem::path>);
^                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
repro.cpp(5,28): note: because 'const std::filesystem::path' does not satisfy 'range'
static_assert(std::ranges::range<const std::filesystem::path>);
                           ^
D:\repos\STL\out\\build\x64\out\inc\xutility(2233,9): note: because '::std::ranges::begin(__r)' would be invalid: no
      matching function for call to object of type 'const _Begin::_Cpo'
        _RANGES begin(__r);
        ^
D:\repos\STL\out\\build\x64\out\inc\yvals_core.h(1411,20): note: expanded from macro '_RANGES'
#define _RANGES    ::std::ranges::
                   ^
1 error generated.
```

**STL version**

https://github.com/microsoft/STL/commit/3c2fd04d441d46ec9d914d9cbb621a3bac96c3a5

**Comment by cpplearner** [comment]
In addition to `path`'s comparison operators (both `operator==` and `operator<=>`), the following lines also cause clang-cl to attempt implicit conversion from `const path&` to `wstring_view`:

https://github.com/microsoft/STL/blob/3c2fd04d441d46ec9d914d9cbb621a3bac96c3a5/stl/inc/filesystem#L971
https://github.com/microsoft/STL/blob/3c2fd04d441d46ec9d914d9cbb621a3bac96c3a5/stl/inc/filesystem#L1739-L1740

There are similar uses in templates, but uses in uninstantiated templates are probably fine.

**Comment by StephanTLavavej** [comment]
@CaseyCarter agrees that this is definitely a bug, and that we need to ensure that `path::iterator` is defined before its semantics affect the behavior of the program (by defining `path::iterator` earlier, or the dependent stuff later).
