### ISSUE TITLE
`<xstddef>`: `first_argument_type` et al are not removed starting in C++20

### ISSUE THREAD

**Issue by AlexGuteniev** [microsoft/STL#2375]
`first_argument_type` et al should be removed starting in C++20.
Yes there's C++17 deprecation warning, but C++20 says these are removed not deprecated.

**Comment by CaseyCarter** [comment]
These were removed by WG21-P0619. It looks like we may have missed some changes, we should audit the entire proposal.

**Comment by cpplearner** [comment]
The `first_argument_type` of `binary_function` is not removed because `binary_function` does not exist in C++20. The rest are removed by means of `_FIRST_ARGUMENT_TYPE_NAME`.

https://github.com/microsoft/STL/blob/3c2fd04d441d46ec9d914d9cbb621a3bac96c3a5/stl/inc/yvals_core.h#L1127-L1137

**Comment by AlexGuteniev** [comment]
@cpplearner , that's correct. I didn't expect this method of removal by renaming instead of completely deleting.
