### ISSUE TITLE
LWG-3563 `keys_view` example is broken

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#2389]
LWG-3563 `keys_view` example is broken

https://github.com/microsoft/STL/blob/5e3574b97985db31112a1c60e4eb52e821d25a83/stl/inc/ranges#L4711-L4714

**Comment by CaseyCarter** [comment]
The product update is trivial, and I don't _think_ the test changes will be too bad, so tagging this good-first-issue.
