### ISSUE TITLE
<type_traits>: Improve _Invoke_traits throughput

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#239]
https://github.com/microsoft/STL/blob/19067f675253943eedc9d5894bb960f7c74d8471/stl/inc/type_traits#L1685-L1696

The compiler front-end team has advised us that repeating `_STD invoke(_STD declval<_Types>()...)` here is unusually expensive. Preserving the distinction between `_Callable, _Args...` and replacing this with the equivalent `_Invoker::_Call()` expression should significantly improve throughput (~25% faster).

**Comment by lozinska** [comment]
Hi! Can I work on this issue?

**Comment by StephanTLavavej** [comment]
Sure! When I initially looked at this issue, I thought that the `_Types...` parameter needed to be refactored into `_Callable, _Args...`. Looking at it again, that refactoring might not be necessary; you should be able to pass the `_Types` parameter pack to `_Invoker` directly. (For example, if `Things` is a parameter pack containing two types, you can say `pair<Things...>` and it’ll compile just fine; the pack expansion works with `pair<First, Second>`.)

Please let us know if you need further information; `invoke` is one of the more complicated bits of template metaprogramming in the STL, and currently we generate `_Invoker` with a macro so it’s a bit hard to read (which we’ll be able to avoid in the future).

**Comment by lozinska** [comment]
Ok, thank you!

**Comment by lozinska** [comment]
Hi @StephanTLavavej I have been looking through this issue and I have question. So as I understand I will need to replace `invoke(_STD declval<_Types>()...)` with `invoke(pair<_Types>()...)`. Is it correct?
By the way can i use https://godbolt.org/ in order to check if I made right corrections?

**Comment by lozinska** [comment]
@StephanTLavavej sorry I probably ask very general question. Let me investigate more on this issue and then ask questions

**Comment by StephanTLavavej** [comment]
> So as I understand I will need to replace `invoke(_STD declval<_Types>()...)` with `invoke(pair<_Types>()...)`. Is it correct?

No - the suggested replacement is `_Invoker<_Types...>::_Call(_STD declval<_Types>()...)`. See:

https://github.com/microsoft/STL/blob/19067f675253943eedc9d5894bb960f7c74d8471/stl/inc/type_traits#L1594-L1603

(which is difficult to read due to macro machinery; we're waiting for the compiler to implement a Core Language issue resolution, after which we'll be able to remove that macro and possibly simplify the code further).

What's happening here is that the function template `invoke()` is being implemented by calling a static member function `_Call` of a struct template `_Invoker`. This is what performs the template metaprogramming of inspecting the callable type and argument types, determining what kind of invocation expression to use (e.g. lambdas need to be called with parentheses, but pointers to member functions need to be called with syntax like `(obj.*pmf)(args)`). 

Regarding `pair`, I was trying to clarify how variadic template pack expansion works, but I probably just made things more confusing; my apologies. `pair` is not actually involved in this issue.

> By the way can i use https://godbolt.org/ in order to check if I made right corrections?

Hmm, I think that would be difficult, since this isn't a standalone snippet of code - it's the entire stack of machinery powering `invoke()` and its related type traits. It would probably be easier to write a small command-line test case for `is_invocable`, `is_nothrow_invocable`, `is_invocable_r`, and `is_nothrow_invokable_r`, verifying that it compiles with the current `<functional>` header, and then seeing if it compiles with your updated `<functional>` header. In this case, as the change is for improving compiler throughput (build speed), the goal is to simply keep the code compiling correctly (measuring the performance difference is difficult and we'll ask the compiler team to do that).

We have an extensive test suite for this `<functional>` machinery but we're still working on writing the test harness so we can put it on GitHub; this will probably not be available until January.
