### ISSUE TITLE
LWG-3570 `basic_osyncstream::emit` should be an unformatted output function

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#2395]
LWG-3570 `basic_osyncstream::emit` should be an unformatted output function

This was voted into the Working Paper in October 2021, see #2236.

**Comment by AlexGuteniev** [comment]
Isn't this vNext?

**Comment by StephanTLavavej** [comment]
I think we just need to construct a sentry object - I don't see any ABI concerns here. Perhaps I'm missing something (I always find it hard to understand iostreams).

**Comment by AlexGuteniev** [comment]
I'm not sure if new code which constructs a sentry object can link with old code that doesn't
