### ISSUE TITLE
LWG-3571 `flush_emit` should set `badbit` if the `emit` call fails

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#2396]
LWG-3571 `flush_emit` should set `badbit` if the `emit` call fails

This was voted into the Working Paper in October 2021, see #2236.

**Comment by MattStephanson** [comment]
I was going to post this on the PR, but it's more about the issue itself, so I'll put it here.

The LWG resolution makes this an "unformatted output function", so it seems to need a `sentry` object and everything that goes with it from [[ostream.unformatted]/1](http://eel.is/c++draft/ostream.unformatted#1).

On the other hand, LWG-3570 makes `basic_osyncstream::emit` itself an unformatted output function, so constructing a `sentry` both here and in the `emit` call seems redundant. Both issues use the typical "After constructing a `sentry` object..." wording, which I read as requiring two separate `sentry` objects, unless there's an argument that the as-if rule applies.

**Comment by MattStephanson** [comment]
FYI, @fsb4000.

**Comment by fsb4000** [comment]
Thank you @MattStephanson ! I completely missed this sentence when doing the implementation.

But I think both sentry objects are needed because one sentry object is created in `basic_osyncstream::emit` but `flush_emit` calls `_Basic_syncbuf_impl::emit`

**Comment by MattStephanson** [comment]
> But I think both sentry objects are needed because one sentry object is created in `basic_osyncstream::emit` but `flush_emit` calls `_Basic_syncbuf_impl::emit`

@fsb4000 I think you're right, I was confusing `basic_osyncstream::emit` (which is an unformatted output function) with `basic_syncbuf::emit` (which isn't). `flush_emit` calls the latter, so there's no issue of duplicate `sentry` objects.
