### ISSUE TITLE
<unordered_map> in 32Bit Application causes Illegal Instruction on Windows 2008 R2 64Bit

### ISSUE THREAD

**Issue by Markus87** [microsoft/STL#240]
**Describe the bug**
"std::unordered_map" crashes on the 9th insert with the "[]" operator. We did not have this issue with Visual Studio 2019.2.x, after upgrading to Visual Studio 2019.3.x the issue appeared sometimes with Windows Server 2018 R2. Once the problem occures it can be reproduced always.
We worked around the issue by using a std::map instead for the 32Bit build.
I know the issue can not be reproduced 100% of the time but I hope it is still useful to you.

**Command-line test case**
Visual Studio 16.3.7

```
D:\Tmp\Issue>type repro.cpp
#include <string>
#include <unordered_map>

int main()
{
        std::unordered_map< std::string, std::string* > map;

        for( size_t i = 0; i < 10000; ++i )
                map[ "PropertyType::SomePropertyTypeName" + std::to_string( i ) ] = nullptr;  //- Illegal Instruction on i == 8

        return 0;
}

D:\Tmp\Issue>cl /EHsc /W4 /WX /DEBUG /Zi .\repro.cpp
Microsoft (R) C/C++-Optimierungscompiler Version 19.23.28106.4 für x86
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

repro.cpp
Microsoft (R) Incremental Linker Version 14.23.28106.4
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:repro.exe
repro.obj

D:\Tmp\Issue>cl /EHsc /W4 /WX /DEBUG /Zi .\repro.cpp
Microsoft (R) C/C++-Optimierungscompiler Version 19.23.28106.4 für x86
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

repro.cpp
Microsoft (R) Incremental Linker Version 14.23.28106.4
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:repro.exe
/debug
repro.obj
```

**Expected behavior**
I expect the program to finish without a crash.

**Additional context**
System on which it crashes:
![grafik](https://user-images.githubusercontent.com/6339979/67944377-a3250500-fbdc-11e9-9642-b990becffe3f.png)
On this system it crashes always, but another system just like it does not crash.
But we have seen this issue only with Windows 2008 R2.

Stacktrace of crash:
![grafik](https://user-images.githubusercontent.com/6339979/67941893-df556700-fbd6-11e9-96cf-b4cf640aac31.png)

**Comment by StephanTLavavej** [comment]
Unrelated note: Passing `/DEBUG` to the compiler defines a macro named `EBUG`, which isn't what you were expecting. (`/Zi` emits debug info, `/MTd` or `/MDd` requests the debug runtimes, and `/DNDEBUG` defines the `NDEBUG` macro that silences `assert()`.)

**Comment by StephanTLavavej** [comment]
Thanks for the report. This is a compiler bug that's currently being investigated; see DevCom-787296 for more information. I've informed the compiler devs investigating that bug about your report.

Because we're using this GitHub repo to track only bugs within the STL's source code, I'm going to close this issue as a duplicate.

**Comment by Markus87** [comment]
Thank you for the quick response.

**Comment by StephanTLavavej** [comment]
By the way, it appears that your hardware-software combination (specifically, Skylake and Server 2008 R2) is unsupported by Microsoft. The compiler team is still investigating, but I thought you should be aware of this (and consider upgrading your OS).

**Comment by Markus87** [comment]
Thanks for the heads-up. 
The affected system is not under my control, but I will let them know.
The nearing end of life of Windows 2008 (R2) in January is one more reason to upgrade.
But our customers have a way of delaying it as long as possible.

By the way, we tried to workaround the broken ```unordered_map``` by using ```map``` instead but then had crashes in other places.

I just had a look at the [/arch](https://docs.microsoft.com/en-us/cpp/build/reference/arch-x86?view=vs-2019) compiler flag.
Setting it to below AVX512 should prevent the problem too? I could try that on Monday.

**Comment by StephanTLavavej** [comment]
It is extremely unlikely that `/arch` will help. First, it defaults to a low value (SSE2 for both x86 and x64). Second, it controls whether the compiler is willing to unconditionally emit instructions (e.g. during autovectorization). For example, `/arch:AVX2` gives the compiler permission to unconditionally use AVX2; `/arch:SSE2` forbids the compiler from unconditionally using AVX2, but it can still emit *runtime-guarded* instructions - which is fine as long as the runtime guards work correctly.

The issue you've encountered is where an assembly file, separately compiled by Microsoft (and therefore unaffected by `/arch` in any way) is conditionally using AVX-512, yet the runtime guard appears to be misbehaving.

The compiler team is developing an attempted fix for this (it involves detecting whether the OS performs AVX-512 state saving), although I don't believe they've been able to confirm it on an affected machine, and we don't have an ETA for when/how it will ship.

**Comment by Markus87** [comment]
Okay, I did not expect it to have such a low default value.
But now our findings make more sense.

Our customer provided us with a machine where we could reproduce the issue. 
This time the machine was a Windows Server 2012. Like the machine before it is a virtualized machine. He assigned the same CPU as before to this machine and this was enough to break the example.
We experimented with the ```/arch``` flag and made an executable for every setting.
Every executable built above ```/arch:SSE``` had the crash. But ```/arch:SSE``` seems to work just fine. We rebuilt the 32Bit version of our program the same and it seems the problem is solved as well.

I have limited knowledge of the infrastructure of our customer, but if you need to know more I can check back with him.

**Comment by StephanTLavavej** [comment]
That's very interesting - from looking at `cpu_disp.c`, I can't see how `/arch` could affect it. But I'm glad your customer has a workaround.
