### ISSUE TITLE
LWG-3593 Several iterators' `base() const &` and `lazy_split_view::outer-iterator::value_type::end()` missing `noexcept`

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#2403]
LWG-3593 Several iterators' `base() const &` and `lazy_split_view::`*`outer-iterator`*`::value_type::end()` missing `noexcept`

We need to remove `/* strengthened */` comments when the Standard starts mandating `noexcept`.

This was voted into the Working Paper in October 2021, see #2236.

**Comment by sam20908** [comment]
I think this is a good first issue.
