### ISSUE TITLE
Implementing is_reference_v restraints?

### ISSUE THREAD

**Issue by cristeigabriel** [microsoft/STL#2408]
Hello!

I was thinking, when trying to do the following (I know it isn't possible for clear specified reason, I was just tinkering):

```
std::allocator<char&> my_allocator;
```
we get good error input, but still not particularly the easiest to read. A way to make the output error better is with requires(!is_reference_v<_Ty>) after the template.

This will be particularly helpful when this is done with, say, `std::vector`, as the errors spewed are way more complicated than with allocator, obviously.

Here is what I mean, on `msvc v19.latest`:
https://godbolt.org/z/n5dE76na9

A situation where this could happen is when someone is trying to create a vector of a variable's type and that variable is a ref. It'd make reading the error to understand what's going on more easy. Perhaps this could even be turned into a static assert and get a message alongside.

You can comment the require constraint to see the difference.

From what I understood talking with others, this could classify as a "Quality of Implementation" enhancement. I tried to implement it but I can't think of a common denominator to reduce the amount of code and I do not want to litter and use up CI time, so I thought that a way to contribute without making things worse is to perhaps bring attention to this.

Kind regards.

**Comment by AlexGuteniev** [comment]
I think the current errors for concepts are not too clear either.  `static_assert` may give a better results:
```
#include <memory>
#include <type_traits>
#include <vector>

template<class _Ty>
struct my_validate
{
    static_assert(!std::is_reference_v<_Ty>,"no refs pls");
    using type = _Ty;
};

template<class _Ty>
using my_validate_t = my_validate<_Ty>::type;


template<class _Ty>
struct my_vector:
    public std::vector<my_validate_t<_Ty>, std::allocator<_Ty>> {
};

int main() {
    my_vector<char&> vec;
}
```

In the STL this is used when you pass garbage to `std::function`:
https://github.com/microsoft/STL/blob/2f9f567ffe1087353ecacc5a03f81c395a1922e1/stl/inc/functional#L1008-L1011

I added the same to my `move_only_function` PR.

But probably this could be used more often.

**Comment by StephanTLavavej** [comment]
Yep, we prefer `static_assert` for such enforcement of Standard requirements, and we already have one for `allocator<const T>` which is forbidden:

https://github.com/microsoft/STL/blob/2f9f567ffe1087353ecacc5a03f81c395a1922e1/stl/inc/xmemory#L780-L784

Additional `static_assert`s to improve horrible diagnostics and provide Standard citations would be welcome, in general. (The compiler throughput cost of checking basic type traits is minimal.)

**Comment by cristeigabriel** [comment]
I'd be willing to do an implementation of the idea but I'd have to figure a common denominator to not spam the source code (in a way that doesn't affect the effectiveness of the constraints) and a way to do this in a way that wouldn't create code smell. A type validator as @AlexGuteniv proposed would be the best way to approach this I believe, but I don't know where it'd reside. Also, I think that requires constraints would be better especially for CLI, since its less output with them, but in editors constraints of both static assert and requires should be highlighted the same, at least they are on my end.

**Comment by cristeigabriel** [comment]
If it's ok, I'll start to review the standard library containers over this weekend for which have requirements which prevent reference generic types and implement said assertions accordingly, and then perhaps we can work out possible details in a following PR.
