### ISSUE TITLE
`<format>`: `volatile integral<T>` compilation error

### ISSUE THREAD

**Issue by jovibor** [microsoft/STL#2427]
```cpp
#include <format>

int main()
{
    volatile int vol = 42;
    auto ret = std::format("{}", vol);
}
```
`error C2668: 'std::_Format_arg_traits<_Context>::_Phony_basic_format_arg_constructor': ambiguous call to overloaded function`

The same code compiles fine with **{fmt}**.
MSVS 17.0.4

Update:
It's rather `volatile integral types` fail to compile, because `volatile` `double` and `float` compile fine.

**Comment by fsb4000** [comment]
probably LWG issue needed.

Look: https://github.com/microsoft/STL/pull/2579#issuecomment-1048189367

It seems we can't fix the issue for now...

**Comment by CaseyCarter** [comment]
> probably LWG issue needed.

I'm currently gathering requirements for such an LWG issue on the WG21 reflectors, trying to determine the design intent.

**Comment by barcharcraz** [comment]
Should this be closed now that #2579 is merged?

**Comment by barcharcraz** [comment]
Allright, closing given #2579

**Comment by CaseyCarter** [comment]
FWIW, the workaround for scalar volatile types is literally one keystroke: use unary `+` to turn your `volatile` lvalue into a non-`volatile` prvalue a la `std::format("{}", +vol);`.
