### ISSUE TITLE
`<string>`: `std::stol` throws `out_of_range` exception on valid values

### ISSUE THREAD

**Issue by gian21391** [microsoft/STL#2444]
As stated in the title, I get an `out_of_range` exception when using `std::stol`. Here is a piece of code that I expected to be working (the expected result is 21492913190):

```
#include <iostream>
#include <string>

int main() {
    std::string value = "010100000001000100111101010000100110";
    auto val = std::stol(value, nullptr, 2);
    std::cout << val << std::endl;

    return 0;
}
```

This works correctly in GCC: https://godbolt.org/z/rbjccs1Wv

The issue appears to be actually in `std::strtol`:

```
#include <iostream>
#include <string>

int main() {
    std::string value = "010100000001000100111101010000100110";
    errno = 0;
    char* p_end;
    auto val = std::strtol(value.c_str(), &p_end, 2);
    const bool range_error = errno == ERANGE;
    std::cout << range_error << std::endl;
    std::cout << val << std::endl;

    return 0;
}
```

The previous piece of code returns:

```
1
2147483647
```

And again, this works on GCC: https://godbolt.org/z/E8GPYrqse

I tested this using `Microsoft (R) C/C++ Optimizing Compiler Version 19.30.30706 for x64`

**Comment by fsb4000** [comment]
I think MSVC works correct.

See, MSVC `long` type is 32 bit, not 64 like on x86-64 Linux.
Max value of 32 bit long is `2 147 483 648`
`21 492 913 190` > `2 147 483 648`
So exception is correct.
gcc does same for 32 bit Linux where `long `is 32 bit, same as in Windows.

https://godbolt.org/z/G1fKGWEcn

**Comment by CaseyCarter** [comment]
As @fsb4000 says, this is not a bug but expected behavior on a system with 32-bit long. Changing `std::stol` to `std::stoll` in the original program returns `21492913190` as expected, but as a `long long`.

**Comment by gian21391** [comment]
I wasn't aware of the LLP64 and LP64 difference. Thanks for the clarification.
