### ISSUE TITLE
`<yvals_core.h>`: Update `_MSVC_STL_UPDATE` to January 2022

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#2454]
Explanation on our wiki: [Macro `_MSVC_STL_UPDATE`](https://github.com/microsoft/STL/wiki/Macro-_MSVC_STL_UPDATE)

Code:
https://github.com/microsoft/STL/blob/303df3dae6f5ed9fe4f1c35257f663af8355584a/stl/inc/yvals_core.h#L584

Previous issue: #2371

This issue is intended for a new contributor (especially one new to GitHub) to get started with the simplest possible change.

Please feel free to submit a pull request if there isn't one already linked here - no need to ask for permission! :smile_cat:

You can (and should) link your pull request to this issue using [GitHub's close/fix/resolve syntax](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

**Comment by ssenthilnathan3** [comment]
https://github.com/microsoft/STL/pull/2455#issue-1092235596
