### ISSUE TITLE
Do std::search algorithms work with multi byte string?

### ISSUE THREAD

**Issue by AlexGuteniev** [microsoft/STL#2456]
I mean Boyer Moore search

**Comment by CaseyCarter** [comment]
I suppose it depends on your definition of "work." If you want to find a subsequence of code units in a larger sequence of code units, sure. If you expect the algorithms to respect boundaries between encoding sequences for distinct code points, you're going to have a bad time - not every encoding has the UTF-8 feature that makes lead and continuation byte values non-overlapping.

**Comment by AlexGuteniev** [comment]
Thanks, that's a complete answer
