### ISSUE TITLE
Changelog is unwieldy; split it?

### ISSUE THREAD

**Issue by CaseyCarter** [microsoft/STL#2459]
Editing [our Changelog](https://github.com/microsoft/STL/wiki/Changelog) has become fairly painful; it takes anywhere from 4-10 seconds sometimes for keystrokes to take effect. Should we archive each major Visual Studio release on its own page, keeping only the current release series on the Changelog itself?

**Comment by AlexGuteniev** [comment]
Yes, but split another major release from the current only when it becomes production, to avoid having to look into multiple change logs often.

**Comment by CaseyCarter** [comment]
> Yes, but split another major release from the current only when it becomes production, to avoid having to look into multiple change logs often.

Verifying my understanding: you're suggesting that when the first release of VS `x+1` ships, we should archive all of the VS `x` Changelog entries? That would ensure that the "active window" of merged-but-not-yet-shipped changes is always on the Changelog "front page".

**Comment by AlexGuteniev** [comment]
Yes. So for 2019 it is already time to archive since November 8

**Comment by StephanTLavavej** [comment]
I am totally in favor of splitting. I believe we should have the current Changelog end with a section for VS 2019 that links to the VS 2019 Changelog, and that section should contain extra anchors of the form `<a name="vs-2019-1610"></a>` so people who were directly linking to those sections will be able to get to the new page easily.

**Comment by StephanTLavavej** [comment]
Done. In the future, we may need to split VS 2022's Changelog after several releases.
