### ISSUE TITLE
<exception>: Invalid destruction of non-copyable throwables during exception_ptr rethrow

### ISSUE THREAD

**Issue by hofst** [microsoft/STL#2466]
**Describe the bug**
If you rethrow an object with deleted copy-constructor via an `exception_ptr`, it will corrupt the memory and crash.

**Command-line test case**
```
C:\Temp>type repro.cpp
#include <exception>
#include <string>
using namespace std;

class C {
public:
  C() = default;
  C(const C&) = delete;
  C& operator=(const C&) = delete;
  C(C&&) = default;
  C& operator=(C&&) = default;

private:
  string m;
};

int main() {
  exception_ptr eptr;
  try {
    throw C();
  } catch (const C&) {
    eptr = std::current_exception();
  }
  try {
    rethrow_exception(eptr);
  } catch (const C&) {
  }
}

C:\Temp>cl /EHsc /W4 /WX .\repro.cpp
Microsoft (R) C/C++ Optimizing Compiler Version 19.23.28019.1 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

repro.cpp
Microsoft (R) Incremental Linker Version 14.23.28019.1
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:repro.exe
repro.obj

C:\Temp>.\repro.exe
test failure
```

**Expected behavior**
Does not crash.

**STL version**
MSVC build tools 14.28, 14.29, 14.30, 14.31 (reproes in all of them).

**Comment by fsb4000** [comment]
I think this line of code is to blame: https://github.com/microsoft/STL/blob/0dc93fcf0e7f18d47fff4daccce729cc5ea9570b/stl/src/excptptr.cpp#L158
we cannot distinguish between trivially copyable and non-copyable classes :(
then both ExceptionObjects call a destructor for the same string and we got the error.
If we build with ASAN then we can reduce repro to this:
```c++
#include <exception>
#include <string>
using namespace std;

class C {
public:
    C() = default;
    C(const C&) = delete;
    C& operator=(const C&) = delete;
    C(C&&) = default;
    C& operator=(C&&) = default;

private:
    string m;
};

int main() {
    exception_ptr eptr;
    try {
        throw C();
    }
    catch (const C&) {
        eptr = std::current_exception();
    }
}
``` 
Unfortunately, at first glance, I don't know how to solve this issue:(

**Comment by fsb4000** [comment]
I found this: https://en.cppreference.com/w/cpp/language/throw

>Even if copy initialization selects the move constructor, copy initialization from lvalue must be well-formed, and the destructor must be accessible 

I will look in the standard also...

**Comment by CaseyCarter** [comment]
The bug here is - per [except.throw]/5 - the compiler failing to diagnose that `C` is not copyable at `throw C();`. Please report this as a compiler bug at https://developercommunity.visualstudio.com/report?space=62&entry=problem.

**Comment by CaseyCarter** [comment]
> Are you positive that this is a compiler bug and the deleted/non-existent copy constructor is called? How did you verify that?

Yes, it's clear: the standard says "the constructor selected for a copy-initialization considering the thrown object as an lvalue shall be non-deleted and accessible." This program violates that diagnosable constraint, so the compilers should diagnose it.

> I have some doubts because I did more tests with other compiler / STL combinations: The exact same problem **does reproduce** with clang13+msvcSTL but the problem **does not reproduce** with clang13+libcxx.

"The problem" is the lack of diagnostic, which _does_ reproduce with Clang + libc++. And GCC + libstdc++, for that matter.

**Comment by fsb4000** [comment]
>What do you mean with lack of diagnostics? 

I think a conforming C++ compiler must give a compilation error for the initial code.

**Comment by hofst** [comment]
@fsb4000 
> Even if copy initialization selects the move constructor, copy initialization from lvalue must be well-formed
Interesting! This citation is from "cppreference.com", right? Do you happen to know the original citation in the c++ standard? I don't seem to find it.

**Comment by fsb4000** [comment]
> Do you happen to know the original citation in the c++ standard?

I think that line from cppreference is paraphrased the line from the standard: 

>the constructor selected for a copy-initialization considering the thrown object as an lvalue shall be non-deleted and accessible

![Cubby](https://en.cppreference.com/w/User:Cubbi) added the line after cwg-1863 was accepted.

https://en.cppreference.com/mwiki/index.php?title=cpp%2Flanguage%2Fthrow&diff=81680&oldid=74819

https://wg21.cmeerw.net/cwg/issue1863

**Comment by fsb4000** [comment]
I created issues:

DevCom-1638273

LLVM-53224

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=104046
