### ISSUE TITLE
`<memory>`: `std::construct_at(s, " ")` did not evaluate to a constant

### ISSUE THREAD

**Issue by hewillk** [microsoft/STL#2467]
```cpp
#include<string>
#include<memory>

constexpr bool b = [] {
  std::string s[1];
  std::construct_at(s, " ");
  return true;
}();
```
https://godbolt.org/z/jdx7oGnMn

MSVC-trunk rejects it with:

```
<source>(4): error C2131: expression did not evaluate to a constant
<source>(6): note: a non-constant (sub-)expression was encountered
```

I don't know if this is a language bug or a library bug, please correct me if I'm missing something.

**Comment by miscco** [comment]
This is a clear compiler bug. You can play with other forms aka assignment etc that work. So it seems to be related to `std::construct_at`.

Strangely using a simple literal type works.

**Comment by CaseyCarter** [comment]
This won't work in debug mode since we allocate memory in the default constructor of all containers and that memory isn't deallocated if you reuse the storage for the container without destruction.

**Comment by CaseyCarter** [comment]
Correction: at compiletime the default constructor always allocates memory. This is not a compiler bug. It may be a library bug?

**Comment by miscco** [comment]
I doubt that this is the issue here.

For once the error is quite different.

Secondly it also fails when destroying the allocation with destroy_at

**Comment by hewillk** [comment]
This OP is simplified from the following, if it helps.

```cpp
#include<string>
#include<vector>

constexpr bool b = [] {
  std::vector<std::string> v;
  v.push_back(" "); // ok
  v.emplace_back(" "); // not ok
  return true;
}();
```
https://godbolt.org/z/PMdTo5sK1

**Comment by CaseyCarter** [comment]
> I doubt that this is the issue here.

I doubt it's the _only_ issue here.
 
> For once the error is quite different.
> 
> Secondly it also fails when destroying the allocation with destroy_at

Clang compiles successfully with the `destroy_at`, MSVC does not. An altered program that includes such a `destroy_at` call _would_ indicate a compiler bug.

**Comment by CaseyCarter** [comment]
Less reduced, but more library-free:
```c++
#include <memory>
#include <string>

constexpr const char *space = " ";

static_assert([] {
  std::string *v = std::allocator<std::string>{}.allocate(4);

  std::construct_at(v + 0, std::string{}); // OK
  std::construct_at(v + 1, space);         // OK
  std::construct_at(v + 2, " ");           // Error
  std::destroy_at(v + 2);
  std::destroy_at(v + 1);
  std::destroy_at(v + 0);

  std::allocator<std::string>{}.deallocate(v, 4);
  return true;
}());
```

**Comment by miscco** [comment]
I also checked with a local string_view of a whitespace, which also works. Seems that @cdacamar will have a lot of fun with all the string issues

**Comment by miscco** [comment]
Luckily it has nothing to do with `std::string` https://godbolt.org/z/TG9PqsvoT

**Comment by miscco** [comment]
Removing all the library code I believe this is the minimal example
https://godbolt.org/z/zj1dGzsK3

**Comment by miscco** [comment]
Filed https://developercommunity.visualstudio.com/t/cl-incorrectly-rejects-call-to-stdrangesconstruct/1634430

**Comment by CaseyCarter** [comment]
Thanks for filing the compiler bug, @miscco! Since this is not an STL bug, and anyone interested can follow the compiler bug on DevCom, I'm closing this.
