### ISSUE TITLE
<memory>: Consistently use `int = 0` SFINAE

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#248]
Over the years, we settled on a consistent pattern for SFINAE: default template arguments of the form `enable_if_t<CONDITION, int> = 0`. This works in a wide variety of situations, including when we have an overload set where SFINAE makes exactly one overload viable. There are a few remaining occurrences of SFINAE that don't follow this pattern.

In `<memory>`, these occurrences are `_Enable_ctor_reset` and `_Enable_conversion`:

https://github.com/microsoft/STL/blob/28ec9a32952e0d7443936f8d5ae5d675ba6cf65c/stl/inc/memory#L1933-L1938

https://github.com/microsoft/STL/blob/28ec9a32952e0d7443936f8d5ae5d675ba6cf65c/stl/inc/memory#L1975-L1978

This change is currently blocked by a compiler bug. We need to provide a reduced test case to the compiler front-end team.

(Split from #187.)

**Comment by MikeGitb** [comment]
Just curious: What is the advantage of this form over `class = std::enable_if_t<Cond>`?

**Comment by StephanTLavavej** [comment]
Consider the common scenario of having two overloads, one of which is enabled when `is_cat_v<T>` and the other when `!is_cat_v<T>`. If you try to do this with `class = enable_if_t<Cond>`, it won’t compile. That’s because the compiler sees two templates, both taking an unnamed type parameter, with different default arguments; that looks like conflicting definitions.

If instead you use `enable_if_t<Cond, int> = 0`, then the compiler has to perform substitution and SFINAE before discovering what the non-type template parameter is (humans can see that it’s always `int` or nonexistent). This means that the compiler will only ever see one overload with an `int` template parameter and the other will vanish.

**Comment by MikeGitb** [comment]
Thanks for the explanation.

**Comment by StephanTLavavej** [comment]
I believe that this is now unblocked; it should be possible to resolve this with the same technique that @BillyONeal used in #244.
