### ISSUE TITLE
What is `_M_HYBRID`? How is it different from `_M_ARM64EC`?

### ISSUE THREAD

**Issue by AlexGuteniev** [microsoft/STL#2483]

**Comment by cbezault** [comment]
`_M_HYBRID` is the x86 emulation on ARM/ARM64 technology. `_M_ARM64EC` is the new x64 on ARM64 emulation technology.

**Comment by StephanTLavavej** [comment]
Adding to what Curtis said:

`_M_HYBRID` indicates CHPE (Compiled Hybrid Portable Executable, I think?), if you ever see that acronym mentioned. CHPE shares some similarities with ARM64EC but there are important differences. If you have specific questions that affect the STL, we can find a compiler back-end dev to comment (as we've reached out to them in the past when we've encountered issues).

**Comment by AlexGuteniev** [comment]
Thanks, no specific questions for now.
