### ISSUE TITLE
`<xtree>`: associative containers require `Compare::operator() const` even in C++14

### ISSUE THREAD

**Issue by MattStephanson** [microsoft/STL#2487]
**Describe the bug**
LWG-2542 points out that, read strictly, N4140 (i.e., C++14) [associative.reqmts]/8 only requires that "`c` denotes a [not necessarily `const`] value of type `X::key_compare`". The resolution adds an Annex C entry that explicitly calls comparison objects with non-`const` function call operators "[v]alid 2014 code". But there are a few places that are taking and invoking `const` references to the comparison object:
https://github.com/microsoft/STL/blob/86e22c3cf3238fa9aca10e47665f4c2b88b27206/stl/inc/xtree#L1485
https://github.com/microsoft/STL/blob/86e22c3cf3238fa9aca10e47665f4c2b88b27206/stl/inc/xtree#L1686

**Command-line test case**
```
c:\Temp>type bug.cpp
#include <set>

struct compare
{
  bool operator()(int a, int b)
  {
    return a < b;
  }
};

int main() {
  const std::set<int, compare> s;
  (void) s.find(0);
}

c:\Temp>cl /EHsc /W4 /WX /std:c++14 bug.cpp
Microsoft (R) C/C++ Optimizing Compiler Version 19.31.30818 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

bug.cpp
C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.31.30818\include\xtree(1601): error C3848: expression having type 'const compare' would lose some const-volatile qualifiers in order to call 'bool compare::operator ()(int,int)'
[etc.]
```

**Expected behavior**
Should compile without error in C++14 mode.

**Comment by CaseyCarter** [comment]
We discussed this when implementing LWG-2542, and there was no interest at the time in adding complexity to `xtree` to arrange for `const` member functions to use a copy of the stored comparator in C++14 mode. Casting away `const` or annotating the comparator as `mutable` and using the stored comparator in `const` members would at the very least violate [res.on.data.races], which is a non-starter. In other words, we treat this issue as a defect and its resolution is a DR implemented uniformly in all language modes.

Note that there's no implementation divergence here, at least among the "big 3": https://godbolt.org/z/WK6j5faxE.

**Comment by MattStephanson** [comment]
Thanks for clarifying! My BU is upgrading to VS2019 this weekend, and some people (running untested later updates) are having issues with this, so I thought I'd at least report it. I feel much more strongly that the `op()` that's triggering this should be made `const`.
