### ISSUE TITLE
P0553R4 <bit> Rotating And Counting Functions

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#25]
[P0553R4](https://wg21.link/P0553R4) `<bit>` Rotating And Counting Functions

This may need compiler support.

**Comment by crackedmind** [comment]
How i can see, MSVC supports __builtin_clz/__builtin_popcount and some other helpers since 19.23. Can we start start to implement this? :)

**Comment by sylveon** [comment]
There's _BitScanReverse for clz. Not sure if constexpr though.

**Comment by crackedmind** [comment]
> There's _BitScanReverse for clz. Not sure if constexpr though.

if you will grep c1xx.dll from vc >= 19.23 you can find __builtin_clz and other functions.

**Comment by StephanTLavavej** [comment]
@barcharcraz is actively working on this. Charlie, would it be useful to submit a draft PR so people can see what you’ve been working on, as I did for Casey’s `<coroutine>` that I revised?

**Comment by crackedmind** [comment]
> @barcharcraz is actively working on this. Charlie, would it be useful to submit a draft PR so people can see what you’ve been working on, as I did for Casey’s `<coroutine>` that I revised?

How about  lables 'i started' in issues or maybe WIP PRs? I think it can be useful. Specialy, if you start it iternal.
