### ISSUE TITLE
STL: Consider consistently rephrasing Standard mode diagnostics

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#250]
When a header for a newer C++ Standard is compiled with an older Standard mode, it emits a diagnostic. Our phrasing varies; some talk about the contents of the header:

https://github.com/microsoft/STL/blob/28ec9a32952e0d7443936f8d5ae5d675ba6cf65c/stl/inc/charconv#L3101

Others talk about the main class or class template defined by that header:

https://github.com/microsoft/STL/blob/28ec9a32952e0d7443936f8d5ae5d675ba6cf65c/stl/inc/any#L445
https://github.com/microsoft/STL/blob/28ec9a32952e0d7443936f8d5ae5d675ba6cf65c/stl/inc/variant#L1754

Some don't bother to say "class" (and ignore the distinction between the `basic_string_view` class template and the `string_view` typedef):

https://github.com/microsoft/STL/blob/28ec9a32952e0d7443936f8d5ae5d675ba6cf65c/stl/inc/string_view#L15

And some have custom phrasing:

https://github.com/microsoft/STL/blob/28ec9a32952e0d7443936f8d5ae5d675ba6cf65c/stl/inc/execution#L5141

Should we be consistent about this phrasing?

**Comment by StephanTLavavej** [comment]
My preference: "The contents of `<meow>` are only available with C++MEOW or later." This is currently used by `<charconv>`, `<compare>`, `<concepts>`, `<filesystem>`, `<memory_resource>`, and `<ranges>`.

**Comment by CaseyCarter** [comment]
Didn't @BillyONeal suggest that we should invert the conditionals that guard these "downlevel" diagnostics so the `#pragma` is nearer the top of the header file also? (Admittedly these are separable issues, but the level of "creep" from combining them seems small to me.)

**Comment by SuperWig** [comment]
There's code inconsistencies too.

`C++20` vs `_HAS_CXX20`
https://github.com/microsoft/STL/blob/3b0a1c9cfa607840519e49e8589815c25078c3df/stl/inc/compare#L478
Double sided arrows
https://github.com/microsoft/STL/blob/3b0a1c9cfa607840519e49e8589815c25078c3df/stl/inc/variant#L1753
