### ISSUE TITLE
std::vector visualization in VS2022 is different than VS2019 

### ISSUE THREAD

**Issue by amitprakash07** [microsoft/STL#2505]
In VS2022, the debugger watch is showing std::vector differently than the VS2019. It looks like the natvis visaulizers are different for VS2019, and VS2022. Below is the screenshot for reference. Is it expected?

![Screenshot 2022-01-26 125031](https://user-images.githubusercontent.com/8896156/151218658-a9bf9d70-9cc5-4821-85f1-71bad9ab3cef.png)

**Comment by CaseyCarter** [comment]
Hmmm - looks like we changed something in `vector` and broke the visualizer. That's not good.

**Comment by CaseyCarter** [comment]
I can't naively reproduce this with VS 2022 17.1p3. What version are you using? Can you attach a minimal project that reproduces the issue?

**Comment by amitprakash07** [comment]
Sure! Here is the attached project, and VS version details.

![Screenshot 2022-01-26 134149](https://user-images.githubusercontent.com/8896156/151226300-2b71c1fa-b4a6-4bb0-b0eb-04364c100af0.png)
[TestCopy.zip](https://github.com/microsoft/STL/files/7944342/TestCopy.zip)

**Comment by fsb4000** [comment]
I have a professional version and the project works fine:
![изображение](https://user-images.githubusercontent.com/4289847/151230161-5ce2d5c5-c06c-479f-9841-56553e0d06ed.png)
Strange...
Maybe it's somehow Enterprise specific...

**Comment by gix** [comment]
If the analyzer is somehow broken, there should be diagnostics. Enable them under `Options -> Debugging -> Output Window -> General Output Settings -> Natvis diagnostic messages -> Verbose` then look in the Output window while debugging.

**Comment by amitprakash07** [comment]
With the latest update, I am not noticing this issue anymore.
