### ISSUE TITLE
Why does std::filesystem::path try to convert from ACP to Unicode when using /utf-8?

### ISSUE THREAD

**Issue by SnowMB** [microsoft/STL#2511]
I'm trying to make my way around the different charsets as I try to support unicode filepaths in my application. I stubled uppon a problem when using `/utf-8` option and utf-8 encoded source files. 

In this case string narrow string literals and `u8` prefixed literals should produce the same bytes and I could verify that this is indeed so. 

But when trying to build a `std::filesystem::path` using the non-prefixed literal I get a path that looks like the bytes were interpreted as my current code page (Latin-I) and converted to utf-8 from there, thus resulting in an invalid (wrong) path. 

Using the u8 prefix however works as expected.

Am I doing something illegal here?

```c++
#include <filesystem>
#include <iostream>

int main() {
  auto path     = std::filesystem::path(".") / "this" / "is" / "a" / "path" / "abcdefgäöüµ°😍";
  auto pathUtf8 = std::filesystem::path(".") / "this" / "is" / "a" / "path" / u8"abcdefgäöüµ°😍";
    
  if (path != pathUtf8)
  {
     std::cout << "test failure\n";
  }
  else 
  {
    std::cout << "test success\n";
  }
}
```

**Comment by StephanTLavavej** [comment]
We talked about this at the weekly maintainer meeting - the current behavior was intended, but this is an interesting question - should `<filesystem>`'s implementation be changed to do something like what `<format>` does (where it recognizes `/utf-8` via a new macro that MSVC defines).

Any behavior changes here would affect the runtime behavior of existing code, hence we'll need to think very carefully before doing anything.

**Comment by SnowMB** [comment]
This raises also the question what should happen if the execution-charset is set to `utf-8` and one uses `path.string()`. I would expect this to also be an utf-8 encoded `std::string`.

For now i use  `path.8string()` and copy the bytes into a `std::string`. But I would like to avoid the copy.

**Comment by fsb4000** [comment]
>For now i use path.u8string() and copy the bytes into a std::string. But I would like to avoid the copy.

```
std::setlocale(LC_ALL, ".UTF-8");
```
resolved the issue for me.

Could you use it?

https://gcc.godbolt.org/z/hhKcfbaKP

**Comment by StephanTLavavej** [comment]
We talked about this again at the weekly maintainer meeting and concluded that the current behavior is correct according to the Standard and that @fsb4000's recommendation is the way to go. Avoiding the problem entirely by using wide strings is also possible, or converting narrow strings to wide strings.

**Comment by Trafo** [comment]
I actually being disappointed by this decision. I am not expecting the old code to break, but trying to go into the modern time and enable with somehow a flag, which is just using a utf8 code table instead what is done now, should be the interest of the C++ community. Otherwise, I have to wait a decade till u8string is well supported by the standard. (What a mess that they introduced this half-baked)
