### ISSUE TITLE
STL Contributors Survey

### ISSUE THREAD

**Issue by MahmoudGSaleh** [microsoft/STL#2513]
Hi all,
Thanks a lot for your contributing to the STL repo! We want to continue ensuring the open source project experience is up to your expectations. We’ve created a survey to better understand your individual experience of participating and contributing to this project.

We would appreciate your feedback so we can work to address shortcomings and missed opportunities. 

https://www.surveymonkey.com/r/8QTQTGJ?Source=stl

**Comment by AlexGuteniev** [comment]
This specific question seemed to narrow:

> 5. Have you tried to submit a change to the code in the microsoft/stl repo?
> ( ) I haven’t tried
> ( ) I tried, but was not able to build and run tests
> ( ) I was able to build and run tests, but not successfully make the code change
> ( ) I made the code change, but was not able to complete the PR
> ( ) My PR has been merged
> ( ) My PR was closed by me or others without being merged

Missing "Work in progress" and "Review in progress", also should allow multiple options. My answer would be
- [x] Work in progress
- [x] Review in progress
- [x] My PR has been merged
- [x] My PR was closed by me or others without being merged

**Comment by danmoseley** [comment]
@alexguteniev thanks for the feedback. in our minds this was "what is the furthest progress you have made with a PR". we were interested to see how many people had failed to get a PR merged, and if so why. In your case you've clearly been successful! I'll make a note to clarify the question for next time.

**Comment by MahmoudGSaleh** [comment]
The survey is now closed
