### ISSUE TITLE
`<__msvc_int128.hpp>`: Performance issues

### ISSUE THREAD

**Issue by CaseyCarter** [microsoft/STL#2520]
There are some potenial performance improvements to be made to the 128-bit integer-class types `_Int128` and `_Uint128` defined in `<__msvc_int128.hpp>`:

* [X] ~~DevCom-1544675 results in terrible codegen when MSVC fails to fuse a division and modulo operation with equivalent operands into a single assembly instruction. Divides are expensive enough as it is, we don't want to pay double. The CRT's `div` and `lldiv` are also affected, so we'll need to use `_udiv64`/`_div64` instead of raw `/` and `%` when `!is_constant_evaluated()`.~~ The fix for this will ship "soon", it's not worth investing in a workaround.
* [x] Increment and decrement operations currently use a branch, but `_AddCarry64` / `_SubBorrow64` might be more efficient on x64 / arm64 (needs investigation).
* [x] `_mm_and_si128` / `_mm_or_si128` / `_mm_xor_si128` could probably be used to implement bitops more efficiently at runtime on x64 (presumably arm64 has equivalents).
* [X] (Actually a throughput issue) `__shiftleft128`, `_addcarry_u64`, `_subborrow_u64`, and `_udiv128` need to be moved from `intrin.h` to `intrin0.h` in vcruntime.

Thanks to @AlexGuteniev for suggesting all the above.

**Comment by AlexGuteniev** [comment]
> presumably by using `div` and `lldiv`

These are affected too. `_div64` and `_udiv64` intrinsic is the only viable workaround I'm aware of.

**Comment by CaseyCarter** [comment]
> * (Actually a throughput issue) `__shiftleft128`, `_addcarry_u64`, `_subborrow_u64`, and `_udiv128` need to be moved from `intrin.h` to `intrin0.h` in vcruntime.

I've moved these intrinsics in MSVC-PR-381950. We should be able to fixup the includes in `__msvc_int128.hpp` when that change ships in the first 17.3 preview with a toolset update (generally preview 1 or 2).

**Comment by compnerd** [comment]
The inclusion of `intrin.h` which transitively includes `intrin0.h` causes some trouble for clang.  In particular, the declaration of `_subborrow_u64` and `_addcarry_u64` result in conflicts.  I've put up https://reviews.llvm.org/D139749 however, it is unclear whether this is reasonable as a workaround.  Even with this workaround, include order will still cause an issue as the declaration following the inline definition seems to conflict.

**Comment by AlexGuteniev** [comment]
> [DevCom-1544675](https://developercommunity.visualstudio.com/t/1544675) status: Fixed, Pending Release

DevCom-1544675 status fixed

**Comment by BurningEnlightenment** [comment]
Fixed in which version? No tag 'fixed in: xxx' has been added to the DevCom issue and there hasn't been a release today...

**Comment by CaseyCarter** [comment]
> Fixed in which version? No tag 'fixed in: xxx' has been added to the DevCom issue and there hasn't been a release today...

Looks like it was fixed for 17.4 preview 3, but the metadata wasn't set at the time, so the DevCom automation was confused.

**Comment by AlexGuteniev** [comment]
> * [ ]  `_mm_and_si128` / `_mm_or_si128` / `_mm_xor_si128` could probably be used to implement bitops more efficiently at runtime on x64 (presumably arm64 has equivalents).

This is not needed: the compiler does it on its own.

**Comment by AlexGuteniev** [comment]
> * [ ]  Increment and decrement operations currently use a branch, but `_AddCarry64` / `_SubBorrow64` might be more efficient on x64 / arm64 (needs investigation).

The compiler does not avoid branch even if stated via `_AddCarry64`, and it is apparently right (rollovers are rare, so branch should be predicted)

**Comment by CaseyCarter** [comment]
Awesome, @AlexGuteniev, thanks for the investigation.
