### ISSUE TITLE
P0323R12 `<expected>`

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#2529]
[P0323R12](https://wg21.link/P0323R12) `<expected>`

Feature-test macro:
```cpp
#define __cpp_lib_expected 202202L
```

**Comment by frederick-vs-ja** [comment]
Currently libstdc++ also implements WG21-P2549.

**Comment by miscco** [comment]
:FYI: I started an implementation. I think I am through with a first brush and need to add some serious testing
