### ISSUE TITLE
P1206R7 Conversions From Ranges To Containers

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#2532]
[P1206R7](https://wg21.link/P1206R7) Conversions From Ranges To Containers

Feature-test macros:
```cpp
#define __cpp_lib_containers_ranges   202202L
#define __cpp_lib_ranges_to_container 202202L
```

**Comment by CaseyCarter** [comment]
FWIW, I have most/all of the sequence container changes implemented on https://github.com/CaseyCarter/STL/tree/p1206 if someone would like to steal that branch as a starting point.
