### ISSUE TITLE
P2387R3 Pipe Support For User-Defined Range Adaptors

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#2536]
[P2387R3](https://wg21.link/P2387R3) Pipe Support For User-Defined Range Adaptors

New feature-test macro:
```cpp
#define __cpp_lib_bind_back 202202L
```

This also **increases** the value of an existing feature-test macro:
```cpp
#define __cpp_lib_ranges 202202L
```

**Comment by Ukilele** [comment]
Not that I would want to make any promises, that I will create a MR any time soon. But I at least already implemented `bind_back` in https://github.com/Ukilele/STL/tree/pipe_for_user_defined_range_adaptors.

**Comment by miscco** [comment]
> Not that I would want to make any promises, that I will create a MR any time soon. But I at least already implemented `bind_back` in https://github.com/Ukilele/STL/tree/pipe_for_user_defined_range_adaptors.

That is awesome. I would strongly recommend to rebase on the latest main though

**Comment by Ukilele** [comment]
Thansk for your feedback @miscco ! I've done the rebasing and incorporated your suggestions. I'm not a github expert, so the rebasing required me to create a new branch (but the URL and name is still the same, just the commits are differnt).

**Comment by cpplearner** [comment]
> I made some progress: [Ukilele@1f390cb](https://github.com/Ukilele/STL/commit/1f390cbc1102ab34995a0693bc82f88f09a5a801) Too me it all looks good, but the test, which I added, fails for `Configuration Number` 11. I still try to figure it out, but help (or any other kind of feedback) would be appreciated. I guess it is the test that compiles with `/permissive` (without a dash). FYI @miscco .

It does seem like a problem with `/permissive`. The error reproduces with today's `transform_view`: https://godbolt.org/z/4Mdqe9oaM .

Maybe the test should follow most ranges-related tests and use `strict_concept_latest_matrix.lst` (instead of `usual_latest_matrix.lst`), which doesn't try to compile with `/permissive` 😜

**Comment by Ukilele** [comment]
`tests\P2443R1_views_chunk_by\env.lst` indeed also uses `strict_concepts_latest_matrix.lst`. Thank you very much @cpplearner ! 😃
