### ISSUE TITLE
N1381 memset_s() to clear memory, without fear of removal

### ISSUE THREAD

**Issue by TheStormN** [microsoft/STL#2545]
[N1381](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1381.pdf) memset_s() to clear memory, without fear of removal

Feature-test macro:
`#define __STDC_WANT_LIB_EXT1__ 1`

This is actually C11 ISO/IEC 9899:2011 k 3.7.4.1 which is not a core future, but an appendix. I see that on *nix implementations, this function is available and I would like to also have it in MSVC STD library to avoid adding my own `#ifdefs` each time when I need to securely erase memory.

If this is going to be generally accepted, I can submit a PR myself, just give me your opinion.

**Comment by frederick-vs-ja** [comment]
I think `memset_s` should be managed by UCRT, not MSVC STL.
But I don't know how to contribute to UCRT.😿

**Comment by TheStormN** [comment]
Ah, me too. Lets hope that they can at least forward it where it belongs.

**Comment by stwish-msft** [comment]
Could you open a feedback item on [Developer Community](https://developercommunity.visualstudio.com/) for this feature request? Pass me a link here and I'll get it to the right place.

**Comment by fsb4000** [comment]
@stwish-msft DevCom-1657319

**Comment by TheStormN** [comment]
@stwish-msft @fsb4000 I was going to post it, but waited for a link, because when you post on DevCom, you are not getting the issue published immediately. So yeah: [DevCom-1657319](https://developercommunity.visualstudio.com/t/1657319) is the thing I've created.

**Comment by StephanTLavavej** [comment]
Thanks everyone - closing this issue as DevCom and the UCRT will now track this.
