### ISSUE TITLE
LWG-3525 `uses_allocator_construction_args` fails to handle types convertible to `pair`

### ISSUE THREAD

**Issue by CaseyCarter** [microsoft/STL#2551]
LWG-3525 `uses_allocator_construction_args` fails to handle types convertible to `pair`

**Comment by frederick-vs-ja** [comment]
I find that the resolution possibly imply that `T` may be cv-qualified. Currently MSVC STL only treats cv-unqualified `pair` types as such specializations, while libstdc++ admits both unqualified and const-qualified (but not volatile-qualified) `pair` types.
Is another LWG issue needed?

**Comment by CaseyCarter** [comment]
LWG has a bad habit of sometimes saying "specialization of `meow`" when they really intend "cv-qualified specialization of `meow`". I've asked for clarification, and will open an issue if necessary.
