### ISSUE TITLE
Azure Pipelines: Investigate uploading test logs as artifacts

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#2557]
When tests fail, the error messages displayed in Azure Pipelines can be truncated if the command lines and/or error messages are very long (>4000 characters). Apparently, this is a limitation that can't be lifted or directly worked around. However, we should be able to upload the test logs as artifacts. `run-tests.yml` might be the file to modify:

https://github.com/microsoft/STL/blob/bbd5dbaa61f192b393d12ea75a2dae1b8a014e7a/azure-devops/run-tests.yml#L1-L48

I think these are the log files:

https://github.com/microsoft/STL/blob/bbd5dbaa61f192b393d12ea75a2dae1b8a014e7a/azure-devops/native-build-test.yml#L20
https://github.com/microsoft/STL/blob/bbd5dbaa61f192b393d12ea75a2dae1b8a014e7a/azure-devops/cross-build.yml#L23

**Comment by cbezault** [comment]
I _think_ there should already be a way to get at the xml file behind the log output but otherwise what you've described will definitely work. Just add another publish block and you'll be good to go.
