### ISSUE TITLE
`syserror.cpp`: update `_Syserror_map`

### ISSUE THREAD

**Issue by fsb4000** [microsoft/STL#2561]
we need update `_Syserror_map` to handle zero error code.

and delete the workaround from `<system_error>`:

```c++
if (_Errcode == 0) {
    return "success";
} else {
    return _Syserror_map(_Errcode);
}
```

**Comment by AlexGuteniev** [comment]
Not `<syserror.cpp>`, just `syserror.cpp`, it is not a STL header, I assume.
