### ISSUE TITLE
`<vector>`: Consider another representation

### ISSUE THREAD

**Issue by AlexGuteniev** [microsoft/STL#2574]
Vector internally uses pointers.

For loops like this:
```C++
for (int i = 0; i < v.size(); i++) {
   ...
}
```

This may be suboptimal, as there would be a division to convert from pointer to size. For non-power-of-two element size this would be a reciprocal multiplication, which is not as slow as a real division but still.

Assuming the size is stored, converting to pointers for iterator-based loop is usually easy with arithmetic (one or two `lea` is efficient to multiply by some small constants. other arithmetic insn can also be used to avoid long multiplication).

Index-based loops are frequent use case, as index may be used to index multiple vectors a/or for computations; this cannot be easily expressed with iterators.

Workaround is
```C++
for (int i = 0, m = v.size(); i < m; i++) {
   ...
}
```
but maybe the STL should be changed instead.

**vNext note:** Resolving this issue will require breaking binary compatibility. We won't be able to accept pull requests for this issue until the vNext branch is available. See #169 for more information.

**Comment by miscco** [comment]
I think there is a more important aspect here.

If one goes with ptr-size-capacity model one can implement all varieties of contiguous containers with a single implementation templated on the storage type

`static_vector` for example really wants this 

P.s. obviously dependent on all those additional containers being added

**Comment by fsb4000** [comment]
I believe range based for loop is

```c++
auto begin = v.begin();
auto end = v.end();
for(; begin != end; ++begin) {
  // do stuff
}
```
That's why C++ vector is pointers in MSSTL, libstdc++, libc++

**Comment by AlexGuteniev** [comment]
> That's why C++ vector is pointers in MSSTL, libstdc++, libc++

Don't think it is precise, vector is a far earlier invention than range based for loop.
Anyway, I acknowledge that range based for loop is a primary use case, but it is only slightly pessimized (`end` is only slightly more expensive, and it is computed only once).

The case:
```c++
for(auto it = v.begin(); it != v.end(); ++it) {
  // do stuff
}
```
is pessimized more, but still size-based loop is more optimized, than this one is pessimized

**Comment by StephanTLavavej** [comment]
As there are no pure wins here, extracting the size is an effective (although not complete) mitigation for programs that need index loops, and changing the representation of the STL's most important data structure would affect existing codebases, I am not in favor of changing this in vNext.

**Comment by StephanTLavavej** [comment]
We talked about this at the weekly maintainer meeting and several maintainers felt that having benchmark data indicating whether this is a noticeable improvement and how much so would be helpful in deciding whether to make such a change.

**Comment by AlexGuteniev** [comment]
<details>
<summary><b>Benchmark program</b></summary>

```c++
#include <benchmark/benchmark.h>
#include <vector>

struct data_t {
    int data[5];
};

struct iterator_vector {
    data_t* _begin;
    data_t* _end;
    data_t* _last;

    data_t* begin() { return _begin; }
    data_t* end() { return _end; }

    data_t& at(size_t i) { return _begin[i]; }
    size_t size() { return _end - _begin; }

    iterator_vector(size_t size, size_t reserved) {
        _begin = reinterpret_cast<data_t*>(calloc(reserved, sizeof(data_t)));
        _end = _begin + size;
        _last = _begin + reserved;
    }

    ~iterator_vector() { free(_begin); }

    iterator_vector(const iterator_vector&) = delete;
    iterator_vector& operator=(const iterator_vector&) = delete;
};

struct size_vector {
    data_t* _begin;
    size_t _size;
    size_t _rsvd;

    data_t* begin() { return _begin; }
    data_t* end() { return _begin + _size; }

    data_t& at(size_t i) { return _begin[i]; }
    size_t size() { return _size; }

    size_vector(size_t size, size_t reserved) {
        _begin = reinterpret_cast<data_t*>(calloc(reserved, sizeof(data_t)));
        _size = size;
        _rsvd = reserved;
    }

    ~size_vector() { free(_begin); }

    size_vector(const iterator_vector&) = delete;
    size_vector& operator=(const iterator_vector&) = delete;
};


const size_t size = 10000;
const size_t rsvd = 15000;

// To feed vector, thus preserve the compiler from cheating due to knowing all context.
// (To model real-life usage)
void (*unknown)(void*) = [](void*) {};

template<class V>
static void IndexLoop(benchmark::State& state) {
    V v(size, rsvd);
    unknown(&v);
    for (auto _ : state) {
        // deliberately not caching size to model usual suboptimal pattern
        for (std::size_t i = 0; i < v.size(); ++i) { 
            auto& data = v.at(i);
            benchmark::DoNotOptimize(data.data[0]);
        }
    }
}

template<class V>
static void IteratorLoop(benchmark::State& state) {
    V v(size, rsvd);
    unknown(&v);
    for (auto _ : state) {
        // deliberately not caching size to model usual suboptimal pattern
        for (auto it = v.begin(); it != v.end(); ++it) {
            auto& data = *it;
            benchmark::DoNotOptimize(data.data[0]);
        }
    }
}

template<class V>
static void RangeLoop(benchmark::State& state) {
    V v(size, rsvd);
    unknown(&v);
    for (auto _ : state) {
        for (auto& data : v) {
            benchmark::DoNotOptimize(data.data[0]);
        }
    }
}

BENCHMARK(IndexLoop<iterator_vector>);
BENCHMARK(IteratorLoop<iterator_vector>);
BENCHMARK(RangeLoop<iterator_vector>);
BENCHMARK(IndexLoop<size_vector>);
BENCHMARK(IteratorLoop<size_vector>);
BENCHMARK(RangeLoop<size_vector>);

BENCHMARK_MAIN();
```

</details>

I added `--benchmark_min_time=1` parameter when running for a bit more reliable results.
**The results:**
```
2022-02-20T16:02:27+02:00
Running C:\Users\Aleksandr.Gutenev\source\repos\vb\x64\Release\vb.exe
Run on (12 X 2208 MHz CPU s)
CPU Caches:
  L1 Data 32 KiB (x6)
  L1 Instruction 32 KiB (x6)
  L2 Unified 256 KiB (x6)
  L3 Unified 9216 KiB (x1)
------------------------------------------------------------------------
Benchmark                              Time             CPU   Iterations
------------------------------------------------------------------------
IndexLoop<iterator_vector>         13908 ns        13811 ns        99556
IteratorLoop<iterator_vector>      10271 ns        10254 ns       128000
RangeLoop<iterator_vector>         12794 ns        12835 ns       112000
IndexLoop<size_vector>             10281 ns        10312 ns       100000
IteratorLoop<size_vector>          12806 ns        12835 ns       112000
RangeLoop<size_vector>             12802 ns        12835 ns       112000
```

Results reformatted:
| Loop        | iterator_vector| size_vector |
|-------------|----------------|-------------|
|IndexLoop    | 13811 ns       | 10312 ns    |
|IteratorLoop | 10254 ns       | 12835 ns    |
|RangeLoop    | 12835 ns       | 12835 ns    |


**The results interoretation:**
 * Expectedly no difference for range based loop, due to end iterator caching
 * Expectedly sized loop is better with size as a member (the suggested layout optimization)
 * Expectedly iterator-based loop is better with size as a pointer (pessimization of this change)

**Comment by AlexGuteniev** [comment]
To me the difference appears to be of little significance to consider this further.

**Comment by CaseyCarter** [comment]
> To me the difference appears to be of little significance to consider this further.

Thank you for the investigation, @AlexGuteniev! I agree there's nothing here to motivate shaking up the status quo.

> Just wondering: Does microsoft have some sort of "real-world" benchmark suite, which you can recompile with a new version of the STL and see if it has any effects? 

No we do not, a fact which has been bothering us since at least 2017 or so. We've been talking about it more seriously lately in conjunction with our discussions of open-sourcing VCRuntime; it would be a shame if someone reordered a couple of instructions in `memcpy` and made all programs run 10% slower.
