### ISSUE TITLE
`<charconv>`: Replace script-generated constants with compile time computed

### ISSUE THREAD

**Issue by AlexGuteniev** [microsoft/STL#2585]
After #2125, the large tables will reside in `.cpp`. The tables are generated by C++ programs.

With moving into `.cpp` it is possible to make these programs into constant initializer:
 * We don't spend throughput for the user's code
 * We only need to support MSVC and latest C++, so we can use nice things in `constexpr` functions (like, `unique_ptr<T[]>`)
 * With `constexpr` or `constinit` it is possible to guarantee compile-time evaluation

**Comment by StephanTLavavej** [comment]
It may be feasible to do this with `constexpr` computation, although I note a couple of concerns:

* The original generators were Java in Ulf Adams' upstream repo; that part of the codebase was not dual-licensed under Boost. We'd probably need to ask Ulf to extend the dual-licensing if we want to pursue such a `constexpr` conversion.
* IIRC, the generators needed bignums (available in Java), but our extremely minimal `_Big_integer_flt` may not be suitable for the task. Python might be a better approach.

Finally, I'm not convinced that this would achieve anything significant, as the tables aren't frequently modified (in fact they never are, as long as the algorithm remains unchanged), and having them checked into the repo is not a significant cost.

**Comment by AlexGuteniev** [comment]
I agree, I didn't realize the generstors are upstream code.
