### ISSUE TITLE
`stl/CMakeLists.txt`: Rerunning CMake relinks `msvcp140_atomic_wait_oss.dll` unnecessarily

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#2605]
`msvcp140_atomic_wait_oss.dll` depends on a generated file:

https://github.com/microsoft/STL/blob/4bb41db3d8e7605fc03656659752f3fad4133bc0/stl/CMakeLists.txt#L505-L513

We're replacing this text:

https://github.com/microsoft/STL/blob/4bb41db3d8e7605fc03656659752f3fad4133bc0/stl/src/msvcp_atomic_wait.src#L6

After building, rerunning `ninja` alone is fine:

```
D:\GitHub\STL>cmake -G Ninja -S . -B out\build\x64 && ninja -C out\build\x64
[...]
[977/977] Linking CXX static library out\lib\amd64\libcpmtd.lib

D:\GitHub\STL>ninja -C out\build\x64
ninja: Entering directory `out\build\x64'
ninja: no work to do.
```

However, rerunning `cmake` followed by `ninja` performs an unnecessary relink:

```
D:\GitHub\STL>cmake -G Ninja -S . -B out\build\x64 && ninja -C out\build\x64
[...]
[2/2] Linking CXX shared library out\bin\amd64\msvcp140_atomic_wait_oss.dll
```

@cbezault says that [`add_custom_command`](https://cmake.org/cmake/help/latest/command/add_custom_command.html) might be the cleanest way to do this.

We should avoid changing the content of `msvcp_atomic_wait.src` as the internal build system also needs to consume this file (and changing that is a headache).

**Comment by AlexGuteniev** [comment]
Maybe give up on that and go to `__declspec(dllexport)` ?
