### ISSUE TITLE
Unicode char support issue

### ISSUE THREAD

**Issue by HenryAWE** [microsoft/STL#2608]
**Describe the bug**
Compiler refuse to compile `std::basic_stringstream<char32_t>`, but `std::basic_stringstream<wchar_t>` works fine.

**Comment by fsb4000** [comment]
Why do you think it should work?

It doesn't work with clang either: https://godbolt.org/z/nje9z7nTf

**Comment by HenryAWE** [comment]
I've tested it on my Arch Linux with GCC 11.1 and it doesn't work fine either. However, GCC can compile those code with `std::basic_stringstream<char32_t>`, though the runtime result is incorrect when I tried to input/output a type other than `std::basic_string`.
So how should I write a program supporting Unicode well since `sizeof(wchar_t)` is varying between different platform

**Comment by fsb4000** [comment]
What do you want to do?

Maybe the stackoverflow answer will help you: https://stackoverflow.com/a/31462506

**Comment by HenryAWE** [comment]
I think this can solve my problem. Thanks.
