### ISSUE TITLE
`<xloctime>`: `get_time` does not return correct year in `tm.tm_year` if year is 1

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#2618]
Originally reported as DevCom-1287303 and internal VSO-1259138 / AB#1259138 .

```
C:\Temp>type meow.cpp
```
```cpp
#include <ctime>
#include <iomanip>
#include <iostream>
#include <sstream>
#include <string>
using namespace std;

void test(const string& date) {
    tm time{};
    istringstream iss{date};
    iss >> get_time(&time, "%Y");
    cout << "date: \"" << date << "\"; 1900 + time.tm_year: " << 1900 + time.tm_year << endl;
}

int main() {
    test("0001");
    test("0080");
    test("1995");
    test("2022");
}
```
```
C:\Temp>cl /EHsc /nologo /W4 /MTd meow.cpp && meow
meow.cpp
date: "0001"; 1900 + time.tm_year: 2001
date: "0080"; 1900 + time.tm_year: 1980
date: "1995"; 1900 + time.tm_year: 1995
date: "2022"; 1900 + time.tm_year: 2022
```

This is due to: https://github.com/microsoft/STL/blob/f099e9c9f91187376e85385b135ac62ef933e54f/stl/inc/xloctime#L351-L357

The Standardese is WG21-N4910 [[locale.time.get.virtuals]/9](https://eel.is/c++draft/locale.time.get.virtuals#9)

> *Effects:* Reads characters starting at `s` until it has extracted an unambiguous year identifier. It is implementation-defined whether two-digit year numbers are accepted, and (if so) what century they are assumed to lie in. Sets the `t->tm_­year` member accordingly.

The issue appears to be that we activate our two-digit logic even when we've physically read 4 digits.

**Comment by MattStephanson** [comment]
Is there any reason this *must* call `_Getint`? The trouble with `_Getint`, as you pointed out [here](https://github.com/microsoft/STL/pull/1280#discussion_r485983647), is that it's separately-compiled so it's signature can't change. But we're working with `InputIterators` here, so the parsing function is the only place to find out how many digits were read.

It seems like if we could replace `_Getint` with a header-only or non-exported function, maybe we'd have the freedom to create a new interface.

**Comment by StephanTLavavej** [comment]
Excellent question - I see no reason why this must call `_Getint`. (It's not `virtual`, it's not doing anything special that header-only code can't do.) So such a change should be possible.
