### ISSUE TITLE
`<xutility>`: SFINAE constraint on `construct_at` prevents emplacing immovable objects with copy elision

### ISSUE THREAD

**Issue by Chlorie** [microsoft/STL#2620]
**Describe the bug**
Currently the constraint on `construct_at` is implemented via SFINAE
https://github.com/microsoft/STL/blob/f099e9c9f91187376e85385b135ac62ef933e54f/stl/inc/xutility#L132-L134

This causes an error when trying to emplace immovable objects with copy elision:
`xutility(145): error C2783: '_Ty *std::construct_at(_Ty *const ,_Types &&...) noexcept(<expr>)': could not deduce template argument for '<unnamed-symbol>'`

Example code:

```cpp
struct S
{
    int v;
    S(int v): v(v) {}
    S(const S&) = delete;
};

union U
{
    char c;
    S s;
    U(): c{} {}
    ~U() noexcept {}
};

struct copy_elider
{
    operator S() const { return S(42); }
};

int main()
{
    U u;
    // AFAIK this should work since C++17 mandates copy elision
    std::construct_at(&u.s, copy_elider{});
}
```

Yet if the constraint is implemented via concepts, i.e.
```cpp
template <class _Ty, class... _Types>
    requires requires (void* ptr, _Types&&... _Args) { ::new (ptr) _Ty(static_cast<_Types&&>(_Args)...); }
constexpr _Ty* construct_at(_Ty* const _Location, _Types&&... _Args) noexcept(
```
then the example code above works as expected. I don't know the reason that these two behaviors differ though...

This issue hinders the ability to emplace immovable objects into `optional`s or `variant`s using the copy elision converter trick shown above.

**STL version**
VS Community 2022, Version 17.1.2

**Comment by miscco** [comment]
Originally we had it constrained via a requires clause, but that lead to some strange compiler errors for some corner cases. (Not to speak of intellisense which is EDG based and thus currently not available for concepts)

@StephanTLavavej found this to be the appropriate perma workaround. Do you still remember what broke?

**Comment by miscco** [comment]
Oh and it is constexpr container support machinery. Who would have thought?

https://github.com/microsoft/STL/pull/1546/commits/075dfaf2c3aed15291bcd2f205e905ec94fa4166

**Comment by miscco** [comment]
Also please note, that your code exhibits a certain amount of UB, because you are taking the reference to a not yet alive object.
```cpp
std::construct_at(&u.s, copy_elider{});
```
here `u.s` is not yet alive so taking a reference is ill formed. you *should* be fine, but do not expect this to work in a constexpr context

**Comment by Chlorie** [comment]
> Also please note, that your code exhibits a certain amount of UB, because you are taking the reference to a not yet alive object.
> 
> ```c++
> std::construct_at(&u.s, copy_elider{});
> ```
> 
> here `u.s` is not yet alive so taking a reference is ill formed. you _should_ be fine, but do not expect this to work in a constexpr context

Yes, I'm aware of the potential UB. It's just that I couldn't come up with any concise examples without UB :sob:
I stumbled upon the issue when trying to emplace immovable objects into `optional`s as described in the main description.

**Comment by frederick-vs-ja** [comment]
> Also please note, that your code exhibits a certain amount of UB, because you are taking the reference to a not yet alive object.
> 
> ```c++
> std::construct_at(&u.s, copy_elider{});
> ```
> 
> here `u.s` is not yet alive so taking a reference is ill formed. you _should_ be fine, but do not expect this to work in a constexpr context

No, this is well-defined, as at least the code is just taking the address of an inactive member. If such code has UB, then we can't generally reasonably change active member of a union during constant evaluation.

Using `std::addressof` in such case may be UB. This is [WG21-CWG453](https://cplusplus.github.io/CWG/issues/453.html).

**Comment by miscco** [comment]
Ahh, sorry, you are correct, you can take the address. https://godbolt.org/z/zbbWPr3M3

The issue I was miss-remembering was that we passed that address on into another function (char_traits for std::string) and there it is indeed invalid.

**Comment by fsb4000** [comment]
```
C:/data/msvc/14.31.31104/include\xmemory(676): error C2783: '_Ty *std::construct_at(_Ty *const ,_Types &&...) noexcept(<expr>)': could not deduce template argument for '<unnamed-symbol>'
```

It is duplicate DevCom-1691516 and I think it is a compiler issue.

**Comment by StephanTLavavej** [comment]
Agreed that this seems like a compiler issue if it works fine with Clang and MSVC's STL (haven't confirmed), labeling accordingly.

**Comment by frederick-vs-ja** [comment]
It seems that MSVC works if implementation of the constraint is changed to:
```C++
void_t<decltype(::new (_STD declval<void*>()) _Ty(_STD declval<_Types>()...))>* = nullptr
```

**Comment by miscco** [comment]
I think we should report that issue for EDG and work around it by keeping the original code for EDG with `#ifdef __EDG__` and using the fixed version in other cases
