### ISSUE TITLE
`<yvals_core.h>`: Conformance issue on `[[msvc::known_semantics]]`

### ISSUE THREAD

**Issue by frederick-vs-ja** [microsoft/STL#2645]
`msvc` and `known_semantics` are not reserved identifiers in the C++ Standard, so users are allowed to `#define` them to anything, which may break every header that directly uses `[[msvc::known_semantics]]` (e.g. `<type_traits>`).

IIUC the Standard equivalently requires that every non-Standard attribute used in a Standard header to be spelled in reserved identifiers, e.g. `[[__msvc__::__known_semantics__]]`. Does MSVC support such spelling?

**Comment by frederick-vs-ja** [comment]
This issue seems not correctly fixed (https://github.com/llvm/llvm-project/issues/61196#issuecomment-1458718673).

**Comment by CaseyCarter** [comment]
Per Discord discussion, we should probably give up battling the preprocessor and just have the compiler front end implement ugly equivalents of the pertinent attributes.
