### ISSUE TITLE
`<memory>`: `~unique_ptr` redundantly checks the pointer is non-null before `delete`

### ISSUE THREAD

**Issue by CaseyCarter** [microsoft/STL#2652]
`~unique_ptr` checks that the stored pointer is non-null before invoking its deleter. When that deleter is `default_delete`, the null check is redundant since `delete ptr;` doesn't require `ptr` to be non-null. We should detect this case (`pointer` is actually a pointer and deleter is a library-defined specialization of `default_delete`) and avoid the redundant check.

(Per discussion on the Microsoft-internal C++ VCSig distribution list.)

**Comment by AlexGuteniev** [comment]
It is a pessimization quite often. When the pointer is trackably null, like moved out pointer, a call is avoided with check, but not avoided without.

**Comment by CaseyCarter** [comment]
Optimizing away the null check and calling `delete` with null pointers changes observable behavior since `operator delete` is replaceable. It's also potentially a pessimization, as Alex points out, since with the change the compiler must call `operator delete` with null pointers unless it can prove that `operator delete` has not been replaced.

I don't think there's anything we can do here except suggest that folks enable LTO and hope the compiler removes the redundant check after determining that `operator delete` is not replaced.

**Comment by CaseyCarter** [comment]
> It's also potentially a pessimization, as Alex points out, since with the change the compiler must call `operator delete` with null pointers unless it can prove that `operator delete` has not been replaced.

This isn't exactly true. [[expr.delete]/7](https://eel.is/c++draft/expr.delete#7.sentence-3) says:

> If the value of the operand of the [delete-expression](https://eel.is/c++draft/expr.delete#nt:delete-expression) is a null pointer value, it is unspecified whether a deallocation function will be called as described above.

So a compiler may freely omit calls to `operator delete` with arguments known to be null pointers. (I don't know that they _do_, but they _may_.)
