### ISSUE TITLE
vector pop_back invalidates iterator pointing to the element being popped out

### ISSUE THREAD

**Issue by bubnikv** [microsoft/STL#2659]
**Describe the bug**

```
std::vector<int> v { 1 };
for (auto it = v.begin(); it != v.end();) {
    v.pop_back();
}
```
fails at `it != v.end()` in debug mode because the iterator pointing to the last element was marked as invalid at v.pop_back(), while I expect the iterator to be still valid and pointing to v.end(). As expected, everything works in release mode.

**STL version**

Microsoft (R) Build Engine version 16.11.2+f32259642 for .NET Framework

**Comment by miscco** [comment]
I have to strongly disagree. The iterator has changed substantially in that it is not longer dereferenceable

Further the underlying sequence has changed after the erasure position. This is especially important for erasing in the mid.

**Comment by bubnikv** [comment]
@miscco I understand your point of view, however the code snippet is perfectly valid. Nobody is trying to dereference the iterator, only to compare it against vector::end(), which should succeed.

**Comment by sylveon** [comment]
The standard says "Effects: Invalidates iterators and references at or after the point of the erase." which means the behavior you are seeing is correct. Iterator debugging is catching a bug in your code.

**Comment by CaseyCarter** [comment]
As @sylveon made clear, the Standard says that `pop_back` "Invalidates iterators and references at or after the point of erase." ([vector.modifiers]/3](https://eel.is/c++draft/vector.modifiers#3)) which includes the end iterator. This is not a bug, but intentional behavior.
