### ISSUE TITLE
Bad compile time with std::variant

### ISSUE THREAD

**Issue by tquante** [microsoft/STL#2664]
I have tested some toy variant examples and experienced a very bad compile time. The following example
```
#include<variant>

struct f1 { explicit f1(int i) :j(i) {} int j; };
struct f2 {  };
struct f3 {  };
struct f4 {  };
struct f5 {  };
struct f6 {  };
struct f7 {  };
struct f8 {  };
struct f9 {  };
struct f10 {  };
struct f11 {  };
struct f12 {  };
struct f13 {  };
struct f14 {  };
struct f15 {  };
struct f16 {  };
struct f17 {  };
struct f18 {  };
struct f19 {  };
struct f20 {  };
std::variant<f1, f2, f3, f4, f5, f6,f7,f8,f9,f10,f11,f12,f13,f14,f15,f16,f17,f18,f19,f20> test = f2{};
```

compiles in 20-40 ms, but in case the first struct does not have a constructor, the compile times sky rocket to several minutes. Is this the expected behavior or is it a bug in the implementation? If this is the expected behavior, variants are unable to replace tagged unions which would be very unfortunate.

Currently I use the STL, that has been deployed by visual studio version 16.11.10

**Comment by fsb4000** [comment]
> Currently I use the STL, that has been deployed by visual studio version 16.11.10

I can reproduce the same behaviour in visual studio version 17.2 Preview 3

**Comment by fsb4000** [comment]
I found bug report Devcom-1660892 and I upvoted the issue, maybe it will speed up :)

**Comment by StephanTLavavej** [comment]
Closing as this is a compiler bug that's currently assigned to a `constexpr` maintainer - thanks again for the report! :smile_cat:

**Comment by fsb4000** [comment]
DevCom-1660892: Fixed - Pending Release
