### ISSUE TITLE
[Question] why not use std::array for ryu_table.h?

### ISSUE THREAD

**Issue by expnkx** [microsoft/STL#267]
https://github.com/microsoft/STL/blob/master/stl/inc/xcharconv_ryu_tables.h

Here is my implementation
https://bitbucket.org/ejsvifq_mabmip/fast_io/src/default/include/fast_io_freestanding_impl/ryu/fixed_table.h

https://bitbucket.org/ejsvifq_mabmip/fast_io/src/default/include/fast_io_freestanding_impl/ryu/fixed.h

I have implemented this with std::array. it works for no problem. No performance decrease. No compilation speed decrease.

C style array/string should be abolished in modern C++.

https://bitbucket.org/ejsvifq_mabmip/fast_io/src/default/include/fast_io_core_impl/shared_base_table.h

I think the table can be generated with constexpr functions, which will decrease compilation further.. However, I do not understand how the table was generated.

**Comment by StephanTLavavej** [comment]
* There's a relatively minor throughput concern for dragging `<array>` into `<charconv>`. (Throughput involves both time and compiler memory consumption.)
* There's a more significant bincompat concern - separately compiling the tables for #172 will be safest if they're builtin arrays. (If we inject things into the import LIB, they can't depend on `_ITERATOR_DEBUG_LEVEL`, but `array::iterator` does.)
* `array` would provide bounds checking in debug mode, but that would detect only logic errors in the algorithm.
* We're already layering a massive number of changes on top of upstream Ryu.
* Making `operator[]` into a function call introduces debug mode overhead, as the optimizer and inliner aren't running.

This is a judgement call, but currently I believe that `array` wouldn't be worth the trouble here.
