### ISSUE TITLE
File an LWG issue about `char_traits::eq()` being underspecified

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#2691]
See this comment thread: https://github.com/microsoft/STL/pull/2676#discussion_r862163154

For example, `char_traits::eq()` should consider the null terminator to be distinct from every other value.

**Comment by frederick-vs-ja** [comment]
It may be difficult to make such specification when there's no `operator==` for `T`, or when equality comparison results in UB for `T()` (while `eq` is still well-defined). Not sure whether "value representation" is suitable here.

**Comment by frederick-vs-ja** [comment]
LWG-3694 is filed now.

**Comment by StephanTLavavej** [comment]
Thank you! :heart_eyes_cat:
