### ISSUE TITLE
P0608R3 Improving variant's Converting Constructor/Assignment

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#27]
[P0608R3](https://wg21.link/P0608R3) Improving `variant`'s Converting Constructor/Assignment

This is reportedly a highly breaking change.

**Comment by StephanTLavavej** [comment]
[libc++ says](https://libcxx.llvm.org/cxx2a_status.html) this was implemented in Clang 9.0, and [libstdc++ says](https://gcc.gnu.org/onlinedocs/libstdc++/manual/status.html#status.iso.2020) this was implemented in GCC 10.1. I haven't heard about this further, so I'm assuming that it's ultimately reasonable to implement.

**Comment by statementreply** [comment]
Related: WG21-P1957
