### ISSUE TITLE
STL: Change macro constants to constexpr variables

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#270]
Older parts of our codebase contain many macro constants:

https://github.com/microsoft/STL/blob/66b1e235afd433062d3f527ce6df2a6432822737/stl/src/xtime.cpp#L11-L14

We try to avoid macros when possible, so we use constexpr variables in new code. We should update the old code to be consistent.

**Comment by JeanPhilippeKernel** [comment]
Can I work on this  :) ? @CaseyCarter  @StephanTLavavej

**Comment by StephanTLavavej** [comment]
Absolutely, @JeanPhilippeKernel!
