### ISSUE TITLE
STL: Consider using P1301R4 [[nodiscard("message")]]

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#271]
WG21-P1301 `[[nodiscard("message")]]` has been implemented for VS 2019 16.5 and has [also been implemented](https://clang.llvm.org/cxx_status.html) by Clang 9.

We should consider using this in the STL. We have a few criteria for marking functions as `[[nodiscard]]`: pure observer (most common), resource leak, incorrect behavior (e.g. `remove_if()`). We could have macros for each of these reasons.

**Comment by SuperWig** [comment]
Just linking #206 as you've given a much more in depth description of the goals of `[[nodiscard]]` there.

re:
> We could have macros for each of these reasons

`_NODISCARD` is defined in `vcruntime.h` which is not in this repo so would those just go in `yvals_core.h`?

**Comment by StephanTLavavej** [comment]
> `_NODISCARD` is defined in `vcruntime.h` which is not in this repo so would those just go in `yvals_core.h`?

Yep!

**Comment by StephanTLavavej** [comment]
Thinking about this a little more, we could make `_NODISCARD` (classic) state the "pure observer" reason, since it is overwhelmingly common, then we could have separate macros for other reasons (or maybe just one that takes a custom message). We'd need to audit the 3000+ existing `_NODISCARD`s to find the special ones.

**Comment by AlexGuteniev** [comment]
Please check if the approach in #2211 is right. Or maybe we can go by parts and avoid a huge PR?
