### ISSUE TITLE
<future>: promise<_Ty&>::set_value(_Ty& _Val) should use _STD addressof(_Val)

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#272]
https://github.com/microsoft/STL/blob/f9b1dccd121b5f8bb76d06adb0c85aac3f766326/stl/inc/future#L1240-L1246

This code is saying `&_Val` to get the address of an object (specifically, a parameter passed by reference). This is, perhaps surprisingly, a bug. The STL is required to be extremely flexible and work with near-arbitrary user-defined types. In particular, user-defined types might overload the address-of operator, `operator&()`, and the STL is required to tolerate this.

We do so by calling the library function `addressof()`, which uses special magic to get the true address of an object without interference from overloaded operators.

Additionally, the STL is required to defend itself against Argument-Dependent Lookup, so we explicitly qualify all non-`_Ugly` function calls. We use an internal macro for this: `_STD` expands to `::std::` .

This should be a two-line fix (unless I have missed other occurrences; note that it is okay to say `&thing` for object types that can't depend on user-defined types - there's no way that `&some_int` can misbehave).

**Comment by WinstonWolf1** [comment]
I would like to work on this

**Comment by StephanTLavavej** [comment]
Sounds good, I look forward to your pull request!
