### ISSUE TITLE
<fstream>: ICE when used as header unit

### ISSUE THREAD

**Issue by michaelvlach** [microsoft/STL#2724]
**Describe the bug**
When all MSVC STL headers are included in a single header and that header is converted to a header unit any usage of stuff from `<fstream>` causes ICE. Started happening with MSVC `17.2.0`. Luckily there is a workaround (see at the bottom).

**Command-line test case**
The `stl.hpp` is attached for convenience along with full repro.

[vs_repro.zip](https://github.com/microsoft/STL/files/8698170/vs_repro.zip)

```
import "stl.hpp";

int main()
{
    std::ofstream{"C:/repro"} << "Hello, World!";
}
```
Build it with:
```
cl.exe /std:c++20 /EHsc /exportHeader /ifcOutput stl.hpp.ifc /Fostl.hpp.obj /c /TP stl.hpp
cl.exe /std:c++20 /EHsc /headerUnit stl.hpp=stl.hpp.ifc /Femain.exe  main.cpp stl.hpp.obj
```
You will get:
```
c:\dev\vs_repro>cl.exe /std:c++20 /EHsc /headerUnit stl.hpp=stl.hpp.ifc /Femain.exe  main.cpp stl.hpp.obj
Microsoft (R) C/C++ Optimizing Compiler Version 19.32.31328 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

main.cpp
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\random(4485): error C2028: struct/union member must be inside a struct/union
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\fstream(705): note: while compiling class template member function 'void std::basic_filebuf<_Elem,_Traits>::_Init(FILE *,std::basic_filebuf<_Elem,_Traits>::_Initfl)'
        with
        [
            _Elem=char,
            _Traits=std::char_traits<char>
        ]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\fstream(688): note: see reference to function template instantiation 'void std::basic_filebuf<_Elem,_Traits>::_Init(FILE *,std::basic_filebuf<_Elem,_Traits>::_Initfl)' being compiled
        with
        [
            _Elem=char,
            _Traits=std::char_traits<char>
        ]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\fstream(1167): note: see reference to class template instantiation 'std::basic_filebuf<_Elem,_Traits>' being compiled
        with
        [
            _Elem=char,
            _Traits=std::char_traits<char>
        ]
main.cpp(5): note: see reference to class template instantiation 'std::basic_ofstream<char,std::char_traits<char>>' being compiled
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\fstream(710): fatal error C1903: unable to recover from previous error(s); stopping compilation
INTERNAL COMPILER ERROR in 'C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\bin\HostX86\x86\cl.exe'
    Please choose the Technical Support command on the Visual C++
    Help menu, or open the Technical Support help file for more information
```

**Expected behavior**
It would compile without issues as it did prior to MSVC 17.2.0.

**STL version**
```
Microsoft Visual Studio Community 2022
Version 17.2.0
```

**Additional context**
I know we are not going to get "modularized" STL until 2023 so this is not exactly fully supported. These kinds of issues plagued MSVC for a long time but they were mostly fixed and it has worked like a charm for a long time too until now so if it broke (either in the compiler or STL) it might be worth fixing it.

**Workaround**

Move `<fstream>` to the top before all other headers. Might be a clue as to what's wrong.

Thanks!

**Comment by fsb4000** [comment]
I confirm the issue on  current preview 19.33.31424

Also the bug is reproduced on x86 Native build, x86_64 Cross tools.
But the repro works fine on x64 Native build:

![изображение](https://user-images.githubusercontent.com/4289847/168570354-b4c3eb18-95b4-4abf-bfbd-8d48d3b2de4a.png)

![изображение](https://user-images.githubusercontent.com/4289847/168570399-b6a5c092-cc37-42af-a7ba-f6c6e914eeab.png)

**Comment by StephanTLavavej** [comment]
This also repros for me with 17.3 Preview 1 x86, but works properly with our current development build (prod/fe x86chk) - so it's very likely that this is a compiler bug that's already been fixed (I'd say 98%), and the fix will likely appear in 17.3 Preview 2 (I'd say 90%) which will be the first 17.3 preview with compiler changes. Small chance that this was fixed *recently* for 17.3 Preview 3. I'll leave this bug open for now until we can confirm the fix in a public Preview.

Thank you for the bug report - header units *should* work, and we have test coverage to ensure that they keep working, but we must have missed something here for some time.

**Comment by fsb4000** [comment]
> the fix will likely appear in 17.3 Preview 2 (I'd say 90%) 

@StephanTLavavej  you are correct. The repro works for me now, so the issue could be closed.

![изображение](https://user-images.githubusercontent.com/4289847/175048239-b42bfbf3-c15d-48e8-91fa-479beebdae35.png)
![изображение](https://user-images.githubusercontent.com/4289847/175048368-0e086e26-aaf0-48aa-9301-645e4cdad8fb.png)

**Comment by fsb4000** [comment]
Someone faced the same problem in DevCom-10076720

**Comment by StephanTLavavej** [comment]
Thanks for verifying, @fsb4000!
