### ISSUE TITLE
xlock.cpp: Should _Lock_at_thread_exit_mutex() be noexcept?

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#273]
`_Lock_at_thread_exit_mutex()` and `_Unlock_at_thread_exit_mutex()` are separately compiled, but aren't used outside the STL's DLL (or static LIB):

https://github.com/microsoft/STL/blob/f9b1dccd121b5f8bb76d06adb0c85aac3f766326/stl/src/xlock.cpp#L123-L129
https://github.com/microsoft/STL/blob/f9b1dccd121b5f8bb76d06adb0c85aac3f766326/stl/src/xnotify.cpp#L31-L34

Since they aren't exported, I believe that it would be safe (i.e. binary-compatible) to mark them as `noexcept`, and give them C++ linkage.

It's also possible that there's no point in doing so; because they're `extern "C"` and we compile with `/EHsc`, they should already be treated as `noexcept`.

**Comment by BillyONeal** [comment]
No, they should be deleted :)

**Comment by StephanTLavavej** [comment]
For vNext, or can that be done in v19?

**Comment by BillyONeal** [comment]
If they aren't exported should be doable in v19.

**Comment by StephanTLavavej** [comment]
What would deletion involve? (i.e. what additional code would be necessary to replace this mechanism?)

**Comment by BillyONeal** [comment]
Would probably hook it into the existing locale lock system. Even just moving this stuff into the one .cpp where it's currently used would be an improvement.

**Comment by StephanTLavavej** [comment]
#4106 actually made them `noexcept`.
