### ISSUE TITLE
`expected<void, E>` move assignment should `move()`

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#2731]
* Good: https://eel.is/c++draft/expected.void.assign#4.2
  + > `construct_at(addressof(unex), std::move(rhs.unex));`
* Bad: https://eel.is/c++draft/expected.void.assign#4.4
  + > Otherwise, equivalent to `unex = rhs.error()`.

I believe this should say `std::move(rhs.error())` (or perhaps `std::move(rhs.unex)`). We should file an LWG issue.

**Comment by frederick-vs-ja** [comment]
This is LWG-3687 (although its title is currently wrong) and already set to "Tentatively Ready" now.
