### ISSUE TITLE
`expected::error()` is inconsistently `noexcept`

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#2733]
WG21-N4910 [expected.object.general] class definition:

```cpp
constexpr const E& error() const &;
constexpr E& error() &;
constexpr const E&& error() const &&;
constexpr E&& error() &&;
```

[expected.object.obs]/12, /14:
```cpp
constexpr const E& error() const & noexcept;
constexpr E& error() & noexcept;
constexpr E&& error() && noexcept;
constexpr const E&& error() const && noexcept;
```

This appears to be an editorial issue - if [expected.object.obs] has decided that they should be `noexcept` regardless of *Preconditions*, then the class definition should match.

---

[expected.void.general] class definition:

```cpp
constexpr const E& error() const &;
constexpr E& error() &;
constexpr const E&& error() const &&;
constexpr E&& error() &&;
```

[expected.void.obs]/5, /7:

```cpp
constexpr const E& error() const &;
constexpr E& error() &;
constexpr E&& error() &&;
constexpr const E&& error() const &&;
```

These consistently omit `noexcept`, but it makes no sense that the partial specialization would differ from the primary template here. This appears to be worthy of an LWG issue.

I did a quick search and didn't see existing issues covering this.

**Comment by frederick-vs-ja** [comment]
This has been fixed editorially (cplusplus/draft#5381).
