### ISSUE TITLE
<format>: call to immediate function is not a constant expression

### ISSUE THREAD

**Issue by nickmoss-2** [microsoft/STL#2745]
**Describe the bug**
When calling std::format through a variadic function passing a std::string_view initialised as a constexpr by value, the compiler outputs error C7595: 'std::_Basic_format_string<char,std::basic_string_view<char,std::char_traits<char>>>::_Basic_format_string': call to immediate function is not a constant expression. This does not occur when using the string in other ways, such as replacing the std::format call with 'std::cout << message;'.

**Command-line test case**
```
C:\Temp>type .\StrTest.cpp
#include <iostream>
#include <string>
#include <string_view>
#include <format>

using namespace std::string_literals;
using namespace std::string_view_literals;

constexpr inline std::string_view TestFormat = "Test {}."sv;

template<typename... Args>
std::string Format(const std::string_view message, Args... formatItems)
{
        return std::format(message, std::forward<Args>(formatItems)...);
}

int main()
{
        std::cout << Format(TestFormat, "message"sv);
        return 0;
}

C:\Temp>cl /W4 -std:c++20 StrTest.cpp
Microsoft (R) C/C++ Optimizing Compiler Version 19.32.31329 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

StrTest.cpp
StrTest.cpp(14): error C7595: 'std::_Basic_format_string<char,std::basic_string_view<char,std::char_traits<char>>>::_Basic_format_string': call to immediate function is not a constant expression
C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.32.31326\include\format(2963): note: failure was caused by a read of a variable outside its lifetime
C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.32.31326\include\format(2963): note: see usage of 'message'
StrTest.cpp(19): note: see reference to function template instantiation 'std::string Format<std::string_view>(const std::string_view,std::string_view)' being compiled
```
**Expected behavior**
I expect this code to compile successfully, to link successfully, and when the resultant binary is invoked, execute emitting the string 'Test message."

**STL version**
Microsoft Visual Studio Community 2022 (64-bit) - Current
Version 17.2.2

**Additional context**
This reproduces in Clang 13.0.1 on Windows using the MS standard library but did not reproduce in Clang 14 on Linux using libc++ (with the various invocations required to enable the prerelease std::format implementation in that library) - though this compiled without the error message there was an unrelated linker error that prevents the production of executable code.

**Comment by fsb4000** [comment]
It is expected and duplicate https://github.com/microsoft/STL/issues/2735
Look at https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2021/p2216r3.html
Clang will implement the same behaviour later.
You can use `std::vformat`, example: https://github.com/microsoft/STL/issues/2735#issuecomment-1133165914

**Comment by nickmoss-2** [comment]
Hi fsb4000,

Excuse me, I searched a fair bit but somehow missed the duplicate.

So, to make sure I understand correctly, C++ does not preserve the compile time constant nature of (from my example code) `TestFormat` when passing it via `Format`? A quick test suggests that it does not even with a reference, which I find surprising but am happy to accept as true with confirmation.

**Comment by fsb4000** [comment]
Hi @nickmoss-2 

yes, because 
```c++
template<typename... Args>
std::string Format(const std::string_view message, Args... formatItems)
{
        return std::format(message, std::forward<Args>(formatItems)...);
}
```
is not `consteval` / `constexpr` and format string must be known at compile time.

Yes, you passed a compile time constant but you could also pass runtime variable as argument and the function should work too.

for example this code works:
```c++
constexpr inline std::string_view TestFormat = "Test {}."sv;

template<typename... Args>
std::string Format(const std::string_view, Args... formatItems)
{
    return std::format(TestFormat, std::forward<Args>(formatItems)...);
}
```

or you can use vformat:
```c++
#include <iostream>
#include <string>
#include <string_view>
#include <format>

using namespace std::string_literals;
using namespace std::string_view_literals;

constexpr inline std::string_view TestFormat = "Test {} {}."sv;

template<typename... Args>
std::string Format(const std::string_view message, Args... formatItems)
{
    return std::vformat(message, std::make_format_args(std::forward<Args>(formatItems)...));
}

int main()
{
    std::cout << Format(TestFormat, "message"sv, 1);
    return 0;
}
```

![изображение](https://user-images.githubusercontent.com/4289847/170829276-189907cc-e236-4ef4-aa15-fadc491ddda3.png)

**Comment by nickmoss-2** [comment]
Hi fsb4000,

Thanks for the clarification, I wasn't entirely sure if it was reasonable for the compiler to trace the lifetime over the function but on reflection it was a bit of a long shot to think it would do more than allow optimisations based on that. I'll move to the compile time version until all the compilers I need to support implement `std::format` and I can remove the wrapper function.
