### ISSUE TITLE
<coroutine>: check preconditions for `resume()`, `done()`, `destroy()`

### ISSUE THREAD

**Issue by fsb4000** [microsoft/STL#2750]
Users violate preconditions of coroutine methods: Devcom-10056222 , Devcom-1251708

It would be nice to add asserts and check the violations.

I looked at LLVM: https://github.com/llvm/llvm-project/blob/09c2b7c35af8c4bad39f03e9f60df8bd07323028/libcxx/include/__coroutine/coroutine_handle.h#L154-L175

They added the asserts but they didn't implement ` bool __is_suspended() const`: https://github.com/llvm/llvm-project/blob/09c2b7c35af8c4bad39f03e9f60df8bd07323028/libcxx/include/__coroutine/coroutine_handle.h#L184-L187

I don't know how to implement the method either, this is why I'm creating the issue instead of a pull request :)

**Comment by cpplearner** [comment]
In the linked DevCom issues, the coroutine handle is accessed after the associated coroutine state is *deallocated*. It's essentially use-after-delete. I don't think we can do much in that case.

It might be easier to detect whether a coroutine handle is accessed while the coroutine is running, if the compiler exposed that information. But I agree that this requires compiler support.

**Comment by fsb4000** [comment]
oh, yes, and ASAN detects that.
I added to Devcom-10056222 info about ASAN.

**Comment by CaseyCarter** [comment]
I talked with the coroutine maintainer on MSVC's compiler front-end team to validate my suspicion that there's way for us to detect whether a coroutine is suspended. We update the coroutine frame at suspension to indicate where the coroutine should resume, but there is no state change upon resumption. Consequently "coroutine suspended at X" and "coroutine that resumed at X and hasn't yet suspended" are not differentiable even with compiler assistance.

We could theoretically break ABI and add a bit somewhere that's atomically flipped on suspend/resume to make it possible to implement an "is this coroutine suspended?" intrinsic, but paying a cost in runtime performance to enhance debuggability seems distinctly non-C++. I doubt _any_ compiler would willingly pay this cost in release builds, and at least MSVC has been reluctant to have different ABI for language features in debug vs. release.

I find it very unlikely that we'll ever be able to do anything in this space, so I'm going to close this STL issue. Feel free to file a feature suggestion for the compiler on Developer Community if you disagree with my analysis, or to argue here for reopening this issue if you think there's something we could usefully achieve in the library without the ability to determine if a coroutine is suspended.
