### ISSUE TITLE
<atomic>: Memory perf: unused 16k buffer in .data when using std::atomic::wait on Windows 8 and later.

### ISSUE THREAD

**Issue by PDeets** [microsoft/STL#2755]
**Describe the bug**
I just investigated a memory regression in my code which was due to two of my DLLs taking a new dependency on `std::atomic::wait`. I used SizeBench to track it down to a 16k table in `_Atomic_wait_table_entry` which is unused on Windows 8 and later.

When using `__std_atomic_api_level::__has_srwlock`, `atomic::wait` uses a table in `_Atomic_wait_table_entry`. This table is 16k in size. Since it is read-write, there is a separate copy of the table taking up space each time the DLL is loaded in a separate process. (My DLLs link to the STL statically.) In this scenario, there were two DLLs using `std::atomic::wait` loaded into two processes; so there were 4 copies of the table in memory.

The thing is, the table is not needed when `_Init_wait_functions` returns `__has_wait_on_address`. It would be nice if you’d dynamically allocate the table during `_Init_wait_functions` only when it is needed (for example, on Windows 7) instead of storing it in the .data section of the PE file. If the dynamic allocation fails, you could always fall back to using a single static `_Wait_table_entry` for all waits.

**Command-line test case**
Build optimized code that statically links to the STL without usage `std::atomic::wait` and with usage of `std::atomic::wait`. Compare the two binaries using SizeBench (https://apps.microsoft.com/store/detail/sizebench/9NDF4N1WG7D6?hl=en-us&gl=US). There is an extra 16k buffer in the .data section when `std::atomic::wait` is used.

**Expected behavior**
There is not 16k memory overhead each time my DLL is loaded into a separate process for Win7 support code when running on Windows 8 or later. (The 16k overhead is fine if I'm actually running on Windows 7 though; so I'm OK with doing dynamic allocation when the memory is actually needed.)

**STL version**
```
Microsoft Visual Studio Enterprise 2022 (64-bit) - Current
Version 17.2.3
```

**Comment by StephanTLavavej** [comment]
It appears that the wait table is used on Win8+ for non-1/2/4/8 sizes:

https://github.com/microsoft/STL/blob/17fde2cbab6e8724d81c9555237c9a623d7fb954/stl/inc/xatomic_wait.h#L48-L50

I assume it's still possible to defer allocation of the table unless/until it is needed, but possibly at the cost of an additional atomic variable?

**Comment by PDeets** [comment]
Makes sense. I had missed that. Given this new info, I agree this would take a second atomic variable for initialing the pointer to the buffer on-demand. My program only uses 4-byte and 8-byte atomics; so I wouldn't hit this code except when running on Win7.

**Comment by AlexGuteniev** [comment]
Atomic wait contributor here.

> It would be nice if you’d dynamically allocate the table during `_Init_wait_functions` only when it is needed (for example, on Windows 7) instead of storing it in the .data section of the PE file. If the dynamic allocation fails, you could always fall back to using a single static `_Wait_table_entry` for all waits.

I'm not convinced it would be a good optimization given the minimal amount of potential gain (a couple of memory pages that would page out anyway if unused), and noticeable complexity added (more code branches).

Atomic stuff is complex already so we don't want to complicate it further. E.g. originally the case of odd size on Win8+ and the Win7 case were handled differently, the Win8+ odd-size implementation was removed for simplicity during PR review.

**Comment by AlexGuteniev** [comment]
Having allocated table has some potential benefits if used though:
 * Table can be sized dynamically based on the current hardware concurrency support
 * Table can be allocated in a named mapping private to the process, this way even statically linked STL instances will share it

But these benefits would cost even more complexity

**Comment by PDeets** [comment]
If you decide to keep the static buffer, I'd recommend that you at least try updating the `_Wait_table_entry` class to initialize all members to 0 on construction with the goal of eliminating the binary size difference even if the memory overhead is still there. This would remove 512 relocations in the DLL when it is loaded. Also, by having it all be zeros, the linker might take advantage of the PE file format where if you put the data at the end of the .data section, it doesn't have to be included in the file. This might shrink the actual file size by 16k even if you still commit the 16k at runtime.

I think this would just involve updating the linked list traversal code to check for null to find the end of the list instead of checking for a loop back around to the head.

Also, I think the `_Storage`, `_Prev`, and `_Condition` members are never used in the head; so you could potentially eliminate them without adding any code complexity if the prev pointers pointed to the next pointer instead of to an actual `_Wait_context`. This would cut the table sized down from 16k to 4k. (The array is currently an array of 40 bytes entries with 24 bytes of padding between each entry. Removing these three unused members would make it an array of 16 byte entries with 0 bytes of padding between each entry.)

**Comment by PDeets** [comment]
My last paragraph was incorrect due to the usage of `alignas(_STD hardware_destructive_interference_size)`. This code is intentionally padding to 64 bytes per entry; so shrinking the entries to 16 bytes wouldn't shrink the array. The point about initializing members to 0 to eliminate the relocs still stands though.

**Comment by AlexGuteniev** [comment]
> I think this would just involve updating the linked list traversal code to check for null to find the end of the list instead of checking for a loop back around to the head.

Another way of achieving this would be to keep traversal/insertion/deletion code as is, but delay nonzero initialization of `_Wait_list_head`. This looks more appealing, as does not introduce branches in insertion/deletion, and, as you noted later, it does not save the size if we avoid `_Prev` in head. 

To me this indeed looks a worth improvement, as it does not introduce behavior difference for different cases.

**Comment by AlexGuteniev** [comment]
Actually can indeed switch to single linked, for which null termination is natural

**Comment by StephanTLavavej** [comment]
We talked about this at the weekly maintainer meeting and we'd be happy to review a PR here - @AlexGuteniev, feel free to choose the best approach (whether that's a singly linked list or something else).

**Comment by AlexGuteniev** [comment]
> I assume it's still possible to defer allocation of the table unless/until it is needed, but possibly at the cost of an additional atomic variable?

No extra atomic variable would be needed, it would be always under `_SrwLock_guard _Guard(_Entry._Lock);`.

**Comment by AlexGuteniev** [comment]
> > I assume it's still possible to defer allocation of the table unless/until it is needed, but possibly at the cost of an additional atomic variable?
> 
> No extra atomic variable would be needed, it would be always under `_SrwLock_guard _Guard(_Entry._Lock);`.

Actually, **yes**, because to lock that mutex we need an entry in the first place

**Comment by AlexGuteniev** [comment]
💡  I have an idea
