### ISSUE TITLE
STL: Should checks for self-move-assignment be removed?

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#276]
We often check for self-move-assignment:

https://github.com/microsoft/STL/blob/f9b1dccd121b5f8bb76d06adb0c85aac3f766326/stl/inc/memory#L1858-L1859
https://github.com/microsoft/STL/blob/f9b1dccd121b5f8bb76d06adb0c85aac3f766326/stl/inc/vector#L664-L665

According to https://eel.is/c++draft/res.on.arguments#1.3 , "If a function argument binds to an rvalue reference parameter, the implementation may assume that this parameter is a unique reference to this argument."

Note: self-move-assignment is a tricky question. I can never remember if implementers are supposed to consider it a precondition violation, or if they're supposed to tolerate it and leave the object in a "valid but unspecified" state.

**Comment by Mike-Devel** [comment]
Related discussion on boost container: https://github.com/boostorg/container/issues/88

Not sure what the standard mandates,  but as a bare minimum, please keep self swap (`std::swap(x,x)`) working.

**Comment by StephanTLavavej** [comment]
Self-swap definitely has to work because its arguments are lvalue references, no worries 😸

**Comment by MikeGitb** [comment]
Yes, but the naive implementation (didn't 
check the STL implementation) does a self, move assignment internally.

**Comment by Mike-Devel** [comment]
Yes, that's what I was referring to.

**Comment by StephanTLavavej** [comment]
Yep, I totally forgot about the MoveAssignable requirement cited in the issue you linked. So, STL types must make self-move-assign valid-but-unspecified, and self-checks are one way to achieve that. There may be places where performance can be improved, but this answers my original question. (This issue was filed as I was going through my old todo list and migrating everything to GitHub.)

**Comment by 2underscores-vic** [comment]
> There may be places where performance can be improved

Consider this implementation for classes with `swap()` member:

    Class& operator=(Class&& _Right) noexcept {
        this->swap(_Right);
        return *this;
    }

No need for self-move-assignment check.
