### ISSUE TITLE
`<filesystem>`: Resize files in a better way

### ISSUE THREAD

**Issue by AlexGuteniev** [microsoft/STL#2767]
Currently `<filesystem>` and its experimental ancestor use `SetFilePointerEx` + `SetEndOfFile`:

https://github.com/microsoft/STL/blob/17fde2cbab6e8724d81c9555237c9a623d7fb954/stl/src/filesys.cpp#L418-L430
https://github.com/microsoft/STL/blob/17fde2cbab6e8724d81c9555237c9a623d7fb954/stl/src/filesystem.cpp#L696-L702

The modern way, which is supported starting in Windows Vista is `SetFileInformationByHandle` with `FILE_END_OF_FILE_INFO`.
It would make fewer kernel calls and cleaner code.

Probably should wait till #2766 is handled to avoid conflicts.

**Comment by AtariDreams** [comment]
Resolved in #2766
