### ISSUE TITLE
<deque>: For allocators where allocator_traits<T>::pointer is an object, destructors aren't always called

### ISSUE THREAD

**Issue by nicolasjinchereau** [microsoft/STL#2769]
When using a custom allocator that defines `allocator_traits<T>::pointer` as a class or struct, `std::deque` constructs more instances of that `pointer` object than it destroys. So if `pointer` has non-trivial constructors or destructors, some destructors will not be called.

```
> cl repro.cpp /std:c++latest

#include <type_traits>
#include <cstdio>
#include <cstdlib>
#include <compare>
#include <iterator>
#include <deque>

int numPtrs = 0;

template<class T>
class FancyPointer
{
    T* p{};

    template<class U>
    friend class FancyPointer;

    template<class U> requires std::is_convertible_v<U*, T*>
    FancyPointer(U* p)
        : FancyPointer()
    {
        this->p = p;
    }
    
    template<class U>
    friend class FancyAllocator;
public:
    
    using value_type = T;
    using pointer = FancyPointer<T>;
    using difference_type = ptrdiff_t;
    using iterator_category = std::random_access_iterator_tag;

    template<class U = T> requires (!std::is_void_v<U>)
    using reference = U&;

    FancyPointer() {
        ++numPtrs;
    }

    ~FancyPointer() {
        --numPtrs;
    }

    FancyPointer(const FancyPointer& fp)
        : FancyPointer()
    {
        p = fp.p;
    }

    FancyPointer(FancyPointer&& fp)
        : FancyPointer()
    {
        p = fp.p;
        fp.p = nullptr;
    }

    template<class U> requires std::is_convertible_v<U*, T*>
    FancyPointer(const FancyPointer<U>& fp)
        : FancyPointer()
    {
        p = fp.p;
    }

    FancyPointer(std::nullptr_t)
        : FancyPointer()
    {
        p = nullptr;
    }

    FancyPointer& operator=(const FancyPointer& fp) {
        p = fp.p;
        return *this;
    }

    template<class U> requires std::is_convertible_v<U*, T*>
    FancyPointer& operator=(const FancyPointer<U>& fp) {
        p = fp.p;
        return *this;
    }
    
    FancyPointer& operator=(FancyPointer&& fp) {
        p = fp.p;
        fp.p = nullptr;
        return *this;
    }

    FancyPointer& operator=(std::nullptr_t) {
        reset();
        return *this;
    }

    T* get() const {
        return p;
    }

    void reset() {
        p = nullptr;
    }

    explicit operator bool() const {
        return p != nullptr;
    }

    T* operator->() const {
        return p;
    }

    template<class U = T> requires (!std::is_void_v<U>)
    U& operator*() const {
        return *p;
    }

    template<class U = T> requires (!std::is_void_v<U>)
    U& operator[](ptrdiff_t index) const {
        return p[index];
    }

    FancyPointer& operator++() {
        ++p;
        return *this;
    }

    FancyPointer operator++(int) {
        auto tmp = *this;
        ++p;
        return tmp;
    }

    FancyPointer& operator--() {
        --p;
        return *this;
    }

    FancyPointer operator--(int) {
        auto tmp = *this;
        --p;
        return tmp;
    }

    FancyPointer& operator+=(ptrdiff_t off) {
        p += off;
        return *this;
    }

    FancyPointer& operator-=(ptrdiff_t off) {
        p -= off;
        return *this;
    }

    FancyPointer operator+(ptrdiff_t off) const {
        return { p + off };
    }

    FancyPointer operator-(ptrdiff_t off) const {
        return { p - off };
    }

    ptrdiff_t operator-(const FancyPointer& fp) const {
        return { p - fp.p };
    }

    template<class U> requires (!std::is_void_v<U> && std::is_same_v<U, T>)
    static FancyPointer<U> pointer_to(U& u) {
        return { &u };
    }

    template<class T2>
    bool operator==(const FancyPointer<T2>& right) const {
        return get() == right.get();
    }

    bool operator==(std::nullptr_t) const {
        return get() == nullptr;
    }

    template<class T2>
    std::strong_ordering operator<=>(const FancyPointer<T2>& right) {
        return get() <=> right.get();
    }

    std::strong_ordering operator<=>(std::nullptr_t) {
        return get() <=> nullptr;
    }
};

template <class T>
class FancyAllocator
{
public:
    using value_type = T;
    using pointer = FancyPointer<T>;
    using const_pointer = FancyPointer<const T>;
    using difference_type = ptrdiff_t;
    using size_type = std::size_t;

    template <class U>
    struct rebind {
        using other = FancyAllocator<U>;
    };

    FancyAllocator() {}
    ~FancyAllocator() {}

    template<class U>
    FancyAllocator(const FancyAllocator<U>& that) {}

    pointer allocate(size_type n) {
        void* p = ::operator new(n * sizeof(T), std::align_val_t(alignof(T)));
        return pointer{ static_cast<T*>(p) };
    }

    void deallocate(pointer fp, size_type n) {
        ::operator delete(fp.p, std::align_val_t(alignof(T)));
    }

    FancyAllocator select_on_container_copy_construction() const {
        return *this;
    }

    using propagate_on_container_copy_assignment = std::false_type;
    using propagate_on_container_move_assignment = std::true_type;
    using propagate_on_container_swap = std::true_type;
    using is_always_equal = std::true_type;
};

template <class T1, class T2>
inline bool operator==(const FancyAllocator<T1>& a, const FancyAllocator<T2>& b) noexcept {
    return true;
}

template <class T1, class T2>
inline bool operator!=(const FancyAllocator<T1>& a, const FancyAllocator<T2>& b) noexcept {
    return false;
}


int main(int argc, char* argv[])
{
    {
        std::deque<int, FancyAllocator<int>> stuff;
        stuff.push_back(1);
    }

    printf("FancyPointers (should be zero) : %d\n", numPtrs);
    return 0;
}
```

**Results**

`FancyPointer` has a counter in the constructor and destructor to count the number of live instances. After the `deque` has been destroyed, the counter should be zero, showing that all `FancyPointer` destructors have run correctly. However, the program outputs '7'. If `std::deque` in the above program is replaced with `std::list` or `std::vector`, the program will output '0' as expected.

**STL version**
Microsoft Visual Studio Enterprise 2022 (64-bit) - Preview
Version 17.3.0 Preview 1.1

**Comment by StephanTLavavej** [comment]
I believe that this is clearly a bug - thanks for the report! Over time, we overhauled `vector` etc. to respect fancy pointers, but we must have missed `deque` (which does fairly complicated things with its "map" of block pointers).

**Comment by MattStephanson** [comment]
I don't know how to properly solve it, but to save some debugging effort, I think this is at least one issue: all the block pointers in the map are constructed, even if they're empty, but are only destroyed if they're non-empty. The map size in this example is 8, so the pointer to the one used block gets destroyed and the other 7 don't.

https://github.com/microsoft/STL/blob/17fde2cbab6e8724d81c9555237c9a623d7fb954/stl/inc/deque#L1486-L1495

**Comment by CaseyCarter** [comment]
Do we want to fix this by ensuring that all pointers are constructed and destroyed via the allocator, or do we want to _really_ fix it by never constructing nor destroying pointers via the allocator?

**Comment by MattStephanson** [comment]
> Do we want to fix this by ensuring that all pointers are constructed and destroyed via the allocator, or do we want to _really_ fix it by never constructing nor destroying any pointers via the allocator as the Standard requires?

The call to `_Destroy_in_place` isn't going through the allocator anyway. As I understand it, in at least some cases the deque's map must refer to the blocks using the allocator's fancy `pointer` type, and the issue here is that those fancy pointers aren't being destroyed *at all*.

**Comment by StephanTLavavej** [comment]
We talked about this at the weekly maintainer meeting and we believe that it should be safe to fix this to follow the Standardese - we should use `construct()`/`destroy()` provided by the allocator (via `allocator_traits`) only for container elements, never other types. (As @MattStephanson mentioned, we already appear to be doing this correctly - @CaseyCarter thinks he might have led us astray here temporarily. :joy_cat:) For the fancy pointers, we should directly construct and destroy them in a balanced manner, regardless of their nullness.

**Comment by MattStephanson** [comment]
> we should use `construct()`/`destroy()` provided by the allocator (via `allocator_traits`) only for container elements, never other types [...] (we already appear to be doing this correctly)

On that part @CaseyCarter is right. I noticed during debugging that the allocator is also used for the map and the container proxy:
https://github.com/microsoft/STL/blob/17fde2cbab6e8724d81c9555237c9a623d7fb954/stl/inc/deque#L587-L593

https://github.com/microsoft/STL/blob/17fde2cbab6e8724d81c9555237c9a623d7fb954/stl/inc/deque#L1442-L1455

etc.

**Comment by StephanTLavavej** [comment]
We need to *allocate* the map and the proxy with the user-provided allocator (as all persistent allocations must respect this) - it's `construct()` and `destroy()` that should be specific to the elements. (Allocators are weird.)

**Comment by MattStephanson** [comment]
Ah, I was pretty sure I was missing *something*. Thanks.
