### ISSUE TITLE
`<format>`: File an LWG issue to fix `basic_format_arg`'s constructors

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#2778]
After merging #2768, we should file an LWG issue recommending our chosen approach to fixing `basic_format_arg`'s constructors, as mentioned by https://github.com/microsoft/STL/pull/2768#discussion_r892950656. As @CaseyCarter noted, [P2418R2](https://wg21.link/P2418R2) "was very rushed, and did some damage to the wording".

**Comment by frederick-vs-ja** [comment]
LWG-3718 has been filed. But I proposed a possibly different resolution (that behaves same as the current implementation in normal cases, though)...
