### ISSUE TITLE
<algorithm>: Consider using iter[idx] for clarity

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#278]
The heap algorithms repeatedly say `*(iter + idx)` when `iter[idx]` would probably be easier to read. (Because of our iterator unwrapping logic, this usually shouldn't make a performance difference.) After searching the entire STL, the three affected functions that I see are:

https://github.com/microsoft/STL/blob/f9b1dccd121b5f8bb76d06adb0c85aac3f766326/stl/inc/algorithm#L2577-L2590
https://github.com/microsoft/STL/blob/f9b1dccd121b5f8bb76d06adb0c85aac3f766326/stl/inc/algorithm#L2612-L2638
https://github.com/microsoft/STL/blob/f9b1dccd121b5f8bb76d06adb0c85aac3f766326/stl/inc/algorithm#L2672-L2683

**Comment by StephanTLavavej** [comment]
Note that we format our source code with clang-format (currently 9.0.0) and have automated checks for this. Changing this code to use `operator[]` will have clang-format impact, due to the alignment of consecutive assignment statements.

**Comment by BillyONeal** [comment]
Hmmm I'm not sure about this; I'm concerned about in-the-wild iterators that don't have operator[]s..

**Comment by StephanTLavavej** [comment]
Such iterators wouldn’t conform to the random-access iterator requirements, and are doomed in a concepts-powered world.

**Comment by BillyONeal** [comment]
All of our existing customers are not in a concepts powered world. There's a reason we are putting concepts powered world into `std::ranges`.

**Comment by StephanTLavavej** [comment]
Fair enough. However, I argue that this will be a minor source breaking change; user-defined iterators are rare, they’re typically provided by expert-written libraries, and their cross-section with the heap algorithms and `priority_queue` is even smaller. I believe it will be far less of an issue than comparator constness.

**Comment by CaseyCarter** [comment]
> user-defined iterators are rare, they’re typically provided by expert-written libraries

I'm almost universally in favor of "let's break code that doesn't meet the requirements as hard as we can". That said, this statement suggests to me that breakage will be rare but fixing that breakage in "expert-written libraries" may be costly.

If we were gaining something other than a bit of code clarity I would have no doubts. As it is I'm not motivated to make a change, but could live with it if we're careful to include a "Breaking Change" release note with clear instructions on how to fix broken iterators.
