### ISSUE TITLE
<locale>: Converting UTF-8 sequences to `wchar_t`/UTF-16 surrogates impossible

### ISSUE THREAD

**Issue by Flamefire** [microsoft/STL#2788]
**Describe the bug**

When using an UTF-8 locale and trying to convert an UTF-8 sequence to a `wchar_t` sequence that would contain a surrogate pair (i.e. code points above `U+FFFF` the conversion fails.

However conversion to a `char16_t` sequence works as expected.

Shouldn't both be the same (except for the types)?

**test case**
```
#include <cassert>
#include <locale>
#include <string.h>

int main()
{
    auto* cvt = new std::codecvt_byname<wchar_t,char,std::mbstate_t>("EN_US.UTF-8");
    const std::string from = "\xf0\xa0\x82\x8a";
    std::wstring to(2, 0);
    const char* from_next;
    wchar_t* to_next;
    std::mbstate_t state{};
    auto res = cvt->in(state, &from.front(), &from.back(), from_next, &to.front(), &to.back(), to_next);
    assert(res == std::codecvt_base::ok);
}
```

**Expected behavior**
`res` should be `ok`

**STL version**
    ```
Microsoft Visual Studio Community 2022 (64-Bit) - Current
Version 17.2.3
    ```

* Option 2: git commit hash

Current HEAD also affected although different:
    ```
9947dd9d6d2506029ed4486bb7596bda7d70f99d
    ```

**Additional context**

The issue is the use of `_Mbrtowc` in the `wchar_t-codecvt`:
https://github.com/microsoft/STL/blob/9947dd9d6d2506029ed4486bb7596bda7d70f99d/stl/inc/xlocale#L1998

Which hard fails for surrogate pairs:
https://github.com/microsoft/STL/blob/9947dd9d6d2506029ed4486bb7596bda7d70f99d/stl/src/xmbtowc.cpp#L110-L115

However the comment there is wrong:
> this would result in a UTF-16 surrogate pair, which we can't emit in our singular output wchar_t, so fail. see N4750 [locale.codecvt.virtuals]/3

The `char16_t` codecvt proves that this works: https://github.com/microsoft/STL/blob/9947dd9d6d2506029ed4486bb7596bda7d70f99d/stl/inc/xlocale#L984-L988

**Comment by StephanTLavavej** [comment]
@CaseyCarter found WG21-N4910 [[locale.codecvt.virtuals]/4](https://eel.is/c++draft/locale.codecvt.virtuals#4), which by mentioning "A `codecvt` facet that is used by `basic_­filebuf`" introduces the asymmetry between `wchar_t` and `char16_t`. So, this behavior is unfortunately mandated by the Standard. :crying_cat_face:

**Comment by Flamefire** [comment]
@StephanTLavavej but isn't wchar_t effectively an utf16 encoding just like char16_t? So where does the difference come from?
Or does the "used by" part imply that the char16_t codecvt is not intended /valid for a filebuf anyway while the wchar_t version is?

I mean if one disregards the note in the quoted standard than you can have the situation where the "from+1" starts at the 2nd surrogate and hence would return "invalid". But I thought that using the state this is "fixed" as the call with "from" modifies the state in a way that "from+1" can succeed (i.e. store the first char)

**Comment by StephanTLavavej** [comment]
According to my understanding, the asymmetry is introduced because `wfilebuf` is specifically for `wchar_t`, not `char16_t`.

**Comment by Flamefire** [comment]
That makes `basic_filebuf<char16_t>` invalid, doesn't it? That would use the UTF-16 codecvt which isn't allowed to be used for a filebuf.
I also found https://github.com/sg16-unicode/sg16/issues/9 for a discussion about Windows APIs (for a while now) accepting UTF-16 while C++ APIs on Windows assume UCS-2 (which on paper doesn't exist anymore)

Standard text aside: Is there actually anything in the MS STL `std::basic_filebuf` assuming single-value `wchar_t`? I.e. would anything actually break if the UTF-16 codecvt was used there (after adjusting the types of course)?
