### ISSUE TITLE
<format>: invalid format strings lead to internal failures in the header (constexpr violations)

### ISSUE THREAD

**Issue by fredemmott** [microsoft/STL#2800]
**Describe the bug**

 `std::format('{}}', 123)` hits this code inside a constexpr:

```
                    _THROW(format_error("Unmatched '}' in format string."));
```

This is not valid:

```
error C7595: 'std::_Basic_format_string<char,int>::_Basic_format_string': call to immediate function is not a constant expression
   C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\format(1017,21): note: failure was caused by evaluating a throw sub-expression
```

Looking through the header, this seems to be a fairly widespread issue - `_THROW(format_error())` is called from several constexpr functions. For example, `{:99999999d}` also fails with "call to immediate function is not a constant expression" instead of the apparently intended "Invalid fill (too long)." error.

It would be great for usability if the error strings in the code were directly reported to the user as compile errors - maybe something like this:

```C+++
if constexpr (std::is_constant_evaluated()) {
  static_assert(false, "Unmatched '}' in format string."));
} else {
  _THROW(format_error("Unmatched '}' in format string."));
}
```

**Command-line test case**
```
c:\Users\Fred>type test.cpp
#include <format>

int main() {
  std::format("{}}", 123);
  return 0;
}

c:\Users\Fred>cl.exe /std:c++20 test.cpp
Microsoft (R) C/C++ Optimizing Compiler Version 19.32.31329 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

test.cpp
test.cpp(4): error C7595: 'std::_Basic_format_string<char,int>::_Basic_format_string': call to immediate function is not a constant expression
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\format(1017): note: failure was caused by evaluating a throw sub-expression
test.cpp(4): warning C4834: discarding return value of function with 'nodiscard' attribute

c:\Users\Fred>
```

**Expected behavior**

* The header should not use non-constexpr functions for error reporting in constexpr-contexts
* Compile-time-detected errors should be surfaced as compile errors with informative text.

**STL version**

```
Microsoft Visual Studio Community 2022 (64-bit) - Current
Version 17.2.4
```

**Comment by fredemmott** [comment]
FYI, https://github.com/microsoft/STL/commit/2f7bfce86965d01d2eb5d270e9d12db8adf02a00 touch this, but doesn't appear to fix it

**Comment by sylveon** [comment]
The suggested fix is unfortunately not possible, as the compiler will fail any `static_assert(false)` it sees, even if guarded behind a condition, a separate method or made dependent on a templated type. Meanwhile, it only fails `throw` within a constant expression if the code attempts to actually run that throw expression at compile-time. The following doesn't build:
```cpp
#include <type_traits>
#include <stdexcept>

template<typename T>
struct always_false {
    static constexpr bool value = false;
};

template<typename T>
constexpr T test(T x) {
    if (x == 42) {
        if (std::is_constant_evaluated()) {
            static_assert(always_false<T>::value);
        } else {
            throw std::runtime_error("Invalid");
        }
    } else {
        return x;
    }
}

int main() {
    test<int>(43);
}
```

Note that `std::is_constant_evaluated()` within `if constexpr` always gives `true`, it needs a normal if. MSVC warns as such:
```
warning C5063: 'std::is_constant_evaluated' always evaluates to true in manifestly constant-evaluated expressions
```

Because of the aforementioned problem, `throw` is the typical pattern to report non-recoverable failures within `constexpr` methods. I feel like the fix here would be an improved diagnostic from the compiler (alternatively, just using `/diagnostics:caret` on the consumer side would make it much more obvious what's happening). It would also help a bunch of third-party code doing similar.

**Comment by fredemmott** [comment]
> even if guarded behind a condition

:'( also locally checked this is still the case for `if constexpr`

**Comment by frederick-vs-ja** [comment]
I don't think this can be fixed in a library implementation. IMO a core language mechanism is needed to customize the error message for constant evaluation failure, like WG21-P2573.

**Comment by fredemmott** [comment]
Thanks for looking - and for the wchar_t compile-time checking, and std::chrono coverage :)
