### ISSUE TITLE
More minmax vectorization

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#2803]
Followup issue after merging #2447.

* [x] Vectorize `ranges::min_element`, `ranges::max_element`, `ranges::minmax_element`
  + This should be similar to vectorizing `ranges::count`, as we should be able to call the same `vector_algorithms.cpp` functions after dealing with the iterator/sentinel. (Unlike `ranges::find`, we don't need to worry about unbounded ranges.)

And as @AlexGuteniev explained, we can go even further:

* [x] Vectorize `ranges::min`, `ranges::max`, `ranges::minmax`
  + These algorithms return values instead of iterators, so they can be simpler and faster, and "will consist only of vertical max and one reduction".
* [ ] Use AVX2.

#2439 tracks extending the optimization to floating-point types.

**Comment by AlexGuteniev** [comment]
An observation.
We have an implementation that uses `minmax_element` and implementation that just goes just iteratively, saving minmax values. The later might auto-vectorize, in this case we can avoid separately compiled impl

https://github.com/microsoft/STL/blob/ed8150e099f6124c50dd4f002cd2ab8c429a81e3/stl/inc/xutility#L7002-L7011
