### ISSUE TITLE
`cthread.cpp`: unnecessary OS call

### ISSUE THREAD

**Issue by AlexGuteniev** [microsoft/STL#2817]
`_Thrd_join` optionally fills `code` output parameter:
https://github.com/microsoft/STL/blob/7f04137880e1c3df5125c1baf808f16f399dee2e/stl/src/cthread.cpp#L55-L66

If this parameter is not requested, an unnecessary OS call performed.
It is never requested - the only call site passes `nullptr`:
https://github.com/microsoft/STL/blob/7f04137880e1c3df5125c1baf808f16f399dee2e/stl/inc/thread#L130-L132

**Comment by StephanTLavavej** [comment]
We may want to explore the source code history to verify that there were no *previous* callers passing non-null here.

**Comment by AlexGuteniev** [comment]
VS 2015 has in `<threads.h>`:
```c
#define thrd_join(thr, res)		_Thrd_join(thr, res)
```

I can't find this file in VS 2022, but still looks like `thrd_join` is a public API that was previously published.

Still we can put `GetExitCodeThread` under `code` condition.
