### ISSUE TITLE
<filesystem>: `filesystem::read_symlink` ignores junctions

### ISSUE THREAD

**Issue by strega-nil-ms** [microsoft/STL#2818]
### Discussed in https://github.com/microsoft/STL/discussions/2809

<div type='discussions-op-text'>

<sup>Originally posted by **operatios** June 21, 2022</sup>
I do understand that symbolic links and junctions are different, still, they both point to a target. For example, as a user, I expected to be able to successfully read both `"C:\Users\All Users"` (a symbolic link)  and `"C:\Users\Default User"` (a junction).

After looking at the source code: https://github.com/microsoft/STL/blob/7f04137880e1c3df5125c1baf808f16f399dee2e/stl/src/filesystem.cpp#L515 I see that only `IO_REPARSE_TAG_SYMLINK` is checked, and in case of junctions (tag value `IO_REPARSE_TAG_MOUNT_POINT`), an error `ERROR_REPARSE_TAG_INVALID` is returned. This would be fine if there existed a function like `read_junction`, but as far as I am aware, there is none.

This feels weird to me since other in programming languages like Python, Rust and Go you are able to successfully read both junctions and symbolic links on Windows. Here is a reference to their implementations, if needed: Python's [os.readlink](https://github.com/python/cpython/blob/0efe3a1636c143fe0694a8e4d25d6eae19e0d618/Modules/posixmodule.c#L8692), Rust's [fs::read_link](https://github.com/rust-lang/rust/blob/17c6bde14eabdd61c35505ed6834ee9196c2fdc9/library/std/src/sys/windows/fs.rs#L506) and Go's [os.Readlink](https://github.com/golang/go/blob/19309779ac5e2f5a2fd3cbb34421dafb2855ac21/src/os/file_windows.go#L483).

After doing some more investigation, I found that a similar question was raised as an issue in boost: boostorg/filesystem#125 and later was [fixed](https://github.com/boostorg/filesystem/pull/100). I am just not sure whether this is a bug or not, since libc++'s `read_symlink` also does not support junctions.

Is this something that is not allowed by the C++ Standard, or is there another reason?
</div>

### Other questions?

* What do we do about other types of reparse points, like app execution aliases?

**Comment by AlexGuteniev** [comment]
I think that preferably they should be supported, though it is not mandatory.

If they are handled in `read_symlink` and `copy_symlink`, `is_symlink` and `symlink_status` should support them too.
