### ISSUE TITLE
`<cvt/meow>`: Remove the `cvt` subdirectory

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#282]
The [`cvt` subdirectory](https://github.com/microsoft/STL/tree/f9b1dccd121b5f8bb76d06adb0c85aac3f766326/stl/inc/cvt) contains extension headers providing code conversion machinery. I believe they're rarely used, and have an unknown number of performance and correctness issues. We should deprecate them in favor of simply calling [`MultiByteToWideChar()`](https://docs.microsoft.com/en-us/windows/win32/api/stringapiset/nf-stringapiset-multibytetowidechar) and [`WideCharToMultiByte()`](https://docs.microsoft.com/en-us/windows/win32/api/stringapiset/nf-stringapiset-widechartomultibyte), ideally removing them in vNext.

(If we didn't have this subdirectory, we wouldn't accept it as an extension now.)

**Comment by AlexGuteniev** [comment]
Deprecate every exported public symblo from it.

**Comment by StephanTLavavej** [comment]
We talked about this at the weekly maintainer meeting, and we're all in favor of deprecating `<cvt/meow>` (with an escape hatch as usual).

@AlexGuteniev's suggestion of deprecating each publicly visible top-level name (instead of attempting to deprecate each header as a whole via the old typedef trick) is a good one - thanks Alex!

**Comment by frederick-vs-ja** [comment]
Is it sufficient to deprecate the `stdext::cvt` namespace (in every header) only?

**Comment by StephanTLavavej** [comment]
Good idea. I'd prefer to deprecate every occurrence of the namespace, which is what we did for `tr1`, instead of trying to find occurrences that are always dragged in. Mentioning it on every occurrence is less confusing.

**Comment by CaseyCarter** [comment]
#3924 deprecated the contents of these headers. I'm leaving this issue open as a place to discuss when and how we should remove them.

**Comment by StephanTLavavej** [comment]
The next major version, whatever/whenever that ends up being, would be an opportunity to pursue such a removal. It would raise fewer eyebrows than a mid-cycle removal, and we could tell people to use the final release of v17 side-by-side if they've taken a difficult-to-replace dependency on this extension.

The fact that we never documented this on MSDN / Microsoft Learn should help.

**Comment by StephanTLavavej** [comment]
I talked to @MahmoudGSaleh today, and he agreed that we should remove `<cvt/meow>` after VS 2022 in the next major version of VS, aka IDE version 18.x, toolset version 14.4x, compiler version 19.4x. (This is totally distinct from the mythical vNext ABI-breaking release.) Having shipped the deprecation in at least one long-term support release (VS 2022 17.8) will have given users advance notice.
