### ISSUE TITLE
<functional>: Failed to specialize std::invoke on operator() with default argument std::source_location::current()

### ISSUE THREAD

**Issue by namniav** [microsoft/STL#2822]
**Describe the bug**
Exactly same as title: Failed to specialize `std::invoke` on types with `operator()` with default argument `std::source_location::current()`.

**Command-line test case**
```
C:\Temp>type repro.cpp
#include <source_location>
#include <functional>

int main() {
    std::invoke([](std::source_location = std::source_location::current()) {} );
}

C:\Temp>cl /std:c++latest /permissive- /W4 /WX .\repro.cpp
error C2672: 'std::invoke': no matching overloaded function found
error C2893: Failed to specialize function template 'unknown-type std::invoke(_Callable &&) noexcept(<expr>)'
note: With the following template arguments:
note: '_Callable=main::<lambda_1>'
```
godbolt link: https://godbolt.org/z/K6qjzEP4f

**Expected behavior**
The example should compile.

**STL version**
The version of "x86 msvc v19.latest" on godbold.org.

**Additional context**
1. GCC accepts the example.
2. Not only lambdas, all class types are affected.
3. Wrapping `std::source_location::current()` with custom function can fix the problem: https://godbolt.org/z/j53YsTzfb.

**Comment by fsb4000** [comment]
I almost sure it's a compiler bug but I have found a workaround.
After someone agreed with me I can reduce the repro and report it to compiler developers to DevCom.

**Comment by StephanTLavavej** [comment]
This definitely looks like a compiler bug - `source_location` has data member initializers for everything, so there should be no difference between default-init and value-init here.

**Comment by fsb4000** [comment]
I created DevCom-10080771

**Comment by AlexGuteniev** [comment]
Do we want perma-workaround, or TRANSITION?

**Comment by StephanTLavavej** [comment]
Agreed - it's reasonable to always perform value-initialization even if it's technically unnecessary.
