### ISSUE TITLE
<filesystem>: `directory_entry::clear_cache` is non-standard

### ISSUE THREAD

**Issue by cpplearner** [microsoft/STL#2838]
The `directory_entry` class has a member function `clear_cache`:
https://github.com/microsoft/STL/blob/c34f24920e463a71791c2ee3d2bed14926518965/stl/inc/filesystem#L2178-L2182

And this function is mentioned in `<yvals_core.h>` with paper number `P????R?`:
https://github.com/microsoft/STL/blob/c34f24920e463a71791c2ee3d2bed14926518965/stl/inc/yvals_core.h#L276

It appears that this function is part of the change to `<filesystem>` depicted in https://github.com/microsoft/STL/issues/232#issuecomment-887018520, but AFAIK the change did not materialize into a proposal.

Given that #232 was closed via #1343, is there still interest in this function?

**Comment by StephanTLavavej** [comment]
I am inclined to remove this non-Standard extension.
