### ISSUE TITLE
<chrono>: abs(duration) requires a duration with reduced period

### ISSUE THREAD

**Issue by barcharcraz** [microsoft/STL#2839]
consider the duration `duration<long long, ratio<INTMAX_MAX, INTMAX_MAX>>{2}`, according to the standard I believe `std::abs()` of this duration should result in exactly `duration<long long, ratio<INTMAX_MAX, INTMAX_MAX>>{2}`.

Nothing prohibits using abs on a duration whose period is not fully reduced.

abs is specified thusly:
> If d >= d.zero(), return d, otherwise return -d

here both d and -d are of the same type as d.

we implement it as:
```c++
return _Dur < duration<_Rep, _Period>::zero() ? duration<_Rep, _Period>::zero() - _Dur : _Dur;
```
here `duration<_Rep, _Period>::zero() - _Dur` is of type `common_type_t<duration<_Rep, _Period>, duration<_Rep, _Period>>` and `_Dur` is of type `duration<_Rep, _Period>`. You would think these types would be the same, however `std::common_type` is specialized for durations and this specialization reduces the period!

All this means that if the duration is not already reduced `abs` fails to compile as the two arms of that ternary end up having different types. This would actually work fine if a normal if statement was used, as the branch with the reduced period would convert back to the unreduced period upon the return statement.

I figured I should document what went wrong.

**Comment by barcharcraz** [comment]
The explination is somewhat incorrect, -d in the standard does result in reduction of the period (as uniary- returns `common_type_t<duration>`, which looks at `common_type_t<duration, duration>`)

Still the standard wording implies a conversion.

**Comment by MikeGitb** [comment]
Given the standard wording: Why is this implemented as `zero() - d` instead of `-d`?

**Comment by barcharcraz** [comment]
I am not sure. Could be the standard wording changed since we implemented it. But in any event the behavior is the same. I believe this is a standard defect and will file an LWG issue.

**Comment by CaseyCarter** [comment]
This is LWG-3741, which will likely be closed as Not a Defect.

> Given the standard wording: Why is this implemented as `zero() - d` instead of `-d`?

We write a lot of `0 - x` to avoid warnings about `-x` being non-negative when it has unsigned type. I admittedly can't see how such a warning would trigger here - maybe just cargo culting?
