### ISSUE TITLE
<valarray>: Inconsistent use of ADL

### ISSUE THREAD

**Issue by cpplearner** [microsoft/STL#285]
**Describe the bug**
Non-member functions in \<valarray> are inconsistent about whether to use ADL.

`abs` enables ADL:
https://github.com/microsoft/STL/blob/f9b1dccd121b5f8bb76d06adb0c85aac3f766326/stl/inc/valarray#L749-L752

Other functions disable ADL by qualify the function call with `_CSTD`. For example:
https://github.com/microsoft/STL/blob/f9b1dccd121b5f8bb76d06adb0c85aac3f766326/stl/inc/valarray#L834-L837

Both libstdc++ and libc++ use ADL for all these functions.

**Command-line test case**
STL version (git commit or Visual Studio version): 19.24.28218.2

```
D:\>type test.cpp
#include <valarray>

namespace ns {
    struct A {};

    A abs(A);
    A sqrt(A);
}

int main() {
    std::valarray<ns::A> a;
    (void)std::abs(a);
    (void)std::sqrt(a);
}

D:\>cl /c test.cpp
Microsoft (R) C/C++ Optimizing Compiler Version 19.24.28218.2 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

test.cpp
D:\...\valarray(836): error C2665: 'sqrt': none of the 3 overloads could convert all the argument types
D:\...\cmath(485): note: could be 'long double sqrt(long double) noexcept'
D:\...\cmath(241): note: or       'float sqrt(float) noexcept'
D:\Windows Kits\10\include\10.0.17763.0\ucrt\corecrt_math.h(485): note: or       'double sqrt(double)'
D:\...\valarray(836): note: while trying to match the argument list '(const _Ty)'
        with
        [
            _Ty=ns::A
        ]
test.cpp(11): note: see reference to function template instantiation 'std::valarray<ns::A> std::sqrt<ns::A>(const std::valarray<ns::A> &)' being compiled
```

**Expected behavior**
No error.

**Additional context**
N/A

**Comment by miscco** [comment]
That seems to indeed be a bug. From [valarray.transcend](https://eel.is/c++draft/valarray.transcend) $1:

>Requires: Each of these functions may only be instantiated for a type T to which a unique function with the indicated name can be applied (unqualified).
This function shall return a value which is of type T or which can be unambiguously implicitly converted to type T.

So each of those functions should be indeed called unqualified.
