### ISSUE TITLE
GH_000935_complex_numerical_accuracy test fails on ARM64 w/ native compiler

### ISSUE THREAD

**Issue by barcharcraz** [microsoft/STL#2857]
The test GH_000935_complex_numerical_accuracy fails on arm64 in the "fast math" configurations. The results are off by like 50 orders of magnitude, however the numbers in question are _very_ close to zero, so in absolute terms it's not that much.

My suspicion is that by asking for fast math you get different results around zero for arm64 vs SSE (perhaps differing subnormal FTZ mode). Tracking this down means basically doing a binary search through the execution of the test for when results start to diverge, and could take quite a bit of time.

There's also a bigger discussion about what testing under fast math _even means_, and how close is close enough in these tests.

This is also DevCom-10088405 / VSO-1567425 / AB#1567425.

**Comment by statementreply** [comment]
Possibly the same bug as DevCom-10088405.
My suspicion is bad codegen of `vfma_f64`. https://godbolt.org/z/8E5K5MP9K

**Comment by statementreply** [comment]
[Test result](https://discord.com/channels/737189251069771789/737189251497721887/998134333950935091) by @strega-nil-ms:
```
PS C:\Users\nimazzuc> type test.cpp
#include <arm_neon.h>
#include <cstdio>
#include <cmath>

int main() {
    constexpr double x = 2.0;
    constexpr double y = 3.0;
    constexpr double z = 4.0;
    const double expected = std::fma(x, y, z);

    const float64x1_t vx = vld1_f64(&x);
    const float64x1_t vy = vld1_f64(&y);
    const float64x1_t vz = vld1_f64(&z);
    const float64x1_t vxyz = vfma_f64(vx, vy, vz);
    const float64x1_t vzxy = vfma_f64(vz, vx, vy);
    double xyz;
    double zxy;
    vst1_f64(&xyz, vxyz);
    vst1_f64(&zxy, vzxy);

    std::printf("    vfma(x, y, z): %.17g\n", xyz);
    std::printf("    vfma(z, x, y): %.17g\n", zxy);
    std::printf("std::fma(x, y, z): %.17g\n", expected);
}
PS C:\Users\nimazzuc> .\test.exe
    vfma(x, y, z): 10
    vfma(z, x, y): 11
std::fma(x, y, z): 10
```

Per [Arm docs](https://developer.arm.com/architectures/instruction-sets/intrinsics/vfma_f64), argument order of `vfma_f64` is different from `std::fma`, and `vfma_f64(vz, vx, vy)` should return the same value as `std::fma(x, y, z)`. The contradicting test result implies bad codegen of `vfma_f64`.

**Comment by CaseyCarter** [comment]
We need to ensure that the compiler bug in `vfma_f64` is reported before closing this issue.

**Comment by StephanTLavavej** [comment]
I've filed internal VSO-1579856 "Silent bad codegen in the `vfma_f64` intrinsic for ARM64" with @strega-nil-ms's test case and @statementreply's analysis.
