### ISSUE TITLE
strong_ordering with int statics fails with C2610

### ISSUE THREAD

**Issue by kasperk81** [microsoft/STL#2871]
compile with: `/std:c++latest`

```c++
namespace std {
class strong_ordering {
    int _v;
public:
    constexpr strong_ordering (int v) :_v(v) {}
    constexpr operator int (void) const { return _v; }
    constexpr bool operator== (int v) const { return _v == v; }
    constexpr bool operator< (int v) const { return _v < v; }
    constexpr bool operator<= (int v) const { return _v <= v; }
    constexpr bool operator> (int v) const { return _v > v; }
    constexpr bool operator>= (int v) const { return _v >= v; }
    constexpr bool operator== (const strong_ordering& v) const { return _v == v._v; }
    constexpr bool operator< (const strong_ordering& v) const { return _v < v._v; }
    constexpr bool operator<= (const strong_ordering& v) const { return _v <= v._v; }
    constexpr bool operator> (const strong_ordering& v) const { return _v > v._v; }
    constexpr bool operator>= (const strong_ordering& v) const { return _v >= v._v; }
    static constexpr const int less = -1;
    static constexpr const int equal = 0;
    static constexpr const int greater = 1;
};
}

struct A {
    int v;
    auto operator<=> (const A& a) const = default;
}
```

fails:
```
<source>(31): error C3774: cannot find 'std::partial_ordering': Please include <compare> header
<source>(31): error C2610: 'auto A::operator <=>(const A &) const': is not a special member function or comparison operator which can be defaulted
<source>(31): note: default arguments or varargs are not allowed
ASM generation compiler returned: 2
example.cpp
1933
<source>(31): error C3774: cannot find 'std::partial_ordering': Please include <compare> header
<source>(31): error C2610: 'auto A::operator <=>(const A &) const': is not a special member function or comparison operator which can be defaulted
<source>(31): note: default arguments or varargs are not allowed
Execution build compiler returned: 2
```

godbolt: https://godbolt.org/z/E4o6MYdrG
only g++ seems to compile it so far..

**Comment by MikeGitb** [comment]
Why are you defining your own std::strong_ordering? AFAIK, you are not allowed to do that.

**Comment by kasperk81** [comment]
this is being fixed in llvm. i am not sure about its legality. do you have a reference how it's disallowed?

**Comment by fsb4000** [comment]
LLVM-56571 issue if someone needs it.

**Comment by fsb4000** [comment]
I suppose @MikeGitb is correct.
Look at https://eel.is/c++draft/expr.spaceship#8

>The three comparison category types ([[cmp.categories]](https://eel.is/c++draft/cmp.categories)) (the types std​::​strong_­ordering, std​::​weak_­ordering, and std​::​partial_­ordering) are not predefined; if the header [<compare>](https://eel.is/c++draft/compare.syn#header:%3ccompare%3e) is not imported or included prior to a use of such a class type – even an implicit use in which the type is not named (e.g., via the auto specifier ([[dcl.spec.auto]](https://eel.is/c++draft/dcl.spec.auto)) in a defaulted three-way comparison ([[class.spaceship]](https://eel.is/c++draft/class.spaceship)) or use of the built-in operator) – the program is ill-formed[.](https://eel.is/c++draft/expr.spaceship#8.sentence-1)

**Comment by MikeGitb** [comment]
> this is being fixed in llvm. i am not sure about its legality. do you have a reference how it's disallowed?

From 
https://en.cppreference.com/w/cpp/language/extending_std

> Adding declarations to std
>
> It is undefined behavior to add declarations or definitions to namespace std or to any namespace nested within std, with a few exceptions noted below. 

I I didn't see an exception that would apply to std::strong_ordering

What ate you trying to achieve anyway?

**Comment by frederick-vs-ja** [comment]
I suggest close this as "invalid" - you are not permitted to override the definition of `std::strong_ordering` (or other comparison category types). Compilers are allowed to assume that the definitions of these types in `<compare>` are consistent with their internal representations, if any.

**Comment by strega-nil-ms** [comment]
I agree with @frederick-vs-ja -- this is not _really_ a bug, and it's also _definitely_ not an STL bug. Closing as not planned.

Thanks for the report @kasperk81 ! If you still wish to report it, please do so on developer community 😄
