### ISSUE TITLE
`<yvals_core.h>`: Update the reference to P2549 to P2549R1

### ISSUE THREAD

**Issue by frederick-vs-ja** [microsoft/STL#2873]
The adopted revision of WG21-P2549 is [P2549R1](https://wg21.link/p2549r1), which only differs from R0 in some editorial changes.

We should just update the reference to it in `<yvals_core.h>`.

Code:

https://github.com/microsoft/STL/blob/ef62d3fa0b8e4e2406b9bb74e916e1ca8a1df802/stl/inc/yvals_core.h#L318

This issue is intended for a new contributor (especially one new to GitHub) to get started with the simplest possible change.

Please feel free to submit a pull request if there isn't one already linked here - no need to ask for permission! 😸

You can (and should) link your pull request to this issue using [GitHub's close/fix/resolve syntax](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
(in the PR description not the commit message)

**Comment by CaseyCarter** [comment]
No version of WG21-P2549 has yet been adopted by WG21. We may as well wait for things to be official before making updates.

**Comment by CaseyCarter** [comment]
We did, in fact, merge P2549R1 as expected.
