### ISSUE TITLE
`<ranges>`: `chunk_by_view`'s helper lambda does not specify return type

### ISSUE THREAD

**Issue by hewillk** [microsoft/STL#2889]
https://github.com/microsoft/STL/blob/ef62d3fa0b8e4e2406b9bb74e916e1ca8a1df802/stl/inc/ranges#L6258-L6260
https://github.com/microsoft/STL/blob/ef62d3fa0b8e4e2406b9bb74e916e1ca8a1df802/stl/inc/ranges#L6272-L6274

This is basically the same problem as #2888.
I don't know how to use MSVC-STL-trunk with Compiler Explorer, but the following code should be rejected incorrectly.

```cpp
#include <ranges>

struct Bool {
  Bool& operator!();
  Bool() = default;
  Bool(const Bool&) = delete;
  operator bool() { return true; };
};

int main() {
  Bool b;
  int x[] = {42};
  auto r = std::views::iota(0, 5) | std::views::chunk_by([&](auto, auto) -> Bool& { return b; });
  r.begin();
}
```

**Comment by strega-nil-ms** [comment]
Mmh, actually now that I look at the standard wording, I disagree with this issue being a bug. The specification of _`find-next`_ is:

```
ranges::next(ranges::adjacent_find(current, ranges::end(base_), not_fn(ref(*pred_))),
             1, ranges::end(base_))
```

(this being [[range.chunk.by.view]/8][])

The definition of `not_fn` ([[func.not.fn]][]) says it "Returns: A perfect forwarding call wrapper ([[func.require]][]) `g` with call pattern `!invoke(fd, call_­args...)`", i.e., that it exactly returns the return type of `!invoke(fd, call_args...)`, and thus `adjacent_find` will use _that_ type, not `bool`, to do whatever it does.

[[range.chunk.by.view]/8]: http://eel.is/c++draft/ranges#range.chunk.by.view-8
[[func.not.fn]]: http://eel.is/c++draft/func.not.fn
[[func.require]]: http://eel.is/c++draft/func.require#term.perfect.forwarding.call.wrapper

**Comment by hewillk** [comment]
> The definition of `not_fn` ([[func.not.fn]](http://eel.is/c++draft/func.not.fn)) says it "Returns: A perfect forwarding call wrapper ([[func.require]](http://eel.is/c++draft/func.require#term.perfect.forwarding.call.wrapper)) `g` with call pattern `!invoke(fd, call_­args...)`", i.e., that it exactly returns the return type of `!invoke(fd, call_args...)`, and thus `adjacent_find` will use _that_ type, not `bool`, to do whatever it does.

then lambda needs to specify return type returns `-> decltype(auto)`, which is equivalent to `->bool`, which will work.

**Comment by CaseyCarter** [comment]
[func.require]/5: "A postfix call performed on a perfect forwarding call wrapper is expression-equivalent ([[defns.expression.equivalent]](http://eel.is/c++draft/defns.expression.equivalent)) to an expression `e` determined from its call pattern cp by replacing all occurrences of the arguments of the call wrapper and its state entities with references as described in  the corresponding forwarding steps[.](http://eel.is/c++draft/func.require#5.sentence-2)"

`e` might be a glvalue, in which case expression-equivalence requires the return type of the perfect forwarding call wrapper to be `decltype(e)` and not `decay_t<decltype(e)>` as is the case for `_Rev_not_pred`. As @hewillk says, the simplest fix is for the lambda to return `decltype(auto)`.

**Comment by strega-nil-ms** [comment]
Mmh, point; so in other words, the issue is correct, but the PR is incorrect.

**Comment by hewillk** [comment]
No, the PR is correct. As I said, the two are equivalent because the return type is converted to `bool` anyway.
