### ISSUE TITLE
`<system_error>`: Several Windows system errors are not mapped

### ISSUE THREAD

**Issue by Morph1984** [microsoft/STL#2893]
**Describe the bug**
Several Windows system error codes are not mapped in syserror.cpp

https://github.com/microsoft/STL/blob/main/stl/src/syserror.cpp#L27

The description for each of the errors are as follows:
`ERROR_FILENAME_EXCED_RANGE` -> The filename or extension is too long.
`ERROR_BAD_NET_NAME` -> The network name cannot be found.
`ERROR_NO_MORE_FILES` -> There are no more files.

**Command-line test case**
```
std::errc::filename_too_long == std::error_code{ERROR_FILENAME_EXCED_RANGE, std::system_category()}; // false
std::errc::no_such_file_or_directory == std::error_code{ERROR_BAD_NET_NAME, std::system_category()}; // false
std::errc::no_such_file_or_directory == std::error_code{ERROR_NO_MORE_FILES, std::system_category()}; // false
```

**Expected behavior**
`ERROR_FILENAME_EXCED_RANGE` should be mapped to `std::errc::filename_too_long` (ENAMETOOLONG)
`ERROR_BAD_NET_NAME` and `ERROR_NO_MORE_FILES` should be mapped to `std::errc::no_such_file_or_directory` (ENOENT)

**STL version**
The latest commit manifests this behavior

**Comment by fsb4000** [comment]
Thanks for the detailed report. 😍 
Don't be sad that only 2 out of 3 of your proposals were accepted 😉

**Comment by Morph1984** [comment]
No worries, thank you for the quick implementation 😄
The last one was admittedly a stretch compared to the other 2.
