### ISSUE TITLE
Should STL errors use `pragma message` in order to make the output prettier/more obvious?

### ISSUE THREAD

**Issue by strega-nil-ms** [microsoft/STL#2896]
Currently, our STL errors look like:

```cxx
#error STL1003: Unexpected compiler, expected C++ compiler.
```

This results in the following output from MSVC:

```
C:\Users\nimazzuc\projects\stl\out\x64\out/inc\yvals_core.h(687): fatal error C1189: #error STL1003: Unexpected compiler, expected C++ compiler.
```

This is as opposed to our STL warnings, which result in much prettier output:

```
C:\Users\nimazzuc\projects\stl\out\x64\out/inc\yvals.h(238): warning STL4000: _STATIC_CPPLIB is deprecated and will be REMOVED.
```

Do we wish to use `pragma message` instead, so that we get prettier output?

Something like:

```cxx
// yvals_core.h
// preprocessor fun
#define _STL_PRAGMA(PRAGMA) _Pragma(#PRAGMA)
#define _STL_PRAGMA_MESSAGE(MESSAGE) _STL_PRAGMA(message(MESSAGE))

// note: clang-format does weird things to this
// clang-format off
#define _ERROR_MESSAGE(NUMBER, MESSAGE) \
    _STL_PRAGMA_MESSAGE(__FILE__ "(" _CRT_STRINGIZE(__LINE__) "): error STL" #NUMBER ": " MESSAGE) \
    static_assert(false, "Error in C++ Standard Library usage.")
// clang-format on
```

called like:

```cxx
#ifndef __cplusplus
_ERROR_MESSAGE(1003, "Unexpected compiler, expected C++ compiler.");
#endif
```

resulting in the following output:

```
PS C:\..\nimazzuc\projects\stl-tests> cl /c test.cxx
Microsoft (R) C/C++ Optimizing Compiler Version 19.33.31517 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

test.cxx
test.cxx(12): error STL1004: Unexpected compiler, expected C++ compiler.
test.cxx(12): error C2338: static_assert failed: 'Error in C++ Standard Library usage.'
```

which I at least believe is far more readable (and is probably better for VS diagnostics as well)

(if we do make this change, we should do the same pragma preprocessor nonsense for `_WARNING_MESSAGE`

**Comment by CaseyCarter** [comment]
I'm concerned about using non-preprocessor machinery (`static_assert`) to enforce error-ness for the "this isn't a C++ compiler" case. rc/midl/moc all run the preprocessor, but they don't know what a `static_assert` is, so I think this damages the existing behavior.

For any other STL messages emitted when we know we're being parsed by a C++ compiler (or at least something that proclaims itself to be such) I think this is fine.

**Comment by strega-nil** [comment]
@CaseyCarter one thing I'll say is that rc/midl/moc _should_, in theory, just ignore the `static_assert`, so it won't be damaging at all; adding a `#error` to that specifically would be reasonable though.

**Comment by StephanTLavavej** [comment]
@CaseyCarter and I talked about this and we agree with you here that this would be a desirable change for consistency and user experience. Casey was convinced after looking at the code that rc/midl/moc/etc will indeed not be affected as we near-immediately prevent them from seeing the vast majority of STL header contents:

https://github.com/microsoft/STL/blob/04ee87830a404437f1691d6a3e8809e4986d8493/stl/inc/yvals_core.h#L10-L24
