### ISSUE TITLE
`<xstring>`: `basic_string::_Is_elem_cptr` should be a variable template

### ISSUE THREAD

**Issue by CaseyCarter** [microsoft/STL#2898]
`_Is_elem_cptr<T>` is currently an alias for  `bool_constant<stuff>`. We only ever use it as `_Is_elem_cptr<T>::value`. It could more simply be a `constexpr bool` variable template initialized with `stuff` that we access directly.

https://github.com/microsoft/STL/blob/04ee87830a404437f1691d6a3e8809e4986d8493/stl/inc/xstring#L2473-L2474

**Comment by StephanTLavavej** [comment]
Update: Unfortunately, a compiler bug in `/clr:pure` prevents this change from being made.

**Comment by jonwil** [comment]
Is there a report for the compiler bug?
