### ISSUE TITLE
`<algorithm>`: `ranges::minmax` initializes `minmax_result` with the moved value

### ISSUE THREAD

**Issue by hewillk** [microsoft/STL#2900]
https://github.com/microsoft/STL/blob/04ee87830a404437f1691d6a3e8809e4986d8493/stl/inc/algorithm#L10046

This is basically GCC [PR104858](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=104858), which has been resolved in libstdc++.

```cpp
#include <algorithm>
#include <string>
#include <vector>
#include <iostream>

int main() {
  std::vector<std::string> v{"1", "0"};
  auto [min, max] = std::ranges::minmax(
    std::ranges::subrange{
      std::make_move_iterator(v.begin()),
      std::make_move_iterator(v.end())});
  std::cout << min << " " << max << "\n"; // only print 0 in MSVC-STL
}
```
https://godbolt.org/z/nM5a1Y9Gr

**Comment by CaseyCarter** [comment]
> `<algorithm>`: `ranges::minmax` double dereferences `_UFirst`

This is not a bug.

> `std::cout << min << " " << max << "\n"; // only print 0 in MSVC-STL`

_This_ is a bug.

**Comment by hewillk** [comment]
> > `<algorithm>`: `ranges::minmax` double dereferences `_UFirst`
> 
> This is not a bug.

Sorry, I just kept the original title.
