### ISSUE TITLE
P0009R18 `<mdspan>`

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#2909]
WG21-P0009R18 `<mdspan>`
WG21-P2599R2 `mdspan`: `index_type`, `size_type`
WG21-P2604R0 `mdspan`: `data_handle_type`, `data_handle()`, `exhaustive`
WG21-P2613R1 `mdspan`: `empty()`
WG21-P2763R1 Fixing `layout_stride`'s Default Constructor For Fully Static Extents
LWG-3876 Default constructor of `std::layout_`*`meow`*`::mapping` misses precondition

Feature-test macro (expected):
```cpp
#define __cpp_lib_mdspan 202207L
```

Internal VS-PR-420058 has taught the IDE about this new extensionless header - thanks @CaseyCarter!

**Comment by MattStephanson** [comment]
I looked at this around the new year and implemented large parts of R14. I'd like to continue working on it, but I'd appreciate a ping if anyone decides to work on it themselves.

**Comment by StephanTLavavej** [comment]
@MattStephanson Cool! I'll mark this as Investigating to reflect your progress.

**Comment by StephanTLavavej** [comment]
@MattStephanson has started a feature branch, `feature/mdspan2`, with his partial implementation. :smile_cat: I'm marking this feature as available now - if anyone is interested in continuing this work, it would be a good idea to coordinate on Discord.

**Comment by vickoza** [comment]
I would like to work on this feature.

**Comment by StephanTLavavej** [comment]
@vickoza We're working in a multi-collaborator feature branch, `feature/mdspan2`, with @JMazurkiewicz regularly making changes. It would be best to join the `#mdspan` channel on the STL Discord to coordinate work. Thanks!

**Comment by vickoza** [comment]
How do I join the STL Discord? mdspan is a feature I would like to use

**Comment by JMazurkiewicz** [comment]
Here you go: https://discord.gg/XWanNww

**Comment by vickoza** [comment]
thank you
