### ISSUE TITLE
P1223R5 `ranges::find_last`, `ranges::find_last_if`, `ranges::find_last_if_not`

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#2913]
[P1223R5](https://wg21.link/P1223R5) `ranges::find_last`, `ranges::find_last_if`, `ranges::find_last_if_not`

Feature-test macro (expected):
```cpp
#define __cpp_lib_find_last 202207L
```

**Comment by SuperWig** [comment]
Why is the feature macro `__cpp_lib_find_last` and not `__cpp_lib_ranges_find_last`?

**Comment by StephanTLavavej** [comment]
Thanks for filing an issue! Sounds similar to #2922 where that paper was voted in with `__cpp_lib_fold` which was later changed to `__cpp_lib_ranges_fold`.
