### ISSUE TITLE
P1899R3 `views::stride`

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#2915]
[P1899R3](https://wg21.link/P1899R3) `views::stride`

Feature-test macro (expected):
```cpp
#define __cpp_lib_ranges_stride 202207L
```

**Comment by JMazurkiewicz** [comment]
I've started working on this feature: https://github.com/JMazurkiewicz/STL/tree/stride_view

**Comment by CaseyCarter** [comment]
> I've started working on this feature: https://github.com/JMazurkiewicz/STL/tree/stride_view

Great! I'll move this to "Investigating" to avoid duplication of work. Please let us know if you need to stop work for any reason.
