### ISSUE TITLE
P2408R5 Ranges Iterators As Inputs To Non-Ranges Algorithms

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#2925]
[P2408R5](https://wg21.link/P2408R5) Ranges Iterators As Inputs To Non-Ranges Algorithms

Feature-test macro (expected):
```cpp
#define __cpp_lib_algorithm_iterator_requirements 202207L
```

**Comment by frederick-vs-ja** [comment]
P2408R5 seemly lacks changes in [[iterator.operations]](https://eel.is/c++draft/iterator.operations). Will there be a patch paper?

**Comment by cpplearner** [comment]
> P2408R5 seemly lacks changes in [[iterator.operations]](https://eel.is/c++draft/iterator.operations). Will there be a patch paper?

You mean LWG-3197?
