### ISSUE TITLE
<cmath>: cyl_bessel_i(0.7e2, 0.177219114266335964202880859375e-2) is wrong

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#293]
@CaseyCarter said: "The subject data point generates a result with many orders of magnitude more error than any other data point from Boost's test data." At the time (March 2018), he wasn't sure if this was caused by Boost.Math's original implementation, the changes he made to Boost.Math while using it to implement the MSVC STL's Special Math functions, or the MSVC compiler itself.

I (@StephanTLavavej) am far from an expert here, but I constructed the following test case, which I hope demonstrates the error (although I am not certain):

```
C:\Temp>type meow.cpp
#include <cmath>
#include <cstdio>
using namespace std;

int main() {
    // WG21-N4835 [sf.cmath.cyl.bessel.i]/1 "Effects: These functions compute the
    // regular modified cylindrical Bessel functions of their respective arguments nu and x."
    const double d = cyl_bessel_i(70.0, 0.00177219114266335964202880859375);
    printf("    cyl_bessel_i(): %.16e\n", d);

    // https://www.wolframalpha.com
    // modified Bessel function of (70.0, 0.00177219114266335964202880859375)
    puts("Expected (I think): 1.758873426403941061891519761125...e-314");
}

C:\Temp>cl /EHsc /nologo /W4 /std:c++17 meow.cpp
meow.cpp

C:\Temp>meow
    cyl_bessel_i(): 1.7588734259765355e-314
Expected (I think): 1.758873426403941061891519761125...e-314
```

Also tracked by Microsoft-internal VSO-577628 / [AB#577628](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/577628).

**Comment by statementreply** [comment]
The result is subnormal, only 0.865 ulp from the expected value, despite relative error being in the order of 10^-10.

Perhaps not a bug.

**Comment by StephanTLavavej** [comment]
Ah, that's an excellent point. @CaseyCarter, is this a non-bug?

**Comment by StephanTLavavej** [comment]
Now that we're using Boost.Math 1.80.0 without local changes, I've re-confirmed what @statementreply found:

```
D:\GitHub\STL\out\x64>type meow.cpp
```
```cpp
#include <cmath>
#include <cstdio>
using namespace std;

int main() {
    // WG21-N4835 [sf.cmath.cyl.bessel.i]/1 "Effects: These functions compute the
    // regular modified cylindrical Bessel functions of their respective arguments nu and x."
    const double d = cyl_bessel_i(70.0, 0.00177219114266335964202880859375);
    printf("cyl_bessel_i(): %.16e %a\n", d, d);

    // https://www.wolframalpha.com
    // modified Bessel function of (70.0, 0.00177219114266335964202880859375)
    const double expected = 1.7588734264039411e-314;
    printf("      expected: %.16e %a\n", expected, expected);
}
```
```
D:\GitHub\STL\out\x64>cl /EHsc /nologo /W4 /std:c++17 meow.cpp && meow
meow.cpp
cyl_bessel_i(): 1.7588734259765355e-314 0x0.00000d43147d7p-1022
      expected: 1.7588734264706012e-314 0x0.00000d43147d8p-1022
```

I'm going to resolve this as by design. Thanks!
