### ISSUE TITLE
P2445R1 `forward_like()`

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#2931]
[P2445R1](https://wg21.link/P2445R1) `forward_like()`

Feature-test macro (expected):
```cpp
#define __cpp_lib_forward_like 202207L
```

**Comment by CaseyCarter** [comment]
We now have both a core _and_ library feature for explicit object member functions, and they're still not usable for deduplication because of the conversion-to-private-base issue. 😿
