### ISSUE TITLE
P2467R1 `ios_base::noreplace`: Exclusive Mode For `fstream`s

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#2932]
[P2467R1](https://wg21.link/P2467R1) `ios_base::noreplace`: Exclusive Mode For `fstream`s

Feature-test macro (expected):
```cpp
#define __cpp_lib_ios_noreplace 202207L
```

**Comment by frederick-vs-ja** [comment]
It seems that we can just add a `noreplace` constant with value equal to `_Noreplace`. Has `_Noreplace` been well tested?
