### ISSUE TITLE
P2517R1 Conditional `noexcept` For `apply()`

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#2938]
[P2517R1](https://wg21.link/P2517R1) Conditional `noexcept` For `apply()`

Note: If this link appears to be broken, don't worry! Papers are often revised during a WG21 meeting before the final vote. When that happens, there's a delay of a few weeks between the end of the meeting and the publication of the papers. When the papers are available, the https://wg21.link redirector will start working.

This paper doesn't mention any feature-test macros, presumably intentionally.

**Comment by hewillk** [comment]
> This paper doesn't mention any feature-test macros, presumably intentionally.

Yes, I would like to see it as a defect fix like [P2401](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2021/p2401r0.html#defect). The committee does not seem to mention this either.

**Comment by CaseyCarter** [comment]
> > This paper doesn't mention any feature-test macros, presumably intentionally.
> 
> Yes, I would like to see it as a defect fix like [P2401](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2021/p2401r0.html#defect). The committee does not seem to mention this either.

Agree we should unconditionally implement this conditional `noexcept` =)
