### ISSUE TITLE
P2549R1 `unexpected<E>::error()`

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#2940]
[P2549R1](https://wg21.link/P2549R1) `unexpected<E>::error()`

It is unclear to me whether the editors will increase the value of `__cpp_lib_expected` when merging this paper.

@miscco speculatively implemented this as part of #2643, so I believe that all that remains to be done is:

* [x] Double-check that there are no normative differences between R0 and R1.
* [x] Find out what's happening with the feature-test macro.
* [ ] Update this citation: https://github.com/microsoft/STL/blob/04ee87830a404437f1691d6a3e8809e4986d8493/stl/inc/yvals_core.h#L318

**Comment by frederick-vs-ja** [comment]
According to the corresponding [editorial PR](https://wg21.link/edit5692),
- no normative differences are in R0 and R1, and
- no feature-test macro is changed.

So this should be a "good first issue" and we may proceed in #2873?
