### ISSUE TITLE
P2585R1 Improve Default Container Formatting

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#2941]
[P2585R1](https://wg21.link/P2585R1) Improve Default Container Formatting

**Increased** feature-test macro (expected):
Also updated by [P2286R8](https://wg21.link/P2286R8) Formatting Ranges
Also updated by [P2419R2](https://wg21.link/P2419R2) Clarify Handling Of Encodings In Localized Formatting Of `chrono` Types
Also updated by [P2508R1](https://wg21.link/P2508R1) `basic_format_string`, `format_string`, `wformat_string`
```cpp
#define __cpp_lib_format 202207L
```

This is reportedly strongly coupled to [P2286R8](https://wg21.link/P2286R8) Formatting Ranges and they should probably be implemented simultaneously.

**Comment by CaseyCarter** [comment]
> [P2585R1](https://wg21.link/P2585R1) Improve Default Container Formatting
> 
> **Increased** feature-test macro (expected): Also updated by [P2286R8](https://wg21.link/P2286R8) Formatting Ranges Also updated by [P2419R2](https://wg21.link/P2419R2) Clarify Handling Of Encodings In Localized Formatting Of `chrono` Types Also updated by [P2508R1](https://wg21.link/P2508R1) `basic_format_string`, `format_string`, `wformat_string`
> 
> ```c++
> #define __cpp_lib_format 202207L
> ```
> 
> This is reportedly strongly coupled to [P2286R8](https://wg21.link/P2286R8) Formatting Ranges and they should probably be implemented simultaneously.

Yes, this is a patch paper for P2268.

**Comment by StephanTLavavej** [comment]
Thanks, I will update the issues accordingly.

**Comment by StephanTLavavej** [comment]
Fused into #2919. I have removed the **cxx23** label so that this doesn't affect the Status Chart.
