### ISSUE TITLE
P1169R4 `static` `operator()`

### ISSUE THREAD

**Issue by frederick-vs-ja** [microsoft/STL#2954]
[P1169R4](https://wg21.link/p1169r4) `static` `operator()`

In addition to core language changes, the paper also requires extending deduction guides for `function` and `packaged_task` to deduce from classes with static `operator()`.

No library feature-test macro.

The library change is meaningless and not testable as long as the core change is not implemented. Once the compilers have implemented this feature, I think we can change some CPOs, niebloids, and internally used lambdas to use static `operator()`.

**Comment by CaseyCarter** [comment]
FYI, Clang 16 has implemented this feature.

**Comment by StephanTLavavej** [comment]
I'm working on this.

**Comment by StephanTLavavej** [comment]
EDG now supports this as Future Technology (VS-PR-532076) so we're just waiting for MSVC.
