### ISSUE TITLE
Status Chart: Charts may end up monochromatic if the stylesheet loads slowly

### ISSUE THREAD

**Issue by cpplearner** [microsoft/STL#2963]
Since #2835, https://microsoft.github.io/STL/ uses [Primer CSS](https://primer.style/css/) to colorize the charts. I believe that, since the stylesheet and the script that draws the charts are fetched through separate network requests, it may happen that the script is loaded and executed before the stylesheet finishes loading, in which case everything in the chart will be black.

That's probably why @h-vetinari finds the lines invisible in dark mode (https://github.com/microsoft/STL/pull/2845#issuecomment-1197894620).

Once the stylesheet is loaded, it is stored in the browser cache, so it's less likely to see this problem after the page is refreshed.

**Comment by StephanTLavavej** [comment]
Thanks for the analysis (and @h-vetinari for the report)! I noticed this happening too, primarily when updating the Primer CSS version (thus making it uncached on my machine), but didn't connect the dots that something was wrong and fixable.

**Comment by StephanTLavavej** [comment]
I think I can solve this by running the status chart machinery after the window has loaded, which will wait for the CSS. Will experiment when I get a chance.

**Comment by AlexGuteniev** [comment]
Can consistently recreate using Opera VPN

**Comment by StephanTLavavej** [comment]
I was able to consistently reproduce this by temporarily altering the CSS URL with https://www.deelay.me/ .

I believe I have a fix. I'll create a PR later today:

:chart_with_downwards_trend: Live preview: [stephantlavavej.github.io/STL/](https://stephantlavavej.github.io/STL/)

**Comment by h-vetinari** [comment]
Thanks everyone for taking my stray comment and leveraging it into a detailed analysis + fix. 😊
