### ISSUE TITLE
<format>: error when trying to output a variable from ```enum sides```

### ISSUE THREAD

**Issue by akrisfx** [microsoft/STL#2968]
**Describe the bug**
if I try to output some value from enumerations using ```std::format```, an error occurs during compilation

```cpp
/std:c++20 
D:\Programming\VS22\Try\ConsoleApplication1\Stud.cpp
#include <iostream>
#include <format>


int main()
{
    enum sides : int
    {
        north = 0,
        east = 90,
        south = 180,
        west = 270
    };
    sides n2 = west;
    std::cout << n2 << "\n"; // cout work without problem and print "270"
    std::cout << std::format("{} \n", n2); // if this line is not commented out, an error occurs during compilation

    return 0;
}

```
Error [C2668](https://docs.microsoft.com/ru-ru/cpp/error-messages/compiler-errors-2/compiler-error-c2668)
```
std::_Format_arg_traits<_Context>::_Phony_basic_format_arg_constructor: ambiguous call to overloaded function 
MVS_dir\2022\Community\VC\Tools\MSVC\14.32.31326\include\format	1496
```
```cpp
using _Storage_type = decltype(_Phony_basic_format_arg_constructor(_STD declval<_Ty&>()));
```

Error [C2993](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-2/compiler-error-c2993)
```
"unknown-type":illegal type for non-type template parameter '_Test' 
MVS_dir\2022\Community\VC\Tools\MSVC\14.32.31326\include\format	2774
```
```cpp
consteval typename _ParseContext::iterator _Compile_time_parse_format_specs(_ParseContext& _Pc) {
```	
and 4 more errors, if necessary, I will throw them off

**STL version**
    ```
    Microsoft Visual Studio Community 2022 - Current
    Version17.2.5
    ```

**Comment by frederick-vs-ja** [comment]
I believe this is not a bug, but error message may be improvable.

The standard disables `formatter` for enums by default, so you need to opt-in it. See also [this example](https://eel.is/c++draft/format.formatter.spec#example-1).

**Comment by akrisfx** [comment]
and it won't be a dirty hack?

**Comment by akrisfx** [comment]
if this is spelled out in the standard, then you can close the issue

**Comment by CaseyCarter** [comment]
`std::format` doesn't know how to format enumeration types. You could tell it how to do so by specializing `std::formatter` for your type, or you could convert the enumeration to an integer type (e.g., `std::to_underlying(n2)`) before passing to `format`.
