### ISSUE TITLE
A question about file streams

### ISSUE THREAD

**Issue by HalfWayLambda** [microsoft/STL#2982]
The standard library classes **std::ofstream** and **std::ifstream** need a const char* in their write and read functions respectively. This works well for handling ASCII files that are in text form. However, if one would want to use these classes for doing binary file reading/writing, the parameters passed in would have to be interpreted as a const char*, since they would beforehand be an int, float, double etc.
For example, this simple program creates a file named file.bin and inserts an integer in binary form, the integer address has to be interpreted as a const char* for that to happen without getting an error:
```
int main()
{
	std::ofstream file{ "file.bin" };
	int x{ 5 };
	file.write(reinterpret_cast<const char*>(&x), sizeof(x));
	file.close();
}
```
But having to do this reinterpret_cast for every single write/read operation can get quite messy, and using macros or a wrapper function isn't an ideal solution. So my question is, does the Standard Library support a way of doing this binary file manipulation, without having to resort to doing a **reinterpret_cast**? I'm thinking of a solution that wouldn't involve writing my own FILE* wrapper, as that eliminates the purpose of using the Standard Library in the first place.

**Comment by StephanTLavavej** [comment]
> does the Standard Library support a way of doing this binary file manipulation, without having to resort to doing a reinterpret_cast?

It does not - we recommend looking into serialization libraries. iostreams can perform formatted output (writing an `int` in decimal as `1729` etc.), but doesn't perform portable binary serialization.

Note that `<cstdio>` (classic C I/O) may be a more natural fit for unformatted I/O (like the `file.write()` call above, which would be `fwrite()` in `<cstdio>`); iostreams provides a type-safe interface for formatted I/O but it doesn't buy very much for unformatted.
