### ISSUE TITLE
_Random_device() runs rand_s()

### ISSUE THREAD

**Issue by samrrr** [microsoft/STL#2983]
https://github.com/microsoft/STL/blob/62137922ab168f8e23ec1a95c946821e24bde230/stl/src/xrngdev.cpp#L12-L14
Why its not do something like `return time(NULL)+ __rdtsc();` ?

**Comment by CaseyCarter** [comment]
[`rand_s`](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/rand-s?view=msvc-170) generates cryptographically secure random numbers. `time(NULL) + __rdtsc()`, on the other hand, is predictable and deterministic - any real randomness is isolated to the lower few bits.
