### ISSUE TITLE
`_Get_unwrapped` et. al. should (almost) always be `noexcept`

### ISSUE THREAD

**Issue by strega-nil-ms** [microsoft/STL#2989]
Noticed in https://github.com/microsoft/STL/pull/2987 - `distance` was marked conditionally noexcept on whether `_Get_unwrapped` is noexcept, but `_Get_unwrapped` is never `noexcept`. However, `_Get_unwrapped` could be noexcept whenever `_Iter::_Unwrapped()` is noexcept, as well as when `_Iter::_Unwrapped()` does not exist.

**Comment by CaseyCarter** [comment]
Design intent is that no part of the iterator checking/unwrapping/rewrapping machinery should ever emit an exception. We need an overhaul to make all of our machinery (and ideally, that in the GSL) explicitly `noexcept`.
