### ISSUE TITLE
STL: !_HAS_EXACT_COMPOUND_REQUIREMENT fallbacks are unnecessary

### ISSUE THREAD

**Issue by CaseyCarter** [microsoft/STL#299]
Many of the concept definitions in the standard library have two definitions conditional on `_HAS_EXACT_COMPOUND_REQUIREMENT`. The intent is to be able to support both conforming implementations of C++20 concepts and clang-concepts, which until quite recently had not implemented WG21-P1084's change to *return-type-requirement*s. I've verified with the author of clang-concepts that clang proper will certainly support P1084's semantics when it defines `__cpp_concepts`, so we can remove `_HAS_EXACT_COMPOUND_REQUIREMENT` from the STL as well as all conditional code that is used when `_HAS_EXACT_COMPOUND_REQUIREMENT` is `0`.

**Comment by StephanTLavavej** [comment]
Here's an example:

https://github.com/microsoft/STL/blob/58bb49d63d92e7a0346a05af29816aeea6b4cf0f/stl/inc/concepts#L99-L108
