### ISSUE TITLE
Status Chart: Investigate Firefox dark mode

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#2993]
Reported by @h-vetinari in https://github.com/microsoft/STL/pull/2975#issuecomment-1203799529.

I need to figure out why #2975 isn't working for Firefox. `check_css()` attempts to call `load_charts()` immediately (unlike the earlier #2967), so my tentative guess is that `regex.test(sheet.href)` is failing.

**Comment by StephanTLavavej** [comment]
I'm unable to reproduce this with Firefox 103.0.1 on Windows 11:

<img width="963" alt="firefox_chart" src="https://user-images.githubusercontent.com/4231088/182761890-33f4f68a-47a2-4a58-a560-8e8653acbb8f.png">

**Comment by fsb4000** [comment]
It works for me on Windows 10
![изображение](https://user-images.githubusercontent.com/4289847/182843115-18c55b0d-ce7b-4c1e-bc6c-b131d2df320a.png)

**Comment by NN---** [comment]
Works in Firefox iOS.

**Comment by h-vetinari** [comment]
I retried this again. This time it worked for me. Not sure what changes occurred in the meantime (but I'm pretty sure not even the browser got updated in the meantime; maybe I had been particularly unlucky with the http connection to download the style sheet extremely slowly...?)

**Comment by StephanTLavavej** [comment]
Very strange - perhaps some sort of caching? Anyways, thanks for reporting the issue, and I'm glad it went away! Let us know if it behaves weirdly again.
