### ISSUE TITLE
P0053R7 <syncstream>

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#3]
[P0053R7](https://wg21.link/P0053R7) `<syncstream>`
[P0753R2](https://wg21.link/P0753R2) `osyncstream` Manipulators

LWG-3127 `basic_osyncstream::rdbuf` needs a `const_cast`
LWG-3253 `basic_syncbuf::basic_syncbuf()` should not be explicit
LWG-3334 `basic_osyncstream` move assignment and destruction calls `basic_syncbuf::emit()` twice

Feature-test macro as of WG21-N4842, added by WG21-P1902:
`#define __cpp_lib_syncbuf 201803L`

**Comment by StephanTLavavej** [comment]
Qt reportedly macroizes `emit` so we will probably need `push_macro` defenses.

**Comment by MichaelRizkalla** [comment]
I am starting to work on P0053R7, just checking if I can pick it up since this is an entirely new header 🤔.
I have an initial `basic_syncbuf`'s implementation in 30a999b,
