### ISSUE TITLE
P0645R10 <format> Text Formatting

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#30]
[P0645R10](https://wg21.link/P0645R10) `<format>` Text Formatting
[P1361R2](https://wg21.link/P1361R2) Integrating `<chrono>` With `<format>`
[P1652R1](https://wg21.link/P1652R1) `printf()` Corner Cases In `std::format()`
[P1868R2](https://wg21.link/P1868R2) Clarifying Units Of Width And Precision In `std::format()`
[P1892R1](https://wg21.link/P1892R1) Extended Locale-Specific Presentation Specifiers For `std::format()`

LWG-3242 `std::format` missing rules for `arg-id` in `width` and `precision`
LWG-3243 `std::format` and negative zeroes
LWG-3246 What are the constraints on the template parameter of `basic_format_arg`?
LWG-3248 `std::format` `#b`, `#B`, `#o`, `#x`, and `#X` presentation types misformat negative numbers
LWG-3250 `std::format` `#` (alternate form) for NaN and inf
LWG-3251 Are `std::format` alignment specifiers applied to string arguments?
LWG-3327 Format alignment specifiers vs. text direction
LWG-3340 Formatting functions should throw on argument/format string mismatch in `[format.functions]`
LWG-3371 `visit_format_arg` and `make_format_args` are not hidden friends
LWG-3372 `vformat_to` should not try to deduce `Out` twice
LWG-3373 `{to,from}_chars_result` and `format_to_n_result` need the "we really mean what we say" wording
LWG-3473 Normative encouragement in non-normative note

The IDE's list of extensionless headers has been updated for VS 2019 16.5.

Feature-test macro as of WG21-N4842:
`#define __cpp_lib_format 201907L`

**Comment by AdamBucior** [comment]
This feature is changelogged under 17.0, will it be backported to 16.10?

**Comment by StephanTLavavej** [comment]
@AdamBucior Yes, we plan to request a backport soon (we want to merge #1834 first). At that time we'll update the Changelog.
