### ISSUE TITLE
<string>: Consider providing a 1 argument version of resize()

### ISSUE THREAD

**Issue by BillyONeal** [microsoft/STL#300]
**Describe the bug**
This is DevCom-816413. A customer reported that they have tests which attempt to determine if a member function named "resize" takes a size_type, which used to succeed in VS2015 but fails in VS2019.

Implementing resize with a default argument as we do now, as well as as overloads, are conforming with the standard. http://eel.is/c++draft/member.functions#2 grants implementations broad latitude to define member function signatures in a different form as long as a function call expression that would call a function declared in the standard has the same behavior as calling that function, which is the case here. The intent of that freedom is to explicitly allow implementing default arguments as overloads and vice versa, as VS2019 does. I don't remember exactly why I made this particular change; it probably resulted in smaller code size or similar on some benchmarks or something like that; certainly saving passing of a char in a register isn't worth duplicating all the code here. ([​string has had literally every mutating member rewritten since 2015 for performance reasons](https://twitter.com/MalwareMinigun/status/814196564507799552))

Taking the address of the function, as attempted by the user, is explicitly forbidden by ​http://eel.is/c++draft/requirements#namespace.std-6, which generally forbids taking the address of functions in the standard library, precisely because changes like this are made in the standard itself all the time.

Even though VS is entirely justified in doing this, apparently some customer(s) were relying on this behavior before, and I don't remember exactly why I eliminated the other overload. We might want to add the other overload back for them.

**Command-line test case**
STL version (git commit or Visual Studio version):

```
C:\Users\bion\Desktop>type repro.cpp
#include <string>

// COMPILE-ONLY

using memberFnType = void (std::string::*)(std::size_t);
memberFnType x = &std::string::resize;

C:\Users\bion\Desktop>cl /EHsc /W4 /WX /c .\repro.cpp
Microsoft (R) C/C++ Optimizing Compiler Version 19.23.28107 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

repro.cpp
.\repro.cpp(6): error C2440: 'initializing': cannot convert from 'void (__thiscall std::basic_string<char,std::char_traits<char>,std::allocator<char>>::* )(const unsigned int,const _Elem)' to 'memberFnType'
        with
        [
            _Elem=char
        ]
.\repro.cpp(6): note: Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast
```

**Comment by StephanTLavavej** [comment]
I strongly believe that this should be resolved as by design, and that we shouldn’t change our implementation. Taking the address of Standard Library member functions is brittle and should not be encouraged.

**Comment by BillyONeal** [comment]
I think that outcome is reasonable if you want to close this. I linked the user here if they want to litigate it further.

**Comment by sylveon** [comment]
There may be a performance gain by adding an overload that takes only a size and does not fills the resized buffer with 0s in case you are resizing to something huge and plan to fill it with something else through a C API call right after (because the standard says that the pointer returned by data is only valid through [`data()`, `data()` + `size()`) and not `capacity()`, so `reserve()` cannot work)

The non filling with 0 behavior would be breaking and non-conformant though so that's something that would need to be added to the standard (probably under another name, like `uninitialized_resize()`)

**Comment by BillyONeal** [comment]
That would be a proposal that would have to go through the committee.

**Comment by sylveon** [comment]
Indeed, as I've said myself
