### ISSUE TITLE
<filesystem>: `std::filesystem::canonical()` resolves SUBST-drives as symbolic links

### ISSUE THREAD

**Issue by opfez** [microsoft/STL#3004]
**Describe the bug**
`std::filesystem::canonical()` resolves a SUBST-drive to its target as if it were a symbolic link. This is unexpected because `std::filesystem::is_symlink()` correctly returns false for a non-symlink SUBST-drive path.

**Command-line test case**
```
[Windows] [dev] Sun 07/08/22 13:01 0.093 1716G D:\dev\test>subst E: C:\work\

[Windows] [dev] Sun 07/08/22 13:02 0.090 1716G D:\dev\test>subst
E:\: => C:\work\

[Windows] [dev] Sun 07/08/22 13:01 0.101 1716G D:\dev\test>type nul > E:\target

[Windows] [dev] Sun 07/08/22 13:02 0.101 1716G D:\dev\test>mklink E:\symlink E:\target
Symbolic link created for E:\symlink <<===>> E:\target

[Windows] [dev] Sun 07/08/22 13:02 0.094 1716G D:\dev\test>type repro.cpp
#include <iostream>
#include <filesystem>

int
main()
{
    namespace fs = std::filesystem;

    fs::path path1(R"(E:\)");
    fs::path path2(R"(E:\symlink)");

    std::cout
        << "is_symlink(" << path1 << ") = " << fs::is_symlink(path1) << std::endl
        << "is_symlink(" << path2 << ") = " << fs::is_symlink(path2) << std::endl
        << path1.string() << " => " << fs::canonical(path1).string() << std::endl
        << path2.string() << " => " << fs::canonical(path2).string() << std::endl;
}

[Windows] [dev] Sun 07/08/22 13:02 0.094 1716G D:\dev\test>type build.bat
@echo off
cl repro.cpp /std:c++17 /EHsc /W4 /WX /I D:\dev\base-00\sdk\pc\VisualStudio\17\VC\Tools\MSVC\14.31.31103\include /I D:\dev\base-00\sdk\pc\Windows\10\Include\10.0.18362.0\ucrt /link
/LIBPATH:"D:\dev\base-00\dll\x64" /LIBPATH:"D:\dev\base-00\dll" /LIBPATH:"D:\dev\base-00\sdk\pc\VisualStudio\17\VC\Tools\MSVC\14.31.31103\lib\x64" /LIBPATH:"D:\dev\base-00\sdk\pc\Wi
ndows\10\Lib\10.0.18362.0\um\x64" /LIBPATH:"D:\dev\base-00\sdk\pc\Windows\10\Lib\10.0.18362.0\ucrt\x64"

[Windows] [dev] Sun 07/08/22 13:02 0.095 1716G D:\dev\test>build.bat
Microsoft (R) C/C++ Optimizing Compiler Version 19.31.31104 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

repro.cpp
Microsoft (R) Incremental Linker Version 14.31.31104.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:repro.exe
/LIBPATH:D:\dev\base-00\dll\x64
/LIBPATH:D:\dev\base-00\dll
/LIBPATH:D:\dev\base-00\sdk\pc\VisualStudio\17\VC\Tools\MSVC\14.31.31103\lib\x64
/LIBPATH:D:\dev\base-00\sdk\pc\Windows\10\Lib\10.0.18362.0\um\x64
/LIBPATH:D:\dev\base-00\sdk\pc\Windows\10\Lib\10.0.18362.0\ucrt\x64
repro.obj

[Windows] [dev] Sun 07/08/22 13:02 0.631 1716G D:\dev\test>repro
is_symlink("E:\\") = 0
is_symlink("E:\\symlink") = 1
E:\ => C:\work
E:\symlink => C:\work\target
```

**Expected behavior**
`E:\` should not resolve to `C:\work`, but should stay as `E:\`.

`E:\symlink` should resolve to `E:\target`.

**STL version**
```
Microsoft Visual Studio Community 2019
Version 17.1.0
```

**Additional context**
Judging by the source in [microsoft/STL](https://github.com/microsoft/STL/blob/2263d931f48a4e196036b2523af7a0048bb96b46/stl/inc/filesystem#L3059-L3060), it seems like paths are resolved by calling a Windows system function, so that this check cannot be avoided without rewriting the code as a loop like Boost [has done](https://github.com/boostorg/filesystem/blob/ea22e7655258b61776e4213ca4001a6b97b3541b/src/operations.cpp#L2464-L2468). As you can see, it calls `__std_fs_get_final_path_name_by_handle` [which in turn calls `GetFinalPathNameByHandleW`](https://github.com/microsoft/STL/blob/a0b84e0d6a2c7c3e6a1360b31d774c0d091dcaf4/stl/src/filesystem.cpp#L239). `boost::filesystem` does not resolve SUBST-drives by treating the drive letter as an exception in the resolving algorithm.

**Comment by strega-nil-ms** [comment]
Hi @opfez!

Generally, we believe that, if Windows has an "obvious" way to implement a function, unless we have a very good reason, we should use that functionality (e.g., `rename()` should use `MoveFileW()`).

Additionally, from the standard, `canonical()` is specified as:

> Effects: Converts `p` to an absolute path that has no symbolic link, dot, or dot-dot elements in its pathname in the generic format. _[\[fs.op.canonical\]/1][]

And a symbolic link is:

> A is a type of file with the property that when the file is encountered during pathname resolution ([\[fs.class.path\]][]), a string stored by the file is used to modify the pathname resolution.

It is the opinion of the standard library team that, according to this definition, a subst _is_, in fact, a symbolic link (similar to junctions - junctions are also non-`symlink` symbolic links), and thus that `canonical()` should expand it out.

Finally, at least Python (`os.path.realpath()`) and Rust (`fs::canonicalize()`) agree with our understanding of the canonical operation.

Given all this, we are of the opinion that this is not a bug. If you are in need of this operation, we recommend doing the same thing Boost does.

Thanks so much for the report!

[\[fs.op.canonical\]/1]: http://eel.is/c++draft/filesystems#fs.op.canonical-1
[\[fs.class.path\]]: http://eel.is/c++draft/filesystems#fs.class.path

**Comment by opfez** [comment]
That's understandable! Substs do resemble symbolic links quite a lot. Leaving `canonical` to work like this is probably fine, but in that case shouldn't `is_symlink()` return true on a path like `E:\` where `E:\` is a subst? Right now it seems like there's a disagreement between what the two functions see as symbolic links.

**Comment by strega-nil-ms** [comment]
@opfez This is a weird outcropping of the standard; `is_symlink()` returns whether a path is a `file_type::symlink`, while "symbolic links" are a more general occurrence (including substs and junctions).

**Comment by opfez** [comment]
Right, thanks for your answer.

**Comment by opfez** [comment]
@strega-nil-ms I did some further testing and found the subst to return true for `is_directory()` and false for `is_other()`, but shouldn't it return false for `is_directory()` and true for `is_other()` in this case because it is another type of symbolic link?

Documentation for `is_other()`:
> Checks if the given file status or path corresponds to a file of type other type. That is, the file exists, but is neither regular file, nor directory nor a symlink.

**Comment by strega-nil-ms** [comment]
@opfez it's hard to say; root directories are weird.
