### ISSUE TITLE
`<iterator>`: `move_sentinel` could be unwrappable

### ISSUE THREAD

**Issue by JMazurkiewicz** [microsoft/STL#3009]
As the title says, `std::move_sentinel` could be unwrappable.

## Outdated (fixed by #3024)

Since `std::move_sentinel<X>` is not unwrappable, it cannot be used with ranges algorithms when corresponding `std::move_iterator<X>` is unwrappable.

```c++
#include <algorithm>
#include <cassert>
#include <iterator>
#include <vector>

using namespace std;

int main() {
    vector<int> ints = {1, 2, 3};
    auto is_positive = [](auto x) { return x > 0; };
    assert(ranges::all_of(move_iterator{ints.begin()}, move_sentinel{ints.end()}, is_positive));
}
```

**Expected behavior:** This code should compile.

**Additional context:**

* [Compiler explorer](https://godbolt.org/z/jqzd19doj),
* Noticed while implementing test coverage for #3008.

**Comment by JMazurkiewicz** [comment]
This is no longer a bug (thanks to #3024), so it should be labelled with `enhancement`.

**Comment by StephanTLavavej** [comment]
Relabeled - thanks @JMazurkiewicz!
