### ISSUE TITLE
`<ranges>`: list-initialization is misused

### ISSUE THREAD

**Issue by hewillk** [microsoft/STL#3014]
Non-list-initialization (parentheses) and list-initialization (curly braces) styles are mixed in the `<ranges>`, however, the latter does not provide any observable benefit and may bring potential issues.
We should use non-list-initialization consistently, as the standard does.

```cpp
#include <ranges>
#include <initializer_list>
#include <utility>

struct I {
  using difference_type = int;
  using value_type = int;
  I(std::initializer_list<int*>) = delete;
  I(int*);
  int operator*() const;
  I& operator++();
  I operator++(int);
};

struct R {
  int* begin();
  I begin() const;
  std::unreachable_sentinel_t end() const;
};

int main() {
  auto r = R{} | std::views::transform(std::identity{});
  decltype(std::as_const(r).begin()) c = r.begin();
}
```
https://godbolt.org/z/89eo678qd

**Comment by hewillk** [comment]
`move_sentinel` has the same issue. (since these bugs are in the same category, I'm not going to open new ones.)

https://github.com/microsoft/STL/blob/5aae6780236208577b4e8a000cbe7aa3cbc24c41/stl/inc/iterator#L193-L197

```cpp
#include <iterator>

struct Sentinel {
  Sentinel() = default;
  Sentinel(std::initializer_list<int*>) = delete;
  Sentinel(int*);
};

int main() {
  std::move_sentinel<Sentinel> s(std::move_sentinel<int*>{});
}
```
https://godbolt.org/z/PMq8snb59

**Comment by StephanTLavavej** [comment]
Thanks for reporting this issue! I've edited your description to use the Standard's term "non-list-initialization" (often seen as "direct-non-list-initialization"), and clarified that this refers to parentheses, while list-initialization refers to curly braces. ("Braces" is often interpreted by Americans as referring to curly braces `{}`).
