### ISSUE TITLE
`<string>`: Should `string::substr` forward the allocator to the newly created `string`?

### ISSUE THREAD

**Issue by fsb4000** [microsoft/STL#3022]
The C++ Standard doesn't say that: https://eel.is/c++draft/string.substr

https://github.com/microsoft/STL/blob/5aae6780236208577b4e8a000cbe7aa3cbc24c41/stl/inc/xstring#L4673-L4676

@CaseyCarter agreed. He also assumed that we'll fix this when implementing WG21-P2438 but I still decided to create an issue to not forget about it.

**Comment by frederick-vs-ja** [comment]
I think copying or moving from another allocator-aware `basic_string` object should SOCCC or copy the resulted allocator from the source respectively, instead of default-constructing it.

The requirements for constructors performing partial copy/move and `substr` are a bit unreasonable to me. But we may need a particular paper to change this.

**Comment by fsb4000** [comment]
@frederick-vs-ja I also sent an email to lwgchair@gmail.com asking for clarification.

**Comment by StephanTLavavej** [comment]
@CaseyCarter notes that there's implementation divergence here, so we need the Standard to tell us what to do.

**Comment by fsb4000** [comment]
They replied 😊  
https://cplusplus.github.io/LWG/issue3752

**Comment by CaseyCarter** [comment]
Discussion in the prioritization thread on the Library reflector is leaning very strongly toward closing LWG-3752 as Not A Defect. [[string.substr]/1](https://eel.is/c++draft/string.substr#1) is quite clear that the effects are equivalent to the "substring constructor" `basic_string(const basic_string&, size_type, size_type, Allocator = Allocator())` which LWG-2420 revalidated _should_ default construct an `Allocator` back in early 2016.

I think we should implement this - and the new rvalue overload introduced in WG21-P2438 - as specified.

**Comment by frederick-vs-ja** [comment]
I'm fixing this. But I feel that I'm "unfixing" something. (Although this is making the implementation conforming!)

These substring constructors do not follow the convention of allocator-aware containers, so I think they are defective now. Given the source is already an allocator-aware `basic_string`, in the IMO reasonable specification,
- the `const basic_string&` overloads (and the `const`/`const&` overload of `substr`) should use SOCCC to obtain the allocator from the source, and
- the newly added `basic_string&&` overloads (and the `&&` overload of `substr`) should copy (which is equivalent to move for allocators) the allocator from the source, however,
- the default argument is no longer possible, so each existing constructor overload should be split into two overloads.
