### ISSUE TITLE
`<iterator>`: `ranges::prev` maybe ill-formed in debug mode

### ISSUE THREAD

**Issue by hewillk** [microsoft/STL#3025]
https://github.com/microsoft/STL/blob/5aae6780236208577b4e8a000cbe7aa3cbc24c41/stl/inc/xutility#L2636-L2648

`ranges::prev` uses `_Min_possible_v` to detect integer overflow, whereas `_Min_possible_v` uses `make_unsigned_t` which doesn't work with integer-class types.

```cpp
#define _DEBUG
#include <ranges>

int main() {
  auto r = std::views::iota(0ull, 5ull);
  auto it = r.end();
  auto prev = std::ranges::prev(it, 3);
}
```
https://godbolt.org/z/4GzPo1nzc

**Comment by frederick-vs-ja** [comment]
I prefer extending `make_signed` and `make_unsigned` to support integer-class types, and eliminating weird _`make-signed-like-t`_/_`make-unsigned-like-t`_ in the standard wording.
