### ISSUE TITLE
std::move_only_function::operator bool doesn't work for DLLs

### ISSUE THREAD

**Issue by andreeL** [microsoft/STL#3037]
The current implementation:

    _NODISCARD bool _Is_null() const noexcept {
        return _Data._Impl == &_Null_move_only_function;
    }

compares with a static object (&_Null_move_only_function), which is different for each DLL

**Comment by CaseyCarter** [comment]
It would be better if the `_Impl` itself "knew" whether or not it is null, i.e. via a `bool` member or `bool`-returning function.

**Comment by AlexGuteniev** [comment]
> It would be better if the `_Impl` itself "knew" whether or not it is null, i.e. via a `bool` member or `bool`-returning function.

I agree that this would be the way to fix the issue, and also don't see good non-ABI-breaking ways.

**Comment by StephanTLavavej** [comment]
I think we also need to worry about the case where a `move_only_function` is constructed in DLL A, then used as the source to move-construct a `move_only_function` in DLL B, then DLL A is unloaded. DLL B's `move_only_function` should continue to be usable (as long as it didn't refer to a function in DLL A), including when it is empty.

**Comment by AlexGuteniev** [comment]
> I think we also need to worry about the case where a `move_only_function` is constructed in DLL A, then used as the source to move-construct a `move_only_function` in DLL B, then DLL A is unloaded. DLL B's `move_only_function` should continue to be usable (as long as it didn't refer to a function in DLL A), including when it is empty.

Thanks, I hate it.

I see couple of options:
1. Keep nullptr` as empty "vtable" indicator. This will solve both issues, but will add a check for `nullptr` on every "vtable" use. Hopefully the check will cause extra `cmov`, not real branch.
2. Embed the content of "vtable" to the object itself, keep `nullptr` as default `_Move` / `_Destroy`, make sure `nullptr` is also an invalid `_Call`. This will avoid any dangerous indirections, and potentially improve some operations, but will make the used part of the function object larger, and leave less room for the buffer

I'm leaning towards the first option.
