### ISSUE TITLE
`<iterator>`: Automatic `iterator_category` detection misbehaves when `::reference` is an rvalue reference, refuses to accept a forward iterator

### ISSUE THREAD

**Issue by HolyBlackCat** [microsoft/STL#3047]
**Describe the bug**
When an iterator doesn't have `::iterator_category`, and its `::reference` is an rvalue reference (either set manually, or `operator*` returns an rvalue reference), the automatically determined `std::iterator_traits<T>::iterator_category` is at best an input/output iterator, never a forward iterator.

**Command-line test case**
```cpp
z:\>type 1.cpp
#include <iterator>
#include <type_traits>

template <typename T>
struct A
{
    using value_type = std::remove_cvref_t<T>;
    using difference_type = int;
    T operator*() const;
    A &operator++();
    A operator++(int);
    bool operator==(const A &) const;
};

// Ok.
static_assert(std::is_same_v<std::iterator_traits<A<int &>>::iterator_category, std::forward_iterator_tag>);
// Should pass but fails, the category is `std::input_iterator_tag`.
static_assert(std::is_same_v<std::iterator_traits<A<int &&>>::iterator_category, std::forward_iterator_tag>);

z:\>cl /EHsc /W4 /WX /std:c++latest 1.cpp
Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30133 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

/std:c++latest is provided as a preview of language features from the latest C++
working draft, and we're eager to hear about bugs and suggestions for improvements.
However, note that these features are provided as-is without support, and subject
to changes or removal as the working draft evolves. See
https://go.microsoft.com/fwlink/?linkid=2045807 for details.

1.cpp
1.cpp(18): error C2607: static assertion failed
```

**Expected behavior**
`::reference` being an rvalue reference should be permitted for any iterator category.

**STL version**

```
Microsoft Visual Studio Community 2019
Version 16.11.1
```

**Additional context**

This also reproduces on trunk on gcc.godbolt.org.

I blame this on [cppreference](https://en.cppreference.com/w/cpp/named_req/ForwardIterator), which used to incorrectly say that only lvalue references are allowed there. It was fixed since then.

See [`[forward.iterators]/1.3`](https://eel.is/c++draft/iterators#forward.iterators-1.3). Also see [LWG issue 1211](https://cplusplus.github.io/LWG/issue1211) (from 2009), which was resolved by [N3066](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2010/n3066.html) (in 2010).

This was discussed on SO: https://stackoverflow.com/q/73353152

[libstdc++](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=106676) and [libc++](https://github.com/llvm/llvm-project/issues/57233) share the exact same bug.

**Comment by hewillk** [comment]
This is standard-specified behavior.
When `A` does not provide `iterator_category`, `iterator_traits` will first determine whether type A models `cpp17-input-iterator`. Since A's `reference` is an rvalue reference, it will fall back to detect whether A models `cpp17- iterator`, and provide `output_iterator_tag` as its `iterator_category`.
See [iterator.traits](https://eel.is/c++draft/iterator.traits).

**Comment by HolyBlackCat** [comment]
@hewillk 

> `cpp17-forward-iterator` requires the reference type to be an lvalue reference

Any source for this? [`[forward.iterators]/1.3`](https://eel.is/c++draft/iterators#forward.iterators-1.3) says "reference", not "lvalue reference".

**Comment by CaseyCarter** [comment]
As @hewillk stated, this is precisely what the Standard requires us to do. This isn't a bug in any standard library implementation. However, WG21 did recently approve P2520R0 "`move_iterator<T*>` should be a random access iterator" to relax the similar suppression of `move_iterator`'s nested `iterator_concept` type. It would seem consistent to change _`cpp17-forward-iterator`_ similarly. AFAIK such a change was never discussed - it didn't occur to us during review of P2520 that the autodetection machinery in [iterator.traits] was effectively doing the same thing. 

I'm going to close this as not-a-bug, and I'm also going to start a discussion on the WG21 reflectors about making the consistent change in [iterator.traits] so this becomes a bug.

**Comment by HolyBlackCat** [comment]
I've also tried to report this as an LWG issue to `lwgchair@gmail.com` (after seeing hewillk's comment), but I'm not familiar with the process, and didn't receive a response yet.

**Comment by frederick-vs-ja** [comment]
This is tracked in #3228 now.
