### ISSUE TITLE
STL: WE SHOULD REMOVE THE SHOUTY COMMENT BANNERS!

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#306]
We currently follow a convention of introducing structs, classes, functions, etc. with "SHOUTY COMMENT BANNERS". A few examples:

https://github.com/microsoft/STL/blob/580e61a5f5536016f521cc1b2ca636eadc69bd30/stl/inc/vector#L410-L412

https://github.com/microsoft/STL/blob/580e61a5f5536016f521cc1b2ca636eadc69bd30/stl/inc/algorithm#L29-L41

https://github.com/microsoft/STL/blob/580e61a5f5536016f521cc1b2ca636eadc69bd30/stl/inc/type_traits#L536-L541

We've been thinking about changing this convention. It hasn't been applied rigorously, even for publicly-documented components (e.g. we have `// STRUCT TEMPLATE is_empty` but not `// VARIABLE TEMPLATE is_empty_v`). It might have helped file navigation many years ago, but IDE/editor support for Go To Definition and Find In Files (e.g. VSCode Ctrl+Shift+F) makes it easy to find where components are defined.

In theory, the banners could be most useful when publicly-documented components are preceded by internal support machinery, but in practice, we haven't always used them like that. For example, some but not all of the helpers for `is_permutation()` are introduced with `// FUNCTION TEMPLATE is_permutation`:

https://github.com/microsoft/STL/blob/580e61a5f5536016f521cc1b2ca636eadc69bd30/stl/inc/xutility#L4395-L4455

As these comments seem to provide minimal value today, are commonly overlooked by new contributors, and consume valuable lines, we should decide whether to keep or discard them.

**Comment by BillyONeal** [comment]
I use these to find the definitions of a given feature, since searching for the thing directly often finds uses rather than the definition, and the implementation of a given thing often starts well above where it is declared.

**Comment by BillyONeal** [comment]
I just found the definition of 1-arg `std::move` with these :)

**Comment by brycelelbach** [comment]
I'm the person he found the 1-arg `std::move` definition for... so I'm a fan of these staying.

**Comment by AlexGuteniev** [comment]
Will normal `#pragma region` work? 
In case of `std::move` the nonmoving move can go to a separate region from iterator move.

**Comment by CaseyCarter** [comment]
Here we are, one year later. Since we don't _really_ care about these shouty banners, we have added lots of new code without them despite the inconsistency. Is it time to restore consistency by removing all of them yet?

**Comment by AdamBucior** [comment]
Yeah, I think they should be removed

**Comment by StephanTLavavej** [comment]
We talked about this in our weekly maintainer meeting and there's agreement - let's remove the shouty banners from the product code, and avoid adding new ones. This could be a "good first issue" except that it involves editing a *whole* bunch of files, which is difficult to ask of very new contributors (especially because such PRs tend to accumulate merge conflicts if they're open for any amount of time, and resolving merge conflicts is difficult for git novices). An experienced contributor could easily do this in a single PR.
