### ISSUE TITLE
<concepts>: ICE when using as header unit

### ISSUE THREAD

**Issue by Arthapz** [microsoft/STL#3062]
Hi, i'm getting an ICE when using <concepts> as a header unit

```
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.33.31629\include\concepts(216): fatal error C1001: Internal compiler error.
(compiler file 'msc1.cpp', line 1576)
 To work around this problem, try simplifying or changing the program near the locations listed above.
If possible please provide a repro here: https://developercommunity.visualstudio.com 
Please choose the Technical Support command on the Visual C++ 
 Help menu, or open the Technical Support help file for more information
INTERNAL COMPILER ERROR in 'C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.33.31629\bin\HostX64\x64\cl.exe'
    Please choose the Technical Support command on the Visual C++
    Help menu, or open the Technical Support help file for more information
```

**STL version**
```
Microsoft Visual Studio Build Tools 2022
Version 17.3.2
```

**Comment by StephanTLavavej** [comment]
Can you provide a complete self-contained test case - i.e. your source file and command lines? We have test coverage for `<concepts>` being used as a header unit, so this is likely specific to your exact source and options:
https://github.com/microsoft/STL/blob/8ca7bd3c002d383940de9abe6379721e96eb12e3/tests/std/tests/P1502R1_standard_library_header_units/test.cpp#L25

**Comment by StephanTLavavej** [comment]
@Arthapz commented on Discord:

> i can't reproduce it anymore (the code has changed, and i don't have history so i can't rewind to the point where it was not working)

Please open a new issue if you encounter another ICE. (The compiler team has been busy fixing many ICEs in header units and named modules, so hopefully this one was truly fixed by recent work. :smile_cat:)
