### ISSUE TITLE
Improve `std::source_location::function_name()` informativeness

### ISSUE THREAD

**Issue by b1ackviking** [microsoft/STL#3063]
Why does the `std::source_location::function_name()` return a string equivalent to `__builtin_FUNCTION()` instead of `__FUNCSIG__`? Are there any plans to change that in the future?

The `<source_location>` header was introduced PR #664, and there was a discussion starting from [this comment](https://github.com/microsoft/STL/issues/54#issuecomment-787760197) on improving the informativeness of the `std::source_location::function_name()`. There are also two ([1](https://developercommunity.visualstudio.com/t/Improvement-Expand-output-of-__builtin/1491652), [2](https://developercommunity.visualstudio.com/t/improve-the-output-of-__builtin_FUNCTION/1489591)) DevCom tickets that are both in the “Under review” status since August 10, 2021, but there are no feedback since then.

The suggestion is to make the `std::source_location::function_name()` return the same string as `__FUNCSIG__` does, analogous to what GCC and Clang do by returning the string equivalent to `__PRETTY_FUNCTION__`. Here is the [side by side comparison (compiler explorer)](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DIApACYAQuYukl9ZATwDKjdAGFUtAK4sGIAKykrgAyeAyYAHI%2BAEaYxCBmZqQADqgKhE4MHt6%2BASlpGQKh4VEssfGJtpj2jgJCBEzEBNk%2BfoF2mA6Z9Y0ExZExcQlJCg1NLbntY31hA2VDiQCUtqhexMjsHOYAzGHI3lgA1Cbbbo3ETACeJ9gmGgCCO3sHmMenyKP4gjd3j2a7DH2XiOJzcThYhjwyR%2BDyegJebzBaQIxEwrBhfwBQJBpwUq3WmAA%2BrRUKJagwMXDsa9QV5HLRCNdtrdYf9nsCaacAG6dIjESkPAD0gsODFQBFeBAQTAIhzEtEOeO85IUhwA7iQANaHMLHABsGjQDFGmC5YhMBt%2BEpYyQMEsRBEuyUYrFeABUMUaTWaFUw6ahDsBMARCVQvIDyYTmGwFBBFscAOxWB6HQ5edJGUWuhTJJgbRUEdAgEAMiUXWgKYujYhhYCErl4TBq4mEOJiBQnZP3VOoghrBgFosgc5XRNd1Opz7F3N4flJ8xmQmh8PIJcgY6JBRc0iHJdhwFLkwJgAipF%2BE8H06Ys6PVkSS%2BiXjojgYhIAYnIIm43QBJADyETrguW47g%2BT60C%2B76ft%2B/4RHGR6nr8TxUIcWA0OE6AQEuADiERyG4S7xkebjEahmDoZgmFLvshh1oSiznhOU4gDOc53ouhLKAAStgbpugAmlBX6/gBa4bmYIG7pxPF8YJH7CbBh4nmerLbNUeAoWhsxUQAskIBEAGrYFxDEpkxhZXje873kJbhCD%2B2FicB25SfJdkOUpiGqa4GmMZOFksdebELvuXQCFGrpAZuLnMXiawbMSpIypkxbIGsqKCHGAB0oWRtGmDwcpjEIZ2SEnkhDzWraMqcm4jrOvlhwesyvxcqgeDoIcyQ1oIy4RpkEUxnGY6MfwxCHBAfpEMc/gWJqO5ciY/jHoc65BiGuUDflHanM12BxkR85mf5Q5oHSiKgpeIBKAQaoQGYXBEacl3aqCl1chdpyHGAWz%2BG4DA/aVZklWZzFnbKb1fcxri0EDjzlbCDxhLKEJhBAyM7sg0rEAAVDjh3jl1PUbSueXZqCyM3PB2yE91yN9WFr7baCVAkjKVMMTTjF071m3hczuIBTyDgkKCzFPoI2yLgQPzMtTXYg/cHDLLQnD%2BLwfgcFopCoJwJGWNYir4vmOw8KQBCaMryyaiAkh6llXAAJxmI7CYAByO1w2z%2BP8XBcPonCSBrls65wvCVho5uW8scCwDAiAoKgNp0HE5CUGgyf0PEwAKMwyQKAg4p8M%2BcSVhA0Qh9EYSNJcnBmxnbCCH%2BDC0LXWu8FgEJGOI7ekPgqJdDyla95gqidHSmza8j1Qhwy0QXMQlweFgIcongLB18rfAGDnBmNmqf4NZvMiCCIYjsFIJ/yEoagh7o/sGEYKDWNY%2Bh4NElaQMsqDJCqnAALR/lVP/T4JxjymANpYf4hx/4AHV5QwNgaPFETBEHOnQIYRwyBEFxGICQGBVAFCQkcAAL0wGApg6B0CogUAofQaJ5rhi0hhGBtBf4IFRJQ8O1ReQpQgK4CYfh/YhFmKUcoehUjpHJIIiRBRyT9DEUMf2HRGY9HGJ4VoegVHkjUTMEogx4jKOmDIoxvQFEGIkMsOKBI9AokwJsHgKs1bB17rrDgqg3Z6n/nqSQgZkDYIgCicMmp4wQH1neGwhxcCEHwabHcHhM5xA3NsR6vALbt0WNbBIgRVYcCDqQDe/hI6a21m48OIBI7pK0DHeOEAkCrAIMkOkacIAZ2SCnYgERIruM8d43xwB/ETSCQwEJvBKIxJrEWf2/BT6iHEJfGZ18VDqF7vfUgaoLjJE3k4jg6tSAlN4G4v8dImmylQChDxXifF%2BICcMkJE0EntKzsk1JUcMnLAQGiLA8Q4wBzybwQpxSQ5lNsBUt51SslcDdllB6/h/CO0kBoSQ/hJDbClt7P52wXGlLDuCrescoC1KQG0jpLSSVZxQI/Osdzi4QVLpQCuvcq7MEXsfBujACDN1biHTutEe7a37rwoeIdR7jwlCHaeuTtZzwXkvDAk80k1g3twLerMmC733ofRgx9Fln3mdIRZihll3wSPoWiz9IE2Dnp/X5P8/4cEAcA0B2xwEvygdERBCC4HIIuGgyimC8DYO9cQPB41/6EOIXgMhFCqE0LofQJgjCGDMMotwmofCBEaNyMI5N5j5iGPyFIzIJjC2FAYHm8RyieGqOMVmoRVR011GmBWpRtha05HraMMxoiLGPRWPFC%2B5tUQOK3rkvZBzQ49Kub4mimZAnEGCaE8Jr8on4D5C8%2BJScnlJJ2GYRYaTo5ZLMDkwOAKAhAtcbiiOeKanwDqSABppyyVbo6V0tgnBLl9MOLO4AQyF0jP3UENdJAOp6F1XMi%2BBrZBGtvqs01GymBbJVTs8dwLODHMaedc5hxP3XJ/X%2BxdDyX3PN3YBqpVtSCfMoUMX5uT8mAv2Whjg5TKmHtIDbLgCYsqOw0BoPUZgEy8akE7V2CZMXYsObi8jt6453uJcR1OFBWkKfiFyZAyRkj1idsSGqoxCSqB8bSssZdGXa2ZTXNlSdG6cpbm3AVmAu7AH5R3WcQrMDD21qKtK4re6Stnu/WVy8FVDvXts7e6qFB7ybFqzWZtwPnwkFBwQMGVna10NsM1T8IERLfh/eA39f6ZGHo6mBU5svWDtO52UcDfFwIABppt4c4fhyaS0iP0fm2RRaBAlskWWltBbtHdHbZoqtjaGC6IG1okb2a23do65WqxxtB12JHShiTk6DO%2BJYFubBXInZZUq6MB5brInRPXXEw4jyOnJO2GRtjNtj1/Po%2Beh2GgPZSztlChM2w9S/cY5e5joLWMZNIAS%2B9j7mlKfJXEN9mwtuHB22pw4%2B3HaHd0wQMZwHJlgdkHqyDV8UsmoywhpDji/mocBxh05hxsMI6R3tg7R3ZRhJU7d%2B77zKNfJozsl7kg0cey4HxhM/hthuy4GYP7hmJ0guvdJyFXG9Q8bdrxjQ2xHb8e2GJ3JWKAc4qB/Lv5ZgNsgsNzyYg6RnCSCAA). Please note, that GCC and Clang also provide the `__builtin_FUNCTION()` intrinsic which works the same as MSVC implementation, however, [libstdc++](https://github.com/gcc-mirror/gcc/blob/16e2427f50c208dfe07d07f18009969502c25dc8/gcc/cp/cp-gimplify.c#L2943-L3034) and [libc++](https://reviews.llvm.org/D120634) implementations of `source_location` rely on the `__builtin_source_location()` intrinsic which works differently.

This is not a bug report because the current implementation is definitely valid by the [C++ Standard](https://eel.is/c++draft/support.srcloc#cons-1.1), but I find it a significant usability improvement for using `source_location`, thus bringing it here.

If I am misunderstanding some concepts, please correct me in the comments.

Also tracked by internal VSO-1614161 / AB#1614161 .

**Comment by fsb4000** [comment]
Я обращался к Кэмерону, но он как раз уходил в отпуск и пятница была его последним рабочим днём перед отдыхом.
На вопросы про STL ответы появляются оперативнее.

**Comment by StephanTLavavej** [comment]
I've created an internal work item for the compiler front-end team to track, thanks.

**Comment by StephanTLavavej** [comment]
Internal MSVC-PR-423006 implemented `__builtin_FUNCSIG()`, which will be available in VS 2022 17.5 Preview 1.

**Comment by fsb4000** [comment]
@StephanTLavavej , do we need to ask Clang devs and EDG devs to implement `__builtin_FUNCSIG()` ?

**Comment by nuuSolutions** [comment]
Why not have both? simple name and full signature
I really liked getting the plain function name without any hassle.

**Comment by Jasonzyt** [comment]
> Why not have both? simple name and full signature I really liked getting the plain function name without any hassle.

You can take an indirect approach since there is an `#if` preprocessor statment 🤣 
![image](https://github.com/microsoft/STL/assets/66063199/468b678b-b7ed-46ab-b3ce-54307523d24e)

**Comment by fsb4000** [comment]
>What is a preprocessor?

A text replacing mechanism which is running before compilation.

More details: https://en.cppreference.com/w/cpp/preprocessor

**Comment by jonesmz** [comment]
I'm starting to migrate my codebase to using std::source_location over the equivalent home grown type, and I have to say that the switch to `__builtin_FUNCSIG()` over `__builtin_FUNCTION()` seems to be a *major* step backwards in terms of basic readability.

I have an assert macro which, among other things, uses `__FUNCTION__` to get the current function name.

With this macro, i get nice, simple, function signatures, for example:

```
Function: libname::`anonymous-namespace'::parse_fract_time_value
```

Switching this macro to using `std::source_location::current()` I get neigh-incomprehensible symbol vomit.

```
class std::_String_const_iterator<class std::_String_val<struct std::_Simple_types<char> > > __cdecl libname::`anonymous-namespace'::parse_fract_time_value(class std::_String_const_iterator<class std::_String_val<struct std::_Simple_types<char> > >,const class std::_String_const_iterator<class std::_String_val<struct std::_Simple_types<char> > > &,unsigned __int64 *,unsigned __int64 *,unsigned __int64 *)
```

the actual function signature is
```
std::string::const_iterator    parse_fract_time_value(std::string::const_iterator         pos, 
                                                   const std::string::const_iterator&  end, 
                                                   std::uint64_t*                        pValue, 
                                                   std::uint64_t*                        pFractNom, 
                                                   std::uint64_t*                        pFractDenom)
```

Is this really better to have 5x the characters in the output, including the unnecessary `class` keywords, and fully expanded out template parameters?

C++ has nothing in the standard library to assist developers in parsing function signatures, and MSVC, Clang, and GCC each have their own formatting. 

How are we supposed to parse this to get the actual function name?

**Comment by SuperWig** [comment]
You can define `_USE_DETAILED_FUNCTION_NAME_IN_SOURCE_LOCATION` to 0 if you want the old behaviour.
