### ISSUE TITLE
Can you provide the more support of <bit> like GCC does?

### ISSUE THREAD

**Issue by expnkx** [microsoft/STL#307]
libstdc++ has already done that.
ryu string to double algorithm requires algorithm like log2p1.

https://github.com/ulfjack/ryu/blob/parsing/ryu/s2d.c

https://github.com/gcc-mirror/gcc/blob/master/libstdc%2B%2B-v3/include/std/bit
https://en.cppreference.com/w/cpp/numeric/log2p1
THANK YOU!!!

**Comment by StephanTLavavej** [comment]
This is coming very soon, tracked by #25, #26, and #61.
