### ISSUE TITLE
`<xatomic.h>`: Investigate making this a core header

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#3103]
`<xatomic.h>` is currently a non-core header:

https://github.com/microsoft/STL/blob/ac129e595f762f11551663f1c7fa5f51444a8c6c/stl/inc/xatomic.h#L9

In #3048, we found that we might want to centralize some macro machinery here, but before we drag it into the import lib, `<xatomic.h>` really ought to be a core header (as we've had trouble with non-core headers getting into the import lib).

It should be possible to make this into a core header with a bit of investigation.

**Comment by frederick-vs-ja** [comment]
I've noticed that there are several internal core headers that are never included by standard core headers. Can we add a test for their core-ness?

**Comment by CaseyCarter** [comment]
> I've noticed that there are several internal core headers that are never included by standard core headers. Can we add a test for their core-ness?

`std/tests/GH_001411_core_headers` enforces core-ness.
