### ISSUE TITLE
STL: Test Clang 10

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#312]
We should test Clang 10 soon, so if we find any issues, they can be fixed before release.

Several bugs have already been fixed; we should verify these fixes:

* LLVM-38491 clang-cl should accept `__declspec(allocator)`
Workaround:
https://github.com/microsoft/STL/blob/580e61a5f5536016f521cc1b2ca636eadc69bd30/stl/inc/yvals_core.h#L981-L987

* LLVM-39247 clang-format `FixNamespaceComments` damages deprecation macros
Workaround:
https://github.com/microsoft/STL/blob/580e61a5f5536016f521cc1b2ca636eadc69bd30/.clang-format#L97-L99

* LLVM-39248 clang-format mishandles macroized `if constexpr`
No workaround. Responsible for:
https://github.com/microsoft/STL/blob/580e61a5f5536016f521cc1b2ca636eadc69bd30/stl/inc/vector#L2315-L2316

* LLVM-43531 clang-format damages "alternative representations" for operators
Test workaround in `tr1/tests/qproofer/ciso646`.

* LLVM-38478 Clang 7.0.0 RC1 `-fno-ms-compatibility` rejects `Windows.h`
Extensive test workarounds.

**Comment by StephanTLavavej** [comment]
@CaseyCarter During your Clang 10 validation, were you able to verify that these issues were properly fixed?

**Comment by CaseyCarter** [comment]
> @CaseyCarter During your Clang 10 validation, were you able to verify that these issues were properly fixed?

No, I didn't validate any of these fixes. My home-built binaries are enormous and statically linked, so I'm hesitant to build a nuget and throw Contest at it; I've been performing hand testing. FWIW, I'm refreshing http://prereleases.llvm.org/10.0.0/ a couple of times a day so I'll notice when the RC binary packages appear.

**Comment by CaseyCarter** [comment]
Updating the thread: I've verified that all of the issues linked in the first post are fixed in Clang 10 RC1.

**Comment by CaseyCarter** [comment]
Closed by #708.
