### ISSUE TITLE
<bit>: Activate __cpp_lib_bitops for MSVC

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#313]
#310 implemented #25 and #26:

* WG21-P0553 `<bit>` Rotating And Counting Functions
* WG21-P0556 `<bit>` `ispow2()`, `ceil2()`, `floor2()`, ~~`log2p1()`~~ `bit_length()`

This is currently active for Clang (and EDG, used for IntelliSense), but not MSVC, due to compiler support that has not yet been implemented:

https://github.com/microsoft/STL/blob/1980e1a295be31fd3b377a9ea3c254904b76fc71/stl/inc/yvals_core.h#L952-L957

When this compiler support is available, we should activate these features for MSVC.

**Comment by BurningEnlightenment** [comment]
Thanks for all the hard work. However
> This is currently active for [...] IntelliSense), but not MSVC

From a user point of view it is a bit confusing that IntelliSense (in MSVC mode) happily auto completes/goes to the definition of the affected overload sets. While `cl` fails with the message that said overload sets are not part of the `std` namespace and points to completely unrelated headers. So I think it makes sense to expand `defined(__EDG__)` to `(defined(__EDG__) && !defined(_MSC_VER))` or something similiar. 
Fixing this isn't important, but OTOH it doesn't require much work. Thanks again 😸

**Comment by CaseyCarter** [comment]
That *is* awkward; we should probably guard functionality that works in EDG but not MSVC with `!defined(__INTELLISENSE__)` to keep the IDE consistent with the compiler.

**Comment by StephanTLavavej** [comment]
I think I'd prefer to just drop `|| defined(__EDG__)` here until C1XX gains support, but I agree with the overall proposed change.

**Comment by AlexGuteniev** [comment]
I'm confused about `__cpp_lib_int_pow2` and `__cpp_lib_bitops`.

Currently,  `__cpp_lib_int_pow2` is defined and `__cpp_lib_bitops` is not.

What is the difference?

**Comment by CaseyCarter** [comment]
When you need to know the history of a feature-test macro, or what features are covered by a feature-test macro, go straight to WG21 Stand Document 6 ([SD-6](https://isocpp.org/std/standing-documents/sd-6-sg10-feature-test-recommendations)). It is roughly 1000 times more useful than the working draft, which simply tells you what macros a conforming C++20 implementation defines and with what values.

`__cpp_lib_int_pow2` corresponds to the facilities defined in WG21-P0556 "Integral power-of-2 operations" (`ispow2`, `ceil2`, `floor2`, and `log2p1`) which were later renamed by WG21-P1956 "On the names of low-level bit
manipulation functions" (`has_single_bit` - yes, really - `bit_ceil`, `bit_floor`, and `bit_width`).

`__cpp_lib_bitops` corresponds to WG21-P0553 "Bit operations" (`rotl`, `rotr`, `countl_zero`, `countl_one`, `countr_zero`, `countr_one`, and `popcount`). 

The implementations of all of these functions rely on intrinsics that Clang supports but MSVC does not. We conditionally define `__cpp_lib_bitops` - which is proper, it should only be defined when the facilities with which it corresponds are available. However, we unconditionally define `__cpp_lib_int_pow2` _even though we do not always provide the corresponding functions_ which is most definitely a bug.

**Comment by CaseyCarter** [comment]
This was fixed by the merge of #795.
