### ISSUE TITLE
test: hundreds of failures with Clang 15.0.1

### ISSUE THREAD

**Issue by CaseyCarter** [microsoft/STL#3134]
The IDE team is working through their process to ship Clang 15.0.1 with VS. I'm validating the STL against the new compiler, and seeing (no surprise) hundreds of failures due to the new `unqualified-std-cast-call` warning. This warning diagnoses every unqualified call to `forward` and single-argument `move` in our `using namespace std` tests. I see two ways to keep our tests working with Clang 15:

1. Suppress the warning by adding `-Wno-unqualified-std-cast-call` to every clang config in our `.lst` files. I used this as a quick-and-dirty method to allow me to complete my validation.
2. Avoid the warning by qualifying `move` and `forward` in our tests. 

(1) is by _far_ the lowest-impact alternative: there are around `94` hits for `clang-cl` in `tests/**/*.lst`, and roughly 1.6k matches for `([^:])\b(forward|move)\b([<(])` (which has false positives that are actually multiple-argument `move` calls) under `tests`. (2) would take someone hours to qualify the calls, and someone else hours to review the changes.

(2) is the more useful alternative, since it leaves the warning active to find occurrences of unqualified `forward` and `move` in product code which we do NOT want. So the question here is really "Do we want to spend a few minutes to disable this warning, or invest about a developer day to enable the warning?"

My personal opinion right now is that the benefit of enabling the warning doesn't justify the cost. Our headers are currently clean: `[^D]\s+(move|forward)\b` in `stl/inc` has 164 hits which I believe are all definitions of `forward`/`move` and comments. We've done a good job controlling this issue with code review, which hasn't really been a huge burden since `move` and `forward` are no different from any other "pretty" function.

**Comment by strega-nil-ms** [comment]
I'm personally generally in favor of "qualify more if needed"; however, in this case, I don't think it's particularly useful. `move` and `forward` being the _only_ qualified function in test code is... kinda odd, and I'd prefer to just turn off the warning. I don't think it's particularly useful for product code either, since we expect _all_ function calls to be qualified, not just `move` and `forward`.

**Comment by fsb4000** [comment]
LLVM 15.0.2 is released: https://github.com/llvm/llvm-project/releases/tag/llvmorg-15.0.2

**Comment by CaseyCarter** [comment]
Discussion in the weekly maintainer meeting: @barcharcraz suggests that we could enable this warning _only_ for the include-each-header-alone test. General agreement that the warning is low-value.
