### ISSUE TITLE
`filesystem::path`: concatenating a path via `operator/` leads to a mix of unix/windows separators

### ISSUE THREAD

**Issue by famastefano** [microsoft/STL#3136]
**Describe the bug**
When a path is concatenated via `operator/` like `my_path / "tmp" / "projects"` it always uses the preferred separator, ignoring completely the format the path has been constructed with.
This is standard compliant as stated below, but leads to the following bug:

**Command-line test case**
`cl.exe /EHsc /W4 /WX /std:c++17 ./repro.cpp`
```cpp
#include <filesystem>
#include <iostream>

using std::filesystem::path;
using std::cout;

int main()
{
    auto auto_format    = path("C:/Program Files", path::auto_format)     / "temp";
    auto generic_format = path("C:/Program Files", path::generic_format)  / "temp";
    auto native_format  = path("C:\\Program Files", path::native_format)  / "temp";

    cout << "auto_format : "    << auto_format    << "\n";
    cout << "generic_format : " << generic_format << "\n";
    cout << "native_format : "  << native_format  << "\n";
}
/* Output:
auto_format : "C:/Program Files\\temp"
generic_format : "C:/Program Files\\temp"
native_format : "C:\\Program Files\\temp"
*/
```

**Expected behavior**
From what I understand here:
- [cppreference filesystem/path/format](https://en.cppreference.com/w/cpp/filesystem/path/format)
> Determines how string representations of pathnames **_are interpreted by the constructors_** of [std::filesystem::path](https://en.cppreference.com/w/cpp/filesystem/path) that accept strings.
- [cppreference filesystem/path/ctor](https://en.cppreference.com/w/cpp/filesystem/path/path)
> `path( string_type&& source, format fmt = auto_format );`
> Constructs the path from a character sequence (format **_interpreted as_** specified by fmt) provided by source
- [cppreference filesystem/path/append](https://en.cppreference.com/w/cpp/filesystem/path/append)

The format is used only to interpret the path used to construct the object, not to select a format for that path instance specifically.
Therefore, the path constructors shall always convert the path to the native format.

Another solution might be that `operator/` shall always use the format it has been constructed with, but I suppose that it won't be standard compliant.

**STL version**
```
Microsoft Visual Studio Professional 2022
Version 17.2.8
VisualStudio.17.Release.LTSC.17.2/17.2.8+32901.213

Installed Version: Professional

Visual C++ 2022   00483-10700-13864-AA187
Microsoft Visual C++ 2022
```

**Additional context**
My usecase is providing an absolute path where my unit tests can read/write/delete directories/files, without polluting the environment.
I'm using CMake so the path I use is `CMAKE_BINARY_DIR`, but CMake always uses the "generic_format", unix-style.
This gave me a lot of issues after refactoring as some of my paths where a mix of Unix-style separators and Windows-style separators.

**Comment by cpplearner** [comment]
`C:/Program Files` is a valid path name in the native format. Although `/` is not the preferred directory separator, it is a valid directory separator on Windows.

If you want to convert all directory separators to the preferred separator `\`, you can use the `make_preferred` member function.

**Comment by sylveon** [comment]
Yes, you should be able to use `/` and `\` mixed in the same path with no issues.

**Comment by frederick-vs-ja** [comment]
> But if I compare 2 paths that point to the same directory, just with different separators, they are considered different. That's a problem from my POV though, see [godbolt.org](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DIApACYAQuYukl9ZATwDKjdAGFUtAK4sGe1wAyeAyYAHI%2BAEaYxCAAbKQADqgKhE4MHt6%2BekkpjgJBIeEsUTHxdpgOaUIETMQEGT5%2BXLaY9nkM1bUEBWGR0XG2NXUNWc0KQ93BvcX9sQCUtqhexMjsHOYAzMHI3lgA1CYbbjT0CgCe45gsh9gmGgCCm9u7mAdHTuPEmKw3d48PwQIexYTGCEDmfxMAHYrA89vC9uN0CAQCdMOdLiwUQkmAQEHsEhoIOYzG4QCYAKxuSluZTEVDAYisPYAMTo6JpNIILASJIWBK4xLMpJAAHo6QymSxWeyFKLubzhfyEmYhSLOVSJYzmWzTvKeXzDrD7gjEQRkSglkDDtSjmaLRFUJ4xAkEEw/qbPZ6bTa9hBCW8ACKHQMEjRzN62twHYU0hgkj1epM%2Bu3%2BjRBkMCiMp6MJqnx2NwpNenN%2BhJcDMbUMq7NHX15twFsxGyFQwMcBa0TgU3h%2BDhaUioTjUyzWRFLFavTY8UgETQdhYAaxAGw2ADpV5ut9v4l2OJJe/PB5xeAoQBpZ/OFnBYEg0Dz2WQKBB7wlHygDEYpBoLycCNEzwgCIjwiYJajOTgZ3vNhBAAeQYWgIP7XgsBBIxxGQ0h8C%2BSoADd0SPTBVAqLx/yPQFWiPWg8AiJliDODwsCPAhiDwLFuA7PgDGABQADU8EwAB3WCEkYSDeH4QQRDEdgpBkQRFBUdRMN0ZpP2MaxrH0Giz0gBZUASdozw4ABaJEQ1MUdLDMAdykqZwIFcEYmlIQIpiKEpsmSVIBGcrzcjSHoPP6MZWgqdpOmGTxGj0OyIomIK%2BhiMYJj8lKukSmZkoWBQJ1WPQWMwNYeE7btD0wocOFUAAOWITNiSQ9h2QxgD2KQ1w0Dq/RHKxLFIPZcEIEgYw2Zo9g8B96GIEauDmXg52QuYlxXddtzWzdd04A9SD7AdKtPc9L0W0gb0QEArQSUjyEoV9H1CVg1hquqGqa9S2skDqOt4TB8CIVjkWaSThFEcQ5KBxS1CPVTSEEpkEnE0qOB7Haj0q2DSMuoFUCoPYnvqxrmqMd7PvTCAJrfKaZrmo6tCW0hl1XDd1rW/QtvKvaT1sQ6FtpxGzHZ3h9pphdSHw4gUmcSQgA) Tomorrow I'll make a test to see if I can use a path with mixed separators, if I recall correcly I couldn't create a directory.

It seems that you didn't make the test on Windows, but made the test with libstdc++ on a POSIX OS instead.
