### ISSUE TITLE
unordered_set<string_view> access violation if clear() is called and fast path is taken in debug build

### ISSUE THREAD

**Issue by skottmckay** [microsoft/STL#3137]
**Describe the bug**
If the underlying strings that an unordered_set<string_view> contains are invalidated, a call to unordered_set::clear() will succeed, but the second insert() after that will cause a read access violation when the fast path in clear() is taken (condition is `bucket_count() / 8 > _Oldsize`). 

**Command-line test case**
```
C:\Temp>type repro.cpp
#include <iostream>
#include <vector>
#include <string>
#include <unordered_set>
#include <string_view>

int main() {
  std::vector<std::string> step1 = {"image", "486", "453"};
  std::vector<std::string> step2 = {"image", "486", "453"};

  std::unordered_set<std::string_view> the_set;

  // do a large reserve to create enough buckets so we hit the special case in unordered_set::clear()
  the_set.reserve(2639);

  // add some entries
  for (const auto& str : step1) {
    the_set.insert(str);
  }

  // clear the underlying vector to invalidate the string_view entries
  step1.clear();

  // call clear(), which assumably should not be affected by the string_view values being invalid
  the_set.clear();

  // usage of the set will now break on second insert
  try {
    for (const auto& str : step2) {
      // breaks on second insert.
      the_set.insert(str);
    }
    std::cout << "Success";
  } catch (...) {
    std::cout << "Got exception";
  }
}

C:\Temp>cl /MDd /D "_DEBUG" /EHa /W4 /WX /std:c++17 .\repro.cpp
Microsoft (R) C/C++ Optimizing Compiler Version 19.33.31630 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

repro.cpp
Microsoft (R) Incremental Linker Version 14.33.31630.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:repro.exe
repro.obj

C:\Temp>.\repro.exe
Got exception
```

**Expected behavior**
No read access violation in debug build.

**STL version**
    ```
    Microsoft Visual Studio Enterprise 2022
    Version 17.3.4
    ```

Also affects VS 2019

**Additional context**
Release build seems to be fine. Replace `/MDd` with `/MD` and there's no exception.

**Comment by skottmckay** [comment]
Probably comes down to the fast path using _Unchecked_erase which has an implicit requirement that the values are all still valid as it calls `bucket` to hash values. 

https://github.com/microsoft/STL/blob/2f03bdf361f7f153b4216c60a0d9491c0be13a73/stl/inc/xhash#L1036

**Comment by CaseyCarter** [comment]
This is the result of `clear` hashing elements to determine their buckets in order to achieve the Standard's mandated complexity for `clear`. It's not clear to me (pun intended) if that is conforming or not. If it's not conforming, we'll need to decide whether we prefer to conform to the complexity requirement, or a presumed requirement that we not inspect elements in `clear`.

**Comment by skottmckay** [comment]
Would it be possible to add a check in a debug build to detect this issue? It is quite obtuse and extremely time consuming to figure out why later usage is broken due to the clear() not being able to cleanup the internal state correctly. If it broke during the clear() in at least a debug build it would be far easier to understand the issue.

**Comment by CaseyCarter** [comment]
I don't think there's anything we can do without violating the complexity requirement of `clear`. We've learned our lesson about debug checks that impact complexity in the past: people will put up with slightly larger linear factors in debug runs, but checks that impact complexity encourage people to avoid either the debug checks or the feature itself.
