### ISSUE TITLE
MSVC\14.29.30133\include\xtr1common:20: error: C2894: 模板不能声明为有“C”链接

### ISSUE THREAD

**Issue by GreenTeaHua** [microsoft/STL#3146]
C:\app\VS2019\Community\VC\Tools\MSVC\14.29.30133\include\xtr1common:20: error: C2894: 模板不能声明为有“C”链接

anyone meet this eeor?

**Comment by frederick-vs-ja** [comment]
It seems that you accidently included a standard library header within an `extern "C"` block.

Could you paste the code that triggered this error?

**Comment by StephanTLavavej** [comment]
We talked about this at the weekly maintainer meeting - @frederick-vs-ja's hypothesis sounds very likely here. If this turns out not to be the case, please reopen this and provide a self-contained test case for us to investigate. Thanks!
