### ISSUE TITLE
<atomic>: Broken visualizer for atomic<uint64_t>

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#315]
A user has reported that `atomic<uint64_t>` visualization no longer works due to recent STL changes. We need to add an updated visualizer. (Note that if the previous visualizer worked for VS 2017 and earlier, we should retain it, as `stl.natvis` supports previous versions of the STL.)

Also tracked by DevCom-605247 and Microsoft-internal VSO-936876.

**Visualizer note:** The Visual Studio debugger "visualizes" STL data structures using a file named `stl.natvis`. (Example location: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\Common7\Packages\Debugger\Visualizers\stl.natvis`) This file is updated by Microsoft's STL maintainers because it's deeply connected to the representations of STL data structures, but at this time it isn't part of this GitHub repo.

**Comment by CaseyCarter** [comment]
This visualizer has been fixed internally for Visual Studio 16.5 Preview 2.

**Comment by StephanTLavavej** [comment]
@CaseyCarter Can this issue be closed now?

**Comment by CaseyCarter** [comment]
Yes it can.
