### ISSUE TITLE
STL: Visualizers should display size() and capacity() as unsigned types

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#316]
A few years ago, the Visual Studio debugger added support for "intrinsic functions", allowing users to call things like `size()` and `capacity()` for a `vector` in an expression in the Watch window. A user has observed that these intrinsic functions appear to have signed types, which is contrary to how they're actually implemented in the STL. This might appear to be a superficial issue, but it's confusing at best, and might interfere with conditional breakpoints at worst. We should fix `stl.natvis` to behave like actually compiling `vector` does. (I am unsure whether `vector` is the only type affected; we should check all of the intrinsic functions.)

Also tracked by Microsoft-internal VSO-830421 / [AB#830421](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/830421).

**Visualizer note:** The Visual Studio debugger "visualizes" STL data structures using a file named `stl.natvis`. (Example location: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\Common7\Packages\Debugger\Visualizers\stl.natvis`) This file is updated by Microsoft's STL maintainers because it's deeply connected to the representations of STL data structures, but at this time it isn't part of this GitHub repo.

**Comment by futuarmo** [comment]
Hello! Did you mean convert by "(unsigned int)"? I've modified stl.natvis that way and it works fine
I've checked all "intrinsic" tags and seems like vector is the only place when the problem appears. And also checked the string types (which use intrinsics too) in debugger and everything is fine - size is unsigned int

**Comment by StephanTLavavej** [comment]
I think we'd need to handle 64-bit architectures because a `vector` can easily contain 5 billion elements - but yes, a cast is what I had in mind.

**Comment by futuarmo** [comment]
Yes, of course. I just tried conversion with int. Now I've made it like this:
`<Item Name="[capacity]" Condition="sizeof(void *) == 4u" ExcludeView="simple">(unsigned)capacity()</Item>`
`<Item Name="[capacity]" Condition="sizeof(void *) == 8u" ExcludeView="simple">(unsigned __int64)capacity()</Item>`
Is it right way?  I saw example in std::recursive_mutex

**Comment by StephanTLavavej** [comment]
@AnjuDel fixed this with VS-internal https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/308324 which will ship in VS 2019 16.10 Preview 2 (I am 99% sure).

The visualizers now cast to `(size_t)`.
