### ISSUE TITLE
<ranges>: compiler error ranges::to with ranges::views::split and string_view

### ISSUE THREAD

**Issue by davidhunter22** [microsoft/STL#3179]
First I am not convinced that this is a bug but it seems very odd to me. I was porting some code to use the std::ranges::to in VS 2022  17.4.0 Preview 3 and ran into a compiler error with the following code. 

```c++
void ranges_to_string_view_with_split( )
{
  std::string_view input { "Hello cruel world" };

  auto split { input | std::ranges::views::split( ' ' ) };

  auto m1 { split | std::ranges::to<std::vector<std::string_view>>( ) }; // Compiler error

  assert( m1.size( ) == 3U );
}
```

I compile this with:
> `cl /std:c++latest /EHsc test.cpp`

and I get a compiler error starting with:
> ```
> Microsoft (R) C/C++ Optimizing Compiler Version 19.34.31931 for x86
> c:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.34.31931\include\ranges(6915): error C2672: 'std::ranges::to': no matching overloaded function found
> ```
--- Large amount a error spew follow this

If I change the 'std::ranges::views::split' to say a 'std::ranges::views::filter' things compile fine. Also if I change the 'string_view' to a 'string' it compiles fine. I have experimented with a few other variants and they all seem to work. Now it may be that this code is not supposed to work although I can see why not. Also I did try compiling the code using the ranges::to from Sy Brand's tl library, https://github.com/TartanLlama/tl, and it compiles fine. libc++ and libstdc++ don't seem to have ranges::to yet so I can't test them.

**Comment by CaseyCarter** [comment]
`std::ranges::to<Container>(range)` requires `convertible_to<range_reference_t<decltype(range)>, range_value_t<Container>>` (https://eel.is/c++draft/range.utility.conv.to#1.1). Sy's implementation (https://github.com/TartanLlama/ranges/blob/main/include/tl/to.hpp) doesn't model that convertibility constraint. IIRC, the conversion constraint was added in a late revision of the paper by LWG to mirror the similar requirement for the iterator constructors of standard containers (https://eel.is/c++draft/sequence.reqmts#3.5).

The reference type of `split` in your program is `std::ranges::subrange<std::ranges::iterator_t<std::string_view>>`. WG21-P2499 relatively recently made `string_view`'s arbitrary range constructor `explicit`. `std::ranges::subrange<std::ranges::iterator_t<std::string_view>>` is explicitly, but not implicitly, convertible to `string_view`, so `ranges::to` refuses to convert `split` to `vector<string_view>`. This is conforming, if perhaps unfortunate.

The workaround is to use `views::transform` to explicitly convert the `subrange`s to `string_view`s and feed _that_ to `ranges::to` (https://godbolt.org/z/EPcv8Ecj3):
```c++
template <class To>
constexpr auto convert_to = [](auto&& x) -> To 
{
  return static_cast<To>( std::forward<decltype(x)>( x ) );
};

int main()
{
  std::string_view input { "Hello cruel world" };

  auto m1 = input | std::ranges::views::split( ' ' )
                  | std::ranges::views::transform( convert_to<std::string_view> )
                  | std::ranges::to<std::vector<std::string_view>>( );

  assert( m1.size( ) == 3U );
}
```

**Comment by davidhunter22** [comment]
Thanks for the detailed response. I guess I am feeling a bit :-( about ranges/concepts now.
Looking at the 37 lines of the error message that comes out I don't think I would be able to map it to your explanation, let alone work out how to "fix" it. To me understanding why the code in my issue does not compile while

`
void ranges_to_string_view_filter( )
{
    std::string_view input[] { "Hello", "cruel", "world" };
	
	auto f { input | std::ranges::views::filter( []( auto x ) { return x.size( ) > 4; } )};

    auto m1 { f | std::ranges::to<std::vector<std::string_view>>( ) };
	
    assert( m1.size( ) == 3U );	
}
`

does is completly beyond most C++ programmers.  I have been prgramming C++ for far longer than I care to admit and generally feel that understanding what is wrong in your code and how to fix it, based on compiler errors, has got a lot worse recently. Maybe compilers will get better about this but I am not hopeful. In watching C++ talks I see people talking about making C++ simpler, easier to teach, with fewer exceptions and special cases. Im my view it is failing badly. Anyway rant finshed and thanks again for the answer.
