### ISSUE TITLE
<regex>: Improve the sub_match visualizer with size specifiers

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#318]
See: ["Format specifiers for C++ in the Visual Studio debugger"](https://docs.microsoft.com/en-us/visualstudio/debugger/format-specifiers-in-cpp?view=vs-2019)

Aeons ago, when I implemented the `sub_match` visualizer, I was unable to display the stored substring, because of its representation as a pair of iterators/pointers. At the time, the VS debugger could visualize only null-terminated strings. A few years ago, format specifiers for buffer sizes were implemented. `pBuffer,[bufferSize]` is now supported, and I believe that this can be combined with string visualization to produce `pBuffer,[bufferSize]s`. If this works, we should update `sub_match`'s visualizer.

**Visualizer note:** The Visual Studio debugger "visualizes" STL data structures using a file named `stl.natvis`. (Example location: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\Common7\Packages\Debugger\Visualizers\stl.natvis`) This file is updated by Microsoft's STL maintainers because it's deeply connected to the representations of STL data structures, but at this time it isn't part of this GitHub repo.

**Comment by CaseyCarter** [comment]
@BillyONeal apparently did this in [this internal PR](https://devdiv.visualstudio.com/DevDiv/_git/CppEE/pullrequest/48141) back in 2016.
