### ISSUE TITLE
<concept>: global operator co_await

### ISSUE THREAD

**Issue by 4kangjc** [microsoft/STL#3198]
**Describe the bug**
I want to write a concept about co_await, but it doesn't work
It works well on gcc and clang

**Command-line test case**
```cpp
#include <concepts>

template <class T>
concept has_global_co_await = requires(T&& val) {
    operator co_await(std::forward<T>(val));
};

struct A {

};

auto operator co_await(A) { return "Hello"; }

int main()
{
    static_assert(has_global_co_await<A>);
}
```

**Expected behavior**
work well

**STL version**
* Option 1: Visual Studio version
  * Displayed in Help > About Microsoft Visual Studio
  * Example:
    ```
    Microsoft Visual Studio Professional 2022 
    Version 17.3.6
    ```

**Additional context**

**Comment by frederick-vs-ja** [comment]
For the purpose of tracking: this is a compiler bug, probably same as DevCom-10160851.

**Comment by 4kangjc** [comment]
> For the purpose of tracking: this is a compiler bug, probably same as [DevCom-10160851](https://developercommunity.visualstudio.com/t/10160851).

OK, thank you
