### ISSUE TITLE
P2167R3 Improving `boolean-testable` Usage

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#3211]
[P2167R3](https://wg21.link/P2167R3) Improving *`boolean-testable`* Usage

No feature-test macro is mentioned.

~~It's unclear to me whether there's anything for implementers to do here, or if this is merely a specification cleanup. If we determine that there's nothing to do, we should remove the **cxx23** label, as this was never a feature to begin with.~~ (Edit: It appears that changes do need to be made - thanks @frederick-vs-ja!)

**Comment by frederick-vs-ja** [comment]
IIUC `compare_*_order_fallback` CPOs need to be changed. When the return type of `operator==` or `operator<` doesn't to satisfy _`boolean-testable`_, there should be substitution failure.
