### ISSUE TITLE
LWG-3778 `vector<bool>` missing exception specifications

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#3226]
LWG-3778 `vector<bool>` missing exception specifications

We have some strengthening, but we need to align this with the Standard. (It's okay if we end up with properly-commented strengthening beyond what this LWG issue resolution provides.)

**Comment by frederick-vs-ja** [comment]
Allocator rebinding wasn't discussed in WG21-N4258, and implementations seemly assume that rebound allocators have the same properties of propagation as user-provided allocators. It seems that we can't reasonably implement the standard requirements if `_Choose_pocma_v<_Alvbase>` is `_No_propagate_allocators` while `_Choose_pocma_v<_Alloc>` has a different value.

I think it may be necessary to resolve LWG-3267 more completely by requiring that
- `is_always_equal::value`,
- `propagate_on_container_copy_assignment::value`,
- `propagate_on_container_move_assignment::value`, and
- `propagate_on_container_swap::value`

are all equal for `allocator_traits<X>` and `allocator_traits<Y>`.
