### ISSUE TITLE
LWG-3823 Unnecessary precondition for `is_aggregate`

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#3229]
LWG-3823 Unnecessary precondition for `is_aggregate`

It appears that we'll need to request an MSVC compiler change for this. I haven't checked Clang and EDG's behavior.

**Comment by frederick-vs-ja** [comment]
I've submitted DevCom-10201896 and LLVM-59002 for this. EDG's `__is_aggregate` also rejects arrays of incomplete types.

I believe a workaround using `disjunction_v` is implementable ([Godbolt link](https://godbolt.org/z/dze5dWdcb)). Should we temporarily use such a workaround?

**Comment by CaseyCarter** [comment]
> I believe a workaround using `disjunction_v` is implementable ([Godbolt link](https://godbolt.org/z/dze5dWdcb)). Should we temporarily use such a workaround?

As evidenced by my approval of your PR, I think the workaround is fine.
