### ISSUE TITLE
`<__msvc_int128.hpp>`: UDLs aren't used by product code

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#3240]
`<__msvc_int128.hpp>` spends a hundred lines defining a lot of machinery to implement UDLs:

https://github.com/microsoft/STL/blob/009881898c2112f92ab7ee743eadb148c01329c9/stl/inc/__msvc_int128.hpp#L1423-L1524

These UDLs aren't used by product code at all. They're used by only one test (where they are indeed quite useful):

https://github.com/microsoft/STL/blob/009881898c2112f92ab7ee743eadb148c01329c9/tests/std/tests/P1522R1_difference_type/test.cpp#L40

We typically don't define internal machinery in product code that's used only by test code, as this has a throughput cost. (Separately, this is triggering a `/clr` compiler bug, VSO-1673940 DevCom-10195454 "managed C++ 17.5 error C2049: '`std::literals::_Int128_literals`': non-inline namespace cannot be reopened as inline".)

I believe that we should move these UDLs into the test.

**Comment by frederick-vs-ja** [comment]
My intent was providing a resolution of DevCom-879048 in the STL implementation, and thus these UDLs should be product code, not merely internal machinery.

If this turns out to be unsuitable, I think these UDLs and related test code should be completely removed.

**Comment by StephanTLavavej** [comment]
I think that officially supporting these types and UDLs would fall under our "non-Standard extension" [Non-Goals](https://github.com/microsoft/STL#non-goals).

**Comment by StephanTLavavej** [comment]
We talked about this at the weekly maintainer meeting and agree that the UDLs should be moved into the test code. (The test is already mentioning reserved identifiers, so it would be OK to keep the UDLs with their current names.)
