### ISSUE TITLE
<atomic>: static struct std::atomic<bool> Test::g_test has different type

### ISSUE THREAD

**Issue by justanotheranonymoususer** [microsoft/STL#3241]
**Describe the bug**
I had this warning in my code which I could reduce to the following. I'm not 100% sure it's an STL bug, but I tried asking on StackOverflow and nobody could explain it otherwise.

**Test case**
Create a new console project, compile in x64 release (doesn't reproduce in debug):

### test1.cpp

```cpp
#include <atomic>
#include "test.h"

int main() {
	Test::g_test = true;
}
```

### test2.cpp

```cpp
#include <atomic>

struct A {
	std::atomic<bool> m_test = false;
};

#include "test.h"

void a() {
	Test::g_test = true;
}
```

### test.h

```cpp
#pragma once

struct Test {
    static inline std::atomic<bool> g_test = false;
};
```

**Expected behavior**
No warning and no unexplained `__declspec(align(1))`.

**STL version**
```
Microsoft Visual Studio Community 2022 (64-bit) - Current
Version 17.4.1
```

**Additional context**
Video: https://youtu.be/mLMmzSsWmKs

**Comment by CaseyCarter** [comment]
Thanks for the report! This looks like a compiler issue and not an STL bug. I've reduced the repro and made it library-free, and reported the compiler bug as DevCom-10207002. You can followup there.

For what it's worth, I'm almost positive this warning is safe to ignore. If you're _really_ paranoid, you can disable whole program optimization in your project and it should go away.

**Comment by jaykrell** [comment]
Disabling whole program optimization is NOT a valid workaround.
Next thing you know, we'll disable optimization.
And then just use abacuses.

This bug remains in the latest 19.44 supported compiler and now we have to stop using inline variables to avoid it (not as bad as avoiding link time codegen, granted).
