### ISSUE TITLE
Unused internal identifiers

### ISSUE THREAD

**Issue by strega-nil-ms** [microsoft/STL#3290]
I was reading `<xutility>` and I noticed that we have an old unused `typedef` - `_Any_tag`. In theory, we could remove this.

After realizing this, I figured I'd search for any other internal identifiers that are only used once (and we could theoretically remove/aren't useful - for example, `__std_fs_file_attr::_Archive` is not used elsewhere, but it seems reasonable to have it still).

I literally just tokenized and took a count of all the internal identifiers, so it's likely I've missed stuff.

- `_Alproxy_traits` (`deque`)
- `_Any_tag` (`<xutility>`)
- `_Atomic_load_uchar` (`parallel_algorithms.cpp`, in an anonymous namespace)
- `_Char_class_type` (`_Regex_traits_base` - we could just remove the name)
  + `_Ch_none` is also never used
- `_Generic_reparse_buffer` (`__std_fs_reparse_data_buffer` - we never use it, and we could remove it without changing ABI)
- `_Deque_unchecked_type` (`_Deque_iterator`, we just always use `_Deque_unchecked_iterator<_Mydeque>` anyways)
- `_FieldFlags` (`_Time_parse_fields` similarly  to `_Char_class_type` could be unnamed)
- `_Meta_find_index` (`<variant>`)
- `_Try_resize` (`_Fmt_buffer`)
- `_Unwrapped_sentinel_t` (this doesn't seem that worth it to remove? but eh)
- `_Uses_default_destroy_t`
- `_Iosb` has a few unused enums (`_Dummy_enum`, `enum { _Openprot }`)

**Comment by StephanTLavavej** [comment]
The last time I tried to remove `_Dummy_enum::_Iosb`, it broke ABI (IIRC by changing the export surface), hence the `TRANSITION, ABI` comment:
https://github.com/microsoft/STL/blob/4483e87f6e5aa5c4598404fc01eecb7e547dd439/stl/inc/xiosbase#L26
I forgot about `_Openprot` but the same thing happened:
https://github.com/microsoft/STL/blob/4483e87f6e5aa5c4598404fc01eecb7e547dd439/stl/inc/xiosbase#L90-L92

`_Generic_reparse_buffer` in `__std_fs_reparse_data_buffer` is matching the Windows declaration - I think there's a case for keeping it.

Having names for enums is potentially nicer when debugging.

All of the others look like good candidates for removal to me. Thanks for finding them! :smile_cat:
