### ISSUE TITLE
`<xiosbase>`: Non-conforming extension `ios_base::hexfloat`

### ISSUE THREAD

**Issue by frederick-vs-ja** [microsoft/STL#3296]
**Describe the bug**

MSVC STL provides `ios_base::hexfloat`, which is probably non-conforming.

https://github.com/microsoft/STL/blob/8ddf4da23939b5c65587ed05f783ff39b8801e0f/stl/inc/xiosbase#L47

And the comment seems wrong as `ios_base::hexfloat` is not a part of TR1. It was stated in the final draft of TR1 (WG21-N1836) that:
> [_Note_: Adding the format flag `hexfloat` to class `ios_base` cannot be done without invading namespace `std`, so only the named manipulator is provided. Note also that the more obvious use of `ios_base::hex` to specify hexadecimal floating-point format would change the meaning of existing well defined programs. C++2003 gives no meaning to the combination of `fixed` and `scientific`. —end note]

Should we remove it (maybe in vNext) or make it conforming with an LWG issue or a paper?

**Comment by strega-nil-ms** [comment]
Yeah this is certainly a vNext kind of thing.
