### ISSUE TITLE
<immintrin.h>: Linker-Error when binding _mm256_sub_epi16

### ISSUE THREAD

**Issue by octopus-prime** [microsoft/STL#3309]
**Describe the bug**
Use an stl algorithm, e.g. transform
Bind to the _mm256_sub_epi16 function
Compile ok
Link error

**Command-line test case**
```
#include <immintrin.h>
#include <algorithm>

void showcase() {
	alignas(64) __m256i accumulation[16];
	alignas(64) __m256i weights[16];

	std::ranges::transform(accumulation, weights, accumulation, _mm256_sub_epi16);
}
```
->
```
Erstellen gestartet...
1>------ Erstellen gestartet: Projekt: Project1, Konfiguration: Release x64 ------
1>showcase.cpp
1>showcase.obj : error LNK2001: Nicht aufgelöstes externes Symbol "_mm256_sub_epi16".
1>C:\Users\mikeg\source\repos\Project1\x64\Release\Project1.exe : fatal error LNK1120: 1 nicht aufgelöste Externe
1>Die Erstellung des Projekts "Project1.vcxproj" ist abgeschlossen -- FEHLER.
========== Build: 0 erfolgreich, 1 Fehler, 0 aktuell, 0 übersprungen ==========
========== Erstellen wurde am 9:55 AM gestartet und dauerte 00,581 Sekunden ==========
```
How can the linker miss a CPU instruction? It's always present...

And
```
#include <immintrin.h>
#include <algorithm>

void showcase() {
	alignas(64) __m256i accumulation[16];
	alignas(64) __m256i weights[16];

	auto wtf = [](__m256i a, __m256i b) { return _mm256_sub_epi16(a, b); };
	std::ranges::transform(accumulation, weights, accumulation, wtf);
}
```
builds without any errors.

**Expected behavior**
There should be no need to implement wrapper-functions around intrinsics.
If the compiler accepts the binding, the linker should too.

**STL version**
```
Microsoft Visual Studio Community 2022 (64-Bit) - Preview
Version 17.5.0 Preview 2.0
```

**Comment by fsb4000** [comment]
It might be a compiler issue...

`clang-cl` works fine.

If you need a workaround, you can use `clang-cl` too...

![изображение](https://user-images.githubusercontent.com/4289847/209539863-ea7d3399-ec81-4bca-aca8-38fe86ca13f1.png)

**Comment by fsb4000** [comment]
Reduced example:
```c++
#include <immintrin.h>

template<typename F>
void test(F f) {
	alignas(64) __m256i a{};
	alignas(64) __m256i b{};
	f(a, b);
}

int main(){
	test(_mm256_sub_epi16);
}
```

**Comment by fsb4000** [comment]
It looks like the issue is known since Visual Studio 2013 or earlier: https://stackoverflow.com/questions/32219721/linker-errors-when-using-intrinsic-function-via-function-pointer

**Comment by AlexGuteniev** [comment]
I also reported this, see DevCom-1527806. It is not STL issue.

**Comment by octopus-prime** [comment]
Thanks! Closing the issue because it's not STL issue and - after 10 years with this bug - there is no hope for bugfix.
