### ISSUE TITLE
<header>: offsetof is not a a valid constant expression on clang-based tools

### ISSUE THREAD

**Issue by Lectem** [microsoft/STL#3311]
**Describe the bug**

When using (for example) clang-tidy on a MSVC codebase, it will behave as if it was building using CL.exe, however `offsetof` is currently defined using `reinterpret_cast`, which makes `offsetof` not a valid constant expression.
The error looks like the following:

```cpp
c:\Temp>"C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/Llvm/bin/clang-tidy.exe" --extra-arg-before=--driver-mode=cl repro.cpp --
1 error generated.
Error while processing c:\Temp\repro.cpp.
c:\Temp\repro.cpp:4:18: error: constexpr variable 'fieldOffset' must be initialized by a constant expression [clang-diagnostic-error]
constexpr size_t fieldOffset{ offsetof(SomeStruct, field) };
                 ^
c:\Temp\repro.cpp:4:31: note: cast that performs the conversions of a reinterpret_cast is not allowed in a constant expression
constexpr size_t fieldOffset{ offsetof(SomeStruct, field) };
                              ^
C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\stddef.h:47:32: note: expanded from macro 'offsetof'
        #define offsetof(s,m) ((::size_t)&reinterpret_cast<char const volatile&>((((s*)0)->m)))
                               ^
Found compiler error(s).
```

I thought this could be worked around by setting `_CRT_USE_BUILTIN_OFFSETOF` but you then get warnings `macro name '_CRT_USE_BUILTIN_OFFSETOF' is reserved`. (This is most likely due CMake using the same parameters for both CL.exe and clang-tidy).

**Command-line test case**
```
C:\Temp>type repro.cpp
#include <stddef.h>
struct SomeStruct { int field; };
constexpr size_t fieldOffset{ offsetof(SomeStruct, field) };


C:\Temp>"C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/Llvm/bin/clang-tidy.exe" --extra-arg-before=--driver-mode=cl repro.cpp --
```

**Expected behavior**

No compilation (analysis) error.

**STL version**

Microsoft Visual Studio Community 2019
Version 16.11.13
VisualStudio.16.Release/16.11.13+32413.511

**Additional context**

I am unsure if this should be fixed on the clang-tidy side, or if there is a way to trigger the definition of `_CRT_USE_BUILTIN_OFFSETOF` easily without warning. Do you have background as to why this macro was used instead of a version check ? (A version check would have triggered the `__builtin_offset` even with clang-tidy). One may also use the `__clang_analyzer__ ` macro, but I'm not sure if we want such checks in the STL.
In any case, I thought it might be worth reporting this as Visual Studio now ships with clang-tidy support, and this may come up in the editor. I have not checked the behavior of clang-cl.

Qt also had to add a workaround https://bugreports.qt.io/browse/QTCREATORBUG-19266
I personally used `clang-tidy` with `--extra-arg=-D_CRT_USE_BUILTIN_OFFSETOF` in the meantime.

**Comment by Lectem** [comment]
Note: this seems to be fixed with the latest build of clang-tidy (LLVM version 15.0.6), so this may already be fixed on the clang tool side. Would need to check with clang-tidy shipped in VS2022.

**Comment by CaseyCarter** [comment]
Ideally other clang-based tools would use the same set of header overrides that the compiler itself uses. `<stddef.h>` is such a header: Clang overrides it to provide its own definition of `offsetof` on Windows. `offsetof` isn't the only problematic issue those override headers deal with, so while we could make a fix upstream in the UCRT for this specific issue it would be better to fix all such issues by using the override headers with all tools.
