### ISSUE TITLE
Disabling warnings within C++23's std and std.compat modules

### ISSUE THREAD

**Issue by keris1** [microsoft/STL#3313]
With the old include system, it was possible to use something like this:

```
#pragma warning( push )
#pragma warning( disable : 4702 )
#include <chrono>
#pragma warning( pop )
```

However, with the advent of standardized modules coming in C++23, I see no way to disable warnings in std and std.compat.  In some cases, inlined code can have warnings disabled, but this is quite tedious and negatively affects code quality.  Are there any planned workarounds for this behavior?  I like to enable as many warnings as possible and turn them into errors, and there are many warnings arising from /Wall and /W4 that cannot be handled in user code without deprecating use of some STL functionality.

**Comment by fsb4000** [comment]
Because you build modules yourself you can disable any warnings with `_STL_EXTRA_DISABLED_WARNINGS`

**Comment by keris1** [comment]
My understanding is that in-code disabling using macros does not work without directly modifying std.ixx. Are you suggesting defining these preprocessor symbols at the command line or via the IDE then rather than #define?

**Comment by sylveon** [comment]
Yes

**Comment by fsb4000** [comment]
Yes. project-wide.  Via the IDE or via CMake or something like that.
