### ISSUE TITLE
`<mutex>`: Is `_Mutex_base::try_lock` actually `noexcept`?

### ISSUE THREAD

**Issue by CaseyCarter** [microsoft/STL#3324]
@strega-nil-ms observed in https://github.com/microsoft/STL/pull/3321/files#r1060904759 that `_Mutex_base::try_lock` (which implements `try_lock` for all of the standard mutex types) is not marked `noexcept` despite that the Standard says it "_Throws:_ Nothing". In fact, the function calls `_Throw_C_error`:

https://github.com/microsoft/STL/blob/8ddf4da23939b5c65587ed05f783ff39b8801e0f/stl/inc/mutex#L51-L61
which throws `system_error`:

https://github.com/microsoft/STL/blob/8ddf4da23939b5c65587ed05f783ff39b8801e0f/stl/src/thread0.cpp#L34-L53

Either (1) we're not conforming, or (2) `_Mutex_base::try_lock` only throws on violation of the precondition in [[thread.mutex.requirements.mutex.general]/14](https://eel.is/c++draft/thread.mutex.requirements.mutex.general#14): "If `m` is of type `mutex`, `timed_mutex`, `shared_mutex`, or `shared_timed_mutex`, the calling thread does not own the mutex". If (2) is the case, we should convert the throw into an assertion failure. If (1), we should fix it. In either case, it would be nice to strengthen `noexcept` for `_Mutex_base::try_lock`.

(I'll tag this as a bug until we investigate. (1) is certainly a bug, but (2) an enhancement.)

**Comment by frederick-vs-ja** [comment]
IIRC the throwing code path is now dead, and thus we can eliminate it and make `try_lock` `noexcept`.

Analysis
----
`_Mtx_try_lock` passes a zeroed `xtime` to internal `mtx_do_lock`.
https://github.com/microsoft/STL/blob/73924c1920af92899f7582cd904ea819b9db35bc/stl/src/mutex.cpp#L177-L183

Currently, the control flow goes here (`_Mtx_plain` is no longer used for plain mutexes), setting `res` either `WAIT_OBJECT_0` or `WAIT_TIMEOUT`.
https://github.com/microsoft/STL/blob/73924c1920af92899f7582cd904ea819b9db35bc/stl/src/mutex.cpp#L105-L115

And `res` would be furtherly changed to `WAIT_TIMEOUT`.
https://github.com/microsoft/STL/blob/73924c1920af92899f7582cd904ea819b9db35bc/stl/src/mutex.cpp#L133-L142

Finally, given `*target` is zeroed in `_Mtx_try_lock`, the return value is either `_Thrd_success` or `_Thrd_busy`.
https://github.com/microsoft/STL/blob/73924c1920af92899f7582cd904ea819b9db35bc/stl/src/mutex.cpp#L144-L158

Other concerns
----
UB and a `false` result are not distinguished, while it seems possible to distinguish them.

**Comment by CaseyCarter** [comment]
I agree - great analysis. I believe we should make `_Mutex_base::try_lock` be `noexcept`, and simplify its body to `return  _Mtx_trylock(_Mymtx()) == _Thrd_success;`.
