### ISSUE TITLE
`<syncstream>`: `is_nothrow_move_assignable_v<osyncstream>` is squirrelly 🐿️

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#3355]
WG21-N4928 [\[syncstream.osyncstream.overview\]](https://eel.is/c++draft/syncstream.osyncstream.overview) depicts `basic_osyncstream& operator=(basic_osyncstream&&) noexcept;`. However, it also depicts an exposition-only data member `syncbuf_type sb;` and [\[syncstream.syncbuf.assign\]](https://eel.is/c++draft/syncstream.syncbuf.assign) depicts `basic_syncbuf& operator=(basic_syncbuf&& rhs);` which is **not** `noexcept` (it calls `emit()`).

Our current implementation:

https://github.com/microsoft/STL/blob/fbed7eaec0df4fefec2e447604e12d39d9eab857/stl/inc/syncstream#L348

https://github.com/microsoft/STL/blob/fbed7eaec0df4fefec2e447604e12d39d9eab857/stl/inc/syncstream#L371-L372

https://github.com/microsoft/STL/blob/fbed7eaec0df4fefec2e447604e12d39d9eab857/stl/inc/syncstream#L109-L110

It seems to me that there's an LWG issue here, and that `operator=(basic_osyncstream&&)` should **not** be marked `noexcept` in the Standard (and in our implementation).

Programmer-archaeology: LWG-3498 "Inconsistent `noexcept`-specifiers for `basic_syncbuf`" (already merged into the WP) removed `noexcept` from `operator=(basic_syncbuf&&)` because it calls `emit()`. It seems to me that `operator=(basic_osyncstream&&)` was simply missed at that time.

Noticed while reviewing #3314.

**Comment by frederick-vs-ja** [comment]
LWG-3867 has been reported.
