### ISSUE TITLE
P1645R1 constexpr For <numeric> Algorithms

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#337]
[P1645R1](https://wg21.link/P1645R1) `constexpr` For `<numeric>` Algorithms

Feature-test macro as of WG21-N4842:
`#define __cpp_lib_constexpr_numeric 201911L`

**Comment by contre** [comment]
The link for P1645R1 currently 404s. P1645R0 does exist. I assume R1 is something that will be forthcoming in the post belfast mailing?

**Comment by SuperWig** [comment]
Yeah they're not public yet. Quoting STL

>That’s because the post-Belfast papers are not yet publicly available; when they’re released soon, the link will start working. (I probably should have mentioned this in all of the affected issues. Thanks for bringing it up, sometimes I do mess up links.)

**Comment by StephanTLavavej** [comment]
The link is now active! 😸
