### ISSUE TITLE
<xlocnum>: Incorrect result when parsing 9.999999...

### ISSUE THREAD

**Issue by statementreply** [microsoft/STL#3376]
**Command-line test case**
```
D:\Temp>type test.cpp
```
```cpp
#include <iostream>
#include <sstream>
#include <string>
using namespace std;

int main() {
    istringstream stream("9." + string(1000, '9'));
    cout.precision(17);
    double x;
    if (stream >> x) {
        cout << "actual:   " << x << "\n";
    } else {
        cout << "actual:   (failure)\n";
    }
    cout << "expected: 10\n";
    return 0;
}
```
```
D:\Temp>cl /EHsc /W4 test.cpp
用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.35.32213 版
版权所有(C) Microsoft Corporation。保留所有权利。

test.cpp
Microsoft (R) Incremental Linker Version 14.35.32213.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:test.exe
test.obj

D:\Temp>.\test
actual:   100
expected: 10
```

**STL version**
```
Microsoft Visual Studio Community 2022 (64 位) - Preview
版本 17.5.0 Preview 5.0
```

**Comment by frederick-vs-ja** [comment]
https://github.com/microsoft/STL/blob/f8b8ad6dea901d360d8165cc6719de47ca9d9ca2/stl/inc/xlocnum#L893-L896

Oh, I think I've found the reason - `++_Pten;` is wrong here and we can just strike it. This is actually changing "09..." to "10..." and `_Pten` shouldn't be increased.

However, I guess such logic is actually needed for hexadecimal representations, but not dec ones. For dec representations, "n.999...9" is never a midpoint of binary32/64 FP formats, and the "sticky" parts can be discarded.
