### ISSUE TITLE
Errors when linking x64 OBJ files into ARM64EC programs

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#3382]
When linking x64 OBJ files into ARM64EC programs, users are encountering errors like:

```
error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_8 (EC Symbol)
```

Related to #2635 and #2740.

It appears that for this scenario, we need to provide separately compiled functions in the import lib (the ARM64 import lib?) that x64 object files could be expecting. These functions can perform plain vanilla swaps/reverses/etc., they don't need to be fancy initially. I am not exactly sure what their mangled names should look like, or what the entire fix will look like as a whole. We should be sure to actually validate the fix end-to-end manually (we now have the ability to create ARM64 VMs for internal testing).

Originally reported as DevCom-10219146 and Microsoft-internal VSO-1707080 / AB#1707080 .

**Comment by CaseyCarter** [comment]
We've had yet another customer step on this rake. `<mutex>`/`xonce2.cpp` manifest a similar issue:
```
Rebuild started...
1>------ Rebuild All started: Project: vmwaretestclient, Configuration: Release ARM64EC ------
1>add_person.cc
1>libprotobuf.lib(any.cc.obj) : error LNK2001: unresolved external symbol __imp___std_init_once_begin_initialize (EC Symbol)
1>libprotobuf.lib(map_field.cc.obj) : error LNK2001: unresolved external symbol __imp___std_init_once_begin_initialize (EC Symbol)
```
the ARM64EC import library needs to provide these symbols.
