### ISSUE TITLE
P1902R1 Missing Feature-Test Macros 2017-2019

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#339]
[P1902R1](https://wg21.link/P1902R1) Missing Feature-Test Macros 2017-2019

**Comment by stevenhoving** [comment]
@StephanTLavavej fyi the wg21 link doesn't seem to work

**Comment by StephanTLavavej** [comment]
That’s because the post-Belfast papers are not yet publicly available; when they’re released soon, the link will start working. (I probably should have mentioned this in all of the affected issues. Thanks for bringing it up, sometimes I do mess up links.)

**Comment by StephanTLavavej** [comment]
This link is now active! 😸
