### ISSUE TITLE
`<ranges>`: `views::repeat(...) | views::take(...)` is not always a valid range

### ISSUE THREAD

**Issue by JMazurkiewicz** [microsoft/STL#3392]
**Command-line test case**
```c++
#include <ranges>

using namespace std;

const auto rice = views::repeat("🌾"sv, 100zu); // difference_type is _Signed128
const auto taken_rice = rice | views::take(3);
static_assert(ranges::range<decltype(taken_rice)>); // error!
```

```console
PS D:\stl-playground> clang-cl /std:c++latest /Zs .\iota_diff.cpp
In file included from .\iota_diff.cpp:1:
In file included from D:\stl\Out\build\x64\out\inc\ranges:16:
In file included from D:\stl\Out\build\x64\out\inc\iterator:12:
In file included from D:\stl\Out\build\x64\out\inc\xutility:12:
D:\stl\Out\build\x64\out\inc\__msvc_iter_core.hpp(96,1): error: no type named 'difference_type' in 'std::incrementable_traits<std::_Signed128>'
using iter_difference_t = typename conditional_t<_Is_from_primary<iterator_traits<remove_cvref_t<_Ty>>>,
^~~~~
[...]
```

The main reason of this error is that `_Signed128` does not model `weakly_incrementable`.

**Expected behavior**
This code should compile.

**Additional context**
The truth is that standard does not require `_Signed128` to model `weakly_incrementable` ([[range.iota.view]/1](http://eel.is/c++draft/range.iota.view#1)), but it would be **very** nice if it did:

```c++
#include <ranges>

using namespace std;

using X = ranges::_Iota_diff_t<size_t>;
static_assert(!weakly_incrementable<X>);
using Y = ranges::_Iota_diff_t<X>; // <= compile error
```

**Comment by frederick-vs-ja** [comment]
I've verified that `ranges::repeat_view<T, _Signed128>` and `ranges::repeat_view<T, _Unsigned128>` are both broken.

I guess the title of this issue should be changed to "`<ranges>`: `ranges::repeat_view<T, IntegerClass>` is broken".

----
This is probably a defect in current specification, and an LWG issue seems needed.

[[range.repeat.iterator]](https://eel.is/c++draft/range.repeat.iterator) says
```C++
    using difference_type = conditional_t<is-signed-integer-like<index-type>,
        index-type,
        IOTA-DIFF-T(index-type)>;
```
which always instantiates _`IOTA-DIFF-T`_`(`_`index-type`_`)`, and thus possibly makes the program ill-formed when _`index-type`_ (same as `Bound` in such case) is an integer-class type.

I think the intent is when _`index-type`_ is signed-integer-like, it is used as-is without instantiating _`IOTA-DIFF-T`_, which fix cases for signed integer-class types. But this may be still broken when `_Bound` is an unsigned integer-class type (`_Unsigned128` in MSVC STL).

**Comment by frederick-vs-ja** [comment]
Oh, there seems another issue.

It's arguably better if `views::take` & `views::drop` preserve the bound type of `repeat_view` whenever possible. When `E` is an unbounded `repeat_view`, I guess `views::take(E, F)` should return a `repeat_view` whose bound type is either `ptrdiff_t` or `decltype(auto(F))` (in which case this type must be integer-like).
