### ISSUE TITLE
STL Contributors Survey 2023

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#3398]
New year, new survey! Microsoft regularly runs this survey to understand your experience of contributing to this repo. This helps us identify areas where we can improve our processes to make it easier to participate.

Speaking for myself, I have been amazed by all of your contributions since we open-sourced this codebase in 2019. I've been working on the STL since 2007 and back then I never imagined I'd be reviewing PRs from experts all around the world! One of the most important parts of my job now is building an environment here where everyone can be productive and implement features and improvements for the future of C++. I personally review the results of these surveys to see what I should focus on. The survey results are also reviewed by the other STL maintainers, MSVC management, and DevDiv upper management (who approved our open-sourcing in the first place).

Survey link: ~~https://www.surveymonkey.com/r/8KTX9VT?Source=RepoLink~~ (now closed)

Thanks for your time and contributions, as always.

:red_square::green_square: :smiley_cat::smile_cat:
:blue_square::yellow_square: :joy_cat::heart_eyes_cat:

**Comment by Amaroker** [comment]
I would like to contribute, but last time I was asked to sign an agreement. If I remember correctly, there was a requirement to consent to exclusive jurisdiction clause where only laws of the State of Washington applies (as a non-US citizen I know nothing about American laws) and some other mumbo jumbo. Is this still necessary?

**Comment by fsb4000** [comment]
Yes, https://opensource.microsoft.com/pdf/microsoft-contribution-license-agreement.pdf
I don't know about this nonsense either. 
In my country I can do whatever I want before/after work without any permissions, so for me this sentence works: 
>I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer

**Comment by miscco** [comment]
Signing the CLA is still critical for corporations to ensure they indeed own the intellectual property to the code submitted and are not liable in any way. 

Your personal legal situation is highly dependent on your country of origin, your contract and your employer so there is no generic answer here.

**Comment by StephanTLavavej** [comment]
Yep, we still require contributors to agree to the Microsoft CLA. The CLA Bot changed somewhat recently to simply ask for a comment saying that you agree, instead of the previous process of electronically signing a form. (It still activates for patch sizes above a de minimis threshold.) This policy is organization-wide and applied to all repos automatically.

I can't offer any interpretation of the CLA's paragraphs - you have to read it and decide whether it's something you want to agree to.

If you want, you can take the survey and leave a comment about the CLA policy. (I believe there should be a freeform field for such feedback, although I haven't taken the survey myself as I am a maintainer.)

**Comment by StephanTLavavej** [comment]
The survey is now closed. Thanks to everyone who responded!

**Comment by MahmoudGSaleh** [comment]
Thanks to everyone who participated in the survey. Here are the survey results for this year:

![stl_survey_results_2023](https://user-images.githubusercontent.com/12202790/228938419-f041dda0-e885-442a-b67d-3018fe0dd84c.png)
