### ISSUE TITLE
<functional>: _HAS_STATIC_RTTI=0 shouldn't say typeid(void)

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#340]
We have a supported (obscure) mode `_HAS_STATIC_RTTI=0` which disables most occurrences of `typeid(Type)`. However, it says `typeid(void)` in a couple of places (I believe these are the only occurrences):

https://github.com/microsoft/STL/blob/8f4c8163775d665d80642044ce27c4bc696127ce/stl/inc/functional#L866-L870
https://github.com/microsoft/STL/blob/8f4c8163775d665d80642044ce27c4bc696127ce/stl/inc/functional#L930-L934

When I implemented this in April 2017, my checkin notes said:

> We must provide virtuals, so make this one return `typeid(void)`. (This is a single use of static RTTI, but always for the same type. I felt that this was superior to terminating.) `typeid(void)` is what's used for empty `std::function`s, so it's a reasonable return value.

It turns out that clang.exe has a mode, `-fno-rtti`, which makes `typeid` an error, even `typeid(void)`. I believe we should change `_HAS_STATIC_RTTI=0` to never say `typeid(void)`.

**Comment by SuperWig** [comment]
A bit off topic but wow those double `// _HAS_STATIC_RTTI` right next to each other is... The opposite of helpful.
