### ISSUE TITLE
LWG-3870 Remove `voidify`

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#3431]
LWG-3870 Remove *`voidify`*

**Comment by frederick-vs-ja** [comment]
WOW! Since `operator=`, `swap`, and `emplace` of `expected` are specified with `construct_at` ([[expected.expected]](https://eel.is/c++draft/expected.expected)), they are now completely broken for a `const` or `volatile` `value_type`.

**Comment by CaseyCarter** [comment]
> WOW! Since `operator=`, `swap`, and `emplace` of `expected` are specified with `construct_at` ([[expected.expected]](https://eel.is/c++draft/expected.expected)), they are now completely broken for a `const` or `volatile` `value_type`.

@frederick-vs-ja Have you reported this to LWG?

**Comment by frederick-vs-ja** [comment]
> > WOW! Since `operator=`, `swap`, and `emplace` of `expected` are specified with `construct_at` ([[expected.expected]](https://eel.is/c++draft/expected.expected)), they are now completely broken for a `const` or `volatile` `value_type`.
> 
> @frederick-vs-ja Have you reported this to LWG?

No, I haven't. I'm not sure how to fix `swap`...
