### ISSUE TITLE
LWG-3878 `import std;` should guarantee initialization of standard iostreams objects

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#3436]
LWG-3878 `import std;` should guarantee initialization of standard iostreams objects

Need to investigate whether our iostreams machinery achieves this automatically, or if we need to do something special for Standard Library Modules. It sure seems like I can use `cout` normally.

**Comment by CaseyCarter** [comment]
`cout` works fine with no dynamic initializer in the TU for `std::ios_base::Init`. We use some `#pragma init_seg(compiler)` trickery to ensure that `cout` et al. are initialized before dynamic initializers run. This is all true for both modules and non-modules builds.

**Comment by StephanTLavavej** [comment]
Thanks, that explains it. I think we can close this.
