### ISSUE TITLE
P2652R2 Disallowing User Specialization Of `allocator_traits`

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#3443]
WG21-P2652R2 Disallowing User Specialization Of `allocator_traits`

No feature-test macro is mentioned.

In addition to this paper's observable changes, there's the question that @frederick-vs-ja raised on Discord - what to do about:

> If a program declares an explicit or partial specialization of `allocator_traits`, the program is ill-formed, no diagnostic required.

We could do nothing (allowing squirrelly programs to be bad kitties :chipmunk: :smirk_cat:), or we could implement enforcement (with possible throughput impact and extensive codebase edits).

**Comment by CaseyCarter** [comment]
> We could do nothing (allowing squirrelly programs to be bad kitties 🐿️ 😼), or we could implement enforcement (with possible throughput impact and extensive codebase edits).

I _think_ we could minimize throughput issues by simply renaming `allocator_traits` to something `_Ugly` and making a new `allocator_traits` alias template. If that's not conforming (I've given it a whole 30 seconds of thought) it could at least be useful to hack up such a change and throw it at RWC and Windows to see what breaks. I'd hate for anyone to invest a lot of effort into enforcement only to learn it would be so breaking that we can't do it in practice.

**Comment by frederick-vs-ja** [comment]
> > We could do nothing (allowing squirrelly programs to be bad kitties 🐿️ 😼), or we could implement enforcement (with possible throughput impact and extensive codebase edits).
> 
> I _think_ we could minimize throughput issues by simply renaming `allocator_traits` to something `_Ugly` and making a new `allocator_traits` alias template. If that's not conforming (I've given it a whole 30 seconds of thought) it could at least be useful to hack up such a change and throw it at RWC and Windows to see what breaks. I'd hate for anyone to invest a lot of effort into enforcement only to learn it would be so breaking that we can't do it in practice.

Unfortunately, this would break the seemingly reasonable code:
```C++
template<class T, template<class...> class Templ>
inline constexpr bool is_specialization_of = false;

template<template<class...> class Templ, class... Args>
inline constexpr bool is_specialization_of<Templ<Args...>, Templ> = true;

static_assert(is_specialization_of<std::allocator_traits<int>, std::allocator_traits>);
```
