### ISSUE TITLE
P2675R1 Improving `std::format`'s Width Estimation

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#3446]
WG21-P2675R1 Improving `std::format`'s Width Estimation

No feature-test macro is mentioned.

**Comment by achabense** [comment]
I hope to work on this.

According to the paper, I need to look for all ranges marked `;W` or `;F` in
https://www.unicode.org/Public/UCD/latest/ucd/EastAsianWidth.txt or
https://www.unicode.org/Public/15.0.0/ucd/EastAsianWidth.txt (current latest version)
and combine them with `U+4DC0 – U+4DFF`, ` U+1F300 – U+1F5FF` and `U+1F900 – U+1F9FF` to make a table, then update `_Width_estimate_intervals`:
https://github.com/microsoft/STL/blob/8d18fec555022f4f355dabbb8e8c1893c91f5553/stl/inc/format#L981-L982

Is it enough to complete this feature by ~?
1. Introduce a parser to `/tools`, taking the `.txt` file as input to make the new table
2. Update `_Width_estimate_intervals`, and do optimizations if necessary

**Comment by achabense** [comment]
I'm confused by this:
[20000..2FFFF, 30000...3FFFF](https://www.unicode.org/reports/tr11/#:~:text=the%20Supplementary%20Ideographic,Plane%2C%2030000..3FFFF)
vs
[20000..2FFFD, 30000...3FFFD](
https://www.unicode.org/Public/UCD/latest/ucd/EastAsianWidth.txt#:~:text=Plane%202%3A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20U%2B20000..U%2B2FFFD%0A%23%20%20%20%20%20%20%20%20%20Plane%203%3A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20U%2B30000..U%2B3FFFD)
By taking the second one(that in the `EastAsianWidth.txt` file), I can now reproduce exactly the same result as in `Annex: Exhaustive list of changes` in the [paper]((https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2023/p2675r1.pdf)).

**Comment by frederick-vs-ja** [comment]
> Do I need to update the table directly, or keeping the old table in C++20 mode?

I believe we should change the table in C++20 mode, as P2675R1 is essentially the resultion of LWG-3780. MSVC STL gererally implement resolutions of LWG issues when they are merely fixes of old features.
