### ISSUE TITLE
P2713R1 Escaping Improvements In `std::format`

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#3449]
WG21-P2713R1 Escaping Improvements In `std::format`

No feature-test macro is mentioned.

**Comment by frederick-vs-ja** [comment]
I think this is patching WG21-P2286R8.

**Comment by StephanTLavavej** [comment]
You're right, it's patching the newly added section \[format.string.escaped\]. Thanks! :heart_eyes_cat: I'll fuse this into #2919.
