### ISSUE TITLE
LWG-3631 `basic_format_arg(T&&)` should use `remove_cvref_t<T>` throughout

### ISSUE THREAD

**Issue by CaseyCarter** [microsoft/STL#3460]
LWG-3631 `basic_format_arg(T&&)` should use `remove_cvref_t<T>` throughout

We have a comment indicating something is consistent with an early version of the resolution, but we need some work to implement the final resolution. (Note that we do not yet implement the `formattable` concept from WG21-P2286R8 #2919 "Formatting Ranges".)

**Comment by mordante** [comment]
Note the definition of the `formattable` concept in the final resolution is incorrect. See [LWG 3925](https://cplusplus.github.io/LWG/issue3925) for the details and the proposed fix.
