### ISSUE TITLE
<shared_mutex>: Do we still need the _USING_V110_SDK71_ guard?

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#347]
When we implemented `shared_mutex`, we guarded it against `_USING_V110_SDK71_`:

https://github.com/microsoft/STL/blob/1e8b8d4eef4b2dddeb7533c5231c876383bd0ea6/stl/inc/yvals_core.h#L896-L898
https://github.com/microsoft/STL/blob/1e8b8d4eef4b2dddeb7533c5231c876383bd0ea6/stl/inc/shared_mutex#L31-L33

`shared_mutex` requires `SRWLOCK`, unavailable on Windows XP. At the time, we shipped the `v140_xp` toolset, which defined `_USING_V110_SDK71_`.

Now, while our separately compiled `msvcp140.dll` must continue to support running on Windows XP, we no longer ship an XP-targeting toolset, and we don't support programmer-users attempting to target Windows XP.

Accordingly, I believe that the `_USING_V110_SDK71_` guard should be removed.

**Comment by BillyONeal** [comment]
>we no longer ship an XP-targeting toolset

Is that true? I thought we just deprecated it.

**Comment by StephanTLavavej** [comment]
https://docs.microsoft.com/en-us/cpp/overview/what-s-new-for-visual-cpp-in-visual-studio?view=vs-2019 says:

> Windows XP targeting will no longer be available for the latest C++ toolset. XP targeting with VS 2017-level MSVC compiler & libraries is still supported and can be installed via "Individual components."

**Comment by BillyONeal** [comment]
Woot 

(╯°□°）╯︵ ┻x━p┻
