### ISSUE TITLE
STL: Include stl.natvis in this repository

### ISSUE THREAD

**Issue by KindDragon** [microsoft/STL#349]
Natvis file should be in that repository and linked to pdb file ([/natvis](https://docs.microsoft.com/en-us/cpp/build/reference/natvis-add-natvis-to-pdb?view=vs-2019))
Example:
https://github.com/microsoft/GSL/blob/7e99e76c9761d0d0b0848b91f8648830670ee872/CMakeLists.txt#L79-L81

Also, `natstepfilter` and `natjmc` file could be also useful

**Comment by StephanTLavavej** [comment]
I agree! We should work with the IDE team to make this possible. (Testing `stl.natvis` is currently the most significant issue to resolve here, as I understand it.)
