### ISSUE TITLE
source_location::current() is wrong when used for a variant or optional in arguments

### ISSUE THREAD

**Issue by HaydnVH** [microsoft/STL#3505]
**Describe the bug**
When used as a default argument for a function that takes an `std::source_location`, the value returned by `std::source_location::current()` is correct; it captures the location where the function is _called_, not defined.  However, if `std::source_location::current()` is used as a default argument for a type of `std::optional<std::source_location>` or `std::variant<std::source_location, ...>`, it erroneously captures the location of where the function is _defined_, not called.

**Command-line test case**
```
C:\Temp>type repro.cpp
#include <iostream>
#include <source_location>
#include <variant>
#include <optional>
#include <assert.h>

std::source_location getHereNormal(std::source_location src = std::source_location::current()) {
  return src;
}

struct GetHereStruct {
  GetHereStruct(std::source_location src = std::source_location::current()) : src_(src) {}
  std::source_location src_;
  auto get() { return src_; }
};

std::source_location getHereOptional(std::optional<std::source_location> src = std::source_location::current()) {
  return *src;
}

std::source_location getHereVariant(std::variant<std::source_location, const char*> src = std::source_location::current()) {
  return std::get<std::source_location>(src);
}

int main() {
  size_t line;
  line = getHereNormal().line();          std::cout << "Line = " << line << std::endl; assert(line == 27); // Passes
  GetHereStruct s; line = s.get().line(); std::cout << "Line = " << line << std::endl; assert(line == 28); // Passes
  line = getHereOptional().line();        std::cout << "Line = " << line << std::endl; assert(line == 29); // FAILS! Reports 17
  line = getHereVariant().line();         std::cout << "Line = " << line << std::endl; assert(line == 30); // FAILS! Reports 21
  return 0;
}
C:\Temp>cl /std:c++20 /EHsc /W4 /WX .\repro.cpp
Microsoft (R) C/C++ Optimizing Compiler Version 19.23.28019.1 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

repro.cpp
Microsoft (R) Incremental Linker Version 14.23.28019.1
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:repro.exe
repro.obj

C:\Temp>.\repro.exe
test failure
```

**Expected behavior**
Calling `std::source_location::current()` as a default function argument should always capture the location where that function is _called_, even if it's used to initialize some other object.

**STL version**
Microsoft Visual Studio Community 2022 (64-bit) - Current
Version 17.5.0

**Additional context**
In GCC 12.2, all of the above tests pass and `std::source_location::current()` behaves as expected.  In Clang 15.0.0, all 4 tests fail.

**Comment by StephanTLavavej** [comment]
This definitely appears to be a compiler bug, so it should be reported to [Developer Community](https://developercommunity.visualstudio.com/home) where it will be assigned to the compiler team.

**Comment by frederick-vs-ja** [comment]
I think this is closely related to #3138/DevCom-10224094...

**Comment by StephanTLavavej** [comment]
I suspect that this was just fixed by internal MSVC-PR-456552 for VS 2022 17.7 Preview 1. I've reached out to @JonCavesMSFT for confirmation.

**Comment by StephanTLavavej** [comment]
We should check the behavior of VS 2022 17.7 Preview 1 which contains MSVC-PR-457217.

**Comment by nuuSolutions** [comment]
I'm seeing the same. Looks like a clang 'feature' to me. It also happens in compiler explorer - without Microsoft being involved ;-)
Suspicion: they (clang) handle default arguments differently internally

**Comment by frederick-vs-ja** [comment]
I've checked that the original example is correctly accepted by MSVC in VS 2022 17.7 P1 (for MSVC).

Clang 16 also works, but we need to wait for 17.7 P2 which includes the changes in #3584 (enabling `<source_location>` for Clang).

**Comment by achabense** [comment]
It appears this issue is already fixed now.

**Comment by CaseyCarter** [comment]
I concur: both MSVC and clang-cl compile this program correctly in 17.8p1.
