### ISSUE TITLE
<vector>: What is _Alloc_temporary2 used for in vector<T>::insert(_Where, _Count, _Val)?

### ISSUE THREAD

**Issue by Kami-chanw** [microsoft/STL#3507]
Here is the entire code of insert:
https://github.com/microsoft/STL/blob/16bb556afe5c56fe70a5508a6116842c226dd3be/stl/inc/vector#L1008-L1085
Here is the code that I want to ask:
```
           const _Alloc_temporary2<_Alty> _Tmp_storage(_Al, _Val); // handle aliasing
            const auto& _Tmp              = _Tmp_storage._Get_value();
            const auto _Affected_elements = static_cast<size_type>(_Oldlast - _Whereptr);
            _Orphan_range(_Whereptr, _Oldlast);

            _ASAN_VECTOR_EXTEND_GUARD(static_cast<size_type>(_Oldlast - _My_data._Myfirst) + _Count);
            if (_Count > _Affected_elements) { // new stuff spills off end
                _Mylast = _Uninitialized_fill_n(_Oldlast, _Count - _Affected_elements, _Tmp, _Al);
                _Mylast = _Uninitialized_move(_Whereptr, _Oldlast, _Mylast, _Al);
                _STD fill(_Whereptr, _Oldlast, _Tmp);
            } else { // new stuff can all be assigned
                _Mylast = _Uninitialized_move(_Oldlast - _Count, _Oldlast, _Oldlast, _Al);
                _Move_backward_unchecked(_Whereptr, _Oldlast - _Count, _Oldlast);
                _STD fill(_Whereptr, _Whereptr + _Count, _Tmp);
            }
            _ASAN_VECTOR_RELEASE_GUARD;
```
Why creates `_Tmp_storage` and construct values from it instead of the parameter?
I guess there are two possibilities:
1. Satefy guarantee: construct values before moving/copying data to prevent throws during copy construction of `value_type`. If under such a consideration, why not use `std::is_nothrow_copy_constructible` then implement the corresponding case to avoid redundant construction of the object?
2. Construct value by using allocator.

**Comment by StephanTLavavej** [comment]
`// handle aliasing` is the (extremely terse) explanation. It handles the case where `const _Ty& _Val` refers to an element within the `vector` itself. In this case, we need to create a local copy, because moving elements around in the vector might invalidate `_Val`.
