### ISSUE TITLE
performance improvements  when _STL_OPTIMIZE_SYSTEM_ERROR_OPERATORS  defined

### ISSUE THREAD

**Issue by vinniefalco** [microsoft/STL#3514]
Consider the following program (https://godbolt.org/z/vEY9MojxW)

```cpp
#include <future>
#include <system_error>

bool f1()
{
    return
        std::error_code( std::io_errc::stream ) ==
        std::future_errc::no_state;
}

bool f2()
{
    return
        std::error_condition( std::errc::address_not_available ) ==
        std::errc::address_in_use;
}

int main()
{
    return f1() + f2();
}
```

With `_STL_OPTIMIZE_SYSTEM_ERROR_OPERATORS` defined, the right hand side must first be constructed from an enum:

https://github.com/microsoft/STL/blob/16bb556afe5c56fe70a5508a6116842c226dd3be/stl/inc/system_error#L212

https://github.com/microsoft/STL/blob/16bb556afe5c56fe70a5508a6116842c226dd3be/stl/inc/system_error#L216

Then the categories are compared followed by the value:
https://github.com/microsoft/STL/blob/16bb556afe5c56fe70a5508a6116842c226dd3be/stl/inc/system_error#L213

This could be improved further by adding a member operator== which accepts an integral value on the right hand side and performs the numerical comparison first as a trivial reject. There could be some issues with this, making this a function template and adding a constraint could increase compile times. It would need some thought.

In any case, I have written an extensive amount of parsing and network code that uses error_code inside of tight loops and it is often the case that related functions appear higher up in performance profiles than I am comfortable with. If the standard is preventing performance improvements with overlay constraining requirements, we should consider writing a paper to amend it. The guidance from experience when defining `_STL_OPTIMIZE_SYSTEM_ERROR_OPERATORS` would be helpful.

**Comment by frederick-vs-ja** [comment]
It seems that `_STL_OPTIMIZE_SYSTEM_ERROR_OPERATORS` only turns operators exposed in namespace `std` into hidden friends, (almost) without changing their definitions, so it probably has no affection on performance. This strategy is non-conforming ([Godbolt link](https://godbolt.org/z/aW8cTfjYW)), but such non-conformance perhaps only affects a relatively small amount of codes.

I think we can do such optimizations - adding something like `bool operator==(const error_code&, errc);` (and its friends, but need to be valid in C++14) as hidden friends, and defining it like this
```C++
inline bool operator==(const error_code& ec, errc ec_enum) noexcept {
    return ec.category()._Compared_addr() == _Generic_addr && ec.value() == static_cast<int>(ec_enum);
}
```

The operators should be hidden friends and be constrained to not to affect any user-defined error enums. I believe such optimization can be conforming.

**Comment by vinniefalco** [comment]
> it probably has no affection on performance

My guess is that it has to do with compilation performance. While the issue I am reporting has to do with runtime performance.

**Comment by StephanTLavavej** [comment]
We talked about this at the weekly maintainer meeting. While there may indeed be performance considerations here, we are *extremely wary* of altering overload sets, especially for an area that's already as complicated as the `<system_error>` operators. We believe that if anything should be done, it should take the form of an LWG issue or paper that overhauls the operators (ideally making 'em hidden friends while in the neighborhood).
