### ISSUE TITLE
fmt\format.h(3200,1): fatal  error C1001

### ISSUE THREAD

**Issue by shithappens2016** [microsoft/STL#3544]
17.6.0 Preview 1.0

**abc.ixx**
```C++
module;

#include <fmt/xchar.h>
#include <fmt/color.h>

export module abc;

export class abc
{
public:
   static void test() {
      fmt::print(L"{}", L "abc");
   }
};
```

**main.cpp**
```C++
import abc;

int main() {
  abc::test();
  return 0;
}
```

```
/std:c++latest
/experimental:module
```

**Comment by StephanTLavavej** [comment]
Fatal error C1001 is an internal compiler error (ICE), which is a compiler bug by definition. As our readme explains, compiler bugs should be reported to [Visual Studio Developer Community](https://developercommunity.visualstudio.com/home), where the compiler team can follow up with you (and let you know when the bug has been fixed). While libfmt may be using the STL and the combined library code results in an ICE, we library maintainers have no way to directly investigate this, and the fix must happen in the compiler. I can't transfer microsoft/STL GitHub issues to DevCom, so you'll need to report it there yourself - apologies for asking you to report it again.

As an aside, `/experimental:module` is no longer needed for Standard module support; `/std:c++latest` for C++23 (or `/std:c++20`) is sufficient.
