### ISSUE TITLE
`<ranges>`: `ranges::equal` does not work for ranges with integer-class `range_difference_t`

### ISSUE THREAD

**Issue by JMazurkiewicz** [microsoft/STL#3550]
Repro:

```c++
#include <algorithm>
#include <ranges>

using namespace std;

void f() {
  auto v = views::iota(0ull, 5ull) | views::stride(2); // range_difference_t<v> == _Unsigned128
  auto w = views::iota(0ull, 5ull) | views::stride(2);
  (void)ranges::equal(v, w);
}
```

Expected: *correct compilation*
Got: *error* (see link below)
Compiler explorer: https://godbolt.org/z/crcbMfY7z
Discovered while implementing #2923

**Comment by StephanTLavavej** [comment]
Yep, this seems like a bug in `_Equal_count`, with a very simple fix. A brief search indicated no other occurrences of `integral _Size` so hopefully this is the only one.
