### ISSUE TITLE
filesystem_space.cpp: Consider avoiding reinterpret_cast

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#357]
https://github.com/microsoft/STL/blob/da0d8cfdef750abd55e1874b81252b99934c1329/stl/src/filesystem_space.cpp#L19-L33

In https://github.com/microsoft/STL/pull/356#discussion_r355020948, @sylveon asked whether this `static_assert` and `reinterpret_cast` technique is necessary. I believe that we could avoid this by defining `ULARGE_INTEGER` local variables, passing their addresses to `GetDiskFreeSpaceExW()`, and then if successful, writing their `QuadPart`s to `_Available`, `_Total_bytes`, and `_Free_bytes`. This would involve a few more instructions, but I don't believe that the code size and runtime impact would be observable, and avoiding `reinterpret_cast` may be worth it.

**Comment by BillyONeal** [comment]
I don't see any value in avoiding the reinterpret_cast.

**Comment by StephanTLavavej** [comment]
I'd argue that there's a minor benefit. `reinterpret_cast` is the scariest cast, so avoiding it whenever possible makes the remaining necessary occurrences stand out more, where they can be carefully analyzed for correctness.

That said, because this is a separately compiled source file calling a separately compiled API, we don't need to worry about things like strict aliasing, and I certainly don't think that there are major benefits.

I'm happy to close this as `wontfix` if nobody feels strongly about it.

**Comment by sylveon** [comment]
If `uintmax_t` ever becomes bigger in the future (like 128-bits), there could be a benefit to doing 
```cpp
void DoThing(uintmax_t *size)
{
	ULARGE_INTEGER u;
	GetFileSizeOrWhatever(&u);
	*size = u.QuadPart;
}
```
because then the source code would not require manual adjustment due to an implicit conversion happening (although, the `static_assert` already makes sure that such a breakage does not go silent)

**Comment by StephanTLavavej** [comment]
That's true (although changing the size of `uintmax_t` would be ABI-breaking, and is unlikely to happen within a decade).

**Comment by sylveon** [comment]
I can make a PR for this tomorrow if there's no objections.

**Comment by StephanTLavavej** [comment]
I think such a PR would be useful for us to compare the before and after states, although we may decide against changing anything here, depending on what the other STL maintainers think. (If the necessary change were extensive, I'd advise against doing work that might not be accepted, but this change should be quite small and easy to validate by just building.)

**Comment by BillyONeal** [comment]
>I'd argue that there's a minor benefit. reinterpret_cast is the scariest cast, so avoiding it whenever possible makes the remaining necessary occurrences stand out more, where they can be carefully analyzed for correctness.

I guess I find the cast less offensive than the code that I think is going to have to be written instead (more things to get wrong, more wires to get crossed, etc). Plus the codegen will be worse (though that's secondary).

Certainly not an over my dead body thing.

>we don't need to worry about things like strict aliasing

There's no strict aliasing issue here due to the common initial subsequence rule, and this is a cast from a struct to the type of its first member.

**Comment by StephanTLavavej** [comment]
After comparing the before-and-after code, a majority of the team preferred to keep the code as-is, so we're resolving this as `wontfix`.
