### ISSUE TITLE
MSVC compiler version constants

### ISSUE THREAD

**Issue by robert-andrzejuk** [microsoft/STL#3573]
In our code-base I wrote a piece of code:

```
#if _MSC_VER >= 1935
    // .....
#else
   // ....
#endif
```
For which I received a remark in code review:
> WHY 1935?! MAGIC NUMBER.. PLEASE CHANGE IT.

I thought ... *"but that's the way we always do it!"*
This is even used in example for MSVC_VER: https://learn.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=msvc-170

But I continued thinking ... why are there no constants for MSVC versions?

Raymond Chen "committed" a very usefull article:
https://devblogs.microsoft.com/oldnewthing/20221219-00/?p=107601
Which just shows that this information is needed and requested.

Can we "enshrine" this in the code?
For example: `#define __VS2022_V17_5_MSC_VER 1935`

Maybe the same can be done for: `_MSVC_LANG`

**Comment by StephanTLavavej** [comment]
Thanks for the suggestion, but this is not for MSVC's STL - you should file it as a suggestion for the compiler in [Visual Studio Developer Community](https://developercommunity.visualstudio.com/cpp/suggest), where the compiler team can evaluate and prioritize it, and reply to you for follow-up if necessary.

Note that if feature-test macros are applicable, they are better to use than compiler version checks. (Such checks are still necessary to detect things like bugs for workarounds.)

The STL itself provides `_MSVC_STL_UPDATE`, and we publish a table of our constant values at https://github.com/microsoft/STL/wiki/Macro-_MSVC_STL_UPDATE . At this time, we don't provide named values for these constants.

**Comment by robert-andrzejuk** [comment]
@StephanTLavavej Thank you for the detailed reply. This is actually what I need.
