### ISSUE TITLE
STL upper_bound() not working properly

### ISSUE THREAD

**Issue by Rishul2003** [microsoft/STL#3595]
**a.cpp**

```
#include<bits/stdc++.h>
using namespace std;
#define ll long long int
int main(){
    int a[6]={0,0,0,0,5,0};
    auto it1=upper_bound(a,a+6,0);
    cout<<*it1<<endl<<" index "<<it1-a<<endl;
}
```

C:\Temp>cl /EHsc /W4 /WX .\repro.cpp
Microsoft (R) C/C++ Optimizing Compiler Version 19.23.28019.1 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

repro.cpp
Microsoft (R) Incremental Linker Version 14.23.28019.1
Copyright (C) Microsoft Corporation.  All rights reserved.

**TEST CASE FAIL**

```
                           > cd "c:\Users\91701\Desktop\cp\" ; if ($?) { g++ a.cpp -o a } ; if ($?) { .\a }
0
 index 6
```

**Expected behavior**
upper_bound() gives the first no. greater than or equal to the given number but 
GIVING : - 0 
                  index 6
Expected: - 5 
                   index 4

**STL version**
  Version: 1.76.2 (user setup)
Commit: ee2b180d582a7f601fa6ecfdad8d9fd269ab1884
Date: 2023-03-14T17:55:54.936Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No

* Option 2: git commit hash
  * Example:
    ```
    https://github.com/microsoft/STL/commit/2195148
    ```

**Additional context**

upper_bound() is working fine for

```
#include<bits/stdc++.h>
using namespace std;
#define ll long long int
int main(){
    int a[7]={0,0,0,0,5,5,0};
    auto it1=upper_bound(a,a+7,0);
    cout<<*it1<<endl<<" index "<<it1-a<<endl;
}
```

and giving ans as expected i.e
5
index 4

**Comment by Rishul2003** [comment]
Can you assign this issue

**Comment by fsb4000** [comment]
1)

from https://en.cppreference.com/w/cpp/algorithm/upper_bound

>The range [first, last) must be partitioned with respect to the expression !(value < element) or !comp(value, element), i.e., all elements for which the expression is true must precede all elements for which the expression is false. A fully-sorted range meets this criterion. 

So I think you use `upper_bound` wrongly.

2) 

>#include<bits/stdc++.h>

This is a Microsoft STL repo, not GCC libstdc++ repo.

**Comment by Rishul2003** [comment]
okay thanks for correcting
