### ISSUE TITLE
<algorithm>: vectorized algorithms hurt performance.

### ISSUE THREAD

**Issue by atyuwen** [microsoft/STL#3601]
**Describe the bug**

Some STL algorithms will automatically use the AVX version if supported,  without calling `_mm256_zeroupper()` at the end of the function, which will slow down subsequent SSE code on some CPUs (e.g. Skylake).

[Why is this SSE code 6 times slower without VZEROUPPER on Skylake?](https://stackoverflow.com/questions/41303780/why-is-this-sse-code-6-times-slower-without-vzeroupper-on-skylake)

In following code, the second `calculate()` is much slower than the first `calculate()`. 

**Command-line test case**
```
C:\Temp>type repro.cpp

#include <Windows.h>
#include <vector>
#include <algorithm>

void calculate() {
    int t = ::GetTickCount();
    float a = 1.0f, b = 1.0f, m = 0.0f;
    for (int i = 0; i < 30000000; i++) {
        m = a * b;
        m -= a * 0.1f;
        m += b * 0.2f;
    }
    printf("time cost %d\n", ::GetTickCount() - t);
}

int main() {
    std::vector<float> v1;
    v1.resize(10);
    for (auto it = v1.begin(); it != v1.end(); it++)
        *it = (float)rand();
    std::vector<float> tmp(10);

    std::reverse_copy(v1.end() - 7, v1.end(), tmp.begin());
    calculate();

    std::reverse_copy(v1.end() - 8, v1.end(), tmp.begin());  // AVX code path is selected.
    calculate();
}

C:\Temp>cl /EHsc /W4 /WX .\repro.cpp
Microsoft (R) C/C++ Optimizing Compiler Version 19.34.31937 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

repro.cpp
Microsoft (R) Incremental Linker Version 14.34.31937.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:repro.exe
repro.obj

C:\Temp>.\repro.exe
time cost 172
time cost 296
```

**Comment by atyuwen** [comment]
Thanks for your reply, but actually I can reproduce this issue in the release build:

```
	std::reverse_copy(v1.end() - 8, v1.end(), tmp.begin());  // AVX code path is selected.
00007FF7EAF9139A  lea         rcx,[rsi-20h]  
00007FF7EAF9139E  mov         r8,rbx  
00007FF7EAF913A1  mov         rdx,rsi  
00007FF7EAF913A4  call        __std_reverse_copy_trivially_copyable_4 (07FF7EAF915E0h)  
	calculate();
00007FF7EAF913A9  call        calculate (07FF7EAF91210h)  
}
```
Again, no `VZEROUPPER` is inserted. Besides, since STL can be dynamically linked, the compiler has no clue whether the `__std_reverse_copy_trivially_copyable_4` is VEX-encoded or not. So I doubt if the compiler's auto `VZEROUPPER` insertion can be fully trusted, especially for library authors.

**Comment by AlexGuteniev** [comment]
As per Discord discussion, we should add `_mm256_zeroupper()` intrinsic in `vector_algorithms.cpp` when leaving AVX parts.
There should be `TRANSITION, DevCom-10331414` comment.

**Comment by magicchao** [comment]
> The compiler is expected to insert `VZEROUPPER` instruction automatically. See [Do I need to use _mm256_zeroupper in 2021?](https://stackoverflow.com/questions/68736527/do-i-need-to-use-mm256-zeroupper-in-2021)
> 
> However, your repro really demonstrates the issue. Looks like the compiler does not bother to insert `VZEROUPPER` in **debug** (`/Od`) compilation. GCC compiler behaves the same, whereas some other compilers do insert `VZEROUPPER` even in debug: https://godbolt.org/z/ff5qv111M
> 
> I see the following ways forward:
> 
> * Get the compiler fixed the issue (preferable way to me)
> * Place missing `_mm256_zeroupper` intrinsic, possibly wrapped with configuration check.
> * Both get the compiler fixed the issue, and place a temporary workaround
> * Don't do anything (it is debug after all)
> 
> I've created [DevCom-10331414](https://developercommunity.visualstudio.com/t/10331414) to report the compiler issue.

Not only in debug, but release x86 will also be affected. However release x64 is not affected.
`#include <Windows.h>
#include <vector>
#include <algorithm>

void calculate() {
    int t = ::GetTickCount();
    float a = 1.0f, b = 1.0f, m = 0.0f;
    for (int i = 0; i < 60000000; i++) {
        m = a * b;
        m -= a * 0.1f;
        m += b * 0.2f;
        a = m > 0 ? 1 : 0;
    }
    printf("time cost %d %f\n", ::GetTickCount() - t, m);
}

int main() {
    std::vector<float> v1;
    v1.resize(10);
    for (auto it = v1.begin(); it != v1.end(); it++)
        *it = (float)rand();
    std::vector<float> tmp(10);

    std::reverse_copy(v1.end() - 7, v1.end(), tmp.begin());
    calculate();

    std::reverse_copy(v1.end() - 8, v1.end(), tmp.begin());  // AVX code path is selected.
    calculate();
}
`
Try this code with x86 Native Tools Command Prompot

D:\tmp\test>cl /EHsc /O2 ./repro.cpp
repro.cpp
Microsoft (R) Incremental Linker Version 14.35.32216.1
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:repro.exe
repro.obj

D:\tmp\test>.\repro.exe
time cost 266 1.100000
time cost 328 1.100000

**Comment by AlexGuteniev** [comment]
> Not only in debug, but release **x86** will also be affected. However release x64 is not affected.

I notice that real difference should be `/MT` or `/MD` vs `/MTd` or /MDd`, because it is the `/O2` on the import library

However, I confirm that real release on x86 (with both `/O2` and  `/MT` or `/MD`)  suffers from this problem due to missing `vzeroupper`.

As my PR is submitted, this should be fixed with a next release anyway from the STL side.

I was not able to pinpoint x86 release problem to create a compiler bug report. The `vzeroupper` is present in my attempt: https://godbolt.org/z/sjso4b8bc . It probably has to do with some combination of factors.
