### ISSUE TITLE
Unable to get a native reference to a managed enum value type obtained through structured binding.: Problem

### ISSUE THREAD

**Issue by General-Fault** [microsoft/STL#3620]
**Describe the bug**
When using C++17 structured binding where one of the types is a managed enum type, the value cannot be referenced.

**Command-line test case**
```
C:\Temp>type repro.cpp
#include <utility>

public enum class managedEnum { foo, bar };

int main()
{
	auto testPair = std::pair{ 1, managedEnum::foo };

	auto& [i, e] = testPair;
	int& testIntRef = i; //sanity-check - ok
	managedEnum &testEnumRef = e; //Fails - "C2440 'initializing: cannot convert from 'managedEnum' to 'managedEnum &'"

	managedEnum& testEnumPairRef = testPair.second;  //ok
}

C:\Temp>cl /clr /std:c++17 .\repro.cpp
Microsoft (R) C/C++ Optimizing Compiler Version 19.35.32216.1
for Microsoft (R) .NET Framework version 4.08.4614.0
Copyright (C) Microsoft Corporation.  All rights reserved.

repro.cpp
repro.cpp(11): error C2440: 'initializing': cannot convert from 'managedEnum' to 'managedEnum &'
repro.cpp(11): note: An object from the gc heap (a dereferenced gc pointer) cannot be converted to a native reference
```

**Expected behavior**
The program should compile using the result of structured binding to create a reference to the enum value.

**STL version**
    ```
    Microsoft Visual Studio Community 2022 (64-bit) - Current
    Version 17.5.3
    ```

**Additional context**
This was encountered when trying to expand msclr::interop::marshal_as to convert between native and managed enums. This worked fine until I tried using structured binding to marshal the value from an item in a std::pair. The marshal_as specialized template uses a "const T&" parameter. 
The workaround is to either not use structured binding, or to copy the bound value into another variable.

```
	auto& [i, e] = testPair;
	managedEnum cpy = e;
	managedEnum &testEnumRef = cpy;
```

**Comment by frederick-vs-ja** [comment]
It seems that MSVC miscomputed the value category of `e` - it should be an lvalue, but was wrongly treated as an rvalue. This is probably a compiler bug and needed to be reported [here](https://developercommunity.visualstudio.com/cpp/report).

I guess no fix can be done in the standard library implementation...

**Comment by StephanTLavavej** [comment]
If you can reduce this repro to avoid involving the STL, that would be best - the compiler devs can investigate and fix it more rapidly that way.

**Comment by Atari2** [comment]
I reduced it to this, which I believe is the same issue: <https://godbolt.org/z/b91q6nWx1> feel free to play with it and use it however you see fit to report the issue to compile devs.

**Comment by General-Fault** [comment]
I very much appreciate the feedback. Thank you Atari2 for reducing the example code to exclude STL. I'll get this filed with the compiler group.
