### ISSUE TITLE
<string>: doesn't handle 0'd out reserve properly, returns garbage strings from that point onward.

### ISSUE THREAD

**Issue by alecazam** [microsoft/STL#3652]
**Describe the bug**
Microsoft STL string has nasty behavior when the class is cast from 0-initialized memory, or memset is applied to a class containing empty strings.  This doesn't happen in any other impls of string that we've used.  There is an assumption that the reserve size is 15 on an empty string, and _Myres = 0 causes the string to incorrectly allocate to the heap, and store the data in _Ptr.  

Then from that point on, short strings below 15 characters return the garbage pointer data stored in _Ptr that now overwrite _Buf.  This seems like a bad design on this string class, even if memset of the class isn't ideal (yes it leaks memory, but shouldn't cause a failure like this).  Please see other STL implementations, and copy what they do.   They seem to work with 0 size/reserve, and ptr data.   

There are postings like this one with devs hitting this issue.   We will fix our code so that default ctor occurs to avoid this issue,.  Switching from casts to placement new etc, and checking type_traits before memsetting classes that now contain string.  But we didn't need this on other platforms despite the poor practices.

https://stackoverflow.com/questions/72651818/stdstring-assignment-issue-in-vs2019-where-it-is-working-fine-in-vs2015

**Command-line test case**
```
C:\Temp>type repro.cpp

#include <iostream>
#include <string>
int main() {
    // Replace this program with one demonstrating your actual bug report,
    // along with the following compilation command. Please leave compiler
    // version banners in the output (don't use /nologo), and include output
    // of your test program, if any.
    using namespace std;

     const char* str11 = "12345678901";

     string s;
    // 11 char string, VC copies to _Buf short string
    s = str11;

    if ( s != str11 )
      std::cout << "copy test failure\n";

   // this fails
   char buf[256] = {};
   string& sCast = *(string*)buf;
   sCast = str11;

    if ( sCast  != str11 )
      std::cout << "cast test failure\n";

   // this also fails
   string sMemset;
   memset( &sMemset, 0, sizeof(sMemset) );
   sMemset = str11;

    if ( sMemset != str11 )
      std::cout << "memset test failure\n";

   return 0;
}

C:\Temp>cl /EHsc /W4 /WX .\repro.cpp
Microsoft (R) C/C++ Optimizing Compiler Version 19.23.28019.1 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

repro.cpp
Microsoft (R) Incremental Linker Version 14.23.28019.1
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:repro.exe
repro.obj

C:\Temp>.\repro.exe
test failure
```

**Expected behavior**
Alternatively, include `static_assert` or `assert` lines in your
test case above whose failure clearly indicates the problem.

**STL version**
    ```
STL version
Microsoft Visual Studio Professional 2019 (2)
Version 16.11.16
C++14 build

Microsoft Visual Studio Professional 2019 (2)
Version 16.11.16
VisualStudio.16.Release/16.11.16+32602.291
Microsoft .NET Framework
Version 4.8.04084

    ```

**Additional context**
None.

**Comment by frederick-vs-ja** [comment]
> when the class is cast from 0-initialized memory, or memset is applied to a class containing empty strings

I don't think anyone should expect that these operations work for `string`.

Note that `string` is neither implicit-lifetime nor trivially copyable, so these operations probably result in undefined behavior.

**Comment by StephanTLavavej** [comment]
As @frederick-vs-ja explained, it is undefined behavior to bypass non-trivial constructors. `std::basic_string` is not plain old data, and MSVC's STL will never support such non-Standard code.

**Comment by alecazam** [comment]
Seems pretty short sighted to let users hit this case when other STL handle it gracefully.  There's not even an assert in the growth code to see if _Myres has been 0'd out.  Memset-ing a string isn't the end of the world despite the leak of memory, nor is casting blocks of memory to a struct/class that happens to contain a string.   But we'll just have to fix all the places MS STL crashes, or move to EASTL.
