### ISSUE TITLE
<optional>: Throwing transformers will cause the program to terminate

### ISSUE THREAD

**Issue by achabense** [microsoft/STL#3667]
In the following example, the catch clause is unreacheable. Is this a bug?
The program will terminate directly as <code>optional(_Construct_from_invoke_result_tag, _Fn&& _Func, _Ux&& _Arg)</code>'s noexcept doesn't care about whether _Func itself throws. (see also <code>_Optional_destruct_base(_Construct_from_invoke_result_tag, _Fn&& _Func, _Ux&& _Arg)</code>)
```
#include<optional>

int main() {
	std::optional opt(1);
	try {
		opt.transform([](int) {
			throw(0); return 0;
		});
	}
	catch (...) {
		//unreachable.
	}
}
```
In otional::transform:
```
if (this->_Has_value) {
	return optional<_Uty>{_Construct_from_invoke_result_tag{}, _STD forward<_Fn>(_Func), this->_Value};
} else {
	return optional<_Uty>{};
}
```
In the constructor:
```
template <class _Fn, class _Ux>
constexpr optional(_Construct_from_invoke_result_tag _Tag, _Fn&& _Func, _Ux&& _Arg) noexcept(
        is_nothrow_constructible_v<_Ty, invoke_result_t<_Fn, _Ux>>)
: _Mybase(_Tag, _STD forward<_Fn>(_Func), _STD forward<_Ux>(_Arg)) {}
```

**Comment by fsb4000** [comment]
Yes, this is a bug.

GCC works fine with your example: https://gcc.godbolt.org/z/vh5znebKf
