### ISSUE TITLE
Report Clang bug affecting `P2278R4_views_as_const`

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#3707]
`P2278R4_views_as_const` contains a couple of workarounds for Clang:

https://github.com/microsoft/STL/blob/a0f03675a61b93053d01e3ae4381709dd3e4ca57/tests/std/tests/P2278R4_views_as_const/test.cpp#L548-L555
https://github.com/microsoft/STL/blob/a0f03675a61b93053d01e3ae4381709dd3e4ca57/tests/std/tests/P2278R4_views_as_const/test.cpp#L614-L620

LLVM-44833 was resolved as fixed in Clang 16, but these workarounds are still necessary. We should investigate what's happening here and report it to Clang.

**Comment by JMazurkiewicz** [comment]
I've reduced it to:

```c++
template <class D> struct view_interface {
  const int *data() {
    static_assert(__is_constructible(D, D), "oopsie");
    return nullptr;
  }
};

template <class T> auto data(T v) { return v.data(); }

struct span : view_interface<span> {
  template <class R>
    requires requires(R &r) { ::data(r); }
  span(R);
};

static_assert(__is_constructible(span, span));
```

And it looks like LLVM-62096.

**Comment by StephanTLavavej** [comment]
Thanks! :heart_eyes_cat: I'll update the citations.
