### ISSUE TITLE
`deque(size_t,const Allocator&)` doesn't clear up constructed elements on exception

### ISSUE THREAD

**Issue by achabense** [microsoft/STL#3717]
`deque<T>(size_t,const Allocator&)` lacks a tidy guard now. When the default constructor of a `T` throws, no destructor of constructed `T`s will be called.

For example, in the code below, `test([] {std::deque<resource>f(10); });` will print `"created:5 destroyed:0"`. The expected behavior should be `"created:5 destroyed:5"` as the other code do.

```
#include<deque>
#include<iostream>

struct resource {
	inline static int created = 0, destroyed = 0;
	resource() {
		if (created == 5) { throw 0; }
		++created;
	}
	resource(const resource&) {
		if (created == 5) { throw 0; }
		++created;
	}
	~resource() { ++destroyed; }
};

void test(auto f) {
	resource::created = resource::destroyed = 0;
	try { f(); }
	catch (...) {}
	std::cout << "created:" << resource::created << " destroyed:" << resource::destroyed << std::endl;
}

int main() {
	//created:5 destroyed:0
	test([] {std::deque<resource>f(10); });
	//created:5 destroyed:5
	test([] {std::deque<resource>f; f.resize(10); });
	test([] {std::deque<resource>f; f.resize(10, resource{}); });
	test([] {std::deque<resource>f(10, resource{}); });
	test([] {std::deque<resource>f(10, resource{}, {}); });
}
```

Causes: In the implementation, the use of `resize` is wrong as it doesn't do cleanup on exception, and the construction is not completed so `~deque()` won't be called either.
https://github.com/microsoft/STL/blob/a62109595b6d89e08172fdf4beb75a2670fe0cc9/stl/inc/deque#L622-L628

**Comment by CaseyCarter** [comment]
That's a nasty one - thanks for the report.
