### ISSUE TITLE
`<iomanip>`: consider removing `operator>>` for `istream >> setfill(c)`

### ISSUE THREAD

**Issue by achabense** [microsoft/STL#3724]
According to the standard([this version](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2023/n4944.pdf)), `std::setfill` is only for ostreams. Therefore, `istream >> setfill(c)` has no well-defined meaning and can lead to [confusion](https://stackoverflow.com/questions/42530114/stdsetfill-and-stdsetw-for-input-streams).
![image](https://github.com/microsoft/STL/assets/60953653/7d3b328c-88ae-4eed-9e7f-ee11a2d5b3f7)
The following piece of code should get removed.
https://github.com/microsoft/STL/blob/a62109595b6d89e08172fdf4beb75a2670fe0cc9/stl/inc/iomanip#L28-L35

**Comment by fsb4000** [comment]
Thanks. I agree.

I noticed that LLVM libc++ doesn't have the operator. But GCC libstdc++ has the operator.

https://gcc.godbolt.org/z/E75eavsd4

Will you report this bug to them?

**Comment by achabense** [comment]
@fsb4000 I'm not famaliar with GCC, you may do the report.

**Comment by fsb4000** [comment]
Sure. I created: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=109922

**Comment by achabense** [comment]
It seems also better to define separate classes as return type for `get_*` and `put_*`, and give only matching `operator<< or >>` for each class, to make the following cases directly not-defined.
```
#include<iostream>
#include<iomanip>

int main() {
	double _{};
	tm __{};

	//compilable, but comfusing and also not specified by the standard.
	std::cout << std::get_money(_);
	std::cout << std::get_time(&__, "");

	//not compilable due to constness.
	//std::cin >> std::put_money(_);
	//std::cin >> std::put_time(&__, "");
}
```
