### ISSUE TITLE
`<string>`: Consider improving conformance for `char_traits`

### ISSUE THREAD

**Issue by achabense** [microsoft/STL#3735]
1. According to the standard([ref](https://eel.is/c++draft/char.traits.specializations.char)), `char_traits::eq/lt/to_char_type/to_int_type/eq_int_type/not_eof` should take values instead of references as parameters.
(
Also in
https://github.com/microsoft/STL/blob/a62109595b6d89e08172fdf4beb75a2670fe0cc9/stl/inc/xstring#L305-L327?plain=1
https://github.com/microsoft/STL/blob/a62109595b6d89e08172fdf4beb75a2670fe0cc9/stl/inc/xstring#L449-L471?plain=1
)
https://github.com/microsoft/STL/blob/a62109595b6d89e08172fdf4beb75a2670fe0cc9/stl/inc/xstring#L193-L215

2. Also, `int_type`s for `char_traits<char16_t>`, `<char32_t>` and `<wchar_t>` should be `uint_least16_t`, `uint_least32_t` and `wint_t` respectively. Currently they are defined as `unsigned short`, `unsigned int` and `unsigned short`. --They just works now. However, I think it will be better to use aliases directly, or at least add some static_asserts(e.g. `static_assert(std::is_same_v<wint_t,unsigned short>)`.
https://github.com/microsoft/STL/blob/a62109595b6d89e08172fdf4beb75a2670fe0cc9/stl/inc/xstring#L337-L344
(`char_traits<char>`,`<char8_t>` has no such issue)

3. (off topic) We can safely add `noexcept /*strengthened*/` for this function:
https://github.com/microsoft/STL/blob/a62109595b6d89e08172fdf4beb75a2670fe0cc9/stl/inc/xstring#L1402-L1404

4. (off topic; question) What does the template(line2547~2549) do here? `_Alloc2` is not used in the body, and `_Alloc` is directly used as allocator in other member functions.
(
Also here; the only another use of this pattern
https://github.com/microsoft/STL/blob/a62109595b6d89e08172fdf4beb75a2670fe0cc9/stl/inc/xstring#L2560-L2566?plain=1
)
https://github.com/microsoft/STL/blob/a62109595b6d89e08172fdf4beb75a2670fe0cc9/stl/inc/xstring#L2547-L2553

**Comment by frederick-vs-ja** [comment]
> 4\. `_Alloc2` is not used in the body, and `_Alloc` is directly used as allocator in other member functions.

This is needed by SFINAE. In order to constrain this constructor, we need to make it a function template and introduce a template parameter on which substitution may fail.

**Comment by achabense** [comment]
@frederick-vs-ja Can we simply remove this constraint? `_Alloc` is the allocator for `basic_string` --It is not used elsewhere other than these two cases. Also, the impl defines separate `basic_string(const CharT*)` and `basic_string(const CharT*, const Allocator&)` for `basic_string(const CharT*, const Allocator& alloc = Allocator());` (& basic_string(size_type, CharT, const Allocator& alloc = Allocator());)

**Comment by frederick-vs-ja** [comment]
> Can we simply remove this constraint?

No. This constraint is added by LWG-3076, which should be considered as a defect report against C++17 (in which CTAD is introduced).

**Comment by frederick-vs-ja** [comment]
> 1. According to the standard([ref](https://eel.is/c++draft/char.traits.specializations.char)), `char_traits::eq/lt/to_char_type/to_int_type/eq_int_type/not_eof` should take values instead of references as parameters.

Wow, this is a missed change from WG21-N2349. We need to implement these **C++11** changes.

FYI libstdc++ can't make the changes for `char` and `wchar_t` specializations due to ABI compatibility (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=80810).
