### ISSUE TITLE
`<chrono>`: consider adding a macro that will remove methods that don't work in Windows 7

### ISSUE THREAD

**Issue by fsb4000** [microsoft/STL#3750]
From https://developercommunity.visualstudio.com/t/std::chrono-time-zones-ignore-windows-ve/10384150

Quote:

I have
```
#define WINVER _WIN32_WINNT_WIN7
#define _WIN32_WINNT _WIN32_WINNT_WIN7
#define NTDDI_VERSION NTDDI_WIN7
#include <SDKDDKVer.h>
```
defined before anything else is included but functionality that does not work before window 10 version 1903 is being built in without an error at compile time. Specifically calls to `std::chrono::current_zone` throws a system_error saying the specified module could not be found. Per the visual studio release notes, this is not supported before 1903. I think you guys need to #def that out so it doesn’t compile. That is expected behavior for operating system provided functionality in windows.

**Comment by StephanTLavavej** [comment]
We talked about this at the weekly maintainer meeting, and we don't want to add such a mode. Note that we couldn't automatically activate such a mode based on seeing `_WIN32_WINNT_WIN7` etc. - that just means that the WinSDK headers provide up to Win7 APIs, but the end user's OS might be newer (and the program might "light up" additional API usage via `GetProcAddress()`, which is indeed what the STL does).

While we still support [targeting Win7 with VS](https://learn.microsoft.com/en-us/visualstudio/releases/2022/compatibility) (despite Win7 being unsupported by Windows), we don't want to add additional complexity to the STL to encourage targeting an end-of-life operating system.

**Comment by cedral** [comment]
I get it for windows 7 but the same thing will happen if you target windows server 2019 as it is also predates build 1903. You have a lot of enterprise customers out there on non EOL server OSes that predate build 1903 and you just made it so I can't predictably compile code for them so that you don't have to put a macro check in your headers. That doesn't seem like a great cost benefit analysis.
