### ISSUE TITLE
What's the purpose of different declaration patterns for `facet::id`s?

### ISSUE THREAD

**Issue by achabense** [microsoft/STL#3751]
The following test is inspired by [this question](https://stackoverflow.com/questions/32002653/error-while-using-stdbasic-stringstreamchar16-t-in-vc14) on stackoverflow. All the `//` lines will fail due to errors showing `'std::XXX<_Elem>::id': definition of dllimport static data member not allowed`. The only exceptions are `ctype`, `time_get` and `time_put`.

```cpp
#include <iostream>
#include <chrono>

int main() {
	using char32 = char32_t;

	//std::collate<char32>::id;
	//std::messages<char32>::id;
	std::ctype<char32>::id;
	std::time_get<char32>::id;
	std::time_put<char32>::id;
	//std::num_get<char32>::id;
	//std::num_put<char32>::id;
	//std::numpunct<char32>::id;
	//std::money_get<char32>::id;
	//std::money_put<char32>::id;
	//std::moneypunct<char32>::id;
}
```
What makes the difference is the way `id` get declared in each class. Is this intentional?

For those that cannot compile, `id`s are declared as:
https://github.com/microsoft/STL/blob/c8d1efb6d504f6392acf8f6d01fd703f7c8826c0/stl/inc/xlocnum#L96
For those that can: (`codecvt::id` is also declared this way)
https://github.com/microsoft/STL/blob/c8d1efb6d504f6392acf8f6d01fd703f7c8826c0/stl/inc/xloctime#L115

**Comment by StephanTLavavej** [comment]
@StephanTLavavej: "It was like that when I got here!"
@CaseyCarter: "These are non-Standard and unsupported specializations, but nobody but me thinks that we should enable `_ENFORCE_FACET_SPECIALIZATIONS` by default."
@StephanTLavavej: "It broke a bunch of code, as much as I'd love to do that!"
@CaseyCarter: "You mean it caused a bunch of *broken code* to not compile? :smile_cat:"
@StephanTLavavej: "Yeah."

The actual reason for the difference is that some of the facets have their IDs in a satellite DLL (according to Casey who worked on this, and understands the facet IDs better than I ever have).
