### ISSUE TITLE
<chrono>: Targeted windows version ignored at compile time

### ISSUE THREAD

**Issue by cedral** [microsoft/STL#3766]
# Describe the bug
If I set 
```
#define NTDDI_VERSION NTDDI_WIN10_RS5 //build 1809
```
and then build a program calling (requires /std:c++20)
``` 
std::chrono::current_zone() 
```
or
```
std::chrono::clock_cast()
```
it throws a system error saying the specified module could not be found at run time on OS versions that were targeted at build time. Those do not work before window 10 version 1903 but are being compiled without error. You guys need to #if that out so it doesn’t compile if you are targeting below 1903. For instance if you are building for server 2019 or 2016. I need to support Server 2016 or newer. We are going to have enterprise customers using Server 2016 until at least 2027 so I need to be able to reliably target it for compilation. 

# Command-line test case
```
#define WINVER _WIN32_WINNT_WIN10
#define _WIN32_WINNT _WIN32_WINNT_WIN10
#define NTDDI_VERSION NTDDI_WIN10_RS5
#include <SDKDDKVer.h>
#include <chrono>
#include <iostream>

int main()
{
  try
  {
    auto tz = std::chrono::current_zone();
    std::cout << "Current timezone " << tz->name() << std::endl;
  }
  catch (const std::exception& ex)
  {
    std::cerr << ex.what() << std::endl;
  }
}
```
works fine on latest windows 10 (anything >= 1903) but fails on Server 2019 with module not found

# Expected behavior
That should result in the timezone name but instead results in module not found due to a missing dll at runtime if you are one Server 2019. Server 2019 is based on build 1809 which is what the RS5 NTDDI setting above should limit us to. The expected behavior would be a compile time error for trying to use functions that don't exist in the targeted version of the operating system. Or, put the required dll(s) in the visual C++ runtime redistributable. 

# STL version
    ```
    Microsoft Visual Studio Enterprise 2022
    Version 17.6.2
    ```

# Additional context
[Visual C++ Change Log Entry](https://wg21.link/P0355R7)

**Comment by StephanTLavavej** [comment]
Thanks for reporting this issue. The `NTDDI_VERSION` macro controls the Windows SDK's behavior of declaring functions and structures, but it doesn't inherently say anything about the range of possible targeted operating systems.

In theory, we could implement an opt-in macro that would `= delete` various functionality in the STL that depends on newer operating system versions. However, that would increase the maintenance burden and would be difficult for users to discover (like all opt-in machinery). Finally, user code must be prepared for `current_zone()` etc. to throw exceptions as specified in the Standard, so throwing such exceptions on older OSes is permitted behavior for an implementation.
