### ISSUE TITLE
Retarget project from VS2010 to VS2019

### ISSUE THREAD

**Issue by mcgunay** [microsoft/STL#378]
Hi,
I have retargeted my visual studio 2010 project to VS2019 and platform toolset that is used to v142.
My Project uses some dynamic library reference. this library has it s own begin implementation for vector iterator of a class.
After I have converted the project to VS2019 I got this unresolved external symbol error.
The reason as far as I understand so far is that in VS2010 _Vector_val definition from stl is different then stl in VS2019.
In 2019 it is something like below:
 using _Scary_val = _Vector_val<conditional_t<_Is_simple_alloc_v<_Alty>, _Simple_types<_Ty>,
In 2010 it is like this:
typedef _Vector_val<_Ty, _Ax> _Mybase

So does this make sense? Should I change the library that I used with the one compiled with VS2019? How can this be solved?

Regards.

**Comment by StephanTLavavej** [comment]
VS 2010 and VS 2019 aren't binary compatible. You need to use the VS 2019 build of the third-party library you're using.

(More details: VS 2010, 2012, 2013, and 2015 were all binary incompatible. However, the VS 2015, 2017, and 2019 release series are binary compatible, with certain restrictions. So if your application is built with VS 2019, you can use a third-party library compiled with VS 2015, 2017, or 2019. However, it's best to use the latest version consistently, which will give you the most correctness and performance fixes.)

**Comment by mcgunay** [comment]
thanks for the info.
