### ISSUE TITLE
`<numeric>`: `transform_inclusive_scan` passes output values to the binary (reduce) operation

### ISSUE THREAD

**Issue by akrivx** [microsoft/STL#3783]
# Describe the bug
The overload of `transform_inclusive_scan` that takes execution policy and initial value arguments passes the result of dereferencing the output iterator to the binary reduce operation.

Doing so requires that the output value type can be converted to the types expected by the binary operation.

# Command-line test case
See this example here: https://godbolt.org/z/4fscYPcTW
It's working fine with the latest gcc.

# Expected behavior
`transform_inclusive_scan` does not pass the result of dereferencing the output iterator to the binary operation.

# STL version
    Microsoft Visual Studio Community 2022 (64-bit)
    Version 17.6.2

**Comment by achabense** [comment]
&& `transform_exclusive_scan(execution::par,...` has the same problem.

**Comment by frederick-vs-ja** [comment]
It seems that we should pass `_Transform_op` to `_Apply_inclusive_predecessor` (with its signature changed) and use `_Transform_op` in it.
