### ISSUE TITLE
<complex>: asinh(-1e+307 + 2e+307i) is wrong

### ISSUE THREAD

**Issue by statementreply** [microsoft/STL#379]
**Describe the bug**
Results of the following are wrong:
```
asinh(-1e+307 + 2e+307i)
acosh(-1e+307 + 2e+307i)
acos(2e+307 + 1e+307i)
acos(-2e+307 + 1e+307i)
```

**Command-line test case**
Visual Studio 16.4.1:

```
G:\Temp>type asinh.cpp
#include <complex>
#include <cstdio>

int main() {
    using namespace std;
    const auto a = asinh(-1e+307 + 2e+307i);
    const auto b = acosh(-1e+307 + 2e+307i);
    const auto c = acos(2e+307 + 1e+307i);
    const auto d = acos(-2e+307 + 1e+307i);

    puts("asinh(-1e+307 + 2e+307i)");
    puts("  Expected: (-708.39148968594902047...,1.1071487177940905030...)");
    printf("    Actual: (%.17g,%.17g)\n", a.real(), a.imag());

    puts("acosh(-1e+307 + 2e+307i)");
    puts("  Expected: (708.39148968594902047...,2.0344439357957027354...)");
    printf("    Actual: (%.17g,%.17g)\n", b.real(), b.imag());

    puts("acos(2e+307 + 1e+307i)");
    puts("  Expected: (0.4636476090008061162...,-708.39148968594902047...)");
    printf("    Actual: (%.17g,%.17g)\n", c.real(), c.imag());

    puts("acos(-2e+307 + 1e+307i)");
    puts("  Expected: (2.6779450445889871222...,-708.39148968594902047...)");
    printf("    Actual: (%.17g,%.17g)\n", d.real(), d.imag());
}

G:\Temp>cl /EHsc /W4 asinh.cpp
用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.24.28314 版
版权所有(C) Microsoft Corporation。保留所有权利。

asinh.cpp
Microsoft (R) Incremental Linker Version 14.24.28314.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:asinh.exe
asinh.obj

G:\Temp>.\asinh.exe
asinh(-1e+307 + 2e+307i)
  Expected: (-708.39148968594902047...,1.1071487177940905030...)
    Actual: (708.27991791029194,1.1071487177940904)
acosh(-1e+307 + 2e+307i)
  Expected: (708.39148968594902047...,2.0344439357957027354...)
    Actual: (-707.58677072973205,2.0344439357957027)
acos(2e+307 + 1e+307i)
  Expected: (0.4636476090008061162...,-708.39148968594902047...)
    Actual: (0.46364760900080615,-0.74737784215813008)
acos(-2e+307 + 1e+307i)
  Expected: (2.6779450445889871222...,-708.39148968594902047...)
    Actual: (2.677945044588987,708.27991791029194)
```

**Additional context**
https://github.com/microsoft/STL/blob/aa0a7a3d859ade0f6f1ff13aa4ef74b3d5ce2326/stl/inc/complex#L1380

Should be `_Beta = -_Zr - _Wr * (_Zi / _Alfa);`

https://github.com/microsoft/STL/blob/aa0a7a3d859ade0f6f1ff13aa4ef74b3d5ce2326/stl/inc/complex#L1305

Should be `_Beta = _Wr * (_Zr / _Alfa) + _Zi;`

https://github.com/microsoft/STL/blob/aa0a7a3d859ade0f6f1ff13aa4ef74b3d5ce2326/stl/inc/complex#L1234

Should be `_Beta = _Wr * (_Zi / _Alfa) - _Zr;`

https://github.com/microsoft/STL/blob/aa0a7a3d859ade0f6f1ff13aa4ef74b3d5ce2326/stl/inc/complex#L1242

Should be `if (0 <= _Vx) {`

**Comment by theuserbl** [comment]
Right. On Windows with Visual C++ it looks like your output. And on Ubuntu 19.10 with g++ 9.2.1 it outputs

```
$ ./asinh 
asinh(-1e+307 + 2e+307i)
  Expected: (-708.39148968594902047...,1.1071487177940905030...)
    Actual: (-708.39148968594895,1.1071487177940904)
acosh(-1e+307 + 2e+307i)
  Expected: (708.39148968594902047...,2.0344439357957027354...)
    Actual: (708.39148968594895,2.0344439357957027)
acos(2e+307 + 1e+307i)
  Expected: (0.4636476090008061162...,-708.39148968594902047...)
    Actual: (0.46364760900080609,-708.39148968594895)
acos(-2e+307 + 1e+307i)
  Expected: (2.6779450445889871222...,-708.39148968594902047...)
    Actual: (2.677945044588987,-708.39148968594895)
```

I wonder... don't existing tests with https://github.com/catchorg/Catch2 or other testing units?

**Comment by StephanTLavavej** [comment]
@theuserbl
> I wonder... don't existing tests with https://github.com/catchorg/Catch2 or other testing units?

I don't understand your question - did you delete a few words while composing it?

Our test suites, which we're working on uploading soon (hopefully January!), don't use Catch2. The tests have a simple structure - each source file just `assert()`s run-time conditions and `static_assert()`s compile-time conditions, and returns an exit code for success or failure. Then our test harness compiles and runs each source file with a large combination of compilers and compiler options.
