### ISSUE TITLE
P2198R7 Freestanding Feature-Test Macros And Implementation-Defined Extensions

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#3794]
WG21-P2198R7 Freestanding Feature-Test Macros And Implementation-Defined Extensions

See the paper for exactly which feature-test macros are provided.

I don't know whether there's anything for our hosted implementation to do here.

Note: We're focused on implementing [the remaining library-only features in C++23](https://github.com/microsoft/STL/projects/8?card_filter_query=-label%3Acompiler+-label%3Afixed+-label%3Aresolved). Until that's done, we will **NOT** be accepting PRs for C++26 features.

**Comment by frederick-vs-ja** [comment]
The paper apparently requires hosted implementations to define all `__cpp_lib_freestanding_*` macros as the _`new-val`_.
