### ISSUE TITLE
P0879R0 constexpr For Swapping Functions

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#38]
[P0879R0](https://wg21.link/P0879R0) `constexpr` For Swapping Functions

LWG-3256 Feature testing macro for `constexpr` algorithms

<s>This may need #156 `is_constant_evaluated()`.</s>

Feature-test macro as of WG21-N4842 if both #6 WG21-P0202 and this feature are implemented:
`#define __cpp_lib_constexpr_algorithms 201806L`

**Comment by BillyONeal** [comment]
I'm starting this and hope to get the `<xutility>` family constexprized shortly.

**Comment by BillyONeal** [comment]
p0879r0, those in **bold** have libc++ tests already present we can use:
* *swap_ranges*
* *iter_swap*
* revese
* rotate
* partition
* sort
* partial_sort
* partial_sort_copy
* nth_element
* push_heap
* pop_heap
* make_heap
* sort_heap
* is_heap
* next_permutation
* prev_permutation
* *swap*
