### ISSUE TITLE
P2538R1 ADL-Proof `projected`

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#3801]
WG21-P2538R1 ADL-Proof `projected`

This paper deliberately doesn't provide a feature-test macro.

Note: We're focused on implementing [the remaining library-only features in C++23](https://github.com/microsoft/STL/projects/8?card_filter_query=-label%3Acompiler+-label%3Afixed+-label%3Aresolved). Until that's done, we will **NOT** be accepting PRs for C++26 features.

**Comment by frederick-vs-ja** [comment]
It seems to me that we should implement this in C++20 mode, like WG21-P2602R2 (#3209) and WG21-P2609R3 (#3441).

**Comment by StephanTLavavej** [comment]
I would be fine with that if the other maintainers are, in which case this would be a special exception to our "not yet" policy.
