### ISSUE TITLE
P2874R2 Mandating Annex D

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#3814]
WG21-P2874R2 Mandating Annex D

No feature-test macro is mentioned.

My first impression of this paper is that it's a wording-only cleanup with no action required for implementers or users. If that's true, this should be considered N/A and not a C++26 feature at all (i.e. we should retroactively remove the `cxx26` label).

Note: We're focused on implementing [the remaining library-only features in C++23](https://github.com/microsoft/STL/projects/8?card_filter_query=-label%3Acompiler+-label%3Afixed+-label%3Aresolved). Until that's done, we will **NOT** be accepting PRs for C++26 features.

**Comment by CaseyCarter** [comment]
It's pure cleanup with the exception of [depr.fs.path.factory]/1, which changes "The value type of `Source` and `InputIterator` is `char` or `char8_t`." from _Requires_ to _Mandates_ in the specification of the `u8path` overloads. We already diagnose this, so there's nothing to do.

First C++26 feature completed!
