### ISSUE TITLE
<chrono>: std::chrono::current_zone() ignores %TZ% env variable

### ISSUE THREAD

**Issue by kmccarty-dgi** [microsoft/STL#3836]
# Describe the bug

It appears that `std::chrono::current_zone()` ignores the setting of the TZ environment variable, unlike the C runtime functions `mktime()` / `localtime()`.  This means that in cases where the user expects %TZ% to be honored, `current_zone()` cannot be used to replace the functionality of the C runtime.

# Command-line test case
```
D:\users\kevin> type tz.cpp
#include <chrono>
#include <cstdlib>
#include <ctime>
#include <format>
#include <iostream>
#include <string>

using namespace std::chrono;
using std::cout;
using std::format;
using std::localtime;
using std::string;
using std::time_t;

void require(bool b)
{
    if (!b)
        std::abort();
}

void info_from_std_chrono(sys_seconds time_point)
{
    auto zone = current_zone();
    require(zone != nullptr);

    auto info = zone->get_info(time_point);
    auto local = zone->to_local(time_point);

    cout << format("Local time from std::chrono:\n"
                   "    {0:%F} {0:%T}{1:%z} ({1:%Z})\n"
                   "    Time zone name: {2}\n\n",
                   local, info, zone->name());
}

void info_from_c_runtime(sys_seconds time_point)
{
    time_t t = system_clock::to_time_t(time_point);
    require(t > 0);
    auto tm = localtime(&t);
    require(tm != nullptr);

    // keep retrying until buffer is large enough for strftime()
    string s(std::size("YYYY-MM-DD HH:MM:SS+zzzz (CEST)"), '\0');
    while (! strftime(s.data(), s.size(), "%F %T%z (%Z)", tm))
        s.resize(s.size() * 2);

    cout << format("Local time from C runtime:\n"
                   "    {}\n", s.c_str());
}

int main()
{
    _tzset();

    using namespace std::literals::chrono_literals;
    sys_days date = year_month_day{2020y, July, 1d};
    sys_seconds time_point = date;
    cout << format("UTC time: {0:%F} {0:%T}\n\n", time_point);

    info_from_std_chrono(time_point);
    info_from_c_runtime(time_point);
}

D:\users\kevin> ver

Microsoft Windows [Version 10.0.19044.3086]

D:\users\kevin> cl /EHsc /W4 /WX /std:c++latest /D_CRT_SECURE_NO_WARNINGS tz.cpp
Microsoft (R) C/C++ Optimizing Compiler Version 19.36.32535 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

/std:c++latest is provided as a preview of language features from the latest C++
working draft, and we're eager to hear about bugs and suggestions for improvements.
However, note that these features are provided as-is without support, and subject
to changes or removal as the working draft evolves. See
https://go.microsoft.com/fwlink/?linkid=2045807 for details.

tz.cpp
Microsoft (R) Incremental Linker Version 14.36.32535.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:tz.exe
tz.obj

D:\users\kevin> set TZ=EST5EDT

D:\users\kevin> tz
UTC time: 2020-07-01 00:00:00

Local time from std::chrono:
    2020-06-30 17:00:00-0700 (PDT)
    Time zone name: America/Los_Angeles

Local time from C runtime:
    2020-06-30 20:00:00-0400 (EDT)
```

# Expected behavior
The local time output from std::chrono functions should match that output by the C runtime, in cases where the TZ environment variable is set and the C runtime functions correctly [*] honor its setting.

[*] See "Additional context" below.

# STL version

```
Microsoft Visual Studio Professional 2022
Version 17.6.4
```

# Additional context

I note as an aside that with `set TZ=America/New_York`, the C runtime functions do not honor the timezone setting correctly, although its presence does affect the behavior.  That I presume is beyond the scope of the STL.  However, the std::chrono functions entirely ignore settings of TZ like this one with valid Olson database timezone names, as well as (as shown above) ignoring settings of TZ that are properly understood by the C runtime.  Demo:

```
D:\users\kevin> set TZ=America/New_York

D:\users\kevin> tz
UTC time: 2020-07-01 00:00:00

Local time from std::chrono:
    2020-06-30 17:00:00-0700 (PDT)
    Time zone name: America/Los_Angeles

Local time from C runtime:
    2020-07-01 01:00:00+0100 (ric)
```

**Comment by cpplearner** [comment]
[[time.zone.db.tzdb]/4](http://eel.is/c++draft/time.zone.db.tzdb#4) specifies that `current_zone` returns "a pointer to the time zone which the computer has set as its local time zone." This suggests that it should prefer the system setting and not the env variable.

It's relatively easy to get a `time_zone` object for the time zone named by `TZ`.
```c++
const std::chrono::time_zone* tz;
try {
    tz = std::chrono::locate_zone(std::getenv("TZ"));  // get the time zone info for %TZ%
} catch (...) {
    tz = std::chrono::current_zone(); // fall back to current_zone()
}
```

**Comment by kmccarty-dgi** [comment]
> This suggests that it should prefer the system setting and not the env variable.

It's unfortunate that this makes `current_zone()` behave differently out-of-the-box than `mktime() / localtime()`, as well as making it infeasible to affect the behavior of this function within non-privileged code at runtime -- e.g. for unit tests of code built atop it -- but I can accept that as being a logical reading of the Standard.

FWIW upon a bit of research, it appears that libstdc++ implementation of `current_zone()` does not check the `$TZ` environment variable either [except, recently, on AIX for platform-specific reasons].  Cf. https://gcc.gnu.org/bugzilla/show_bug.cgi?id=108409 and https://gcc.gnu.org/git/?p=gcc.git;a=blob;f=libstdc%2B%2B-v3/src/c%2B%2B20/tzdb.cc;h=8d27726016ece9bfb7372ed195458b0ee9b6fc17;hb=HEAD .  Although I don't have insight as to whether their rationale is the same.

So at least the behavior of `current_zone()` ignoring TZ environment setting will be (more or less) cross-platform.

As far as I can see, the C standard (at least the drafts to which I have access) does not say anything about how `mktime() / localtime()` should behave.  For instance [N3096](https://www.open-std.org/jtc1/sc22/wg14/www/docs/n3096.pdf) says "Some functions deal with *local time*, which is the calendar time expressed for some specific time zone [...] The local time zone and Daylight Saving Time are implementation-defined."

**Comment by JMazurkiewicz** [comment]
> Although I don't have insight as to whether their rationale is the same.

Here is their rationale: https://gcc.gnu.org/pipermail/libstdc++/2023-May/055928.html

**Comment by StephanTLavavej** [comment]
Thanks for reporting this issue. We've talked about it at the weekly maintainer meeting and have concluded that this is by design for the reasons that @cpplearner and @jwakely (via @JMazurkiewicz) explained in detail.
