### ISSUE TITLE
`<functional>`: Clang error when calling `target()` on a `const function`

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#3843]
Repros with VS 2022 17.7 Preview 2 x64 containing Clang 16.0.1.

```
D:\GitHub\STL\out\x64>type meow.cpp
```
```cpp
#include <cassert>
#include <functional>
using namespace std;

int main() {
    const function<void()> f;

    assert(f.target<void()>() == nullptr);
}
```
```
D:\GitHub\STL\out\x64>cl /EHsc /nologo /W4 /MTd /Od meow.cpp && meow
meow.cpp

D:\GitHub\STL\out\x64>clang-cl /EHsc /nologo /W4 /MTd /Od meow.cpp && meow
In file included from meow.cpp:2:
D:\GitHub\STL\out\x64\out\inc\functional(1142,16): error: reinterpret_cast from 'const void *' to 'void (*)()' casts
      away qualifiers
        return reinterpret_cast<const _Fx*>(this->_Target(typeid(_Fx)));
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
meow.cpp(8,14): note: in instantiation of function template specialization 'std::function<void ()>::target<void ()>'
      requested here
    assert(f.target<void()>() == nullptr);
             ^
1 error generated.
```

Reduced from the original report DevCom-10402530 VSO-1843867 AB#1843867 "`std::function::target` is broken on clang-cl when called on `const` objects".

**Comment by cpplearner** [comment]
IIIC `f.target<void()>()` could unconditionally return `nullptr`. The target has a decayed type and thus can't be a function ([[func.wrap.func.con]/13](https://eel.is/c++draft/func.wrap.func.con#13)).

**Comment by AlexGuteniev** [comment]
> IIUC `f.target<void()>()` could unconditionally return `nullptr`. The target has a decayed type and thus can't be a function ([[func.wrap.func.con]/13](https://eel.is/c++draft/func.wrap.func.con#13)).

I understand that the standard states this.
But I'm not sure that there was an intention to say this.

**Comment by cpplearner** [comment]
I don't think the standard cares about impossible types. It also allows `f.target<int>()`, for example.

**Comment by frederick-vs-ja** [comment]
> But I'm not sure that there was an intention to say this.

LWG-3305 seems to be related, but the resolution seemly states that MSVC STL is just fine, and we should continue to accept function types and return null function pointers for them.
