### ISSUE TITLE
<chrono>: Time zone Africa/Juba causes runtime_error in std::chrono::tzdb::current_zone

### ISSUE THREAD

**Issue by lat9nq** [microsoft/STL#3854]
# Describe the bug
A user can choose the time zone Africa/Juba in Windows 10 by selecting `(UTC+02:00) Juba` in the Date & Time options. This time zone has a path and name, however causes a runtime_error if used here.

# Command-line test case
```cmake
cmake_minimum_required(VERSION 3.12)

project(tzdb_test VERSION 1.0)

add_executable(tzdb_test
    main.cpp)

if (MSVC)
    target_compile_options(tzdb_test PRIVATE
        /std:c++20)
endif()
```
```c++
// main.cpp
#include <chrono>
#include <cstdio>
#include <stdexcept>
#include <string_view>

int main() {
  std::string location_name;
  try {
    const struct std::chrono::tzdb &time_zone_data = std::chrono::get_tzdb();
    const std::chrono::time_zone *current_zone = time_zone_data.current_zone();
    std::string_view current_zone_name = current_zone->name();
    location_name = current_zone_name;
  } catch (std::runtime_error &runtime_error) {
    location_name = std::string{"FAILURE: "} + runtime_error.what();
  }

  std::printf("%s\n", location_name.c_str());

  return 0;
}
```
```
PS C:\Temp> mkdir build
PS C:\Temp> cd build
PS C:\Temp\build> cmake ..
-- Building for: Visual Studio 17 2022
-- Selecting Windows SDK version 10.0.20348.0 to target Windows 10.0.19045.
-- The C compiler identification is MSVC 19.36.32532.0
-- The CXX compiler identification is MSVC 19.36.32532.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.36.32532/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.36.32532/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done (6.9s)
-- Generating done (0.0s)
-- Build files have been written to: C:/Temp/build
PS C:\Temp\build> cmake --build . --config Release
MSBuild version 17.6.3+07e294721 for .NET Framework

  Checking Build System
  Building Custom Rule C:/Temp/CMakeLists.txt
  main.cpp
  tzdb_test.vcxproj -> C:\Temp\build\Release\tzdb_test.exe
  Building Custom Rule C:/Temp/CMakeLists.txt
PS C:\Temp\build> .\Release\tzdb_test.exe
FAILURE: unable to locate time_zone with given name
```

# Expected behavior
It is expected to not receive a std::runtime_error, thus crash if it's not caught, when using these functions. Instead, this program should output the string `Africa/Juba`.

# STL version
Visual Studio version on compile VM:
```
Microsoft Visual Studio Community 2022 (64-bit) - Current
Version 17.6.2
```

**Comment by achabense** [comment]
I try to set my timezone to `(UTC+02:00) Juba` and get the same error.

`current_zone` calls `_Tzdb_generate_current_zone`, which calls `__std_tzdb_get_current_zone` inside.
https://github.com/microsoft/STL/blob/2261f7edb760eb3fe0726187c818b796dc7ea798/stl/inc/chrono#L2093-L2095
https://github.com/microsoft/STL/blob/2261f7edb760eb3fe0726187c818b796dc7ea798/stl/inc/chrono#L2049-L2051
The following program shows that `_Tzdb_generate_current_zone` is generating `"Etc/Unknown"`:
```cpp
#include <chrono>
#include <iostream>
int main() {
    std::cout << std::chrono::_Tzdb_generate_current_zone();//"Etc/Unknown"
}
```

An emulation of `__std_tzdb_get_current_zone` shows that `ucal_getDefaultTimeZone` generating `""Etc/Unknown""` for this time zone.
```cpp
#include<iostream>
#include<icu.h>
#include<Windows.h>

#pragma comment(lib, "Advapi32")

int main() {
    const HMODULE _Icu_module = LoadLibraryExW(L"icu.dll", nullptr, LOAD_LIBRARY_SEARCH_SYSTEM32);
    if (_Icu_module != nullptr) {
        auto getter = (decltype(+ucal_getDefaultTimeZone))GetProcAddress(_Icu_module, "ucal_getDefaultTimeZone");
        UChar result[3000]{};
        UErrorCode ec;
        getter(result, 2500, &ec);
        std::wcout << reinterpret_cast<wchar_t*>(result);//"Etc/Unknown"
    }
}
```

**Comment by cpplearner** [comment]
MSVC STL uses [ICU](https://learn.microsoft.com/en-us/windows/win32/intl/international-components-for-unicode--icu-) to get time zone information. ICU uses [CLDR](https://github.com/unicode-org/cldr) to map Windows time zones to IANA time zones. CLDR added mapping for "Africa/Juba" in 2021 (https://github.com/unicode-org/cldr/commit/85885edfb64a49d6ad903f639e9bfbb00a15ea0c), but it seems that Windows doesn't contain this update 😕

**Comment by StephanTLavavej** [comment]
Thanks for reporting this issue. As @cpplearner noted, Windows needs to update its copy of ICU before this will start working. MSVC's STL absolutely relies on ICU (via Windows) for time zone information as this is the only way for us to obtain the info and have it updated (in situations exactly like this one!) without requiring users to rebuild and reship their apps that are using the STL. As a result, we're closing this issue as external.
