### ISSUE TITLE
`<bitset>`: Investigate further performance improvements

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#3858]
Followup to #3838 which is adding a benchmark - thanks @achabense!

* @AlexGuteniev suggested using `basic_string::resize_and_overwrite`, creating an `_Ugly` version for unconditional use internally. (We generally avoid adding totally novel secret machinery to Standard classes as it can become a maintenance burden, but simply having `_Ugly` names to access Future Technology is easy and common.)
* @AlexGuteniev also suggested investigating whether branchless codegen for assigning `_Elem0` vs. `_Elem1` would be superior. (Note: we cannot assume that their values are consecutive, they could be `'M'` and `'E'`.)
* I suggest investigating SIMD, as this would seem to be highly amenable to vectorization.

Regardless of what's investigated, I recommend profiling each change in isolation.

**Comment by achabense** [comment]
Somewhat off-topic, but I think we should also pay some attention to the maintainance issue of `_Getword`:
https://github.com/microsoft/STL/blob/2261f7edb760eb3fe0726187c818b796dc7ea798/stl/inc/bitset#L447-L449
https://github.com/microsoft/STL/blob/2261f7edb760eb3fe0726187c818b796dc7ea798/tests/std/tests/Dev10_860410_bitset_ctors/test.cpp#L255-L257

**Comment by AlexGuteniev** [comment]
Vectorization approach suggested by @Alcaro : 
```c++
void bits_to_str16_walrus(char* dest, uint16_t src)
{
	__m128i bits = _mm_cvtsi32_si128(src);
	bits = _mm_unpacklo_epi8(bits, bits);
	bits = _mm_unpacklo_epi8(bits, bits);
	bits = _mm_unpacklo_epi8(bits, bits);
	bits = _mm_and_si128(bits, _mm_set1_epi64x(0x8040201008040201));
	bits = _mm_cmpeq_epi8(bits, _mm_setzero_si128());
	bits = _mm_and_si128(bits, _mm_set1_epi8(0x01));
	bits = _mm_xor_si128(bits, _mm_set1_epi8(0x31));
	_mm_storeu_si128((__m128i*)dest, bits);
}
```
https://godbolt.org/z/hK1YaY8fK
(saving it here for now, so that it is not lost while reviewing the current PR)
