### ISSUE TITLE
Consider unifying existing practices of `don't-call` functions

### ISSUE THREAD

**Issue by achabense** [microsoft/STL#3888]
Currently there are (at least) 4 special functions that use unconditional `abort/terminate` to express that, they are not supposed to be called at runtime, but have to be defined for some reasons:

<details>
<summary>List</summary>

`<functional>`:
`_Func_impl(_no_alloc)::_Target_type` when `!_HAS_STATIC_RTTI`:
https://github.com/microsoft/STL/blob/f51733ca5352c712165e46fdbc5d0d395971f0e7/stl/inc/functional#L756
https://github.com/microsoft/STL/blob/f51733ca5352c712165e46fdbc5d0d395971f0e7/stl/inc/functional#L817
`<future>`:
`_Fake_no_copy_callable_adapter`'s copy constructor:
https://github.com/microsoft/STL/blob/f51733ca5352c712165e46fdbc5d0d395971f0e7/stl/inc/future#L1416
`<xutility>`:
`projected(_Projected_impl)::operator *`:
https://github.com/microsoft/STL/blob/f51733ca5352c712165e46fdbc5d0d395971f0e7/stl/inc/xutility#L887
</details>

It's desirable to make them distinct from common noreturn functions, which are to be called to get noreturn behavior purposefully. Further, I think it's also desirable to do this in a unified way. Some questions are:

1. Are the intents of these `abort/terminate` exactly indentical(Nothing more than `should not be called at runtime`)?
2. Is `_Fake_no_copy_callable_adapter`'s usage of `terminate` replaceable with `abort`?
2. Is it desirable to replace direct usage of `abort` with a specific utility(like a `_MACRO()`), to express the intent more clearly?
3. Is `"abort"` preferrable behavior in these conditions? Are there other candidates for it?

**Comment by AlexGuteniev** [comment]
> 3. Is it desirable to replace direct usage of `abort` with a specific utility(like a `_MACRO()`), to express the intent more clearly?

IMO. no. 
For extra context, a comment is better:
https://github.com/microsoft/STL/blob/f51733ca5352c712165e46fdbc5d0d395971f0e7/stl/inc/functional#L1225-L1229

There are useful macros, though.
 * `_STL_VERIFY` calls `abort()` when the passed expression evaluates to false
 * `_STL_ASSERT` is the same, except that in non-debug builds it is not evaluated.

**Comment by StephanTLavavej** [comment]
We talked about this at the weekly maintainer meeting:

> 1. Are the intents of these `abort/terminate` exactly indentical(Nothing more than `should not be called at runtime`)?
> 2. Is `_Fake_no_copy_callable_adapter`'s usage of `terminate` replaceable with `abort`?
> 3. Is it desirable to replace direct usage of `abort` with a specific utility(like a `_MACRO()`), to express the intent more clearly?
> 4. Is `"abort"` preferrable behavior in these conditions? Are there other candidates for it?

1. The effects are identical (the functions shouldn't be called), but their reasons for abrupt termination vary. `_Fake_no_copy_callable_adapter` exists for ABI limitation reasons, `_Projected_impl::operator*` exists for a modules perma-workaround, `_Func_impl_no_alloc::_Target_type()` exists because we must `override` the pure `virtual` to make the class concrete but when RTTI is disabled we can't return anything. (And we can't eliminate the `virtual` entirely, because that would affect vtable layout, and who knows how many people are mixing RTTI enabled and disabled TUs), etc.
2. Yes, this should be a desirable change. Except when mandated by the Standard to call `terminate()` (like `~thread()`), we should instead `abort()` because that doesn't search for `terminate` handlers, making things simpler.
3. No, a macro would not be desirable. We generally attempt to avoid internal usage of macros, except when platform variation, debug mode variation, extreme code repetition, etc. are a good reason. As @CaseyCarter observes, comments are better than macros when applicable.
4. `abort()` is the best tool that we have unconditional access to; there's a "fastfail" intrinsic but due to platform variation reasons we don't use it in STL headers.

**Comment by achabense** [comment]
> For extra context, a comment is better:

Thanks for picking out that there is another `don't-call` function using `abort`. 

As to `_STL_VERIFY`, I find there is also a use case of `_STL_VERIFY(false, "...")` (and some use cases of `_STL_INTERNAL_CHECK(false)`):
https://github.com/microsoft/STL/blob/f51733ca5352c712165e46fdbc5d0d395971f0e7/stl/inc/format#L3438-L3440
<details>
<summary>_STL_INTERNAL_CHECK(false)</summary>

https://github.com/microsoft/STL/blob/f51733ca5352c712165e46fdbc5d0d395971f0e7/stl/inc/chrono#L4939-L4941
https://github.com/microsoft/STL/blob/f51733ca5352c712165e46fdbc5d0d395971f0e7/stl/inc/format#L2395-L2397
https://github.com/microsoft/STL/blob/f51733ca5352c712165e46fdbc5d0d395971f0e7/stl/inc/format#L2664-L2666
</details>

**Comment by achabense** [comment]
```
 _OutputIt operator()(typename basic_format_arg<_Context>::handle) { 
     _STL_VERIFY(false, "The custom handler should be structurally unreachable for _Arg_formatter"); 
     _STL_INTERNAL_CHECK(_Ctx); 
```

The `_STL_INTERNAL_CHECK(_Ctx);` looks also useless, as `_STL_VERIFY(false, "...")` will make it unreachable...

**Comment by AlexGuteniev** [comment]
Would it be valuable to comment `termimate()` with Standard quotes?

**Comment by StephanTLavavej** [comment]
Yes, when we must `terminate()`, citing the Standardese paragraph would be useful.

**Comment by AlexGuteniev** [comment]
`_STL_VERIFY(false, "...")` has only two occurrences in `<format>`. It is almost equivalent to `_STL_REPORT_ERROR(...)`, which occurs more often, except that it also include codegen assumption of untaken path in release mode. This doesn't look like an equivalent to `abort()`

**Comment by AlexGuteniev** [comment]
I don't understand this function
https://github.com/microsoft/STL/blob/0fe653a9d6efd2ac0ad07825804436672dbffe3b/stl/src/ppltasks.cpp#L38-L48
Thoughts:
 * There are no call sites in the STL.
    - Maybe it is called by the runtime, but then it is odd that it is not in runtime.
    - Maybe it is preserved for ABI, then it lacks transition comment
 * It is odd to try to call `std::terminate()` after trying to `__fastfail`. `__fastfail` is likely to be available and succeed on a normal CPU, so it is pointless to call `std::terminate()`, std::abort()` would have made more sense.
 * Parallel algorithms should `std::terminate()` on exception. I don't see that place. Maybe this function is supposed exactly for that.

**Comment by CaseyCarter** [comment]
`_ReportUnobservedException` is called indirectly via the `_REPORT_PPLTASK_UNOBSERVED_EXCEPTION` from the destructor of `_ExceptionHolder` defined in `ppltasks.h`. (Don't ask me why `ppltasks.cpp` is part of the STL but `ppltasks.h` is not.) I agree that `abort` makes more sense here than `terminate`.

We typically annotate parallel algorithms with `noexcept /* terminates */` so they _do_ `terminate()` on exception, with the comment to point out that this case differs from `/* strengthened */` despite that `noexcept` doesn't appear on the declarations in the Standard.

**Comment by AlexGuteniev** [comment]
> 4\. there's a "fastfail" intrinsic but due to platform variation reasons we don't use it in STL headers.

Apparently, after making Windows 8 or newer the minimum version, it is possible to use `__fastfail`, as it is required by the OS.

**Comment by AlexGuteniev** [comment]
Now we still have non-unified fatal error handling:
 * `terminate()`
 * `abort()`
 * `_STL_VERIFY(...)` 
 * `_STL_REPORT_ERROR(...)`
 * `__fastfail()` backed by `abort()` (one occurrence)
 * `_STL_INTERNAL_CHECK(...)`
 * `_STL_ASSERT(...)`

However, the original concern about `abort()` / `terminate()` was addressed. Should we close the issue?

**Comment by StephanTLavavej** [comment]
I think we can go ahead and close this. The other functions are for various kinds of checking and there's some reason for variation (changes may be possible but that would be a separate issue).
