### ISSUE TITLE
P0896R4 <ranges>

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#39]
[P0896R4](https://wg21.link/P0896R4) `<ranges>`
[P1035R7](https://wg21.link/P1035R7) Input Range Adaptors
[P1207R4](https://wg21.link/P1207R4) Movability Of Single-Pass Iterators
[P1243R4](https://wg21.link/P1243R4) Rangify New Algorithms
[P1248R1](https://wg21.link/P1248R1) Fixing Relations
[P1252R2](https://wg21.link/P1252R2) Ranges Design Cleanup
[P1391R4](https://wg21.link/P1391R4) Range Constructor For `string_view`
[P1456R1](https://wg21.link/P1456R1) Move-Only Views
[P1474R1](https://wg21.link/P1474R1) Helpful Pointers For `contiguous_iterator`
[P1522R1](https://wg21.link/P1522R1) Iterator Difference Type And Integer Overflow
[P1523R1](https://wg21.link/P1523R1) Views And Size Types
[P1638R1](https://wg21.link/P1638R1) `basic_istream_view::iterator` Should Not Be Copyable
[P1716R3](https://wg21.link/P1716R3) Range Comparison Algorithms Are Over-Constrained
[P1739R4](https://wg21.link/P1739R4) Avoiding Template Bloat For Ranges
[P1862R1](https://wg21.link/P1862R1) Range Adaptors For Non-Copyable Iterators
[P1870R1](https://wg21.link/P1870R1) `safe_range`
[P1871R1](https://wg21.link/P1871R1) `disable_sized_sentinel_for`
[P1878R1](https://wg21.link/P1878R1) Constraining Readable Types
[P1970R2](https://wg21.link/P1970R2) `ranges::ssize`
[P1983R0](https://wg21.link/P1983R0) Fixing Minor Ranges Issues
[P1994R1](https://wg21.link/P1994R1) `elements_view` Needs Its Own `sentinel`
[P2091R0](https://wg21.link/P2091R0) Fixing Issues With Range Access CPOs
[P2106R0](https://wg21.link/P2106R0) Range Algorithm Result Types

LWG-3169 `ranges` permutation generators discard useful information
LWG-3173 Enable CTAD for ref-view
LWG-3179 `subrange` should always model `Range`
LWG-3180 Inconsistently named return type for `ranges::minmax_element`
LWG-3183 Normative permission to specialize Ranges variable templates
LWG-3186 `ranges` removal, partition, and `partial_sort_copy` algorithms discard useful information
LWG-3191 `std::ranges::shuffle` synopsis does not match algorithm definition
LWG-3276 Class `split_view::outer_iterator::value_type` should inherit from `view_interface`
LWG-3280 View converting constructors can cause constraint recursion and are unneeded
LWG-3281 Conversion from *pair-like* types to `subrange` is a silent semantic promotion
LWG-3282 `subrange` converting constructor should disallow derived to base conversions
LWG-3286 `ranges::size` is not required to be valid after a call to `ranges::begin` on an input range
LWG-3291 `iota_view::iterator` has the wrong `iterator_category`
LWG-3292 `iota_view` is under-constrained
LWG-3299 Pointers don't need customized iterator behavior
LWG-3301 `transform_view::iterator` has incorrect `iterator_category`
LWG-3302 Range adaptor objects `keys` and `values` are unspecified
LWG-3313 `join_view::iterator::operator--` is incorrectly constrained
LWG-3323 *has-tuple-element* helper concept needs `convertible_to`
LWG-3325 Constrain return type of transformation function for `transform_view`
LWG-3335 `range_size_t` and `views::all_t`
LWG-3355 The memory algorithms should support move-only input iterators introduced by P1207
LWG-3363 `drop_while_view` should opt-out of `sized_range`
LWG-3364 Initialize data members of ranges and their iterators
LWG-3381 `begin` and `data` must agree for `contiguous_range`
LWG-3384 `transform_view::sentinel` has an incorrect `operator-`
LWG-3385 `common_iterator` is not sufficiently constrained for non-copyable iterators
LWG-3387 `[range.reverse.view]` `reverse_view<V>` unintentionally requires `range<const V>`
LWG-3388 `view` iterator types have ill-formed `<=>` operators
LWG-3389 A move-only iterator still does not have a `counted_iterator`
LWG-3397 `ranges::basic_istream_view::iterator` should not provide `iterator_category`
LWG-3398 `tuple_element_t` is also wrong for `const subrange`
LWG-3474 Nesting `join_view`s is broken because of CTAD
LWG-3500 `join_view::iterator::operator->()` is bogus
LWG-3505 `split_view::`*`outer-iterator`*`::operator++` misspecified

Feature-test macro as of WG21-N4842, increased by WG21-P1902:
`#define __cpp_lib_ranges 201911L`

**Comment by CaseyCarter** [comment]
Detailed breakdown / rough plan-of-action for Ranges:

* [X] P0898R3 "Standard Library Concepts"
  * Changes to `common_type` and addition of `common_reference` ([MSVC-PR-179742](https://devdiv.visualstudio.com/DevDiv/_git/msvc/pullrequest/179742))
  * Addition of `<concepts>` (with P0896R4's changes to `Swappable`/`SwappableWith`) ([MSVC-PR-182506](https://devdiv.visualstudio.com/DevDiv/_git/msvc/pullrequest/182506))
* [X] Iterator machinery in `<xutility>` ([MSVC-PR-194010](https://devdiv.visualstudio.com/DevDiv/_git/msvc/pullrequest/194010))
  * Traits: `incrementable_traits`, `readable_traits`, `iterator_traits`
  * CPOs: `iter_move`, `iter_swap`
  * Aliases: `iter_XXXX_t`
  * Concepts: `readable`, `writable`, ... `random_access_iterator`, `contiguous_iterator`
  * P1207's changes to `weakly_incrementable`
  * P1754's concept renaming.
* [X] Range machinery in `<xutility>` ([GH-82](https://github.com/microsoft/STL/pull/82))
  * CPOs: `c?r?(begin|end)`, `c?data`, `empty`, `size` (P1523 changes)
  * Aliases: `iterator_t`, `sentinel_t`
  * P1035's `range_XXXX_t` composed aliases
  * Concepts: `XXX_range`, `view`, ...
  * P1474R changes to ``contiguous_iterator`
* [X] Update "old" range types ([GH-95](https://github.com/microsoft/STL/pull/95))
  * to model `contiguous_range`: `array`, `basic_string`, `basic_string_view`, `valarray`, `vector` (not `span` yet)
  * and *`forwarding-range`*: `basic_string_view` (not `span` yet)
* [X] More iterator machinery in `<xutility>` ([GH-329](https://github.com/microsoft/STL/pull/329))
  * Primitives: `ranges::advance`, `ranges::next`, `ranges::prev`, `ranges::distance`
  * `default_sentinel`
  * `unreachable_sentinel`
* [X] Functional machinery
  * `identity` ([MSVC-PR-167844](https://devdiv.visualstudio.com/DevDiv/_git/msvc/pullrequest/167844))
  * `ranges::equal_to` and `ranges::less` in `<xutility>`, other `ranges` comparison function objects in `<functional>` ([GH-385](https://github.com/microsoft/STL/pull/385))
* [X] Misc range concepts ([GH-389](https://github.com/microsoft/STL/pull/389))
  * [P1870R1](https://wg21.link/p1870r1) `safe_range`
  * Relax copyability requirement of `view` concept (Partially implements [P1456R1 "Move-Only Views"](https://wg21.link/p1456r1))
  * `viewable_range` concept
* [X] Fix various issues with Range Access CPOs (investigation for [P2091](https://wg21.link/p2091r0)) ([GH-432](https://github.com/microsoft/STL/pull/432))
* [X] Algorithm machinery in `<xutility>` ([GH-565](https://github.com/microsoft/STL/pull/565))
  * Indirect callable concepts / Common algorithm requirements
  * `indirectly_swappable`
  * `projected`
  * `dangling`, `borrowed_iterator_t`
  * [P2106R0](https://wg21.link/p2106r0) generic algorithm result types
  * `<algorithm>`s batch 1:
    * `copy`/`copy_n`/`copy_if`
    * `all_of`/`any_of`/`none_of`
    * `find`/`find_if`/`find_if_not`
    * `count`/`count_if`
    * `for_each`/`for_each_n`
    * `equal`/`mismatch`
* [X] LWG-3326 "`enable_view` has false positives" ([GH-588](https://github.com/microsoft/STL/pull/588))
* [X] insert iterators ([GH-589](https://github.com/microsoft/STL/pull/589))
* [ ] Iterator adaptors, old and new:
  * [X] [P1871R1: Rename `disable_sized_sentinel` to `disable_sized_sentinel_for`](https://wg21.link/p1871r1) ([GH-607](https://github.com/microsoft/STL/pull/607))
  * [ ] stream iterators
  * [ ] `reverse_iterator` (WIP)
  * [ ] `move_iterator` (don't forget P1252 deprecation), `move_sentinel` (P1207 changes) (WIP)
  * [ ] `common_iterator`
  * [ ] `counted_iterator` (P1207 changes)
  * [ ] Strengthen `noexcept` on all of the above
* [ ] Many simple range `<algorithm>`s
* [ ] Range adaptor machinery
  * `views::all` and `views::all_t`
  * `view_interface`, closure stuff, `_Semiregular_box` (WIP)
  * `ref_view` (LWG 3173), `subrange` (LWG 3179, [tuple.helper] changes, P1523) (WIP)
  * `borrowed_subrange_t` (WIP)
* [ ] Range factories in `<ranges>`:
  * P1522 changes to `weakly_incrementable`
  * `iota_view` (P1522 changes)
  * `empty_view` (P1523 changes)
  * `single_view` (P1523 changes)
  * ...
* [ ] Range adaptors Part 1:
  * `common_view`
  * `views::counted`
  * `filter_view`
  * `reverse_view` (Don't forget P1252)
  * `transform_view`
* [ ] Range adaptors Part 2:
  * `basic_istream_view` (P1638 changes)
  * `drop_view`
  * `drop_while_view`
  * `elements_view` (`keys_view`, `values_view`)
  * `join_view`
  * `split_view`
  * `take_view`
  * `take_while_view`
* [ ] Few complicated range `<algorithm>`s (Some of these can't be imported from cmcstl2 for license reasons.)
* [ ] Special `<memory>` range algorithms
* [ ] Define `__cpp_lib_ranges`
* "Future work"
  * Refactor to share code in the `std` and `ranges` algorithms
  * Enable all of the `memcmp`/`memset`/`memcpy`/vector optimizations that the `std` algorithms perform
  * Consider relaxing "old" library components to accept more "new" iterators (For C++23: do we change *everything* to support and require "new" iterators? Do we change everything to support *both* "old" and "new" iterators?)

**Comment by Lyberta** [comment]
Looks like the roadmap ignores `std::ranges::ssize` (it is mentioned in the first message though). It is logical to add it before the algorithms.

**Comment by StephanTLavavej** [comment]
Thanks @Lyberta - I've added it right after the "simple range algorithms"; although that may be a less logical placement, I felt that grouping it with other unchecked checkboxes would make it harder to miss.

**Comment by CaseyCarter** [comment]
> Looks like the roadmap ignores `std::ranges::ssize` (it is mentioned in the first message though). It is logical to add it before the algorithms.

I've been putting off `ranges::ssize` since `ranges::distance` provides almost equivalent functionality with the same `sized_range` requirement, and because the existing spec for `ssize` is borked (LWG-3403). But since you went to the trouble to come here and request it, I've submitted a proposed resolution for the LWG issue and implemented `ranges::ssize`.

**Comment by CaseyCarter** [comment]
We need to file separate issues for these future work items:
  * Refactor to share code in the `std` and `ranges` algorithms
  * Apply the exponential probing technique from `partition_point` to the binary search family.
  * Enable all of the `memcmp`/`memset`/`memcpy`/vector optimizations that the `std` algorithms perform
  * Consider relaxing "old" library components to accept more "new" iterators (For C++23: do we change *everything* to support and require "new" iterators? Do we change everything to support *both* "old" and "new" iterators?)
  * Re-evaluate the iterator unwrapping story in the face of the experience gained writing the algorithms and range adaptors.

**Comment by AdamBucior** [comment]
>   * [x]  `adjacent_find` ([GH-322](https://github.com/microsoft/STL/issues/322))

BTW this should be GH-822

**Comment by StephanTLavavej** [comment]
Thanks @AdamBucior, fixed. (@CaseyCarter may sleep but I don't! :night_with_stars: :owl:)

**Comment by CaseyCarter** [comment]
> We need to file separate issues for these future work items:

So filed, except for:

> * Design issue: should `viewable_range` reject lvalues of move-only `view` types? (This is [LWG-3481](https://cplusplus.github.io/LWG/issue3481); we don't need to track it here.)

for which I filed an LWG issue a while back.
