### ISSUE TITLE
`<valarray>`: Consider replacing `size()` calls with `_Mysize`

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#3915]
Followup issue after discussion in #3911, to improve debug codegen for a minor editing cost.

As @AlexGuteniev mentioned in https://github.com/microsoft/STL/pull/3911#issuecomment-1656875296 , `<valarray>` is currently extremely careful to extract the size to a local variable to avoid aliasing, which is important for vectorizing its following loops. When replacing calls of `size()` with direct access to `_Mysize`, the local variables should be preserved. We may even want to add comments like `// avoid aliasing` as a small reminder about this somewhat unusual pattern.

**Comment by AlexGuteniev** [comment]
Fun facts:
* Capturing `size()` was suggested by @miscco for a reason unrelated to vectorization. Back then I had less experience with vectorization and didn't see it also helps vectorizing https://github.com/microsoft/STL/pull/1165#discussion_r467483702
* There's still a place where we don't capture size - it is `_Tidy_deallocate()`. Capturing `_Mysize` there wouldn't normally help vectorization, as the types that are vectorized are normally trivially destructible. For debug codegen `if constexpr` skipping that part may help

https://github.com/microsoft/STL/blob/0fe653a9d6efd2ac0ad07825804436672dbffe3b/stl/inc/valarray#L558-L560
