### ISSUE TITLE
`<__msvc_chrono.hpp>`: `duration_cast` only needs compile time branches

### ISSUE THREAD

**Issue by frederick-vs-ja** [microsoft/STL#3929]
The conditions of the if statements in `duration_cast` are all constant expressions, so we can change all of these occurences of plain `if` to `if constexpr`.

https://github.com/microsoft/STL/blob/ed8150e099f6124c50dd4f002cd2ab8c429a81e3/stl/inc/__msvc_chrono.hpp#L428-L447

_Originally posted by @achabense in https://github.com/microsoft/STL/issues/3914#issuecomment-1663572154_

This issue is intended for a new contributor (especially one new to GitHub) to get started with the simplest possible change.

Please feel free to submit a pull request if there isn't one already linked here - no need to ask for permission! 😸

You can (and should) link your pull request to this issue using [GitHub's close/fix/resolve syntax](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

**Comment by achabense** [comment]
Btw, this would be a followup towards #189

**Comment by achabense** [comment]
Extra background: though this is a C++17 feature, we are free to add `if constexpr` wherever suitable (see #189).
