### ISSUE TITLE
Are `long double`s with different implementations supported?

### ISSUE THREAD

**Issue by AlexGuteniev** [microsoft/STL#3931]
MSVC supports `float`, `double` and `long double` but `long double` is the same as `double`.

However with classic FPU instructions, x86 provides a native support for a more precise type than the usual `double`. Some implementations may use that as underlying implementation of `long double`. MSVC doesn't, but maybe Intel Compiler or Clang or CUDA has a switch for that support.

Does such a switch exist? Do we need to support that?

The question is for #3928 , where I assume that `long double` is the same as `double`. The vector algorithm may return a totally wrong pointer for array of `long double`s of different implementation.

**Comment by sylveon** [comment]
No, see https://github.com/microsoft/STL/pull/1316

**Comment by AlexGuteniev** [comment]
> No, see #1316

Thanks, I forgot about that precedent
