### ISSUE TITLE
`<format>`: Parsing error when using `std::format` inside a lambda

### ISSUE THREAD

**Issue by Caball009** [microsoft/STL#3938]
Using `std::format` inside a lambda can lead to parsing errors in certain scenarios, as shown in the first link and code sample below. The second and third link may provide some more data about the nature of the problem.

https://godbolt.org/z/nx98Tvf9v

https://godbolt.org/z/Yz4WM6j3P
https://godbolt.org/z/GjaxWEPP4

The code from the first link for posterity's sake:
```
#include <filesystem>
#include <format>
#include <functional>

void FileTree(std::function<void(std::filesystem::path)>)
{}

bool Button(const char*)
{
    return true;
}

int main()
{
    // works fine outside the lambda
    if (Button(std::format("Load##{0}", "").c_str())) 
    {}

    FileTree([](std::filesystem::path) 
    {
        // works fine when not part of the if statement
        const auto str = std::format("Load##{0}", "");

        if (Button(str.c_str())) 
        {}

        // works fine when the result is stored and compared
        if (const auto b = Button(std::format("Load##{0}", "").c_str()); b) 
        {}

        // does not work like this
        if (Button(std::format("Load##{0}", "").c_str())) 
        {}
    });
}
```
Error messages:
`C:/data/msvc/14.36.32530-Pre/include\format(1099): error C2760: syntax error: 'member initializer' was unexpected here; expected ')'`
`C:/data/msvc/14.36.32530-Pre/include\format(1099): error C2760: syntax error: ';' was unexpected here; expected ')'`

**Comment by CaseyCarter** [comment]
First-pass reduces to:
```c++
#include <format>

std::string meow(const std::format_string<int>);

#if 0 // Primary repro
int main() {
    (void)[] { // format(1163): error C2760: syntax error: 'member initializer' was unexpected here; expected ')'
        if (meow("{0}").c_str())
            ;
    };
}
#elif 0 // Similar, but I think very related repro?
int main() {
    [] { // error C3409: empty attribute block is not allowed
        if (meow("{0}").c_str())
            ;
    };
}
#else
auto woof = [] { // format(1163): error C3878: syntax error: unexpected token 'member initializer' following 'expression'
    if (meow("{0}").c_str())
        ;
};
#endif
```
This feels like a parsing issue to me so I'm going to file a compiler bug, but without further reducing since both `basic_string` and `basic_format_string` seem to be involved and I don't want to overreduce.

The compiler issue is DevCom-10433589.

**Comment by cpplearner** [comment]
The error message points to the definition of `_Id_adaptor`.

https://github.com/microsoft/STL/blob/ed8150e099f6124c50dd4f002cd2ab8c429a81e3/stl/inc/format#L1264

`_Id_adaptor` objects are created when parsing *arg-id*s (the `0` in `{0}`). But I don't understand how this causes a syntax error.

**Comment by cpplearner** [comment]
Reduced:

```c++
struct String {
    const char *c_str();
};

struct Id_adapter {
    int &ref;
    int id = -1;
};

struct Format_string {
    consteval Format_string(const char *) {
        int v;
        Id_adapter h{v};
    }
};

String meow(Format_string);

#if 1 // Primary repro
int main() {
    (void)[] { // error C2760: syntax error: 'member initializer' was unexpected here; expected ')'
        if (meow("").c_str())
            ;
    };
}
#elif 0 // Similar, but I think very related repro?
int main() {
    [] { // error C3409: empty attribute block is not allowed
        if (meow("").c_str())
            ;
    };
}
#else
auto woof = [] { // error C3878: syntax error: unexpected token 'member initializer' following 'expression'
    if (meow("").c_str())
        ;
};
#endif
```

**Comment by CaseyCarter** [comment]
> Reduced:

Awesome, thanks! I've linked this library-free repro to the internal bug tracker.

**Comment by StephanTLavavej** [comment]
Thanks again for reporting this compiler bug; with the library-free repro and the DevCom issue filed, we've done all we can in the microsoft/STL repo and will close this GitHub issue as "external" now. (We've also pinged the compiler dev who maintains lambdas.)
