### ISSUE TITLE
questions about `<xmath.hpp>`

### ISSUE THREAD

**Issue by achabense** [microsoft/STL#3942]
<details>
<summary>Solved</summary>

1. It seems to me that all these functions are just defined, but are neither exported nor called. Can we remove them?
https://github.com/microsoft/STL/blob/ed8150e099f6124c50dd4f002cd2ab8c429a81e3/stl/src/xmath.hpp#L87-L96
2. It seems these functions(also their `_Fxp` and `_Lxp` versions) are neither defined nor referred-to. Can we remove them?
https://github.com/microsoft/STL/blob/ed8150e099f6124c50dd4f002cd2ab8c429a81e3/stl/src/xmath.hpp#L117-L125
</details>

3. I notice that `_Dval`, `_Fval` and `_Lval` are using wrong array size, and are only used/passed(only by `_Dnorm(_Dval*)` and `_FDnorm(_Fval*)`) via pointers. Can we correct array size for them?
https://github.com/microsoft/STL/blob/ed8150e099f6124c50dd4f002cd2ab8c429a81e3/stl/src/xmath.hpp#L99-L102
https://github.com/microsoft/STL/blob/ed8150e099f6124c50dd4f002cd2ab8c429a81e3/stl/src/xmath.hpp#L128-L131
https://github.com/microsoft/STL/blob/ed8150e099f6124c50dd4f002cd2ab8c429a81e3/stl/src/xmath.hpp#L155-L158

**Comment by frederick-vs-ja** [comment]
Some functions are actually used via tricky macro expansions, see https://github.com/microsoft/STL/issues/3622#issuecomment-1495788207.

I attempted to remove some of them but have given up (at least for now) due these annoying (although helpful) macros.

**Comment by StephanTLavavej** [comment]
We can't mess with `_Dconst`, that appears on the export surface (and has a TRANSITION, ABI comment).

I think we might be able to mess with `_Fval`, `_Dval`, `_Lval` based on our clearer understanding of the differences between:

* Dllexported functions (can't remove them, can't change their interfaces, currently can't add them unless we revisit that policy)
* Import lib-injected functions (can't remove them, can't change their interfaces, but can add more)
* Cross-TU functions that aren't dllexported or import lib-injected (can change freely)

I think that these are cross-TU but not dllexported or import lib-injected. We should also be able to rework `extern const _Dconst _FEps;` etc. (as they themselves are not dllexported).

To be safe, we should `_v2` both the types and the functions. Even if mismatches aren't a concern, this makes reasoning about the code much easier.

Please note - messing with this old code is fairly low value and the maintainer team has sharply limited review capacity for the foreseeable future. Simple transformations are probably low risk but I am not especially eager to review large-scale changes in this area at this time. Additionally, I believe that much of this code may simply be unused except for bincompat - e.g. `_Stodx` was the entry point for most of it, but we've moved on to using an `inline` `_Stodx_v3` that bypasses all of this code and simply calls `strtod`. Overall I am interested in changes that remove lots of code (e.g. #3936 was great), and changes that improve performance for active code. However, reducing the sizes of data structures used by code-retained-for-bincompat-only is not really making anyone's experience better.

So what I would be looking for is:

* Changes that remove code, with brief analysis of why this is a compatible change,
* Changes that improve efficiency (e.g. reducing overly-bloated unions), with a brief explanation of how this codepath is still active for modern users.

**Comment by achabense** [comment]
Thanks for clarification! I'm much more confident about bincompat things.
