### ISSUE TITLE
`<chrono>`: Question on recency of timezone database and leap second table

### ISSUE THREAD

**Issue by kmccarty-dgi** [microsoft/STL#3953]
Hello!  I am wondering about the recency of the information obtained from the MS implementation of timezones in `<chrono>`, which to the best of my understanding, is based on a copy of ICU that ships outside the control of the STL team.

Running the following program on my Windows 10 machine (updated to 22H2) prints "2021a.27" which seems a bit stale --

```
// Build with Visual C++ 2022: cl /EHsc /std:c++20 test.cpp
#include <chrono>
#include <iostream>

int main()
{
    const auto & db = std::chrono::get_tzdb();
    std::cerr << db.version << "\n";
}
```

Version info for my `C:\Windows\System32\icu.dll` shows that it is at version 64.2.0.0.

Questions
=======
* Is there a Microsoft-blessed way that I (either as a normal user, or as administrator) can install an update for this copy of ICU?  I found https://github.com/microsoft/icu but it isn't clear to me if there is any easy way to install updated DLLs from here.
* If not, is there a way that I can install an update for just the timezone data, separately from the DLL?
* Are there plans in the future to include ICU and/or timezone data updates automatically as a normal part of the Windows update infrastructure?  (Otherwise we certainly cannot rely on our customers having installed the updates.)
* Should I presume / is it safe to programmatically determine, based on the version number "2021a.27", that the timezone database is up-to-date only as of sometime in 2021?  Or does it have a potential to contain newer updates that don't touch the (year part of the) tzdb version number?
* Is the leap second info any more up-to-date than the timezone database?  (This is of course purely a theoretical question until a new leap second is inserted, since the last one was end-of-2016.)  I came across https://github.com/microsoft/STL/discussions/1624 that gave me some reason to believe that the `<chrono>` implementation is using a separate source for leap second data, than for timezone data.
* If so, then is there any way to programmatically determine how recent the leap second info is?  (Again, just querying the last-known leap second in the table is not currently very helpful since that is currently the one at the end of 2016 :-) )

Thanks very much for your time!

**Comment by kmccarty-dgi** [comment]
Cross-referencing https://github.com/microsoft/icu/issues/125 here.

**Comment by MattStephanson** [comment]
I wrote the leap second code, so I can speak to that.

> Is the leap second info any more up-to-date than the timezone database?

Maybe. The ICU doesn't have leap second data, so the two are completely independent. The 27 past leap seconds (as of 2023) are hard-coded. I reverse-engineered the registry leap second data, so if you're running a version of Windows that has that, it will be checked when the `tzdb_list` is initially loaded and when you call `reload_tzdb`.

The hard-coded list can be updated if future leap seconds are added, but users would need an updated STL to take advantage of that.

> is there any way to programmatically determine how recent the leap second info is? 

I'm not aware of any versioning info for the registry leap second data, so I can't think of any way to check if it's up-to-date without already knowing the correct number of leap seconds.

**Comment by MattStephanson** [comment]
> is there a way that I can install an update for just the timezone data, separately from the DLL?

I don't think so. icu.dll is loaded here:

https://github.com/microsoft/STL/blob/8674b3d732a2bae43105fb7654d3b8c1c57adb56/stl/src/tzdb.cpp#L66

The `LOAD_LIBRARY_SEARCH_SYSTEM32` flag means that only %windows%\system32 is searched.

**Comment by StephanTLavavej** [comment]
@kmccarty-dgi
> * Is there a Microsoft-blessed way that I (either as a normal user, or as administrator) can install an update for this copy of ICU?  I found https://github.com/microsoft/icu but it isn't clear to me if there is any easy way to install updated DLLs from here.

Not at this time. This `icu.dll` is part of Windows.

> * If not, is there a way that I can install an update for just the timezone data, separately from the DLL?

No. We rely exclusively on `icu.dll` with no way to overlay an update.

> * Are there plans in the future to include ICU and/or timezone data updates automatically as a normal part of the Windows update infrastructure?  (Otherwise we certainly cannot rely on our customers having installed the updates.)

We believe that ICU is updated semi-regularly via Windows Update, but the cadence of such updates is determined by the Windows team. If Windows has updated the list of timezones that are available to select in the OS, but has not updated ICU correspondingly, then that seems like a bug that should be reported to Windows via their Feedback Hub app.

> * Should I presume / is it safe to programmatically determine, based on the version number "2021a.27", that the timezone database is up-to-date only as of sometime in 2021?  Or does it have a potential to contain newer updates that don't touch the (year part of the) tzdb version number?

We obtain that `"2021a"` component from `icu.dll`; we can't say it's safe to make such assumptions about its meaning.

> * If so, then is there any way to programmatically determine how recent the leap second info is?  (Again, just querying the last-known leap second in the table is not currently very helpful since that is currently the one at the end of 2016 :-) )

@MattStephanson
> I'm not aware of any versioning info for the registry leap second data, so I can't think of any way to check if it's up-to-date without already knowing the correct number of leap seconds.

FYI (for @kmccarty-dgi), we're not sure if you realized the significance of this number, but the `".27"` part of the version string refers to the number of known leap seconds:

https://github.com/microsoft/STL/blob/8674b3d732a2bae43105fb7654d3b8c1c57adb56/stl/inc/chrono#L2196-L2198

Of course, this doesn't map to how *recently* the information was updated, but at least it captures how much information we have.

**Comment by kmccarty-dgi** [comment]
Thank you @MattStephanson and @StephanTLavavej, the information is much-appreciated!
Kevin
