### ISSUE TITLE
Coroutine + exceptions ?+ debug msvc runtime? = segfault

### ISSUE THREAD

**Issue by kelbon** [microsoft/STL#3957]
I have generator coroutine and test:

```C++
generator<int> g() {
  throw 0; // 'unhandled_exception' just rethrows
  co_return;
}

int foo() {
try {
  for(auto x : g()) (void)0;
} catch(...) {
  // destructor for exception called by compiler, SEGFAULT
  // because somehow exception is on 'generator' frame,
  // while its deallocated in destructor of 'g' object in 'try' section
  // and i have no such problem on gcc/clang with all sanitizers, (see link) and even no such problem in release
  // so i think its just msvc debug runtime libs / msvc runtime for exceptions
}
}
```

Full code witih tests (broken only 2 under 'ifdef')

 https://github.com/kelbon/kelcoro/blob/776770b82f36ad2f11ff9266a1121b6704cdc6e4/tests/tests_generator.cpp#L655

```shell
git clone https://github.com/kelbon/kelcoro
cd kelcoro
cmake . -B build -G "Visual Studio 17"  -DKELCORO_ENABLE_TESTING=ON
cmake --build build
cd build
ctest -C Debug -R .*gene.* --output-on-failure
```

**Comment by kelbon** [comment]
P.S. its breakes with clang compiler(only on windows debug)
clang --version
clang version 15.0.1
Target: x86_64-pc-windows-msvc
Thread model: posix

**Comment by StephanTLavavej** [comment]
I can't reproduce this with microsoft/STL `main` compiled by Clang 17.0.3 x64 (from VS 2022 17.9 Preview 5), in debug mode as specified (`/MTd`). Extracting your code into a single source file compiles and runs normally, no crash.

Please let us know if you continue to see this.

**Comment by kelbon** [comment]
@StephanTLavavej 
https://github.com/kelbon/kelcoro/pull/48

pretty similar

```cpp
dd::task<int> foo1(int i) try {
  abc c;
  for (;;) {
    if (i == 42)
      co_return 0;
    co_await std::suspend_always{};

    try {
      bar(c);
      break;
    } catch (std::exception& e) {
      std::cout << '"' << e.what() << '"';
    }
  }
  throw "";
} catch (...) {
  co_return 0;
}
```

Here in catch block memory under exception already invalidated

Segfaults only on windows
