### ISSUE TITLE
GitHub: File validation interacts badly with PRs adding submodules

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#396]
Our automation to "validate" files for whitespace, line endings, and non-ASCII characters doesn't handle submodule additions very well. We have a hardcoded list of directories to skip when validating:

https://github.com/microsoft/STL/blob/098333c9126c4df2370b3d08f8800bb5e3d82f1e/tools/validate/validate.cpp#L155-L162

Here's the problem scenario:

1. A PR adds a `cat` submodule, and updates `validate.cpp` to skip that directory.
2. The VMs properly init that submodule, and skip it while validating.
3. At this point, the `cat` PR hasn't been merged yet!
4. A totally separate PR (modifying `mouse` machinery or whatever) triggers checks on those VMs.
5. The VMs don't clean out the `cat` directory, and the `mouse` PR doesn't contain `validate.cpp` changes to skip `cat`, so all of the `cat` files are scanned and fail to validate.

I suspect that this is involved:

https://github.com/microsoft/STL/blob/098333c9126c4df2370b3d08f8800bb5e3d82f1e/azure-devops/run_build.yml#L13-L14

According to the [YAML schema](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#checkout), do we need to set `clean: true` so we don't have to worry about lingering submodules?

**Comment by Akoneto9** [comment]
Hello

**Comment by StephanTLavavej** [comment]
@cbezault just encountered another form of this - submitting a PR that emits new files/directories that are also added to `.gitignore` contaminates the VMs.

**Comment by StephanTLavavej** [comment]
This wasn't cured after all - #2780 (adding a `benchmarks/google-benchmark` submodule) contaminated a run for #2811 (making an unrelated visualizer change). We probably would have noticed this earlier if adding submodules happened more often.

The [raw_log.txt](https://github.com/microsoft/STL/files/8965965/raw_log.txt) reveals the problem:

```
...
##[command]git clean -ffdx
Removing tests/std/tests/Dev09_056375_locale_cleanup/__pycache__/
Removing tests/std/tests/Dev09_172666_tr1_tuple_odr/__pycache__/
Removing tests/std/tests/GH_000545_include_compare/__pycache__/
Removing tests/std/tests/P0607R0_inline_variables/__pycache__/
Removing tests/std/tests/P1502R1_standard_library_header_units/__pycache__/
Removing tests/std/tests/VSO_0000000_any_calling_conventions/__pycache__/
Removing tests/std/tests/VSO_0000000_matching_npos_address/__pycache__/
Removing tests/utils/stl/__pycache__/
Removing tests/utils/stl/test/__pycache__/
##[command]git reset --hard HEAD
HEAD is now at 2542aa00 Merge 36798a7cd9176b5de0b5f45719f0be83dc61ce9c into 7f04137880e1c3df5125c1baf808f16f399dee2e
...
##[command]git checkout --progress --force refs/remotes/pull/2811/merge
warning: unable to rmdir 'benchmarks/google-benchmark': Directory not empty
Previous HEAD position was 2542aa00 Merge 36798a7cd9176b5de0b5f45719f0be83dc61ce9c into 7f04137880e1c3df5125c1baf808f16f399dee2e
HEAD is now at f25805ba Merge 84a9095de7a38d21148f29b0970a0573e889d2a5 into 7f04137880e1c3df5125c1baf808f16f399dee2e
...
```

The [`clean: true` documentation](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/pipeline-options-for-git?view=azure-devops&tabs=yaml) says "When set to `true`, the pipeline runs execute `git clean -ffdx && git reset --hard HEAD` before fetching the repo." This appears to be accurate, but it doesn't solve the problem we have! The `git clean -ffdx` is running *before* checking out the commit we want to build. In this "before" state, the submodule still exists, so the clean skips it. It's when we `git checkout` the commit to build, that `git` notices that the new commit doesn't contain the submodule, and (to avoid data loss) dutifully reports that it will not `rmdir` the non-empty directory. If we cleaned *after* checking out the commit, `git clean -ffdx` would remove the contaminating submodule - but there appears to be no way to request specifically that.

However, [other documentation](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml#workspace) suggests that we may be able to use `workspace: clean: all`. If I understand the docs right, this would be a true clean.

In theory we can confirm that this works, although doing so would require a delicate dance. It might be easier to just inspect the logs to verify the true clean.
