### ISSUE TITLE
<deque>: Support incomplete value type

### ISSUE THREAD

**Issue by zhihaoy** [microsoft/STL#3961]
# Describe the bug
Certain standard sequence containers, such as `list` and `vector`, allow the value type to be an incomplete type to support recursive data structures. Although it's not a part of the standard (yet), Microsoft STL's `deque` implementation should consider supporting this. libstdc++ and libc++ since ABI version 2 (contributed by Google) have this support.

See also: https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/n4510.html

# Godbolt test case

https://godbolt.org/z/7fEbPnTc3

```cpp
#include <deque>

struct Entry
{
    std::deque<Entry> messages;
    // ...
};
```

# Expected behavior
Compiles without error.

# STL version
Any.

# Additional context

It could be done in vNext, as a part of #147.

**Comment by fsb4000** [comment]
I'm sorry. The issue has been discussed before and will not be fixed: https://github.com/microsoft/STL/issues/108

**Comment by zhihaoy** [comment]
Let me check the reason:

> We talked about this at the weekly maintainer meeting and have consensus to close this PR. If the Standard is changed in the future to require `deque<Incomplete>` then merging such a change will be possible.

I was told "we (MSVC STL) cannot support [n3890](https://www.open-std.org/JTC1/SC22/WG21/docs/papers/2014/n3890.html) because we don't want to break ABI," which is why I removed `deque` from [n4510](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/n4510.html). Supporting the change in major implementations may be a better way than forming a loop here.

**Comment by StephanTLavavej** [comment]
We talked about this at the weekly maintainer meeting, and our view is unchanged: supporting incomplete value types in `deque` would be a non-Standard extension, which is explicitly a [non-goal](https://github.com/microsoft/STL#non-goals) of our project.

**Comment by frederick-vs-ja** [comment]
I've moved the requested changes to [this non-official branch](https://github.com/frederick-vs-ja/STL/tree/feature/deque-of-incomplete-element-types). IIUC the changes won't break ABI, and it's possibly OK to write a new paper to support `deque<Incomplete>`.
