### ISSUE TITLE
`vector_algorithms.cpp`: turn tails

### ISSUE THREAD

**Issue by AlexGuteniev** [microsoft/STL#3963]
There are some scalar tails extracted in `vector_algorithms.cpp`,
Whereas some are used multiple times, some are used just one. A few examples:
https://github.com/microsoft/STL/blob/8674b3d732a2bae43105fb7654d3b8c1c57adb56/stl/src/vector_algorithms.cpp#L1057-L1058
https://github.com/microsoft/STL/blob/8674b3d732a2bae43105fb7654d3b8c1c57adb56/stl/src/vector_algorithms.cpp#L1396
https://github.com/microsoft/STL/blob/8674b3d732a2bae43105fb7654d3b8c1c57adb56/stl/src/vector_algorithms.cpp#L1345

The tail extraction does not serve any purpose in such cases, it only provides an obstacle for debugging of optimized code (as tails are expectedly inlined. so the debugger does not navigate the lines).

**Comment by AlexGuteniev** [comment]
> Checking my understanding: You're suggesting that we should hand-inline tail-called functions with only one callsite?

Exactly.

**Comment by StephanTLavavej** [comment]
We talked about this at the weekly maintainer meeting and are highly in favor of such fusion/hand-inlining, as a stylistic preference.
