### ISSUE TITLE
Questions about visualizer

### ISSUE THREAD

**Issue by achabense** [microsoft/STL#3979]
1. The link here has been broken. (`The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.`) Should we do something for it?
https://github.com/microsoft/STL/blob/60f18856c56389001c38a9929ef37bd5c01c4e47/stl/debugger/STL.natvis#L7

2. There are empty classes that have empty expansion; are they on purpose?
https://github.com/microsoft/STL/blob/60f18856c56389001c38a9929ef37bd5c01c4e47/stl/debugger/STL.natvis#L273-L276
![gif](https://github.com/microsoft/STL/assets/60953653/bf28bc32-c373-4b97-98e2-39415244935b)

3. Some non-empty classes also have empty expansions; are they on purpose? What's the rule for the usage of this feature?
https://github.com/microsoft/STL/blob/60f18856c56389001c38a9929ef37bd5c01c4e47/stl/debugger/STL.natvis#L688-L692

**Comment by fsb4000** [comment]
1. No, we don't need to do anything for it. The schema mentioned is just a string ID used for handling syntax correctly by the Visual Studio IDE and cannot be downloaded through a web browser.
For example a scheme for WPF apps: http://schemas.microsoft.com/winfx/2006/xaml .
You also can't download it through web browser.

**Comment by StephanTLavavej** [comment]
We seem to have forgotten what `<Expand/>` was trying to do; my vague recollection is that it inhibits the display of children data members, when the rest of the visualizer is already showing that information (as in your (3)), and this convention may have been copied into stateless classes even though it wasn't necessary there (as in your (2)). I'd recommend experimentally removing `chrono::duration`'s `<Expand/>` to confirm whether this vague recollection is accurate.

**Comment by achabense** [comment]
> it inhibits the display of children data members, when the rest of the visualizer is already showing that information ...
> I'd recommend experimentally removing chrono::duration's `<Expand/>`

Yes, the `<Expand/>` will also result in empty expansion for stateful classes.
