### ISSUE TITLE
Natvis no longer works with vc120

### ISSUE THREAD

**Issue by LennoxP90** [microsoft/STL#3986]
I have a program that I develop that still uses vc120_xp

Visual studio 2022 no longer shows std::strings or any other stl objects in the watch window anymore instead shows {...}
this used to work fine in Visual studio 2019

Natvis: Parsing natvis xml file: C:\Programming\Visual Studio 2022\Common7\Packages\Debugger\Visualizers\atlmfc.natvis.
Natvis: Parsing natvis xml file: C:\Programming\Visual Studio 2022\Common7\Packages\Debugger\Visualizers\concurrency.natvis.
Natvis: Parsing natvis xml file: C:\Programming\Visual Studio 2022\Common7\Packages\Debugger\Visualizers\cpp_rest.natvis.
Natvis: Parsing natvis xml file: C:\Programming\Visual Studio 2022\Common7\Packages\Debugger\Visualizers\ObjectiveC.natvis.
Natvis: Parsing natvis xml file: C:\Programming\Visual Studio 2022\Common7\Packages\Debugger\Visualizers\stl.natvis.
Natvis: Parsing natvis xml file: C:\Programming\Visual Studio 2022\Common7\Packages\Debugger\Visualizers\Windows.Data.Json.natvis.
Natvis: Parsing natvis xml file: C:\Programming\Visual Studio 2022\Common7\Packages\Debugger\Visualizers\windows.devices.geolocation.natvis.
Natvis: Parsing natvis xml file: C:\Programming\Visual Studio 2022\Common7\Packages\Debugger\Visualizers\windows.devices.sensors.natvis.
Natvis: Parsing natvis xml file: C:\Programming\Visual Studio 2022\Common7\Packages\Debugger\Visualizers\windows.media.natvis.
Natvis: Parsing natvis xml file: C:\Programming\Visual Studio 2022\Common7\Packages\Debugger\Visualizers\windows.natvis.
Natvis: Parsing natvis xml file: C:\Programming\Visual Studio 2022\Common7\Packages\Debugger\Visualizers\winrt.natvis.
Natvis: Parsing natvis xml file: C:\PROGRAMMING\VISUAL STUDIO 2022\COMMON7\IDE\EXTENSIONS\MICROSOFT\PYTHON\CORE\Visualizers\PythonDkm.natvis.
Natvis: C:\Programming\Visual Studio 2022\Common7\Packages\Debugger\Visualizers\stl.natvis(910,6): Successfully parsed expression '16' in type context 'std::basic_string<char,std::char_traits<char>,std::allocator<char> >'.
Natvis: C:\Programming\Visual Studio 2022\Common7\Packages\Debugger\Visualizers\stl.natvis(908,6): Error: identifier "_Mypair" is undefined
    Error while evaluating '_Mypair._Myval2._Myres' in the context of type 'mmserver-dt-10.exe!std::string'.
Natvis: C:\Programming\Visual Studio 2022\Common7\Packages\Debugger\Visualizers\stl.natvis(904,4): Ignoring visualizer for type 'std::basic_string<char,std::char_traits<char>,std::allocator<char> >' labeled as 'std::basic_string<char,*>' because one or more sub-expressions was invalid.

**Comment by fsb4000** [comment]
This is expected.
I dropped the support a year ago: https://github.com/microsoft/STL/commit/6c82314e1f0ccfe89988540e27bc2d99eaaea9c3
I think we don't support vc120_xp anymore...
Although I'll wait for more opinions from the maintainers: @StephanTLavavej @CaseyCarter

**Comment by fsb4000** [comment]
I think you can copy this version of https://raw.githubusercontent.com/microsoft/STL/b23ecba48f625d9f6065b3735c15c6b55c3cdf82/stl/debugger/STL.natvis to your project and Natvis will use this copy STL.natvis instead of a prebuilt Visual Studio version and I hope it will work for you.

**Comment by CaseyCarter** [comment]
As @fsb4000 says, we haven't supported XP for quite a while now. I suggest you find an older `STL.natvis` - maybe the one from VS2019 - and incorporate it into your project, ideally with a different name.
