### ISSUE TITLE
`<xstring>`: Fix `basic_string::operator=(const&)` thoroughly

### ISSUE THREAD

**Issue by achabense** [microsoft/STL#3997]
`basic_string::operator=(const&)` is still problematic even after #3862. For example:
https://github.com/microsoft/STL/blob/60f18856c56389001c38a9929ef37bd5c01c4e47/stl/inc/xstring#L3170-L3175
1. After `_Tidy_deallocate` the string is left in SSO mode, so the pointer should be constructed instead of assigned.
2. The new allocation lacks ASAN annotation.

These are what I can find. As the branch is in such a broken state, I'm uncertain whether there are other problems.

**Comment by achabense** [comment]
Also I find the codeblock become very loose after changing some texts; can I control the line height here?
<img width="379" alt="image" src="https://github.com/microsoft/STL/assets/60953653/06f4e747-98bd-42cf-a349-3e4dfcb0a09c">

**Comment by frederick-vs-ja** [comment]
> 1\. After `_Tidy_deallocate` the string is left in SSO mode, so the pointer should be constructed instead of assigned.

Yes. It seems that there should be test coverage for non-trivial (but constexpr-friendly) fancy pointers.
(I roughly remember that I've invented more that one kind of fancy pointers for testing.)

**Comment by achabense** [comment]
> there should be test coverage for non-trivial (but constexpr-friendly) fancy pointers.

Fancyptr is implemented in [VSO_0000000_fancy_pointers](https://github.com/microsoft/STL/blob/d8ed02d2ec7ba8216848a33dec2b5fb385febf4e/tests/std/tests/VSO_0000000_fancy_pointers/test.compile.pass.cpp) (which does not test special allocators).
`operator=` with special allocators is tested in [VSO_0000000_allocator_propagation](https://github.com/microsoft/STL/blob/d8ed02d2ec7ba8216848a33dec2b5fb385febf4e/tests/std/tests/VSO_0000000_allocator_propagation/test.cpp) (which does not test ptrs).
