### ISSUE TITLE
vectorize `lexicographical_compare`, `lexicographical_compare_three_way`

### ISSUE THREAD

**Issue by AlexGuteniev** [microsoft/STL#3998]
Some parts are similar to what we have
 * There's already `memcmp` optimization, so the predicate classification can be reused
 * The elements classification can be reused from `min`/`max_element` optimization
 * The wrappers for intrinsics can also be reused from `min`/`max_element` optimization

Scope
 * 1 byte integers (for strings, IP addresses, binary data, etc., try to beat `memcmp`)
 * 2 byte integers (for wide strings)
 * 4 or 8 byte integers (for arrays of integers)
 * ~~4 or 8 byte floats (for arrays of floats, after #3928)~~
 * ~~Can support infinite ranges removed in #3989 again~~

**Comment by CaseyCarter** [comment]
> * Can support infinite ranges removed in [Don't `memcmp(x, y, -1)` from `ranges::lexicographical_compare` #3989](https://github.com/microsoft/STL/pull/3989) again

`ranges::lexicographical_compare` still supports comparing two infinite ranges, the change is that it won't try to pass them to `memcmp`.

**Comment by AlexGuteniev** [comment]
> `ranges::lexicographical_compare` still supports comparing two infinite ranges

Yes, I meant support by optimization, not general support.

**Comment by AlexGuteniev** [comment]
I struck floats, as on more thought it doesn't seem to make much sense to do lexicographical comparison of array of floats.
I also struck infinite ranges, guess we're not doing that anymore.
