### ISSUE TITLE
P0122R7 <span>

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#4]
[P0122R7](https://wg21.link/P0122R7) `<span>`
[P1024R3](https://wg21.link/P1024R3) Enhancing `span` Usability
[P1085R2](https://wg21.link/P1085R2) Removing `span` Comparisons
[P1394R4](https://wg21.link/P1394R4) Range Constructor For `span`
[P1872R0](https://wg21.link/P1872R0) `span` Should Have `size_type`, Not `index_type`

LWG-3101 `span`'s `Container` constructors need another constraint
LWG-3102 Clarify `span` `iterator` and `const_iterator` behavior
LWG-3103 Errors in taking subview of `span` should be ill-formed where possible
LWG-3144 `span` does not have a `const_pointer` typedef
LWG-3198 Bad constraint on `std::span::span()`
LWG-3274 Missing feature test macro for `<span>`
LWG-3369 `span`'s deduction-guide for built-in arrays doesn't work

This is also patched by #56, [P1227R2](https://wg21.link/P1227R2) Signed `std::ssize()`, Unsigned `span::size()`.

Feature-test macro as of WG21-N4842:
`#define __cpp_lib_span 201902L`

**Comment by gongminmin** [comment]
Can make use of the implementation of GSL::span :)

**Comment by AdamBucior** [comment]
I suppose that all of these proposals were implemented, so maybe they all should be listed in [Changelog](https://github.com/microsoft/STL/wiki/Changelog), not just P0122R7 (also applies to #26 and #13).

**Comment by StephanTLavavej** [comment]
@AdamBucior Good idea! I've recorded all patch papers in the Changelog, and updated the PR checklist so we'll follow this convention in the future.
