### ISSUE TITLE
self-implement constexpr allocator

### ISSUE THREAD

**Issue by havedifficultyinfindingnames** [microsoft/STL#4002]
I'm working on making my own allocator. It has different api from ```std::allocator``` so that I cannot inherit from it or meet any ```std::``` allocator requirements. All things are going well under gcc and clang for the ```constexpr```ness of allocate and deallocate functions, except in msvc. And I'm surprised to find that msvc using ```__declspec(allocator)``` to "dig a hole through the compiler" according to somewhat "GH-1532". However, as I try to make my allocate function ```__declspec(allocator)```, the compiler keeps complaining that it's not constexpr. 
So there're mainly two questions troubling me: 1. What is "GH-1532" and where can I find papers about it? 2. How can my allocator ```constexpr```? I would appreciate it very much if someone can offer any help.

**Comment by CaseyCarter** [comment]
[`__declspec(allocator)` ](https://learn.microsoft.com/en-us/cpp/cpp/allocator?view=msvc-170) has nothing to do with `constexpr` allocation or even C++ allocators, it simply tells the Visual Studio memory profiler to track calls to the annotated function.

"GH-1532" is simply how we refer to the issue or pull request `microsoft/STL#1532`. (Note how GH-1532 automagically links to that issue.) It looks like that issue has some early discussion of how we were going to implement constexpr allocation in a manner friendly to both MSVC and clang.

You can portably make your allocator `constexpr` by doing only things that [[expr.const]](https://eel.is/c++draft/expr.const) says are allowed in constant expressions. It's very hard to stay within those restrictions and actually allocate memory; you may need to "give up" and fallback on `std::allocator` in constant expressions. [Here's an example allocator that uses `malloc`/`free` at runtime but uses `std::allocator` at compiletime.](https://godbolt.org/z/Y79MPdcTr)

**Comment by havedifficultyinfindingnames** [comment]
> [`__declspec(allocator)` ](https://learn.microsoft.com/en-us/cpp/cpp/allocator?view=msvc-170) has nothing to do with `constexpr` allocation or even C++ allocators, it simply tells the Visual Studio memory profiler to track calls to the annotated function.
> 
> "[GH-1532](https://github.com/microsoft/STL/issues/1532)" is simply how we refer to the issue or pull request `microsoft/STL#1532`. (Note how [GH-1532](https://github.com/microsoft/STL/issues/1532) automagically links to that issue.) It looks like that issue has some early discussion of how we were going to implement constexpr allocation in a manner friendly to both MSVC and clang.
> 
> You can portably make your allocator `constexpr` by doing only things that [[expr.const]](https://eel.is/c++draft/expr.const) says are allowed in constant expressions. It's very hard to stay within those restrictions and actually allocate memory; you may need to "give up" and fallback on `std::allocator` in constant expressions. [Here's an example allocator that uses `malloc`/`free` at runtime but uses `std::allocator` at compiletime.](https://godbolt.org/z/Y79MPdcTr)

Thank you! That helps a lot. But I'm still curious about the magic how stl calls ```::operator new``` in constexpr function. 
This is ```std::allocator<T>::allocate```
```cpp
_NODISCARD_RAW_PTR_ALLOC _CONSTEXPR20 __declspec(allocator) _Ty* allocate(_CRT_GUARDOVERFLOW const size_t _Count) {
    static_assert(sizeof(value_type) > 0, "value_type must be complete before calling allocate.");
    return static_cast<_Ty*>(_Allocate<_New_alignof<_Ty>>(_Get_size_of_n<sizeof(_Ty)>(_Count)));
}
```
within which all function called are ```constexpr```. That's fine. 
This is ```std::_Allocate```
```cpp
template <size_t _Align, class _Traits = _Default_allocate_traits,
    enable_if_t<(!_HAS_ALIGNED_NEW || _Align <= __STDCPP_DEFAULT_NEW_ALIGNMENT__), int> = 0>
__declspec(allocator) _CONSTEXPR20 void* _Allocate(const size_t _Bytes) {
    // allocate _Bytes when !_HAS_ALIGNED_NEW || _Align <= __STDCPP_DEFAULT_NEW_ALIGNMENT__
#if defined(_M_IX86) || defined(_M_X64)
#if _HAS_CXX20 // TRANSITION, GH-1532
    if (!_STD is_constant_evaluated())
#endif // _HAS_CXX20
    {
        if (_Bytes >= _Big_allocation_threshold) { // boost the alignment of big allocations to help autovectorization
            return _Allocate_manually_vector_aligned<_Traits>(_Bytes);
        }
    }
#endif // defined(_M_IX86) || defined(_M_X64)

    if (_Bytes != 0) {
        return _Traits::_Allocate(_Bytes);
    }

    return nullptr;
}
```
In the ```constexpr``` path it calls std::_Default_allocate_traits::_Allocate, which is not noted as ```constexpr```. 

If I copy the code to my file without changing anything, which looks like
```cpp
#include <memory>

template <typename T>
constexpr __declspec(allocator) T* allocate(const size_t _Count) {
	return static_cast<T*>(std::_Allocate<std::_New_alignof<T>>(std::_Get_size_of_n<sizeof(T)>(_Count)));
}

consteval auto func() {
	auto p1 = std::allocator<int>{}.allocate(1);
	auto p2 = allocate<int>(1);
	delete p1;
	delete p2;
	return 0;
}
```
and I got compiler errors. I know according to the standard it's not a well-defined behavior to calls into the unexposed identities in ```std::```, but in this case it sounds weird.

**Comment by CaseyCarter** [comment]
> Thank you! That helps a lot. But I'm still curious about the magic how stl calls `::operator new` in constexpr function. This is `std::allocator<T>::allocate`
> 
> ```c++
> _NODISCARD_RAW_PTR_ALLOC _CONSTEXPR20 __declspec(allocator) _Ty* allocate(_CRT_GUARDOVERFLOW const size_t _Count) {
>     static_assert(sizeof(value_type) > 0, "value_type must be complete before calling allocate.");
>     return static_cast<_Ty*>(_Allocate<_New_alignof<_Ty>>(_Get_size_of_n<sizeof(_Ty)>(_Count)));
> }
> ```
> within which all function called are `constexpr`. That's fine. This is `std::_Allocate`
>  
> ```c++
> template <size_t _Align, class _Traits = _Default_allocate_traits,
>     enable_if_t<(!_HAS_ALIGNED_NEW || _Align <= __STDCPP_DEFAULT_NEW_ALIGNMENT__), int> = 0>
> __declspec(allocator) _CONSTEXPR20 void* _Allocate(const size_t _Bytes) {
>     // allocate _Bytes when !_HAS_ALIGNED_NEW || _Align <= __STDCPP_DEFAULT_NEW_ALIGNMENT__
> #if defined(_M_IX86) || defined(_M_X64)
> #if _HAS_CXX20 // TRANSITION, GH-1532
>     if (!_STD is_constant_evaluated())
> #endif // _HAS_CXX20
>     {
>         if (_Bytes >= _Big_allocation_threshold) { // boost the alignment of big allocations to help autovectorization
>             return _Allocate_manually_vector_aligned<_Traits>(_Bytes);
>         }
>     }
> #endif // defined(_M_IX86) || defined(_M_X64)
> 
>     if (_Bytes != 0) {
>         return _Traits::_Allocate(_Bytes);
>     }
> 
>     return nullptr;
> }
> ```
> 
> In the `constexpr` path it calls std::_Default_allocate_traits::_Allocate, which is not noted as `constexpr`.

There are differences in how MSVC and Clang support constexpr allocation. Since we support both, things can get confusing. MSVC doesn't even look at the body of `std::allocator::allocate` when it's evaluated as part of a constant expression, it just replaces a call to `std::allocator<T>::allocate(n)` with storage for an array of `n` objects of type `T`. MSVC never sees `std::_Allocate` or `std::_Default_allocate_traits::_Allocate` at compiletime.

Clang uses a different magic which replaces calls to `::operator new(n * sizeof(T))` that appear within the evaluation of `std::allocator<T>::allocate(n)` with storage for an array of `n` objects of type `T`. Clang _does_ see the bodies of `std::allocator::allocate`, `std::_Allocate`, and `std::_Default_allocate_traits::_Allocate` at compiletime. This is at least hinted at by the conditional `constexpr` in `std::_Default_allocate_traits` that's `#ifdef __clang__`.

> If I copy the code to my file without changing anything, which looks like
> 
> ```c++
> #include <memory>
> 
> template <typename T>
> constexpr __declspec(allocator) T* allocate(const size_t _Count) {
> 	return static_cast<T*>(std::_Allocate<std::_New_alignof<T>>(std::_Get_size_of_n<sizeof(T)>(_Count)));
> }
> 
> consteval auto func() {
> 	auto p1 = std::allocator<int>{}.allocate(1);
> 	auto p2 = allocate<int>(1);

This call to `allocate<int>` isn't a constant expression because of the call to non-`constexpr` `std::_Default_allocate_traits::_Allocate` inside `std::_Allocate`. The near-identical call inside `std::allocator<int>::allocate` is also not a constant expression, but it doesn't matter because `std::allocator<int>{}.allocate(1)` is magically replaced at compiletime and doesn't evaluate the function body. The mechanism is slightly different for Clang, but the effect is the same as with MSVC: `std::allocator::allocate` is magically a constant expression virtually by fiat because the Standard says so.

Disclaimer: I'm working from memory of how bleeding-edge stuff worked a year or two ago, I wouldn't stake my life on the precise details.

**Comment by havedifficultyinfindingnames** [comment]
Thanks! That's clear enough to understand how the code works.
