### ISSUE TITLE
`<xnode_handle.h>`: Can we remove type punning from `_Node_handle_map_base`?

### ISSUE THREAD

**Issue by frederick-vs-ja** [microsoft/STL#4007]
The current implementation of node handle sometimes relies on type punning, which is currently UB and hard to made well-defined:
https://github.com/microsoft/STL/blob/6c69a73911b33892919ec628c0ea5bbf0caf8a6a/stl/inc/xnode_handle.h#L31-L52

It seems OK to remove type punning and just use `const_cast` to remove the `const`-qualifier on `key_type`, which reduces UB in node handles themselves. The modifications on keys may even be made well-defined by CWG-2514 in the future.

**Comment by StephanTLavavej** [comment]
We talked about this at the weekly maintainer meeting and we concur with Casey's assessment - no motivation for a change at this time. Thanks again for bringing this to our attention.
