### ISSUE TITLE
`<yvals_core.h>`: `_EMIT_STL_ERROR` leads to uninformative error logs

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#4009]
#2897 introduced:

https://github.com/microsoft/STL/blob/6c69a73911b33892919ec628c0ea5bbf0caf8a6a/stl/inc/yvals_core.h#L512-L514

This emits a `#pragma message` which is captured in full build logs but *not* error-only logs, followed by a `static_assert` which does appear in error-only logs but with a message that doesn't say what's actually wrong.

This has the potential to confuse users who are looking at error-only logs; e.g. in https://github.com/twistedfall/opencv-rust/issues/452 the problem was *very* simple (Clang version was too old), but the `static_assert` lost the reason.

For `_EMIT_STL_ERROR`, I think we should use `static_assert` alone (with the given `NUMBER` and `MESSAGE`); I don't see any reason to use `#pragma message` here.

**Comment by frederick-vs-ja** [comment]
https://github.com/microsoft/STL/blob/6c69a73911b33892919ec628c0ea5bbf0caf8a6a/stl/inc/yvals_core.h#L509-L511

Maybe related: can/should we remove the seemingly useless `static_assert` from `_EMIT_STL_WARNING`?

**Comment by frederick-vs-ja** [comment]
I found that `#pragma message` has its own benefit:
- it doesn't emit unhelpful error codes (C1189 for `#error` or C2338 for `static_assert`);
- it can cause Visual Studio to generate a link in Error List - however, the generated links are currently invalid.

But it can't be used for rejecting an invalid program.

Error diagnostics have some drawbacks:
- currently, `static_assert` doesn't prevent MSVC emitting following error messages;
- `#error` prevents MSVC emitting following error messages, but stringization doesn't take place within it; and
- both of them emit unhelpful error codes.

Ideally, there should be something behaving like `#pragma message` except that it terminates compilation after emitting the error message.
