### ISSUE TITLE
STL: _NODISCARD _XXX_DEPRECATE_XXX vs. _XXX_DEPRECATE_XXX _NODISCARD

### ISSUE THREAD

**Issue by CaseyCarter** [microsoft/STL#403]
We're inconsistent about the order of appearance of `_NODISCARD` and deprecation macros in declarations. Grepping for `_NODISCARD.*DEPRECATE` finds eight results, whereas `DEPRECATE.*_NODISCARD` finds six (and #402 wants to add four more). Let's choose an ordering and make all such declarations consistent.

**Comment by Neargye** [comment]
It seems to me that the attribute should be the leftmost. `*DEPRECATE ... foo()`
If it is deprecated, then there is no sense to look to the right.
If it’s not deprecated, then look at which attributes to the right. `*DEPRECATE _NODISCARD conxtexpr foo()`

**Comment by AdamBucior** [comment]
I also think that deprecation macros should be first. They seem more important.

**Comment by StephanTLavavej** [comment]
Another vote for deprecation macros going first.

**Comment by SuperWig** [comment]
Being the person who wants to add 4 more I guess I've already voted?

Assuming it's decided to go with depreation first and seeing as it's a relatively small change (8 uses) I have already committed the changes and can push that to #402 if wanted?

**Comment by StephanTLavavej** [comment]
For a small, low-risk, stylistic cleanup, I'm fine with bundling it together with related changes. A separate PR would lead to somewhat nicer history, so that would also be fine.

**Comment by BillyONeal** [comment]
Fixed by #402
