### ISSUE TITLE
why std::locale has class-specific allocation functions with _DEBUG macro

### ISSUE THREAD

**Issue by WhiteSmoogy** [microsoft/STL#4046]
In xlocale header
```
extern "C++" struct _CRTIMP2_PURE_IMPORT _Crt_new_delete  
{ // base class for marking allocations as CRT blocks  
#ifdef _DEBUG  
// class-specific allocation functions  
#endif  
}  
 class locale : public _Locbase<int>, public _Crt_new_delete{  
}  
```
The _DEBUG macro is defined in the A.cpp file, but it is not defined in b.cpp  file, 
The link don't give any warning and error。
When we upgrade from VC140 to VC143 ,This problem occurs in a game engine that charges for installs。
Is it possible to disable links by adding compiler attributes？

**Comment by SuperSodaSea** [comment]
https://github.com/microsoft/STL/blob/385f1335956684135d0766d70a4a5cb7153c09af/stl/inc/xlocale#L58-L89

Maybe we need some `#pragma detect_mismatch` here?

**Comment by frederick-vs-ja** [comment]
`#pragma detect_mismatch` is already used for `_DEBUG` here. I don't know why it didn't work.
https://github.com/microsoft/STL/blob/385f1335956684135d0766d70a4a5cb7153c09af/stl/inc/yvals.h#L148-L158

**Comment by StephanTLavavej** [comment]
Mixing release and debug is indeed super forbidden.

If a `.cpp` file is defining or undefining `_DEBUG` in its source lines, that is an even more unwise idea, as it may have already included STL headers. `_DEBUG` should never be altered in source files, and it should never be mentioned on command lines in opposition to what `/MD /MDd /MT /MTd` imply. (IDE-crafted command lines sometimes *redundantly* mention `_DEBUG` so IntelliSense can see what the definition is, which is fine although it encourages users to do different bad things.)

`_Crt_new_delete` exists so that in debug mode, when CRT leak-tracking machinery exists, `std::locale`'s long-lived allocations aren't detected as leaks.

**Comment by WhiteSmoogy** [comment]
> Mixing release and debug is indeed super forbidden.
> 
> If a `.cpp` file is defining or undefining `_DEBUG` in its source lines, that is an even more unwise idea, as it may have already included STL headers. `_DEBUG` should never be altered in source files, and it should never be mentioned on command lines in opposition to what `/MD /MDd /MT /MTd` imply. (IDE-crafted command lines sometimes _redundantly_ mention `_DEBUG` so IntelliSense can see what the definition is, which is fine although it encourages users to do different bad things.)
> 
> `_Crt_new_delete` exists so that in debug mode, when CRT leak-tracking machinery exists, `std::locale`'s long-lived allocations aren't detected as leaks.
I'll investigate why the linker doesn't output LNK2038 during our code build in next monday,This should be our problem.

**Comment by WhiteSmoogy** [comment]
Our code looks like this
```
#include "Prefix.h" //import yval.h 
#define _DEBUG 1
#include <xxx.h> //import  10.0.22621.0\\ucrt\\crtdbg.h"
#include <stringstream>
```
After preprocessing, the code is as follows
···
#line 10037
#pragma detect_mismatch("RuntimeLibrary", "MT_StaticRelease")
//replace _malloc_dbg with malloc 
extern "C++" struct  _Crt_new_delete { 

    void* __cdecl operator new(size_t _Size) { 
        void* _Ptr = operator new(_Size, nothrow);
        if (!_Ptr) {
            _Xbad_alloc();
        }

        return _Ptr;
    }

    void* __cdecl operator new(size_t _Size, const nothrow_t&) noexcept { 
        return malloc(_Size > 0 ? _Size : 1);
    }
···
Although this code is very stupid,
#pragma detect_mismatch don‘t work this becaus of preprocessing.
so whether to consider dealing with this stupid code by compiler or library?
