### ISSUE TITLE
Compile error involving zip_view and iter_move

### ISSUE THREAD

**Issue by duanqn** [microsoft/STL#4056]
Esteemed maintainers and C++ experts,
I'm implementing `flat_map` in #3896 and I encountered a compile error specifically in the test configuration `/MTd /D_ITERATOR_DEBUG_LEVEL=2 /permissive`. All other configurations have the flag `/permissive-` and the tests are passing. The compiler error message was posted [here](https://github.com/microsoft/STL/pull/3896#issuecomment-1736978291). I don't have much experience working with `ranges` and I couldn't figure out the reason behind this error, but it looks like a bug with `zip_view` rather than my `flat_map` implementation.

Many thanks to @achabense who composed a minimal repro source code:
```
#include <ranges>
#include <vector>
using namespace std;

void test() {
    vector<int> a(10, 1);
    vector<double> b(10, 2.0);
    auto zipv = views::zip(a, b);

    *zipv.begin() = _RANGES iter_move(zipv.begin());
}

int main() {
    test();
}
```

I'd love some help with this, thanks!

**Comment by duanqn** [comment]
Got it. Thanks for the answer!
I will try to remove the usage of `zip_view` as an improvement after I finish the core functionalities.

**Comment by CaseyCarter** [comment]
Hidden friends aren't hidden in permissive mode; any use of what should be a hidden friend `iter_swap` or `iter_move` in `std::ranges` will cause compile errors. This is well-known and unavoidable.

If you can easily avoid using `zip_view` then by all means do, but don't go out of your way to do so.
