### ISSUE TITLE
`<deque>`: `shrink_to_fit()` should follow the Standard

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#4072]
WG21-N4958 \[deque.capacity\]/6:

> *Effects:* `shrink_to_fit` is a non-binding request to reduce memory use but does not change the size of the sequence.
> \[*Note 1:* The request is non-binding to allow latitude for implementation-specific optimizations. - *end note*\]
> If the size is equal to the old capacity, or if an exception is thrown other than by the move constructor of a non-*Cpp17CopyInsertable* `T`, then there are no effects."

We unconditionally move, which is a bug:

https://github.com/microsoft/STL/blob/283cf32878948f41b5b68fe60860e0c4dca85ce1/stl/inc/deque#L998

(#4071 is patching this line in an unrelated way.)

`vector` provides its strong guarantees correctly, like this (note that it doesn't directly use `move_if_noexcept()`):

https://github.com/microsoft/STL/blob/283cf32878948f41b5b68fe60860e0c4dca85ce1/stl/inc/vector#L837-L842

**Comment by frederick-vs-ja** [comment]
Reallocation of elements doesn't seem valuable since the current block size of `deque` is unwisely small. I think we should just deallocate unused blocks and shrink the internal map.
