### ISSUE TITLE
`<mdspan>`: `std::layout_meow::mapping::operator()` is missing `std::move`

### ISSUE THREAD

**Issue by hewillk** [microsoft/STL#4081]
It seems that we need to convert `_Indices` into rvalues before casting

https://github.com/microsoft/STL/blob/f362f7d7bea87bd199c927a89718e929ed89b187/stl/inc/mdspan#L563-L568

testcase:

```cpp
#include <mdspan>

struct Index {
  operator size_t() && noexcept { return 0; }
};

int main() {
  std::layout_left::mapping<std::extents<std::size_t, 1>> map;
  return map(Index{});
}
```

**Comment by hewillk** [comment]
oops, forgive me. This is standards compliant, this should be LWG.

**Comment by CaseyCarter** [comment]
the function's _Preconditions_ already invoked `i`'s _rvalue_ conversion operator, I'm not sure if `static_cast<index_type>(i)` in the function body is still valid...

Good catch! This is a defect. The wording should either require lvalues to convert or require implementations to convert rvalues.

**Comment by hewillk** [comment]
This is LWG [3995](https://cplusplus.github.io/LWG/lwg-active.html#3995).

**Comment by frederick-vs-ja** [comment]
> For the above case, the function's _Preconditions_ already invoked `i`'s _rvalue_ conversion operator, I'm not sure if `static_cast<index_type>(i)` in the function body is still valid...

I don't think any expression is required to be evaluated in _Preconditions_.

However, in these `operator()`'s, I think it's permitted to actually evaluate the expressions in _Preconditions_ and as a part of calculation of the return value, with preconditions checked. Each parameter in `_Indices...` of a class type can and should be forwarded at most once.

Oh, it seems that the standard wording should say _`index-cast`_`(i)...` which expands parameter packs.

**Comment by CaseyCarter** [comment]
> > For the above case, the function's _Preconditions_ already invoked `i`'s _rvalue_ conversion operator, I'm not sure if `static_cast<index_type>(i)` in the function body is still valid...
> 
> I don't think any expression is required to be evaluated in _Preconditions_.

The issue here isn't one of timing - it's not unusual for library functions to have preconditions that can't be evaluated without invalidating the arguments - it's that `static_cast<index_type>(i)` performs an explicit conversion of an lvalue `_IndexTypes` to `index_type` when the constraints only require implicit conversion from rvalue `_IndexTypes` to `index_type` to be valid.

> This is LWG-3995.

We've handed this off to LWG, there's no need to continue tracking it here. Thanks, @hewillk!
