### ISSUE TITLE
<yvals_core.h>: Update _MSVC_STL_UPDATE to January 2020

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#409]
Explanation on our wiki: [Macro `_MSVC_STL_UPDATE`](https://github.com/microsoft/STL/wiki/Macro-_MSVC_STL_UPDATE)

Code:
https://github.com/microsoft/STL/blob/264b0d4a167daa9e5499af6d783c9ff22f7af03f/stl/inc/yvals_core.h#L430

Previous update: #344

This issue is intended for a new contributor (especially one new to GitHub) to get started with the simplest possible change.

**Comment by miscco** [comment]
On that occasion a Happy New Year to you all 🎉
