### ISSUE TITLE
Add `const`-qualifier for `_Ref_fn::operator()`?

### ISSUE THREAD

**Issue by hewillk** [microsoft/STL#4101]
`_Pass_fn()` is heavily used in `<algorithm>`, which returns a simple aggregate call wrapper `_Ref_fn`:
https://github.com/microsoft/STL/blob/1c59a205787f4fdcd9c20decc8fa6dfa9096d394/stl/inc/xutility#L541-L556
I'm curious why `operator()` here is not `const`-qualified, given my impression that MSVC-STL uses `const`-qualifiers as much as possible.
 
I believe that that the `operator()` of library callable should be as `const`-qualified as possible because the interaction of `mutable `lambdas with `<algorithm>` is definitely not recommended by the standard:

```
#include <ranges>

int main() {
  int x[] = {0, 1, 2, 3};
  auto pred = [unused = std::span<int>{}](int x) { return true; };
  auto drop1 = std::ranges::drop_while_view(x, pred);
  auto drop2 = std::ranges::drop_while_view(x, std::_Pass_fn(pred)); // error
}
```
So, is the seemingly missing `const`-qualifier here just an oversight or are there other considerations?

**Comment by StephanTLavavej** [comment]
We talked about this at the weekly maintainer meeting. @strega-nil-ms says there's no benefit to making this function operator `const`, but she is completely neutral on this issue. @StephanTLavavej argues that there's an advantage to keeping this non-`const`, as it will avoid `const _Pred` parameters from being introduced during maintenance or feature work (such parameters would work with `_Pass_fn` if its `operator()` were `const`-qualified, but they would forbid user-defined function objects that are lacking `const`-qualified function call operators - such things are risky/squirrelly :chipmunk: but permitted by the Standard). @CaseyCarter was not persuaded by Stephan's argument, saying that it doesn't represent a case that's likely to occur, and thinks we should qualify `_Pass_fn`'s function call operator as `const`, but also thinks that this is not an important issue. On second thought, @StephanTLavavej wouldn't argue for removing `const` if it were already there, so he (I) would be fine either way.

We do seem to be united in the feeling that we wouldn't make a PR ourselves to add `const` here, but we wouldn't reject a submitted one either.
