### ISSUE TITLE
`flat_set`'s transparent insertion requirements are deficient

### ISSUE THREAD

**Issue by achabense** [microsoft/STL#4105]
The precondition of `flat_set`'s transparent insertion is specified as follows:
>https://eel.is/c++draft/flat.set#modifiers-2
>Preconditions: The conversion from x into value_type constructs an object u, for which find(x) == find(u) is true.

... which is highly problematic. #4084 tried to add the following test. As `fs.find(2) == fs.end()`, and `fs.find(2-10) == fs.end()`, this is currently allowed by the standard.
```cpp
void test_insert_transparent_partially_inconsistent() {
    struct broken_key {
        int key;
        explicit operator int() const {
            return key - 10;
        }
    };

    flat_set<int, key_comparer/*comparator able to extract ".key" if present*/> fs{ 0, 3, 5 };

    // fs.find(2) == fs.end(), and fs.find(2-10) == fs.end(), so this is currently allowed by the standard:
    fs.insert(broken_key{ 2 });
    // ... (assert fs has "{-8, 0, 3, 5}")
    // ...
}
```
The problem is that the precondition cannot ensure the `lower_bound(transparent-key)` be the same as `lower_bound(convert-result)`. If we must adhere to the current specification, after deciding that the `transparent-key` is not contained (by finding its `lower_bound` and doing the comparision), we still need to verify that the bound is also the real `lower_bound` for the `convert-result`; and if not, we need to fall back to another (non-transparent) insert function.

The condition above is unlikely useful but is generally undetectable, and the solution will have considerable performance impact. As [commented](https://github.com/microsoft/STL/pull/4084#discussion_r1364691294) in #4084, the real solution might be making the precondition more restrictive in the standard.

The current implementation will work fine if the precondition is specified as:
>The conversion from x into value_type constructs an object u, for which "contains(x) == contains(u) && lower_bound(x) == lower_bound(u)" is true.

**Comment by CaseyCarter** [comment]
I don't understand the issue, possibly because the example is incomplete. What's `key_comparer`? What requirement are we unable to implement?

**Comment by achabense** [comment]
>What's key_comparer?

```
struct key_comparer {
    const auto& extract_key(const auto& obj) const {
        if constexpr (requires { obj.key; }) {
            return obj.key;
        } else {
            return obj;
        }
    }

    bool operator()(const auto& lhs, const auto& rhs) const {
        return extract_key(lhs) < extract_key(rhs);
    }

    using is_transparent = int;
};
```

To support `fs.insert(broken_key{ 2 });`, the flat_set should firstly find `lower_bound(broken_key{2})`, which is after `0` and before `3`. Then `flat_set` decides it is not contained, so convert it to `int(-8)` and try to do the insertion. However, that `lower_bound` is unusable as insert position.

**Comment by CaseyCarter** [comment]
> The current impl is assuming lower_bound should be insertable here.

This seems like a bug in the implementation.

> Otherwise, `flat_set` have to make another common `insert(int(-8))` call.

Is that not conforming? `insert` must have linear complexity, we "have time" to perform two logarithmic searches. Ideally we'd perform another binary search for `-8` starting at the position we found looking for `broken_key{2}` - with the expectation that it will often be close to the correct insertion position - but even that is an optimization, not a requirement.

**Comment by achabense** [comment]
This issue is motivated by https://github.com/microsoft/STL/pull/4084#discussion_r1364691294. #4084 tried to make the insertion "conformant". However, I strongly believe the current specification is a defect in the standard. We'd be better off just requiring that `transparent comparision` and `conversion` must represent the same thing.

These "partially inconsistent" types, which represent different things when doing `transparent comparision` and when `converting to key_type`, are logically broken, and I believe are always design defects and never work as intended.
Take the sample code for example, the expression is initially valid by the current standard. However, the same expression becomes invalid *immediately after that call*.
```
flat_set<int, key_comparer/*comparator able to extract ".key" if present*/> fs{ 0, 3, 5 };

    // [searching: fs.find(2) == fs.end()], and [converted: fs.find(2-10) == fs.end()], so this is currently allowed by the standard:
    fs.insert(broken_key{ 2 }); // ... (assert fs has "{-8, 0, 3, 5}")
    // now precondition violation: [searching: fs.find(2) == fs.end()], but [converted: fs.find(2-10) != fs.end()]
    // fs.insert(broken_key{ 2 });
```
Actually, unless doing the real conversion to `key_type`, there is even no ways to decide whether such an insertion will trigger precondition violation. That is:
```
    fs.insert(transparent_key{ arbitary-value }); // cannot tell whether this will trigger precondition violation...
    // unless...
    ~ firstly get "find(transparent_key)".
    ~ then convert transparent_key to key_type, and get "find(converted)".
    ~ if(find(transparent_key) == find(converted))... <--!!!
    ~ then it's really safe to do fs.insert(transparent_key) ... however, as conversion
       already happened, the transparent insertion has become pointless here
```

About the `<--!!!` part, as `transparent searching` is not guaranteedly equivalent to `key_type searching`, *even if we have confirmed `!contains(transparent_key)`, we still cannot decide whether `contains(converted)`*. Unless such "partially inconsistent" types are inherently prohibited by the standard, there is actually no way to decide whether the precondition violation will happen without doing the real conversion, which I believe makes transparent insertion senseless (and for user-provided types,  we cannot detect whether this will happen).

The reason that the standard cannot disallow types like this is that `find(transparent-key) == find(converted)` can be *dependent on contents in `flat_set`*, as the two `find` can both be `end()` so that there can be no relation about the two searching, so cannot enforce that `the `transparent comparision` and `conversion` represent the same thing`.

As to the current implementation's requirement (`contains(x) == contains(u) && lower_bound(x) == lower_bound(u)`), it will work fine as long as `transparent comparision` and `conversion` represent the same thing.

**Comment by StephanTLavavej** [comment]
We talked about this at the weekly maintainer meeting, although we didn't have time to track down all of the Standardese. (The main question in our minds is whether this affects the existing ordered/unordered associative containers too.)

We strongly believe that the Standard's requirements for transparent insertion should say that the freshly constructed element should sort into the same position as the transparent comparison indicates, otherwise the Standard is asking for an additional comparison after the element has been constructed (which largely defeats the purpose of the transparent machinery), to avoid violating container invariants.

**Comment by timsong-cpp** [comment]
This wording was copied from an older revision of WG21-P2363. LWG review of that paper led to wording changes (see WG21-P2363R5) but we'll need an issue to apply the same changes to all the flat_meows]

**Comment by frederick-vs-ja** [comment]
LWG-4048 is filed.
