### ISSUE TITLE
Support for __int128 (clang/gcc)

### ISSUE THREAD

**Issue by Colengc** [microsoft/STL#411]
Using VS with clang integration (w/MS STL), the following fails for x64.

```
#include <type_traits>
typedef std::make_unsigned_t<__int128> type;
```

Clang and gcc provide signed/unsigned __int128.  Supporting them would seem to be a matter of updating the following to check for associated compiler define(s).  (Maybe `__SIZEOF_INT128__`).

https://github.com/microsoft/STL/blob/92508bed6387cbdae433fc86279bc446af6f1b1a/stl/inc/xtr1common#L180-L185

… as well as numeric_limits<> specializations.
Perhaps atomics, using cmpxchg16b.

**Comment by BillyONeal** [comment]
Even on clang/gcc, `__int128` is not an integer type (because that would force them to change `intmax_t`), and `make_unsigned_t` has a precondition that the input is an integer type.

**Comment by StephanTLavavej** [comment]
Standardese citations:
* WG21-N4842 6.8.1 [basic.fundamental] specifies the integral types.
* 20.15.7.3 [meta.trans.sign] specifies the preconditions for `make_signed` and `make_unsigned`: "*Requires:* `T` shall be a (possibly cv-qualified) integral type or enumeration but not a `bool` type."

While we support Clang as a first-class citizen, we draw a distinction between supporting Standard features and non-Standard extensions, as mentioned in our [Non-Goals](https://github.com/microsoft/STL#non-goals). Adding a non-Standard extension to `make_unsigned` recognizing `__int128` is therefore out of scope for our project - and as you observed, it raises additional support questions (why not `numeric_limits`, `atomic`, `from_chars()`, `to_chars()`, iostreams, etc.).
