### ISSUE TITLE
<std::filesystem>: Broken string conversion (almost in c++ std 20)

### ISSUE THREAD

**Issue by boludoz** [microsoft/STL#4110]
```
#include <filesystem>
#include <iostream>
#include <string>
#include <windows.h>
#include <fstream>
#include <codecvt>

typedef unsigned int u32;

static std::wstring CPToUTF16(u32 code_page, std::string_view input) {
    const auto size =
        MultiByteToWideChar(code_page, 0, input.data(), static_cast<int>(input.size()), nullptr, 0);

    if (size == 0) {
        return {};
    }

    std::wstring output(size, L'\0');

    if (size != MultiByteToWideChar(code_page, 0, input.data(), static_cast<int>(input.size()),
                                    &output[0], static_cast<int>(output.size()))) {
        output.clear();
    }

    return output;
}

std::string UTF16ToUTF8(std::wstring_view input) {
    const auto size = WideCharToMultiByte(CP_UTF8, 0, input.data(), static_cast<int>(input.size()),
                                          nullptr, 0, nullptr, nullptr);
    if (size == 0) {
        return {};
    }

    std::string output(size, '\0');

    if (size != WideCharToMultiByte(CP_UTF8, 0, input.data(), static_cast<int>(input.size()),
                                    &output[0], static_cast<int>(output.size()), nullptr,
                                    nullptr)) {
        output.clear();
    }

    return output;
}

std::wstring UTF8ToUTF16W(std::string_view input) {
    return CPToUTF16(CP_UTF8, input);
}

int main() {
    // console UTF-8
    SetConsoleOutputCP(CP_UTF8);
    SetConsoleCP(CP_UTF8);

    // create file
    std::filesystem::path p{L"♻️.txt"}; // Explicit UTF-16 encoding
    std::filesystem::path evaluatep = {L"hello" / p};
    std::wstring evaluate = evaluatep.wstring();
    try {
        std::wcout << L"wstring -> " << evaluate; // Explicit UTF-16 encoding

        std::cout << std::endl;

        std::cout << "UTF16ToUTF8 -> " << UTF16ToUTF8(evaluate) << std::endl; // Explicit UTF-8 codified
    
        std::cout << ".string() -> " << evaluatep.string(); // Bad filesystem string() conversion

        std::cout << std::endl;

        std::cout << std::endl;
    } catch (std::exception& e) {
        std::cout << e.what() << std::endl;
    }

}
```
![image](https://github.com/microsoft/STL/assets/11653030/1f5aa05b-c0c1-4a8b-906b-c8a60e73f56b)

`Microsoft Visual Studio Professional 2022 (64 bits) - Current
Versión 17.5.4`

Explained more in: https://github.com/llvm/llvm-project/issues/69678

Must return two "hello\♻️.txt" at end almost.

**Comment by frederick-vs-ja** [comment]
Line 2 is transcoded as UTF-8 (the emoji is encoded as `"\xe2\x99\xbb\xef\xb8\x8f"`), but code units are considered encoded in [Windows-1252](https://en.wikipedia.org/wiki/Windows-1252) during output.
Line 3 seems to be correct.

Perhaps this is more a bug/mis-design of Windows Console than MSVC STL.

**Comment by boludoz** [comment]
> Line 2 is transcoded as UTF-8 (the emoji is encoded as `"\xe2\x99\xbb\xef\xb8\x8f"`), but code units are considered encoded in [Windows-1252](https://en.wikipedia.org/wiki/Windows-1252) during output.
> Line 3 seems to be correct.
> 
> Perhaps this is more a bug/mis-design of Windows Console than MSVC STL.

The console is set on UTF-8. Wstring and string are broken, that dont happens in rust.

**Comment by boludoz** [comment]
Also think the following, something is wrong there, both .string() and the function that converts utf16 to utf8 should give the same result.

**Comment by boludoz** [comment]
Also think the following, something is wrong there, both .string() and the function that converts utf16 to utf8 should give the same result.

Please for more test results goto link in main desc.



https://user-images.githubusercontent.com/11653030/276982787-8a7d068f-0dcb-4d6e-b45e-dac493f1827a.png

**Comment by frederick-vs-ja** [comment]
Have you tried to dump code units out like this?
```C++
static std::string DumpCodeUnits(std::string_view s) {
    std::string result;
    for (auto c : s) {
        result += std::format("\\x{:02x}", static_cast<unsigned char>(c));
    }
    return result;
}
```

I think the result `std::string` for line 2 should always be correct on Windows, although the output may be in a wrong enconding. I'm curious about why the output in line 3 is correct, but I can't reproduce the correct result on my machines. Coud you show the code units produced in that line?

The internal implementation of MSVC STL needs to call [`___lc_codepage_func`](https://learn.microsoft.com/en-us/cpp/c-runtime-library/lc-codepage-func?view=msvc-170) to determine whether UTF-8 is used.
https://github.com/microsoft/STL/blob/adea8d5ae280cafb91ae69b8dfaecd1c37a847d9/stl/src/filesystem.cpp#L268-L280

And the related UTF-8 environment seemingly needs to be established by `std::setlocale(LC_CTYPE, ".UTF8")`, not `SetConsoleOutputCP` or `SetConsoleCP`.

**Comment by boludoz** [comment]
> 
![image](https://github.com/microsoft/STL/assets/11653030/ab4f5097-744f-4d60-bce1-273e6b60f542)

It seems to me that you are very wrong. Have you started to analyze the problem?

**Comment by frederick-vs-ja** [comment]
> ![image](https://user-images.githubusercontent.com/11653030/277081665-87bcbec3-3f13-4ad7-8644-f0bd7e21f53b.png) It seems to me that you are wrong, the problem is not the console, I have already shown you that even though they are supposed to do exactly the same thing, it does not work. Have you started to analyze the problem?, that isnt a console problem, is a codecs problem.

I was looking at the dumped code units and found that `std::setlocale(LC_CTYPE, ".UTF8")` can make `path::string` produce right UTF-8 code unit sequences. The sequence in this example should be `\x68\x65\x6c\x6c\x6f\x5c\xe2\x99\xbb\xef\xb8\x8f\x2e\x74\x78\x74`.

It seems that the correct UTF-8 code unit sequence becomes wrong at output, while another sequence can cause right output.

Could you show the "another sequence" by `std::cout << DumpCodeUnits(evaluatep.string())`?

**Comment by boludoz** [comment]
> > ![image](https://user-images.githubusercontent.com/11653030/277081665-87bcbec3-3f13-4ad7-8644-f0bd7e21f53b.png) It seems to me that you are wrong, the problem is not the console, I have already shown you that even though they are supposed to do exactly the same thing, it does not work. Have you started to analyze the problem?, that isnt a console problem, is a codecs problem.
> 
> I was looking at the dumped code units and found that `std::setlocale(LC_CTYPE, ".UTF8")` can make `path::string` produce right UTF-8 code unit sequences. The sequence in this example should be `\x68\x65\x6c\x6c\x6f\x5c\xe2\x99\xbb\xef\xb8\x8f\x2e\x74\x78\x74`.
> 
> It seems that the correct UTF-8 code unit sequence becomes wrong at output, while another sequence can cause right output.
> 
> Could you show the "another sequence" by `std::cout << DumpCodeUnits(evaluatep.string())`?

You're being too hasty in telling me to remove " SetConsoleOutputCP(CP_UTF8);"
    "SetConsoleCP(CP_UTF8);
"
because the solution is to use both, anyway I think the problem is deeper. I would like to know what they expect for all APIs to be compatible with UTF-8?

![image](https://github.com/microsoft/STL/assets/11653030/45a50518-6731-4e0c-82a3-ec6b14421299)

**Comment by boludoz** [comment]
Using CLANG:
![image](https://github.com/microsoft/STL/assets/11653030/45a50518-6731-4e0c-82a3-ec6b14421299)

USING:
    // console UTF-8
    std::setlocale(LC_CTYPE, ".UTF8");
    SetConsoleOutputCP(CP_UTF8);
    SetConsoleCP(CP_UTF8);

**Comment by fsb4000** [comment]
your example in first post looks like this for me:
![изображение](https://github.com/microsoft/STL/assets/4289847/ccd12b87-99f7-4ea7-86b4-7319a693194b)

**Comment by fsb4000** [comment]
just 
```
// console UTF-8
std::setlocale(LC_CTYPE, ".UTF8");
SetConsoleOutputCP(CP_UTF8);
SetConsoleCP(CP_UTF8);
```
and change console font to some font which have the emoji.
I also added flag `/utf-8`

**Comment by fsb4000** [comment]
![изображение](https://github.com/microsoft/STL/assets/4289847/13fb71dc-8a03-4fde-98bb-b017627e7031)
![изображение](https://github.com/microsoft/STL/assets/4289847/4dc1e962-d7ac-47a9-a478-c5e6452a1fbf)

**Comment by fsb4000** [comment]
I used NSimSun font for the cmd:
![изображение](https://github.com/microsoft/STL/assets/4289847/82889b32-2b78-4b12-a45a-c19c373f63ec)

**Comment by boludoz** [comment]
> just
> 
> ```
> // console UTF-8
> std::setlocale(LC_CTYPE, ".UTF8");
> SetConsoleOutputCP(CP_UTF8);
> SetConsoleCP(CP_UTF8);
> ```
> 
> and change console font to some font which have the emoji. (the consolas font doesn't have the emoji, I used cmd. Windows Terminal default font might have the emoji) I also added flag `/utf-8`

Today we learned something new.

**Comment by boludoz** [comment]
Please improve support for this, WSL has better Unicode support than Windows itself.

**Comment by boludoz** [comment]
![image](https://github.com/microsoft/STL/assets/11653030/eaccc0cf-2321-4970-a7bc-1c1c783afff9)
