### ISSUE TITLE
<system_error>: ERROR_BROKEN_PIPE isn't mapped to std::errc::broken_pipe

### ISSUE THREAD

**Issue by BillyONeal** [microsoft/STL#413]
**Describe the bug**
It seems unusual that `ERROR_BROKEN_PIPE` from `<winerror.h>` isn't mapped to `std::errc::broken_pipe`. The table we currently use for that was originally submitted by Boost maintainers

There is some concern that changing this mapping is an ABI breaking change, as the `<system_error>` mapping currently lives in `msvcp140.dll`.

This is also tracked by Microsoft-internal bug VSO-149983.

**Command-line test case**
STL version (git commit or Visual Studio version): Tested at 94c9f9965b4e39bab9fdec6f71f1fad320e96d8b but at least as old as Visual Studio 2012.

```
C:\Temp>type repro.cpp
#include <assert.h>
#include <windows.h>
#include <system_error>

int main() {
    std::error_code ec{static_cast<int>(ERROR_BROKEN_PIPE), std::system_category()};
    assert(ec == std::make_error_condition(std::errc::broken_pipe));
}

C:\Temp>cl /EHsc /W4 /WX .\repro.cpp
Microsoft (R) C/C++ Optimizing Compiler Version 19.24.28314 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

repro.cpp
Microsoft (R) Incremental Linker Version 14.24.28314.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:repro.exe
repro.obj

C:\Temp>.\repro.exe
Assertion failed: ec == std::make_error_condition(std::errc::broken_pipe), file .\repro.cpp, line 7

```

**Additional context**
We previously have not fixed this over ABI break concerns.

**Comment by StephanTLavavej** [comment]
After further consideration, while this would be a behavior change in the separately compiled DLL in the redistributable, this doesn't seem to be harmful. Such behavior changes always need additional scrutiny, but I believe that this should be reasonable to implement.
