### ISSUE TITLE
`<ranges>`: `operator|(_Left&& __l, _Right&& __r)` should return `decltype(auto)`

### ISSUE THREAD

**Issue by hewillk** [microsoft/STL#4153]
https://github.com/microsoft/STL/blob/bc5a5c349643f35b65d755c2ce33861c8029f705/stl/inc/ranges#L183-L190

IIUC, LWG-3981 being tagged as NAD means it's a bug in MSVC-STL, right?

**Comment by StephanTLavavej** [comment]
We talked about this at the weekly maintainer meeting and we agree that this is a bug - WG21-N4964 \[range.adaptor.object\]/1

> For a range adaptor closure object `C` and an expression `R` such that `decltype((R))` models `range`, the following expressions are equivalent:
> `C(R)`
> `R | C`

does indeed appear to clearly mandate that `decltype(auto)` is used here.
