### ISSUE TITLE
<memory>: Remove workarounds for VSO-1006185

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#416]
Microsoft-internal VSO-1006185 "/clr is incompatible with LWG-2899's changes to unique_ptr" was fixed by Microsoft-internal MSVC-PR-221726.

This will be available in VS 2019 16.6 (presumably Preview 1); when that is released, we should remove the workarounds in `<memory>`. For example:

https://github.com/microsoft/STL/blob/31bed7ae0d2ff22029e7ed3e8c58d6ee429974fc/stl/inc/memory#L1824-L1826

There are also workarounds in our devcrt test suite.

**Comment by CaseyCarter** [comment]
I'll self-assign this since I already have a change sitting in a branch which the compiler dev was kind enough to test with the fixed compiler.
