### ISSUE TITLE
P0952R2 A New Specification For `generate_canonical()`

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#4169]
WG21-P0952R2 A New Specification For `generate_canonical()`

No feature-test macro is mentioned.

This technically isn't a Defect Report, but it's a behavioral change that resolves an LWG issue and avoids the correctness-damaging behavior of returning `1.0`, so we want to implement this unconditionally and **WILL** accept a PR for this in advance of opening up the floodgates to arbitrary C++26 features at some point in the future.

**Comment by frederick-vs-ja** [comment]
It seems that this is only the resolution of LWG-2524 and should be handled as other LWG issues.

**Comment by MattStephanson** [comment]
I'm investigating this. The new specification causes several more libc++ tests to fail, so I've opened a [PR](https://github.com/llvm/llvm-project/pull/88669) to relax some of their tolerances.
