### ISSUE TITLE
P2905R2 Runtime Format Strings

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#4184]
WG21-P2905R2 Runtime Format Strings

No feature-test macro is mentioned.

This was formally accepted as a Defect Report, retroactively amending C++20.

**Comment by Alan-Jowett** [comment]
Linked to this issue as this change broke my code. It would have been nice to know ahead of time that VS 17.10 contained a breaking change (perhaps in the known issues section)?

**Comment by frederick-vs-ja** [comment]
> Linked to this issue as this change broke my code. It would have been nice to know ahead of time that VS 17.10 contained a breaking change (perhaps in the known issues section)?

You can view the [Changelog](https://github.com/microsoft/STL/wiki/Changelog).
