### ISSUE TITLE
When will P2128 be implemented?

### ISSUE THREAD

**Issue by dr-eck** [microsoft/STL#4199]
I'd really like to be able to write the following code:
```
std::vector<double> Bdat(dfcts.ndf * vbs.nvb);     // allocate the space
    using Dext = std::dextents<size_t, 2>;
    std::mdspan<double, Dext> B{ Bdat.data(), dfcts.ndf, vbs.nvb};    // create the mdspan
    B[0, 0] = 1.0;
```
But, according to 康桓瑋 on StackOverflow, the last line needs to be:
```
B[std::array{0, 0}] = 1.0;
```
That's really ugly!  When will P2128R6 be implemented?

**Comment by frederick-vs-ja** [comment]
It will, but perhaps not soon. Nothing can be furtherly done in a standard library implementation, but you can use Clang-CL in the meanwhile.

The implementation of [P2128R6](https://wg21.link/p2128r6) by MSVC is tracked in DevCom-10306063.

**Comment by CaseyCarter** [comment]
We can't speculate on when a compiler feature will be implemented, so all we can really do is guarantee that it will be implemented before we consider C++23 to be complete.
