### ISSUE TITLE
P0966R1 string::reserve() Should Not Shrink

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#42]
[P0966R1](https://wg21.link/P0966R1) `string::reserve()` Should Not Shrink

This deprecates old machinery.

**Comment by NathanSWard** [comment]
Is this issue available for me to resolve? :)

**Comment by StephanTLavavej** [comment]
This is sufficiently small that we can review it and write tests before getting the full test suite on GitHub (which is making steady progress), and nobody has worked on it. So yes, available!

My initial opinion is that `reserve()` with no arguments should do whatever it does today, as long as that behavior is conformant; users should call `string::shrink_to_fit()` if they want that behavior. After looking at the code, I see that we treat zero-arg `reserve()` as a no-op; changing that behavior would be unnecessarily destabilizing.

Note: we emit deprecation messages for almost all Standard-deprecated features and this should be one of them; look at `shared_ptr::unique()` and `yvals_core.h` for precedent. Let us know if you need more info. 😸
