### ISSUE TITLE
`<chrono>` `<format>`: `duration` formatting ignores dynamic width

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#4201]
```
C:\Temp>type meow.cpp
```
```cpp
#include <chrono>
#include <format>
#include <iostream>
#include <string>
#include <thread>
using namespace std;

int main() {
#ifdef __GLIBCXX__
    cout << "libstdc++\n";
#elif defined(_LIBCPP_VERSION)
    cout << "libc++\n";
#elif defined(_MSVC_STL_UPDATE)
    cout << "microsoft/STL\n";
#endif
    const auto id = this_thread::get_id();
    cout << format("       int {{:20}}: [{:20}]\n", 1729);
    cout << format("       int {{:{{}}}}: [{:{}}]\n", 1729, 20);
    cout << format("thread::id {{:20}}: [{:20}]\n", id);
    cout << format("thread::id {{:{{}}}}: [{:{}}]\n", id, 20);
    cout << format(" seconds {{:20%T}}: [{:20%T}]\n", 314159s);
    cout << format(" seconds {{:{{}}%T}}: [{:{}%T}]\n", 314159s, 20);
}
```
```
C:\Temp>cl /EHsc /nologo /W4 /std:c++latest /MTd /Od meow.cpp && meow
meow.cpp
microsoft/STL
       int {:20}: [                1729]
       int {:{}}: [                1729]
thread::id {:20}: [               34680]
thread::id {:{}}: [               34680]
 seconds {:20%T}: [87:15:59            ]
 seconds {:{}%T}: [87:15:59]
```
https://godbolt.org/z/YbM9qnocf

When formatting a `duration`, the fact that `{:20%T}` respects the statically provided width but `{:{}%T}` ignores the dynamically provided width is *super* buggy, and neither libstdc++ nor libc++ exhibit that behavior.

(There's a separate question of whether `duration` should default to being left-aligned or right-aligned. MSVC and libstdc++ chose left, libc++ chose right.)

(libc++ is also printing the hours mod 24, unlike MSVC and libstdc++.)

**Comment by cpplearner** [comment]
It seems that `_Chrono_formatter` never reads `_Specs._Dynamic_width_index` after it is set. Maybe `_Chrono_formatter::_Write` needs to do the same thing as done in `_Formatter_base::format` (with `_Dynamic_format_specs` replaced by `_Chrono_format_specs`).

https://github.com/microsoft/STL/blob/46843b3bf320c6070ff63e978936bcf898e5a2bc/stl/inc/format#L3682-L3691
