### ISSUE TITLE
`<ostream>`: With `setprecision(0)` `showpoint` `fixed`, a bogus `'.'` is emitted for infinity and NaN

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#4210]
```
C:\Temp>type meow.cpp
```
```cpp
#include <iomanip>
#include <iostream>
#include <limits>
using namespace std;

int main() {
    constexpr double inf_dbl = numeric_limits<double>::infinity();
    constexpr double nan_dbl = numeric_limits<double>::quiet_NaN();

    cout << "setprecision(0) showpoint fixed:\n";
    cout << setprecision(0) << showpoint << fixed;

    cout << inf_dbl << "\n";
    cout << -inf_dbl << "\n";
    cout << nan_dbl << "\n";
    cout << -nan_dbl << "\n";

    cout << "\nAnd showpos:\n";
    cout << showpos;

    cout << inf_dbl << "\n";
    cout << -inf_dbl << "\n";
    cout << nan_dbl << "\n";
    cout << -nan_dbl << "\n";
}
```
```
C:\Temp>cl /EHsc /nologo /W4 /MTd /Od meow.cpp && meow
meow.cpp
setprecision(0) showpoint fixed:
i.nf
-.inf
n.an
-.nan(ind)

And showpos:
+i.nf
-.inf
+n.an
-.nan(ind)
```

libstdc++ and libc++ behave correctly (note that MSVC's STL has an intentional behavior difference regarding negative NaNs, though): https://godbolt.org/z/MYsPxc98h

Originally reported as DevCom-10512845 / VSO-1917556 / AB#1917556 .

**Comment by MattStephanson** [comment]
The STL appears to be sending the correct format flags to `printf`. The UCRT seems to be adding the point regardless of whether the value is finite or not. Perhaps we could work around it by omitting the `#` flag for non-finite values.

![image](https://github.com/microsoft/STL/assets/68978048/7198a8bf-b0ff-4912-a73d-3d8a281b8181)

**Comment by frederick-vs-ja** [comment]
> The STL appears to be sending the correct format flags to `printf`. The UCRT seems to be adding the point regardless of whether the value is finite or not. Perhaps we could work around it by omitting the `#` flag for non-finite values.
> 
> ![image](https://user-images.githubusercontent.com/68978048/284024930-7198a8bf-b0ff-4912-a73d-3d8a281b8181.png)

Thanks! I've verified that this is essentially a bug of UCRT and reported DevCom-10519861.

I think we should add some workaround at this moment.
