### ISSUE TITLE
<xlocinfo.h>: Reduce size of _Ctypevec, ctype<char>, ctype<wchar_t>, and ctype<unsigned short>

### ISSUE THREAD

**Issue by SunnyWar** [microsoft/STL#426]
`_Ctypevec` has some padding that can be eliminated by moving the pointers to the front.  Here are the sizes before and after rearranging the members.

```
class _Ctypevec	size(32):
	+---
 0	| _Page
  	| <alignment member> (size=4)
 8	| _Table
16	| _Delfl
  	| <alignment member> (size=4)
24	| _LocaleName
	+---

class std::ctype<char>	size(48):	
class std::ctype<wchar_t>	size(96):
class std::ctype<unsigned short>	size(96):

///////////  After

class _Ctypevec	size(24):
	+---
 0	| _Table
 8	| _LocaleName
16	| _Page
20	| _Delfl
	+---		
class std::ctype<char>	size(40):
class std::ctype<wchar_t>	size(88):
class std::ctype<unsigned short>	size(88):
```

**vNext note:** Resolving this issue will require breaking binary compatibility. We won't be able to accept pull requests for this issue until the vNext branch is available. See #169 for more information.

**Comment by StephanTLavavej** [comment]
Relevant code:

https://github.com/microsoft/STL/blob/2989323bdc47a5e0eac4537a862f8c06f503d6fe/stl/inc/xlocinfo.h#L64-L69

**Comment by SunnyWar** [comment]
I assume pull requests for this cannot happen until #169 ?

**Comment by StephanTLavavej** [comment]
That's correct. At the moment, vNext is lower priority than finishing the GitHub migration and C++20, so the branch won't be ready for a while - but it will happen.

**Comment by SunnyWar** [comment]
> That's correct. At the moment, vNext is lower priority than finishing the GitHub migration and C++20, so the branch won't be ready for a while - but it will happen.

No, priority is not on C++23. History indicates this will not happen. Closing.
