### ISSUE TITLE
<complex.h>: Defines C macros that it should not

### ISSUE THREAD

**Issue by mborland** [microsoft/STL#4281]
# Describe the bug
The working draft of the C++ ISO states: The header <complex.h> behaves as if it simply includes the header `<complex>`. This is not the case with the MSVC STL as it defines C macros such as `#define I  _Complex_I`.

# Command-line test case
```
C:\Temp>type repro.cpp
#include <complex.h>

int main()
{
   int J = 0;
   for (int I = 0; I < 10; ++I)
   {
      J += I;
   }
   
   return 0;
}

C:\Temp>cl /EHsc /W4 /WX /std:c++latest .\repro.cpp
Microsoft (R) C/C++ Optimizing Compiler Version 19.36.32522 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

/std:c++latest is provided as a preview of language features from the latest C++
working draft, and we're eager to hear about bugs and suggestions for improvements.
However, note that these features are provided as-is without support, and subject
to changes or removal as the working draft evolves. See
https://go.microsoft.com/fwlink/?linkid=2045807 for details.

repro.cpp
Microsoft (R) Incremental Linker Version 14.36.32522.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:repro.exe
repro.obj

C:\Temp>.\repro.exe
test failure
```

See also: https://godbolt.org/z/xh8jvr7Kx and https://godbolt.org/z/b9PseP7nn

# Expected behavior
I would expect `I` to not be defined as a macro. 

# STL version
Godbolt provided v19.latest

# Additional context
Initial issue is: https://github.com/scipy/scipy/issues/19726

**Comment by frederick-vs-ja** [comment]
This is a bug of UCRT which is not shipped in this repo.

**Comment by frederick-vs-ja** [comment]
Opened DevCom-10547133. UCRT should be already fine if you use C++17 or later modes.

**Comment by mborland** [comment]
> Opened [DevCom-10547133](https://developercommunity.visualstudio.com/t/10547133). UCRT should be already fine if you use C++17 or later modes.

Thank you
