### ISSUE TITLE
<filesystem>: directory_iterator(...) and is_empty(...) not working with empty volumes 

### ISSUE THREAD

**Issue by MartinKuschnik** [microsoft/STL#4291]
I'm woking with virtual disks and have some trouble if a new volume does not contain any files or directories.

First we have to ceate and attch a new virtual disk:
```
New-VHD -Path "$env:TEMP\test_volume.vhdx" -SizeBytes 100MB | Mount-VHD -Passthru -NoDriveLetter |Initialize-Disk -Passthru | New-Partition -UseMaximumSize | Format-Volume -FileSystem NTFS -Confirm:$false -Force | Format-List -Property Path
```
The command should return the volume name

```
Path : \\?\Volume{069de63e-8072-42fe-9adf-5a9b9cec201d}\
```
that can be used to access it:

```cpp
#include <filesystem> 
#include <iostream> 

int wmain(int argc)
{
	constexpr const char* volume = "\\\\?\\Volume{069de63e-8072-42fe-9adf-5a9b9cec201d}\\";

	std::cout 
		<< std::format("std::filesystem::exists('{0}')) : {1}", volume, std::filesystem::exists(volume)) 
		<< std::endl;

	try
	{
		std::cout 
			<< std::format("std::filesystem::is_empty('{0}')) : {1}", volume, std::filesystem::is_empty(volume)) 
			<< std::endl;
	}
	catch (const std::exception& ex)
	{
		std::cout 
			<< std::format("std::filesystem::is_empty('{0}')) failed: {1}", volume, ex.what()) 
			<< std::endl;
	}

	try
	{
		const auto it = std::filesystem::directory_iterator(volume);

		std::cout 
			<< std::format("std::filesystem::directory_iterator('{0}')) succeeded.", volume) 
			<< std::endl;
	}
	catch (const std::exception& ex)
	{
		std::cout 
			<< std::format("std::filesystem::directory_iterator('{0}')) failed: {1}", volume, ex.what()) 
			<< std::endl;
	}
}
```
This code will produce the following output:
```
std::filesystem::exists('\\?\Volume{069de63e-8072-42fe-9adf-5a9b9cec201d}\')) : true
std::filesystem::is_empty('\\?\Volume{069de63e-8072-42fe-9adf-5a9b9cec201d}\')) failed: is_empty: The system cannot find the file specified.: "\\?\Volume{069de63e-8072-42fe-9adf-5a9b9cec201d}\"
std::filesystem::directory_iterator('\\?\Volume{069de63e-8072-42fe-9adf-5a9b9cec201d}\')) failed: directory_iterator::directory_iterator: The system cannot find the file specified.: "\\?\Volume{069de63e-8072-42fe-9adf-5a9b9cec201d}\"
```
# Expected behavior
- `std::filesystem::is_empty(...)` should not throw any exception for an empty volume.
- `std::filesystem::directory_iterator(...)` should not throw any exception for an empty volume.

# STL version
```
Microsoft Visual Studio Community 2022 (64-bit) - Current
Version 17.8.3
```
# Additional context
After asigning a drive letter or creating a file or directory the code workes like expacted.

**Comment by Fulgen301** [comment]
`is_empty` constructs a `directory_iterator`, which calls `FindFirstFileExW`. which ultimately calls [`NtQueryDirectoryEx`](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/nf-ntifs-ntquerydirectoryfileex) with a file handle to the volume directory, `QueryFlags = SL_RETURN_SINGLE_ENTRY` and `FileName = "*"`, which therefore returns the first directory entry. A "regular" empty directory (e.g. one created by `mkdir`) isn't actually empty, as far as that function is concerned - it returns an entry with the file name `.` However, your volume path does _not_ have such an entry - it is truly empty, so `NtQueryDirectoryEx` fails with `STATUS_NO_SUCH_FILE`. This behavior isn't explicitely documented in the syscall documentation, [but the Server Message Block protocol specification before Revision 51.0 documented that error code with the same behavior](https://winprotocoldoc.blob.core.windows.net/productionwindowsarchives/MS-SMB2/%5bMS-SMB2%5d-170316-diff.pdf):

> If there are no entries to return and this was the initial query (Open.EnumerationLocation was zero
before querying the object store), the server MUST fail the request with STATUS_NO_SUCH_FILE.

The error code then bubbles up and is returned as `ERROR_FILE_NOT_FOUND` by `FindFirstFileExW`.

As calling `FindFirstFileExW` with an inexistent path results in `ERROR_PATH_NOT_FOUND`,

https://github.com/microsoft/STL/blob/a8888806c6960f1687590ffd4244794c753aa819/stl/inc/filesystem#L2572-L2581

could maybe be extended to interpret `ERROR_FILE_NOT_FOUND` as "no more files"?
