### ISSUE TITLE
<optional>: Calling reset() through a member function pointer is not allowed

### ISSUE THREAD

**Issue by davidharabagiu** [microsoft/STL#4300]
# Describe the bug
Calling reset() on an `optional` object works even though the method is defined in `_Optional_construct_base` which is privately inherited, but doesn't work when calling through a member function pointer.

# Command-line test case
```
C:\Temp>type repro.cpp
#include <optional>

using namespace std;

int main()
{
    optional<int> s;
    s.reset(); // works

    auto fp = &optional<int>::reset;
    (s.*fp)(); // doesn't work

    auto fp2 = &optional<int>::has_value;
    (s.*fp2)(); // works
    
    return 0;
}

C:\Temp>cl /EHsc /W4 /WX /std:c++latest .\repro.cpp
Microsoft (R) C/C++ Optimizing Compiler Version 19.36.32522 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

/std:c++latest is provided as a preview of language features from the latest C++
working draft, and we're eager to hear about bugs and suggestions for improvements.
However, note that these features are provided as-is without support, and subject
to changes or removal as the working draft evolves. See
https://go.microsoft.com/fwlink/?linkid=2045807 for details.

repro.cpp
error C2243: 'type cast': conversion from 'std::optional<int> *' to 'std::_Optional_destruct_base<_Ty,true> *' exists, but is inaccessible
error C2243:         with
error C2243:         [
error C2243:             _Ty=int
error C2243:         ]
```

# Expected behavior
The code should compile.

# STL version
Microsoft Visual Studio Professional 2022
Version 17.8.3
VisualStudio.17.Release/17.8.3+34330.188
Microsoft .NET Framework
Version 4.8.09037

Installed Version: Professional

Visual C++ 2022   00476-80000-00000-AA314
Microsoft Visual C++ 2022

ASP.NET and Web Tools   17.8.358.6298
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.8.358.6298
Azure App Service Tools v3.0.0

C# Tools   4.8.0-7.23572.1+7b75981cf3bd520b86ec4ed00ec156c8bc48e4eb
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

FireGiant HeatWave   1.0.2.1
Visual Studio tooling for WiX projects.  For more information about HeatWave, visit http://www.firegiant.com.

Linux Core Dump Debugging   1.0.9.34330
Enables debugging of Linux core dumps.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

NuGet Package Manager   6.8.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

RunPowerShellCommand Extension   1.0
RunPowerShellCommand Visual Studio Extension Detailed Info

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

TypeScript Tools   17.0.20920.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.8.0-7.23572.1+7b75981cf3bd520b86ec4ed00ec156c8bc48e4eb
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual C++ for Linux Development   1.0.9.34330
Visual C++ for Linux Development

Visual F# Tools   17.8.0-beta.23475.2+10f956e631a1efc0f7f5e49c626c494cd32b1f50
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

# Additional context

**Comment by sylveon** [comment]
The C++ standard makes it illegal to take the address of standard functions. This is not a bug.

**Comment by frederick-vs-ja** [comment]
> The C++ standard makes it illegal to take the address of standard functions. This is not a bug.

It seems to me that [[namespace.std]/6](https://timsong-cpp.github.io/cppwp/n4868/namespace.std#6) is true only since C++20 (WG21-P0551R3).
Fortunately (or unfortunately?), the signatures of standard non-virtual member functions are already made unspecified by LWG-2259.

**Comment by StephanTLavavej** [comment]
Thanks for reporting this issue. We talked about this at the weekly maintainer meeting and we agree with @sylveon and @frederick-vs-ja - this is conforming behavior.
