### ISSUE TITLE
`__cpp_lib_modules` is not defined when importing the C++ standard library using modules

### ISSUE THREAD

**Issue by bluetarpmedia** [microsoft/STL#4329]
# Describe the bug
After following [these instructions](https://learn.microsoft.com/en-us/cpp/cpp/tutorial-import-stl-named-module?view=msvc-170) to import the C++ standard library using modules and compile on the command line, I expected `__cpp_lib_modules` to be defined but it is not.

# Command-line test case
```
C:\Temp>type repro.cpp
import std;

int main()
{
    std::cout << "Hello World!\n";

#ifdef __cpp_modules
    std::cout << "__cpp_modules: " << std::to_string(__cpp_modules) << " \n";
#else
    std::cout << "__cpp_modules: not defined\n";
#endif

#ifdef __cpp_lib_modules
    std::cout << "__cpp_lib_modules: " << std::to_string(__cpp_lib_modules) << " \n";
#else
    std::cout << "__cpp_lib_modules: not defined\n";
#endif
}

C:\Temp>cl /std:c++latest /permissive- /MD /EHsc /W4 /WX /c "%VCToolsInstallDir%\modules\std.ixx"
Microsoft (R) C/C++ Optimizing Compiler Version 19.38.33134 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

/std:c++latest is provided as a preview of language features from the latest C++
working draft, and we're eager to hear about bugs and suggestions for improvements.
However, note that these features are provided as-is without support, and subject
to changes or removal as the working draft evolves. See
https://go.microsoft.com/fwlink/?linkid=2045807 for details.

std.ixx

C:\Temp>cl repro.cpp std.obj /std:c++latest /permissive- /MD /EHsc /W4 /WX
Microsoft (R) C/C++ Optimizing Compiler Version 19.38.33134 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

/std:c++latest is provided as a preview of language features from the latest C++
working draft, and we're eager to hear about bugs and suggestions for improvements.
However, note that these features are provided as-is without support, and subject
to changes or removal as the working draft evolves. See
https://go.microsoft.com/fwlink/?linkid=2045807 for details.

repro.cpp
Microsoft (R) Incremental Linker Version 14.38.33134.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:repro.exe
repro.obj
std.obj

C:\Temp>repro.exe
Hello World!
__cpp_modules: 201907
__cpp_lib_modules: not defined
```
# Expected behavior
I expected `__cpp_lib_modules` to be defined.

# STL version
```
Microsoft Visual Studio Professional 2022 (64-bit) - Current
Version 17.8.5
```
# Additional context
When I inspect `yvals_core.h`, I see:

```
#if !defined(__clang__) && !defined(__EDG__) // TRANSITION, Clang and EDG support for modules
#define __cpp_lib_modules 202207L
#endif // !defined(__clang__) && !defined(__EDG__)
```

And `__EDG__` is defined to be `1`, causing `__cpp_lib_modules` to not be defined.

**Comment by fsb4000** [comment]
> And `__EDG__` is defined to be 1, causing `__cpp_lib_modules` to not be defined.

No, `__EDG__` is 0, `__EDG__` is 1 only for Intellesense. 
It's because modules don't export C macros.
You can change your code:
```
#include <yvals_core.h>
import std;

int main()
{
    std::cout << "Hello World!\n";

#ifdef __cpp_modules
    std::cout << "__cpp_modules: " << std::to_string(__cpp_modules) << " \n";
#else
    std::cout << "__cpp_modules: not defined\n";
#endif

#ifdef __cpp_lib_modules
    std::cout << "__cpp_lib_modules: " << std::to_string(__cpp_lib_modules) << " \n";
#else
    std::cout << "__cpp_lib_modules: not defined\n";
#endif
}
```
and you will get:
```
main
Hello World!
__cpp_modules: 201907
__cpp_lib_modules: 202207
```
![изображение](https://github.com/microsoft/STL/assets/4289847/891ebd4b-162e-40ce-9504-807d91d411cf)
Yes, I agree, this is a bug...

**Comment by bluetarpmedia** [comment]
Thanks. Yes, I think you're right that it's necessary to `#include <version>` first, since C++ modules don't import macros, and C++ Library feature test macros are defined in header files, as opposed to Language feature test macros which are predefined in each translation unit by the compiler.

**Comment by frederick-vs-ja** [comment]
`__cpp_lib_modules` is a non-predefined macro so it can't be provided by only importing modules.

**Comment by StephanTLavavej** [comment]
Yep, this is by design (although it is admittedly surprising).

Note that before VS 2022 17.10 Preview 1, mixing `#include <meow>` and `import std;` in the same translation unit is highly likely to cause compiler errors. You'll probably get away with it if you restrict yourself to only `#include <version>` (which is very lightweight) before `import std;`. (UCRT headers like `<stdio.h>` are generally ok too.) After 17.10 Preview 1, we have a workaround that should allow you `#include` any STL header before `import std;` (but *not* the reverse order). Long-term, arbitrarily ordered mixing is required to work according to the Standard, but we're still working on that.
