### ISSUE TITLE
<yvals_core.h>: Warnings C4472 and C4571 are removed in VS 2019 16.6

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#433]
When VS 2019 16.6 Preview 1 is available, we can remove the following warning suppressions, as the compiler has permanently removed these useless warnings:

https://github.com/microsoft/STL/blob/2989323bdc47a5e0eac4537a862f8c06f503d6fe/stl/inc/yvals_core.h#L349-L350

https://github.com/microsoft/STL/blob/2989323bdc47a5e0eac4537a862f8c06f503d6fe/stl/inc/yvals_core.h#L353-L354

and the corresponding numbers from:

https://github.com/microsoft/STL/blob/2989323bdc47a5e0eac4537a862f8c06f503d6fe/stl/inc/yvals_core.h#L375-L382

This was Microsoft-internal compiler checkin MSVC-PR-224138.

**Comment by dcorbin-wintellect** [comment]
Question: I am trying to research WHY the compiler has removed C4472 - and why it is (was) considered a "useless warning"...  I can be reached privately as david (dot) corbin (at) live (dot) com. ... Thanks in advance for any information/links/reasons...
