### ISSUE TITLE
[Unresolved external symbol] [C++20] [std.ixx] [import std;]

### ISSUE THREAD

**Issue by Acalamity** [microsoft/STL#4343]
This happens when using std::format anywhere.
I built std.ixx with C++20 in VS2022. Exactly the same command lines as in the consuming project.
The error listing when trying to `import std;` with a proper path in `/reference` in another project (also C++20) with files Test.cpp and TestHeader.h:

```cpp
1>Tests.obj : error LNK2001: unresolved external symbol "public: static int const std::_General_precision_tables_2<double>::_Max_P" (?_Max_P@?$_General_precision_tables_2@N@std@@2HB::<!std>)
1>TestHeader.h.obj : error LNK2001: unresolved external symbol "public: static int const std::_General_precision_tables_2<double>::_Max_P" (?_Max_P@?$_General_precision_tables_2@N@std@@2HB::<!std>)
1>Tests.obj : error LNK2001: unresolved external symbol "public: static int const std::_General_precision_tables_2<float>::_Max_P" (?_Max_P@?$_General_precision_tables_2@M@std@@2HB::<!std>)
1>TestHeader.h.obj : error LNK2001: unresolved external symbol "public: static int const std::_General_precision_tables_2<float>::_Max_P" (?_Max_P@?$_General_precision_tables_2@M@std@@2HB::<!std>)
```
TestHeader.h is a header unit.
The project only uses std::format, std::string, std::vector, std::cout and std::cin. It does not `#include` anything at all, only the `import std;` imports anything.

Is there a way to fix this?
Thank you very much and I am very grateful for C++20 support. My builds are truly swift now.

**Comment by StephanTLavavej** [comment]
Are you linking with the `std.obj` that was produced alongside the `std.ifc`?

**Comment by Acalamity** [comment]
Oh it seems like I missed how to do that! I definitely am only using /reference to the std.ixx.ifc produced.

**Comment by StephanTLavavej** [comment]
Great, I'm glad it wasn't some novel bug! :smile_cat: For future reference, `std.obj` is mentioned by the documentation here: https://learn.microsoft.com/en-us/cpp/cpp/tutorial-import-stl-named-module?view=msvc-170
