### ISSUE TITLE
Exported declaration of `std::exception` follows non-exported declaration

### ISSUE THREAD

**Issue by AndreyG** [microsoft/STL#4350]
In the header `<exception>` firstly `<vcruntime_exception.h>` is [included](https://github.com/microsoft/STL/blob/32e65ac3e54a7150202cc9b3cc4de7330d58d24e/stl/inc/exception#L34) and then `class exception` is redeclared [as exported](https://github.com/microsoft/STL/blob/32e65ac3e54a7150202cc9b3cc4de7330d58d24e/stl/inc/exception#L39). This is incorrect by the standard (https://eel.is/c++draft/module.interface#6), namely it repeats https://eel.is/c++draft/module.interface#example-4, where `struct S` is replaced with `class exception`.

**Comment by StephanTLavavej** [comment]
Reported internal compiler bug VSO-1953157 "Modules: MSVC should emit an error when an exported declaration follows a non-exported declaration".

**Comment by StephanTLavavej** [comment]
Thanks again for reporting this bug - fixing it was surprisingly involved but it's going to significantly improve and simplify our code! :heart_eyes_cat:
