### ISSUE TITLE
<stdatomic.h> '_Atomic_imod_fetch8': benign redefinition of type...

### ISSUE THREAD

**Issue by Nyufu** [microsoft/STL#4360]
# Describe the bug
Using stdatomic.h with [/J](https://learn.microsoft.com/en-us/cpp/build/reference/j-default-char-type-is-unsigned?view=msvc-170) cause warning C4142: '_Atomic_imod_fetch8': benign redefinition of type
predefined C++ types (compiler internal)(88): note: see declaration of '_Atomic_imod_fetch8'

I am not 100% sure it is an STL bug, but most likely the STL should handle char as unsigned.

# Command-line test case
```
C:\Temp>type repro.c
#include <stdatomic.h>

C:\Temp>cl /std:c11 /experimental:c11atomics /J /WX repro.c
Microsoft (R) C/C++ Optimizing Compiler Version 19.38.33135 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

Experimental features are provided as a preview of proposed language features,
and we're eager to hear about bugs and suggestions for improvements. However,
note that these experimental features are non-standard, provided as-is without
support, and subject to breaking changes or removal without notice. See
http://go.microsoft.com/fwlink/?LinkID=691081 for details.

repro.c
c:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.38.33130\include\vcruntime_c11_atomic_support.h(1019): error C2220: the following warning is treated as an error
c:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.38.33130\include\vcruntime_c11_atomic_support.h(1019): warning C4142: '_Atomic_imod_fetch8': benign redefinition of type
predefined C++ types (compiler internal)(88): note: see declaration of '_Atomic_imod_fetch8'
```

**Comment by frederick-vs-ja** [comment]
Your example is a C program and MSVC STL is unlikely to do anything for it (note that `<stdatomic.h>` is originally a C11 header).

VCRuntime or MSVC probably needs to be fixed. Reported DevCom-10575660.

**Comment by CaseyCarter** [comment]
Thanks @frederick-vs-ja for reporting this to DevCom - this indeed looks like something that will need to be fixed in VCRuntime and/or the compiler. Please followup at DevCom-10575660.
