### ISSUE TITLE
`<xutility>`, `<algorithm>`: vector algorithms dispatching functions miss top level `const` on pointer parameters

### ISSUE THREAD

**Issue by AlexGuteniev** [microsoft/STL#4385]
# The affected code

https://github.com/microsoft/STL/blob/bd3d740ae5de7255c720b8133c5d23aa131e0760/stl/inc/algorithm#L66-L112
https://github.com/microsoft/STL/blob/bd3d740ae5de7255c720b8133c5d23aa131e0760/stl/inc/xutility#L113-L214

# The desired change
The functions being defined here are taking `_Ty* _First, _Ty* _Last` parameters, but aren't modifying `_First` and `_Last` themselves. We should apply top-level `const` to these pointers, changing them to `_Ty* const _First, _Ty* const _Last` which will make our code more consistent and ever-so-slightly more resistant to mistakes.

Note that `__std_find_trivial_unsized` takes only `_Ty* _First` but should be changed similarly.

# About this "good first issue"
This issue is intended for a new contributor (especially one new to GitHub) to get started with a simple change.

Please feel free to submit a pull request if there isn't one already linked here - no need to ask for permission! :smile_cat:

You can (and should) link your pull request to this issue using [GitHub's close/fix/resolve syntax](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
(in the PR description not the commit message)

**Comment by KamathScience** [comment]
Hi, I am new to open-source development and interested in working on this. Could you please assign this to me?

**Comment by StephanTLavavej** [comment]
Done! We don't usually assign issues to contributors - it's usually sufficient for a contributor to comment "I'm looking into this" to avoid duplicating work while they prepare a PR - but for things labeled "good first issue" I can see how having an actual assignment will help people searching for unassigned issues.

Welcome to the open-source world! :cat: :world_map:

**Comment by AlexGuteniev** [comment]
Due to the latest merge, the scope is now few functions more.
