### ISSUE TITLE
`<ranges>`: Drop one superfluous `_Fake_copy_init<bool>` where the argument type is always `bool`

### ISSUE THREAD

**Issue by frederick-vs-ja** [microsoft/STL#4394]
Discovered while dealing with #4389.

The use of `_Fake_copy_init` here (determining whether the implicit coversion is non-throwing) looks superfluous.
https://github.com/microsoft/STL/blob/bd3d740ae5de7255c720b8133c5d23aa131e0760/stl/inc/ranges#L3911-L3912

In this place:
- The type of `_Left._Outer` and `_Right._Outer` models [`forward_iterator`](https://en.cppreference.com/w/cpp/iterator/forward_iterator) (definition can be found [here](https://github.com/microsoft/STL/blob/7d5d8c32a7988f86c0f9e975559d1c7a3566f05e/stl/inc/ranges#L3719-L3730)), and thus `decltype(_Left._Outer == _Right._Outer)` should already model [_`boolean-testable`_](https://en.cppreference.com/w/cpp/concepts/boolean-testable), and
- `_Left._Inner` and `_Right._Inner` are `_Defaultabox`es (definition can be found [here](https://github.com/microsoft/STL/blob/7d5d8c32a7988f86c0f9e975559d1c7a3566f05e/stl/inc/ranges#L3746-L3748)) for which `operator==` always returns `bool` ([[1]](https://github.com/microsoft/STL/blob/7d5d8c32a7988f86c0f9e975559d1c7a3566f05e/stl/inc/ranges#L704-L709), [[2]](https://github.com/microsoft/STL/blob/7d5d8c32a7988f86c0f9e975559d1c7a3566f05e/stl/inc/ranges#L768C25-L768C55)).

As indicated by the use of _`boolean-testable`_, the `&&` operator in `_Left._Outer == _Right._Outer && _Left._Inner == _Right._Inner` should always has the built-in meaning and thus the result should always be a `bool` prvalue. Otherwise, the program is already ill-formed, possibly no diagnostic required.

So, I think we can directly use `noexcept(_Left._Outer == _Right._Outer && _Left._Inner == _Right._Inner)` instead, which possibly slightly improves compiler throughput.

----
This issue is intended for a new contributor (especially one new to GitHub) to get started with a simple change.

Please feel free to submit a pull request if there isn't one already linked here - no need to ask for permission! 😸

You can (and should) link your pull request to this issue using [GitHub's close/fix/resolve syntax](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
(in the PR description not the commit message)

**Comment by CaseyCarter** [comment]
I agree with your analysis; there's no need for us to validate that copy-initializing a `bool` from a `bool` doesn't throw. We can safely drop this particular `_Fake_copy_init<bool>`.
