### ISSUE TITLE
<yvals.h>: _CONTAINER_DEBUG_LEVEL mismatch?

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#441]
https://github.com/microsoft/STL/blob/2989323bdc47a5e0eac4537a862f8c06f503d6fe/stl/inc/yvals.h#L169-L175

`_CONTAINER_DEBUG_LEVEL` doesn't affect layout, so we didn't think it needed `#pragma detect_mismatch`. We were wrong. If someone has requested lightweight security checks, they'll be surprised if they don't get them just because they linked in a separately compiled static library.

**Comment by BillyONeal** [comment]
This defeats the entire purpose of `_CONTAINER_DEBUG_LEVEL`.

**Comment by StephanTLavavej** [comment]
I was just talking to Joe Bialek who (IIRC) originally requested `_CONTAINER_DEBUG_LEVEL` and he was *very* surprised about the static linking implications.

The setting of `_CONTAINER_DEBUG_LEVEL` can differ across EXEs/DLLs with C++ interfaces (unlike IDL), but within a binary, it needs to be consistent, otherwise there was literally no point in implementing it. It's for lightweight *security checks*, so if those don't end up enabled, we're providing a false sense of security.

**Comment by BillyONeal** [comment]
In that case Joe will be just as surprised given that existing TUs / static libs won't have the detect mismatch. If he wants an assertion that it's turned on in all TUs I think he should add a BinSkim rule that looks for it.

**Comment by StephanTLavavej** [comment]
D’oh, that’s a great point for string_view etc. (At least span is new.) I think we need to rethink this thing.

**Comment by StephanTLavavej** [comment]
Idea: We could introduce template parameters with default arguments to force different name mangling, although we'd need to think about possible linker errors. (In general, changing Standard Library member function signatures is something we can do.)

We also need to worry about string, string_view, vector, span, etc. instantiations in the STL's own static lib.

**Comment by StephanTLavavej** [comment]
After looking into this, we've decided against making any changes to this behavior.
