### ISSUE TITLE
Is it joke?

### ISSUE THREAD

**Issue by kelbon** [microsoft/STL#4411]
Ok, now msvc have [[msvc::no_unique_address]]. Okay. But why it has same problem as EBO does (and msvc dont want to fix EBO with > 1 base because it ABI break or smth)
But why [[msvc::no_unique_address]] have same issue?!?!
https://godbolt.org/z/6d7x6Exxh
```cpp

struct E {};
struct E1 {};
struct __declspec(empty_bases) abc : E {
    char a;
    [[msvc::no_unique_address]] E1 e;
};

int main() {
    static_assert(sizeof(abc) == 1); // static assert failed!
}
```

Its even does not fixable by __declspec(empty_bases)!!

I have this issue in real code

Both gcc and clang correctly handle this (but for some reason two fields with [[no_unique_address]] does not produce empty type)

https://godbolt.org/z/1GTPsshdq

**Comment by AlexGuteniev** [comment]
This is STL (the MSVC Standard Library) repo.
Report MSVC compiler bugs to [Developers Community](https://developercommunity.visualstudio.com/cpp).

**Comment by kelbon** [comment]
> This is STL (the MSVC Standard Library) repo. Report MSVC compiler bugs to [Developers Community](https://developercommunity.visualstudio.com/cpp).

Unfortunately, it will be ignored atleast 6 month if reported to Developers Community

**Comment by frederick-vs-ja** [comment]
DevCom-10588147 opened. Note that clang-cl behaves well, and there's nothing can be done for this in a library implementation.

**Comment by fsb4000** [comment]
Yes, this is a bug. clang-cl supports your code: https://godbolt.org/z/os18Eh4M7 so probably you can use clang-cl for your project for now.
I will search if there is an open issue at Devcom about it.

**Comment by kelbon** [comment]
> you can use clang-cl 

im writing library for all 3 compilers, this is exactly place where this breaks expected layout for my struct
https://github.com/kelbon/AnyAny/blob/65c7a77f64a52881981ebee84eb31610fe6e7db9/include/anyany/anyany.hpp#L1109

Empty base, potentially empty allocator and i need allocator to be last in fields (for cache, most unused field), and i cannot inherit it (even private inheritance may break overload resolution, in this case it will really break overload resolution for operator==() )

**Comment by StephanTLavavej** [comment]
Thanks for properly reporting this to the compiler team, @frederick-vs-ja.

@kelbon, I understand your frustration, but *please* don't report compiler bugs to the STL repo. That creates more work for us, slowing down our ability to deliver STL features and fixes, and won't get you compiler fixes any sooner.
