### ISSUE TITLE
`std::replace` vectorization and redundant writes

### ISSUE THREAD

**Issue by AlexGuteniev** [microsoft/STL#4433]
## Vectorization non-options

Vectorized `replace` algorithm would write to its source.

To preserve the existing elements with only replacing some in a single vector register, one of these approaches could be used:
1. Masked stores
2. Element-wise stores
3. Storing the old elements along with replaced elements

Before AVX512, masked stores are only for 32 and 64 sized elements and only for AVX2: `mm_maskstore_epi32`, `_mm256_maskstore_epi32`, `_mm_maskstore_epi64`, `_mm256_maskstore_epi64`. The SSE2 `_mm_maskmoveu_si128` is not suitable due to a non-temporal memory hint. So, only AVX2 and only large element size is not a full set.

Element-wise stores will defeat the purpose of vectorization, at least the most of it, since the scalar replacement is fast, and need to do several elements at once to outperform it.

## Redundant writes caveat

So having to resort to redundant writes. That is computing a vector with preserved and replaced elements, and writing it at once.

Redundant writes are not transparent, in a sense that one can pass read-only array with no elements to be replaced, and expect no crashes. With sophisticated `VirtualAlloc`/`VirtualProtect` use, only a part of array can be read only. This makes arbitrary redundant writes non-transparent. 

There's a sophisticated approach possible to make the redundant element writes transparent. We can align the pointer at the beginning, and then store only when we have something to replace. So we still have redundant writes, but within the same page we would normally write, so these are transparent.

Sure the sophisticated approach adds complexity to maintain.

## ✨  Compiler magic! ✨

If instead of this:
https://github.com/microsoft/STL/blob/8b081e26ba016970ce3338cb483ff10f2ade30a5/stl/inc/algorithm#L3707-L3711

We would use `*_UFirst =  *_UFirst == _Oldval ?_Newval : *_UFirst`, to enable these redundant writes, the compiler would auto-vectorize the algorithm almost perfectly. I created DevCom-10606365 to improve codegen, but the improvement effect is small. 

So we can just specialize the algorithm with `if constexpr` for proper types, if we accept these redundant stores.

## Are redundant stores indeed harmful?

I dunno.

From the standard perspective, I'm not a language lawyer.

From the beyond standard perspective, assuming standard permits redundant stores, I think these are fine: there's no realistic use case that would rely on read-only array modifying attempt being successful if no modification happens.

From performance perspective, they might be potentially slightly harmful, but the benefit from vectorization clearly outweighs this potential harm

## So the question is

Can vectorized `std::replace` have non-transparent redundant writes?

**Comment by StephanTLavavej** [comment]
We talked about this at the weekly maintainer meeting and although we couldn't immediately point to any obvious badness that this would cause, we're uncomfortable with synthesizing a bunch of stores that wouldn't ordinarily be emitted, regardless of whether it's hand-vectorized or auto-vectorized after library changes to emit unconditional writes (of a conditional operator). There are potential concerns with really squirrely code trying to read elements from other threads that "shouldn't" be changed by the algorithm (even to their own values), or potential power consumption etc. effects of emitting a bunch of stores (again, even if the values are actually unchanged).

At this time we don't want to make any changes here. Thanks for bringing this topic up!

**Comment by AlexGuteniev** [comment]
I think I found how it is ruled out by the standard. [`[algorithms.requirements]/3`](https://eel.is/c++draft/algorithms#requirements-3) says:

> For purposes of determining the existence of data races, algorithms shall not modify objects referenced through an iterator argument unless the specification requires such modification[.](https://eel.is/c++draft/algorithms#requirements-3.sentence-1)

It is possible to imagine scenarios that have data races which exist only with redundant writes.
