### ISSUE TITLE
Improve `std::count` vectorization

### ISSUE THREAD

**Issue by AlexGuteniev** [microsoft/STL#4456]
I noticed from DevCom-10610716 and DevCom-10553384 that MSVC tries to auto-vectorize element counting.

I observe that the following is auto-vectorized for every `int_type` given that `size_type` is of the same size:
```c++
using int_type = int;
using size_type = int_type;

size_type count(int_type* b, int_type* e, int_type v)
{
    size_type r = 0;
    for (;b!=e;++b){
        if (*b == v){
            ++r;
        }
    }
    return r;
}
```
See https://godbolt.org/z/Yxx5e3foz

The algorithm is not the same as in `vector_algorithms.cpp`, specifically, it counts in vector registers, rather than general-purpose registers, hence the limitation of same elements size.

This leads to `std::count` and `ranges::std::count` being auto-vectorized with `/D_USE_STD_VECTOR_ALGORITHMS=0`
 * On x64 for element size 8, beating `__std_count_trivial_8` slightly
 * On x86 for element size 4, beating `__std_count_trivial_4` almost twice
 
**The current compiler-generated code is likely to be incorrect**, as the DevCom-10610716 and DevCom-10553384 are respectively about 8 and 4 element size implementation of this, and the issues are only `Fixed - Pending Release`. Still the whole approach looks like valid.

The approach of auto-vectorization can potentially scale towards supporting standard size type for each element size.
So we have few options to improve over existing `std::count` vectorization:
 * Wait for the compiler to auto-vectorize even mismatching element size, then drop `std::count` manual vectorization. Can wait passively, or create yet another DevCom issue. It may be too much to expect.
 * Reimplement the approach from the complier-generated code in `vector_algorithm.cpp`. Either same-element-size, or generalized version. Sure this would make the algorithm more complex. Not like `minmax_element`, but still more complex than the current `count`.
 * Reimplement `count` in headers, so that it counts portions to to the same size counter as element size, and then accumulates to destination count. So that compiler auto-vectorizes the inner counting. "This is gross".

(I'm not inclined to do anything about this in the near time, especially as there are some recent changes in the compiler in this area, and also because there are some more useful optimization and non-optimization things to do. Just recording the observation).

**Comment by StephanTLavavej** [comment]
Thanks for this analysis. We talked about this at the weekly maintainer meeting and it doesn't sound like it's worth investing much effort into (we're not super enthusiastic about x86-only perf gains).

**Comment by AlexGuteniev** [comment]
I'm afraid I wasn't able to convey the variety of options clearly here.

Reasonable options would improve x64 cases too. Specifically
 * The compiler can be improved to auto-vectorize for any combination of counter size / element size
 * Our implementation can use the approach currently attempted by the compiler in particular cases, but extended to all cases
 * We can make a workaround in headers, so that compiler would auto-vectorize cases that it doesn't now

All of them add more complexity than simpler options.

**Comment by AlexGuteniev** [comment]
> ..............that ... _technically works_ I guess, but it sounds high grade stupid

 -- @Alcaro on the current `std::count` manual vectorization approach

**Comment by AlexGuteniev** [comment]
I see that this issue was phrased in a complex way, and now after the implementation of #4614 and some follow up investigation, I can rephrase it simpler. See the new issue #4653
