### ISSUE TITLE
`<atomic>`: With `_STD_ATOMIC_ALWAYS_USE_CMPXCHG16B` defined to `1`, `atomic_ref<16 bytes>` does not report `is_lock_free` and `is_always_lock_free` correctly

### ISSUE THREAD

**Issue by AlexGuteniev** [microsoft/STL#4472]
With `_STD_ATOMIC_ALWAYS_USE_CMPXCHG16B` defined to `1` on x64, `atomic_ref<16 bytes>` reports `is_lock_free` and `is_always_lock_free` as both `false`. It should be both `true`.

**Comment by StephanTLavavej** [comment]
Thanks for noticing this bug. It's definitely a problem for ARM64, where this mode is always active:

https://github.com/microsoft/STL/blob/d6efe9416e4ad7d6e245ae9e96023d413794d1eb/stl/inc/yvals.h#L316-L330

At first I thought that `is_lock_free()` might be correct, but the code that checks `_ATOMIC_HAS_DCAS` and `__std_atomic_has_cmpxchg16b()` is just completely disabled, which is super wrong for ARM64 too:

https://github.com/microsoft/STL/blob/d6efe9416e4ad7d6e245ae9e96023d413794d1eb/stl/inc/atomic#L2169-L2184

We definitely need to fix this as it impacts ARM64. It would be nice to get rid of this mode and always use the new instruction for x64, but it's probably not possible to do that at this time. (We know for a fact that we must continue supporting SSE2-only processors that lack SSE4.2; cmpxchg16b is different but IIRC support for it appeared around the same time.)
