### ISSUE TITLE
<xstring>: constexpr string does not compile with -d1initall

### ISSUE THREAD

**Issue by tiagomacarios** [microsoft/STL#4473]
The following code stopped compiling when d1initall is enabled.
https://godbolt.org/z/9EW3z1s5P
```
#include <string>

constexpr bool f() noexcept {
    std::string gate_name{"aaaaaaaaaaaaaaaaaaaaaa"};
    return true;
}

constexpr bool b = f();
```
Godbolt shows the regression starting in v19.38. Cameron helped me track the regression to [PR 490538: Port 14 GitHub PRs: GH-3939, GH-3900, GH-3935, GH-3912, GH-3927, GH-3936, GH-3862, GH-3903, GH-3904, GH-3920, GH-3921, GH-3930, GH-3933, GH-3934](https://devdiv.visualstudio.com/DevDiv/_git/msvc/pullrequest/490538).

**Comment by AlexGuteniev** [comment]
Suspect this is GH-3862 , and in particular this uninitialized pointer:

https://github.com/microsoft/STL/blob/d6efe9416e4ad7d6e245ae9e96023d413794d1eb/stl/inc/xstring#L2618-L2624

The `-d1initall1023 -d1initAll:FillPatternE` switches don't like that

**Comment by tiagomacarios** [comment]
Your suggested fix works.
We are currently using 19.38.33135 which ICEs with the fix. The last released version 19.39.33522 works correctly.

**Comment by CaseyCarter** [comment]
> The following code stopped compiling when d1initall is enabled. https://godbolt.org/z/9EW3z1s5P

Well, I suppose it's a good thing that option isn't documented, or we'd have a bug! =P

**Comment by AlexGuteniev** [comment]
It looks like that it is a bug in these options, I'd expect delay initialized pointer to compile

**Comment by frederick-vs-ja** [comment]
Reduced example ([Godbolt link](https://godbolt.org/z/s679Wa75j))
```C++
constexpr bool fun()
{
    char* p [[maybe_unused]];
    return true;
}

constexpr bool b = fun();
```

Filed DevCom-10614520.

**Comment by AlexGuteniev** [comment]
DevCom-10614520 is _Fixed - pending release_.

Should we keep the initialization or pull it out later?

**Comment by tiagomacarios** [comment]
Just keep it.
