### ISSUE TITLE
P3107R5 Permit An Efficient Implementation Of `<print>`

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#4509]
WG21-P3107R5 Permit An Efficient Implementation Of `<print>`
WG21-P3235R3 `std::print` More Types Faster With Less Memory

**INCREASED** feature-test macro:
```cpp
#define __cpp_lib_print 202406L
```

These papers were formally accepted as Defect Reports, retroactively amending C++23.

**Comment by frederick-vs-ja** [comment]
`_fputc_nolock` and `_fwrite_nolock` of UCRT seem useful here. However, they still create a `__crt_cached_ptd_host` guard object for each call, and such overhead seems significant for `_fputc_nolock`. I wonder whether we can furtherly optimize the underlying calls.
