### ISSUE TITLE
P3142R0 Printing Blank Lines With `println()`

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#4524]
WG21-P3142R0 Printing Blank Lines With `println()`

No feature-test macro is mentioned.

* This feature is really simple.
* It doesn't introduce any new identifiers, so there's no real potential for conflict.
* Nobody has finished C++23 yet.

Although this wasn't formally accepted as a Defect Report, I've reached out to libstdc++ and libc++'s maintainers, and everyone agrees that we should implement this "downlevel" in C++23 mode.

**Comment by H-G-Hristov** [comment]
@StephanTLavavej Would you please assign this to me as my first contribution to MS STL?

**Comment by StephanTLavavej** [comment]
@H-G-Hristov Sure, we look forward to your PR! :smile_cat:
