### ISSUE TITLE
Vector algorithms with element size dispatch: standardize dispatching?

### ISSUE THREAD

**Issue by AlexGuteniev** [microsoft/STL#4531]
Currently a scheme like `__std_find_trivial` -> `__std_find_trivial_1/2/4/8` -> `__std_find_trivial_impl`
With these exceptions:
 * Some like  `__std_reverse_trivially_swappable_1/2/4/8` don't have neither header dispatcher (so they are dispatched in multiple places), nor `vector_algorithms.cpp` common implementation
 * Some `.cpp` implementations are unified under names `_Minmax` and `_Minmax_element`

Should we unify that?

**Comment by AlexGuteniev** [comment]
I propose the following:
 * Unify `.cpp` names to `_impl` (including `_Minmax_element` -> `_minmax_element_impl`
 * Don't unify whether there is common `vector_algorithms.cpp` implementation or not, keep this as it is
 * Unify header dispatch to like `_Find_trivial`, so that `_STD __std_find_trivial` becomes `_STD _Find_trivial` and does not repeat "std"
 * Unify to having header dispatch in a separate function if there are multiple usage and to not having it when there is a single usage

**Comment by StephanTLavavej** [comment]
We talked about this at the weekly maintainer meeting; @barcharcraz and I agree with all of your proposals.
