### ISSUE TITLE
Surprising behaviour with std::ranges::views::pairwise and std::ranges::to

### ISSUE THREAD

**Issue by davidhunter22** [microsoft/STL#4548]
This is with VS 17.10 Preview 2. I have not tried other compilers/versions.

So this may not be a bug but it was very surprising to me, and the compiler error is extremely unhelpful.
So I have the following code

```
void test( )
{
    struct Foo { };

    Foo foos[] { Foo { }, Foo { } };

    struct FooTuple1 { FooTuple1( std::tuple<Foo,Foo> ) { } };
    struct FooTuple2 { FooTuple2( std::tuple<Foo&,Foo&> ) { } };

    // This gives a compiler error "error C2338: static_assert failed: 'the program is ill-formed per N4950 [range.utility.conv.to]/2.3'"
    auto foo_tuples1 { foos | std::ranges::views::pairwise | std::ranges::to<std::vector<FooTuple1>>( ) };

    // This compiles fine and does what I expect
    auto foo_tuples2 { foos | std::ranges::views::pairwise | std::ranges::to<std::vector<FooTuple2>>( ) };

    // A std::tuple<Foo,Foo> is constructible from a std::tuple<Foo&,Foo&>
    std::tuple<Foo&,Foo&> p { foos[ 0 ], foos[ 1 ] };
    std::tuple<Foo,Foo> q { p };
}
```

So I'm trying to create a range of FooTuple1 objects containing adjacent pairs of Foo objects.
However the line where I try to do that gives and error referencing a portion of the C++ standard. Sadly I don't read standardeze!

If I try to do this with a FooTuple2 which takes a std::tuple<Foo&,Foo&> it works. I find this very odd as  std::tuple<Foo,Foo> is constructable from a std::tuple<Foo&,Foo&> so why can't ranges::to call the constructor that takes one of those?

So is this really the intended behavior?  If this is what the standard mandates it seems like a unfortunate limitation to me.

**Comment by cpplearner** [comment]
The standard requires `convertible_to<range_reference_t<R>, range_value_t<C>>` ([\[range.utility.conv.to\]/(2.1)](https://eel.is/c++draft/range.utility.conv.to#2.1)), but `std::tuple<Foo&,Foo&>` is not implicitly convertible to `FooTuple1`, because two conversions are required: `std::tuple<Foo&,Foo&>` -> `std::tuple<Foo,Foo>` -> `FooTuple1`, but at most one can occur in implicit conversion (unlike explicit construction).

**Comment by davidhunter22** [comment]
Thanks cppleaner. I was under the impression that `std::ranges::to<std::vector<FooTuple1>>( ) ` actually calls
the constructor of `FooTuple1` explicitly so you would get a call `FooTuple1 {  std::tuple<Foo&,Foo&> }` which would then only require the on conversion `std::tuple<Foo&,Foo&>` to `std::tuple<Foo,Foo>`

**Comment by StephanTLavavej** [comment]
Thanks @cpplearner! We agree; closing this issue.
