### ISSUE TITLE
LWG-3738 has not been implemented?

### ISSUE THREAD

**Issue by hewillk** [microsoft/STL#4549]
[LWG 3738](https://cplusplus.github.io/LWG/issue3738) is recorded as NA in already-closed [Meta LWG issue: 2022-11 meeting](https://github.com/microsoft/STL/issues/3214), It never seems to add the proposed wording though, not sure if this is an oversight.

```cpp
#define _CONTAINER_DEBUG_LEVEL 2
#include <ranges>

constexpr auto take = std::ranges::take_view(std::views::single(0), -11); // ok
constexpr auto drop = std::ranges::drop_view(std::views::single(0), -11); // error
```
https://godbolt.org/z/4oMqG6rG1

**Comment by frederick-vs-ja** [comment]
I don't think there's anything to be implemented.

See [[expr.const]/6.1](https://eel.is/c++draft/expr.const#6.1):

> It is unspecified whether _E_ is a core constant expression if _E_ satisfies the constraints of a core constant expression, but evaluation of _E_ would evaluate
> - an operation that has undefined behavior as specified in [library] through [thread],
