### ISSUE TITLE
validate.cpp: static_assert is_sorted() for the lookup tables

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#455]
When VS 2019 16.6 Preview 1 is available, the shipping toolset will support #6 `constexpr` `is_sorted()`. At that time, this will become a "good first issue".

1. We'll need to build the tools with `/std:c++latest`. This is accomplished by telling CMake to use C++20 instead of C++17:

https://github.com/microsoft/STL/blob/a46d897ac0b271bee59aca556f62e16bdb58ef19/tools/CMakeLists.txt#L7

2. Then we can remove this comment ("TRANSITION" means "TODO" for us), and change each `assert` to `static_assert`:

https://github.com/microsoft/STL/blob/a46d897ac0b271bee59aca556f62e16bdb58ef19/tools/validate/validate.cpp#L174-L177

(Related to #224.)

**Comment by BillyONeal** [comment]
There's no reason the tools can't use the live STL headers.

**Comment by StephanTLavavej** [comment]
Mixing live headers with installed libs would be doom. Doom!

**Comment by BillyONeal** [comment]
I mean, it wouldn't be a supported configuration but the only people it might break would be ourselves

**Comment by StephanTLavavej** [comment]
I'm wary of introducing little bits of weirdness - such things accumulate and make systems difficult to deal with. Waiting is simpler.

**Comment by BillyONeal** [comment]
Sure! Wasn't saying "do this thing", was only saying "consider this thing" :)

**Comment by bhardwajs** [comment]
@StephanTLavavej - I can work on this issue. Should I assign this to myself?

**Comment by StephanTLavavej** [comment]
Thanks! You can just submit a pull request - we don't usually assign issues to devs outside the vclibs team. A comment is sufficient to indicate to other readers that you're working on an issue.

**Comment by bhardwajs** [comment]
Great. Will submit a pull request.
