### ISSUE TITLE
operator delete calls _free_dbg(_UNKNOWN_BLOCK) in debug builds and it crashes when the user has replaced malloc() and free()

### ISSUE THREAD

**Issue by ldorau** [microsoft/STL#4564]
# Describe the bug

`operator delete` calls `_free_dbg(_UNKNOWN_BLOCK)` in the Debug build (when `_DEBUG` is defined) and it crashes when the user has replaced `malloc()` and `free()` (all works well in the Release build).

See: https://github.com/oneapi-src/unified-memory-framework/issues/350
See: https://github.com/microsoft/STL/issues/1066#issuecomment-885185917

# Expected behavior

`malloc()` and `free()` can be replaced in the Debug build and both work well after being replaced.

# STL version

NMAKE  Microsoft (R) Program Maintenance Utility Version 14.35.32216.1
and
MSBuild version 17.5.1+f6fdcf537 for .NET Framework

**Comment by AlexGuteniev** [comment]
Is this the same as #1066 ?

**Comment by ldorau** [comment]
> Is this the same as #1066 ?

I am not sure, because it has nothing to do with `<xlocinfo>` nor `_free_crt_t` nor `_free_base`.

It all about calling `_free_dbg` inside the `operator delete` (in `delete_scalar.cpp`):
```c
_CRT_SECURITYCRITICAL_ATTRIBUTE
void __CRTDECL operator delete(void* const block) noexcept
{
    #ifdef _DEBUG
    _free_dbg(block, _UNKNOWN_BLOCK);
    #else
    free(block);
    #endif
}
```

like described in details in https://github.com/oneapi-src/unified-memory-framework/issues/350

**Comment by ldorau** [comment]
The callstack can be found in https://github.com/oneapi-src/unified-memory-framework/issues/350

![image](https://github.com/microsoft/STL/assets/8492895/c51fa889-555b-4dbc-a7e5-95b4e4ca2548)

The trace comes from the gtest's internals (`TEST_F()`) during calling the string's destructor.

**Comment by fsb4000** [comment]
>malloc() and free() can be replaced in the Debug build and both work well after being replaced.

Sorry, we don't support replacing malloc/free.

Old chat: https://discord.com/channels/737189251069771789/737189251497721887/867839945111371866
![изображение](https://github.com/microsoft/STL/assets/4289847/101f656c-5c0d-400c-b136-e8c212474238)
![изображение](https://github.com/microsoft/STL/assets/4289847/3233772d-1c1c-443b-a7db-c6c6c042967b)
![изображение](https://github.com/microsoft/STL/assets/4289847/c3ae8187-7cb1-4cbc-9120-a3d838bf326b)

**Comment by ldorau** [comment]
> > malloc() and free() can be replaced in the Debug build and both work well after being replaced.
> 
> Sorry, we don't support replacing malloc/free.
> 

@fsb4000 Thanks a lot!

**Comment by fsb4000** [comment]
Yeah, take a look at https://github.com/microsoft/STL/issues/1066#issuecomment-885185917

Although we don't support replacing malloc/free, we will change vcruntime when there is an ABI-breaking release of Visual Studio.
![изображение](https://github.com/microsoft/STL/assets/4289847/9e80de5c-69ba-4306-b5ea-318d7e36fed0)

**Comment by ldorau** [comment]
> > > malloc() and free() can be replaced in the Debug build and both work well after being replaced.
> > 
> > 
> > Sorry, we don't support replacing malloc/free.
> 
> @fsb4000 Thanks a lot!

@fsb4000 you don't support replacing malloc/free, but it seems that it can be done anyway?

https://github.com/microsoft/mimalloc/blob/8f7d1e9a41bb0182166aac6a8d4d8b00f60ed032/doc/mimalloc-doc.h#L1153-L1179

**Comment by ldorau** [comment]
See also [Overriding Standard Malloc](https://github.com/microsoft/mimalloc/tree/8f7d1e9a41bb0182166aac6a8d4d8b00f60ed032?tab=readme-ov-file#overriding-standard-malloc)

**Comment by jblazquez** [comment]
@fsb4000, is that Discord channel you linked to public, or is it an internal MSFT Discord?

**Comment by fsb4000** [comment]
@jblazquez , public, invite link: https://discord.gg/9yaYy5SY
