### ISSUE TITLE
Ranges and lambdas weirdness

### ISSUE THREAD

**Issue by samsinsane** [microsoft/STL#4569]
I think this fits with the on-topic questions, apologies if it doesn't.

There's a little bit more to this question than the title suggests, but I'll start with a code snippet that shows the problem:
```c++
struct A{};
std::array<A, 1> arr;
auto filterFn = [](auto el) {
  (void)std::get<A&>(el);
  return true;
};
auto filteredZip = std::views::zip(arr) | std::views::filter(filterFn);
```
This fails to compile in Clang, GCC and MSVC. The offending line being `std::get<A&>`. All three error outputs suggest that `el` is of type `std::tuple<A>`.

We can output the result of `std::is_same_v<decltype(el), std::tuple<A>>` and it will be false. We can also `static_assert(std::is_same_v<decltype(el), std::tuple<A&>>)` and it will fail indicating that `decltype(el)` is `std::tuple<A>`, but we can also `static_assert(std::is_same_v<decltype(el), std::tuple<A>>)` and that will fail indicating that `decltype(el)` is `std::tuple<A&>`. So, `el` is both of type `std::tuple<A&>` and `std::tuple<A>`, but the latter instantiation doesn't execute.

We can change `auto el` to `std::tuple<A&> el` and it compiles. We could also change `std::get<A&>` to `std::get<0>` and it compiles. However, both of these changes reduce the reusability of the function, and additionally, `auto el` is more portable as Clang and GCC both use `std::pair` when there are two ranges zipped together, while MSVC uses `std::tuple`.

Another change we can make is adding `-> bool` to the lambda. Which for some reason prevents this problem on all three compilers.

We could also just call `filterFn` while iterating the zipped array but that prevents us from sharing a filtered view:
```c++
for (auto el : std::views::zip(arr))
{
  if (!filterFn(el))
    continue;
}
```

Since all three compilers behave the same way, I assume this can't be an implementation bug or quick and as far as I can tell it's all valid C++. So, my question is, why doesn't the snippet above work as I expected? I guess secondary to this, why does `-> bool` have any impact on the issue?

**Comment by cpplearner** [comment]
`filter` requires a `indirect_unary_predicate`, which requires the predicate to be callable with different types of arguments, and return a boolean-testable type in each case.

With `-> bool`, the lambda body is not instantiated when checking the return type, so the validity of `std::get<A&>(el)` is not checked by the concept.

Blame the authors of ranges-v3 for the design of `indirect_unary_predicate` :)

**Comment by StephanTLavavej** [comment]
On a related note, I just filed #4575 because the diagnostic for bogus get-by-type is very confusing.

**Comment by samsinsane** [comment]
Thank you for the responses, really appreciate the time you both spent on this.

@StephanTLavavej @CaseyCarter If there's nothing else to be actioned on your end, I'm happy for this to be closed off.

**Comment by StephanTLavavej** [comment]
Sounds good to me! Casey offered to provide additional clarification if necessary but if you're happy then we're happy.
