### ISSUE TITLE
`<utility>`: Side effects in self-swaps of `pair` are skipped

### ISSUE THREAD

**Issue by frederick-vs-ja** [microsoft/STL#4597]
# Describe the bug
Currently, self-swaps of `pair` are no-op:

https://github.com/microsoft/STL/blob/9aca22477df4eed3222b4974746ee79129eb44e7/stl/inc/utility#L441-L460

However, the _Cpp17Swappable_ requirements ([[swappable.requirements]](https://eel.is/c++draft/swappable.requirements)) doesn't seem to exclude self-swaps or side effects in them, and no special case is specified for self-swaps of `pair`.

Perhaps we should just unconditionally swap members.

# Command-line test case
[Godbolt link](https://godbolt.org/z/5hqE8naET).
```C++
#include <utility>

struct swap_counter {
    unsigned int* pcnt_ = nullptr;

    friend constexpr void swap(swap_counter& lhs, swap_counter& rhs) noexcept
    {
        std::swap(lhs.pcnt_, rhs.pcnt_);
        if (lhs.pcnt_ != nullptr)
            ++*lhs.pcnt_;
        if (rhs.pcnt_ != nullptr)
            ++*lhs.pcnt_;
    }
};

static_assert([]
{
    unsigned int cnt{};
    std::pair<swap_counter, int> pr{swap_counter{&cnt}, 0};
    pr.swap(pr);
    return cnt == 2u;
}());
```

# Expected behavior
The code snippet compiles.

**Comment by StephanTLavavej** [comment]
We looked at this during the weekly maintainer meeting and agree that the Standardese says we should be directly swapping both members without a self-address check.

@CaseyCarter remembered that this is vaguely related to #1485 but is distinct.
