### ISSUE TITLE
`std::isfinite` poor codegen with Microsoft STL + Clang

### ISSUE THREAD

**Issue by johnstiles-google** [microsoft/STL#4609]
I work on Skia. I recently attempted to replace our hand-rolled implementation of `std::isfinite` with the standard library version, trusting that a modern compiler's implementation would be equally efficient.

In practice, this led to a significant, measurable regression in our path-rendering code in clang-cl builds (which mixes Microsoft's STL with the Clang compiler). 

I believe the discrepancy comes from https://github.com/microsoft/STL/blob/main/stl/inc/cmath . There does not appear to be support for clang's `__builtin_isfinite`. Other Clang builtins are supported, however—there are special codepaths for [__builtin_ceilf](https://github.com/microsoft/STL/blob/main/stl/inc/cmath#L73), [__builtin_floorf](https://github.com/microsoft/STL/blob/main/stl/inc/cmath#L129), [__builtin_copysignf](https://github.com/microsoft/STL/blob/main/stl/inc/cmath#L83), and others. However, [isfinite](https://github.com/microsoft/STL/blob/main/stl/inc/cmath#L785) has no Clang builtin support, and ends up calling into `fpclassifyd` for each value, which is extremely expensive relative to the handful of instructions that a native `isfinite` needs.

I've filed this with our LLVM team ([buganizer](https://g-issues.chromium.org/issues/335901087?pli=1&authuser=0)) but they said they could not control it from their end.

**Comment by frederick-vs-ja** [comment]
> I've filed this with our LLVM team ([buganizer](https://g-issues.chromium.org/issues/335901087?pli=1&authuser=0)) but they said they could not control it from their end.

On MSVC. `std::isfinite` (at least for FP types) is ultimately provided MS UCRT, so the MSVC STL team and contributors cannot control it either.

As shown in #4537, we can fix this when `<cmath>` is included. But the issue still exists if only `<math.h>` is included.

**Comment by johnstiles-google** [comment]
That's fine. We're happy to #include `<cmath>` and use the namespaced `std::isfinite`.

**Comment by StephanTLavavej** [comment]
I can work on a fix.

**Comment by johnstiles-google** [comment]
That's great! Thank you.

**Comment by StephanTLavavej** [comment]
This fix is expected to ship in VS 2022 17.11 Preview 2. Thanks again for the report!

**Comment by johnstiles-google** [comment]
Thank you for the quick turnaround! Appreciate the support.
