### ISSUE TITLE
<array>: <array> includes too much stuff

### ISSUE THREAD

**Issue by BillyONeal** [microsoft/STL#462]
In @ned14 's recent STL header benchmark results, `<array>` stands out as the most expensive STL container header. See https://www.reddit.com/r/cpp/comments/eumou7/stl_header_token_parsing_benchmarks_for_vs2017/ . This is because `<array>` includes `<iterator>` (because `reverse_iterator` used to be in there?), `<tuple>` (because when we authored `<array>` the tuple interface wasn't in `<type_traits>` yet?), and `<algorithm>` (for `_Swap_ranges_unchecked`). These are needless overhead for the functionality `<array>` offers.

It probably would make sense to promote `_Swap_ranges_unchecked` to `<xutility>` or similar with all the other "optimized for trivial things" algorithms like `copy`,

**Comment by BillyONeal** [comment]
It might be nice to actually go further and make `<array>` includable without dragging in all of our allocator support machinery `<xutility>` currently drags in but that's a more substantial refactoring effort to break apart `<xutility>`.

**Comment by StephanTLavavej** [comment]
I'd like to see `<iterator>`, `<tuple>`, and `<algorithm>` avoided in one change, before considering whether we should disentangle `<xutility>` and `<xmemory>`. I'm not really concerned about fractionating the `<array>` breaking changes into two smaller doses; instead I am concerned about disrupting every other STL header.

**Comment by BillyONeal** [comment]
That sounds fair to me
