### ISSUE TITLE
Is it by design that `<string_view>` provides most contents of `<string>`?

### ISSUE THREAD

**Issue by frederick-vs-ja** [microsoft/STL#4625]
MSVC STL's `<string_view>` currently directly includes `<xstring>`, which provides most contents of `<string>`.

I think it's OK for `<string>` to include `<string_view>` (since C++17). But when one only includes `<string_view>`, perhaps it's sometimes expected that no mechanism of dynamic allocation is made available.

If the status quo is not by design, I think we may extract the mechanisms of `char_traits` into a new internal header and make `<string_view>` slimmer.

**Comment by StephanTLavavej** [comment]
We talked about this at the weekly maintainer meeting and we don't remember why it was done this way. Extracting both `char_traits` and `basic_string_view` into an internal header (above `<xstring>`, e.g. `<__msvc_string_view.hpp>`) would allow `<string_view>` to avoid dragging in `basic_string`. We don't expect that extracting `char_traits` by itself would be useful, as any usage of `char_traits` is virtually certain to need either `basic_string_view` or `basic_string`.
