### ISSUE TITLE
`<numeric>`: `std::reduce` is missing `static_assert` for Mandates

### ISSUE THREAD

**Issue by hewillk** [microsoft/STL#4649]
```cpp
#include <vector>
#include <string>
#include <numeric>
#include <execution>

struct Op {
  int operator()(int, std::string);
};

int main() {
  std::vector<std::string> v;
  return std::reduce(v.begin(), v.end(), 0, Op{});
}
```

https://godbolt.org/z/5T4cn95nv

According to the current wording, the above should be rejected as `std::reduce` has the following _Mandates_ ([[reduce]](https://eel.is/c++draft/reduce#5)): 

> _Mandates_: All of
> (5.1) - `binary_op(init, *first)`,
> (5.2) - `binary_op(*first, init)`,
> (5.3) - `binary_op(init, init)`, and
> (5.4) - `binary_op(*first, *first)`
> are convertible to `T`.
> 

Not sure if `std::transform_reduce` has the same issue.

**Comment by frederick-vs-ja** [comment]
Duplicate of #4573 and #891?

**Comment by hewillk** [comment]
> Duplicate of #4573 and #891?

Yap, I think you are correct.
