### ISSUE TITLE
<span>: Consider working around LLVM-44627

### ISSUE THREAD

**Issue by CaseyCarter** [microsoft/STL#466]
At this time, the Clang 10 branch compiler does not correctly find comparison operator functions with reversed argument order via argument dependent lookup (See LLVM-44627). This will break much of `<compare>`, which I'm less concerned about, and perhaps also break comparisons of `span::iterator` with `span::const_iterator`. If the Clang devs don't decide to fix this bug before releasing version 10, we'll have a bit of a mess on our hands and need to:

* Enable the fallback operators in the comparison categories in `<compare>`, as well as for `ranges::default_sentinel_t` and `ranges::unreachable_sentinel_t` in `<xutility>`.
* fix comparisons of `_Span_iterator<T>` with `_Span_iterator<const T>`.

**Comment by StephanTLavavej** [comment]
If we need to work around this in the STL, we should do so before VS 2019 16.6 becomes feature complete; porting fixes after that point is possible, but extra work. I would prefer for Clang 10 to be fixed.

**Comment by StephanTLavavej** [comment]
Clang 10 has been fixed, so no changes are necessary in the STL.
