### ISSUE TITLE
unresolved external symbol __isa_available

### ISSUE THREAD

**Issue by fwf02** [microsoft/STL#4671]
hello im trying to use _Unsigned128 in kernel but im getting unresolved external symbol __isa_available which library needed to fix it?

**Comment by fwf02** [comment]
1>LIBCMT.lib(cpu_disp.obj) : warning LNK4257: object file was not compiled for kernel mode; the image might not run with  ignore all libraries to no

**Comment by fwf02** [comment]
update for now the driver loaded without issue from __isa_available nice ! but wonder if its cause issues in near future

**Comment by StephanTLavavej** [comment]
That's part of vcstartup, but what you're doing is currently unsupported.
