### ISSUE TITLE
`.gitignore`: Support more IDEs?

### ISSUE THREAD

**Issue by frederick-vs-ja** [microsoft/STL#4678]
In #4674, `/.idea` was accidently added to `.gitignore` and later removed.

Given there're already `.vs/` and `.vscode/`, is it better to add support for other IDEs, like CLion, in `.gitignore`?

**Comment by AlexGuteniev** [comment]
That would feel like a set of poles with different country flags near a hotel.
I mean I like the idea.

**Comment by StephanTLavavej** [comment]
We talked about this at the weekly maintainer meeting and we have no strong feelings about this. If someone is regularly using a third-party IDE with the STL and would like to gitignore a settings directory for it, then we would review such a change, but we don't think it's necessary to add pre-emptively.
