### ISSUE TITLE
compile STL error: Problem

### ISSUE THREAD

**Issue by ChenMiaoi** [microsoft/STL#4680]
# Describe the bug
I tried to compile the STL on windows11, but there was an error with incorrect SDK version information.But I do know that my environment should be complete and configured according to the compilation dependency requirements on the README.

![image](https://github.com/microsoft/STL/assets/96290967/6d0b9d49-8896-4c5f-bc5c-5d643d0acc3f)

# Expected behavior
I don't know if there is a problem with my SDK PATH, but I can confirm that my SDK version is displayed correctly on cmd.

# STL version
* Option 1: Visual Studio version
    ```
    Microsoft Visual Studio Community 2022
    Version 17.9.7
    ```
* Option 2: git tag version
    ```
    https://github.com/microsoft/STL/commit/900eeacb
    tag: vs-2022-17.9
    ```

# SDK version

![image](https://github.com/microsoft/STL/assets/96290967/d3dfabce-45d2-47a9-b3da-48b8ce1d38f7)

![image](https://github.com/microsoft/STL/assets/96290967/7a2f8b0e-b84c-4ac1-9ea7-f3235b1be653)

**Comment by AlexGuteniev** [comment]
After installing newer SDK I had to restart Windows to make CMake pick it up, maybe environment does not propagate somewhere

**Comment by ChenMiaoi** [comment]
maybe, but I restart some times, not work well, it's the same result, btw, my cmake version is 3.29.3

**Comment by cpplearner** [comment]
can you run `set INCLUDE` and `set WindowsSdkDir` and paste the output here?

**Comment by ChenMiaoi** [comment]
![image](https://github.com/microsoft/STL/assets/96290967/1f83da71-7d17-47dd-b284-0475021a1f8c)
this is SDK
![image](https://github.com/microsoft/STL/assets/96290967/7bed79f8-4f0e-4fb2-b46c-130090ab26a3)
this is include

**Comment by ChenMiaoi** [comment]
> can you run `set INCLUDE` and `set WindowsSdkDir` and paste the output here?

![image](https://github.com/microsoft/STL/assets/96290967/1f83da71-7d17-47dd-b284-0475021a1f8c)
this is SDK
![image](https://github.com/microsoft/STL/assets/96290967/7bed79f8-4f0e-4fb2-b46c-130090ab26a3)
this is include

**Comment by cpplearner** [comment]
Hmm, the SDK dir seems fine. The content of `INCLUDE` is truncated so I can't see whether it contains the SDK dir. 
(It should contain `D:\Windows Kits\10\include\10.0.22621.0\ucrt;D:\Windows Kits\10\\include\10.0.22621.0\\um;D:\Windows Kits\10\\include\10.0.22621.0\\shared`, among others.)

**Comment by ChenMiaoi** [comment]
> Hmm, the SDK dir seems fine. The content of `INCLUDE` is truncated so I can't see whether it contains the SDK dir. (It should contain `D:\Windows Kits\10\include\10.0.22621.0\ucrt;D:\Windows Kits\10\\include\10.0.22621.0\\um;D:\Windows Kits\10\\include\10.0.22621.0\\shared`, among others.)

```
INCLUDE=D:\Study\VS\VS\VC\Tools\MSVC\14.39.33519\include;D:\Study\VS\VS\VC\Tools\MSVC\14.39.33519\ATLMFC\include;D:\Study\VS\VS\VC\Auxiliary\VS\include;D:\Windows Kits\10\include\10.0.22621.0\ucrt;D:\Windows Kits\10\\include\10.0.22621.0\\um;D:\Windows Kits\10\\include\10.0.22621.0\\shared;D:\Windows Kits\10\\include\10.0.22621.0\\winrt;D:\Windows Kits\10\\include\10.0.22621.0\\cppwinrt;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um
```

I think the version is the same, 10.0.22621.0, should there be no impact on the sdk?

**Comment by AlexGuteniev** [comment]
Might be something cached. Try deleting generated files, `/out` dir and others if any

**Comment by ChenMiaoi** [comment]
> Might be something cached. Try deleting generated files, `/out` dir and others if any

Ok, I tried, and done, thanks
