### ISSUE TITLE
`<cassert>` has no include guard

### ISSUE THREAD

**Issue by ameerj** [microsoft/STL#4684]
When building LLVM for example, many files include `<cassert>`, resulting in lots of include churn relating to this header which can be mitigated with an include guard.

Is there a technical reason for the missing include guard for `cassert`?

https://github.com/microsoft/STL/blob/63354c3fa9c1fb2ab1fccb58c47d23c6af1c290f/stl/inc/cassert#L5-L7

**Comment by StephanTLavavej** [comment]
Yep, thanks @frederick-vs-ja.
