### ISSUE TITLE
P1007R3 assume_aligned()

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#47]
[P1007R3](https://wg21.link/P1007R3) `assume_aligned()`

This needs support from the compiler back-end, tracked by Microsoft-internal VSO-917620.

Feature-test macro as of WG21-N4842, added by WG21-P1902:
`#define __cpp_lib_assume_aligned 201811L`

**Comment by AlexGuteniev** [comment]
Is this still blocked?

**Comment by CaseyCarter** [comment]
> Is this still blocked?

No it is not. C1XX and Clang (and EDG, I think?) support `__builtin_assume_aligned`, `assume_aligned` is sitting latent in `<memory>`:

https://github.com/microsoft/STL/blob/212de15c590010c961c0e7bb4025f6fec89866c8/stl/inc/memory#L2947-L2955

waiting for someone to finish up the work. (Noted in passing: `_N0` is not a great template parameter name since it's in the `_RESERVED_MACRO_IDENTIFIER` space.)

**Comment by AlexGuteniev** [comment]
Aha, so is it Good First Issue now?

**Comment by CaseyCarter** [comment]
> Aha, so is it Good First Issue now?

More of a Good First Feature. "Good First Issue" is meant for things that are as simple and straightforward as possible - "Change these lines: .... to this: ..." - where the challenge comes from learning the engineering system. "Good First Issues" are loss leaders in that they take a maintainer more time to write up than they would to fix, but they hopefully make it easier to bring more maintainers into the fold.

_This_ issue, however, is more "enable the function, fix the parameter name that Casey doesn't like, whip up a smoke test, investigate if there's a feature-test macro to define and add the proposal to the list of C++20 stuff in `yvals_core.h`". It's no "Timezones and Calendars," but still a few steps above "Update `_MSVC_STL_VERSION`".

**Comment by StephanTLavavej** [comment]
I'll fix up the `_N0` problem throughout `stl/inc`.

**Comment by AlexGuteniev** [comment]
I don't see `__builtin_assume_aligned` works. 

I mean it is accepted by the compiler, but does not affect code generation.

**Comment by AlexGuteniev** [comment]
Ah, anyway you test in debug mode with `/Od`, so it cannot be tested.

I though the test is as follows:
 * Have a routine that does something simple, like integer sum - with `__builtin_assume_aligned` and without it.
 * Pass aligned and unaligned pointer, where its origin is erased via volatile global variable.
 * Only unaligned pointer on `__builtin_assume_aligned` throws SEH exception, other do not throw.

But I get aligned codegen optimization only if I pass something that has non-erased `alignas`.

**Comment by StephanTLavavej** [comment]
I don't think we should test what happens if we violate the intrinsic's preconditions (i.e. pass an unaligned pointer). A basic test should ensure that we can pass a properly aligned pointer, do a little work with it, and everything behaves as expected. We can compile with `/O2` for that, although that's almost never used in the STL's tests. (I'd have to look up whether our `launder` test found the compiler bug under `/O2`, or whether it happened even under `/Od`.)

Whether the optimizer takes advantage of this information, and in what situations, seems out of scope for the STL's test suite (i.e. it is perfectly reasonable to manually test and report bugs on Developer Community).

**Comment by AlexGuteniev** [comment]
I've reported DevCom-1121352 already, now I discovered even better case towards compiler shouldn't ignore this hint, added it as a comment there. Apparently a good `std` feature will be underimplemented without the proper compiler support.
