### ISSUE TITLE
CMakeLists.txt: Should we update the minimum required versions of CMake, Ninja, and Boost?

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#471]
[README.md](https://github.com/microsoft/STL/blob/master/README.md) currently says:

> Install CMake 3.15 or later, Ninja 1.8.2 or later

Also, we have version checks here:

https://github.com/microsoft/STL/blob/2bd2bd2db1dc1c7bc34616b7efc9bc4c73b70fdd/CMakeLists.txt#L4
https://github.com/microsoft/STL/blob/2bd2bd2db1dc1c7bc34616b7efc9bc4c73b70fdd/CMakeLists.txt#L10
https://github.com/microsoft/STL/blob/2bd2bd2db1dc1c7bc34616b7efc9bc4c73b70fdd/tools/CMakeLists.txt#L4

As of 2020-01-28, the latest versions are [CMake](https://cmake.org/download/) 3.16.3, [Ninja](https://github.com/ninja-build/ninja/releases) 1.10.0, and [Boost](https://www.boost.org/) 1.72.0.

After we merged #428 to update vcpkg, we're now building with Boost 1.72.0.

Should we update our minimum required versions to reduce our support matrix and avoid resolved issues in our dependencies?

**Comment by BillyONeal** [comment]
As we discussed in person on Wednesday I think whenever we bump the toolset version on the builders we should update these to whatever the latest ones are at that time.

**Comment by CaseyCarter** [comment]
> As we discussed in person on Wednesday I think whenever we bump the toolset version on the builders we should update these to whatever the latest ones are at that time.

Verifying my understanding: We bump the toolset version on the builders almost immediately after every release of a Visual Studio Preview with an updated toolset, which isn't every VS preview release.  The suggestion is that we should simultaneously update the versions of ninja, cmake to the most recent public release, and boost to "the version vcpkg currently installs"?

**Comment by BillyONeal** [comment]
Correct.

**Comment by BillyONeal** [comment]
I recorded this in the checklist for updating the toolset as standing policy: https://github.com/microsoft/STL/wiki/Checklist-for-Updating-Toolset-and-or-Dependencies
