### ISSUE TITLE
<span>: cross-type iterator operations are incomplete

### ISSUE THREAD

**Issue by CaseyCarter** [microsoft/STL#473]
C++20's symmetric comparison expression rewrites for `x op y` only work when:

* `op` is `!=` and `x == y` or `y == x` is valid, or
* `op` is `<`, `>`, `<=`, or `>=` and `x <=> y` or `y <=> x` is valid.

Let `i` be an iterator of type `span<int>::iterator` and `ci` an iterator of type `span<int>::const_iterator`. Currently, these are valid:

* `ci == i`
* `ci < i`
* `ci > i`
* `ci <= i`
* `ci >= i`

since `i` converts to `span<int>::const_iterator`. These are valid:

* `i == ci`
* `i != ci`
* `ci != i`

since they rewrite to the valid expressions `ci == i` or `!(ci == i)`. These:

* `i < ci`
* `i > ci`
* `i <= ci`
* `i >= ci`

are broken. 

`x - y` is never rewritten, so similarly `ci - i` is valid but `i - ci` is not.

**Comment by miscco** [comment]
HM that is correct and shows a clear lack of Tests. However, there is currently a paper for a NB comment about removing const_iterator from span. So should we wait that one week until Prague?

**Comment by miscco** [comment]
That said I would guess we would have to implement them as friends or is there some additional spaceship magic?

**Comment by miscco** [comment]
Hm that is strange, my test repro eats those anyway. Is that a compiler bug?
```cpp
#include "pch.h"

#include <array>
#include <span>

std::array<int, 10> iArr1 = { 0,  1,  2,  3,  4,  5,  6,  7,  8,  9 };
std::span<const int> s(iArr1);

TEST(IteratorComparison, EqualitySame) {
	ASSERT_TRUE(s.begin() == s.begin());
	ASSERT_TRUE(s.begin() != s.end());
}

TEST(IteratorComparison, EqualityDifferent) {
	ASSERT_TRUE(s.cbegin() == s.begin());
	ASSERT_TRUE(s.begin() == s.cbegin());
	ASSERT_TRUE(s.cbegin() != s.end());
	ASSERT_TRUE(s.begin() != s.cend());
}

TEST(IteratorComparison, LessSame) {
	ASSERT_TRUE(s.begin() < s.end());
	ASSERT_TRUE(s.begin() <= s.end());
	ASSERT_TRUE(s.end() > s.begin());
	ASSERT_TRUE(s.end() >= s.begin());
}

TEST(IteratorComparison, LessDifferent) {
	ASSERT_TRUE(s.cbegin() < s.end());
	ASSERT_TRUE(s.begin() < s.cend());

	ASSERT_TRUE(s.cbegin() <= s.end());
	ASSERT_TRUE(s.begin() <= s.cend());

	ASSERT_TRUE(s.cend() > s.begin());
	ASSERT_TRUE(s.end() > s.cbegin());

	ASSERT_TRUE(s.cend() >= s.begin());
	ASSERT_TRUE(s.end() >= s.cbegin());
}
```

**Comment by miscco** [comment]
OK dumb me `span::iterator` and `span::const_iterator` are the same type for `span<const int>`
