### ISSUE TITLE
<yvals_core.h>: Update _MSVC_STL_UPDATE to February 2020

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#477]
Explanation on our wiki: [Macro `_MSVC_STL_UPDATE`](https://github.com/microsoft/STL/wiki/Macro-_MSVC_STL_UPDATE)

Code:
https://github.com/microsoft/STL/blob/10e92884618d3b816a4dd54ffe21c4979ec5ddd6/stl/inc/yvals_core.h#L439

Previous update: #409

This issue is intended for a new contributor (especially one new to GitHub) to get started with the simplest possible change.

**Comment by JeanPhilippeKernel** [comment]
Hey @StephanTLavavej  can I work on this issue ?

**Comment by CaseyCarter** [comment]
I'm not @StephanTLavavej, but yes - please do!

**Comment by StephanTLavavej** [comment]
Looking forward to your PR 😸
