### ISSUE TITLE
Performance improvement about std::binary_semaphore::acquire

### ISSUE THREAD

**Issue by YandereChan2** [microsoft/STL#4783]
Before:

```cpp
void acquire() noexcept /* strengthened */ {
    for (;;) {
        unsigned char _Prev = _Counter.exchange(0);
        if (_Prev == 1) {
            break;
        }
        _Counter.wait(0, memory_order_relaxed);
    }
}
```

After:

```cpp
void acquire() noexcept
{
   _Counter._wait_and_write_back(0);
}

T _wait_and_write_back(const _TVal _Expected, const memory_order _Order = memory_order_seq_cst) const noexcept {
    return  _STD _Atomic_wait_and_write_back(this, _STD _Atomic_reinterpret_as<char>(_Expected), _Order);
 }

//Just use exchange when waiting.
//No other atomic calling.

T _Atomic_wait_and_write_back(
    const _Atomic_storage<_Ty>* const _This, _Value_type _Expected_bytes, const memory_order _Order) noexcept {
    const auto _Storage_ptr = _STD addressof(_This->_Storage);
    for (;;) {
        const _Value_type _Observed_bytes = _STD _Atomic_reinterpret_as<_Value_type>(_This->exchange(_Order));
        if (_Expected_bytes != _Observed_bytes) {
            return _Observed_bytes;
        }

        ::__std_atomic_wait_direct(_Storage_ptr, &_Expected_bytes, sizeof(_Value_type), __std_atomic_wait_no_timeout);
    }
}
```

Observely, the changed version will call less atomic functions and have less 'if'.

**Comment by AlexGuteniev** [comment]
I don't see any difference between before and after

**Comment by YandereChan2** [comment]
> I don't see any difference between before and after

In before, there is an extra atomic load in the function body of atomic::wait.(please check the impl of wait) I just remove it in after.

**Comment by AlexGuteniev** [comment]
Oh, I see... you wouldn't beleive, but threre are usually 10'000 loads in `WaitOnAddress`, which is the impl of `__std_atomic_wait_direct`, one more or less doesn't make a difference

**Comment by YandereChan2** [comment]
> Oh, I see... you wouldn't beleive, but threre are usually 10'000 loads in `WaitOnAddress`, which is the impl of `__std_atomic_wait_direct`, one more or less doesn't make a difference

Ok... sorry for bother you.

**Comment by StephanTLavavej** [comment]
Agreed, this doesn't seem like an observable difference. I would be willing to reconsider with demonstrated benchmark data. Thanks for looking into this!
