### ISSUE TITLE
P1020R1 Smart Pointer Creation With Default Initialization

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#48]
[P1020R1](https://wg21.link/P1020R1) Smart Pointer Creation With Default Initialization

[P1973R1](https://wg21.link/P1973R1) Renaming `default_init` To `for_overwrite`

Final feature-test macro in WG21-N4861:

`#define __cpp_lib_smart_ptr_for_overwrite 202002L`

**Comment by Weheineman** [comment]
> [P1973R1](https://wg21.link/P1973R1) Renaming `default_init` To `for_overwrite`
> 
The link for P1973R1 gives me a 404 error.

**Comment by CaseyCarter** [comment]
> The link for P1973R1 gives me a 404 error.

The link will become valid in a few days when the post-Prague WG21 meeting "mailing" becomes available.
