### ISSUE TITLE
STL: We should better tag those files which might end up in import libs

### ISSUE THREAD

**Issue by BillyONeal** [microsoft/STL#483]
In the review https://github.com/microsoft/STL/pull/457 @StephanTLavavej asked for the "ominous comment"

https://github.com/microsoft/STL/blob/b3504262fe51b28ca270aa2e05146984ef758428/stl/inc/xfacet#L19-L22

to be added to a ["core" header](https://github.com/microsoft/STL/wiki/What's-the-difference-between-(core)-and-non-(core)-headers%3F) on the basis that it was included in an import lib. However, that would be incongruous with other core headers, which we already include in our import libs.

We should remove the "ominous comment" from headers and put it in that wiki page, add a link from each "core" header to the wiki page, and ensure the wiki page explains the same content as the "ominous comment". We should also ensure that each .cpp file in the import lib has an ominous comment.

We should probably also update the ominous comment to not talk about the length of included stuff, similar to the following:

```
// This file is part of the msvcprt.lib and msvcprtd.lib import libraries.
// Therefore, it must not depend on any settings that affect layout or behavior of standard
// library types like _CONTAINER_DEBUG_LEVEL or _ITERATOR_DEBUG_LEVEL.
// In particular, basic_string must not be included here.
```

**Comment by StephanTLavavej** [comment]
I'm uncertain whether linking to the STL wiki from product code is a good idea. That essentially requires those wiki pages to have eternally unchanged URLs, which is too easily broken. I'd rather have such headers refer readers to another header containing an explanation, which is our usual practice elsewhere.

**Comment by BillyONeal** [comment]
That sounds OK, we could put the explanation into `<yvals_core.h>` for example.
