### ISSUE TITLE
`STL.natvis`: The VS copy is outdated

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#4831]
It's been a while since a maintainer has "triple-mirrored" the STL visualizers into VS. Comparing VS 2022 17.11 Preview 3's `C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\Packages\Debugger\Visualizers\stl.natvis` to the repo's [`stl/debugger/STL.natvis`](https://github.com/microsoft/STL/blob/ef1d621d51263285aff8e560a214f5477d63d687/stl/debugger/STL.natvis), I observe that (2023-06-15) #3772 is present, but we're missing:

* (2023-08-03) #3848
* (2024-01-30) #4274
* (2024-08-07) #4835
* (2024-08-07) #4836

Casey has created VS-PR-582133 to fix this.

**Comment by CaseyCarter** [comment]
I've managed to complete VS-PR-582133 in time for VS 17.12p3.
