### ISSUE TITLE
VSCode: Investigate using Tasks and Debugging for this repo

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#484]
Currently, [.vscode/settings.json](https://github.com/microsoft/STL/blob/b3504262fe51b28ca270aa2e05146984ef758428/.vscode/settings.json) provides a nice experience for users opening this repo as a VSCode workspace (e.g. with `code .`). However, I've heard that VSCode can do much more. We should investigate whether we can configure VSCode's [Tasks](https://code.visualstudio.com/docs/editor/tasks) and [Debugging](https://code.visualstudio.com/docs/editor/debugging) functionality so users can do things like:

* Run our `clang-format` and `validate` enforcement on the STL's files
* Build the STL
* Build a single configuration of a single test
* Run a test with the debugger attached

**Comment by StephanTLavavej** [comment]
The CMake Tools extension for VSCode may be a better solution that uses our existing machinery; we should run a poll/survey to judge whether VSCode tasks are generally desired by contributors before deciding whether to maintain such tasks in the repo.

**Comment by ZaldronGG** [comment]
At the very least, one could recommend the appropriate CMake extension(s) via [extensions.json](https://code.visualstudio.com/docs/editor/extension-gallery#_workspace-recommended-extensions).

**Comment by KindDragon** [comment]
I think better to setup dev container for VS code https://code.visualstudio.com/docs/remote/containers

**Comment by StephanTLavavej** [comment]
We talked about this at the weekly maintainer meeting and we're not very interested in implementing/maintaining such machinery.
