### ISSUE TITLE
<format>:How do I specialize the std::formatter with module

### ISSUE THREAD

**Issue by eiytoq** [microsoft/STL#4861]
How should I specialize the std::formatter for a type with template parameters within a module?
An example:
[reiteration.zip](https://github.com/user-attachments/files/16367110/reiteration.zip)
When I use this, it fails, but I try moving the std::formatter specialization to main.cpp, it succeeds.

**Comment by StephanTLavavej** [comment]
Thanks for reporting this bug. Your test case is equivalent to DevCom-10506520 "Partial specialization of `std::formatter` in module is not found in other module.", which was a compiler bug that was recently fixed. The fix will be available in VS 2022 17.12 Preview 2.
