### ISSUE TITLE
`<algorithm>`: `ranges::inplace_merge` doesn't seem to be able to utilize `ranges::upper_bound`

### ISSUE THREAD

**Issue by hewillk** [microsoft/STL#4863]
```cpp
#include <algorithm>
#include <vector>

int main() {
  std::vector<int> v;
  auto cmp = [](int&, int&) { return true; };
  std::ranges::sort(v, cmp);
  std::ranges::inplace_merge(v, v.begin(), cmp); // hard error
}
```
https://godbolt.org/z/soe8sa75q

The above code is rejected by libstdc++, libc++, and MSVC-STL, which shouldn't be because `ranges::inplace_merge` has the _same_ constraint signature as `ranges::sort`.
The root cause is that `inplace_merge` uses `upper_bound`, which then requires `Compare` to satisfy `indirect_strict_weak_order<const T*, I>` (note the `const` here), which is not guaranteed by the constraints of `inplace_merge`.

**Comment by frederick-vs-ja** [comment]
> The root cause is that `inplace_merge` uses `upper_bound`, which then requires `Compare` to satisfy `indirect_strict_weak_order<const T*, I>` (note the `const` here), which is not guaranteed by the constraints of `inplace_merge`.

Pedantically wrong for all three major implementations. Implementations actually call the unconstrained (by possible `static_assert`-ing) internal versions instead of `ranges::upper_bound`. Although this perfectly indicates that the [partial implementation posted on cppreference](https://en.cppreference.com/w/cpp/algorithm/ranges/inplace_merge#Possible_implementation) is currently incorrect.

At the first glance, I thought we should remove `const` somewhere. It should be investigated whether additional fix is needed for proxy references.

**Comment by hewillk** [comment]
> At the first glance, I thought we should remove `const` somewhere. It should be investigated whether additional fix is needed for proxy references.

Not sure if making `_Upper_bound_unchecked` accept `_Ty&& _Val` instead of `const _Ty& _Val` and doing the forwarding internally would fix this.

**Comment by hewillk** [comment]
> @barcharcraz and I talked about this at the weekly maintainer meeting. The fact that the Majestic Three implementations all reject this code, and the fact that it seems super pathological/useless for comparison function objects to reject `const` arguments, indicates that we need to send this to the LWG and they need to decide what should happen here. Our initial reaction is that the `sortable` concept should require const-comparisons to work, in the same way that `ranges::upper_bound` is explicitly adding constness when checking for comparability, but mostly we just want the LWG to tell us exactly what should happen here.

OK. Let me change the example that is only rejected by MSVC-STL:

```cpp
#include <algorithm>
#include <vector>

struct S {
  operator int();
};

int main() {
  std::vector<int> v;
  auto cmp = [](int, int) { return true; };
  std::ranges::inplace_merge(v, v.begin(), cmp, [](int) { return S{}; });
}
```
https://godbolt.org/z/f5ahs7nv9

Could this be considered a library bug?

**Comment by StephanTLavavej** [comment]
Yeah, that looks more like a bug to me, since MSVC is alone there (with the nitpicks that a "do nothing" comparator really ought to return `false`, and that it's confusing for the range to be `int`s that are projected to `S` and then compared as `int` - it would be clearer if 3 different types were involved).

**Comment by frederick-vs-ja** [comment]
For the LWG issue part, LWG-3031 seems roughly related.

**Comment by hewillk** [comment]
> For the LWG issue part, [LWG-3031](https://cplusplus.github.io/LWG/issue3031) seems roughly related.

Quoted from  [LWG-3031](https://cplusplus.github.io/LWG/issue3031):
> Similar to the Ranges TS design, the P/R below requires `Predicate`, `BinaryPredicate`, and `Compare` to accept all mixes of const and non-`const` arguments.

Doesn't this already indicate that this is a bug in the standard library implementation rather than a defect in the standard?
The LWG considers these examples should work.

**Comment by frederick-vs-ja** [comment]
> Quoted from [LWG-3031](https://cplusplus.github.io/LWG/issue3031):
> 
> > Similar to the Ranges TS design, the P/R below requires `Predicate`, `BinaryPredicate`, and `Compare` to accept all mixes of const and non-`const` arguments.
> 
> Doesn't this already indicate that this is a bug in the standard library implementation rather than a defect in the standard? The LWG considers these examples should work.

I didn't know what the paragraph intended to mean. `Sortable` in Ranges TS wasn't fundamentally different from the current `std::sortable` and accepted non-const-only comparators. But the decision in that paragraph and the final resolution of LWG-3031 imposed stricter requirements on `Compare` - which was, IIUC, inconsistent with Ranges TS.
