### ISSUE TITLE
`<ranges>`: `zip_view` iterator `tuple` vs `pair`

### ISSUE THREAD

**Issue by matt77hias** [microsoft/STL#4915]
# Describe the bug

Microsoft's `zip_view` iterator always uses `std::tuple` value_types, whereas it should use `std::pair` value_types when zipping two ranges. At least according to the [paper](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2021/p2321r2.html#tuple-or-pair) (as opposed to for example [cppreference](https://en.cppreference.com/w/cpp/ranges/zip_view/iterator)).

* [Clang](https://github.com/llvm/llvm-project/blob/main/libcxx/include/__ranges/zip_view.h#L62): seems to be correct
* [gcc](https://github.com/gcc-mirror/gcc/blob/master/libstdc%2B%2B-v3/include/std/ranges#L4696): doesn't seem to be correct
* [Microsoft](https://github.com/microsoft/STL/blob/main/stl/inc/ranges#L7179): doesn't seem to be correct

Concretely, not using `std::pair` value_types when zipping two ranges, makes it impossible to piggy back on `zip_view` for map-like containers such as `flat_map` and `flat_multimap`, because there are no `first` and `second` members.

# Expected behavior
```c++
// Reusing the libcxx code
template <typename _Tp, typename _Up>
auto __tuple_or_pair_test() -> pair<_Tp, _Up>;

template <typename... _Types>
requires(sizeof...(_Types) != 2)
auto __tuple_or_pair_test() -> tuple<_Types...>;

template <class... _Types>
using __tuple_or_pair = decltype(__tuple_or_pair_test<_Types...>());
```
```c++
using _My_tuple = __tuple_or_pair<iterator_t<_Maybe_const<_IsConst, _ViewTypes>>...>;
```
instead of
```c++
using _My_tuple = tuple<iterator_t<_Maybe_const<_IsConst, _ViewTypes>>...>;
```

# Additional context
[Reddit](https://www.reddit.com/r/cpp_questions/comments/18tlfmi/why_does_stdviewszip_use_an_stdpair_when_zipping/)

_P.S.: Personally, I am not a fan of the discontinuity, nor `std::pair<T,U>` and `std::tuple<T,U>` to be distinct types, but it is what it is._

**Comment by cpplearner** [comment]
[P2165R4](https://wg21.link/P2165R4) changes the element type to always be a `tuple`.

**Comment by CaseyCarter** [comment]
As @cpplearner points out, `zip_view` has been `tuple`-only in the C++23 working draft since the adoption of WG21-P2165R4.
