### ISSUE TITLE
<compare>: x <=> y has wrong type and value category for builtin types

### ISSUE THREAD

**Issue by CaseyCarter** [microsoft/STL#493]
DevCom-591817 / VSO-905257 causes the compiler to use the wrong type and value category for `x <=> y` when that expression uses a builtin `<=>` operator; when the expression should be a prvalue of type `T` it is instead an lvalue of type `const T` that denotes one of the STL's variables of comparison category type. For example, `&(13 <=> 42) == &std::strong_ordering::less` evaluates to `true`. While this is certainly fun, it breaks the concepts added in #385 and machinery that relies on those concepts. The tests for that machinery avoid triggering the bug and consequently don't test much. (I validated the full test with tip-of-`release/10.x` clang that will become Clang 10 RC2.)

The bug has been fixed for VS2019 16.6 Preview 2, but I'm leaving the workarounds in the test code since we plan to open-source the majority of our tests Real Soon Now™. Once VS2019 16.6p2 releases, we can remove the workarounds from the test.

(EDIT: Despite that there's nothing to fix in the header I expect people to stumble across the bug messing with `<compare>` so I'm tagging the issue title to help those people find it.)

**Comment by StephanTLavavej** [comment]
VS 2019 16.6 Preview 2 and Preview 3 are now available, so we can remove these test workarounds.

**Comment by StephanTLavavej** [comment]
The test workarounds appear to be:
https://github.com/microsoft/STL/blob/51446475c15493df1b1e2c0a1b2bc9d36d19fad6/tests/std/tests/P0896R4_P1614R2_comparisons/test.cpp#L261-L277
https://github.com/microsoft/STL/blob/51446475c15493df1b1e2c0a1b2bc9d36d19fad6/tests/std/tests/P0896R4_P1614R2_comparisons/test.cpp#L300-L312

**Comment by CaseyCarter** [comment]
Fixed by #741,
