### ISSUE TITLE
<filesystem>: directory_iterator including "." and ".." on network drives

### ISSUE THREAD

**Issue by BillyONeal** [microsoft/STL#494]
**Describe the bug**
Our directory enumeration machinery assumes `.` and `..` will be the first directory entries returned from FindFirstFile, but this doesn't appear to be the case in some network share scenarios.

This is a dual of DevCom-903816 which has additional details.

**Command-line test case**
STL version (git commit or Visual Studio version): Visual Studio 2019 version 16.5

Create a directory and create a file #1.txt on Windows 10 host. Share this directory to Windows 10 client.

```
#include <iostream>
#include <filesystem>
int main()
{
    try {
        namespace fs = std::filesystem;
        fs::path dir = "//ServerHost/D$/work/dirTest";
        dir = absolute(dir);

        for (auto const& di : fs::directory_iterator(dir)) {
            if (di.is_directory()) {
                std::wcout << "is_directory:  ";
            }
            else {
                std::wcout << "!is_directory: ";
            }
            std::wcout << di.path().native() << std::endl;
        }
    }
    catch(std::filesystem::filesystem_error &e) {
        std::wcout << e.what();
    }
    return 0;
}
```

**Actual behavior**
```
!is_directory: \\ServerHost\D$\work\dirTest1\#1.txt
is_directory:  \\ServerHost\D$\work\dirTest\.
is_directory:  \\ServerHost\D$\work\dirTest\..
```

**Expected behavior**
```
!is_directory: \\ServerHost\D$\work\dirTest\#1.txt
```

**Comment by JeanPhilippeKernel** [comment]
Can I work on this ? @BillyONeal  ?

**Comment by StephanTLavavej** [comment]
At the moment, nobody is working on this (and Billy is helping another team for a while), so feel free to work on it!

**Comment by BillyONeal** [comment]
Yeah, sorry I missed replying to this, go for it :)
