### ISSUE TITLE
Future of std::experimental::fileystem in c++14 mode

### ISSUE THREAD

**Issue by MikeGitb** [microsoft/STL#495]
My understanding is that I can currently use `<filesystem>  / std::filesystem` in c++17 and `<experimental/filesystem> / std::experimental::filesystem` as a (not quite compatible) fallback in c++14. 
However, an error message in `<experimental/filesystem>` tells me that `std::experimental::filesystem`  will be removed in the future. 

Will there still remain some way to use a version of the filesystem library in c++14 or do I have to revert back to boost?

**Comment by StephanTLavavej** [comment]
https://github.com/microsoft/STL/blob/ed3cbf36416a385828e7a5987ca52cb42882d84b/stl/inc/experimental/filesystem#L27-L31

As this message advises, you can define `_SILENCE_EXPERIMENTAL_FILESYSTEM_DEPRECATION_WARNING` to continue using `<experimental/filesystem>` (in any language mode). Note that it contains bugs that will never be fixed, so you should migrate to C++17 and Standard `<filesystem>` as soon as possible (which has a far more robust implementation).

We plan to continue supporting `<experimental/filesystem>` in this state for the rest of the v19 compatible release series (i.e. the VS 2015/2017/2019 binary compatible STL), but we plan to remove `<experimental/filesystem>` in the binary-incompatible vNext release. We will probably continue to support `/std:c++14` in vNext, but we currently have no plans to enable Standard `<filesystem>` in C++14 mode.

That said, supporting `<filesystem>` in C++14 mode would probably be a fairly reasonable thing to do, especially if it mitigates an upgrade blocker for customers.
