### ISSUE TITLE
<chrono>: `zoned_time` and `current_zone` ignore DST preference on Windows 11 and Server 2022

### ISSUE THREAD

**Issue by basilgello** [microsoft/STL#4997]
# Describe the bug

Testing the migration of Kodi to `std::chrono` (xbmc/xbmc#18727), the bug has been reported in STL chrono implementation where
time zones with DST adjustment preference grayed-out (unavailable) or disabled by user result in 1 hour difference between Kodi local time and the Windows Explorer local time.

For example, `(UTC-06:00) Guadalajara, Mexico City, Monterey` has no DST policy and the bug is shown on screenshot (notice top-right clock of Kodi vs bottom-right of Windows Explorer tray and the one in Date and Time Settings applet!):

![00-nodst-bad](https://github.com/user-attachments/assets/7ab7ef21-c716-4161-b14e-c071efdfed62)

For `(UTC-06:00) Central Time (US & Canada)` there is a preference to apply DST adjustment or not. Turning DST adjustment ON shows the proper time in Kodi:

![01-dst-good](https://github.com/user-attachments/assets/c2d91245-f1f2-432b-b9d8-a13a11c52a56)

while turning it OFF manifests the bug:

![02-nodst-bad](https://github.com/user-attachments/assets/6325d01f-d9d6-419a-ab32-b4f27cef28de)
  
# Command-line test case
```
C:\Temp>type repro.cpp
#include <chrono>
#include <iostream>

int main() {
    const std::chrono::zoned_time cur_time{ std::chrono::current_zone(),
                                            std::chrono::system_clock::now() };
    std::cout << cur_time << '\n';
}

C:\Temp>cl /EHsc /W4 /WX /std:c++latest .\repro.cpp
Microsoft (R) C/C++ Optimizing Compiler Version 19.41.34120 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

/std:c++latest is provided as a preview of language features from the latest C++
working draft, and we're eager to hear about bugs and suggestions for improvements.
However, note that these features are provided as-is without support, and subject
to changes or removal as the working draft evolves. See
https://go.microsoft.com/fwlink/?linkid=2045807 for details.

repro.cpp
Microsoft (R) Incremental Linker Version 14.41.34120.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:repro.exe
repro.obj

C:\Temp> REM (UTC-06:00) Guadalajara, Mexico City, Monterey - DST pref grayed out (bad!)
C:\Temp>time      
The current time is:  1:05:09.35
Enter the new time: 
C:\Temp>repro.exe
2024-10-01 02:05:13.0396870 CDT`

C:\Temp> REM (UTC-06:00) Central Time (US & Canada) - DST preference on (good!)
C:\Temp>time      
The current time is:  2:06:44.42
Enter the new time: 
C:\Temp>repro.exe
2024-10-01 02:06:47.3969896 CDT

C:\Temp> REM (UTC-06:00) Central Time (US & Canada) - DST preference off (bad!)
C:\Temp>time      
The current time is:  1:08:39.69
Enter the new time: 
C:\Temp>repro.exe
2024-10-01 02:08:42.3091382 CDT
```

# Expected behavior

DST preferences should be honored!

# STL version
* Option 1: Visual Studio version

```
C:\Temp>"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -property catalog_productDisplayVersion
17.11.4
```

# Additional context

None

**Comment by basilgello** [comment]
@HowardHinnant FYI

**Comment by basilgello** [comment]
As Microsoft's STL implementation is just a wrapper over ICU `ucal_*`, I think the bug resides deeper in ICU

@yumaoka maybe you have any ideas?

**Comment by basilgello** [comment]
Digging further into ICU Jira reveals https://unicode-org.atlassian.net/issues/ICU-21465 which was fixed in 68.2 and 69.1

**Comment by basilgello** [comment]
And https://unicode-org.atlassian.net/browse/ICU-13845

**Comment by basilgello** [comment]
Windows Server 2022 has `icu.dll` of version `64.2.0.2`:

```powershell
PS C:\Users\root> (Get-Item C:\Windows\System32\icu.dll).VersionInfo              

ProductVersion   FileVersion      FileName
--------------   -----------      --------
64, 2, 0, 2      64, 2, 0, 2 (... C:\Windows\System32\icu.dll
```

**Comment by basilgello** [comment]
What bothers me more is the following: is there a chance we get the ICU fix into current Win10 as a Patch Tuesday? And how long time might it take?

Rationale is that Team Kodi must agree on minimally supported Windows version for v22 Piers. And most of Windows Kodi users are on Win10. With current implementation, Win10 1903 is an absolute minimum version possible because it is the first release that introduced ICU as a system component. But it has already reached EOL, so most practical outcome would be to get a KB-update for current Win10 edition and mark it as minimally supported for Kodi.

Another option is to postpone usage of `std::chrono::time_zone` to Kodi v23 and augment Howard Hinnant's date library we currently use to handle Windows timezones using `EnumDynamicTimeZoneInformation` / `SystemTimeToTzSpecificLocalTimeEx` WinAPI functions. This will lift the binding to system-shipped ICU but certainly requires some more efforts from me.

**Comment by basilgello** [comment]
@StephanTLavavej 24H2 passes my tests - both in Kodi and the console reproducer!

**Comment by basilgello** [comment]
@StephanTLavavej Is there a way to get KB-update at least for latest supported Windows 10?
Win11 24H2 has it fixed but we all know that most Kodi users prefer Win10 over Win11.

Can you please raise this question?

Otherwise, I am not sure that Windows Timezone API  can be used to re-implement
<https://en.cppreference.com/w/cpp/chrono/time_zone/get_info> to answer the
question "Was the territory observing DST at a local time point XXX?" given registry
values for Dynamic Time Zones have only years 2006 to 2015.

**Comment by StephanTLavavej** [comment]
With Windows 10 exactly one year away from reaching the end of *security updates* for the mainstream editions, it is incredibly unlikely that the Windows division would update ICU for new features at this time.

Thanks for confirming that Win11 24H2 has fixed this - we're going to resolve this issue as there's nothing else the STL can do here.

**Comment by basilgello** [comment]
> as there's nothing else the STL can do here.

@StephanTLavavej I would not say nothing can be done here ;) I have ported (and optimized a bit!) STL's implementation to Howard's date library and incorporated the ICU fix into `std::chrono::current_zone()`.

Few remarks from the porting excersize:

* https://github.com/microsoft/STL/blob/3532569b95d8b6435100999de2b4e5b4e81453bc/stl/src/tzdb.cpp#L510 - caching `UCal` blindly will produce wrong results while concurrent execution because `__icu_ucal_setMillis` is set once per instance.

* https://github.com/microsoft/STL/blob/3532569b95d8b6435100999de2b4e5b4e81453bc/stl/inc/chrono#L1774 - `_Get_local_info(_Local, __std_tzdb_sys_info_type::_Offset_and_range)` could save the wide-to-narrow conversion of abbreviation that is not used in the function

* https://github.com/microsoft/STL/blob/3532569b95d8b6435100999de2b4e5b4e81453bc/stl/src/tzdb.cpp#L553 - I found out that blindly using `U_DATE_{MIN,MAX}` to get the result of `std::chrono::sys_seconds` will produce incorrect results due to silent overflow. The test https://github.com/HowardHinnant/date/blob/5bdb7e6f31fac909c090a46dbd9fea27b6e609a4/test/tz_test/validate.cpp went into an endless loop here because `info.end` was negative despute `U_DATE_MAX` was positive itself.

**Comment by basilgello** [comment]
Also, I really dont understand where the internal representation overflows in this example: https://godbolt.org/z/5nvo8q87c

FTR, the end-of-year when `tp` does not overflow is 6052.

**Comment by HowardHinnant** [comment]
The overflow is due to [this part](http://eel.is/c++draft/time.syn#def:signed_integer_type_of_at_least_29_bits) of the spec:

```c++
using minutes      = duration<signed integer type of at least 29 bits, ratio<  60>>;
using hours        = duration<signed integer type of at least 23 bits, ratio<3600>>;
```

Your example will portably overflow if you write it as:

```c++
auto tp = sys_days{ymd} + duration<std::int32_t, std::ratio<3600>>{23} + duration<std::int32_t, std::ratio<60>>{59} + seconds{59} + microseconds{999999};
```

The `sys_days`, `hours` and `minutes` computation is all taking place with 32 bit arithmetic.  It switches to 64 bit arithmetic only when you add the `seconds`.  And 32 bit minutes won't reach to year 32767.  One can work around this overflow by adding the time in _reverse_ order:

```c++
auto tp = sys_days{ymd} + microseconds{999999} + seconds{59} + minutes{59} + hours{23} ;
```

This causes the computation to switch to 64 bit arithmetic much earlier.

**Comment by basilgello** [comment]
@HowardHinnant Thanks! Actually, this is https://github.com/HowardHinnant/date/blob/master/test/date_test/format/range.pass.cpp#L53 :) I have another question about https://github.com/HowardHinnant/date/blob/master/test/date_test/durations_output.pass.cpp#L316 failing to expand the template, but I could not craft the godbolt reproducer today.

**Comment by basilgello** [comment]
For https://github.com/HowardHinnant/date/blob/master/test/date_test/durations_output.pass.cpp#L316 the reproducer is
 https://godbolt.org/#z:OYLghAFBqd5QCxAUwB7IMYFcAuB7AJwBoBLECAQwOAGcAFCgO2QBsBlBPAd0ZAHIAjHyIY8AWwAOJFhRwk8jBs3ace/AAzDRk6cgIgAbhgkSA%2BgYEBOUzJzIaOU6gBsAFhHipLPQDkKY5H4tT10CAHlcDm5ePk0iNEwAQWoaIPj0DDYcABMSGOEAMwUcNgwKbxABdyLGHABVGmQ6VA1hACtKohlGUAwAUgAmACFBoa6SACNUyABKIjwJOQVUvmE8Az0CEmz7eDmCLFqSAIAVPDwWaYg5mjwsAgxAgSIHXMUmVii1QWEuAgoJPwhHMWPwAKzCGJxPD8ACiGVwhAA1C5XEixDQjEiLJYAHS2ew4JEQADCo1GRCRsNy%2BAISMGAGYBDNhDhWjM5ghkBQdvprkQANYgMHqLr8VyQ1rzNKpUVs2J8OZwWBIUQ7akkWmkcgFXSMfyBH5EGolMoVKrG4oNJotBVEDrPbq9cnDF6sTBLXgQZCMbIki5YMS8MHxX0AGTyyB8gYmehADOcRAkeBomvkjH9LEDwaTKbTCgjzGjYlj%2BgTbu8GE9WSoOEz2eFFY96ZrBBwhajMbj5YctfrQcbvbbHeLpfjzhudwehsZeQwWZ29IGAwQOBwElSAHpN/8uLjgJqEFgJlhGg9ij6cLjtJvVFRsgg8vrapvsrJkJuxBQHHpN3OFx%2Bb52K%2B764gggwDH06iJFBiR5ESX55NcsF9AA7CM0FIlhSKnnkwBIkBgQgDsOAUNIIAgMAyCOIcmo0H0DIYTBmHYSSYQ%2BGwJwkgAIgIAhIhQiICTQ9IMtxSJUTRjB0QxJIYAgVAMbCECvBRsj4GhIyodxMwMUx2FImxHFcbx/GCfgSIFCJDHiZJpi0Tg9EMnJCkEEpKk5BRBTIGIGnoWhOl6bBBlGZxPF8QJQkbqJtnUfZ0mObJ8mKQyymqSAUiiJpAW6YxwWsexYWmZFFmMNZYkSXFDlOS5KVpZ5IDPng2Xabl%2BkFcZ4VmUJp4xZVUkyc5yVualHnZBRYgkBgBDNf5rVBSxWGhSZEXmXgOE0FwfV2dVslcMNpg4O56WTdNs1aYFeWLYZhUrd1FkYttVUJTVw3HQ1k0sCwJAtZd7VLbdXUletGDlbFA2JUNrnveNICPEcv1tflAOdcVa0EWD/XxYNtUjfVsM7BgP1zX9yM3ajq1CZjO0vUl0Ojel/xLLJAhKYjC2JCFgNo0Jb7U89ONvQzDWExQ7NXZzHVFZTFkIPzEOvfT%2BMUVyVbnTlHNcxT93rQK8vY5DuMwxRArSOr80S1r0s60iACy%2Bu7VDdVjRNyDAGLJNI9dy1A%2BjADiDu007eMu5RJDu%2BL/3k9bwNIicgeC0rod2P8kdkz7PMWXQCeG0LysZdRHsXV7ksozH6OwjnivO%2BlaBFxrlvYRABh4NsMzfpSzet9kMxWZ3Ldtxu/fdzMZXD23p5cOPPenkQZNd23GLTzMoPL9kNDLxvWELz3fPL3Lc/XTvMx68v9vLwHy/x8v2eUsSA895XHPp9zMvrZNjBPQrdM1w1TPyLJZw6g2ae01lLO6scEBfwNtXEOjNZAAOcgmdQwDUpp29q/G22RoGOyNsLWG/9mrOQABxuBQSA4uYDt4PxmB/fea9n4YIpmidG8E3Z6BwUHPB%2BdCEswGAyChDco4ZyqLHQhnDE6/wIQgohJIBD8MpAItBoDG7UJHmwqixB74j14RLMmBBqL3E/qgpiAVFRij4BCIgMQhDSj4GSYYowkS3HuI8JcTJWTsjmEKEUFiJREDEJUFB1ipQwlWC8EAcovEWIGJKO0YTPEKg5EQDYBBUwKBAK4IAA%3D%3D

Please note that removing `CONSTCD14` from both lines makes stuff compiles without any `/std:c++` qualifier. And `/std:c++11`, `/std:c++14` and `/std:c++17` produce one error pattern while `/std:c++20` results in another one.
