### ISSUE TITLE
Mirror stl.natvis to VS

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#5031]
This is a reminder issue that we need to triple-mirror stl.natvis into VS in order for #5005 to take effect.

**Comment by CaseyCarter** [comment]
Validating VS-PR-586841.

**Comment by CaseyCarter** [comment]
> Validating [VS-PR-586841](https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/586841).

Merged. I've updated the Changelog by moving the note for #5005 from the 17.13 preview 2 section to the preview 1 section. (VS hasn't yet snapped for preview 1.)
