### ISSUE TITLE
Strange condition in optional::swap

### ISSUE THREAD

**Issue by kelbon** [microsoft/STL#5033]
looks like a typo

```cpp    
void swap(optional& _Right)
        noexcept(...) {
        static_assert(is_move_constructible_v<_Ty>, ...);
        static_assert(!is_move_constructible_v<_Ty> || is_swappable_v<_Ty>, ...)
....

```

**Comment by CaseyCarter** [comment]
Since non-move-constructible types are very likely non-swappable, we felt like it was a good idea to avoid reporting two errors with roughly the same root cause. Do you think

```c++
static_assert(is_move_constructible_v<_Ty>, /* ... */);
// non-move-constructible types are almost certainly non-swappable, avoid complaining twice about roughly the same thing
if constexpr (is_move_constructible_v<_Ty>) {
    static_assert(is_swappable_v<_Ty>, /* ... */)
}
```

is sufficiently clear?

**Comment by kelbon** [comment]
> Since non-move-constructible types are very likely non-swappable, we felt like it was a good idea to avoid reporting two errors with roughly the same root cause. Do you think
> 
> static_assert(is_move_constructible_v<_Ty>, /* ... */);
> // non-move-constructible types are almost certainly non-swappable, avoid complaining twice about roughly the same thing
> if constexpr (is_move_constructible_v<_Ty>) {
>     static_assert(is_swappable_v<_Ty>, /* ... */)
> }
> would be sufficiently clear?

move_constructibe && swappable is more clear

**Comment by StephanTLavavej** [comment]
We talked about this at the weekly maintainer meeting and I suggested the following, since we can now use `static_assert(false)`:

```cpp
if constexpr (is_move_constructible_v<_Ty>) {
    static_assert(is_swappable_v<_Ty>, "blah blah not swappable");
} else {
    static_assert(false, "blah blah not move constructible");
}
```

This avoids repeating the `is_move_constructible_v` condition, and is sufficiently clear as to not require comment wordsmithing.
