### ISSUE TITLE
`flat_map` and `flat_set` should noisily reject `vector<bool>`

### ISSUE THREAD

**Issue by CaseyCarter** [microsoft/STL#5037]
`flat_map` (and `flat_set`) cannot adapt `vector<bool>` since it doesn't meet the sequence container requirements. We should reject `vector<bool>` at instantiation time with a clear error message citing [flat.map.overview]/7 (respectively [flat.set.overview]/7).

~~The visualizer for `flat_map` (currently on the `feature/flat_map` feature branch) has special cases that activate when both adapted containers are `vector` or `deque`. The `vector` visualization assumes the primary `vector` template and will therefore fail for `flat_map<vector<bool>, meow>` (I can't imagine anyone ever using this) and `flat_map<meow, vector<bool>>` (which should probably be a `flat_set<meow>`?). These are nowhere close to being important enough use cases to block merging the visualizer, but we should try to handle them properly for completeness.~~

**Comment by frederick-vs-ja** [comment]
Notes https://eel.is/c++draft/flat.map.overview#note-3 and https://eel.is/c++draft/flat.multimap.overview#note-3 suggest that these are not (required to be?) supported because `vector<bool>` is not a real container.
