### ISSUE TITLE
Messing with `std::sort`

### ISSUE THREAD

**Issue by achabense** [microsoft/STL#5039]
I'm horrified by the following use case. It's definitely not practical; however, with a shallow glance to cppreference I also cannot find what's going wrong... What am I missing here ?

(Also, [gcc and clang will display different result for this](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DIApACYAQuYukl9ZATwDKjdAGFUtAK4sGIM6SuADJ4DJgAcj4ARpjEIACs8aQADqgKhE4MHt6%2B/ilpGQIhYZEsMXGJtpj2jgJCBEzEBNk%2BfgF2mA6Z9Y0ExRHRsQlJCg1NLbntY32hA2VDiQCUtqhexMjsHOYAzKHI3lgm225iwCSECCxH2CYaAII7eweYR24Abp1ExNe3D2a7DH2XkOxyco2ImFYP3uj0Bz1eogUSia0Ie91CBAA1CwmKEIItMSYAOxWe6Y8mYtAMUaYpheIiY/AKZIGACehO2ABFCfErPFORAqTS6URzAA2SkE4mku4UuWY/jETGCgTC%2BmocWYt6YkCSwkk37yo2Y0boEAoVZY16vLUctw2sAcTGOo4y436zmG42m81oel2h1beJuBgu7Zu43Ez3h35e8kAenjmIQBAIyQUIETjAAdMhkskIVRYowNrnUCx4wB3eN55Lx07nAiXeMKEgEOMmghmkAfBwkV4Y65a10d7VHbnSzFcUgBbakaRJCVRkdkik%2BkCtpoQN7ZmLAPHLLXZ1z40id7v0JHW7Y3A1EzmLFeyilMllMVnbx/hzGJqf/STxGKsaruSQpYiKqC0ug6DEAA%2BpeCgchOvImPyKrUlig5mBKtBnmBmJYRKxBSgaIHyhCBBrAw57mgh163lY94QOKuGEthxFPu6y4xmR%2BEQVBMGwcAEJMAQsRITyfICvhhGYqxMmCJqxH6hGRoUVRNEgMJkJid8xw/HeAosWe4ocTxz5Gtxqk/kmnKQU2mBKAqXiArU1ImqJeAKFQ7LmGYHgsMkjQvGYZiYhCACOXh4BCbCCAoRwAGIdr%2BKZphmWYMLm%2BaFsWgKYGWFbVrW8bMGw6CwZF8YBUFEIpUmFihI0rLKBC%2BCiGJmIAH6YgA8gA1tm9WUuWyQQEwZ5RIsurDe6cpoIF41nkwUpcuOCpiE5PUDUNZG/nNFILWNE2YlNSFDmAYBHRAUTLQS22DbNB0jYtJ1neKmrXbderjkO10ncg919Y9e1JpgUV4G8S2nUDl3/ZNUrYZqcOjTdd0gE9B3g9FUMnSt51cpiBDEF4mDdcDu0WTZz3ktjkPQ%2B9%2BlrTemJ01D334w9lNyvtz1swziNAdhrMQ%2BzeGrdG2Aizj0OA%2BTO3DQAkliSiYCwiGttmWuYgA6ggom0iwmKK9iXnpEYSXAVTY6E5O06zvOpCLh6nFrl25qbgQ267pg%2B4MKeR4noeTDQXB2mibEX7Wa%2BbKfq61NcP%2BgEcsl2yJZi2CqMknyYGaKdJWK8SSNsZhcJbadW3KNsTiSU4zqQc4LqQS73q75JMEisRe%2BuXmwZ7ufe3uB5njuQfLaH8GOQoixR9TCtkeunuD77w%2BBww6AByHgkIVHHYx%2B%2Bcffr%2BhfF6X%2BdpxnWc53n5eJYn2wAUBFcVzCZHVypdcO03LfRtZi8NFEegfc2zLz9gHUe69N4T3DrpXeZF94fjeLPX899H6Yi1pTUcEk7b10bk7ZuLtzJyn/kwQBmBgFbh3EPf2h4IEb2DhPHebdGReTfIg5BSYT4ly4OgrWsZ7wcGWLQTg8ReB%2BG4LwVAnB7SWGsCaVY6wyY7B4KQAgmhBHLH6iAbY2xsw6P0QYwx%2BhOCSDEeo0gUiOC8AzBoVR6jlhwFgEgTAqhOjqjIBQcaxBgAKGUIYaoQgECoErOIlRR06CeQEH4sItBAnBPEVoUg4T6BxDeLWWCbwuAAE54IR1GLBVQYppDJNiOEVgmxeAlOIL1ekcSQnmJcZ0O43iMxWMCK45A9R8DiN4PwQQIgxDsCkDIQQigVDqA4Ik3QAQDBGBQNYaw%2Bg8BRAzJAZYqBkhuVaZIj4xBiB4CwKs08JNBB4DYAAFVQJ4I5yxWxrA2HoU0oRokBKCfUiRpBKzECYMkTgPAhEiLMZMyRnBM5uK%2BJiQpkhsQKDSVqbJ2YDBiRpBAGRVhLBnlwIQEgbFthcEWLwNRwKZ6kAQJCLAcRTxaK4GKbMYp6UMsZYy6QwiOCmNIAkkFbSbF2OJaQRxiAQCNOQO48glBGg%2BJebEt5oTKmjQiW5KVdTOVJPlSklAszgDZK4LYqpZS2CcDlYFOgsQanCBlQ0jpzSfGGvaZ0LpoRbV9OEKIcQwznVjLUOY3Q05NXzNkRi2gyybkWM2ZkbZFjdn7MOfAZYJzHAXKubQENdzFGPK7M8/x0r4l/N4F8n5uaAUcFERy8xliwUiohaoAAHGKAAtEUykmqpxZOzFwbMGhlRosWRnfAELlEEt5VoEl1LaVMvHQyllJigWJMsdYkAtiiXDv5TAQVwrRWeIlb4rNyrc2quNUizISqLXAv3ckE1cQtWSACHq8ptqqlmt3ae4V1qI3CodT0kZLrBkSGkB6pQXrT26DnH60wAabBBpWbG0NWzbWoCjQcxy0H41nMwJc650HU0POnE8hgx6c0fPzb8iRRaS0qvLR09xkLa0NuhcAZAyApySGzGFVFCyMW9uxUqAdhL7GaO0bowxQn9HGLZTOrl87F18dE2YcTFjbVLo0aQXZ6RnCSCAA%3D))

(Related [SO question](https://stackoverflow.com/questions/77224270/sorting-by-element-address))

```cpp
#include<algorithm>
#include<vector>
#include<iostream>
#include<cassert>

int main() {
    const auto display = [](const auto& c) {
        for (const auto& v : c) {
            std::cout << v << ' ';
        }
        std::cout << '\n';
        };

    // https://en.cppreference.com/w/cpp/algorithm/sort
    std::vector<int> v;
    v = { 1,2,3,4,5,6 };
    std::sort(v.begin(), v.end(), std::less<>{});
    display(v); // 123456

    const auto addr_less = [](const int& l, const int& r) {
        return std::less<>{}(&l, &r);
        };
    const auto addr_greater = [](const int& l, const int& r) {
        return std::greater<>{}(&l, &r);
        };
    // Do these functions satisfy "Compare" requirements?
    // https://en.cppreference.com/w/cpp/named_req/Compare
    // BinaryPredicate ~ Ok.
    // comp(a, b): 
    //             comp(a, a) == false ~ Ok.
    //             comp(a, b) => !comp(b, a) ~ Ok.
    //             comp(a, b) && comp(b, c) => comp(a, c) ~ Ok.
    // equiv(a, b) ~ !comp(a, b) && !comp(b, a):
    //             equiv(a, a) == true ~ Ok.
    //             equiv(a, b) <=> equiv(b, a) ~ Ok.
    //             equiv(a, b) && equiv(b, c) => equiv(a, c) ~ Ok.
    // It seems so... What am I missing?

    v = { 1,2,3,4,5,6 };
    std::sort(v.begin(), v.end(), addr_greater);
    display(v); // 123456 ?? Expected: ??654321??

    v = { 1,2,3,4,5,6 };
    assert(std::is_sorted(v.begin(), v.end(), addr_less)); // Ok.
    std::sort(v.begin(), v.end(), addr_less);
    display(v); // 654321 ?? Expected: ??123456??

    v = { 1,2,3,4,5,6 };
    std::stable_sort(v.begin(), v.end(), addr_greater);
    display(v); // 123456 ...

    v = { 1,2,3,4,5,6 };
    std::stable_sort(v.begin(), v.end(), addr_less);
    display(v); // 654321 ...
}
```

**Comment by AlexGuteniev** [comment]
> return std::less<>{}(&l, &r);

Drop `&`s here. Otherwise you are comparing pointers.

**Comment by achabense** [comment]
> > return std::less<>{}(&l, &r);
> 
> Drop `&`s here. Otherwise you are comparing pointers.

Yes, I know I shouldn't compare pointers for real purpose, but here I'm confused what's wrong with them (what is being violated then they are applied to `std::sort`)?

**Comment by AlexGuteniev** [comment]
> I'm confused what's wrong with them (what is being violated then they are applied to `std::sort`)?

Comparison doesn't give the same result all the time. `v[1] < v[2]`, and if you swap them, it is still `v[1] < v[2]`, this mean even violation of `comp(a, b) => !comp(b, a)`.

**Comment by achabense** [comment]
Are you talking about [equality-preserving](https://en.cppreference.com/w/cpp/concepts#Equality_preservation:~:text=An%20expression%20is-,equality%2Dpreserving,-if%20it%20results)? There says `two evaluations of it with the same input objects must have equal outputs without any explicit intervening modification of those input objects.` I think swap should be considered modification here.

Actually, I really hope to see requirements like `v=comp(a, b), swap(a, b) => comp(b, a)==v`. It's just that I cannot get that from the standard wording. If you have a look at the SO question, the answers finally diverge on the word "value" as in `comp shall induce a strict weak ordering on the values` [(here)](https://eel.is/c++draft/alg.sorting#:~:text=ordering%20on%20the-,values,-.), but I think a single word is too vague to pose the constraints...

**Comment by AlexGuteniev** [comment]
[[utility.swap]/3]( https://eel.is/c++draft/utility.swap#3) says:
> _Effects:_ Exchanges values stored in two locations

I think it is clear enough what is value and what is location.

**Comment by achabense** [comment]
Thanks, that's really useful info.

**Comment by frederick-vs-ja** [comment]
FYI the "locations" are not perfectly clear currently, see [editorial PR #6857](https://wg21.link/edit6857).
