### ISSUE TITLE
C++11 constexpr and C99 preprocessor

### ISSUE THREAD

**Issue by fsb4000** [microsoft/STL#504]
Hello. I have a question. Does Visual C++ still not support C++ 11 or is it an error on cppreference? If this is an error, then maybe we should fix it? I hope I did not distract you much, I understand that this does not apply to STL...

![cpp11](https://user-images.githubusercontent.com/4289847/74555508-6fed6280-4f8e-11ea-80f3-b82caa8fb908.png)

https://en.cppreference.com/w/cpp/compiler_support

**Comment by StephanTLavavej** [comment]
This question is indeed off-topic but I can answer it anyways.

The C99 preprocessor is currently controlled by `/experimental:preprocessor`. In VS 2019 16.6 Preview 2, it will be available as `/Zc:preprocessor` with enhanced behavior, but it won't yet be implied by `/std:c++latest` or `/permissive-`, so I still consider its support to be partial. This should hopefully be complete soon, although we don't have an ETA yet.

I don't know why cppreference claims that C++11 `constexpr` support is partial. The MSVC compiler recently fixed a severe bug in constant initialization, if that's what that was referring to.

**Comment by fsb4000** [comment]
Thank you @StephanTLavavej, I showed the link to this conversation to the guys from cppreference and now both items are green.

![cppreference](https://user-images.githubusercontent.com/4289847/74581981-a5269e80-4fe8-11ea-9e0d-bfb114556f8e.png)

**Comment by kasperk81** [comment]
That reference table also suggests `P0063R3` (C++17 should refer to C11 instead of C99 ) is partially implemented, but this table doesn't https://docs.microsoft.com/en-us/cpp/overview/visual-cpp-language-conformance?view=msvc-160#standard-library-features

**Comment by StephanTLavavej** [comment]
cppreference's tooltip says "missing `aligned_alloc()` mainly" which is accurate. As that's impossible for us to implement due to binary compatibility, I consider the feature to be yes-with-asterisk instead of partial-with-asterisk.
