### ISSUE TITLE
`<ostream>`: Should `std::vprint_[non]unicode(ostream &, string_view, Args&&)` pad or not?

### ISSUE THREAD

**Issue by muellerj2** [microsoft/STL#5080]
Formatted output functions of streams typically apply padding to their output according to the stream's field width setting (returned by the stream's member function `width()`).

However, there is implementation divergence for the stream print functions between libc++ (adds padding) on the one hand and MSVC and libstdc++ (no padding) on the other.

What suggests padding is that the stream print functions are defined as formatted output functions ([\[ostream.formatted.print\]/4](https://eel.is/c++draft/ostream.formatted.print#4)), and it appears to me that all other formatted output functions seem to effectively result in padding according to the field width. There is also common language for all these functions in [\[ostream.formatted.reqmts\]/3](https://eel.is/c++draft/ostream.formatted.reqmts#3) how they are to perform padding (*but not if* they pad).

On the other hand, the formatted output functions typically state explicitly that they apply the padding (although all other functions that don't contain such language seem to just defer the padding task to the locale). Such language is missing from the print functions, just like instructions to reset the field width to 0. And this padding feature strikes me as kind of superfluous as well, as padding can be explicitly specified in the format string.

**Comment by CaseyCarter** [comment]
[[ostream.formatted.reqmts]/3](https://eel.is/c++draft/ostream.formatted.reqmts#3) describes how a formatted output function determines padding, if it determines padding. Whether or not a formatted output function determines padding is then left to the specification of the individual functions. [[ostream.inserters.character]/1](https://eel.is/c++draft/ostream.inserters.character#1.sentence-4), for example, says that `operator<<(basic_ostream<char, traits>&, unsigned char)` "determines padding". The `vprint_meow_unicode` functions are specified to be formatted output functions, but they are not specified to "determine padding".

**Comment by muellerj2** [comment]
I filed llvm/llvm-project#116054 .

**Comment by CaseyCarter** [comment]
Great! This question has been answered, and action taken, I think we're done here.
