### ISSUE TITLE
P1065R2 constexpr INVOKE

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#51]
[P1065R2](https://wg21.link/P1065R2) `constexpr` INVOKE

This needs compiler support for [P0859R0](https://wg21.link/P0859R0) "CWG 1581: When are `constexpr` member functions defined?".

Feature-test macro as of WG21-N4842 (note that WG21-P1065 proposed adding `__cpp_lib_constexpr_invoke`, which was renamed by WG21-P1902):
`#define __cpp_lib_constexpr_functional 201907L`
(This was originally added for #50 WG21-P1032 "Miscellaneous `constexpr`" with the value `201811L`, see [SD-6][].)

[SD-6]: https://isocpp.org/std/standing-documents/sd-6-sg10-feature-test-recommendations

**Comment by BillyONeal** [comment]
https://gcc.godbolt.org/z/ro-Wqf <-- all the examples in the paper indicating that we needed CWG1581 fixed look to work in all the compilers now, so I think we can go ahead with this now.

**Comment by kasperk81** [comment]
> https://gcc.godbolt.org/z/ro-Wqf <-- all the examples in the paper indicating that we needed CWG1581 fixed look to work in all the compilers now, so I think we can go ahead with this now.

Not sure if [conformance table](https://github.com/MicrosoftDocs/cpp-docs/blob/master/docs/overview/visual-cpp-language-conformance.md) is up to date, but was CWG 1581 also resolved in 16.8?

**Comment by BillyONeal** [comment]
> Not sure if [conformance table](https://github.com/MicrosoftDocs/cpp-docs/blob/master/docs/overview/visual-cpp-language-conformance.md) is up to date, but was CWG 1581 also resolved in 16.8?

I didn't try to figure out if it was fixed completely, I just made sure the examples called out as problematic there in the paper worked.

Notably, our `std::invoke` implementation doesn't use SFINAE to select the mechanism to use, only `<type_traits>`, so it's possible that we were always immune to the 1581 edge cases.

**Comment by StephanTLavavej** [comment]
When we talked to the compiler devs in Dec 2020, we learned that while CWG-1581 isn't completely implemented (so the conformance table is correct), it's sufficient for the STL's purposes in `std::invoke` as far as we can tell.
