### ISSUE TITLE
`DEFAULTLIB:LIBCMT` leaks into static objects for import libraries

### ISSUE THREAD

**Issue by awson** [microsoft/STL#510]
ATM static objects in `msvcprt.lib` (and `msvcprtd.lib`) import libraries have `DEFAULTLIB:LIBCMT` directive inside.

This obviously leads to warnings when linking against these import libraries.

ATM I do the following to get rid of this:
```
diff -urN a/stl/CMakeLists.txt b/stl/CMakeLists.txt
--- a/stl/CMakeLists.txt	2020-02-18 11:43:07.193324100 +0300
+++ b/stl/CMakeLists.txt	2020-02-18 12:38:11.554992000 +0300
@@ -426,7 +426,7 @@
     # import library 'statics'
     add_library(msvcp${D_SUFFIX}_implib_objects OBJECT ${IMPLIB_SOURCES})
     target_compile_definitions(msvcp${D_SUFFIX}_implib_objects PRIVATE "_DLL;${THIS_CONFIG_DEFINITIONS}")
-    target_compile_options(msvcp${D_SUFFIX}_implib_objects PRIVATE "${THIS_CONFIG_COMPILE_OPTIONS};/EHsc") # No /GL!
+    target_compile_options(msvcp${D_SUFFIX}_implib_objects PRIVATE "${THIS_CONFIG_COMPILE_OPTIONS};/EHsc;/Zl") # No /GL!
 
     # msvcp140_1.dll (the memory_resource satellite)
     add_library(msvcp_1${D_SUFFIX}_objects OBJECT ${SOURCES_SATELLITE_1})
```

**Comment by StephanTLavavej** [comment]
Can you show the exact steps needed to reproduce the warnings (example test code and command line)? We can guess, but it’s better if you show us what you’re seeing.

Does this happen with the GitHub build, but not the import libs that ship in Visual Studio?

**Comment by awson** [comment]
Will create example later.

And yes, this happens only with the GitHub build, stock VS import libs' static objects don't have any `defaultlib` directives inside.

**Comment by awson** [comment]
To repro this you basically need any code, referencing any of these static objects. E.g, we may use this:

**Comment by awson** [comment]
To repro this you basically need any code, referencing any of these static objects. E.g, we may use this:

`foo.cpp`:
```
#include <filesystem>
#include <cstdio>

int main()
{
  for (std::filesystem::path p : std::filesystem::directory_iterator("*"))
    printf("%S\n", p.c_str());

  return 0;
}
```

Now, do `cl /nologo /MD /EHsc /std:c++17 foo.cpp` and get
```
foo.cpp
LINK : warning LNK4098: defaultlib 'LIBCMT' conflicts with use of other libs; use /NODEFAULTLIB:library
```

**Comment by StephanTLavavej** [comment]
@BillyONeal thinks he might have dropped `/Zl` during the conversion from MSBuild because it looked like `/ZI`. If our MSBuild system was using `/Zl` then we should definitely add it to CMake.
