### ISSUE TITLE
LWG-4072 `std::optional` comparisons: constrain harder

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#5115]
LWG-4072 `std::optional` comparisons: constrain harder

**Comment by frederick-vs-ja** [comment]
This seems to be a patch for WG21-P2944R3 which is treated as a changed in C++26...

**Comment by StephanTLavavej** [comment]
You're right, I missed that this is a patch. I'll update the issue.

**Comment by StephanTLavavej** [comment]
Fused into #4522.
