### ISSUE TITLE
P3136R1 Retiring Niebloids

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#5138]
WG21-P3136R1 Retiring Niebloids

No feature-test macro is mentioned.

This was unconditionally implemented by #4098. We just need to list this paper in the C++20 section of `<yvals_core.h>`.

**Comment by frederick-vs-ja** [comment]
Looks like that the only thing left to do is adding one comment line (saying `// P3136R1 Retiring Niebloids`) after this one.

https://github.com/microsoft/STL/blob/5e0ddadefd38b9ab50f2b8772ad4cb001133fd9d/stl/inc/yvals_core.h#L316-L317

Presumably this should be "good first issue".
