### ISSUE TITLE
P0472R3 Put `monostate` In `<utility>`

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#5140]
WG21-P0472R3 Put `monostate` In `<utility>`

No feature-test macro is mentioned.

We should obviously implement this unconditionally. Currently, it's defined by `<xutility>` (which is "bigger than" `<utility>` and includes it, unlike most `<xmeow>` headers):

https://github.com/microsoft/STL/blob/5e0ddadefd38b9ab50f2b8772ad4cb001133fd9d/stl/inc/xutility#L7553-L7555

**Comment by CaseyCarter** [comment]
LWG reviewed and approved R3, but WG21 voted to apply R2 to the working draft. There was a clerical error preparing the polls. We should work to R3: LWG will probably apply the differences as an issue resolution asap. That's the what happened the last time someone similar occurred, anyway

**Comment by StephanTLavavej** [comment]
Updated, thanks.

**Comment by CaseyCarter** [comment]
Update from the reflectors: LWG Chair is suggesting that the incorrect paper revision not be applied to the working draft, and that the correct revision will simply be polled again at the next WG21 meeting. I'm going to block this issue for now so nobody puts work into it, and we'll just delete it if LWG decides to proceed with that plan.

**Comment by StephanTLavavej** [comment]
This has been officially dropped by the WG21 editors, and R3 will be polled at the next meeting.

I've relabeled this accordingly (so it doesn't show up on the Status Chart and C++26 Project as a phantom feature).
