### ISSUE TITLE
`<filesystem>`: Is it fine for `junction` to be a pretty name?

### ISSUE THREAD

**Issue by frederick-vs-ja** [microsoft/STL#5154]
Currently, MSVC STL's `std::filesystem::file_type` contains this implementation-defined extension. Allowance of such an extension seems quite intended per [[tab:fs.enum.file.type]](https://eel.is/c++draft/tab:fs.enum.file.type).

https://github.com/microsoft/STL/blob/5e0ddadefd38b9ab50f2b8772ad4cb001133fd9d/stl/inc/filesystem#L1894

However, the identifier `junction` is not reseverved by the standard.

It seems strongly intended that any non-standard name provided by an implementation should be __ugly, but [[lex.name]/3](https://eel.is/c++draft/lex.name#3) also indicates that user code shouldn't even touch such a name, which seems somehow contradictory with the intent of specifying implementation-defined extensions.

**Comment by robert-andrzejuk** [comment]
What about the this part in the standard:

>  _implementation-defined_ | Implementations that support file systems having file types in addition to the above file_type types shall supply implementation-defined file_type constants to separately identify each of those additional file types

**Comment by CaseyCarter** [comment]
> Currently, MSVC STL's `std::filesystem::file_type` contains this implementation-defined extension. Allowance of such an extension seems quite intended per [[tab:fs.enum.file.type]](https://eel.is/c++draft/tab:fs.enum.file.type).
> 
> [STL/stl/inc/filesystem](https://github.com/microsoft/STL/blob/5e0ddadefd38b9ab50f2b8772ad4cb001133fd9d/stl/inc/filesystem#L1894)
> 
> Line 1894 in [5e0ddad](/microsoft/STL/commit/5e0ddadefd38b9ab50f2b8772ad4cb001133fd9d)
> 
>  junction // implementation-defined value indicating an NT junction
>  
> However, the identifier `junction` is not reserved by the standard.
> 
> It seems strongly intended that any non-standard name provided by an implementation should be __ugly, but [[lex.name]/3](https://eel.is/c++draft/lex.name#3) also indicates that user code shouldn't even touch such a name, which seems somehow contradictory with the intent of specifying implementation-defined extensions.

User code shouldn't touch identifiers in the implementation-reserved namespace _without express permission to do so_. We probably should have given this extension `file_type` an ugly name, but I don't know if it's worth the trouble to try to fix it now. We certainly haven't had any complaints from customers defining `junction` as a macro, which I believe is the only potential source of conflicts with the name of an enumerator for a scoped enumeration.

**Comment by cpplearner** [comment]
In vNext we may want to treat junctions as a special kind of symlinks, since they actually act like symlinks during pathname resolution.

**Comment by StephanTLavavej** [comment]
We talked about this at the weekly maintainer meeting and although this was probably not the most conformingest decision ever, we took the name and users have been living with it perfectly happily since VS 2017 15.7.

@cpplearner It's never a great time to make a behavior change, but if we're going to do it, there's no reason to sync it with the ABI break (which people will have a hard enough time adopting). If you strongly believe we should do that, please file a separate issue.
