### ISSUE TITLE
_CRT_STDIO_ARBITRARY_WIDE_SPECIFIERS

### ISSUE THREAD

**Issue by walbourn** [microsoft/STL#5166]
I know `_CRT_STDIO_ARBITRARY_WIDE_SPECIFIERS` was briefly "a thing" for a VS 2015 Preview and the change was removed due to feedback.

I see that `_CRT_STDIO_ARBITRARY_WIDE_SPECIFIERS` does not appear in any STL code or in the VS 2022 VC++ headers, but it is still being set in the CMakeLists.txt. The symbol also appears in a number of VC++ libraries/PDBs.

Is this just left-over cruft or does it still serve some purpose?

**Comment by frederick-vs-ja** [comment]
https://github.com/microsoft/STL/blob/89ca073a866d24db42b3f4c5e406be4b28a148f4/CMakeLists.txt#L96

This line has never been changed since the first commit. I guess `_CRT_STDIO_ARBITRARY_WIDE_SPECIFIERS` has been forgotten by STL maintainers for years.

**Comment by cpplearner** [comment]
I believe that `_CRT_STDIO_ARBITRARY_WIDE_SPECIFIERS` 
is intended to prevent UCRT from emitting a `detect_mismatch` pragma.

**Comment by StephanTLavavej** [comment]
@cpplearner is correct. `corecrt_stdio_config.h`:

```cpp
// Predefine _CRT_STDIO_ISO_WIDE_SPECIFIERS to use ISO-conforming behavior for
// the wide string printf and scanf functions (%s, %c, and %[] specifiers).
//
// Predefine _CRT_STDIO_LEGACY_WIDE_SPECIFIERS to use VC++ 2013 and earlier behavior for
// the wide string printf and scanf functions (%s, %c, and %[] specifiers).
//
// Predefine _CRT_STDIO_ARBITRARY_WIDE_SPECIFIERS when building code that does
// not use these format specifiers without a length modifier and thus can be
// used with either the legacy (default) or the conforming mode.  (This option
// is intended for use by static libraries).
#if !defined RC_INVOKED // _CRT_STDIO_LEGACY_WIDE_SPECIFIERS et al. are too long for rc
// [...]
    #if defined __cplusplus && !defined _CRT_STDIO_ARBITRARY_WIDE_SPECIFIERS
        #ifdef _CRT_STDIO_ISO_WIDE_SPECIFIERS
            #pragma detect_mismatch("_CRT_STDIO_ISO_WIDE_SPECIFIERS", "1")
        #else
            #pragma detect_mismatch("_CRT_STDIO_ISO_WIDE_SPECIFIERS", "0")
        #endif
    #endif
#endif
```

**Comment by walbourn** [comment]
So there is still a link-mismatch check for a feature that doesn't exist? Fun :)

**Comment by cpplearner** [comment]
It seems that the ISO-conforming behavior still exists, but can only be enabled by defining the undocumented macro `_CRT_STDIO_ISO_WIDE_SPECIFIERS`.

Despite being undocumented, this macro seems to be defined by libc++ when targeting MSVC.
