### ISSUE TITLE
README.md: How To Consume inconsistent with How To Build With A Native Tools Command Prompt

### ISSUE THREAD

**Issue by stevemac321** [microsoft/STL#518]
I might get involved with this project, but for now, just opening this issue, not submitting a diff.

The instructions-example for patching up your include, lib, and bin environment in a x64 msvc native command prompt is not consistent with the instructions provided in How to Build With a Native Tools Command Prompt.

If you follow the How to Build with a Native Tools Command Prompt, the instructions for patching up your environment should look like this:

set INCLUDE=C:\Dev\STL\build.x64\out\inc;%INCLUDE%
set LIB=C:\Dev\STL\build.x64\out\lib\amd64;%LIB%
set PATH=C:\Dev\STL\build.x64\out\bin\amd64;%PATH%

NOT:
set INCLUDE=C:\Dev\STL\out\build\x64\out\inc;%INCLUDE%
set LIB=C:\Dev\STL\out\build\x64\out\lib\amd64;%LIB%
set PATH=C:\Dev\STL\out\build\x64\out\bin\amd64;%PATH%

VS community 16.5
Also, you checked in run.pl etc., I guess its just for internal use running vctools.  It would be nice to be able to run the tests.

**Comment by StephanTLavavej** [comment]
> Also, you checked in run.pl etc., I guess its just for internal use running vctools.

Yep, that's part of our Microsoft-internal test harness. 

> It would be nice to be able to run the tests.

Absolutely. That work is in progress, tracked by #143, #144, #145, and #153.
