### ISSUE TITLE
<array>: to_array +d1initall = bogus data

### ISSUE THREAD

**Issue by tiagomacarios** [microsoft/STL#5180]
This code:
https://godbolt.org/z/fnjhPoPb7

```c++
#include <array>
#include <string_view>
#include <iostream>

inline constexpr std::array a = std::to_array<std::string_view>({ "a", "a"});

int main()
{
    for (auto &v : a)
        std::cout << "'" << v << "',";
}
```

When compiled with `-d1initall1023 -d1initAll:FillPatternE2` prints `'','a',`. The correct answer should be `'a','a',`. For larger arrays all but the last value will be zero.

**Comment by frederick-vs-ja** [comment]
Looks like a bug of MSVC in constant evaluation. If `a` is made a non-constexpr variable of automatic storage duration, the result becomes correct.

**Comment by frederick-vs-ja** [comment]
Reduced and reported DevCom-10812330. Workaround doesn't seem possible to me.

**Comment by CaseyCarter** [comment]
> Workaround doesn't seem possible to me.

Is it plausible to use `string_view` literals (https://godbolt.org/z/h11bMqd7x) instead?

**Comment by CaseyCarter** [comment]
I suppose I'll close this since I think there's no STL issue here. @tiagomacarios, please follow up with DevCom-10812330 (and upvote if you really care when it gets fixed).
