### ISSUE TITLE
Standard pre-processor define for ARM64?

### ISSUE THREAD

**Issue by jamespack** [microsoft/STL#5200]
This may not be the right place to ask/report this forgive me if it's not. While compiling OpenSSL using clang-cl you get a build error for implicit function declarations `[-Wimplicit-function-declaration]` for `InterlockedAdd64`.  The function is not defined because the default preprocessor defines do not include `__aarch64__`  `ARM64` seems be default. I put together a minimum reproducible example at [jamespack\clang-cl-bug](https://github.com/jamespack/clang-cl-bug). I realize its clang but its included in the vs sdk. So im not sure who owns it. Also not entirely sure its a "bug" I could be misunderstanding.

`C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\Llvm\ARM64\lib\clang\18\include\intrin.h`

**Comment by cpplearner** [comment]
It seems to me that clang-cl does define `__aarch64__` when targeting ARM64, and thus `intrin.h` will provide `_InterlockedAdd64` as expected.

However, note that `intrin.h` only provides `_InterlockedAdd64`, with a leading underscore.  [`InterlockedAdd64`](https://learn.microsoft.com/en-us/windows/win32/api/winnt/nf-winnt-interlockedadd) (without an underscore) exists, but is a part of the Windows API, and is only available if `<winnt.h>` or `<Windows.h>` is included.

**Comment by jamespack** [comment]
I see. So more likely a build chain issue with OpenSSL then.
