### ISSUE TITLE
STL: Avoid declaring multiple variables on a single line

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#522]
In the STL, we conventionally avoid declaring multiple variables on a single line. That is:

```cpp
int cats, dogs; // we avoid this style

int meow; // we prefer this style
int woof;
```

Our reasons for this convention are:

1. Being aware of the variables in a class or function is important, because humans have difficulty reasoning about program state (especially when it's modifiable). Consistently declaring one variable per line makes it clear when variables are being introduced, and whether they're initialized. (It also makes it "feel costly" to declare many variables, which is subtle encouragement to avoid introducing unnecessary state.)
2. C++'s rules for multi-variable declarations are surprising to newer programmers. (In particular, the rules when pointers are involved.) Avoiding such declarations avoids the need to learn/teach/read that bit of complexity.

We're pretty consistent about following this convention, but there are a few files that should be changed. I observe the following occurrences (there may be more):

https://github.com/microsoft/STL/blob/fffbd8fe05cd1a21adf2284eb6acef69e982b3c7/stl/inc/random#L622

https://github.com/microsoft/STL/blob/fffbd8fe05cd1a21adf2284eb6acef69e982b3c7/stl/inc/xiosbase#L511
https://github.com/microsoft/STL/blob/fffbd8fe05cd1a21adf2284eb6acef69e982b3c7/stl/inc/xiosbase#L532
https://github.com/microsoft/STL/blob/fffbd8fe05cd1a21adf2284eb6acef69e982b3c7/stl/inc/xiosbase#L540

https://github.com/microsoft/STL/blob/fffbd8fe05cd1a21adf2284eb6acef69e982b3c7/stl/inc/cvt/wbuffer#L264

https://github.com/microsoft/STL/blob/fffbd8fe05cd1a21adf2284eb6acef69e982b3c7/stl/src/filesys.cpp#L317

https://github.com/microsoft/STL/blob/fffbd8fe05cd1a21adf2284eb6acef69e982b3c7/stl/src/xstol.cpp#L21

https://github.com/microsoft/STL/blob/fffbd8fe05cd1a21adf2284eb6acef69e982b3c7/stl/src/xstoll.cpp#L19

https://github.com/microsoft/STL/blob/fffbd8fe05cd1a21adf2284eb6acef69e982b3c7/stl/src/xstoul.cpp#L35-L36
https://github.com/microsoft/STL/blob/fffbd8fe05cd1a21adf2284eb6acef69e982b3c7/stl/src/xstoul.cpp#L40

https://github.com/microsoft/STL/blob/fffbd8fe05cd1a21adf2284eb6acef69e982b3c7/stl/src/xstoull.cpp#L27-L29
https://github.com/microsoft/STL/blob/fffbd8fe05cd1a21adf2284eb6acef69e982b3c7/stl/src/xstoull.cpp#L31

https://github.com/microsoft/STL/blob/fffbd8fe05cd1a21adf2284eb6acef69e982b3c7/stl/src/xxxprec.h#L70
https://github.com/microsoft/STL/blob/fffbd8fe05cd1a21adf2284eb6acef69e982b3c7/stl/src/xxxprec.h#L105
https://github.com/microsoft/STL/blob/fffbd8fe05cd1a21adf2284eb6acef69e982b3c7/stl/src/xxxprec.h#L212

* These occurrences are weird-looking, but should be treated similarly:

https://github.com/microsoft/STL/blob/fffbd8fe05cd1a21adf2284eb6acef69e982b3c7/stl/inc/iostream#L21-L29
https://github.com/microsoft/STL/blob/fffbd8fe05cd1a21adf2284eb6acef69e982b3c7/stl/inc/iostream#L33-L41

https://github.com/microsoft/STL/blob/fffbd8fe05cd1a21adf2284eb6acef69e982b3c7/stl/inc/ymath.h#L48
https://github.com/microsoft/STL/blob/fffbd8fe05cd1a21adf2284eb6acef69e982b3c7/stl/inc/ymath.h#L56
https://github.com/microsoft/STL/blob/fffbd8fe05cd1a21adf2284eb6acef69e982b3c7/stl/inc/ymath.h#L64

* Finally, the occurrences in `xcharconv_ryu.h` should **not** be changed at this time (as this code is kept in sync with the upstream Ryu project):

https://github.com/microsoft/STL/blob/fffbd8fe05cd1a21adf2284eb6acef69e982b3c7/stl/inc/xcharconv_ryu.h#L1061
https://github.com/microsoft/STL/blob/fffbd8fe05cd1a21adf2284eb6acef69e982b3c7/stl/inc/xcharconv_ryu.h#L1751

I found all of these occurrences by using VSCode to regex-search for `(\w+)(, \*?\w+)+;` excluding files in `tests/*`.

**Comment by JeanPhilippeKernel** [comment]
you can assign me this ?

**Comment by StephanTLavavej** [comment]
Sure - we look forward to a PR. (We're currently working through our PR backlog in addition to the LWG issues and features that were recently voted in at the Prague meeting, which is why I haven't reviewed your other PR #497 again - hopefully I will have time soon! :-)
