### ISSUE TITLE
<random>: LWG-3150 has been accepted, so we should remove a comment

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#528]
In VS 2019 16.3, we shipped the following code:

https://github.com/microsoft/STL/blob/e03429600efd951791ba4a903b449fac7473bef9/stl/inc/random#L63-L72

The comment noted that we were speculatively implementing the Proposed Resolution for the Library Issue LWG-3150 "`UniformRandomBitGenerator` should validate `min` and `max`". (Library Issues are bug reports against the C++ Standard.)

At the February 2020 meeting in Prague, LWG-3150 was resolved for C++20. Now that we're implementing what the Working Paper specifies, we should remove this `#if 1` and `#endif` pair, but keep the code within (as it was unconditionally active, and we want to keep doing that). Our convention is that when we're doing what the Standard says, we don't need additional comments about the history of the Standardese.

**Comment by joyceerhl** [comment]
May I submit a PR for this, @StephanTLavavej ? 😊

**Comment by StephanTLavavej** [comment]
Please do! 😸
