### ISSUE TITLE
LWG-3330 Include `<compare>` from most library headers

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#545]
LWG-3330 Include `<compare>` from most library headers

**Comment by miscco** [comment]
This is addressed by #513 i believe

**Comment by StephanTLavavej** [comment]
Thanks! FYI, GitHub's [Custom Autolinks](https://github.com/microsoft/STL/wiki/Custom-Autolinks) are activated by hyphens but not underscores, so you can cite LWG-3330 in a PR but LWG_3330 won't be hyperlinked. (Although autolinks aren't active in code comments, we follow the hyphen convention for consistency.)
