### ISSUE TITLE
<filesystem>: space(R"(path\to\some\directory)") requires read access at the root level

### ISSUE THREAD

**Issue by mscottmueller** [microsoft/STL#549]
When running an application in least privileges mode, it may not be possible to obtain a successful result from std::filesystem::space(p). The conditions for this are as follows:

- The account that the thread is running as does not have read access to the root of the volume pointed to by the directory p.
- The account has read access to the directory p.

The method in the CRT that is eventually invoked by std::filesystem::space, _FS_space_attempt, makes a call to GetVolumePathNameW, which obtains the root of the path pointed to by the given directory, and then goes on to call GetDiskFreeSpaceExW with the returned root path. This particular use scenario has not been useful since the Windows 95 days, when we only had GetDiskFreeSpace.

If we use GetDiskFreeSpaceExW, we can pass in the full path without issue.

**Command-line test case**
STL version (git commit or Visual Studio version):

```
C:\Temp>type filesystem_space_LRP.cpp
// filesystem_space_LRP.cpp : This file contains the 'main' function. Program execution begins and ends there.
//
#include <Windows.h>

#include <iostream>
#include <filesystem>
#include <system_error>
// extract path parameter
int main(int argc, wchar_t* argv[])
{
   if (argc != 2)
   {
      std::wcout <<
         L"filesystem_space_LRP.exe - Demonstrate problem using std::filesytem::space\n"
         L"\t\twhen there is no read access on the root of the mounted volume.\n"
         L"\tDon't try this experiment on your OS installation drive- Use some other NTFS volume instead.\n"
         L"Usage:\n"
         L"\tfilesystem_space_LRP \"path:\\to\\folder\"\n";
      return 0;
   }
   std::filesystem::path p = argv[1];
   if (!std::filesystem::is_directory(p))
   {
      std::wcout << L"Given path \"" << p << L"\" is not a directory.\n";
      return 1;
   }
   // Call std::filesystem::space and report the error.
   try
   {
      auto s = std::filesystem::space(p);
      std::wcout << L"Call of std::filesystem::space was successful.\n"
         L"File system reported that there are " << s.available << L" bytes available.\n"
         L"Note that we expect failure, so perhaps the active user has read access to the root of the mount volume.\n";
      return 0;
   }
   catch (const std::filesystem::filesystem_error & ferr)
   {
      std::wcout << L"Filesystem error was reported as expected. The exception was " << ferr.what() << L"\n";
   }
   // Call ::GetDiskSpaceFreeExW directly.
   ULARGE_INTEGER Avail = {}, TotalBytes = {}, TotalFree = {};
   if (!::GetDiskFreeSpaceExW(p.wstring().c_str(), &Avail, &TotalBytes, &TotalFree))
   {
      std::wcout << std::system_error(std::error_code(::GetLastError(), std::system_category()), "GetDiskFreeSpaceExW returned an error").what() << L"\n";
      return 1;
   }
   std::wcout << L"GetDiskFreeSpaceExW was successful. It says that there are " << Avail.QuadPart << L" bytes available.\n";
   return 0;
}

C:\Temp>cl /permissive- /GS /GL /W4 /Zc:wchar_t /Zi /Gm- /O2 /Fd"x64\Release\vc142.pdb" /Zc:inline /fp:precise /D "NDEBUG" /D "_CONSOLE" /D "_UNICODE" /D "UNICODE" /errorReport:prompt /WX /Zc:forScope /Gd /MD /std:c++latest /FC /Fa"x64\Release\" /EHsc /nologo /Fo"x64\Release\" /Fp"x64\Release\filesystem_space_LRP.pch" /diagnostics:column .\filesystem_space_LRP.cpp
Microsoft (R) C/C++ Optimizing Compiler Version 19.23.28019.1 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

filesystem_space_LRP.cpp
Microsoft (R) Incremental Linker Version 14.23.28019.1
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:filesystem_space_LRP.exe
filesytem_space_LRP.obj

C:\Temp>.\filesytem_space_LRP.exe \Path\to\restricted\volume
```

**Expected behavior**
I expect to be able to get the available space from a folder I have read/write access to, regardless of the read permissions on the root of the volume.

**Additional context**
The underlying implementation of boost::filesystem::space makes use of GetDiskSpaceFreeExW directly, though I'd rather use std::filesystem::space since boost's system::error_code type uses POSIX translations for its error codes rather than the Windows ones.

**Comment by mscottmueller** [comment]
Also note that the current implementation of std::filesystem::space succeeds if the user running the thread does not have any access to the given path but has read access to the root of the mounted volume.

**Comment by mscottmueller** [comment]
[filesystem_space_patch.txt](https://github.com/microsoft/STL/files/4258366/filesystem_space_patch.txt)

**Comment by StephanTLavavej** [comment]
If you wish to submit a patch, please do so as a pull request - that will allow you to sign our CLA, and allow us to properly review the code. We cannot accept patches submitted as attachments.

**Comment by StephanTLavavej** [comment]
Thanks for the bug report and self-contained repro, by the way - we really appreciate it!

**Comment by mscottmueller** [comment]
Thanks Stephan,

I’ll get that done ASAP.

Best regards,

M. Scott Mueller
Staff Engineer
Core Libraries Team
OSIsoft, LLC
