### ISSUE TITLE
Support <ArmAsm> in vcxproj

### ISSUE THREAD

**Issue by am11** [microsoft/STL#551]
> <ins>Disclaimer:</ins> I realize that this is not the right place, but it is the closest repository I have found with VC team members; so I wanted to record this request. I would very much appreciate, if you could re-route it to the appropriate toolchain team. :)

Just like out-of-the-box supported `<ClCompile>` and `<MASM>` targets in vcxproj, it would great if `<ArmAsm>` is also included, so we don't need to write boilerplate configuration which includes locating the arm toolchain and serialization arguments from command line to `armasm[64].exe`. e.g. [this](https://github.com/dotnet/runtime/blob/4365af16fcf99708df04315b19eadee6e533e4bd/src/coreclr/CMakeLists.txt#L49) and [this](https://github.com/libffi/libffi/blob/6fdd0e4e2c1f0438de0c93d7284b0b916bfaffdf/configure_options.cmake#L314).

Perhaps the easiest thing to do would be to include the following in `Microsoft.Cpp.Common.props` and friends:

* https://github.com/microsoft/ChakraCore/blob/3daa567/Build/armasm.props
* https://github.com/microsoft/ChakraCore/blob/3daa567/Build/armasm.targets
* https://github.com/microsoft/ChakraCore/blob/3daa567/Build/armasm.xml

their usage look just like `<ClCompile>` or `<MASM>`: [example](https://github.com/microsoft/ChakraCore/blob/3daa567/lib/Runtime/Library/Chakra.Runtime.Library.vcxproj.filters#L257).

Thank you & Best Regards!

**Comment by StephanTLavavej** [comment]
https://github.com/microsoft/STL#reporting-issues

> You can report STL bugs here, where they'll be directly reviewed by maintainers. You can also report STL bugs through [Developer Community][], or the VS IDE (Help > Send Feedback > Report a Problem...).
>
> **Please help us** efficiently process bug reports by following these rules:
>
> * Only STL bugs should be reported here. If it's a bug in the compiler, CRT, or IDE, please report it through Developer Community or Report A Problem.

[Developer Community]: https://developercommunity.visualstudio.com/spaces/62/index.html

This will allow the Visual Studio team to follow up with you, which is one of the reasons why the STL team has this policy mentioned in the README. (Another reason is that if we relayed IDE, MSBuild, compiler, etc. issues, we wouldn't have time to implement C++20 library features, fix bugs, and review pull requests.)

**Comment by am11** [comment]
Thanks, I missed that bit. I have submitted the feedback over at community portal: https://developercommunity.visualstudio.com/idea/932193/support-in-vcxproj.html.
