### ISSUE TITLE
P0586R2 Integer Comparison Functions

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#560]
[P0586R2](https://wg21.link/P0586R2) Integer Comparison Functions

**NOTE:** This paper proposed a feature-test macro named `__cpp_lib_cmp_equal`. When this paper was accepted at the February 2020 meeting in Prague, this was renamed to `__cpp_lib_integer_comparison_functions` as part of that vote. The value is presumably `202002L` (we need to double-check this).

**Comment by Neargye** [comment]
The link to P0586R2 is 404.

**Comment by StephanTLavavej** [comment]
That’s expected; thanks for reporting it. I should have added this note to the issues I filed for features accepted at the Prague meeting (we now have it in an issue template for future features):

Note: If this link appears to be broken, don't worry! Papers are often revised during a WG21 meeting before the final vote. When that happens, there's a delay of a few weeks between the end of the meeting and the publication of the papers. When the papers are available, the https://wg21.link redirector will start working.

**Comment by Neargye** [comment]
Thanks for the clarification, I will know.
