### ISSUE TITLE
STL: Use __cpp_lib_byte for detection

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#564]
See #204 for the background story.

Currently, we define the "control macro" `_HAS_STD_BYTE` here:
https://github.com/microsoft/STL/blob/d4ee5c3fb4abfe8492f2108384d6f4e0fd0afeae/stl/inc/yvals_core.h#L510-L512

And then `_HAS_STD_BYTE` controls the Standard feature-test macro `__cpp_lib_byte`:
https://github.com/microsoft/STL/blob/d4ee5c3fb4abfe8492f2108384d6f4e0fd0afeae/stl/inc/yvals_core.h#L1015-L1017

What `yvals_core.h` (the STL's central internal header) is doing is good. The issue is that the rest of the STL inspects `_HAS_STD_BYTE` to determine whether `std::byte` is available. It would be more consistent with our modern conventions for the rest of the STL to use `__cpp_lib_byte` to determine whether `std::byte` is available.

Notes:

1. `_HAS_STD_BYTE` follows the convention of always being defined to either `0` or `1`, so we test it with `#if`. `__cpp_lib_byte` follows the convention of not being defined, or being defined to a specific value (we aren't concerned about the specific value here). While the Standard allows such macros to be tested with `#if` because `#if SOMETHING_NOT_DEFINED_AS_A_MACRO` is treated as `#if 0`, that triggers an off-by-default compiler warning, so we always use `#ifdef` for macros that may or may not be defined.
2. We comment `#endif` directives so we can match them up with `#if`, `#ifdef`, or `#ifndef`.

So, we should change:

```cpp
#if _HAS_STD_BYTE
#endif // _HAS_STD_BYTE
```

to:

```cpp
#ifdef __cpp_lib_byte
#endif // __cpp_lib_byte
```

Excluding `yvals_core.h` which should not be changed, there are currently 3 affected files in `stl/inc` and 2 affected tests in `tests/std`. (A third test, `tests/std/tests/VSO_0157762_feature_test_macros/test.cpp`, is inspecting the relationship between `_HAS_STD_BYTE` and `__cpp_lib_byte`, so it should not be changed.)

**Comment by JeanPhilippeKernel** [comment]
@StephanTLavavej  can you assign me this ?

**Comment by StephanTLavavej** [comment]
Sure!
