### ISSUE TITLE
VSCode: Add vcpkg toolchain file to settings.json (CMake Tools extension)

### ISSUE THREAD

**Issue by SuperWig** [microsoft/STL#571]
The following could be added to the `settings.json` for CMake Tools to use the vcpkg toolchain file.
```json
"cmake.configureSettings": {
    "CMAKE_TOOLCHAIN_FILE": "${workspaceFolder}/vcpkg/scripts/buildsystems/vcpkg.cmake"
}
```

**Comment by StephanTLavavej** [comment]
Since you're proposing a specific change, can you submit this as a PR?

**Comment by SuperWig** [comment]
Sure, I wasn't sure which would be better as providing support for an external (to this project at least) extension, figured that might warrant a discussion, Then again that could be done in the PR 🤷‍♂️.
