### ISSUE TITLE
STL: Document updating/adding tests procedure

### ISSUE THREAD

**Issue by SuperWig** [microsoft/STL#575]
Simply put, add @BillyONeal's comment somewhere https://github.com/microsoft/STL/pull/567#issuecomment-592765295

Probably by updating "Tests: Coming soon" to "Tests: WIP" with current info as well as a link to that comment?

**Comment by AlexGuteniev** [comment]
Is this still an issue?

**Comment by CaseyCarter** [comment]
At the very least, it seems we should remove the "high priority" label from this three-and-a-half-year-old bug.

**Comment by StephanTLavavej** [comment]
@CaseyCarter notes that we've certainly had lots of contributors adding tests in the last 3 years so we should just close this issue. I've added personal notes for the Contribution Guidelines that I'll be writing up to more thoroughly explain how to add tests properly, so we don't have to individually teach every new contributor.
