### ISSUE TITLE
std::stringstream is not working properly if the stream size is more than INT_MAX value.

### ISSUE THREAD

**Issue by hariupgetme** [microsoft/STL#578]
std::stringstream is not constructed properly if the stream size is more than INT_MAX value.

**Command-line test case**
STL version (VS 2015 ):
Build Target: x64
```
void fillData(std::vector<char>& buffer)
{
	size_t size(2381320200);
	buffer.reserve(size);
	for (auto i = 0ULL; i < size; i++)
		buffer.push_back('a');
}

int main()
{
	std::vector<char> buffer;
	fillData(buffer);

	std::istringstream stream(std::string(buffer.begin(), buffer.end()), std::ios::in | std::ios::binary);

	char type;

	stream.read(reinterpret_cast<char*>(&type), sizeof(type));

	if (stream.good())
		stream.seekg(0, std::ios::end);
	else
		std::cout << "Stream bad bit set after read";

	if (stream.good())
		std::istream::pos_type fileSize(stream.tellg());
	else
		std::cout << "Stream bad bit set after seek";
		
    return 0;
}

```

**Expected behavior**
The stream should be good and the bad bit message should not be displayed
**Additional context**

**Comment by AdamBucior** [comment]
That's probably caused by #388.

**Comment by StephanTLavavej** [comment]
Yes, this is a duplicate issue. Thank you for reporting it; we'll be able to use your self-contained test case.

**Comment by hariupgetme** [comment]
Hi Stephan,

Thanks for the update. When #388 will be fixed?

Thanks & Regards,
Hariharasudhan K

**Comment by CaseyCarter** [comment]
#388 will be fixed when the next ABI-breaking release of MSVC happens. While we are planning work for that, we don't yet have any kind of ETA we can share.

**Comment by jimver04** [comment]
Why the limits of the stringstream have to be explicitly stated? See how gcc implements it:
https://github.com/gcc-mirror/gcc/blob/master/libstdc%2B%2B-v3/include/std/sstream
Is there any update on the issue? At least please change INT_MAX to UINT_MAX to increase the limit from 2GB to 4GB. 
at Lines 257-258 in sstream:
https://github.com/microsoft/STL/blob/cf1313c39169dc376761eddee23c5e408e01aaa9/stl/inc/sstream#L257C1-L258C32
