### ISSUE TITLE
<yvals_core.h>: Update _MSVC_STL_UPDATE to March 2020

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#579]
Explanation on our wiki: [Macro `_MSVC_STL_UPDATE`](https://github.com/microsoft/STL/wiki/Macro-_MSVC_STL_UPDATE)

Code:
https://github.com/microsoft/STL/blob/0e46d7ab99e15591bb2f0424ff5f4c3596165b20/stl/inc/yvals_core.h#L445

Previous update: #477

This issue is intended for a new contributor (especially one new to GitHub) to get started with the simplest possible change.

**Comment by dmswjd4117** [comment]
Hi
