### ISSUE TITLE
Share implementation between std::atomic::wait for P1135R6 (#52) and parallel_algorithms.cpp

### ISSUE THREAD

**Issue by AlexGuteniev** [microsoft/STL#598]
`parallel_algorithms.cpp` uses specific case of wait-on-address, which waits on one byte.

As @BillyONeal pointed out, it makes sense to switch it to generic implementation, when such generic implementation is ready.

Even though new generic implementation would be almost identical (except that it would handle odd atomic sizes), it makes sense to switch to generic one to avoid duplication.

**Comment by StephanTLavavej** [comment]
My understanding is that because `parallel_algorithms.cpp` is injected into the import lib, changes here wouldn't affect binary compatibility, so this doesn't need to be marked as a `vNext` issue (which is good news).

**Comment by BillyONeal** [comment]
In fact, the reason the import lib trick worked for `parallel_algorithms.cpp` is that we know execution never leaves the module (that's why I was able to get away with avoiding a satellite DLL for the parallel algorithms' missing-WaitOnAddress-fallback-lock-table).

**Comment by AlexGuteniev** [comment]
How should code be shared? By linking to atomic wait satellite dll/lib?

Also, it would make atomic_wait needing XP fallback. There is a solution with #including one piece of code to two `.cpp`, but it does not look like a good solution.

**Comment by AlexGuteniev** [comment]
Incorporated this change into #593 , tests pass.
