### ISSUE TITLE
P0202R3 constexpr For <algorithm> And exchange()

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#6]
[P0202R3](https://wg21.link/P0202R3) `constexpr` For `<algorithm>` And `exchange()`

LWG-3256 Feature testing macro for `constexpr` algorithms

<s>This needs #156 `is_constant_evaluated()`.</s>

Feature-test macro as of WG21-N4842:
* If this feature is implemented, but #38 WG21-P0879 is **not** implemented:
`#define __cpp_lib_constexpr_algorithms 201703L`
* If both this feature and #38 WG21-P0879 are implemented:
`#define __cpp_lib_constexpr_algorithms 201806L`

**Comment by BillyONeal** [comment]
I'm starting this and hope to get the `<xutility>` family constexprized shortly.

**Comment by BillyONeal** [comment]
Should we turn on the feature test macro for this even though some algorithms will break due to DevCom-883631 ?

**Comment by BillyONeal** [comment]
(e.g. so far some calls to is_permutation will trigger it)

**Comment by CaseyCarter** [comment]
> Should we turn on the feature test macro for this even though some algorithms will break due to [DevCom-883631](https://developercommunity.visualstudio.com/content/problem/883631/meow.html) ?

Yes, I believe we should. I wouldn't say that we don't support `is_permutation` at runtime if there were argument types for which the compiler generates bogus diagnostics or values for which it generates bad code, and this seems like the `constexpr` flavor of such cases.

**Comment by BillyONeal** [comment]
p0202r3:
* all_of
* any_of
* none_of
* for_each
* for_each_n
* find
* find_if
* find_end
* find_first_of
* adjacent_find
* count
* count_if
* mismatch
* equal
* is_permutation
* search
* search_n
* copy
* copy_backward
* move
* move_backward
* transform
* replace
* replace_if
* replace_copy
* replace_copy_if
* fill
* fill_n
* generate
* generate_n
* remove
* remove_if
* remove_copy
* remove_copy_if
* unique
* unique_copy
* reverse_copy
* rotate_copy
* is_partitioned
* partition_copy
* partition_point
* is_sorted
* is_sorted_until
* lower_bound
* upper_bound
* equal_range
* binary_search
* merge
* includes
* set_union
* set_intersection
* set_difference
* set_symmetric_difference
* is_heap
* is_heap_until
* lexicographical_compare
* exchange

**Comment by BillyONeal** [comment]
I asked libc++ folks how they would like submitted tests for this since they would fail, and didn't get a reasonable answer, so I'm going to go ahead and do an internal-only test for the missing algorithms, as well as the ones that needed explicit is_constant_evaluated tests.
