### ISSUE TITLE
get_temporary_buffer does not operate as intended.

### ISSUE THREAD

**Issue by pi1024e** [microsoft/STL#604]
**Describe the bug**
The idea is that a system may keep a number of fixed-sized buffers ready for fast allocation so that requesting space for n objects may yield space for more than n. It may also yield less, however, so one way of using get_temporary_buffer() is to optimistically ask for a lot and then use what happens to be available.

However, the current implementation of this tries to ask for a large amount of memory and then gets smaller until the allocation happens. It would be better to allocate while knowing from the OS itself the right memory chunk to allocate, as originally designed.

**Expected behavior**
We ask the OS for the correct size, and get the OS memory management involved

**STL version**
https://github.com/microsoft/STL/commit/285187b7b24be4bebfa271fbd0b1eacd995d18f4

**Comment by CaseyCarter** [comment]
`get_temporary_buffer` and `return_temporary_buffer` have been removed from C++20. At this point, I think the negative effects from changing the behavior to differ from that expected by existing programs outweigh any potential benefits from changing that behavior.

**Comment by StephanTLavavej** [comment]
Agreed; I'm going to resolve this as `wontfix`. Thanks for the suggestion; we appreciate it even though we're choosing not to modify the product code here.
