### ISSUE TITLE
CMakeLists.txt: /O2 is not working

### ISSUE THREAD

**Issue by AlexGuteniev** [microsoft/STL#608]
Maybe I'm doing something wrong, but to me looks like Release build is not correctly configured.

Root make file has **VCLIBS_RELEASE_FLAGS** 

https://github.com/microsoft/STL/blob/285187b7b24be4bebfa271fbd0b1eacd995d18f4/CMakeLists.txt#L67-L70

Stl make file has **VCLIBS_RELEASE_OPTIONS**

https://github.com/microsoft/STL/blob/285187b7b24be4bebfa271fbd0b1eacd995d18f4/stl/CMakeLists.txt#L474-L477

https://github.com/microsoft/STL/blob/285187b7b24be4bebfa271fbd0b1eacd995d18f4/stl/CMakeLists.txt#L488-L493

That's why I don't observe any optimization. I mean when I'm adding  **VCLIBS_RELEASE_OPTIONS** to root make file I start at least seeing inlining of functions.

**Comment by StephanTLavavej** [comment]
Yep, looks like a clear typo to me. Good catch!
