### ISSUE TITLE
Should STL specifically consider /Ob1 ?

### ISSUE THREAD

**Issue by AlexGuteniev** [microsoft/STL#619]
This is not an issue, just a question.

Should STL be optimized for /Ob1 build?

I mean if release is built with /O2 and /Ob1, a significant part of STL is inlined, since it is inline members of template class. Still template functions defined outside classes are not marked as `inline` and thus are not inlined.

(A project may be built with /O2 + /Ob1 if it does not benefit from /Ob2, and has degraded performance comparing to /Ob1. On the other hand, it is rather unusual case)

**Comment by StephanTLavavej** [comment]
The STL expects extensive inlining due to its reliance on small helper functions, and therefore I believe that /Ob1 is the wrong direction - if anything, the STL wants the new /Ob3 option (not implied by /O2, but perhaps in the future). I don’t have hard data, though.

**Comment by StephanTLavavej** [comment]
@BillyONeal mentioned that if you can find performance test cases where /Ob1 is superior to /Ob2 or /Ob3, we can look into changing this option.
