### ISSUE TITLE
P1614R2 Adding Spaceship <=> To The Library

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#62]
[P1614R2](https://wg21.link/P1614R2) Adding Spaceship `<=>` To The Library

LWG-3324 Special-case `std::strong/weak/partial_order` for pointers
LWG-3347 `std::pair<T, U>` now requires `T` and `U` to be less-than-comparable
LWG-3350 Simplify return type of `lexicographical_compare_three_way`
LWG-3354 `has_strong_structural_equality` has a meaningless definition
LWG-3380 `common_type` and comparison categories
LWG-3426 `operator<=>(const unique_ptr<T, D>&, nullptr_t)` can't get no satisfaction
LWG-3427 `operator<=>(const shared_ptr<T>&, nullptr_t)` definition ill-formed
LWG-3432 Missing requirement for `comparison_category`

Feature-test macro as of WG21-N4842 (note that WG21-P1614 proposed `__cpp_lib_spaceship` which was removed by WG21-P1902. Instead, `__cpp_lib_three_way_comparison` which was added for #64 WG21-P0768 "Library Support For The Spaceship Comparison Operator `<=>`" is being increased):
`#define __cpp_lib_three_way_comparison 201907L`

**Comment by CaseyCarter** [comment]
NOTE: The changes to `common_type` are unnecessary after application of [P1959R0 "Remove std::weak_equality and std::strong_equality"](https://wg21.link/p1959r0); we have test coverage to validate this, and have submitted an LWG issue to revert P1614R2's changes to `common_type`.
