### ISSUE TITLE
<unordered_map>: Heterogenous lookup not working

### ISSUE THREAD

**Issue by dgengin** [microsoft/STL#623]
**Describe the bug**
When creating an empty Console App project in Visual Studio and setting `std:c++latest`, this code won't compile. It's using heterogenous lookup for unordered containers which is said to be implemented in 16.5.

**Create a Console App project**
```c++
#include <iostream>
#include <string>
#include <string_view>
#include <unordered_map>

int main()
{
    std::unordered_map<std::string, int> map;
    map["test"] = 1;                              // converts to std::string
    auto it = map.find(std::string_view("test")); // should compile
    return 0;
}
```

**Expected behavior**
This code should compile, heterogenous lookup is included in this version.

**STL version**
    ```
    Microsoft Visual Studio Community 2019
    Version 16.5.0
    ```

**Additional context**
No option was changed from the `Console App` template, except for `std:c++latest`

**Comment by miscco** [comment]
That seems like it is working as expected/required. 

To enable heterogenuous lookup you need to pass a comparator object that has the type `is_transparent` defined. 

Please have a look at the great explanation for the abseil [TipOfTheWeek](https://abseil.io/tips/144) blog

**Comment by dgengin** [comment]
Thanks for the answer. My code isn't valid, true. I can get it to work with maps (I could before).

However, this "fixed" code should work and doesn't.

taken from: http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p0919r3.html#design-function-template

unorderd_map: - doesn't work

```cpp
#include <string>
#include <string_view>
#include <unordered_map>

int main()
{
    struct string_hash {
        using transparent_key_equal = std::equal_to<>;  // Pred to use
        using hash_type = std::hash<std::string_view>;  // just a helper local type
        size_t operator()(std::string_view txt) const { return hash_type{}(txt); }
        size_t operator()(const std::string& txt) const { return hash_type{}(txt); }
        size_t operator()(const char* txt) const { return hash_type{}(txt); }
    };

    std::unordered_map<std::string, int, string_hash> map;
    map["test"] = 1;                              // converts to std::string
    auto it = map.find(std::string_view("test")); // should compile
    return 0;
}
```

I know it's probably something simple, I just can't see what it is.


map: - works

```cpp
#include <string>
#include <string_view>
#include <map>

int main()
{
    struct StringCmp {
        using is_transparent = void;
        bool operator()(std::string_view a, std::string_view b) const {
            return a < b;
        }
    };

    std::map<std::string, int, StringCmp> map;
    map["test"] = 1;                              // converts to std::string
    auto it = map.find(std::string_view("test")); // should compile
    return 0;
}
```

**Comment by miscco** [comment]
I believe this was changed recently. If you look at the link that I gave you or [cppreference](https://en.cppreference.com/w/cpp/container/unordered_map/find) you will see that you need `is_transparent` for both The comparator and the hasher. That is a pain but so is C++

**Comment by miscco** [comment]
For mee it works once I fixed all the little typos: https://godbolt.org/z/6BfqbS

**Comment by dgengin** [comment]
yes, I got it to work. for reference:

```cpp
#include <string>
#include <string_view>
#include <unordered_map>

int main()
{
    struct string_hash_eq {
        using is_transparent = void;
        using transparent_key_equal = std::equal_to<>;  // Pred to use
        using hash_type = std::hash<std::string_view>;  // just a helper local type
        size_t operator()(std::string_view txt) const { return hash_type{}(txt); }
        size_t operator()(const std::string& txt) const { return hash_type{}(txt); }
        size_t operator()(const char* txt) const { return hash_type{}(txt); }

        size_t operator()(std::string_view txt, std::string_view txt2) const { return transparent_key_equal{}(txt, txt2); }
        size_t operator()(const std::string& txt, const std::string& txt2) const { return transparent_key_equal{}(txt, txt2); }
        size_t operator()(const char* txt, const char* txt2) const { return transparent_key_equal{}(txt, txt2); }
    };

    std::unordered_map<std::string, int, string_hash_eq, string_hash_eq> map;
    map["test"] = 1;
    auto it = map.find(std::string_view("test"));
    return 0;
}
```

Thanks.

**Comment by CaseyCarter** [comment]
As @miscco says, the interface for heterogeneous comparisons was recently changed by WG21-P1690. Thanks @missco!
