### ISSUE TITLE
What is the feature testing macro for MSVC STL?

### ISSUE THREAD

**Issue by expnkx** [microsoft/STL#628]
How can I detect I am using MSVC's STL on clang?

**Comment by expnkx** [comment]
#if defined(_MSVC_STL_UPDATE)
???

**Comment by StephanTLavavej** [comment]
Yes, see [Macro `_MSVC_STL_UPDATE`](https://github.com/microsoft/STL/wiki/Macro-_MSVC_STL_UPDATE) on the wiki.
