### ISSUE TITLE
<streambuf> std::basic_streambuf's layout wastes a bunch of space

### ISSUE THREAD

**Issue by expnkx** [microsoft/STL#636]
https://github.com/expnkx/fast_io/blob/master/include/fast_io_legacy_impl/cpp/libstdc%2B%2B_libc%2B%2B.h
https://github.com/expnkx/fast_io/blob/master/include/fast_io_legacy_impl/cpp/msvc_stl.h

private:
    _Elem* _Gfirst; // beginning of read buffer
    _Elem* _Pfirst; // beginning of write buffer
    _Elem** _IGfirst; // pointer to beginning of read buffer
    _Elem** _IPfirst; // pointer to beginning of write buffer
    _Elem* _Gnext; // current position in read buffer
    _Elem* _Pnext; // current position in write buffer
    _Elem** _IGnext; // pointer to current position in read buffer
    _Elem** _IPnext; // pointer to current position in write buffer
    int _Gcount; // length of read buffer
    int _Pcount; // length of write buffer
    int* _IGcount; // pointer to length of read buffer
    int* _IPcount; // pointer to length of write buffer
protected:
    locale* _Plocale; // pointer to imbued locale object

libstdc++ or libc++'s implementations
https://github.com/expnkx/fast_io/blob/master/include/fast_io_legacy_impl/cpp/libstdc%2B%2B_libc%2B%2B.h
/*
https://github.com/gcc-mirror/gcc/blob/master/libstdc%2B%2B-v3/include/std/streambuf
*  This is based on _IO_FILE, just reordered to be more consistent,
*  and is intended to be the most minimal abstraction for an
*  internal buffer.
*  -  get == input == read
*  -  put == output == write
char_type* 		_M_in_beg;     ///< Start of get area.
char_type* 		_M_in_cur;     ///< Current read area.
char_type* 		_M_in_end;     ///< End of get area.
char_type* 		_M_out_beg;    ///< Start of put area.
char_type* 		_M_out_cur;    ///< Current put area.
char_type* 		_M_out_end;    ///< End of put area.
/// Current locale setting.
locale 			_M_buf_locale;
libc++
https://github.com/llvm-mirror/libcxx/blob/master/include/streambuf
    locale __loc_;
    char_type* __binp_;
    char_type* __ninp_;
    char_type* __einp_;
    char_type* __bout_;
    char_type* __nout_;
    char_type* __eout_;
*/

Why does MSVC STL have so many fields for std::basic_streambuf compared libstdc++'s libc++'s implementations where they just simply use 6 pointers? I believe msvc's implementation will bring more cache locality issues because of 2 level's of pointer redirection.

I guess it is because of the underlining CRT and you guys want to map it directly. I understand that.

https://github.com/expnkx/fast_io/blob/master/include/fast_io_legacy_impl/c/msvcrt.h
https://github.com/expnkx/fast_io/blob/master/include/fast_io_legacy_impl/c/universal_crt.h

However, it is still possible not to do this, just like libstdc++ is doing here. Implement 3 classes, one for sync_stdio_filebuf, one for stdio_filebuf, one for std::filebuf. I believe the performance will greatly improved with fstream.

For me, I am doing memcpy hacks to get these private data members. Is that undefined behavior?

**Comment by BillyONeal** [comment]
Changing this would be ABI breaking. The reason for most of this complexity is due to the `_get_stream_buffer_pointers` dance where `_Gfirst`, `_Pfirst`, `_Gnext`, `_Pnext` etc. are *deactivated* and not used because we are using the internal buffering behind the FILE*.

**Comment by expnkx** [comment]
> Changing this would be ABI breaking. The reason for most of this complexity is due to the `_get_stream_buffer_pointers` dance where `_Gfirst`, `_Pfirst`, `_Gnext`, `_Pnext` etc. are _deactivated_ and not used because we are using the internal buffering behind the FILE*.

So you guys are technically using msvcrt and ucrt's like the hacks I do?
https://github.com/expnkx/fast_io/blob/master/include/fast_io_legacy_impl/c/msvcrt.h
https://github.com/expnkx/fast_io/blob/master/include/fast_io_legacy_impl/c/universal_crt.h

**Comment by expnkx** [comment]
> Changing this would be ABI breaking. The reason for most of this complexity is due to the `_get_stream_buffer_pointers` dance where `_Gfirst`, `_Pfirst`, `_Gnext`, `_Pnext` etc. are _deactivated_ and not used because we are using the internal buffering behind the FILE*.

It looks like C++'s I/O system needs a completely revamped. Or these band fix looks likey always breaking something.
If we do not try to fix the problems, iostream will get continued banned widely.

**Comment by BillyONeal** [comment]
>iostream will get continued banned widely.

I don't necessarily see that as a problem. C++20 gets std::format in large part to move in that direction.

**Comment by expnkx** [comment]
> > iostream will get continued banned widely.
> 
> I don't necessarily see that as a problem. C++20 gets std::format in large part to move in that direction.

Unfortunately, it is not. std::format will create std::string randomly which kills performance.

**Comment by BillyONeal** [comment]
That is way less expensive than the piles of virtual dispatch and locale lookup stuff streams are mandated to do.

**Comment by expnkx** [comment]
> That is way less expensive than the piles of virtual dispatch and locale lookup stuff streams are mandated to do.

TBH, it depends. You can still get faster code by using charconv + fwrite.

**Comment by expnkx** [comment]
> That is way less expensive than the piles of virtual dispatch and locale lookup stuff streams are mandated to do.

These kinds of bandfix is huge issue for me. They never work with each other in any meaningful way. I can do in place parsing/formating instead of using a temporary buffer and then fwrite.

**Comment by expnkx** [comment]
It is the kind of situation our exception is facing now.

Violate the zero-overhead principle.
Largely banned.
We create stuffs doing exactly what stream is doing now

C++17 filesystem is poorly designed library which has TOCTTOU vulnerability defects.
charconv: doing exactly what iostream is doing
networking: doing exactly what iostream is doing
process proposal: doing exactly what iostream is doing
LLFIO: doing exactly what iostream is doing
C++20 format: doing exactly what iostream is doing

These features were never designed to work with each other. I feel it is a total disaster for the language.

**Comment by miscco** [comment]
I would argue that the desig Diskussion is Vetter done at the reflector vor even Vetter directly at the meetings.

Bzw I do not geht the point about `std::fmt` because it is intentionally locale agnostic.

Also zero overhead neither implies zero cost nor that a less generic usw case should be preferred.

**Comment by BillyONeal** [comment]
@expnkx I've salvaged the meaningful bug report out of this. this isn't a place to wax poetic about things the committee does you don't like. Please keep the discussion on topic and in keeping with the [Code of Conduct](https://opensource.microsoft.com/codeofconduct/).

**Comment by expnkx** [comment]
> @expnkx I've salvaged the meaningful bug report out of this. this isn't a place to wax poetic about things the committee does you don't like. Please keep the discussion on topic and in keeping with the [Code of Conduct](https://opensource.microsoft.com/codeofconduct/).

It looks like the problem is going to be fixed. I close it.

**Comment by expnkx** [comment]
> I would argue that the desig Diskussion is Vetter done at the reflector vor even Vetter directly at the meetings.
> 
> Bzw I do not geht the point about `std::fmt` because it is intentionally locale agnostic.
> 
> Also zero overhead neither implies zero cost nor that a less generic usw case should be preferred.

Wrong. Locale is just a useless and terrible designs and only idoits use it.
