### ISSUE TITLE
Total length of gslice computed incorrectly

### ISSUE THREAD

**Issue by j6t** [microsoft/STL#663]
Found via code inspection:

https://github.com/microsoft/STL/blob/811c8c181626382ee26ea85e6963843cb17ce53e/stl/inc/valarray#L1001-L1004

`gslice::_Totlen()` must compute the total length by multiplying the sub-slice lengths. But it uses element 0 twice. The loop should start at index 1 instead of 0.

**Comment by miscco** [comment]
That is truely cursed code.

Do you see the `++_Idx` in the loop condition.

So the code does indeed work has intended. It is just highly unusual

**Comment by j6t** [comment]
*slaps forehead* Of course, you are right. All is well. Sorry for the noise.

**Comment by CaseyCarter** [comment]
This *is* subtle - feel free to submit a PR with a comment to clarify the code, or change the loop header to a more conventional `for (size_t _Idx = 1; _Idx < _Len.size(); ++_Idx)`, which I think would avoid confusion.

**Comment by StephanTLavavej** [comment]
I filed a separate issue, because there are several occurrences in both `<valarray>` and `<random>`. Thanks for noticing this!
