### ISSUE TITLE
<bitset>: bitset::all uses bitset::count when it should work like bitset::any

### ISSUE THREAD

**Issue by CaseyCarter** [microsoft/STL#669]
`bitset::all`:

https://github.com/microsoft/STL/blob/8e8453c67723cc28a2773fbb8eacd5821f059386/stl/inc/bitset#L402-L404

could early-return upon finding the first non-set bit, but it does not. It should instead work somewhat like `bitset::any`:

https://github.com/microsoft/STL/blob/8e8453c67723cc28a2773fbb8eacd5821f059386/stl/inc/bitset#L388-L393

although taking special care with the final word since some bits are zero padding when the number of bits in the set isn't a multiple of the word size.

**Comment by AlexGuteniev** [comment]
Depends whether `true` or `false` is expected. If `true` is expected, &ing unconditionally all bits could perform better, as it would be vectorized. Unfortunately, standard does not provide a "hint" parameter, so I guess unbiased implementation indeed should return early.

**Comment by BillyONeal** [comment]
An implementation that stops early could be vectorized too.

**Comment by AlexGuteniev** [comment]
How? I see that by default only non-stop is vectorized: https://godbolt.org/z/kA6aGZ

**Comment by BillyONeal** [comment]
@AlexGuteniev By loading a vector register of input, inverting it, then feeding it to `ptest`. I don't know if autovectorizers will do that.

**Comment by AlexGuteniev** [comment]
I see. I don't understand manual vectorizing, so from the observation that auto vectorizing does not happen for loops with termination condition, I assumed it was impossible.

**Comment by BillyONeal** [comment]
> I see. I don't understand manual vectorizing, so from the observation that auto vectorizing does not happen for loops with termination condition, I assumed it was impossible.

If you want to understand better dig around on https://software.intel.com/sites/landingpage/IntrinsicsGuide/ :)

**Comment by BillyONeal** [comment]
(And here's the equivalent for ARM: https://developer.arm.com/architectures/instruction-sets/simd-isas/neon/intrinsics )

**Comment by AlexGuteniev** [comment]
@BillyONeal , thanks. But honestly there are too many things I want to learn about, so priorities are determined by my project needs. Manual vectorizing is thus of lower priority, than, say, getting truth about `_mm_pause`.

There's one application of manual vectorizing I'm currenly interested in, it is https://libdivide.com . It helps avoiding division. Including that division from `chrono::steady_clock` :-) But this library already looks good enough anyway.

**Comment by AlexGuteniev** [comment]
> If you want to understand better dig around on https://software.intel.com/sites/landingpage/IntrinsicsGuide/ :)

Thanks, turned out to be a good advice. I've sorted out synchronization/cache delays in my code, now got into computation throughput limit.

A bit inconvenient that I cannot filter out floating stuff. But searching `_m64` (which is frequently an integer) and `_m128i`, `_m256i`, `_m512i` (which are always integers) seem to be a workaround.

**Comment by AlexGuteniev** [comment]
So here we would have used `_mm_test_all_ones`
