### ISSUE TITLE
<yvals_core.h>: Update _MSVC_STL_UPDATE to April 2020

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#670]
Explanation on our wiki: [Macro `_MSVC_STL_UPDATE`](https://github.com/microsoft/STL/wiki/Macro-_MSVC_STL_UPDATE)

Code:
https://github.com/microsoft/STL/blob/21944c188d28cbea41a3c04368d528fff1221f66/stl/inc/yvals_core.h#L473

Previous update: #579

This issue is intended for a new contributor (especially one new to GitHub) to get started with the simplest possible change.

**Comment by s00kee** [comment]
I'd like to give this a try. Thanks!

**Comment by StephanTLavavej** [comment]
Cool! Please submit a pull request when you're ready.

**Comment by s00kee** [comment]
First PR submitted. Thank you :)
