### ISSUE TITLE
LWG-2899 is_(nothrow_)move_constructible and tuple, optional, and unique_ptr

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#68]
LWG-2899 `is_(nothrow_)move_constructible` and `tuple`, `optional`, and `unique_ptr`

**Comment by NathanSWard** [comment]
Is this issue available to work on?

**Comment by StephanTLavavej** [comment]
Sure; I'm not aware of anyone else working on this!

* `tuple` is notoriously complicated, but the issue claims that `pair` already satisfies this constraint, and we appear to have matching code here, so I suspect that `tuple` already has correct behavior. You should verify this with manual testing.
* `unique_ptr` should be reasonably straightforward, except that constraining special member functions was "lots of fun" in C++17. See https://github.com/microsoft/STL/blob/957fe99f41748b80c3108447e5dd5ce2be962f4e/stl/inc/tuple#L558-L580 for how `tuple` had to do it (which is extra complicated due to numerous conversions being supported). The issue says that LWG-2756 already made this change for `optional` which doesn't use `tuple`'s complicated technique. I think @CaseyCarter should provide guidance here.

**Comment by CaseyCarter** [comment]
> The issue says that LWG-2756 already made this change for `optional` which doesn't use `tuple`'s complicated technique.

Yes, this issue originated as a National Body comment on C++17, and LWG-2756 was applied in the meantime. `optional` and `variant` don't use `tuple`'s complicated technique, they use a *far more complicated* technique involving conditional inheritance through layers of base classes so their special member functions can be conditionally trivial. I suggest reusing the `tuple` approach for `unique_ptr` over the machinery in `xsmf_control.h` that both `optional` and `variant` use, it will have far smaller impact on compile times.

**Comment by NathanSWard** [comment]
Thanks for the help and direction @StephanTLavavej and @CaseyCarter !
One final question, when I add the constraints, is this something I would wrap in a `_HAS_CXX20` macro block?
e.g.
```
#if _HAS_CXX20
    template<enable_if_t<is_move_constructible<_Ty>>, int> = 0>
#else 
    // nothing
#endif
    unique_ptr(unique_ptr&& other)
    //...
```

**Comment by StephanTLavavej** [comment]
Good question. The answer is no - we treat LWG issue resolutions as "defect reports" that retroactively apply to all earlier Standard versions (regardless of what they technically are according to ISO). We would make an exception for special cases where a resolution is an obnoxious source breaking change, which is very rare. So your code can be unconditional.

**Comment by NathanSWard** [comment]
@StephanTLavavej [LWG 2899](https://cplusplus.github.io/LWG/issue2899) states that `tuple(tuple&&) = default;` now has a constraint. If I understand this correctly, this means that we need to add an `enable_if_t<conjunction_v<is_move_constructible<T>...>>` for each T in the tuple's template parameters, correct?
And if so, this means it is ok to remove the `= default;` and call the correct tag constructor, correct?
