### ISSUE TITLE
Is msbuild maintained?

### ISSUE THREAD

**Issue by AlexGuteniev** [microsoft/STL#689]
Is msbuild project maintained?

**Comment by StephanTLavavej** [comment]
The `stl/msbuild` directory is part of the old Microsoft-internal build system that's currently used to build all of the flavors of the STL shipping in Visual Studio. This includes native, `/clr`, and `/clr:pure` support libraries, desktop and OneCore versions, and normal and Spectre-mitigated binaries. (For all of our supported architectures: x86, x64, ARM, and ARM64.)

Currently, the new CMake build system builds only a subset of these flavors. One of our work items is to extend the CMake system to handle all of these flavors, then change the Microsoft-internal build system to simply invoke CMake (as we already do for the ASan support libraries), then delete `stl/msbuild` forever.

When adding, deleting, or renaming source files, `stl/msbuild` must be kept in sync, even though it isn't used (or usable) in the GitHub repo. https://github.com/microsoft/STL/wiki/Files-To-Edit-When-Adding-Or-Removing-Files records those steps.

**Comment by AlexGuteniev** [comment]
Then there's a problem with #593 
I need to add new satellite without being able to automatically compile it.
Is it possible to compile msbuild project manually without Microsoft-internal build system?

**Comment by StephanTLavavej** [comment]
> Is it possible to compile msbuild project manually without Microsoft-internal build system?

Not to my knowledge. Don't worry about the MSBuild stuff - we'll take care of that. (Adding a new satellite DLL involves making several changes on the Microsoft-internal side, including the VS setup machinery that actually installs files.)

> I need to add new satellite without being able to automatically compile it.

The CMake build system does build the satellites (one flavor only); I see you're already editing `stl/CMakeLists.txt`. Is that not sufficient for your testing?

**Comment by AlexGuteniev** [comment]
> The CMake build system does build the satellites (one flavor only); I see you're already editing `stl/CMakeLists.txt`. Is that not sufficient for your testing?

That's really enough, it builds static/dynamic, debug/release, x86/x64 -- all combinations work for me.

I was just making sure that there's no effort needed from my side to make msbuild project.

**Comment by StephanTLavavej** [comment]
Thanks for checking! :smile_cat: 

If this turns out to be a common question, we could add a README to `stl/msbuild` similar to `tests/tr1/README.md`.
