### ISSUE TITLE
LWG-3158 tuple(allocator_arg_t, const Alloc&) should be conditionally explicit

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#69]
LWG-3158 `tuple(allocator_arg_t, const Alloc&)` should be conditionally explicit

**Comment by NathanSWard** [comment]
I believe I should be able to implement this if no one else already is!

**Comment by StephanTLavavej** [comment]
Sounds good! We already have `explicit(bool)` and SFINAE implementations for the other constructors, so you can follow that pattern. (Someday we hope to be able to use `explicit(bool)` unconditionally even in C++14 mode, but that is not yet possible.)

**Comment by NathanSWard** [comment]
Since [LWG 3158](https://cplusplus.github.io/LWG/issue3158) states "The expression inside explicit evaluates to true if and only if Ti is not copy-list-initializable from an empty list for at least one i", the current `_Tuple_conditional_explicit_v` will not correctly check this, correct?
This means I'll need to implement a way to check if all types are copy-list-initializable.

**Comment by StephanTLavavej** [comment]
Good catch! `_Tuple_conditional_explicit_v` isn't involved here (it's used for non-zero-argument constructors). Instead, we're currently using `_Is_implicitly_default_constructible`:

https://github.com/microsoft/STL/blob/957fe99f41748b80c3108447e5dd5ce2be962f4e/stl/inc/tuple#L259-L284

https://github.com/microsoft/STL/blob/957fe99f41748b80c3108447e5dd5ce2be962f4e/stl/inc/type_traits#L661-L672

This checks whether `_Implicitly_default_construct<_Ty>({})` is well-formed. So I believe that this part of LWG-3158 is already implemented. If you look at the issue history, this was essentially an editorial cleanup, because "implicitly default-constructible" isn't actually a Phrase of Power in the Standard, and that the (non-normative) Note explaining how to implement this was unchanged (and corresponds to what we're doing in the code).

So, `tuple(allocator_arg_t, const Alloc& a)` should use the same trait.

This could be an argument for renaming `_Is_implicitly_default_constructible` to `_Is_copy_list_initializable_from_an_empty_list`. I would accept such a renaming (it's usually nice to use the same terminology as the Standard), although I won't require it.
