### ISSUE TITLE
<functional>: std::function doesn't handle over-aligned types

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#690]
The Small Functor Optimization in `std::function` was implemented before we started to respect over-aligned types. Currently, we emit silent bad codegen when we decide to locally store an over-aligned function object.

```
C:\Temp>type meow.cpp
#include <functional>
#include <stdint.h>
#include <stdio.h>
using namespace std;

struct alignas(16) Meow {
    int i;

    void operator()() {
        printf("This should be 0: %d\n", static_cast<int>(reinterpret_cast<uintptr_t>(this) % alignof(Meow)));
    }
};

int main() {
    function<void()> f(Meow{});
    int x = 1729;
    function<void()> g(Meow{});
    f();
    g();
    (void) x;
}

C:\Temp>cl /EHsc /nologo /W4 /wd4324 meow.cpp
meow.cpp

C:\Temp>meow
This should be 0: 0
This should be 0: 8
```

@CaseyCarter observed: "I think all that's required here is to add `|| alignof(_Impl) > alignof(max_align_t)` to `_Is_large` and write a quick regression test."

https://github.com/microsoft/STL/blob/22391019cba3863a978ea2d7d3f5ca240f38c576/stl/inc/functional#L797-L798

https://github.com/microsoft/STL/blob/22391019cba3863a978ea2d7d3f5ca240f38c576/stl/inc/functional#L1065-L1069

Tracked by Microsoft-internal VSO-157296 and VSO-1062649.

**Comment by AlexGuteniev** [comment]
I think this is a bit more complex than just changing the alignment.
There should be `_ENABLE_FUNCTION_ALIGNMENT_FIX` macro.
See similar for `<atomic>:

https://github.com/microsoft/STL/blob/22391019cba3863a978ea2d7d3f5ca240f38c576/stl/inc/atomic#L1508-L1516

**Comment by StephanTLavavej** [comment]
The difference is that `std::function` performs type erasure via `virtual` while `atomic` does not.

**Comment by AlexGuteniev** [comment]
I've put a test in #698 , let's see it fail here, then proceed with the fix

**Comment by AlexGuteniev** [comment]
Seen test fail, added fix, #698 is ready

**Comment by AlexGuteniev** [comment]
@StephanTLavavej , I did what was suggested and can't understand x86 tests failure.
To me it looks like aligned allocation of underlying function object is still not aligned.

**Comment by AlexGuteniev** [comment]
Figured it out. Legitimately fails if `__cpp_aligned_new` is not there (C++14 and below). Now should pass.
