### ISSUE TITLE
Testing followup for P0722R3 Destroying delete

### ISSUE THREAD

**Issue by CaseyCarter** [microsoft/STL#693]
We can't complete activation of test coverage for destroying `delete` until an MSVC that implements the feature ships. This should be Visual Studio 2019 16.7 Preview 2. When that release ships:

* Disable skips annotated "C++20 P0722R3 "Efficient sized delete for variable sized classes" in libc++'s `skipped_tests.txt` and `expected_results.txt`

* Update the feature-test macro test bits that mention "VS 2019 16.7p1" (Yes, p1, despite that the compiler feature is actually in Preview 2.)

**Comment by StephanTLavavej** [comment]
@CaseyCarter Does this need Preview 1 or Preview 2?

**Comment by CaseyCarter** [comment]
> @CaseyCarter Does this need Preview 1 or Preview 2?

It's actually Preview 2 (I've clarified the first post a bit).
