### ISSUE TITLE
<xmemory>: `allocator_traits` assumes allocator uses raw pointers

### ISSUE THREAD

**Issue by allisonvacanti** [microsoft/STL#696]
**Describe the bug**
If `allocator_traits`'s `_Alloc` class defines a `pointer` member typedef that is not a raw pointer, the compiler emits warnings due to the `__DECLSPEC_ALLOCATOR` macro:

```
warning C4494: 'std::allocator_traits<_Alloc>::allocate' : Ignoring __declspec(allocator) because the function return type is not a pointer or reference.
```

**Expected behavior**
I expected the STL to specialize `allocator_traits` for `allocator`s that use pointer proxies and not use the `__DECLSPEC_ALLOCATOR` markup on methods that don't need it.

**STL version**
I ran into this on MSVC2015 Update 3, but it is still present in master: https://github.com/microsoft/STL/blob/master/stl/inc/xmemory#L520-L522

**Comment by CaseyCarter** [comment]
Despite the continued presence of `__DECLSPEC_ALLOCATOR` in `<xmemory>`, this is no longer a bug. We suppress C4494 globally in all STL headers - including `<xmemory>` - so no warnings should be emitted from `allocator_traits` due to this annotation. I vaguely recall this was fixed early in the VS2017 era - shout out if you need something more specific and we'll dig it up for you.

**Comment by StephanTLavavej** [comment]
And here's the machinery we use to suppress this warning STL-wide:

https://github.com/microsoft/STL/blob/a099e85ce37b2bf1a680506ee44489e24c5cb05b/stl/inc/yvals_core.h#L390
https://github.com/microsoft/STL/blob/a099e85ce37b2bf1a680506ee44489e24c5cb05b/stl/inc/yvals_core.h#L415-L416
https://github.com/microsoft/STL/blob/a099e85ce37b2bf1a680506ee44489e24c5cb05b/stl/inc/xmemory#L19-L20

This warning overhaul shipped in VS 2017 RTM. For more info, read the "Warning overhaul" section of our blog post [STL Fixes In VS 2017 RTM](https://devblogs.microsoft.com/cppblog/stl-fixes-in-vs-2017-rtm/).

**Comment by allisonvacanti** [comment]
Sounds good -- thanks for the quick and thorough responses!
