### ISSUE TITLE
GitHub: We should have means of collecting compiler and test crash dumps

### ISSUE THREAD

**Issue by BillyONeal** [microsoft/STL#697]
This probably involves something like updating https://github.com/microsoft/STL/blob/master/azure-devops/provision-image.ps1 to get [procdump](https://docs.microsoft.com/en-us/sysinternals/downloads/procdump) on the system, installing it as a postmortem debugger (the `-i` switch), and packaging up any crash dumps to Azure DevOps Artifact Services if failures are triggered.

**Comment by AlexGuteniev** [comment]
Can you also in case of tests time out list which tests are hanging and dump their processes?

(For example, the only tricky error for atomic wait based synchronization primitive is lost wake, and it results in hang; process dump will help to identify which primitive is failing)

**Comment by cbezault** [comment]
Step one would be to actually put timeouts on the tests. I unfortunately didn't set that up when I added the testing harness. There's just a global Azure Pipelines step timeout.

**Comment by StephanTLavavej** [comment]
We talked about this at the weekly maintainer meeting and concluded that this is too low priority to spend significant time on - we've survived 4 years without this capability. (Additionally, we had to remove per-test timeouts, which were originally powered by `pip` installing `psutil`; there are now automated security scans that complain about PipInstall so we ripped that code out.)
