### ISSUE TITLE
Consider reversing the order of the changelog

### ISSUE THREAD

**Issue by SuperWig** [microsoft/STL#702]
I think it would be more beneficial to have the most recent changes first. As this starts to get larger it will become harder to see what's new/coming. 

May also be worth marking unreleased versions of VS as such.

**Comment by StephanTLavavej** [comment]
Great idea, I've updated https://github.com/microsoft/STL/wiki/Changelog accordingly.

Marking the current production and preview versions would be another chore, so I've instead added a Release Availability section to the top, linking to the VS release notes where the current versions are mentioned. Hopefully that's sufficient?

In the long run, we'll probably want to "archive" old changelog sections into separate pages; major branded versions (e.g. VS 2017 versus VS 2019) is probably the right granularity for that.
