### ISSUE TITLE
STL: missing test coverage for EDG-emulating-Clang

### ISSUE THREAD

**Issue by CaseyCarter** [microsoft/STL#704]
Per discussion in https://github.com/microsoft/STL/pull/695#discussion_r406569589. IIUC, the VS IDE uses  EDG-emulating-Clang for IntelliSense for CMake project configurations that use the LLVM toolset. We should have some test coverage of EDG-emulating-Clang to ensure that it works properly with the STL.

**Comment by fsb4000** [comment]
flags to enable EDG-emulating-Clang: `/BE /dE--no_microsoft /dE--clang`
![изображение](https://github.com/microsoft/STL/assets/4289847/1fcfbf33-9f24-40a5-bfdb-cc86b79e3275)

**Comment by StephanTLavavej** [comment]
We talked about this at the weekly maintainer meeting and have decided to abandon any attempt to expand test coverage to this exotic scenario. It would increase maintenance effort (and especially test run times), for something that no actual user has ever reported issues with. If any issues are found in the future, we can manually address them if they are on the STL side.
