### ISSUE TITLE
<functional>: Improve performance of function pointer call via std::function

### ISSUE THREAD

**Issue by AlexGuteniev** [microsoft/STL#706]
With `std::function` type erasure, there's always one indirection. 
If functor is not inlined, it causes another indirection. So in example below `f_function` has one indirection and `g_function` two indirections:
```
auto f = [] {
};

void g() {
}

std::function<void()> f_function = f;
std::function<void()> g_function = g;

int main() {
	f_function();
	g_function();
}
```

Indirections impact performance.

But for C function, there's no need in type erasure.

C function is type erasure by itself.

Just save function pointer  in std::function, add another bit of data which calling convention is used, and call that C function using function template parameter type.

Switch dispatch by calling convention is cheaper than indirect function call, especially with `/guard:cf`, which adds double check.

There's a tradeoff: will pay for extra check in case when function object is not C function. 
However this check can be combined with `bad_function_call` check, which is currently present, like:
```
if (is_good_function_object) {
   call_type_erasure_function_object(args)
} else {
   switch (calling_convention) {
   cc: call_cc(args); break;
  default:  throw bad_function_call;
  }
}
```
Another tradeoff is code size. Can be reduced by having such optimization only for the default calling convention, and that 'bad_function_call' is thrown from stub C function:
```
if (is_good_function_object) {
   call_type_erasure_function_object(args)
} else { // default calling convention or empty function
   call_c_function(args); // will also throw bad_alloc: 
   // if function is logically `nullptr`, this would be bad alloc throwing stub
  }
}
```

**Comment by StephanTLavavej** [comment]
Marked as vNext because you're proposing a change outside of the existing type erasure system. Also reworded the title from "C function" to "function pointer", since this doesn't have anything to do with `extern "C"`.

**Comment by sylveon** [comment]
I believe it would make more sense to use something like this

```cpp
template<typename T>
class function {
    static constexpr std::size_t BUFFER_SIZE = 16; // or something
    enum class buffer_content : uint8_t {
        Empty,
        CdeclFuncPtr,
        StdcallFuncPtr,
        FastcallFuncPtr,
        VectorcallFuncPtr,
        SmallObject,
        ObjectPtr
    };

    char buffer[BUFFER_SIZE];
    buffer_content content;
};
```

and then just use a `switch` on `content` in `operator()`.

**Comment by AlexGuteniev** [comment]
Honestly, the above comment was my first thought.

But I'm afraid this would produce quite an amount of code that may not be inlined into the caller for sufficient parameters amount.  So effectively this may cause two calls for every call (albeit the first one is not indirect, so no subject for indirect call penalty, including possible `/guard:cf` penalty.
And even if inlined, it will make significant addition to code size.

So if almost every use of `std::function` are with function object, then the proposed optimization is actually harmful.

That's why I'm thinking of just having two cases as a compromise option. Or maybe this proposal should even be rejected without compromises.

Also, regarding implementing `bad_function_call` as special case of function. It can be implemented as special functor as well, with changing nothing else, i.e. without doing the proposed optimization. This will decrease the amount of code on caller site, comparing to the current. Though this will bloat target binary a bit by having `bad_function_call` functor wrapper for each `std::function` signature, and code decrease on caller site is not much significant.

It is all about tradeoffs, and I'm now leaning to think that `std::function` is good as it is.

**Comment by StephanTLavavej** [comment]
@CaseyCarter has noted that the function pointer's signature, including the return type, would have to exactly match the `std::function` signature, in order for this to be faster. Any conversions on the arguments or return type would require the full power of type erasure. While such exact matching undoubtedly occurs, it seems that optimizing this case at the expense of others doesn't clearly meet the bar for a significant refactoring.

We're going to close this issue, but feel free to reopen it if you find performance data that indicates that this would be a significant improvement.

**Comment by AlexGuteniev** [comment]
I see that for any performance-critical cases, where there is a benefit, workarounds exist:
1. Wrap function pointer with functor, works best if function is inline, but even for non-inline avoids _indirect_ function call: 
```
template<void(*F)()>
struct WrapFPtr {
	void operator()() const { F(); }
};
```
2. Branch on caller site using `std::variant<std::function<Sig>, Sig*>`
