### ISSUE TITLE
LWG-2682 filesystem::copy() won't create a symlink to a directory

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#71]
LWG-2682 `filesystem::copy()` won't create a symlink to a directory

~~Before attempting to implement this, we would like to wait for LWG-3057 "Correct `copy_options` handling" to be resolved.~~

Edit: It doesn't seem that LWG-3057 "Correct `copy_options` handling" will be resolved any time soon. I don't think we need to keep blocking on it.

**Comment by frederick-vs-ja** [comment]
There seems already a branch handling this.
https://github.com/microsoft/STL/blob/994f94199c561a38a4a8e15584030160095bc25a/stl/inc/filesystem#L4327-L4331
