### ISSUE TITLE
Why does atomic_thread_fence work even though it does not use mfence?

### ISSUE THREAD

**Issue by AlexGuteniev** [microsoft/STL#721]
I'm referring to this part:
https://github.com/microsoft/STL/blob/31419650d472932dd24b9c5602707b0454f61fb2/stl/inc/atomic#L1903-L1907

This has been already asked [on SO](https://stackoverflow.com/a/59299167/2945027).
Why I'm not completely satisfied with the answer:
1. The answer points out that `std::atomic_thread_fence` only needs to be synchronized with other atomics, not with everything. This is one part. The remaining part - how exchange is synchronized with other atomics, _including simple loads of other atomics_.
2. The answer is describing the implementation with exchange, I see there's compare exchange already, so probably it is not that simple.

**Comment by AlexGuteniev** [comment]
My understanding that if it is a problem, this piece may be replaced by `mfence`, except a rare config on x86 when _M_IX86_FP is not defined to 2. Even in this rare case, could pick `mfence` at runtime, and have CPU specific fallbacks for pre-SSE2.

**Comment by jonwil** [comment]
Does this code even support versions of Windows that work on CPUs without SSE2?

**Comment by BillyONeal** [comment]
`_InterlockedCompareExchange` is a full `seq_cst` memory barrier, so it certainly meets the standard's requirements. See the Intel Architecture Manual. In the September 2016 copy I have it's at Vol 3A 8-3:

> Locked operations are atomic with respect to all other memory operations and all externally visible events. Only instruction fetch and page table accesses can pass locked instructions

As for 'why not mfence instead', I asked our compiler optimizer folks a few years ago and they said something to the effect of 'I vaguely recall there being some performance reason for this'. ¯\\\_(ツ)\_/¯

**Comment by BillyONeal** [comment]
> Does this code even support versions of Windows that work on CPUs without SSE2?

Yes it does.

**Comment by AlexGuteniev** [comment]
> some performance reason

I do see that difference, and that's why I suspected if faster version is enough.

Well, then I still have question, why `lock cmpxchg` and not `lock inc` or `xchg` (which I think have smaller encoding), but it is of way lower priority (style question, not correctness question), so I'm ok if there's no answer.

**Comment by BillyONeal** [comment]
No idea on that one :)

**Comment by AlexGuteniev** [comment]
Ok, such small decisions like which locked instruction to use if any works, can be for no reason.
You can cite the same answer on SO question, if you're interested (I was impatient on this question, so there's active 200 bounty)
