### ISSUE TITLE
<xhash>: reserve() isn't computing the ceiling properly

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#732]
WG21-N4849 [tab:container.hash.req] says that `a.reserve(n)` should be equivalent to `a.rehash(ceil(n / a.max_load_factor()))`. Our implementation doesn't do that:

https://github.com/microsoft/STL/blob/51446475c15493df1b1e2c0a1b2bc9d36d19fad6/stl/inc/xhash#L1059-L1061

Adding `0.5F` before truncating is completely incorrect. (`1729.25f` plus `0.5f` is `1729.75f` which truncates to `1729`, but the ceiling should be `1730`.) This is the only occurrence of `0.5F` in `<xhash>`.

I believe that the correct fix is to call the `_Min_load_factor_buckets()` helper function:

https://github.com/microsoft/STL/blob/51446475c15493df1b1e2c0a1b2bc9d36d19fad6/stl/inc/xhash#L1769-L1772

(These lines of code will be changed by #730 in the very near future.)

It would be nice, but not critical, to test the behavior difference. Crafting a test might be tricky (because our unordered containers have an invariant that the number of buckets is a power of 2), but should be possible. Perhaps a `reserve()` call that previously would have computed `2048.25f` and then incorrectly produced a "ceiling" of `2048`, whereas the correct code should compute `2048.25f`, ceiling that to `2049`, and then (in the invariant-maintaining logic) increase that to `4096` buckets.

**Comment by BillyONeal** [comment]
Now you have me wondering if I edited this or not when I did the big overhaul of a bunch of _Hash stuff :P

**Comment by babhishek21** [comment]
Can I work on this?

**Comment by CaseyCarter** [comment]
Sure!

**Comment by babhishek21** [comment]
Any pointers on how I should go about writing a test for this? Should I make an entirely new one, or is there a suite which I can just add to?

**Comment by BillyONeal** [comment]
@babhishek21 There's not a super obvious way; figuring out a reasonable test case is part of why this is an issue at all rather than just fixed.

**Comment by babhishek21** [comment]
@BillyONeal Actually, I meant if there are any tests for `reserve()` already, so that I have a base to work off of?

**Comment by BillyONeal** [comment]
@babhishek21 I don't see any obvious test already testing that area; the closest is probably `test_LWG_2156` in `tests\std\tests\Dev09_158181_tr1_unordered_meow_swap\test.cpp`
