### ISSUE TITLE
<mutex>: ~scoped_lock() can use fold expressions

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#738]
`scoped_lock` is C++17 (which supports fold expressions). Currently, its destructor is the only usage of `_For_each_tuple_element` in product code:

https://github.com/microsoft/STL/blob/0cbd1b2470412909b3681902ce0470609d7ae86e/stl/inc/mutex#L465-L467

We define that unconditionally in `<tuple>`, implemented with the `int _Ignored[]` workaround for the absence of fold expressions:

https://github.com/microsoft/STL/blob/0cbd1b2470412909b3681902ce0470609d7ae86e/stl/inc/tuple#L979-L991

We could eliminate lots of machinery here, in addition to using fold expressions. We don't need perfect forwarding (the elements are lvalues) and we don't need a customizable function object (we just need to call `.unlock()`). This will result in less debug codegen and a better debugging experience for anyone who has to step into this logic. This will also emit two fewer function templates for users of `<tuple>` who don't use `<mutex>` at all.

Note that one of our tests is a bad kitty 😼, ~~jumping up on the table where it's not allowed~~ calling STL-internal helper functions when it wasn't absolutely necessary:

https://github.com/microsoft/STL/blob/0cbd1b2470412909b3681902ce0470609d7ae86e/tests/std/tests/VSO_0000000_instantiate_containers/test.cpp#L120-L153

If we eliminate `_For_each_tuple_element` in favor of simpler direct code in `~scoped_lock`, this test will need to be changed (the simplest way being copy-paste-renaming the old helper function into the test).

**Comment by bhardwajs** [comment]
This seems fairly straightforward. Unless someone else is already on it, I can send a PR. Please let me know.

**Comment by StephanTLavavej** [comment]
Please go ahead, I'm looking forward to your PR! :smiley_cat:
