### ISSUE TITLE
P0896R4_P1614R2_comparisons/test.cpp: Remove compiler bug workarounds

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#741]
The compiler bugs that we reported as Microsoft-internal VSO-905257 and VSO-1070391 were resolved as fixed in VS 2019 16.7 Preview 1. When that's available, we should remove the following workarounds in our tests:
https://github.com/microsoft/STL/blob/0cbd1b2470412909b3681902ce0470609d7ae86e/tests/std/tests/P0896R4_P1614R2_comparisons/test.cpp#L261-L277
https://github.com/microsoft/STL/blob/0cbd1b2470412909b3681902ce0470609d7ae86e/tests/std/tests/P0896R4_P1614R2_comparisons/test.cpp#L300-L312
https://github.com/microsoft/STL/blob/0cbd1b2470412909b3681902ce0470609d7ae86e/tests/std/tests/P0896R4_P1614R2_comparisons/test.cpp#L506-L508

**Comment by StephanTLavavej** [comment]
This issue appears to be a superset of #493, except that they disagree about when VSO-905257 was fixed.

**Comment by SuperWig** [comment]
VSO-905257 still fails in preview 1. 
Though the second snippet passes if the static assert in main is removed.

**Comment by SuperWig** [comment]
After actually doing investigation of why that's the case.
The following is what is failing
```cpp
STATIC_ASSERT(test_compare_three_way<long, double, partial_ordering>());
```
And these in constexpr
```cpp
test_partially_ordered(3.14, NaN, partial_ordering::unordered);
test_partially_ordered(3.14f, NaN, partial_ordering::unordered);
test_partially_ordered(3.14, NaNf, partial_ordering::unordered);
```
Worth making a PR with the changes made? Using this issue for the transition comments.

**Comment by StephanTLavavej** [comment]
Thanks for looking into this! I think a PR would let us more easily analyze the remaining failures and what compiler/library issues still need to be fixed.
