### ISSUE TITLE
<execution>: sporadic failure of P0024R2_parallel_algorithms_adjacent_find test

### ISSUE THREAD

**Issue by AlexGuteniev** [microsoft/STL#744]
#684 does not touch `parallel_algorithms`, so it looks like failure is originated from elsewhere

This run:
https://github.com/microsoft/STL/pull/684/checks?check_run_id=612332764

```
2: Test step failed unexpectedly.
2: Command: "D:\build\x86\tests\std\tests\P0024R2_parallel_algorithms_adjacent_find\01\P0024R2_parallel_algorithms_adjacent_find.exe"
2: Exit Code: 3221226505
2: Standard Error:
2: --
2: Assertion failed: less_result == tmp.begin(), file C:\agent\_work\1\s\tests\std\tests\P0024R2_parallel_algorithms_adjacent_find\test.cpp, line 32
2: --
2: 
2: 
2: stl-lit.py: C:\agent\_work\1\s\tests\utils\stl\test\target_info.py:43: warning: The locale Czech_Czech Republic.1250 is not supported by your platform. Some tests will be unsupported.
2: 
2: 1 warning(s) in tests
2: ********************
2: Failing Tests (1):
2:   std :: tests/P0024R2_parallel_algorithms_adjacent_find:01
```

**Comment by AlexGuteniev** [comment]
Are minidumps created on runtime failures? Otherwise this failure may be not very helpful.

**Comment by StephanTLavavej** [comment]
Thanks, I'm marking this as a suspected `bug` unless and until we determine that it's a test-only failure.

> Are minidumps created on runtime failures?

Not yet, see #697.

**Comment by StephanTLavavej** [comment]
I saw another failure in
https://dev.azure.com/vclibs/STL/_build/results?buildId=2825&view=ms.vss-test-web.build-test-results-tab&runId=1005166&resultId=104664&paneView=debug , "#20200430.4 Remove and update compiler bug workarounds (#742)". The assertion was slightly different:

```
Assertion failed: ne_result == tmp.begin(), file C:\agent\_work\1\s\tests\std\tests\P0024R2_parallel_algorithms_adjacent_find\test.cpp, line 33
```

**Comment by AlexGuteniev** [comment]
Same test, different places. Maybe heap corruption or something like this.
Possibly running this one in a loop locally under AppVerifier may help.

**Comment by StephanTLavavej** [comment]
Thanks again for filing this issue, @AlexGuteniev - I'm glad you noticed it!
