### ISSUE TITLE
LWG-2309 mutex::lock() should not throw device_or_resource_busy

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#75]
LWG-2309 `mutex::lock()` should not throw `device_or_resource_busy`

This was fixed in our "WCFB02" vNext branch (which needs to be ported to git).

**Comment by AlexGuteniev** [comment]
working draft still says to throw:
http://eel.is/c++draft/thread.mutex#recursive-3
> If a thread has already acquired the maximum level of ownership for a `recursive_­mutex` object, additional calls to `try_­lock()` fail, and additional calls to `lock()` throw an exception of type `system_­error`.

**Comment by AlexGuteniev** [comment]
To me it is still a bug in the Standard
 * This http://eel.is/c++draft/thread.mutex.requirements.mutex#13 doesn't apply, since it is `recursive_mutex`.
 * Falling back to this http://eel.is/c++draft/thread.mutex.requirements.mutex#4
 * Still neither of the mentioned fits the situation

**Comment by AlexGuteniev** [comment]
Possibly it could be resolved the same way as with `latch`/`semaphore`/`barrier` -- expose `constexpr ptrdiff_t max()` andUB if overrun

**Comment by BillyONeal** [comment]
> To me it is still a bug in the Standard
> 
> * Falling back to this http://eel.is/c++draft/thread.mutex.requirements.mutex#4
> * Still neither of the mentioned fits the situation

For `mutex` (rather than `recursive_mutex`) it is a precondition violation so we can do whatever we want, including the throw that we currently do. But I think `abort` would be better. http://eel.is/c++draft/thread.mutex.requirements#mutex-7
