### ISSUE TITLE
Hi STL. Thank you for your great work for charconv. However, this is my explanation why charconv can never be efficient

### ISSUE THREAD

**Issue by expnkx** [microsoft/STL#754]
https://youtu.be/jTKaC3nshrU?t=1215

**Comment by Cleroth** [comment]
What's the question?

**Comment by expnkx** [comment]
> What's the question?

I think charconv should be removed from standard. same with filesystem, fmt.

**Comment by Cleroth** [comment]
That's not a question. And this is not the place to bring up concerns about the standard.

**Comment by expnkx** [comment]
> That's not a question. And this is not the place to bring up concerns about the standard.

It is a concern since STL wants to contribute this to LLVM. I think he should stop for doing that or better remove it from msvc too to force C++ standard to remove charconv. Leave no compiler supports this.

**Comment by sylveon** [comment]
If you want to get the API changed or removed, the place to look at is https://isocpp.org/std/submit-a-proposal

**Comment by expnkx** [comment]
> If you want to get the API changed or removed, the place to look at is https://isocpp.org/std/submit-a-proposal

Just do not support it and the standard will HAVE to retreat.

Submit a proposal does not solve the problem since I have no-decision. The only thing I would do is to boycott them. Ban them in my projects.

**Comment by expnkx** [comment]
The entire situation would be out of control if we keep allowing standard for accepting horrible stuff like this:
![image](https://user-images.githubusercontent.com/57303909/80340755-3d35d500-882f-11ea-883f-e9888b82441c.png)

**Comment by MikeGitb** [comment]
I really think you should bring your concern to the committee instead of spamming various c++ github repositories. 
And when you do, I recommend you try to be more constructive in your wording. Most of what I've seen so far was just pages and pages of "XYZ is horrible ". Maybe you can rather focus on why another solution is better.

**Comment by expnkx** [comment]
> I really think you should bring your concern to the committee instead of spamming various c++ github repositories.
> And when you do, I recommend you try to be more constructive in your wording. Most of what I've seen so far was just pages and pages of "XYZ is horrible ". Maybe you can rather focus on why another solution is better.

All my friends agree with me on why they are mistakes and will be failure. And I do have another solution. Unfortunately, no one in the standard committee listens to me.

**Comment by Cleroth** [comment]
https://en.wikipedia.org/wiki/Argumentum_ad_populum

**Comment by expnkx** [comment]
> https://en.wikipedia.org/wiki/Argumentum_ad_populum

When did I claim it is a majority or it is right? Your ad populum is out of context.

**Comment by Cleroth** [comment]
Someone said you should be constructive with your arguments, and your response to that is "my friends agree with me." That is argumentum ad populum.

**Comment by miscco** [comment]
@expnkx Please write a paper and have your issues discussed. I did not yet read your proposal on the mailings so the argument "Unfortunately, no one in the standard committee listens to me." is false as you did not speak up yet.

Write a proposal, create a working solution and people will listen. However, just posting on github is not doing you any favors.

**Comment by expnkx** [comment]
> Someone said you should be constructive with your arguments, and your response to that is "my friends agree with me." That is argumentum ad populum.

The entire video I posted here is what is the problem and how to solve a problem. You do not watch it and claim I did not provide a solution. You are false sorry.



> @expnkx Please write a paper and have your issues discussed. I did not yet read your proposal on the mailings so the argument "Unfortunately, no one in the standard committee listens to me." is false as you did not speak up yet.
> 
> Write a proposal, create a working solution and people will listen. However, just posting on github is not doing you any favors.

I have written the proposal before.

https://lists.isocpp.org/std-proposals/att-1039/N_1_problem.pdf

**Comment by expnkx** [comment]
> @expnkx Please write a paper and have your issues discussed. I did not yet read your proposal on the mailings so the argument "Unfortunately, no one in the standard committee listens to me." is false as you did not speak up yet.
> 
> Write a proposal, create a working solution and people will listen. However, just posting on github is not doing you any favors.

I did speak up in multiple places. It is true no one in the standard committee listens to me, or they won't allow the format to be added into the standard.

**Comment by miscco** [comment]
There has been a recent proposal for [byte streams ](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/p2146r0.pdf). You should try to follow their lead and write a similar paper with your ideas.

Just writing Bad!!!!! is not helping

**Comment by expnkx** [comment]
> There has been a recent proposal for [byte streams ](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/p2146r0.pdf). You should try to follow their lead and write a similar paper with your ideas.
> 
> Just writing Bad!!!!! is not helping

I knew Lybetya's work before. 

1. I appreciate his work. However, I have fundamental disagreements with him or Niall Douglas. These people are not talking about how to deal with iostream and cstdio.  Niall Douglas'sone is basically N+1 solution (just like charconv and fmt do) while Lybetya cares about random-access I/O not how to traditional I/O print hello world etc. Lybetya does not think print hello world issue is solvable (because of EBCDIC bullshit.)

2. He just wastes too much time on writing proposals instead of actually implementing the features. Just within half a year, I've implemented 10x features than he does.

3. My library is designed for the future. I have many basic concepts (like implemented cryptography). Unfortunately, I have more and more thoughts when I doing this. They have to be implemented with code as evidence to prove it is working before I could actually propose it as APIs. There are stuff I do not understand like how to do SSL.

I do not want this to be another major failure like charconv is doing here, considering I/O is so fundamental.

**Comment by miscco** [comment]
> These people do not understand how things like iostream work either

This is just an insult and will not get you anywhere. The fact that other people propose solutions that disagree with your opinion does not imply they do not understand something.

Also you should understand that even a *bad* solution is a solution. Your suggestion to delete APIs is eplicititely *not* a solution to anything. The only way forward is to present a *better* solution not ranting about how bad everything is.

**Comment by expnkx** [comment]
"Also you should understand that even a bad solution is a solution. Your suggestion to delete APIs is eplicititely not a solution to anything. The only way forward is to present a better solution not ranting about how bad everything is."

Deleting API is a solution. Deleting gets, auto_ptr, trigraph. Yes, great changes.

**Comment by miscco** [comment]
Yes they were deleted *after* the better solution was in place. You propose to delete them *before* a better solution is in place. One is a way forward the other is a dead end

**Comment by expnkx** [comment]
> Yes they were deleted _after_ the better solution was in place. You propose to delete them _before_ a better solution is in place. One is a way forward the other is a dead end

I am asking to delete something that most compiler does not agree and does not want to implement because it does not worth their effort. Is that a good reason?

I am asking to delete something that is a security vulnerability. Is that a good reason?

**Comment by miscco** [comment]
> I am asking to delete something that most compilers do not agree and do not want to implement because it does not worth their effort like charconv. Is that a good reason?

I do not think that this statement is correct at all. libc++ sounds quite interested in charconv and MSVC obviously is.
 
> I am asking to delete something that is a security vulnerability like filesystem. Is that a good reason?
No. You would not only break an incredible amount of code but even worse create way *more* security vulnerabilities as people would have to implement by themself something even the commitee has a hard time specifying. This would be a terrible degradation of status quo

> Those stuffs should not be added into standard in the first place.
That is you opinion. The majority of the commitee seems to disagree

**Comment by expnkx** [comment]
> > I am asking to delete something that most compilers do not agree and do not want to implement because it does not worth their effort like charconv. Is that a good reason?
> 
> I do not think that this statement is correct at all. libc++ sounds quite interested in charconv and MSVC obviously is.

They don't. If they are interested in it, they would implement charconv before MSVC stl would do that.

I have private emails with libstdc++'s tamer Jonathan Wakely before, he agrees with me.


> 
> > I am asking to delete something that is a security vulnerability like filesystem. Is that a good reason?
> > No. You would not only break an incredible amount of code but even worse create way _more_ security vulnerabilities as people would have to implement by themself something even the commitee has a hard time specifying. This would be a terrible degradation of status quo
> 
> > Those stuffs should not be added into standard in the first place.

That is you opinion. The majority of the commitee seems to disagree

https://en.wikipedia.org/wiki/Argumentum_ad_populum

**Comment by StephanTLavavej** [comment]
Please stop submitting off-topic issues.
