### ISSUE TITLE
<xstring>: Too many enabled hash specializations

### ISSUE THREAD

**Issue by CaseyCarter** [microsoft/STL#757]
Per the standard, the specializations:
```c++
template<> struct hash<string>;
template<> struct hash<u8string>;
template<> struct hash<u16string>;
template<> struct hash<u32string>;
template<> struct hash<wstring>;
template<> struct hash<pmr::string>;
template<> struct hash<pmr::u8string>;
template<> struct hash<pmr::u16string>;
template<> struct hash<pmr::u32string>;
template<> struct hash<pmr::wstring>;

template<> struct hash<string_view>;
template<> struct hash<u8string_view>;
template<> struct hash<u16string_view>;
template<> struct hash<u32string_view>;
template<> struct hash<wstring_view>;
```
Should be enabled, and all other specializations of `hash` for specializations of `basic_string_view` / `basic_string` should be disabled. We currently enable `hash` for all specializations of `basic_string_view`:

https://github.com/microsoft/STL/blob/852a3085906108045a3951064baaf4952f596e9e/stl/inc/xstring#L1715-L1724

and `basic_string`:

https://github.com/microsoft/STL/blob/852a3085906108045a3951064baaf4952f596e9e/stl/inc/xstring#L4579-L4588

**Additional Context**
Skipped libcxx test 
https://github.com/microsoft/STL/blob/06827feb4cdc4d2328dfbfab9fd5302de6058dd9/tests/libcxx/expected_results.txt#L640-L642

**Comment by CaseyCarter** [comment]
> Per the standard, the specializations:

This notably excludes `basic_string` specializations with allocator types other than `std::allocator` even if they have reasonable character and traits types. `basic_string<char, char_traits<char>, my_allocator<char>>`, for example, should be hashable despite the nonstandard allocator: the character encoding has nothing to do with the allocator. I'll poke LWG about this.

**Comment by CaseyCarter** [comment]
> I'll poke LWG about this.

I don't know if this ever happened, but I did just submit an LWG issue to change the explicit specializations of `hash` for `basic_string` to partial specializations that don't depend on allocator type.

**Comment by StephanTLavavej** [comment]
I'm OK with making this change now (at the beginning of the 17.4 cycle) and then implementing the LWG issue once it's accepted (or at least Tentatively Ready). There's no ABI or separately compiled impact, so we aren't locking ourselves into a decision, and if it's a widely breaking change, we should hear about it early (including from RWC coverage). What the Standard currently says is clear and internally consistent, so our usual rule is to do what the Standard says, even if it might be changed to be less restrictive in the future. (Vaguely similar precedent would be how `uniform_int_distribution<unsigned char>` is forbidden.)

**Comment by frederick-vs-ja** [comment]
At the first time cppreference mentioned LWG-2978, I was surprised to find that the resolution was not generalized to all possible allocators. Providing specializations for `pmr` types strongly implies that the difference of memory resources should be ignored when hashing, so I have no idea why the resolution was restricted to strings with `polymorphic_allocator`.

LWG-2978 also mentioned an alternative approch, but it was not adopted.
> An alternative approach, for which wording can be produced if desired, is to make the hash specializations for `basic_string` allocator-agnostic, similar to the partial specialization of hash for `vector<bool>`.

Asking @timsong-cpp why wasn't the alternative approch proposed.

**Comment by CaseyCarter** [comment]
> Asking @timsong-cpp why wasn't the alternative approach proposed.

From [LWG's internal discussion on the Toronto wiki](https://wiki.edg.com/bin/view/Wg21toronto2017/LWGMondayAM#LWG2978), LWGChair was of the opinion that doing so would be a design change beyond the mandate of "making sure all the `pmr` types are hashable" that they were working on at the time. I would have argued differently had I been in the room (think I was in LEWG working on Ranges NB comments).

In any case, the current LWG chair seems to agree with me that the change is a good consistency fix (after mocking me for the issue title "hashability shouldn't depend on **`basic_string_view`'s** allocator", of course 🤦‍♂️).
