### ISSUE TITLE
Should always follow C++ memory model, or should conditionally optimize for x86 / x64 / ARM / ARM64 reality ?

### ISSUE THREAD

**Issue by AlexGuteniev** [microsoft/STL#766]
In my atomic wait PR two memory fences are not needed due to how x86 / x64 works. But in terms of C++ memory model they are needed. And I cannot disprove them on ARM.

Third memory fence does not make sense according to the memory model (superfluous ordering for that case), but does some optimization (earlier visibility of a store).

The reason is that some actual guarantees made by platform are stronger than required by C++ standard.

The question - is this ok to rely on platform guarantees instead of C++:

 - While using `std::atomic` ?
 - While using intrinsic functions directly ?

**Comment by MikeGitb** [comment]
Are those guarantees also obeyed by the compiler? Wouldn't help, if the processor doesn't reorder reads and writes, but the compiler does.

**Comment by AlexGuteniev** [comment]
@MikeGitb , there's `_Compiler_barrier()` which costs almost nothing, comparing to extra memory bariers due to C++ model.

**Comment by AlexGuteniev** [comment]
A somewhat different example but still in the area of what I'm asking about:
https://github.com/microsoft/STL/blob/852a3085906108045a3951064baaf4952f596e9e/stl/src/parallel_algorithms.cpp#L92-L94

Could have done the same without this assumption, but assumption simplifies expressing this.

**Comment by MikeGitb** [comment]
Why do the memory barriers cost anything when they only state what the architecture is doing anyway?

**Comment by MikeGitb** [comment]
That aside I (as a random user) certainly would welcome optimizations that make use of platform specific knowledge if they are safe.

**Comment by AlexGuteniev** [comment]
I'm talking for example about `std::atomic_thread_fence(std::memory_order_seq_cst)` which would emit an expensive instruction.

**Comment by AlexGuteniev** [comment]
And that `std::atomic_thread_fence(std::memory_order_seq_cst)` can be omitted in reality because the next intrinsic would effectively do the same memory barrier.

**Comment by StephanTLavavej** [comment]
We can make platform-specific assumptions, and should for efficiency in the case of `<atomic>` whose whole purpose is speed, but they should be properly commented, and we need to be correct for all supported architectures - so if you're uncertain about ARM/ARM64 you should have strong fences, to be removed only when you can absolutely prove that they are unnecessary.

**Comment by jonwil** [comment]
Is it not OK to do the fast bit on x86/x64 if its safe to do so and do the known-safe slower thing on ARM/ARM64?

**Comment by AlexGuteniev** [comment]
> Is it not OK to do the fast bit on x86/x64 if its safe to do so and do the known-safe slower thing on ARM/ARM64?

I don't see a problem. I may be did not clarify, but meant I saw the fence on ARM in that place is needed, not that "I'm not sure".

ARM has too different performance characteristics anyway, so making changes in different optimizations here is not expected to add too much on top of that.

**Comment by AlexGuteniev** [comment]
For the particular case which made me ask the question, I'm proposing the documentation change to document fencing behavior of API MicrosoftDocs/sdk-api/pull/226 , then the fence is not needed at all.

If it is still needed (and thus the documentation change is invalid), then I'll comment both why it is avoided on x86 / x64, and why it is not avoided on ARM / ARM64.
