### ISSUE TITLE
<yvals_core.h>: Update _MSVC_STL_UPDATE to May 2020

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#777]
Explanation on our wiki: [Macro `_MSVC_STL_UPDATE`](https://github.com/microsoft/STL/wiki/Macro-_MSVC_STL_UPDATE)

Code:
https://github.com/microsoft/STL/blob/2f4c5792b2be4f56b4130817803ca21f7a3ee8f4/stl/inc/yvals_core.h#L486

Previous issue: #670

This issue is intended for a new contributor (especially one new to GitHub) to get started with the simplest possible change.

**Comment by Nishikoh** [comment]
I'd like to tackle this issue.

**Comment by CaseyCarter** [comment]
> I'd like to tackle this issue.

Please do!
