### ISSUE TITLE
tests: Enable /BE (EDG) coverage

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#799]
We should enable our test coverage for the `/BE` compiler option (activating the EDG front-end used for IntelliSense). This is currently disabled by [`tests/utils/stl/test/tests.py`](https://github.com/microsoft/STL/blob/master/tests/utils/stl/test/tests.py); we'll need additional changes to handle `/BE`'s special behavior. (For example, `/BE` doesn't perform codegen, so these are inherently compile-only configurations.)

This issue is for EDG imitating MSVC; #704 tracks EDG imitating Clang.

**Comment by cbezault** [comment]
This isn't disabled. I just add an `edg` requirement on tests which use the `/BE` flag. If we're targeting `x86` I mark them as enabled in `tests/utils/stl/test/config.py`.

**Comment by StephanTLavavej** [comment]
This was implemented by #682.
