### ISSUE TITLE
<algorithm>, <deque>: Use `_Next_iter(it)` and `_Prev_iter(it)` instead of `it + 1` and `it - 1`

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#802]
Sequel issue to #465 (thanks to https://github.com/microsoft/STL/issues/465#issuecomment-624181951 ).

We have helper functions that are simplified forms of `std::next` and `std::prev`:

https://github.com/microsoft/STL/blob/65d98ffabab3a95d79255f741daa1230692e8066/stl/inc/xutility#L1763-L1766

https://github.com/microsoft/STL/blob/65d98ffabab3a95d79255f741daa1230692e8066/stl/inc/xutility#L1778-L1781

We also have various algorithms, working with random-access iterators, that are saying `it + 1` and `it - 1`. It may be more efficient to use `_Next_iter`/`_Prev_iter` for user-defined iterators where incrementing/decrementing are cheaper than general-purpose addition/subtraction.

Known occurrences found by @CaseyCarter in https://github.com/microsoft/STL/issues/465#issuecomment-624278608 :

https://github.com/microsoft/STL/blob/430b569d0a5157d7c95251668fc4607041bdf907/stl/inc/algorithm#L1546

https://github.com/microsoft/STL/blob/430b569d0a5157d7c95251668fc4607041bdf907/stl/inc/algorithm#L1626

https://github.com/microsoft/STL/blob/430b569d0a5157d7c95251668fc4607041bdf907/stl/inc/algorithm#L3763

https://github.com/microsoft/STL/blob/430b569d0a5157d7c95251668fc4607041bdf907/stl/inc/algorithm#L3765

https://github.com/microsoft/STL/blob/430b569d0a5157d7c95251668fc4607041bdf907/stl/inc/algorithm#L3795-L3796

https://github.com/microsoft/STL/blob/430b569d0a5157d7c95251668fc4607041bdf907/stl/inc/deque#L1274

Note A: This issue isn't about replacing occurrences of `++it` and `--it`; those should remain unchanged.

Note B: The following occurrences of `_Backout._Last - 1` are working with raw pointers, where `_Prev_iter` won't provide a performance advantage. Known raw pointers shouldn't be changed:

https://github.com/microsoft/STL/blob/430b569d0a5157d7c95251668fc4607041bdf907/stl/inc/algorithm#L3468-L3471

https://github.com/microsoft/STL/blob/430b569d0a5157d7c95251668fc4607041bdf907/stl/inc/algorithm#L3502-L3506

**Comment by JeanPhilippeKernel** [comment]
I was going to consider leaving this issue since you marked it 'good first issue' for the new contributor coming on the project, but since it is a continuation of my PR I would like to finish it 😁

**Comment by StephanTLavavej** [comment]
Sounds good! :cat:
