### ISSUE TITLE
README.md: Clarify Python Configuration

### ISSUE THREAD

**Issue by mnatsuhara** [microsoft/STL#806]
In [How To Run The Tests With A Native Tools Command Prompt](https://github.com/microsoft/STL/#how-to-run-the-tests-with-a-native-tools-command-prompt), step 3 says 
> Acquire Python 3.8 or newer.

However, the configuring step (step 10 in [How To Build With A Native Tools Command Prompt](https://github.com/microsoft/STL/#how-to-build-with-a-native-tools-command-prompt)) which says 
> Invoke `cmake -G Ninja -DCMAKE_TOOLCHAIN_FILE={where your vcpkg clone is located}\scripts\buildsystems\vcpkg.cmake -S . -B {wherever you want binaries}` to configure the project. For example, `cmake -G Ninja -DCMAKE_TOOLCHAIN_FILE=C:\Dev\vcpkg\scripts\buildsystems\vcpkg.cmake -S . -B out\build\x64`

appears several paragraphs above the instructions of how to run tests.  If Python 3.8 is not already installed when the configuration step is completed, it is likely that the user will need to reconfigure in order for CMake to be able to find the correct Python executable.  It would be good to mention that possibility following the "Acquire Python..." step.

**Comment by cbezault** [comment]
Would it be sufficient to hard fail in the configure step if you don't have a new enough version of Python?

**Comment by mnatsuhara** [comment]
That seems like a viable option.  In that case, I think we should also update step 1 of [How To Build With A Native Tools Command Prompt](https://github.com/microsoft/STL/#how-to-build-with-a-native-tools-command-prompt) to include installing Python 3.8 along with CMake, Ninja, and VS 2019.

**Comment by AlexGuteniev** [comment]
Is #2103 enough?

**Comment by mnatsuhara** [comment]
Yes, I think moving up that mention of Python in the README addresses this.  I'm closing this issue -- thanks for following up here!
