### ISSUE TITLE
<execution>: Consider commenting the _Results._Complete() control flow

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#818]
See the bugfix #816. After that change, we'll have 8 occurrences of the exact same pattern:
https://github.com/microsoft/STL/blob/11150ca6679507461ae9f64e90c678c498cfe908/stl/inc/execution#L1291-L1298
(`_Static_partitioned_mismatch2::_Process_chunk()` is very slightly different, testing `_Results._Storage._Complete()`.)

Trying to centralize this pattern into a helper function ended up degrading codegen, so it remains repeated. We should consider adding a comment to each occurrence, mentioning the surprisingly subtle control flow here. I don't immediately know what it should say - perhaps a high-level explanation that we have to check `_Complete()` before calling `_Get_next_key()` because if we successfully obtain a `_Key`, we're responsible for reporting its result and can't simply drop that work on the floor.

**Comment by AlexGuteniev** [comment]
> Trying to centralize this pattern into a helper function ended up degrading codegen, so it remains repeated.

can you use preprocessor?

**Comment by StephanTLavavej** [comment]
We could, but in recent years we've been trying to avoid "convenience" macros, reserving preprocessor use only when it's really important (typically configuration, or stamping out ridiculously repetitive code with no good Core Language solutions). When macros conceal control flow, it becomes extremely hard to see the logical structure of the code.

**Comment by AlexGuteniev** [comment]
I can imagine a macro that doesn't distort any control flow:

```
// This macro does nothing. It serves as a reminder that once _Key is obtained,
// the amount of work should not be discarded, unless _Key is evaluated as false.
// Thus, return due to cancellation token should be done before obtaining _Key.
#define _CHUNK_MUST_BE_USED(_Key)
```

Usage:
```
    _Cancellation_status _Process_chunk() {
        if (_Cancel_token._Is_canceled()) {
            return _Cancellation_status::_Canceled;
        }

        const auto _Key = _Team._Get_next_key();
        if (!_Key) {
            return _Cancellation_status::_Canceled;
        }
        _CHUNK_MUST_BE_USED(_Key)

        const auto _Range = _Basis._Get_chunk(_Key);
        for (auto _First = _Range._First; _First != _Range._Last; ++_First) {
            if (_Pred(*_First) ? _Invert : !_Invert) {
                _Cancel_token._Cancel();
                return _Cancellation_status::_Canceled;
            }
        }

        return _Cancellation_status::_Running;
    }
```
