### ISSUE TITLE
<xutility>: Teach _Equal_memcmp_is_safe about contiguous iterators and ranges::equal_to

### ISSUE THREAD

**Issue by CaseyCarter** [microsoft/STL#819]
The `_Equal_memcmp_is_safe` machinery in `<xutility>` determines when comparisons in algorithms can be optimized in terms of `memcmp` rather than using a simple loop. That machinery is activated in a very limited set of circumstances, currently only for iterators of pointer type using `std::equal_to` to compare elements of integral type. To provide parity for the `ranges` algorithms, this machinery needs to understand `std::ranges::equal_to`. To provide a better experience for `ranges`, this machinery also needs to activate for `contiguous_iterator`s that aren't pointers.

**Comment by miscco** [comment]
Can I have a look at it?

**Comment by CaseyCarter** [comment]
> Can I have a look at it?

Sure!

**Comment by miscco** [comment]
The fact that everything is based on `bool_type` and then checking for `decltype(_Equal_memcmp_is_safe<>)::type` is that due to historical reasons?

If so should we move to template variables when touching this?

**Comment by StephanTLavavej** [comment]
That's an excellent point - yes, I believe that this metaprogramming predates our ability to use variable templates, so we should modernize this unless an obvious reason appears. (We had to report a *lot* of compiler bugs to a *lot* of compilers before VTs became safe to use. `clang-format` still dislikes VTs, but at least they work now. :crying_cat_face: )
