### ISSUE TITLE
Build: Check for absence of magic statics

### ISSUE THREAD

**Issue by AlexGuteniev** [microsoft/STL#823]
Easiest way could be to enumerate PE directory list to check for TLS directory absence, or enumerate sections to check for .tls section absence.

More complicated but giving better diagnostics is to enumerate debug information to locate thread local and magic static varaibles. Debug information could be enumerated using [DbgHelp functions](https://docs.microsoft.com/en-us/windows/win32/debug/dbghelp-functions) or [DIA SDK](https://docs.microsoft.com/en-us/visualstudio/debugger/debug-interface-access/debug-interface-access-sdk?view=vs-2019) (these are the same APIs, except that DIA SDK is object-oriented; object-orientation is helpful, since with DbgHelp it may be confusing which handle is for what)

**Comment by AlexGuteniev** [comment]
TLS directory entry seem to be simplest solution, and also the most direct, since it check specifically for TLS presence. `.tls` section is a sort of implementation detail, and symbols analysis is testing for possible causes instead of testing for the issue directly.

It can be implemented using `MapViewOfFile` and `ImageDirectoryEntryToDataEx` with `IMAGE_DIRECTORY_ENTRY_TLS`

**Comment by AlexGuteniev** [comment]
Apparently, this check has to be done for STL binaries, and each of test binaries to make it reliable

**Comment by CaseyCarter** [comment]
I'm not sure how much value this would add given that we build the STL and tests with [`/Zc:threadSafeInit-`](https://docs.microsoft.com/en-us/cpp/build/reference/zc-threadsafeinit-thread-safe-local-static-initialization?view=vs-2019) (which disables magic statics) and `/w14640 /WX` so the compiler will treat dynamic initialization of function-local statics as an error.

**Comment by AlexGuteniev** [comment]
Then probably it is not needed. Checking for TLS will also make sure that no `__delcspec(thread)` or `thread_local` is used, but it is hard to type these keywords accidentally.

**Comment by StephanTLavavej** [comment]
Yeah, those would be very apparent during code review, unlike invisible magic statics.

Since I believe that our existing compiler options, mentioned by @CaseyCarter, are sufficient, I'm going to go ahead and close this issue. Thanks for the suggestion, and we can always revisit this if the compiler options prove to be insufficient.
