### ISSUE TITLE
STL: Should the macros `_CSTD`/`_STD`/`_RANGES` be replaced by their expansions?

### ISSUE THREAD

**Issue by CaseyCarter** [microsoft/STL#825]
These macros don't seem to buy us much over simply using their expansions `::`, `::std::`, and `::std::ranges::`. They save a few keystrokes - -4, 2, and 7 for `_CSTD`, `_STD`, and `_RANGES`, respectively - but it's not as if we'd ever define them differently.

**Comment by StephanTLavavej** [comment]
I recall that we did end up defining `_STD` differently, when we tried using inline namespaces in the old vNext branch.

I especially like `_STD` because the difference between `std::` and `::std::` is very subtle and easy to miss, yet important for the STL. `_CSTD` doesn't have that particular problem, but `_CSTD` is still more prominent than `::`.

I think that if we had *perfect* automation to discover missing qualification, then I would be much more willing to drop the macros (and in general I am not a fan of macros, and have removed many relatively unnecessary ones from the STL). However, since that automation doesn't exist, I am strongly in favor of keeping the macros.

**Comment by AlexGuteniev** [comment]
How do you see difference between `std::` and `::std::`? By something like this?
```
namespace wrong_std_lives_here { struct std {}; }
using namespace wrong_std_lives_here;
```

Then I think you have a test where you include each header alone, possibly the same test with force-including (via compilers switch) a header with breaking std would help to test.

**Comment by CaseyCarter** [comment]
>  By something like this?

Close - that unfortunately makes `namespace std` ill-formed. A nested namespace works, though (https://godbolt.org/z/D8qKhA):
```c++
namespace X::std { }
using namespace X;

namespace std {
    void f(int) {}
    template <class T>
    void g(T t) {
#ifdef BAD
        std::f(t); // ill-formed due to ambiguity
#else
        ::std::f(t); // Ok
#endif
    }
}
```

**Comment by AlexGuteniev** [comment]
Got it. So you can detect lack of prefix `::` by compiling each file with force including `namespace X::std { } using namespace X;` , right?

**Comment by AlexGuteniev** [comment]
Yes, there's even no need for force include.
Just add to this .cpp:
https://github.com/microsoft/STL/blob/46ae5f8234c3306c60cd3c9ae3fb44829d692bc0/tests/std/tests/Dev11_0000000_include_each_header_alone/test.cpp#L1-L8

(I've added and looks like there are a lot of failures)

**Comment by AlexGuteniev** [comment]
Everything fails outside STL even:
```
In file included from C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.26.28801\include\vcruntime_new_debug.h:10:
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.26.28801\include\vcruntime_new.h(117,5): error: reference to 'std' is ambiguous
    std::align_val_t _Al
    ^
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.26.28801\include\vcruntime_new.h(33,15): note: candidate found by name lookup is 'std'
    namespace std
              ^
```

**Comment by AlexGuteniev** [comment]
So if we include SDK headers earlier, we can get somewhere. Almost working version of test:

```
#include <vcruntime_new.h>
#include <pplinterface.h>
#include <ppltasks.h>
#include <new.h>

namespace X::std {}
using namespace X;

#define MEOW_ANGLE(X) <X>

#include MEOW_ANGLE(MEOW_HEADER)

int main() {} // COMPILE-ONLY
```

Only two failures.

**Comment by AlexGuteniev** [comment]
Honestly this problem concerns me far less than, like, atomics and lightweight synchronization primitives. I wouldn't imagine myself defining in my project something non-standard and still called `std`.

Having this problem occurring in various SDK headers, seems like that it has the same severity for the most of users.

**Comment by AlexGuteniev** [comment]
See #830

**Comment by StephanTLavavej** [comment]
Should we resolve this now?

**Comment by CaseyCarter** [comment]
Yes, it looks like there wasn't much discussion to be had. Feel free to reopen with new information.
