### ISSUE TITLE
<numeric>: Consider avoiding <limits> inclusion

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#832]
Currently, `<numeric>` includes `<limits>` in C++20 mode:

https://github.com/microsoft/STL/blob/46ae5f8234c3306c60cd3c9ae3fb44829d692bc0/stl/inc/numeric#L13-L15

`<limits>` is a relatively large header (potentially affecting compiler throughput, i.e. slowing down builds), but our usage is very limited here - we just need floating-point min/max:

https://github.com/microsoft/STL/blob/46ae5f8234c3306c60cd3c9ae3fb44829d692bc0/stl/inc/numeric#L640-L641
https://github.com/microsoft/STL/blob/46ae5f8234c3306c60cd3c9ae3fb44829d692bc0/stl/inc/numeric#L675

`<numeric>` always includes `<xutility>` which includes `<climits>`:
https://github.com/microsoft/STL/blob/46ae5f8234c3306c60cd3c9ae3fb44829d692bc0/stl/inc/numeric#L11
https://github.com/microsoft/STL/blob/46ae5f8234c3306c60cd3c9ae3fb44829d692bc0/stl/inc/xutility#L12

So `<numeric>` could directly use the classic macros:
https://github.com/microsoft/STL/blob/46ae5f8234c3306c60cd3c9ae3fb44829d692bc0/stl/inc/limits#L872-L878
https://github.com/microsoft/STL/blob/46ae5f8234c3306c60cd3c9ae3fb44829d692bc0/stl/inc/limits#L921-L927
https://github.com/microsoft/STL/blob/46ae5f8234c3306c60cd3c9ae3fb44829d692bc0/stl/inc/limits#L970-L976

Specifically, the changes in `<numeric>` I'm envisioning are:
1. Stop including `<limits>`.
2. Define a helper variable template `_Floating_min<_Ty>`, specialized for `float`, `double`, and `long double`.
3. Similarly define `_Floating_max<_Ty>`.
4. Replace the `numeric_limits` calls with uses of the variable templates. Note that because users could theoretically pass `volatile` values, the uses should say `remove_cv_t<_Ty>`; `numeric_limits` was previously handling that:

https://github.com/microsoft/STL/blob/46ae5f8234c3306c60cd3c9ae3fb44829d692bc0/stl/inc/limits#L108-L118

**Comment by StephanTLavavej** [comment]
@CaseyCarter observed that there's another `<limits>` dependency that I forgot about, `_Countr_zero`, after we merged #665:

https://github.com/microsoft/STL/blob/46ae5f8234c3306c60cd3c9ae3fb44829d692bc0/stl/inc/numeric#L566-L568

https://github.com/microsoft/STL/blob/46ae5f8234c3306c60cd3c9ae3fb44829d692bc0/stl/inc/limits#L1015-L1032

This is also used by `<bit>`:

https://github.com/microsoft/STL/blob/46ae5f8234c3306c60cd3c9ae3fb44829d692bc0/stl/inc/bit#L116-L124

We could move `_Countr_zero` up to `<xtr1common>`, after appropriately replacing the usage of `numeric_limits<_Ty>::digits`; hopefully that would improve throughput overall, but I'm not 100% certain.

**Comment by miscco** [comment]
My first candidate for the `_Countr_zero` Funktion actually was xtr1common but when I saw the limits usage I went for limits

**Comment by StephanTLavavej** [comment]
#795 has merged, so the analysis here needs to be updated.
