### ISSUE TITLE
Tests: stop disabling warning 5105: "macro expansion producing 'defined' has undefined behavior"

### ISSUE THREAD

**Issue by barcharcraz** [microsoft/STL#854]
**Describe the bug**
When we test with /Zc:preprocessor we disable warning 5105: "macro expansion producing 'defined' has undefined behavior" because it's emitted by the windows SDK. We should stop doing that once windows no longer emits this warning.

This is tracked by OS-26212942 internally

**Comment by MikeGitb** [comment]
Any ETA on when the windows SDK can be expected to be /Zc:preprocessor clean?

**Comment by StephanTLavavej** [comment]
We don’t have an ETA, but they’re working on it.

**Comment by StephanTLavavej** [comment]
Still repros with WinSDK 19041 but should be fixed in a future release.

**Comment by StephanTLavavej** [comment]
No longer repros with Windows 11 SDK 22000 and the OS bug has been resolved. I'll attempt to remove this workaround in the next toolset update.
