### ISSUE TITLE
call_once no longer behaves the same in c++20 mode

### ISSUE THREAD

**Issue by eklipse2k8** [microsoft/STL#859]
**Describe the bug**
When the compiler is set to c++17 mode **call_once** will execute its block synchronously. However in c++20 it seems to skip the lambda. Is this a bug or a change in behavior? 

```c++
  static bool HasInternetConnection() noexcept {
    static ConnectionProfile profile = nullptr;
    static std::once_flag flag = {};
    std::call_once(flag, [&]() {
      profile = NetworkInformation::GetInternetConnectionProfile();
      });
    return profile.GetNetworkConnectivityLevel() == NetworkConnectivityLevel::InternetAccess;
  }
```

**Expected behavior**
call_once executes lambda before proceeding to the next line.

**STL version**
```
Microsoft Visual Studio Community 2019 Preview
Version 16.7.0 Preview 1.0
```

**Comment by CaseyCarter** [comment]
If I compile this program:
```c++
#include <chrono>
#include <mutex>

using namespace std::literals;

namespace {
    int f() {
        static int x = 1;
        static std::once_flag flag = {};
        std::call_once(flag, [] {
            std::this_thread::sleep_for(10s);
            x = 0;
        });
        return x;
    }
}

int main() { return f(); }
```
with x86-host x86-target 16.7p1 `cl /std:c++latest /EHsc`, it runs for 10 seconds (on Windows 10 Home v19041) and returns an exit status of `0` as expected. Does it behave differently for you?

Could you provide a similarly minimal repro that does demonstrate the the behavior you observe?

**Comment by eklipse2k8** [comment]
Ok this is weird, after playing around with it some more, it appears moving it to a toplevel namespace gets it to work again.

In this namespace it's failing to call the lambda
```c++
namespace winrt::MyTestApp::Core::implementation
{ ... }
```

In this namespace, it works!
```c++
namespace winrt
{ ... }
```

Looks like maybe a compiler bug?

**Comment by CaseyCarter** [comment]
This program:
```c++
#include <chrono>
#include <mutex>

using namespace std::literals;

namespace winrt::MyTestApp::Core::implementation {
    int f() {
        static int x = 1;
        static std::once_flag flag = {};
        std::call_once(flag, [] {
            std::this_thread::sleep_for(10s);
            x = 0;
        });
        return x;
    }
}

int main() { return winrt::MyTestApp::Core::implementation::f(); }
```
continues to reliably function as expected. I suspect that there's a variable somewhere we're not accounting for. Can you provide a minimal program and command line (and/or VS project) that reproduces the problem behavior?
