### ISSUE TITLE
tests: Consider using only CTest, dropping lit (except for its test format)

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#867]
@cbezault mentioned that the Python-powered lit test infrastructure is a significant cost for test throughput, and that we should consider using CTest by itself, keeping only the lit test format. This is a tracking issue for such an overhaul.

I've been invoking `stl-lit.py` directly, but as long as we retain the ability to run arbitrary test subdirectories, and to capture output in log files, I think increased test throughput would be awesome. :rocket:

**Comment by cbezault** [comment]
I've explored this and believe that there _could_ be some advantage to using CTest and CMake directly to run the tests but there is a huge amount of complexity overhead to getting there. It would be a bespoke and fragile solution. Unless we have a business reason to run the tests even faster than they are already going it would appear that we are at a happy medium of complexity and performance.
