### ISSUE TITLE
Should I manually fclose after using a FILE* to construct std::basic_filebuf?

### ISSUE THREAD

**Issue by expnkx** [microsoft/STL#871]

**Comment by CaseyCarter** [comment]
Yes, you should - but not until after the lifetime of the `basic_filebuf` ends. `basic_filebuf` expects the original `FILE*` to stay valid.

**Comment by expnkx** [comment]
> Yes, you should - but not until after the lifetime of the `basic_filebuf` ends. `basic_filebuf` expects the original `FILE*` to stay valid.

Should I call close in a move? Is this code correct?

https://github.com/expnkx/fast_io/blob/465d509f283ed88dbcadf84f16f47e6c8d48df8d/include/fast_io_legacy_impl/cpp/filebuf_file.h#L183

**Comment by CaseyCarter** [comment]
> Should I call close in a move?

`basic_filebuf` needs the `FILE*` to stay valid until the `basic_filebuf` is `close`d, destroyed, or move-assigned-to. When the `basic_filebuf` no longer needs the `FILE*` to be valid you can/should `fclose` that `FILE*`.

> Is this code correct?
If `fb` is the only data member - which it appears to be - then all of these special member function definitions:

https://github.com/expnkx/fast_io/blob/465d509f283ed88dbcadf84f16f47e6c8d48df8d/include/fast_io_legacy_impl/cpp/filebuf_file.h#L176-L189

are extraneous. They're equivalent to the special member functions the compiler would implicitly define for that class.

**Comment by expnkx** [comment]
> > Should I call close in a move?
> 
> `basic_filebuf` needs the `FILE*` to stay valid until the `basic_filebuf` is `close`d, destroyed, or move-assigned-to. When the `basic_filebuf` no longer needs the `FILE*` to be valid you can/should `fclose` that `FILE*`.
> 
> > Is this code correct?
> > If `fb` is the only data member - which it appears to be - then all of these special member function definitions:
> 
> https://github.com/expnkx/fast_io/blob/465d509f283ed88dbcadf84f16f47e6c8d48df8d/include/fast_io_legacy_impl/cpp/filebuf_file.h#L176-L189
> 
> are extraneous. They're equivalent to the special member functions the compiler would implicitly define for that class.

So I still need a destructor to call .close() but I do not need to write copy and move right?

**Comment by CaseyCarter** [comment]
> So I still need a destructor to call .close() but I do not need to write copy and move right?

`basic_filebuf` calls `close` in its destructor already. The issue is that `basic_filebuf::close` does not `fclose` the `FILE*` when it is initialized from a `FILE*`: it "borrows" the `FILE*` rather than taking ownership.

**Comment by expnkx** [comment]
> > So I still need a destructor to call .close() but I do not need to write copy and move right?
> 
> `basic_filebuf` calls `close` in its destructor already. The issue is that `basic_filebuf::close` does not `fclose` the `FILE*` when it is initialized from a `FILE*`: it "borrows" the `FILE*` rather than taking ownership.

What I want is to make filebuf takes over the FILE*. Should I do a fclose in move operations?

**Comment by expnkx** [comment]
> > So I still need a destructor to call .close() but I do not need to write copy and move right?
> 
> `basic_filebuf` calls `close` in its destructor already. The issue is that `basic_filebuf::close` does not `fclose` the `FILE*` when it is initialized from a `FILE*`: it "borrows" the `FILE*` rather than taking ownership.

I tried close after calling .close() and the program immediately crashes why?

**Comment by expnkx** [comment]
> > So I still need a destructor to call .close() but I do not need to write copy and move right?
> 
> `basic_filebuf` calls `close` in its destructor already. The issue is that `basic_filebuf::close` does not `fclose` the `FILE*` when it is initialized from a `FILE*`: it "borrows" the `FILE*` rather than taking ownership.

https://github.com/expnkx/fast_io/commit/c8708bea2b9084e4e1be9b82713414b0fd6b87bd

**Comment by CaseyCarter** [comment]
> > > So I still need a destructor to call .close() but I do not need to write copy and move right?
> > 
> > 
> > `basic_filebuf` calls `close` in its destructor already. The issue is that `basic_filebuf::close` does not `fclose` the `FILE*` when it is initialized from a `FILE*`: it "borrows" the `FILE*` rather than taking ownership.
> 
> What I want is to make filebuf takes over the FILE*.

That's not how our extension works. It seems to be intended to be used only for temporarily creating a C++ facade to wrap around a `FILE*` for a few quick operations, not for long-lived `basic_filebuf`s. There isn't even a simple way to recover the `FILE*` from the `basic_filebuf` so you can `fclose` it yourself.

I think your `basic_filebuf_file` needs to keep both a `basic_filebuf` and the original `FILE*` around - nulling the `FILE*` in moved-from objects but otherwise having it "follow" the `basic_filebuf` when moved - so it can `fclose` the `FILE*` when not `NULL` in its destructor.

**Comment by expnkx** [comment]
> > > > So I still need a destructor to call .close() but I do not need to write copy and move right?
> > > 
> > > 
> > > `basic_filebuf` calls `close` in its destructor already. The issue is that `basic_filebuf::close` does not `fclose` the `FILE*` when it is initialized from a `FILE*`: it "borrows" the `FILE*` rather than taking ownership.
> > 
> > 
> > What I want is to make filebuf takes over the FILE*.
> 
> That's not how our extension works. It seems to be intended to be used only for temporarily creating a C++ facade to wrap around a `FILE*` for a few quick operations, not for long-lived `basic_filebuf`s. There isn't even a simple way to recover the `FILE*` from the `basic_filebuf` so you can `fclose` it yourself.
> 
> I think your `basic_filebuf_file` needs to keep both a `basic_filebuf` and the original `FILE*` around - nulling the `FILE*` in moved-from objects but otherwise having it "follow" the `basic_filebuf` when moved - so it can `fclose` the `FILE*` when not `NULL` in its destructor.

I can guarantee you are wrong.

https://github.com/microsoft/STL/blob/7447ad59d61f50c13861878f340d051c298458df/stl/inc/fstream#L199

This proves std::filebuf in MSVC STL does call std::fclose in the .close() method.

Taking another FILE* is nonsense since I hacked all mainstream C FILE* and C++ filebuf implementation. I can directly hack FILE* from it.

https://github.com/expnkx/fast_io/blob/master/include/fast_io_legacy_impl/cpp/fp_hack/msvc_stl.h
