### ISSUE TITLE
Release notes for Preview 2 missing

### ISSUE THREAD

**Issue by mgoldshteyn** [microsoft/STL#876]
The Microsoft page for Release 19 Preview 2 refers to github for release notes, but there are no release notes for Preview 2 in GitHub:

## Visual Studio 2019 version 16.7 Preview 2
C++
New C++20 Standard Library features have been implemented. Please refer to the STL Changelog on GitHub for a detailed list.

See: [Visual Studio 2019 Preview Release Notes](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-preview#16.7.0-pre-2.0)

**Comment by cbezault** [comment]
We only started splitting out our changelog on a per-preview basis starting with 16.8. Moving forward this shouldn't be an issue. @StephanTLavavej, @CaseyCarter, we decided we weren't going to back-port the decision to start recording on a per-preview basis but maybe we should for 16.7?

**Comment by AlexGuteniev** [comment]
I'd suggest adding a note about 16.7 that it was not tracked on per-preview basis.

(And also a TOC of major versions. Or a quick link to latest release version. Since if I'm looking for 16.6, which is latest non-preview, I want to jump into the middle)

**Comment by StephanTLavavej** [comment]
@AlexGuteniev - Thanks, I've updated the Changelog to add a Table of Contents as you suggested, as it was indeed getting unwieldy. I also added a note to 16.7 that it wasn't recorded per-Preview.

@cbezault - I have no objection to someone doing the source control archaeology to split up the 16.7 changes per-Preview. Looks like there's demand for it! :smiley_cat:

**Comment by CaseyCarter** [comment]
We discussed this in our weekly meeting, and the general impression is that the value added by splitting older ChangeLog entries per-preview release isn't worth the source archaeology. We wouldn't refuse to update the ChangeLog if someone were to do that work, but we would prefer to invest that effort elsewhere.
