### ISSUE TITLE
Lambda capture incorrect (by value)

### ISSUE THREAD

**Issue by stevemk14ebr** [microsoft/STL#885]
**Describe the bug**
When executing the lambda at https://github.com/stevemk14ebr/PolyHook_2_0/blob/410c6088433a21eeaead49401e63186b9d3e7c3f/sources/x64Detour.cpp#L161 in x64-ReleaseWithDebugInfo settings the static local variable has the wrong value. I've verified in a debugger that the values appear to be ok, but during execution the wrong addres is printed.

Initial capture: 
![image](https://user-images.githubusercontent.com/6619205/84042872-9edf7800-a973-11ea-859a-bc4573578289.png)

Capture at the callsite:
![image](https://user-images.githubusercontent.com/6619205/84042940-b3bc0b80-a973-11ea-9b57-41e4e7d982c6.png)

Execution:
![image](https://user-images.githubusercontent.com/6619205/84042978-bdde0a00-a973-11ea-9721-82e1b3473c7f.png)

Notice the the printed address is NOT the same as the value for jmpHolderCurAddress which my debugger screenshots show is what is correctly captured.

```
auto calcJmpHolder = [=] () -> uint64_t {
	static uint64_t captureAddr = jmpHolderCurAddr;
	std::cout << std::hex << "captured: " << captureAddr << std::endl;
	captureAddr -= destHldrSz;
	std::cout << std::hex << captureAddr << " max:" << (m_trampoline + m_trampolineSz) << std::dec << std::endl;
	assert(captureAddr > (uint64_t)m_trampoline && (captureAddr + destHldrSz) < (m_trampoline + m_trampolineSz));
	return captureAddr;
};
```

**Expected behavior**
I expect the captured value to print the correct value. Instead some other erroneous address is printed.

**STL version**
```
Microsoft Visual Studio Community 2019
Version 16.6.1
```

**Additional context**
I debugged this at the assembly level. The erroneous address comes from a function called 'lambda_<randomnumber>::operator()::`2::captureAddr. This is executed inside the code:

```
// Line 1410 <functional>
template <class _Ret, size_t... _Ix, class _Cv_FD, class _Cv_tuple_TiD, class _Untuple>
auto _Call_binder(_Invoker_ret<_Ret>, index_sequence<_Ix...>, _Cv_FD& _Obj, _Cv_tuple_TiD& _Tpl, _Untuple&& _Ut)
    -> decltype(_Invoker_ret<_Ret>::_Call(
        _Obj, _Fix_arg(_STD get<_Ix>(_Tpl), _STD move(_Ut))...)) { // bind() and bind<R>() invocation
    return _Invoker_ret<_Ret>::_Call(_Obj, _Fix_arg(_STD get<_Ix>(_Tpl), _STD move(_Ut))...);
}
```

Callstack:
![image](https://user-images.githubusercontent.com/6619205/84050586-ec5fe300-a97b-11ea-9a05-409bccf0840e.png)

The callsite moving the wrong value to print, look at the mov rdx, qword ptr line, which results in RDX being printed (incorrect value):
![2](https://user-images.githubusercontent.com/6619205/84050711-15807380-a97c-11ea-9c65-58bebe2a284c.png)

At that point the debugger showed the following, notice the jmpHolderCurAddress is a different value that from what is printed to the console at the top of the screenshot and that the printed value matches the value of RDX:
![image](https://user-images.githubusercontent.com/6619205/84050834-42348b00-a97c-11ea-8873-aabafbb87f78.png)

I am not sure what ::captureAddress is, but it is not the correct value to be passed. Instead RDX should be set to the jmpHolderCurAddress value that is stored in _Obj.

**Comment by stevemk14ebr** [comment]
I was able to work around this by using a mutable lambda:

```
const auto makeJmpFn = [=, captureAddress=jmpHolderCurAddr](uint64_t a, uint64_t b) mutable {
	std::cout << std::hex << "captured: " << captureAddress << std::endl;
	captureAddress -= destHldrSz;
	std::cout << std::hex << captureAddress << " max:" << (m_trampoline + m_trampolineSz) << std::dec << std::endl;
	assert(captureAddr > (uint64_t)m_trampoline && (captureAddr + destHldrSz) < (m_trampoline + m_trampolineSz));
	return makex64MinimumJump(a, b, captureAddress);
};
```

The following code exhibits the same incorrect behavior however:
```
const auto makeJmpFn = [=](uint64_t a, uint64_t b) mutable {
	static uint64_t captureAddr = jmpHolderCurAddr;
	std::cout << std::hex << "captured: " << captureAddr << std::endl;
	captureAddr -= destHldrSz;
	std::cout << std::hex << captureAddr << " max:" << (m_trampoline + m_trampolineSz) << std::dec << std::endl;
	assert(captureAddr > (uint64_t)m_trampoline && (captureAddr + destHldrSz) < (m_trampoline + m_trampolineSz));
	return makex64MinimumJump(a, b, captureAddr);
};
```
![image](https://user-images.githubusercontent.com/6619205/84052560-bff99600-a97e-11ea-9851-090fff2a5ef3.png)

**Comment by StephanTLavavej** [comment]
Can you reduce this to a self-contained test case (single file and corresponding command line) so we can investigate the root cause? It looks like you're calling `std::bind`, but I don't immediately see whether there's a compiler bug, library bug, or bug in your code.

**Comment by stevemk14ebr** [comment]
I've tried to create a standalone test case and failed. The code I linked to is the exact commit code that fails and is what my images are of. This lamda is only triggered on a very specific code path in my application, and when it does take that path is only triggered by certain compiler release modes. I can provide the failing binary with associated symbols as well as directions on how to build if that's at all useful.

What is the ::captureAddress data member I see being loaded from. Based on what I see the compiler has transformed my lambdas into functions that load the captures. If I understood this transformation I could debug this better.

**Comment by StephanTLavavej** [comment]
Ok, this sounds like an optimizer bug then (as it's dependent on release mode; compiler front-end and library bugs are *generally* insensitive to optimizations). Can you file a bug on [Developer Community](https://developercommunity.visualstudio.com/spaces/62/index.html)? They'll accept a zipped IDE project.

**Comment by stevemk14ebr** [comment]
So i spent more time debugging the assembly and finally figured out the cause and can repro it isolated. I _think_ this is a bug can you tell me if this is expected? The erroneous address i am seeing is the value of the local static from the previous execution of the function. From what i understand the lambda should be a newly created function each execution, therefore the local static should only hold state within it's parent scope functions lifetime (makeLambda). What i am instead seeing is that the local static behaves as if the lambda was written as a completely normal function at global scope that existed the lifetime of the application.

```
// LambdaBugRepro.cpp : This file contains the 'main' function. Program execution begins and ends there.
//

#include <iostream>
#include <functional>
#include <vector>

using namespace std::placeholders;
inline std::vector<uint64_t> makeMinJump(uint64_t a, uint64_t b, uint64_t c) {
    std::vector<uint64_t> blah;
    blah.push_back(a);
    blah.push_back(b);
    blah.push_back(c);
    return {};
}

template<typename T>
std::vector<uint64_t> relocateTramp(uint64_t a, uint64_t b, uint64_t c, uint64_t d, T lambda) {
    volatile uint64_t blah = 0;
    blah += a;
    return lambda(a, b);
}

void makeLambda() {
    const uint8_t sz = 1;
    const uint64_t bad = 1337;
    auto calcJmpHolder = [=]() -> uint64_t {
        static uint64_t captureAddr = bad;
        captureAddr -= sz;
        std::cout << captureAddr << std::endl;
        return captureAddr;
    };

    const auto makeJmpFn = std::bind(makeMinJump, _1, _2, std::bind(calcJmpHolder));
    relocateTramp(1, 3, 3, 8, makeJmpFn);
}

int main()
{
    std::cout << "Hello World!\n";
 
    makeLambda();
    makeLambda();
    makeLambda();
    

    std::cout << "done" << std::endl;
    getchar();
}
```

Outputs:
```
Hello World!
1336
1335
1334
done
```

**Comment by CaseyCarter** [comment]
This is not a bug in the STL nor the compiler(s), this is a bug in your program. Each occurrence of a lambda expression in program text defines a distinct function object type; it is _not_ the case that each evaluation of a lambda expression returns a distinct type with its own set of static variables. The behavior you are witnessing is intended.

**Comment by stevemk14ebr** [comment]
Looking at how this was compiled i see why this is the case. I just found it confusing based ont he semantics of how lambda captures work, seems like a leaky abstraction. Thank you for confirming this.
