### ISSUE TITLE
<cmath>: Missing "sufficient additional overloads" for mathematical special functions

### ISSUE THREAD

**Issue by CaseyCarter** [microsoft/STL#910]
Per the discussion in LWG-3234, the [mathematical special functions](http://eel.is/c++draft/sf.cmath) _should_ have [[cmath.syn]/2](http://eel.is/c++draft/cmath.syn#2) overloads but don't due to editorial oversight. We should implement such overloads.

We should also:
* Update Boost.Math
* Write a short paper to remove [cmath.syn]/2 and declare actual overloads in the synopsis.

Related to #519. Probably related to #2112.

Also tracked by Microsoft-internal VSO-945789 / [AB#945789](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/945789).

**Comment by StephanTLavavej** [comment]
Also tracked by Microsoft-internal VSO-945789. In that bug, you mentioned:

> While you're at it:
> * Update Boost.Math
> * Write a short paper to remove [cmath.syn]/2 and declare actual overloads in the synopsis.

**Comment by frederick-vs-ja** [comment]
[P1467R9](https://wg21.link/p1467r9) (approved by CWG recently) also requires these overloads, effectively resolving LWG-3234.

**Comment by CaseyCarter** [comment]
> [P1467R9](https://wg21.link/p1467r9) (approved by CWG recently) also requires these overloads, effectively resolving [LWG-3234](https://cplusplus.github.io/LWG/issue3234).

As near as I can tell - assuming that the placeholder _floating-point_ is intended to have the same meaning in `<cmath>` as the paper specifies it to have in `<charconv>` - P1467R9 requires overloads of each mathematical special function that accept-and-return each supported floating-point type. It notably doesn't specify changes to the wording of `[cmath.syn]/2` to cover the mathematical special functions. AFAICS this proposal is completely orthogonal to LWG-3234.
