### ISSUE TITLE
Debug visualizers: std::any natvis extensions

### ISSUE THREAD

**Issue by JVApen** [microsoft/STL#929]
**Describe the bug**
The visualizer for std::any ain't that useful. Except knowing how something is stored into it, and the type info for the stored class, it is almost impossible to inspect what's into it.

I've already managed to extend the natvis with the following
```
<Item Name="[castable_ptr]" Condition="_Is_trivial()">(void*)(&amp;_Storage._TrivialData)</Item>
          <Item Name="[castable_ptr]" Condition="_Is_small()">(void*)(&amp;_Storage._SmallStorage._Data)</Item>
          <Item Name="[castable_ptr]" Condition="_Is_big()">(void*)(_Storage._BigStorage._Ptr)</Item>
```

This improved the usability a lot and has a lot of sense to add to the upstream project. Ideally, one would cast this to the actual type, however, I'm not sure that's even possible.

All details can be found in my stackoverflow post, see https://stackoverflow.com/questions/59285956/using-stdtype-info-for-casting-in-natvis

**Command-line test case**
```
C:\Temp>type repro.cpp
#include <any>

int main() {
    std::any a = 0;
}

C:\Temp>cl /EHsc /W4 /WX .\repro.cpp
```

**Expected behavior**
Be able to inspect the content of std::any in an easy way

**STL version**
Microsoft Visual Studio 2019, exact version not relevant

**Additional context**
https://stackoverflow.com/questions/59285956/using-stdtype-info-for-casting-in-natvis

**Comment by StephanTLavavej** [comment]
Thanks for filing this. Related to #349 in the sense that if `stl.natvis` were in this repo, we could accept pull requests for it.

**Comment by creadmefford** [comment]
+1 thanks for opening this.

**Comment by CaseyCarter** [comment]
We should file a suggestion ticket on DevCom to ask for Debugger support to enable this. We're not excited about getting into the  custom visualizer business, we'd prefer for the debugger folks to do so.

**Comment by AnjuDel** [comment]
I filed this into de [devcom](https://developercommunity.visualstudio.com/t/Make-std::any-natvis-extensions-more-use/1380848?viewtype=all&space=62&entry=myfeedback)

**Comment by StephanTLavavej** [comment]
Thanks @AnjuDel! We'll close this issue as "external" as the debugger needs to take action here.

**Comment by JVApen** [comment]
@StephanTLavavej Can the `[castable_ptr]` still be added, awaiting the extension to the natvis protocol?

**Comment by StephanTLavavej** [comment]
Yeah, I think that would be an improvement over the status quo (because finding which of the 3 modes is active, is not easy to do), although I don't know how self-explanatory `[castable_ptr]` would be; perhaps a different name could be more self-explanatory although I can't immediately think of one.
