### ISSUE TITLE
<filesystem>: Avoid additional allocations in path::lexically_relative

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#937]
See: https://github.com/microsoft/STL/pull/923#discussion_r447107800

#923 is implementing LWG-3070 (#333) by iterating through `_Path.relative_path()`. This can allocate memory for each element (which is also a `path`). Avoiding that would improve performance, but we need to carefully verify that directly inspecting the native string has the same behavior.

**Comment by DailyShana** [comment]
I'd like continue this after merging #923

**Comment by StephanTLavavej** [comment]
Great! @CaseyCarter has prepared an MSVC-PR to merge into the internal repo, so we should be able to merge it today. (Someday, this additional step of mirroring might not be necessary, after we've migrated all of our test coverage and can somehow generate binaries directly from this repo.)
