### ISSUE TITLE
<algorithm>: Sort _Guess_median_unchecked comment is inaccurate

### ISSUE THREAD

**Issue by BillyONeal** [microsoft/STL#94]
Andrei Alexandrescu reports that this should be called "Tukey's ninther" rather than "median of 9".

(I'm filing this as an issue because I want to make this change after we can work normally in GitHub; it isn't worth going through a dual-commit process for)

**Comment by andralex** [comment]
"Median of medians" is confusing because that's the name of a different algorithm. "Tukey's ninther" is searchable and yields good results.

**Comment by StephanTLavavej** [comment]
I stand corrected, thank you.
