### ISSUE TITLE
<valarray>: slice_array's copy ctor is missing, the same with mask_array, gslice_array, indirect_array

### ISSUE THREAD

**Issue by AlexGuteniev** [microsoft/STL#940]
**Describe the bug**
slice_array's copy constructor and assignment operator are missing

**Command-line test case**
```
d:\Temp2>type repro.cpp
#include <valarray>
#include <cassert>

int main()
{
        int a1[] = { 0, 1, 2 };
        std::valarray<int> v1(a1, 3);
        std::slice_array<int> s1 = v1[std::slice(1, 1, 1)];
        std::slice_array<int> s2 = v1[std::slice(0, 1, 1)];
        std::slice_array<int> const& s3 = s1 = s2;
        std::slice_array<int> s4 = s3;
        assert(&s1 == &s3);
        assert(&s1 == &s4);
}

d:\Temp2>cl /EHsc /W4 /WX .\repro.cpp
Microsoft (R) C/C++ Optimizing Compiler Version 19.27.29009.1 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

repro.cpp
Microsoft (R) Incremental Linker Version 14.27.29009.1
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:repro.exe
repro.obj
repro.obj : error LNK2019: unresolved external symbol "public: __thiscall std::slice_array<int>::slice_array<int>(class std::slice_array<int> const &)" (??0?$slice_array@H@std@@QAE@ABV01@@Z) referenced in function _main
repro.obj : error LNK2019: unresolved external symbol "public: class std::slice_array<int> & __thiscall std::slice_array<int>::operator=(class std::slice_array<int> const &)" (??4?$slice_array@H@std@@QAEAAV01@ABV01@@Z) referenced in function _main
repro.exe : fatal error LNK1120: 2 unresolved externals
```

**Expected behavior**
Microsoft Visual Studio Professional 2019 Preview
Version 16.7.0 Preview 3.1

**Additional context**
The operators are intentionally not defined.
https://github.com/microsoft/STL/blob/3f6c715563a665748e3e97c163c61bec6f025f17/stl/inc/valarray#L941-L943

According to cppreference, both [copy constructor](https://en.cppreference.com/w/cpp/numeric/valarray/slice_array/slice_array) and [assignment operator](https://en.cppreference.com/w/cpp/numeric/valarray/slice_array/operator%3D) should be defined.

It confirms with [`[template.slice.array.overview]`](https://eel.is/c++draft/template.slice.array.overview)

This item is also tracked on Developer Community as DevCom-1075574 and by Microsoft-internal VSO-109266 / [AB#109266](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/109266).

The same problem is tracked on Developer Community as DevCom-246260 and by Microsoft-internal VSO-366115 / [AB#366115](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/366115).

The same problem with `mask_array` is tracked on Developer Community as DevCom-1075573.

**Comment by StephanTLavavej** [comment]
Thanks, especially for the de-duplication! I've linked the Microsoft-internal bugs to this issue.

**Comment by AlexGuteniev** [comment]
The issue is slightly more complex than I originally anticipated. 
Copy constructors are trivial.
But assignments require implementation.

**Comment by AlexGuteniev** [comment]
Though if don't try to optimize, it is still easy.

**Comment by AlexGuteniev** [comment]
@msalehmsft , there are three VSO links and only two AB links, was this an intention?

**Comment by StephanTLavavej** [comment]
That was me (followed by robo-@msalehmsft's hyperlink edit). The third VSO bug had already been closed as a duplicate so I didn't think it was worth linking. I just went ahead and removed that citation to avoid confusion. Thanks!
