### ISSUE TITLE
How do I provide different configuration sets for different CPU architectures in tests?

### ISSUE THREAD

**Issue by statementreply** [microsoft/STL#954]
I'm working on test coverage for #935, which contains numerical algorithm. It is desirable to test with different compiler and runtime configurations that could affect floating point behavior. The relevant options differ by CPU architecture.

For example, `/arch: IA32` is only available on x86, while `/arch:VFPv4` is only available on ARM. `/link loosefpmath.obj` is meaningless with `/arch:IA32`, while `/link fp10.obj` is only meaningful with `/arch:IA32`.

How do I setup a different set of configurations to test for each CPU architecture?

**Comment by StephanTLavavej** [comment]
We have some machinery in the test harness that @cbezault wrote which detects the undocumented compiler option `/BE` (that activates the EDG front-end), which is available only for x86 at this time. The test machinery has the concept of "features", and contains code that notes that the `"edg"` feature is available only for the x86 architecture. This is what skips `/BE` test configurations for x64 test runs. I believe it should be possible to extend this machinery, teaching it about the availability of compiler options like `/arch:IA32` and `/arch:VFPv4` on different architectures. Please let us know if you'd like help with this.

**Comment by cbezault** [comment]
See [here](https://github.com/microsoft/STL/blob/5ef22f2a884706442257cea3dd9d5a6186f15c07/tests/utils/stl/test/tests.py#L43) and [here](https://github.com/microsoft/STL/blob/5ef22f2a884706442257cea3dd9d5a6186f15c07/tests/utils/stl/test/config.py#L131).

**Comment by StephanTLavavej** [comment]
Thanks, Curtis! Inline code snippets:
https://github.com/microsoft/STL/blob/5ef22f2a884706442257cea3dd9d5a6186f15c07/tests/utils/stl/test/tests.py#L37-L43
https://github.com/microsoft/STL/blob/5ef22f2a884706442257cea3dd9d5a6186f15c07/tests/utils/stl/test/config.py#L130-L131
