### ISSUE TITLE
<yvals_core.h>: Update _MSVC_STL_UPDATE to July 2020

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#962]
Explanation on our wiki: [Macro `_MSVC_STL_UPDATE`](https://github.com/microsoft/STL/wiki/Macro-_MSVC_STL_UPDATE)

Code:
https://github.com/microsoft/STL/blob/5ef22f2a884706442257cea3dd9d5a6186f15c07/stl/inc/yvals_core.h#L490

Previous issue: #895

This issue is intended for a new contributor (especially one new to GitHub) to get started with the simplest possible change.

**Comment by morrme** [comment]
Thank you so much for making tasks like this available for newcomers!

I am new to this project but not to GitHub. I will subscribe just in case no one comes along 😄

**Comment by God-father1** [comment]
Can I work on this issue ?, I'm new to opensource and willing to contribute.

**Comment by God-father1** [comment]
Created my first ever Opensource contribution [PR](https://github.com/microsoft/STL/pull/989).
