### ISSUE TITLE
Should STL try to avoid introducing standard identifiers without corresponding header included?

### ISSUE THREAD

**Issue by AlexGuteniev** [microsoft/STL#963]
See https://github.com/microsoft/STL/pull/795#discussion_r448140737

**Comment by StephanTLavavej** [comment]
The implementation acts contrary to such a goal whenever it defines machinery in centralized headers for maintainer convenience:

https://github.com/microsoft/STL/blob/5e3423a3772827283193f997f221a138a310d1ac/stl/inc/xtr1common#L41-L46

And when headers include other headers:

https://github.com/microsoft/STL/blob/5e3423a3772827283193f997f221a138a310d1ac/stl/inc/tuple#L11-L13

The latter can have significant throughput consequences in addition to identifier cleanliness, and we've reduced some of that over time.

I tend to feel that identifier cleanliness can't really be achieved without modules so it's futile to try, although it is worth investigating and mitigating significant throughput impacts (e.g. avoid including `<animals>` when we only need `std::tiny_kitten`).

We should definitely make a decision though. Thanks for filing this.

**Comment by BillyONeal** [comment]
I don't think we could reasonably achieve this before modules.

**Comment by BillyONeal** [comment]
I've attempted to do something like this before and we were forced to back it out because way too many things broke; for example this is why `<string>` drags in `<cctype>` even though nothing in `<string>` uses that.

**Comment by StephanTLavavej** [comment]
We talked about this at the weekly maintainer meeting and concluded that this is indeed not feasible - we need far too many bits of the STL to implement other components, and providing `_Ugly` machinery that mirrors Standard machinery would result in duplication, debug codegen bloat, and throughput reductions.

Standard Library Modules will be disciplined about exporting *only* Standard machinery (and only in `namespace std` for the `import std;` module), although the `std` and `std.compat` modules export *everything* from `array` to `zip`.
