### ISSUE TITLE
xutility: Style inconsistency in the usage of "requires(" and "requires ("

### ISSUE THREAD

**Issue by mydeveloperday** [microsoft/STL#982]
**Describe the bug**
I'm using STL as test input to add support for concepts into clang-format (https://reviews.llvm.org/D79773)

In headers conepts/random/span and xutility there is sometimes inconsistency about whether there is space after the "requires" and before the "("

$ grep "requires (" * | wc -l
39
$ grep "requires(" * | wc -l
147

It would help us to ensure clang-format is ready to format concepts, if the code could be made consistent, this will help minimize the diffs.

**Expected behavior**
I presume you'd want to follow what you have with "noexcept("

**STL version**
as of trunk (2f4c579)

**Additional context**
If testing clang-format I generally remove all // clang-format off first by doing

sed -i 's/clang-format/cf/g' xutility

This would be a very simple issue for someone who is starting out could look at.

**Comment by StephanTLavavej** [comment]
@CaseyCarter, what’s your preference here? @mydeveloperday is working on your most wanted clang-format feature 😸

**Comment by CaseyCarter** [comment]
There are two different occasions where `requires` appears in the source followed by `(`:
1. The `requires` that introduces a _requires-expression_ when followed by its optional parenthesized _requirement-parameter-list_:
   > _requires-expression_:
   >     `requires` _requirement-parameter-list_<sub>opt</sub> _requirement-body_
   >
   > _requirement-parameter-list_:
   >     `(` _parameter-declaration-clause_<sub>opt</sub> `)`

   These are intended to have no space between `requires` and `(` in our conventional style in an attempt to match the style of a parenthesized _parameter-declaration-clause_ in a function declarations as closely as possible. 

2. The `requires` that introduces a _requires-clause_ in a _template-head_ or trailing after a _function-declarator_ is followed by a _constraint-logical-or-expression_:
   > _requires-clause_:
   >     `requires` _constraint-logical-or-expression_

   The grammar of _constraint-logical-or-expression_ is restricted to _primary-expression_ s conjoined with `&&` disjoined with `||` to avoid parsing ambiguities that would appear if a full _logical-or-expression_ were allowed in this position. Consequently it is often the case that some non-_primary-expression_ must be enclosed in parentheses to produce a _primary-expression_ for use in a _constraint-logical-or-expression_. There should be a space in our conventional style between the `requires` that introduces a _requires-clause_ and its _constraint-logical-or-expression_ whether that _constraint-logical-or-expression_ is parenthesized or not to emphasize the fact that this `requires` and the `requires` in #1 have completely different function despite being spelled identically.

**Comment by CaseyCarter** [comment]
I audited all 316 occurrences of `requires` followed by `(` to ensure they follow my stated rules above. We were fairly consistent in product code - only 2 fixes needed - and wildly inconsistent in test code.

**Comment by mydeveloperday** [comment]
Thanks for the explanation, that sounds like we might need to add
additional clang-formatting options to match your suggestion of them being
handled differently.

MyDeveloperDay
