### ISSUE TITLE
<valarray>: Avoid control flow in macro

### ISSUE THREAD

**Issue by AlexGuteniev** [microsoft/STL#991]
https://github.com/microsoft/STL/blob/5be7d49c243979231dff35919d3a3d813d75d714/stl/inc/valarray#L1094-L1124

Consider converting to a function that takes lambda or manually re-using the code.
Motivation: easier debugging (step by step or crash dump).

Occurrences:
https://github.com/microsoft/STL/blob/5be7d49c243979231dff35919d3a3d813d75d714/stl/inc/valarray#L60-L72
https://github.com/microsoft/STL/blob/5be7d49c243979231dff35919d3a3d813d75d714/stl/inc/valarray#L874-L879
https://github.com/microsoft/STL/blob/5be7d49c243979231dff35919d3a3d813d75d714/stl/inc/valarray#L1014-L1020
https://github.com/microsoft/STL/blob/5be7d49c243979231dff35919d3a3d813d75d714/stl/inc/valarray#L1094-L1102
https://github.com/microsoft/STL/blob/5be7d49c243979231dff35919d3a3d813d75d714/stl/inc/valarray#L1192-L1197

**Comment by StephanTLavavej** [comment]
Strongly agreed! We've moved away from using such "convenience macros" in our implementation for the reasons you mentioned and more (e.g. IDEs find it harder to understand the code when there are more macros).

Simply expanding each occurrence wouldn't be too bad; editors are very good at making repetitive edits these days (and it's not like `<valarray>` undergoes frequent edits anyways). Alternatively, centralizing this machinery into templates with lambdas would be reasonable, but we'd want to make sure that optimizers can still deal with the resulting code - e.g. MSVC doesn't usually see through data members.

**Comment by AlexGuteniev** [comment]
@statementreply mentioned it is clearly UB to overlap ranges for some operations. And for some others it is not defined, so should probably be UB too.

Would be good to add pragma loop ivdep here as well.
